### ISSUE TITLE
[QUESTION] How to correctly add custom lookup file function?

### ISSUE THREAD

**Issue by qhuyduong** [doomemacs/doomemacs#1791]
I'm trying to add a custom file lookup function under `enh-ruby-mode` using
`(set-lookup-handlers! 'enh-ruby-mode :file #'my-custom-function)`.
However it looks like my custom function is never called by `+lookup/file`. It just show the `Find file or URL` prompt right away.
Could you please help?

**Comment by hlissner** [comment]
`+lookup/file` is a bit rigid and needs to be rewritten to respect `:file`. I'll look into this soon.
