### ISSUE TITLE
[BUG] Rust - Strange error UI

### ISSUE THREAD

**Issue by rakanalh** [doomemacs/doomemacs#2151]
**Describe the issue**
When viewing a rust file with errors, placing the cursor at one of the errors displays a popup which looks broken.

![DeepinScreenshot_select-area_20191205001510](https://user-images.githubusercontent.com/195829/70189802-8eb0bc80-16f4-11ea-9c41-42af50c019ab.png)
![DeepinScreenshot_select-area_20191205001852](https://user-images.githubusercontent.com/195829/70189904-d59eb200-16f4-11ea-963d-081b685fd265.png)

Not sure what additional information i could give, it's a UI issue as appearing in the screenshots and i think it's caused by lsp-ui provided that rustic-mode depends on lsp generally.

**Steps to reproduce**
1. Select these example steps,
2. Delete them,
3. And replace them with precise steps to reproduce your issue.
4. Fill in "system information" below.

**System information**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2")
  (build . "Aug 29, 2019")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD a8fd59a05 2019-12-03 22:56:33 -0500"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/zsh")
  (uname . "Linux 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64")
  (path "~/.pyenv/plugins/pyenv-virtualenv/shims" "~/.pyenv/shims" "~/.pyenv/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/usr/local/git/bin" "/usr/local/go/bin" "/opt/sm/bin" "/opt/sm/pkg/active/bin" "/opt/sm/pkg/active/sbin" "platform-tools/" "/bin" "~/Code/Go/bin" "~/.bin;~/.cargo/bin" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra modeline nav-flash ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :tools editorconfig (eval +overlay) flycheck (lookup +docsets) magit :lang data emacs-lisp go javascript lua markdown (org +dragndrop +ipython +pandoc +present) (python +pyenv) rust sh solidity :config (default +bindings +smartparens))
  (packages "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by MuhannadAlrusayni** [comment]
I'm not sure how to fix this but I use `+childframe` and lsp-ui-sideline-enable is nil:
``` el
;; init.el
(flycheck
 +childframe)

;; config.el
;; lsp
(after! lsp-ui
  (setq lsp-ui-sideline-enable nil))
```
and I don't have the issue you got:
![لقطة شاشة من 2019-12-09 20-59-11](https://user-images.githubusercontent.com/14802524/70460267-fa18d680-1ac6-11ea-9bd4-f943b5c20cd7.png)

**Comment by rakanalh** [comment]
Thanks @MuhannadAlrusayni, i added `+childframe` feature to the `flycheck` module and it looks uniform like in your screenshot.
