### ISSUE TITLE
Directory local variables not evaluated for fundamental-mode.

### ISSUE THREAD

**Issue by Janfel** [doomemacs/doomemacs#2493]
**What did you expect to happen?**
I have a `.dir-locals.el` like this:
```emacs-lisp
((fundamental-mode
  (eval let ((auto-mode-alist '(("\\.zsh_\\'" . sh-mode)
                                ("\\.ztxt\\'" . sh-mode))))
        (set-auto-mode))))
```
When I open a `.zsh_` file (which defaults to `fundamental-mode`), I expect `sh-mode` to activate.

**What actually happened?**
The mode stays `fundamental-mode`, until I execute `hack-local-variables` or explicitly call `fundamental-mode`. At this point, the mode changes to `sh-mode`.

**Additional details:**
- In the sandbox, the issue is reproducible with `C-c C-p` (Doom + modules - config) but not with `C-c C-d` (Vanilla Doom).

**Steps to reproduce:**
1. Create a `.dir-locals.el` file like this:
```emacs-lisp
((fundamental-mode
  (eval let ((auto-mode-alist '(("\\.xyz\\'" . c-mode))))
   (set-auto-mode))))
```
2. Create an `example.xyz` file like this:
```c
#include stdio.h

int main() {
    int some = example("code");
}
```
3. Start Doom from the sandbox with `C-c C-p`.
4. Open `example.xyz`.
5. The mode will be `fundamental-mode`.
6. Run `M-x fundamental-mode`.
7. The mode will be `c-mode`.

**System information:**
<details>

```
emacs   version    26.3
        features   XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
        build      Aug 29, 2019
        buildopts  (--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now)
        windowsys  x
        daemonp    server-running
doom    version    2.0.9
        build      HEAD -> develop, origin/develop, origin/HEAD 2c536cf94 2020-01-23 17:20:58 -0500
        dir        ~/.config/doom/
system  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /usr/bin/zsh
        uname      Linux 5.5.0-1-MANJARO #1 SMP PREEMPT Mon Jan 27 09:39:12 UTC 2020 x86_64
        path       (~/bin /usr/local/sbin /usr/local/bin /usr/bin /var/lib/flatpak/exports/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl ~/.local/bin ~/.config/emacs_doom/bin ~/.dotnet/tools ~/var/go/bin ~/.cabal/bin ~/opt/ghcup/bin ~/.gem/ruby/2.7.0/bin ~/.local/share/cargo/bin /usr/lib/emacs/26.3/x86_64-pc-linux-gnu)
config  envfile    nil
        elc-files  32
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +all +defaults) vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold fmt multiple-cursors rotate-text snippets :emacs dired electric ibuffer vc :term term vterm :checkers syntax :tools (eval +overlay) (lookup +docsets) lsp magit :lang (cc +lsp) clojure common-lisp data emacs-lisp haskell latex (lua +moonscript) markdown (org +dragndrop +jupyter +present) (python +lsp) (rust +lsp) sh :config literate (default +evil +bindings +smartparens))
        packages   ((evil-escape :disable t :pin "f4e9116bfbaac8c9d210c17ad488e0982291245f") form-feed hungry-delete company-jedi)
        elpa       (n/a)
```
</details>

**Comment by Janfel** [comment]
I have narrowed the bug down to the `:editor evil` module without any active flags. When this module is disabled, I am unable to reproduce the bug.

**Comment by Janfel** [comment]
It seems `fundamental-mode` is never even called when `:editor evil` is active.

**Comment by hlissner** [comment]
This appears to be an upstream issue, with evil, due to [these lines in `evil-mode`](https://github.com/emacs-evil/evil/blob/master/evil-core.el#L195-L197) setting `major-mode` to `turn-on-evil-mode` if you are in `fundamental-mode`, in order to get evil to work in fundamental mode.

Please report the issue there. In the meantime, here is a workaround:

```elisp
(defadvice! fix-local-vars (&rest _)
  :before #'turn-on-evil-mode
  (when (eq major-mode 'fundamental-mode)
    (hack-local-variables)))
```

I'll keep this issue open until we have a permanent solution.

**Comment by Janfel** [comment]
This issue is still valid.

**Comment by Janfel** [comment]
This issue is still valid.

**Comment by Janfel** [comment]
The upstream issue has recently been closed, see https://github.com/emacs-evil/evil/issues/1268.
