### ISSUE TITLE
Switch default cc language server to clangd

### ISSUE THREAD

**Issue by judemille** [doomemacs/doomemacs#2689]
**Describe the feature**
Clangd is the default language server for C/C++ in `lsp-mode`, and (as of my testing using clang 9.0.1), works quite well. Since this avoids adding an extra package, clangd should be made the default. Of course, this would be a breaking change, so there would have to be some period of adding a `+ccls` option and warning users that if they want to keep `ccls` that they will have to use that. Feedback is welcome.

**System information**
<details><pre>
((emacs
  (version . "27.0.90")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Mar 09, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-sound=alsa --with-modules --without-gconf --without-gsettings --with-x-toolkit=gtk3 --without-xaw3d --without-m17n-flt --with-cairo --without-compress-install 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -g -flto -s -fuse-ld=gold' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 503c6d878 2020-03-08 22:36:34 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.5.8-zen1-1-zen #1 ZEN SMP PREEMPT Fri, 06 Mar 2020 00:57:35 +0000 x86_64")
  (path "~/miniconda3/bin" "~/.local/bin" "~/.cargo/bin" "~/.dotnet/tools" "~/.yarn/bin" "~/.gem/ruby/2.7.0/bin" "~/.config/emacs/bin" "~/.rbenv/shims" "~/.mix/escripts" "~/.poetry/bin" "~/go/bin" "~/.poetry/bin" "~/.cargo/bin" "~/.local/bin" "~/.cargo/bin" "~/.dotnet/tools" "~/.yarn/bin" "~/.gem/ruby/2.7.0/bin" "~/.emacs.d/bin" "~/.rbenv/shims" "~/.mix/escripts" "~/.poetry/bin" "~/go/bin" "~/.local/bin" "~/.cargo/bin" "~/.dotnet/tools" "~/.yarn/bin" "~/.gem/ruby/2.7.0/bin" "~/.emacs.d/bin" "~/.rbenv/shims" "~/.mix/escripts" "~/.poetry/bin" "~/go/bin" "~/.cargo/bin" "~/.local/bin" "~/.poetry/bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.npm-packages/bin" "~/.npm-packages/bin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.npm-packages/bin" "/usr/lib/emacs/27.0.90/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 2)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo hydra indent-guides modeline nav-flash ophints (popup +defaults) pretty-code tabs treemacs unicode vc-gutter vi-tilde-fringe window-select workspaces :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors parinfer snippets :emacs dired electric ibuffer vc :term shell :checkers syntax :tools ansible debugger direnv docker editorconfig ein (eval +overlay) gist lookup (lsp +peek) magit make pdf tmux :lang (cc +lsp) (csharp +lsp) data emacs-lisp ess (fsharp +lsp) (go +lsp) (javascript +lsp) julia latex lua markdown nix (org +dragndrop +hugo +jupyter +pandoc +pomodoro +present) (python +lsp) qt rest rst (ruby +lsp +rails) (rust +lsp) sh (web +lsp) :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by juliandemille** [comment]
I can implement this, does doom have a function to warn users of deprecation?

**Comment by gagbo** [comment]
Not really, but in any case I don't think that silently changing functionality is a good pattern anyway. Having to manually specify a `+clangd` feature instead of a `+ccls` seems better to me, at least during the transition.

The amount of "I upgraded but now it doesn't work" issues is not worth such a brutal change in my opinion.

On `clangd` vs `ccls`, the main issue I had is that `clangd` doesn't index the whole project if `version < 9` ([Source](https://clang.llvm.org/extra/clangd/Features.html#id14)), which is why I went ccls. It seems that [Debian unstable (Sid)](https://packages.debian.org/unstable/clangd) now ships `clangd 9`, Testing (Bullseye) ships clangd-9 too, but unfortunately [Stable](https://packages.debian.org/search?searchon=names&keywords=clangd) looks like it only gives `clangd 8`. So changing this now would remove lsp features to some users.

With that being said, you can probably change it yourself by not installing the `ccls` binary in your path (`lsp-mode` should properly fall back), and disabling the ccls package if you really want some disk space

**Comment by juliandemille** [comment]
True, that has been my solution for now (disabling the ccls package). Perhaps we can revisit when more Linux distros package clang 9?

**Comment by hlissner** [comment]
I don't mind making clangd our new default once v9 becomes more ubiquitous. For the time being:

1. I've introduced a `set-lsp-priority! CLIENT PRIORITY` function for changing the priority of your LSP clients some time ago. You can use it to change which lsp client to use. 
2. I've added a `M-x +lsp/switch-client` command for switching on the fly, if you need that for some reason (for testing, mainly).
3. Disabling the ccls package is acceptable too.

**Comment by rinon** [comment]
Does this still work? This was working fine for me, but after updating doom it seems the `set-lsp-priority!` didn't get called and I had to manually call it.

**Comment by moben** [comment]
```
(after! lsp-clangd
  (set-lsp-priority! 'clangd 1))  ; ccls has priority 0
```
This seems to work for me.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/cc8cf810f58eee7762af364546d57bf56b640380, clangd now has higher priority over ccls, so I'll consider this resolved. Thanks for bringing it to my attention!

**Comment by yetanotherqubick** [comment]
:lang cc [README](https://github.com/doomemacs/doomemacs/tree/master/modules/lang/cc#lsp-mode-with-ccls) still says `ccls` is the default:

```
;;; add to $DOOMDIR/config.el
(after! ccls
  (setq ccls-initialization-options '(:index (:comments 2) :completion (:detailedLabel t)))
  (set-lsp-priority! 'ccls 2)) ; optional as ccls is the default in Doom
```
