### ISSUE TITLE
error code 2 on project searches with ripgrep

### ISSUE THREAD

**Issue by JulHee** [doomemacs/doomemacs#3038]
**What did you expect to happen?**

Expected a partial result from `+default/search-project` using `ripgrep`.

**What actually happened?**

If the user has no permission to a folder inside the project, the command returns `error code 2` and no results are returned.

**Steps to reproduce:**

1. Create a folder inside a project
2. Remove the permissions for your user from the folder
3. Try to search using `+default/search-project`

**System information:**
<details><pre>
((emacs
  (version . "26.3")
  (features . "XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2")
  (build . "Sep 16, 2019")
  (buildopts "--build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=26 --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-xwidgets --with-lcms2 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/emacs26-TP6iDo/emacs26-26.3~1.git96dd019=. -fstack-protector-strong -Wformat -Werror=format-security -no-pie' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -no-pie'")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop 35591cfc4 2020-05-04 16:53:26 -0400")
  (dir . "~/.doom.d/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64")
  (path "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "~/.fzf/bin" "~/.local/bin" "~/.npm/bin" "~/dev/other/capi" "~/.fzf/bin" "~/.yarn/bin" "~/.emacs.d/bin" "~/.poetry/bin" "/usr/lib/x86_64-linux-gnu/emacs/26.3/x86_64-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 0)
  (modules :completion company helm (ivy +childframe +icons +fuzzy) :ui doom doom-dashboard hl-todo indent-guides modeline nav-flash ophints (popup +all +defaults) treemacs vc-gutter vi-tilde-fringe window-select workspaces :editor file-templates fold multiple-cursors rotate-text snippets :emacs (dired +icons) electric ibuffer undo vc :term term :checkers syntax spell :tools editorconfig (eval +overlay) (lookup +docsets) lsp magit pass pdf :lang data emacs-lisp json javascript latex markdown (org +dragndrop +pandoc +ipython +gnuplot +present) plantuml (python +lsp) (rust +lsp) sh yaml :app irc :config (default +bindings +smartparens))
  (packages (prettier-js) (sphinx-doc) (org-caldav) (org-ref))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by hlissner** [comment]
This is [a known issue with how counsel-rg interprets its program's error codes](https://github.com/abo-abo/swiper/issues/2339) -- or perhaps how ripgrep returns a non-zero error code, despite returning a partial result. A crude workaround for this would be:

```elisp
;; Will only work on macos/linux
(after! counsel
  (setq counsel-rg-base-command (concat counsel-rg-base-command " | true")))
```

**Comment by sfc-gh-mpilman** [comment]
I run into a similar issue (on macOS). I don't think there's a permission issue. If I run the following command in my project folder, it works just fine:

```rg --with-filename --no-heading --line-number --color never TEXT```

If I try to apply the above workaround, Emacs is giving me the following error during startup:
```
Loading /Users/mpilman/.emacs.frameg...done
Doom loaded 183 packages across 38 modules in 1.178s
Error in pre-command-hook (doom-first-input-hook-h): (wrong-type-argument characterp "rg")
setq: Wrong type argument: characterp, "rg"
```

**Comment by hlissner** [comment]
@sfc-gh-mpilman Try this instead:

```elisp
(after! counsel
  (setq counsel-rg-base-command "rg -M 240 --with-filename --no-heading --line-number --color never %s"))
```

**Comment by sfc-gh-mpilman** [comment]
@hlissner this works!! Perfect, thank you so much :)

**Comment by wsw0108** [comment]
I have same problem under Windows 10.

Some times when I input the first char of query text, `+default/search-project` show correct search result, but if I continue to input remain chars, the problem occur.

Then I found if I disable `+prescient` for module `ivy`, the search works well.

https://github.com/raxod502/prescient.el/issues/43

**Comment by daedric** [comment]
I've discovered that it can happen if one has a directory without read/execute rights

**Comment by hlissner** [comment]
> I've discovered that it can happen if one has a directory without read/execute rights

As I've said, [this is a known issue with how counsel-rg interprets its program's error codes.](https://github.com/abo-abo/swiper/issues/2339) Ripgrep returns a non-zero exit code if it encounters any trouble (e.g. you don't have the needed permissions for said files/directories). Even if `ripgrep` continues to produce workable results, that non-zero exit code tells `counsel-rg` to discard the rest of the output and display an error.

**Comment by io12** [comment]
Here's another workaround that probably works on windows

```lisp
(after! counsel
  (advice-add 'counsel-rg
              :around
              (lambda (func &rest args)
                (cl-letf (((symbol-function #'process-exit-status)
                           (lambda (_proc) 0)))
                  (apply func args)))))
```

**Comment by AbstProcDo** [comment]
It works 

> 
> 
> Here's another workaround that probably works on windows
> 
> ```lisp
> (after! counsel
>   (advice-add 'counsel-rg
>               :around
>               (lambda (func &rest args)
>                 (cl-letf (((symbol-function #'process-exit-status)
>                            (lambda (_proc) 0)))
>                   (apply func args)))))
> ```

It works on Windows, thank you.

**Comment by v0d1ch** [comment]
> I've discovered that it can happen if one has a directory without read/execute rights

This one helped me out. Not just the folder but if you have a file with the wrong permissions.

**Comment by hlissner** [comment]
Could you see if the following works for you?

```elisp
(defadvice! +ivy--always-return-zero-exit-code-a (fn &rest args)
  :around #'counsel-rg
  (letf! (defun process-exit-status (_proc)
           (let ((code (funcall process-exit-status proc)))
             (if (= code 2) 0 code)))
    (apply fn args)))
```

I'd like counsel-rg to at least be aware of error code `1`, to report when there are no results. It's exit code 2 (which ripgrep returns for both catastrophic and soft errors -- sigh) that we want to ignore.

**Comment by isker** [comment]
@hlissner after correcting `proc` to `_proc`, your advice caused strange errors for me.  Without your change, I get these "error code 2" messages when I try to use escape sequences like `\.`.  With your change, when I go to do that:

![Screen Shot 2021-11-11 at 10 56 03 PM](https://user-images.githubusercontent.com/5225653/141406636-f8cdbaad-88f5-4cf2-9c1f-11a4f74f9dab.png)

I am not too sure what to think of that.

**Comment by rgkirch** [comment]
I was getting the "error code 2" and hlissner's snippet fixed it (after changing proc to _proc). @isker I don't get the "unrecognized escape sequence error" when escaping period in a search e.g. `\.org`. \shrug
On windows with `rg`.

**Comment by eeshugerman** [comment]
In case any other non-doomers find this, here's what I came with for hlissner's latest snippet without the doom-specific macros:
```elisp
(with-eval-after-load 'counsel
  (advice-add 'counsel-rg
              :around
              (lambda (func &rest args)
                (cl-flet ((filter-func (code) (if (= code 2) 0 2)))
                  (unwind-protect
                      (progn (advice-add 'process-exit-status :filter-return #'filter-func)
                             (apply func args))
                    (advice-remove 'process-exit-status #'filter-func))))))
```

**Comment by raveensrk** [comment]
> In case any other non-doomers find this, here's what I came up with for hlissner's latest snippet but without the doom-specific macros:
> 
> ```emacs-lisp
> (with-eval-after-load 'counsel
>   (advice-add 'counsel-rg
>               :around
>               (lambda (func &rest args)
>                 (cl-flet ((filter-func (code) (if (= code 2) 0 code)))
>                   (unwind-protect
>                       (progn (advice-add 'process-exit-status :filter-return #'filter-func)
>                              (apply func args))
>                     (advice-remove 'process-exit-status #'filter-func))))))
> ```

Added this code at the end of my init.el file. But does not seem to work.

**Comment by hlissner** [comment]
I've incorporated @eeshugerman's advice into 6ef8609, so I'll consider this resolved. If you're still using Ivy, I recommend you switch to the Vertico module. Not only does `consult-rg` not suffer from this issue, but I plan to eventually deprecate the Ivy module, as Vertico is superior to it is every way.

Anyhow, thanks for bringing it to my attention, in any case!
