### ISSUE TITLE
"Invalid base64 data": +org-inline-image-data-fn halts org-babel-after-execute-hook, when "attachment:" image link not reachable (e.g. outside narrowed subtree)

### ISSUE THREAD

**Issue by adrech** [doomemacs/doomemacs#3185]
When an `attachment:` image is not reachable (outside narrowed buffer or broken link),
`+org-inline-image-data-fn` throws: `Invalid base64 data`.

This breaks e.g. `jupyter-org-execute-and-next-block` (point does not jump to
the next block), because `org-babel-after-execute-hook` ->
`org-redisplay-inline-images` -> `+org-inline-image-data-fn` -> error
prevents further execution.

```org
* To reproduce this error

<< drag and drop an image here - should create an ~attachment:~ link >>

* execute

#+BEGIN_SRC elisp
(org-narrow-to-subtree)
#+END_SRC

#+BEGIN_SRC elisp
(+ 2 3)
#+END_SRC

Error shown in Messages buffer:
~+org-inline-image-data-fn: Invalid base64 data~

Alternatively, having a broken ~attachment:~ link somewhere in the buffer will
lead to the error as well, regardless of narrowing:
# Triggers the bug: [[attachment:i-do-not-exist.png]]
# Does NOT trigger the bug: [[file:i-do-not-exist.png]]
```

My temporary "fix" to circumvent this:

```emacs-lisp
(defadvice! no-errors/+org-inline-image-data-fn (_protocol link _description)
  :override #'+org-inline-image-data-fn
  "Interpret LINK as base64-encoded image data. Ignore all errors."
  (ignore-errors
    (base64-decode-string link)))
```

**Comment by czikus** [comment]
I'm seeing the same problem for any attachment link with a description. E.g. a PDF attachment with a description will result in:

```
(error "Invalid base64 data")
  (base64-decode-string "file.pdf")
  (+org-inline-image-data-fn "attachment" "file.pdf" "Description")
  (org-display-user-inline-images)
```

**Comment by ashkan-leo** [comment]
Facing the same issue

**Comment by ukcw** [comment]
![image](https://user-images.githubusercontent.com/34738958/230044344-07cd74ad-4155-4aec-aa5f-09af45997df7.png)

I'm facing a similar issue as described above. In my case, I cannot toggle the inline images but when exporting to HTML5 for example, the images are rendered correctly (which means that links actually do work?). But for export to LaTeX via pandoc it doesn't work and gives the openBinaryFile: does not exist error. I'm slightly confused by this and would appreciate any help!

**Comment by barslmn** [comment]
When you create attachment it puts the file into {org-directory}/.attach/{heading-id}/. If you move your attachment around without the heading it won't be able to find it again.

**Comment by KaiAragaki** [comment]
Seems like this one might be able to be closed @hlissner ?
