### ISSUE TITLE
Is it possible to format asyncly on save?

### ISSUE THREAD

**Issue by dsdshcym** [doomemacs/doomemacs#3191]
**Describe the feature**
I use `format +onsave` to format the butter synchronously.
But when the format takes some time, my Emacs is not responsive for 0.5s~1s.

I tried to use [apheleia](https://github.com/raxod502/apheleia) in doom.
This package would call formatter and update buffer asynchronously.
So I can save without waiting for the file to be formatted, which is almost instant compared to a 0.5s delay.
But I ran into several issues with apheleia:
1. it doesn't support many languages (~5 languages only)
2. it conflicts with `flycheck` or some other packages

I know we've patched `format-all` to use RCS diff (which is used by apheleia as well).
So I'm wondering if we can patch `format-all` further to make it async?

**Comment by hlissner** [comment]
It should be possible to do so, but I'm already working on a rewrite for the format module (powered by apheleia). I've pushed it to [my private config](https://github.com/hlissner/doom-emacs-private/tree/master/modules/editor/format) if you'd like to try it out. It doesn't see much use and is still a WIP though.

**Comment by dsdshcym** [comment]
Good to know that you are working on a rewrite!

I've tried my thin wrapper around apheleia.
The only config I add to yours is:

```elisp
  ;; disable flycheck on-save to avoid a race condition between flycheck saving a tmp-file and apheleia formatting it
  (after! flycheck
    (setq flycheck-check-syntax-automatically '(mode-enabled idle-buffer-switch)))
```

**Comment by Jdogzz** [comment]
@hlissner I think this one is also okay to close with the format changes?
