### ISSUE TITLE
Company Error in Elixir Mode (alchemist-company)

### ISSUE THREAD

**Issue by Janfel** [doomemacs/doomemacs#3497]
**What did you expect to happen?**
Autocompletion in `elixir-mode` works just as in every other mode.

**What actually happened?**
When completing a symbol, such as `def`, and idling in the completion popup for 1-2 seconds, Emacs freezes and an error occurs. The backtrace is included below.

**Additional details:**
- The issue is reproducible in `M-x doom/sandbox C-c C-p`.

**Backtrace**
<details><pre>
Debugger entered--Lisp error: (error "Company: backend (alchemist-company company-yasnippet) async timeout with args (doc-buffer def)")
  signal(error ("Company: backend (alchemist-company company-yasnippet) async timeout with args (doc-buffer def)"))
  error("Company: backend %s async timeout with args %s" (alchemist-company company-yasnippet) (doc-buffer #("def" 0 3 (meta "/1"))))
  company--force-sync(company-call-backend-raw (doc-buffer #("def" 0 3 (meta "/1"))) (alchemist-company company-yasnippet))
  company-call-backend(doc-buffer #("def" 0 3 (meta "/1")))
  company-box-doc--fetch-doc-buffer(#("def" 0 3 (meta "/1")))
  company-box-doc--show(0 #<frame math.ex – Doom Emacs 0x555ce46831b0>)
  #f(compiled-function () #<bytecode 0x155739363f6d>)()
  apply(#f(compiled-function () #<bytecode 0x155739363f6d>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x155739363f6d>) nil idle 0])
</pre></details>

**Steps to reproduce:**
1. Have `:lang elixir` enabled.
1. Open a new buffer.
2. `M-x elixir-mode`
3. Type `def` and wait for the company popup.
4. Wait 1-2 seconds.

**System information:**
<details><pre>
((emacs
  (version . "27.0.91")
  (features . "XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP")
  (build . "Jun 23, 2020")
  (buildopts "--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
  (windowsys . batch)
  (daemonp . server-running))
 (doom
  (version . "2.0.9")
  (build . "HEAD -> develop, origin/develop, origin/HEAD 25b240b9b 2020-06-28 01:09:54 -0400")
  (dir . "~/.config/doom-emacs/"))
 (system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/usr/bin/zsh")
  (uname . "Linux 5.7.0-3-MANJARO #1 SMP PREEMPT Wed Jun 3 03:15:33 UTC 2020 x86_64")
  (path "~/bin" "~/opt/bin" "/usr/local/bin" "/usr/bin" "~/.local/bin" "/usr/local/sbin" "/usr/lib/jvm/default/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "~/.dotnet/tools" "~/var/go/bin" "~/.local/share/cabal/bin" "~/opt/ghcup/bin" "~/.gem/ruby/2.7.0" "~/.local/share/cargo/bin" "/usr/lib/emacs/27.0.91/x86_64-pc-linux-gnu"))
 (config
  (envfile . envvar-file)
  (elc-files . 32)
  (modules :completion (company +childframe) ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash neotree ophints (popup +defaults) vc-gutter window-select workspaces :editor (evil +everywhere) file-templates fold (fmt +define) rotate-text snippets :emacs dired electric ibuffer undo vc :term vterm :checkers syntax (spell +aspell) :tools editorconfig (eval +overlay) lookup lsp magit :lang arduino basic (cc +lsp) clojure common-lisp data elixir emacs-lisp fennel (haskell +dante) latex (lua +moonscript) markdown org (python +lsp) (rust +lsp) scheme sh :config literate (default +evil +bindings +smartparens))
  (packages (meson-mode) (moonscript :recipe (:host github :repo "Janfel/moonscript-mode")) (php-mode) (async) (evil-escape :disable t) (flycheck :pin nil) (form-feed) (highlight-indent-guides) (hungry-delete) (company-quickhelp) (company-jedi))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by tmr08c** [comment]
Since `alchemist` was removed in https://github.com/doomemacs/doomemacs/commit/221e75e7391a4c613d089a5ac7d98f0011bc03d0 in favor of LSP (`(elixir +lsp)`), it may make sense to close this and re-open if it is also an issue with LSP mode enabled.
