### ISSUE TITLE
Changing where users get support

### ISSUE THREAD

**Issue by jtpavlock** [doomemacs/doomemacs#3589]
So currently, it seems like the discord is the recommended way for users to get help with doom. 

I see 2 general downfalls with this:
1. Discord isn't really a good Q&A platform as questions can get buried easily
2. Searching discord for a question can be tough and limits how much the "knowledge database" can grow

My proposal is to switch to suggesting users to use the `doom` tag on [emacs.stackexchange.com](https://emacs.stackexchange.com/questions/tagged/doom)

It seems some users are already there, but it would benefit from an official backing.

**Comment by jsmestad** [comment]
I always like discourse as well for community sites. StackExchange can be pretty difficult to search IMO.

**Comment by rushsteve1** [comment]
[The FAQ details why Discord, and only Discord, was chosen.](https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#is-discord-the-only-option-for-interacting-with-your-community)

**Comment by jtpavlock** [comment]
fair enough

**Comment by hlissner** [comment]
I'm aware of Discord's shortcomings, but I'm stretched thin managing the one platform (and Doom's issue tracker) to monitor another. There's still room to consider an alternative (Discourse is a promising candidate), but it'd have to be at Discord's expense -- one platform is my limit.

In any case, I've got at least another month or two's worth of groundwork to do (including CI, a website, and better documentation) before I can consider this further.

**Comment by jtpavlock** [comment]
I'll reopen since it's not a definite no, then 😃 

emacs.stackexchange, imo, would just be a drop-in replacement for the #how-do-i (and potentially #troubleshooting and #emacs-lisp) channels. Having it there allows the knowledge database to grow as it's a lot easier to search and refer back to previous answers. Also, you get the benefit of accessing other users on the site that are able to help with general emacs questions if they are not completely doom-specific.

**Comment by AnikaSU** [comment]
> I'm aware of Discord's shortcomings, but I'm stretched thin managing the one platform (and Doom's issue tracker) to monitor another. There's still room to consider an alternative (Discourse is a promising candidate), but it'd have to be at Discord's expense -- one platform is my limit.
> 
> In any case, I've got at least another month or two's worth of groundwork to do (including CI, a website, and better documentation) before I can consider this further.

Apologies if I'm asking stupid questions, but the Discord server link on README page is expired... is there any alternatives I could join the server?

**Comment by hlissner** [comment]
@AnikaSU Which one? There are three in the README and they're all valid. Maybe you're looking at the README on the master branch?

**Comment by AnikaSU** [comment]
Join the Doom Emacs Discord Server!

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Join the Doom Emacs Discord Server!

Check out the Doom Emacs community on Discord - hang out with 3,266 other members and enjoy free voice and text ...
 |

 |

 |

"https://discord.com/invite/qvGgnVx"
On the dev (default) branch. I found several in the Documentation, all pointing to this link:"https://discord.com/invite/qvGgnVx"
I visited this link, and it opened a webpage saying "This invite may be expired, or you might not have permission to join" 
If the link is valid per se then it might have something to do with the GFW. I'll go check the VPN and see if it works.    On Tuesday, July 21, 2020, 03:30:56 AM GMT+8, Henrik Lissner <notifications@github.com> wrote:  
 
 


@AnikaSU Which one? There are three in the README and they're all valid. Maybe you're looking at the README on the master branch?

**Comment by skaven-gear** [comment]
> I see 2 general downfalls with this:
> 
>     1. Discord isn't really a good Q&A platform as questions can get buried easily
> 
>     2. Searching discord for a question can be tough and limits how much the "knowledge database" can grow

Well this is more, blind peoples can't use it.
Tor users will eventually loop forever in a nightmare of captchas.

**Comment by jman-schief** [comment]
I'll gently push and mention [this article](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html#fnref:1) on why Discord is a bad choice.

I am fully aware of why Discord was choosen at the beginning, but I also notice that I'm excluded from all the fun happening there :-/

I just hope that in the future this can change :-)

**Comment by hlissner** [comment]
Now that Doom has [a Discourse](https://discourse.doomemacs.org), and thus, an alternative to Discord, I will consider this issue resolved.

I also plan to create a [Matrix](https://matrix.org/) space for Doom once:

- ~Spaces are out of beta~ (seems this is already the case?), 
- [A bot capable of bridging spaces to whole Discord servers](https://github.com/Half-Shot/matrix-appservice-discord/issues/738) is available.
- I've found some mods and bots to keep an eye on the Matrix side of things, and have sufficiently mirrored the moderation efforts on our Discord server.

That said, no telling how long that will take, but it's in the works.
