### ISSUE TITLE
.h extension in c++-mode is not correctly handled by lsp-mode

### ISSUE THREAD

**Issue by lromor** [doomemacs/doomemacs#3880]
**What did you expect to happen?**
To have autocompletion and lsp-mode clangd c++ features for a .h header.

I have described in detail the problem in the original repo of lsp-mode: https://github.com/emacs-lsp/lsp-mode/issues/2118

**What actually happened?**

Autocompletion treats the .h header a c header, altough the major mode is c++-mode.

**Additional details:**
https://github.com/emacs-lsp/lsp-mode/issues/2118

Fresh install of doom emacs. Notice that using lsp-mode plain init script solves the issue, hinting there might be
a misconfiguration.

<details><pre>
If an error message is involved include a backtrace of it.

How to acquire a backtrace:
https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#how-to-extract-a-backtrace-from-an-error
</pre></details>

**Steps to reproduce:**
1. Clone doom emacs and install
2. Configure lsp mode for c++
3. Create a .h file and enable c++-mode
4. add "#include <vector>"
5. Try to autocomplete an std::vec

**System information:**
<details><pre>
((system
  (type . gnu/linux)
  (config . "x86_64-pc-linux-gnu")
  (shell . "/bin/bash")
  (uname . "Linux 5.7.0-3-amd64 #1 SMP Debian 5.7.17-1 (2020-08-23) x86_64")
  (path "/usr/local/cuda/bin" "~/.yarn/bin" "~/.local/bin" "~/.cargo/bin" "~/.cargo/bin" "~/.local/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/local/games" "/usr/games" "/usr/local/libexec/emacs/28.0.50/x86_64-pc-linux-gnu"))
 (emacs
  (dir . "~/.emacs.d/")
  (version . "28.0.50")
  (build . "Aug 26, 2020")
  (buildopts . "--with-xwidgets --with-imagemagick")
  (features . "XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.doom.d/")
  (version . "2.0.9")
  (build . "grafted, HEAD -> develop, origin/develop, origin/HEAD 1c99aed 2020-08-25 21:22:56 -0400")
  (elc-files . 0)
  (modules :completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline nav-flash ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term vterm :checkers syntax :tools (eval +overlay) lookup lsp magit :lang (cc +lsp) data emacs-lisp (haskell +dante) json javascript latex markdown org (python +lsp) rust sh web yaml :config (default +bindings +smartparens))
  (packages "n/a")
  (unpin "n/a")
  (elpa "n/a")))

</pre></details>

**Comment by innerout** [comment]
If you add this in your configuration `(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))` Emacs will treat .h files as C++ headers. If you are working with C and C++ headers then put at the top of your C++ .h headers this `// -*- mode: c++ -*-` .

**Comment by lromor** [comment]
Hi @innerout . Thank you for your answer. Unfortunately I already did that:

> Autocompletion treats the .h header a c header, altough the major mode is c++-mode.

**Comment by lromor** [comment]
@hlissner Any change to be able to fix this?

**Comment by lromor** [comment]
A workaround is to create a `compile_flags.txt` containing:
```
-xc++
```

**Comment by grxnola** [comment]
I'm encountering this same bug, it's still around.

**Comment by innerout** [comment]
> I'm encountering this same bug, it's still around.

Have you tried adding `-xc++` in `compile_flags.txt`? It seems to work for me besides the first thing I proposed. (using latest clangd)

**Comment by henrythebuilder** [comment]
In my case the problem seems solved. I don't know if it's due to my configuration but the files seem to be recognized correctly with the correct _major mode_.
- latest Doom Emacs
- [my Doom info](https://pastebin.com/MtCPTGyp)
- [my local cc config](https://pastebin.com/3SfTv9cu)

in my case I had to adapt the `clangd` and `clang-format` path to the specific installed version: `clangd-18` and `clang-format-18`

C mode test
<img width="797" alt="Screenshot_c-mode_test" src="https://github.com/doomemacs/doomemacs/assets/6670654/32b4f159-1846-4d02-959f-92c8c3b405c5">


CPP mode test
<img width="811" alt="Screenshot_cpp-mode_test" src="https://github.com/doomemacs/doomemacs/assets/6670654/d52f6e65-2776-4949-8c3d-2412307bd9c4">
