### ISSUE TITLE
Formatter set with `set-formatter!` isn't called with environment defined in `.envrc`

### ISSUE THREAD

**Issue by ehamberg** [doomemacs/doomemacs#3900]
**What did you expect to happen?**

Adding `(set-formatter! 'erlfmt  "erlfmt -" :modes '(erlang-mode))` to my `config.el` file should enable code formatting by calling the `erlfmt` command with the same (direnv + nix) environment other tools in the same project use.

**What actually happened?**

`erlfmt` seems to get called without using the environment from direnv. This fails because the `escript` command cannot be found, leading to the error `env: escript: No such file or directory` being printed in the `*format-all-errors*` buffer.

**Additional details:**

- Evaluating `(shell-command "erlfmt -v")` in an Erlang buffer in the same project *does* call `erlfmt` with the correct environment. (It returns `0` and prints the version number of *erlfmt* in the `*Shell Command Output*` buffer.)

**Steps to reproduce:**
1. Create a project with an empty `test.erl` file
1. Add a `.envrc` file with `export ZEBRA=1338`
1. Run `direnv allow`
1. Open `test.erl` in emacs
1. Eval `(set-formatter! 'erlfmt  "env" :modes '(erlang-mode))`
1. Run `format-all-buffer`
1. Observe that the `ZEBRA` env. var is not in the output from `env`

**System information:**
<details><pre>
((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.6.0")
  (shell . "/nix/store/wny5xm2fiynw2bgdrpmpk2zmnlzp6x8s-zsh-5.8/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/.local/bin" "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "~/.nix-profile/bin" "~/.cabal/bin" "/usr/local/sbin" "~/.cargo/bin" "~/Projects/go/bin" "~/.config/emacs/bin" "/run/current-system/sw/bin" "/usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0"))
 (emacs
  (dir . "~/.config/emacs/")
  (version . "27.1")
  (build . "Aug 11, 2020")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.config/doom/")
  (version . "2.0.9")
  (build . "HEAD -> develop ae3a2fa8c 2020-09-02 14:23:11 -0400")
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo ligatures modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +hunspell) grammar :tools ansible direnv editorconfig (eval +overlay) lookup lsp magit make terraform :os macos :lang elm (erlang +lsp) (go +lsp) (haskell +dante) idris json javascript markdown nix (org +roam) rest rust sh swift web :config (default +bindings +smartparens))
  (packages (gleam-mode :recipe (:host github :repo "gleam-lang/gleam-mode")) (dash-at-point) (md-roam :recipe (:host github :repo "nobiot/md-roam")) (solarized-theme) (ormolu) (kaolin-themes) (sqitch-for-emacs :recipe (:host github :repo "christophermaier/sqitch-for-emacs" :files ("*.el"))) (csv-mode) (golden-ratio))
  (unpin "n/a")
  (elpa "n/a")))

((system
  (type . darwin)
  (config . "x86_64-apple-darwin19.6.0")
  (shell . "/nix/store/wny5xm2fiynw2bgdrpmpk2zmnlzp6x8s-zsh-5.8/bin/zsh")
  (uname . "Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64")
  (path "~/.local/bin" "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Library/Apple/usr/bin" "~/.nix-profile/bin" "~/.cabal/bin" "/usr/local/sbin" "~/.cargo/bin" "~/Projects/go/bin" "~/.config/emacs/bin" "/run/current-system/sw/bin" "/usr/local/Cellar/emacs-plus@27/27.1/libexec/emacs/27.1/x86_64-apple-darwin19.6.0"))
 (emacs
  (dir . "~/.config/emacs/")
  (version . "27.1")
  (build . "Aug 11, 2020")
  (buildopts . "--disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@27/27.1/share/info/emacs --prefix=/usr/local/Cellar/emacs-plus@27/27.1 --with-xml2 --with-gnutls --without-dbus --with-imagemagick --with-modules --with-rsvg --with-ns --disable-ns-self-contained")
  (features . "RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP")
  (traits batch server-running envvar-file))
 (doom
  (dir . "~/.config/doom/")
  (version . "2.0.9")
  (build . "HEAD -> develop ae3a2fa8c 2020-09-02 14:23:11 -0400")
  (elc-files . 0)
  (modules :completion company (ivy +fuzzy) :ui doom doom-dashboard hl-todo ligatures modeline nav-flash ophints (popup +defaults) treemacs vc-gutter vi-tilde-fringe (window-select +numbers) workspaces zen :editor (evil +everywhere) file-templates fold (format +onsave) multiple-cursors snippets :emacs dired electric undo vc :term vterm :checkers syntax (spell +hunspell) grammar :tools ansible direnv editorconfig (eval +overlay) lookup lsp magit make terraform :os macos :lang elm (erlang +lsp) (go +lsp) (haskell +dante) idris json javascript markdown nix (org +roam) rest rust sh swift web :config (default +bindings +smartparens))
  (packages (gleam-mode :recipe (:host github :repo "gleam-lang/gleam-mode")) (dash-at-point) (md-roam :recipe (:host github :repo "nobiot/md-roam")) (solarized-theme) (ormolu) (kaolin-themes) (sqitch-for-emacs :recipe (:host github :repo "christophermaier/sqitch-for-emacs" :files ("*.el"))) (csv-mode) (golden-ratio))
  (unpin "n/a")
  (elpa "n/a")))
</pre></details>

**Comment by fanshi1028** [comment]
https://github.com/lassik/emacs-format-all-the-code/issues/33
Probably this issue?

**Comment by ehamberg** [comment]
@fanshi1028 Yeah, looks like it. I guess this won't be easy to solve… 😔

**Comment by venikx** [comment]
I might have some additional information to debug this further, since I think it's similar enough. 

Personally I'm running NixOS and wish to keep the node version managed by the projects themselves, so I don't have node globally installed, only in a project nix-env. 
It seems that the integration between direnv + doom-emacs is working fine as things like `eslint` can be found in the local bin by loading the local environment. 

For the `format-all` I was running in the issue, that when it was trying to format via prettier, it was trying to install prettier + some additional packages, but for some reason it couldn't find the "node", let alone find a locally installed package. 
So I tried escaping out of `format-all` for `js2-mode` and use a trusty `prettier-js` from when I still had my own Emacs configuration, and it seems to be working totally fine.

So either the integration between `format-all` and `doom-emacs` doesn't respect the local env changes from `direnv` or it's something that already goes wrong in the `format-all` package. However, my elisp knowledge is too limited to figure this out on my own. 

I hope this helps in progressing the issue.
for 
ut I'm not too sure what exactly is causing the issue `format-all` +  or the integration between `doom-emacs` and `format-all`

**Comment by purcell** [comment]
This is probably related to https://github.com/purcell/envrc/issues/12 and I think that you could use

```el
(advice-add 'format-all-buffer :around #'envrc-propagate-environment)
```

to work around it for now.

**Comment by purcell** [comment]
And in the linked `format-all` issue I mentioned that `format-all` should ideally be (fairly trivially) patched to do the right thing.

**Comment by venikx** [comment]
@purcell 
Thanks, that seems to be working!

**Comment by ehamberg** [comment]
@venikx It does! I had to `unpin!` the `envrc` package to get a version with `envrc-propagate-environment`, but now it seems to work. 🙌

**Comment by exAClior** [comment]
If I may add, a similar issue persists for python-mode. I could not figure out how to solve this problem using pylsp as the LSP. However, if the user is willing to switch to pyright, things seem to be working ok with the code mentioned previously in this issue. Hopefully, this could be helpful to others.

The relevant config codes are:

init.el:
`:editor`
`format` 
`:lang`
`(python +lsp + pyright +conda)`

config.org:
`(set-formatter! 'yapf "yapf --style=google " :modes '(python-mode))`
`(after! format-all (advice-add 'format-all-buffer :around #'envrc-propagate-environment))`

**Comment by dschrempf** [comment]
Hi, I was bumping into this with `format-all-mode`. The issue is, that wrapping `format-all-buffer` like purcell said above:
```
(advice-add 'format-all-buffer :around #'envrc-propagate-environment)
```
was not enough to fix formatting on save. It only fixes the environment propagation when explicitly calling `format-all-buffer`. Additionally, I had to wrap
```
(advice-add 'format-all-buffer--from-hook :around #'envrc-propagate-environment)
```
which is called when using `format-all-mode`.

**Comment by hlissner** [comment]
As of #6369's merge, the rewrite of the `:editor format` module is complete, which replaces format-all with apheleia. I'm not entirely sure yet if that resolves this issue, but please update and let me know if it does.
