### ISSUE TITLE
Workspace delete (SPC-TAB-d) does not remove saved workspace

### ISSUE THREAD

**Issue by ciolansteen** [doomemacs/doomemacs#4399]
Not sure if I got this right, but:

**What did you expect to happen?**
Since there's already SPC-TAB-x which kills current session for a workspace, i suppose workspace delete correct behaviour wold be to delete saved workspaces. 

**What actually happened?**
SPC-TAB-d does not delete the saved workspace from disk. 

**Steps to reproduce:**
1. Create new workspace SPC-TAB-n
2. Save newly created workspace to disk (SPC-TAB-s)
3.Try deleting current workspace (SPC-TAB-d)
4. Check if the deleted workspace is still present (SPC-TAB-l) 

**System information:**
<details><pre>
```
SYSTEM  type       gnu/linux
        config     x86_64-pc-linux-gnu
        shell      /bin/zsh
        uname      Linux 5.9.13-zen1-1-zen #1 ZEN SMP PREEMPT Tue, 08 Dec 2020 12:10:52 +0000 x86_64
        path       (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /usr/lib/emacs/27.1/x86_64-pc-linux-gnu/)
EMACS   dir        ~/.emacs.d/
        version    27.1
        build      Aug 28, 2020
        buildopts  --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
        features   XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
        traits     (gui server-running envvar-file)
DOOM    dir        ~/.doom.d/
        version    2.0.9
        font       #<font-object -ADBO-Source Code Pro-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1>
        theme      doom-one
        build      HEAD -> develop, origin/develop, origin/HEAD fbb8d1b99 2020-12-08 23:01:07 -0500
        elc-files  0
        modules    (:completion company ivy :ui doom doom-dashboard doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :checkers syntax :tools (eval +overlay) lookup magit :lang emacs-lisp markdown org sh :config (default +bindings +smartparens))
        packages   (n/a)
        unpin      (n/a)
        elpa       (n/a)
```
</pre></details>

**Comment by hlissner** [comment]
`SPC TAB d` was not designed to delete the saved file (and shouldn't, because deleting the workspace in the current session should be distinct from deleting its saved copy.

There is currently no command to do this, but I'm open to a PR to rename `delete` operations to `kill`, and introduce `+workspace/delete` + `+workspace-delete` to delete saved workspaces.

**Comment by ciolansteen** [comment]
Oh, thanks for clearing things up for me.

**Comment by ammunk** [comment]
This seems quite useful. It's probably not uncommon for people to be working on several projects (with saved workspaces) and wanting to incrementally remove old saved workspaces as their associated projects finish.

Is anyone working on this?

**Comment by JiaweiChenC** [comment]
I think we still need to do it manually today

**Comment by fnoon** [comment]
Where are workspaces saved on disk?  So that one may finally delete them.  My grep-foo is failing me tonight.

**Comment by hlissner** [comment]
@fnoon In `$EMACSDIR/.local/etc/workspaces/`. Set [here](https://github.com/doomemacs/doomemacs/blob/master/modules/ui/workspaces/config.el#L48).
