### ISSUE TITLE
Error (doom-init-hook) since commit 138ec2bf

### ISSUE THREAD

**Issue by dariooddenino** [doomemacs/doomemacs#446]
1) git checkout 138ec2bf
2) make and then launch emacs
3) `Error (doom-init-hook): void-function in 'helm-mode' -> Symbol's function definition is void: helm-mode`

That's the first checkout that gives me the error and I still get it with the last develop commit

**Comment by hlissner** [comment]
Try to delete `~/.emacs.d/.local/packages.el` then restart Emacs and see if that fixes your issue.

This is a temporary measure, I'm in the process of addressing issues with Doom's package management system.

**Comment by dariooddenino** [comment]
I get the same error. These are the steps in case I'm doing something wrong:
1 git checkout develop
2 delete `.emcas.d/.local/packages.el`
3 make
4 launch emacs

**Comment by dariooddenino** [comment]
Ok it works if I delete the file before launching emacs. I have to delete it everytime I want to launch it though :D

**Comment by hlissner** [comment]
Yikes! I'll look into this.

**Comment by hlissner** [comment]
Alright, this should resolve your issue with the bad cache. You may need to delete the file one last time though. Let me know if that isn't the case!

**Comment by azy2** [comment]
@hlissner I still have to delete `.emacs.d/local/packages.el` every time before launching emacs. For me `Helm-M-x` and `magit-status` are broken.

**Comment by dariooddenino** [comment]
It's fixed for me now

**Comment by hlissner** [comment]
@avy2 @dariooddenino I've just pushed a possible fix for your haskell, helm and magit issues. Let me know if it doesn't fix your issues.

**Comment by dariooddenino** [comment]
Looks like it's fixed now :)
