### ISSUE TITLE
[Discussion] The future of :editor format

### ISSUE THREAD

**Issue by Janfel** [doomemacs/doomemacs#4526]
## About This Issue

I’ve recently found out, that the `:editor format` module is scheduled for a rewrite, as mentioned in #3191 and in the header of [`modules/editor/format/README.org`][README.org]. However it seems that this replacement is currently not under active development. I have opened this issue to discuss some aspects of the current implementation that drove me away from using it, and to introduce you to a simple, flexible and formatter-independent approach which I am currently testing in [my own formatting module][fmt]. This module solves the issues I currently have with `:editor format` and makes it very easy for the user to define and integrate additional formatters. I also believe that it falls more in line with Dooms stated goals than using `format-all` or `apheleia`.
I’m looking forward to hearing your opinion on this.

## The Existing Module

As for the issues I have with the current `:editor format`, the main points are:

1. The tight integration with `format-all-the-code`.
2. The following rigidity and lack of extensibility outside the bounds of `format-all-the-code`.
3. The following complexity, as seen in the special-casing for `lsp-format` and `org-mode`.
4. The lack of “dynamic” formatters, meaning formatters that react to buffer-local variables such as `indent-tabs-mode`, `fill-column` and `standard-indent`.

The main benefits of `:editor format` being of course, that it provides a unified interface to all registered formatters that integrates well with Doom and Evil.

## My Module

The module is designed to be simple and close to the metal, in accordance with the Doom mantras. It takes a function following a simple contract, and provides an interface to easily format the current buffer or region. The function is executed within the current buffer so it can directly access all local variables.

The function variable is supposed to be configured using mode hooks (e.g. `setq-hook!`), file-local variables, etc. providing maximum flexibility. I am also thinking about adding a function to `after-change-major-mode-hook` looking up `major-mode` in a hashtable.

The module is designed to work seamlessly with `indent-region` and functions defined using [`reformatter.el`][reformatter.el]. `format-all` has been hacked to respect the restriction, which is necessary for fulfilling the contract. The formatters for `org-mode` and `lsp-mode` are implemented like every other formatter, without the need for special-casing.

These are some features my module does not have and also does not aim to implement:

- Use RCS patches to apply changes.
  This would incur unnecessary overhead when using something simple like `indent-region` and should be implemented on a per-formatter basis. Changing the formatter definition macro could help with that.
- Format code asynchronously.
  This would have to be implemented by each formatter individually, for the same reasons as the previous point. It could be done by defining a formatter that reads `buffer-file-name`, starts the external process and then returns, although I dont’t know how this would interact with the undo history.
- Restore the buffer when the formatter errors out.
  This could be done by copying the buffers contents into a variable before formatting, but I think this would be a disproportionate overhead for saving the user one call to `undo`.

Please note that this module is still a work-in-progress with features being added if and when I need them. I am also open to specific feedback should you find something I could improve on.

[README.org]: https://github.com/hlissner/doom-emacs/blob/develop/modules/editor/format/README.org
[fmt]: https://github.com/Janfel/doom-emacs-config/tree/master/modules/editor/fmt
[reformatter.el]: https://github.com/purcell/reformatter.el

**Comment by PrimaryCanary** [comment]
It appears we started work on a new formatting module at nearly the same time :). My work has been on Apheleia upstream (https://github.com/raxod502/apheleia/pull/24, https://github.com/raxod502/apheleia/pull/26) with the intent of preparing it for a Doom-ready formatting solution.

Firstly, I have a few comments.
- Your solution is fantastic. The code is elegant and more flexible than the Apheleia-based one I am working on.
- Seamlessly working with `indent-region` is something `format-all-the-code` and Apheleia have trouble with. Kudos.
- I don't see any default formatters in the module. If I'm wrong about this, feel free to disregard this comment. I believe defaults should be provided. After all, One of Doom's mantras is providing sensible defaults. I'd be happy to provide them if requested.

Secondly, I want to explain why I chose Apheleia over `reformatter.el`.
- I value asynchronicity more than some of the other points listed. As the Apheleia README states, running Black on an empty file can take hundreds of milliseconds. If the formatter isn't run asynchronously, the UI is blocked for the entire time. I find this to be a poor UX.
- I aimed to create a module that is mostly backward compatible with the current one. If a user updated Doom and unknowingly started using Apheleia, they might not even need to change their config to enjoy the benefits! Without a bank of default formatters and potentially improperly formatted buffers, this module may have a slightly less smooth migration period.
- I aimed to supply as many user-facing improvements as possible. For example, forgoing the need to special case `org-mode` and `lsp-mode`, while elegant, isn't visible to the user. Asynchronous formatting and a stable point are.

All in all, I find your solution to be flexible and elegant. If it were outfitted with a bank of default formatters and asynchronous formatting, I'd much prefer it to my own.

CCing @hlissner for comments and to see which approach he would prefer.

**Comment by Janfel** [comment]
Thanks for the nice comment, I’m glad you like it. I have moved some of my formatters from my `$DOOMDIR/autoload` into the module, with the defaults still being provided by `format-all`. Feel free to PR if you want to add some more. I might also split the module into it’s own repository, if I can figure out the necessary `git` magic.

Regarding asynchronicity and RCS patching, I would very much prefer to have those implemented in `reformatter.el` directly. The alternative would be rolling my own code for defining command line formatters, and manintaining a de-facto fork of `reformatter.el`, which I am not ready to do. Once that is done, my module should require little to no further modifications to use these features.

**Comment by Janfel** [comment]
There is some discussion in https://github.com/purcell/reformatter.el/pull/24 about adding RCS patching to `reformatter.el` and merging `reformatter.el` with Apheleia.

**Comment by Janfel** [comment]
As far as I can tell, this issue is still relevant.

**Comment by ch1bo** [comment]
What's the status of this?

I :heart: `doom-emacs` but do struggle a bit with (auto-)formatting and would like to dive into this a bit.. but if everything changes, this feels a bit in vain.

**Comment by npajkovsky** [comment]
How can I test/use your new implementation? `:editor format` drives me crazy.

**Comment by Janfel** [comment]
@npajkovsky I have now split the module into it’s own repository, see https://github.com/Janfel/doom-emacs-module-editor-fmt. You can pull it into your config at `$DOOMDIR/modules/editor/fmt` using `git clone`. Then you just have to enable `:editor fmt` in your `$DOOMDIR/init.el` and run `doom sync`.

You can rebind the `:editor format` bindings like this:
```elisp
(map! :when (featurep! :editor fmt)
      :nv "g =" #'+fmt:region
      :map doom-leader-code-map
      :desc "Format buffer/region" "f" #'+fmt/dwim)
```

And for overriding the defaults you can use code like in this example:
```elisp
(setq-local! 'emacs-lisp-mode +fmt-formatter #'indent-region)
```

I will also put this documentation in the repository once I get around to writing a README.

**Comment by noghartt** [comment]
Hey, can you help me to add `formatter.el` on `typescript-mode`?

Do you know how can I do it?

**Comment by Janfel** [comment]
As far as I can tell, this issue is still relevant.

**Comment by Janfel** [comment]
As far as I can tell, this issue is still relevant.

**Comment by goetzc** [comment]
This issue is still relevant, bot.

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. If you have ideas on how to improve the new module, please move the conversation to [our discourse](https://discourse.doomemacs.org), where discussion is easier to follow.
