### ISSUE TITLE
lsp-ui-peek: TAB not working correctly

### ISSUE THREAD

**Issue by futile** [doomemacs/doomemacs#5028]
### What did you expect to happen?

When browsing the references window of `lsp-ui-peek-find-references` (`gD` with `(lsp +peek)` and `(lookup)`), pressing `TAB` should toggle the file I have selected, so I can see/hide the references in that file.

### What actually happened?

However, when I hit `TAB`, instead the peek-window closes, which seems identical to the behavior when pressing `TAB` regularly, i.e., when not in a peek-window. I think this is `indent-for-tab-command`.

The echo area shortly contains `No matching item found on the current line`, which appears in `*Messages*` as `user-error: No matching item found on the current line`.

### Describe your attempts to resolve the issue

I tried checking the available keybindings in the peek-window by doing `C-h b t`, which does list `TAB lsp-ui-peek--toggle-file`, but at the same time `C-h b t` also causes the peek-window to close.

### Steps to reproduce

1. Open doom-emacs with the `(lsp +peek)` and `(lookup)` modules active.
2. Open a project for which a lsp-server is configured, for example a python project (requiring `(python +lsp)`).
3. Move cursor to a symbol that has multiple references to it and press `gD`, which will open the peek-window.
4. Move selection to a _file_ (not a reference) and press `TAB`.
5. Instead of toggling the matches in the file, the peek-window closes.

(This probably does not require `(lookup)`, and can instead be triggered by doing `M-x lsp-ui-peek-find-references` instead of `gD`).

### System Information

https://pastebin.com/pEuCpnJV

**Comment by futile** [comment]
Okay, I just noticed that pressing "enter" instead of TAB does toggle the file. So there definitely is a workaround, but it seems like `TAB` is still intended to toggle it (https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-peek.el#L546).

**Comment by futile** [comment]
Just checked, and #5072 didn't fix the issue (for me). TAB still closes the peek-window (RET still works).

**Comment by hlissner** [comment]
Sorry for the tremendously late response. I've discovered that the cause for this is that `lsp-ui-peek` only binds the `"TAB"` key event and not the `[tab]` key event. GUI Emacs invokes the latter event. Emacs will search down the keymap hierarchy for a `[tab]` event before it searches for a `"TAB"` event.

This is technically an upstream issue and should be reported to [lsp-ui](https://github.com/emacs-lsp/lsp-ui/issues).

In the meantime, the workaround is to bind the key yourself:

```elisp
(map! :after lsp-ui
      :map lsp-ui-peek-mode-map
      [tab] #'lsp-ui-peek--toggle-file)
```

I'll keep this open until it has been addressed upstream.

**Comment by futile** [comment]
[My PR](https://github.com/emacs-lsp/lsp-ui/pull/686) that fixes the issue upstream was merged (basically your solution, so thanks a lot!), do you want to close this now or keep this open until it's in the version lsp-ui that doom downloads? Thanks again for your help in finding the issue, super nice!

**Comment by futile** [comment]
Fixed in my current (pretty recent) version of doom, so going to close this issue. Thanks again for the help!
