### ISSUE TITLE
prettier should show up as markdown mode's dependencies

### ISSUE THREAD

**Issue by tleydxdy** [doomemacs/doomemacs#5130]
### What did you expect to happen?

doom doc should suggest me to install prettier when markdown support is enabled. perhaps doom should know to not try and format the buffer when prettier is missing.

### What actually happened?

doom doc doesn't say I have missing dependency for markdown, but every time I want to save a markdown document an error pop up with 
```
Error (before-save-hook): Error running hook "+format-buffer-h" because: (error You need the "prettier" command. You may be able to install it via "npm install --global prettier @prettier/plugin-php prettier-plugin-solidity".)
```

### Describe your attempts to resolve the issue

Installing prettier seems to make doom happy.

### Steps to reproduce

enable markdown support without having prettier in the system

### System Information

https://pastebin.com/UWDyNAkS

**Comment by jcf** [comment]
There's an approved [pull request](https://github.com/hlissner/doom-emacs/pull/5123) to warn if `shfmt` isn't available. The same could be done for `prettier`.

**Comment by tleydxdy** [comment]
cool, the main thing for me is that the error popup is very annoying. markdown is a fairly free form format so I would think many would choose not use a formatter with it, esp one that depends on nodejs. so some way to make the error go away would be nice.

**Comment by jcf** [comment]
@tleydxdy you can [disable `:editor format`](https://github.com/hlissner/doom-emacs/tree/develop/modules/editor/format#disabling-the-lsp-formatter) on save with something like this:

``` elisp
(when (featurep! :editor format)
  (setq +format-on-save-enabled-modes
        '(not emacs-lisp-mode
              latex-mode
              org-msg-edit-mode)))
```

**Comment by fosskers** [comment]
Yup I intend to do a sweep of the rest of the formatting tools and add `doom doctor` checks for whatever is missing. I can add `prettier` right now for you.

**Comment by hlissner** [comment]
Not too long ago, the `:editor format` module switched from format-all to apheleia, so I'm closing all issues related to format-all. Thanks for bringing this to my attention, in any case!
