### ISSUE TITLE
format-all-buffer--from-hook fails with formatter set by direnv from nix

### ISSUE THREAD

**Issue by ehamberg** [doomemacs/doomemacs#5147]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

When I open a go file in a project using direnv + nix, I expected the file to be formatted automatically on save using the `gofmt` from nix that was added to the PATH by direnv.

### What actually happened?

I get this error when saving a file: `Error (before-save-hook): Error running hook "format-all-buffer--from-hook" because: (file-missing Searching for program No such file or directory gofmt)`.

### Describe your attempts to resolve the issue

- Ensured that direnv succesfully loads when opening the project. It is: “Direnv succeeded in [project dir]” is printed.
- Ran `SPC p ! which gofmt<ENTER>` which shows the correct executable path.
- ~Checked if `SPC c f` works, **and it does**, but the `format-all-buffer--from-hook` error is still shown when saving the file.~ This is no longer the case.

git bisecting shows that this started happening on 2 June with 72c3a79, but reverting that commit on `develop` (currently at b2376a84) does not fix the issue.

Reverting  72c3a79 works until 68b422c7, after which the problem persists, even if 72c3a79 is reverted.

### Steps to reproduce

1. Create a new directory
2. Create `shell.nix` with contents:

```
{ pkgs ? import <nixpkgs> {} }:
with pkgs;

mkShell {
  buildInputs = [ go ];
}
```

3. Create`.envrc` with contents:

```
use_nix
```

4. Create `hello.go` with contents:

```go
package main

import "fmt"

func main() {
fmt.Println("Hello World!")
}
```

5. Make a change in the file
6. Save the file
7. Observere that the error `Error (before-save-hook): Error running hook "format-all-buffer--from-hook" because: (file-missing Searching for program No such file or directory gofmt)` is printed in the `*Warnings*` buffer.
8. ~(Bonus) Run `SPC c f` and observe that the file is correctly formatted.~ This is no longer the case. (Tested with 2d2246d7ca5ec084f4bee9a5de14256eb6828837)

### System Information

https://pastebin.com/8cKrLHg2

**Comment by terinjokes** [comment]
I observe the same problem with dependencies added by direnv on NixOS, but doesn't look like step 8 (running `(+format/region-or-buffer)`) correctly formats.

**Comment by ehamberg** [comment]
Yeah, running `(+format/region-or-buffer)` no longer works in a Go file.

Formatting with a formatter from direnv + nix seems to work in Typescript and Haskell files, but not in Go or Erlang files.

**Comment by shanesveller** [comment]
I had slightly better luck applying the advice to `format-all-buffer--with` instead, but that suggestion helped me!

**Comment by teehemkay** [comment]
I'm seeing a similar issue running `nix-darwin` + `direnv` for JavaScript projects where the `prettier` script in `node_modules/.bin` is correctly launched but it cannot find the `nodejs` setup by `direnv`

```sh
/Users/<username>/hacking/maps/node_modules/.bin/prettier: line 16: exec: node: not found
```

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. Please open a new issue if this (or other) issues present themselves with the new implementation.
