### ISSUE TITLE
Powerline font symbols not rendering correctly

### ISSUE THREAD

**Issue by betaprior** [doomemacs/doomemacs#5160]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

Special symbols commonly used for custom prompts and tmux status lines (see, for example https://github.com/gpakosz/.tmux) display correctly in vanilla Emacs and used to also display correctly in Doom. Example from vanilla emacs:
![image](https://user-images.githubusercontent.com/338250/121324931-08b39a00-c8c6-11eb-916d-12aa9f924f6e.png)

### What actually happened?

The symbols displayed are incorrect. Changing the font does not help.
![image](https://user-images.githubusercontent.com/338250/121325366-634cf600-c8c6-11eb-9dab-19c66878f36c.png)

### Steps to reproduce

1. Install powerline fonts from https://github.com/powerline/fonts
2. In Doom, open vterm and type `printf '\uE0B0'`. Alternatively, do `printf '\uE0B0' > mytempfile`, and open that file in Doom.
3. Compare the symbol that you see to the one echoed in the terminal (e.g. gnome-terminal)

### System Information

https://pastebin.com/xaxJH0Eg

**Comment by betaprior** [comment]
This regression was introduced in d4dec3565870b96abff0f08f1b638b9d527a7086 and can be fixed by setting

```
(setq doom-emoji-fallback-font-families nil)
```

And look, I get it, we all love emoji but breaking neckbeards' carefully crafted powerline and tmux status bars just so some millenial idiot can use a poop emoji is pretty 💩💩💩

**Comment by bersace** [comment]
I use `(setq doom-meoji-fallback-font-families '("icons-in-terminal"))`. This fixes more than Powerline Symbols.

**Comment by Schievel1** [comment]
![2022-09-05 15_16_17-_vterm_ – Doom Emacs](https://user-images.githubusercontent.com/85408625/188458571-78282a8b-8822-4196-9129-f14dd240fb41.png)

This is still happening for me, even though I set `(setq doom-meoji-fallback-font-families '("icons-in-terminal"))` (Also tried nil)

**Comment by joobus** [comment]
I did figure out how to get the right chevron thing to show up instead of the telephone.

`(set-fontset-font t \`57520 "UbuntuMono Nerd Font Mono" nil \`prepend)`

To find the codepoint of the telephone, use `describe-char`, in this case `57520`.  Then find the name of your nerd font; on linux I used `fc-list`, then `fc-query fontfile.ttf`.

I put the above code in my `doom/config.el`.
