### ISSUE TITLE
M-ret won't create org mode headline above current

### ISSUE THREAD

**Issue by bobf32** [doomemacs/doomemacs#5180]
### 

- [X] I have searched [the FAQ](https://doomemacs.org/docs/faq.org) and [the documentation](https://doomemacs.org/docs/getting_started.org) for solutions.
- [X] I have searched [the issue tracker](https://github.com/hlissner/doom-emacs/issues) for similar issues (the closed issues too).
- [X] I have searched [the Discourse](https://doomemacs.org/d/docs) for any errors and solutions.
- [X] I can reproduce my issue on [the latest commit](https://github.com/hlissner/doom-emacs/commit) of Doom Emacs.
- [X] I have read [How to Debug Issues](https://doomemacs.org/d/how2debug) and found no solution.

### What did you expect to happen?

M-ret in an org mode headline will not insert a heading above the current one.

### What actually happened?

Hitting M-ret always inserts a headline below the current one.

### Describe your attempts to resolve the issue

I have since discovered insert-item-above (C-S-ret) which appears to do what I want. Am still interested in why M-ret doesn't appear to function as advertised.

### Steps to reproduce

1. Open emacs
2. Open an org file
3. Place cursor at beginning of line on a headline
4. M-ret

New headline always created under the current one.

### System Information

https://pastebin.com/yYMGxX0D

**Comment by bobf32** [comment]
Hi, has anyone had a chance to look at this? I just noticed is still an issue.

**Comment by hlissner** [comment]
This is because Doom sets `org-insert-heading-respect-content` to `t`. Set it to `nil` to make `M-ret` insert before the heading. I.e.

```elisp
(after! org
  (setq org-insert-heading-respect-content nil))
```

See `C-h v org-insert-heading-respect-content` for documentation on the variable.
