### ISSUE TITLE
Cannot change the default latex-viewer.

### ISSUE THREAD

**Issue by pipiTan** [doomemacs/doomemacs#5275]
### What did you expect to happen?

change latex viewer.

### What actually happened?

Although I've install Skim and zathura, latex viewer is always the docview(pdfview). 
I add (setq +latex-viewers ...) manually in config.el, and it's still the docview(pdfview).

### Steps to reproduce

enable latex module in init.el, and then change the default latex viewer.

### System Information

https://pastebin.com/3bvgQVte

**Comment by dmorady1** [comment]
Hi, i had some similar issues but i could change the pdf viewer with `TeX-view-program-selection`
The first entry in the `TeX-view-program-selection` will be chosen to open your pdf
```elisp
(after! tex 
 (setq TeX-view-program-selection
        '(
          (output-pdf "PDF Tools")
          (output-pdf "Zathura")
          (output-pdf "Okular")
         (output-pdf "preview-pane")
          ((output-dvi has-no-display-manager)
           "dvi2tty")
          ((output-dvi style-pstricks)
           "dvips and gv")
          (output-dvi "xdvi")
          (output-pdf "Evince")
          (output-html "xdg-open")
         )))
```

For example you can try to use Zathura then e.g. 

```elisp
(after! tex 
 (setq TeX-view-program-selection
        '(
         (output-pdf "Zathura")
          (output-pdf "PDF Tools")
          (output-pdf "Okular")
         (output-pdf "preview-pane")
          ((output-dvi has-no-display-manager)
           "dvi2tty")
          ((output-dvi style-pstricks)
           "dvips and gv")
          (output-dvi "xdvi")
          (output-pdf "Evince")
          (output-html "xdg-open")
         )))
```

**Comment by pipiTan** [comment]
@dmorady1 
:( 
it doesn't work on my device. it seems the variable **TeX-view-program-selection** doesn't exit and i can't find any similar variable as well.

**Comment by vancleve** [comment]
I think the problem is that setting `(setq +latex-viewers '(pdf-tools skim))` by itself doesn't do anything without the file `+viewers` getting run. Not only that, if you're just rearranging the order of viewers, `add-to-list` won't modify the list. I found that the following works for me:
```lisp
(after! tex
  (setq TeX-view-program-selection nil)
  (setq +latex-viewers '(pdf-tools skim))
  (load! "../.emacs.d/modules/lang/latex/+viewers"))
```

Maybe this is a bug because the documentation suggests that by you only need to modify the `+latex-viewers` to get the list of viewers in the order you want.

**Comment by maikol-solis** [comment]
> ```lisp
> (after! tex
>   (setq TeX-view-program-selection nil)
>   (setq +latex-viewers '(pdf-tools skim))
>   (load! "../.emacs.d/modules/lang/latex/+viewers"))
> ```

Thanks. The snippet worked for me also.

**Comment by ieremies** [comment]
Neither the above script nor the documented way (`setq +latex-viewers`) works for me... What is even more bizarre is that it opens it in pdf-tools, even thought I have zathura and the default value place it before pdf-tools.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/03e5f1333ccd183939a62cf9b7999030553d67aa, this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Panquesito0** [comment]
> Hi, i had some similar issues but i could change the pdf viewer with `TeX-view-program-selection` The first entry in the `TeX-view-program-selection` will be chosen to open your pdf
> 
> (after! tex 
>  (setq TeX-view-program-selection
>         '(
>           (output-pdf "PDF Tools")
>           (output-pdf "Zathura")
>           (output-pdf "Okular")
>          (output-pdf "preview-pane")
>           ((output-dvi has-no-display-manager)
>            "dvi2tty")
>           ((output-dvi style-pstricks)
>            "dvips and gv")
>           (output-dvi "xdvi")
>           (output-pdf "Evince")
>           (output-html "xdg-open")
>          )))
> For example you can try to use Zathura then e.g.
> 
> (after! tex 
>  (setq TeX-view-program-selection
>         '(
>          (output-pdf "Zathura")
>           (output-pdf "PDF Tools")
>           (output-pdf "Okular")
>          (output-pdf "preview-pane")
>           ((output-dvi has-no-display-manager)
>            "dvi2tty")
>           ((output-dvi style-pstricks)
>            "dvips and gv")
>           (output-dvi "xdvi")
>           (output-pdf "Evince")
>           (output-html "xdg-open")
>          )))

I CAN'T stress enough how much this answers have helped me. 

THANK U. Hope you're having a nice life.
