### ISSUE TITLE
Doom sync does not find git executable

### ISSUE THREAD

**Issue by kmschmidt91** [doomemacs/doomemacs#5356]
### What did you expect to happen?

Doom sync to complete without errors

### What actually happened?

When I run `doom sync`, I receive the error below:

```
Data: (error . "Straight unable to find required executable: \"git\"")
  Backtrace:
    (signal error ("Straight unable to find required executable: \"git\""))
    (error "Straight unable to find required executable: %S" "git")
    (or (executable-find name) (error "Straight unable to find required execut
    (straight--executable-find "git")
    (eval-buffer #<buffer  *load*-565962> nil "/home/kevin/.emacs.d/.local/str
    (load-with-code-conversion "/home/kevin/.emacs.d/.local/straight/repos/str
    (require straight "/home/kevin/.emacs.d/.local/straight/repos/straight.el/
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
    (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch 
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
No catch for tag: exit, 255

Comint exited abnormally with code 255 at Sun Aug  8 00:11:34
```

### Describe your attempts to resolve the issue

I tried disabling magit as I believed it to be causing the error, however, the error persisted. It also appears to be interfering with the installation of other packages as well. After attempting to install org-superstar-mode I received the same error upon sync.

The error persisted after a reinstall of Emacs and Doom Emacs as well.

### Steps to reproduce

Run 'doom sync'

### System Information

https://pastebin.com/Q467KNGV

**Comment by oeyoews** [comment]
> ### What did you expect to happen?
> Doom sync to complete without errors
> 
> ### What actually happened?
> When I run `doom sync`, I receive the error below:
> 
> ```
> Data: (error . "Straight unable to find required executable: \"git\"")
>   Backtrace:
>     (signal error ("Straight unable to find required executable: \"git\""))
>     (error "Straight unable to find required executable: %S" "git")
>     (or (executable-find name) (error "Straight unable to find required execut
>     (straight--executable-find "git")
>     (eval-buffer #<buffer  *load*-565962> nil "/home/kevin/.emacs.d/.local/str
>     (load-with-code-conversion "/home/kevin/.emacs.d/.local/straight/repos/str
>     (require straight "/home/kevin/.emacs.d/.local/straight/repos/straight.el/
>     (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el")
>     (doom--ensure-straight (:host github :repo "raxod502/straight.el" :branch 
>     (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (pli
> ! Extended backtrace logged to ~/.emacs.d/.local/doom.error.log
> No catch for tag: exit, 255
> 
> Comint exited abnormally with code 255 at Sun Aug  8 00:11:34
> ```
> 
> ### Describe your attempts to resolve the issue
> I tried disabling magit as I believed it to be causing the error, however, the error persisted. It also appears to be interfering with the installation of other packages as well. After attempting to install org-superstar-mode I received the same error upon sync.
> 
> The error persisted after a reinstall of Emacs and Doom Emacs as well.
> 
> ### Steps to reproduce
> Run 'doom sync'
> 
> ### System Information
> https://pastebin.com/Q467KNGV

try this command `doom env`

**Comment by kmschmidt91** [comment]
That worked! I must have run those commands out of order. Thanks for the help!

**Comment by BlueDrink9** [comment]
@kmschmidt91 please close this issue

**Comment by Jdogzz** [comment]
@hlissner Looks like this one can be closed as it was resolved by OP?
