### ISSUE TITLE
everytime launch doom emacs, Mapping Unicode Blocks in fontset-standard job is started

### ISSUE THREAD

**Issue by jjpark78** [doomemacs/doomemacs#5387]
### What did you expect to happen?

mapping unicode font mapping runs only once

### What actually happened?

everytime i relaunch doom emacs, 
mapping unicode block job is started. make me wait for a while. 

### Describe your attempts to resolve the issue

i have no idea

### Steps to reproduce

1. use Manjaro WSL2 distro
2. install gccemacs with emacs-git package
3. install doom emacs
4. set FiraMono NF font to default (i've checked with `fc-list | grep fira` command, i do have that font installed)
5. launch doom emacs and see mapping fonts job has beem started.
6. restart doom emacs. and .... 

### System Information

https://pastebin.com/91FVPDyB

**Comment by ymarco** [comment]
This is an issue with the `:ui unicode` module. Henrik said this on discord a while ago:
> It should cache it the first time, then future boots should be quick. But some people have reported that it doesn't (though I can't reproduce it). Your only alternative is to disable the `:ui unicode` module
> Ah, seems to be a known issue: https://github.com/rolandwalker/unicode-fonts/issues/21

**Comment by jjpark78** [comment]
oh i see. i will try that solution https://github.com/rolandwalker/unicode-fonts/issues/21

**Comment by hlissner** [comment]
As of /sigma/pcache#17, this should be resolved. Since it's not a pinned package, it should update the next time you run `doom sync -u` or `doom upgrade`. Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!
