### ISSUE TITLE
 `org-capture` doesn't restart defered buffers

### ISSUE THREAD

**Issue by vherrmann** [doomemacs/doomemacs#5411]
### What did you expect to happen?

After i start emacs, open the agenda with "SPC o A a" and capture sth in my inbox with "SPC X", the capture buffer should just open.

### What actually happened?

Instead of the capture buffer, at first a file select buffer is opened (like find-file) with the prompt "File to load from" and the directory "~/org/gtd". Though it doesn't matter which file i select. 
![screen_2021-08-24_11-16-22](https://user-images.githubusercontent.com/50072577/130590990-a607703c-ae3f-4a4c-9299-869f989b86cd.png)
(I used my real config for the screenshots, but the same happens with the config in the „Steps to reproduce“ part)

After that, the capture buffer is opened but without an active org-mode, the buffer is just grayed out.

![screen_2021-08-24_11-16-25](https://user-images.githubusercontent.com/50072577/130591012-aaa2d008-ab2d-4afa-95ef-b3b1c3a30660.png)

### Describe your attempts to resolve the issue

I think i found the problem, though I'm not sure how to fix it. I'm pretty sure that the defered buffers, which are normally restarted by `+org--restart-mode-h` when you visit them, aren't because org-capture opens them. Probably the `doom-switch-buffer-hook` isn't executed when emacs switches to the org-capture buffer.

### Steps to reproduce

For a minimal example the following "config.el"t is needed:
```
(use-package! org-agenda
  :after org
  :custom
  (org-agenda-files (list "~/org/gtd")))

(use-package! org-capture
  :after org
  :custom
  (org-capture-templates
       `(("i" "inbox" plain (file "~/org/gtd/inbox.org")
          "* TODO %?\n"))))

```
there should also be "~/org/gtd/inbox.org" and an init.el with org-mode activated. 

### System Information

the output of "https://pastebin.com/tVrgCpNE". Iirc i had this issue on guix and emacs 27.2 as well

**Comment by nathanen** [comment]
I had this issue as well.  I do not know what the underlying cause it, but when I removed the following code that relates to org-super-agenda, the problem went away.  I have tried to isolate what exactly is happening when org-super-agenda categorizes things, but this is a real mystery to me

;; organize super-agenda by category
(let ((org-super-agenda-groups
       '((:auto-category t))))
  (org-agenda-list))

;; organize todo list by file/category
(add-to-list 'org-agenda-custom-commands
    '("t" "All TODOs groups by category" alltodo ""
        ((org-super-agenda-groups '((:auto-category t))))
    ))

**Comment by psamim** [comment]
I have this issue as well and I am not using org-super-agenda.

**Comment by yuchen-lea** [comment]
I think the cause of the issue is here: https://github.com/doomemacs/doomemacs/issues/4832#issuecomment-822845907

`(defalias '+org--restart-mode-h #'ignore)` can fix the problem of inactive org-mode in org-capture, but it also causes the org-mode file to fail to load `org-mode-hook` normally. We need better solutions

**Comment by hlissner** [comment]
Does this fix the issue?

```elisp
;;; add to $DOOMDIR/config.el
(add-hook! 'org-capture-mode-hook
  (defun +org--restart-mode-maybe-h ()
    (when (memq #'+org--restart-mode-h doom-switch-buffer-hook)
      (+org--restart-mode-h))))
```

**Comment by real-or-random** [comment]
@hlissner AFAIU, my PR https://github.com/doomemacs/doomemacs/pull/7618 had already fixed this issue. I was just not aware of this old report here. 

Are you sure https://github.com/doomemacs/doomemacs/commit/b0e16dc24332f7334a8b2aee9cad342079a63676 is the right thing to do? I am not convinced that the advice should be restricted only to `org-capture-get-indirect-buffer`, the problem will appear with other indirect buffers too. (And if we believe that it should be restricted to `org-capture-get-indirect-buffer`, then the comment should be changed a bit.)

**Comment by hlissner** [comment]
> Are you sure https://github.com/doomemacs/doomemacs/commit/b0e16dc24332f7334a8b2aee9cad342079a63676 is the right thing to do? I am not convinced that the advice should be restricted only to org-capture-get-indirect-buffer, the problem will appear with other indirect buffers too.

@real-or-random I believe so. I reviewed org's codebase for `make-indirect-buffer` calls and similar, and the only use I found that needed a `+org--restart-mode-h` was org-capture's. The rest were solely for internal/invisible operations, or on org-mode buffers that would most certainly already be fully fledged (e.g. `org-tree-to-indirect-buffer` is meant to be called interactively *from* a fully-fledged org-mode buffer, so its indirect clones won't ever need resetting).

So it seemed safe to narrow the scope of the advice (though, admittedly, that doesn't rule out how 3rd party org plugins; I'll dig around some more).

> And if we believe that it should be restricted to org-capture-get-indirect-buffer, then the comment should be changed a bit

Oops, forgot about that. Will do!

**Comment by real-or-random** [comment]
> (though, admittedly, that doesn't rule out how 3rd party org plugins; I'll dig around some more).

Yeah, this was my concern, plus other unrelated packages making indirect buffers, which may still happen to visit org files. An `rg -uu make-indirect-buffer` in my emacs dir gives just a single example: `magit-ediff-buffers` calls it (though only if you set a not recommended setting), and I haven't thought whether this will need a restart.

But okay, it seems reasonable to err on the side of performance here. We can always revert, or add the advice to more functions if issues appear.
