### ISSUE TITLE
org-set-tags-command infinite loop

### ISSUE THREAD

**Issue by OrionRandD** [doomemacs/doomemacs#5445]
### What did you expect to happen?

When I fire org-set-tags-command it pops up a list of words then I choose one or a few words and hit ENTER to get out from the list, but it keeps asking me to enter more tags...

The only way for me to get out of the loop is to hit 
C-g or ESC, but then it kills the buffer and does not set my tags...
:( 

### What actually happened?

error org-set-tags-command

### Describe your attempts to resolve the issue

error org-set-tags-command

### Steps to reproduce

error org-set-tags-command

### System Information

error org-set-tags-command

**Comment by Jdogzz** [comment]
@OrionRandD Are you still able to reproduce this behavior? I use org-set-tags-command on a regular basis and after hitting Enter it always closes the selection menu and appends the tags to the relevant headline.

https://pastebin.com/Ex5MYLcD

**Comment by OrionRandD** [comment]
> @OrionRandD Are you still able to reproduce this behavior? I use org-set-tags-command on a regular basis and after hitting Enter it always closes the selection menu and appends the tags to the relevant headline.
> 
> https://pastebin.com/Ex5MYLcD

Thx a lot for replying...
It is working properly now...
