### ISSUE TITLE
ccls.xref fails

### ISSUE THREAD

**Issue by nikos-alexandris** [doomemacs/doomemacs#5470]
### What did you expect to happen?

In C mode the code lens that shows the refs should list all the references when clicked on.

### What actually happened?

Instead, it throws an error:

LSP :: `workspace/executeCommand' with `ccls.xref' failed.
(wrong-type-argument json-value-p ccls\.xref)

### Describe your attempts to resolve the issue

I have removed the line from modules/lang/cc/config.el as advised

;; :hook (lsp-lens-mode . ccls-code-lens-mode)

and i correctly get one lens but it crashes as mensioned.

### Steps to reproduce

I have enabled lsp
I have enabled cc +lsp
I have removed the problematic line from modules/lang/cc/config.el

### System Information

https://pastebin.com/2a9ZBPrw

**Comment by scrag0r** [comment]
The bug seems to be in emacs-ccls:
https://github.com/emacs-lsp/emacs-ccls/pull/108
This pull-request fixed it for me
