### ISSUE TITLE
Some ligatures overrided by all-ths-icons font

### ISSUE THREAD

**Issue by bronislav** [doomemacs/doomemacs#5474]
### What did you expect to happen?

I have ligatures enabled in my `init.el` with pragmata-pro flag:

```lisp
(ligatures +pragmata-pro)
```

I have font set to PragmataPro Mono Liga in my `config.el`:
```elisp
;; Use PragmataPro font
(setq doom-font
      (font-spec :family "PragmataPro Mono Liga" :size 14 :weight 'regular))
```

And I expect correct ligatures to used when I type certain symbols sequence.

### What actually happened?

But some ligatures are loaded from all-the-icons font instead, for example:
<img width="314" alt="Screen Shot 2021-09-13 at 3 25 40 PM" src="https://user-images.githubusercontent.com/125880/133164370-0b2ca635-f6bb-4d6d-bede-4ec8fc07998c.png">

In the example above "&&" should be replaced with `#Xe92d` symbol from PragmataPro but actual symbol is loaded from the all-the-icons font.

### Describe your attempts to resolve the issue

1. I tried to switch to the version from https://github.com/hlissner/doom-emacs/pull/5359 but neither version works for me. Because ligatures are loaded from wrong font. 
1. I did reinstall all-the-icons font (didn't helped) 

### Steps to reproduce

Enable ligatures and try particular sequences of characters. Same behavior observed if ligatures enabled without any additional font flags.

### System Information

https://pastebin.com/xX77mfhW

**Comment by Tomahna** [comment]
I had the same issue. It seems that the symbols are using doom-unicode-font instead of doom-font. I'm not sure if it is the intended behavior.
 
Adding ```(setq doom-unicode-font (font-spec :family "PragmataPro Mono Liga"))``` seems to fix the problem.
