### ISSUE TITLE
Add +org-fragtog to org mode

### ISSUE THREAD

**Issue by shenlebantongying** [doomemacs/doomemacs#5476]
### Describe your request

Add `org-fragtog` to `:lang org` as an option `+fragtog`

https://github.com/io12/org-fragtog

### Briefly explain its use-case

1. Writing massive latex symbols & small equations require frequent `preview` ⇄ `edit` toggling. Org comes with only manual toggling, which is a major "thinking blocker".
2. In vanilla org, once you move the cursor to a latex preview box,  the only thing you can do is manually toggling between `preview` ⇄ `edit`.  You can do nothing else. Since this is the only option, why not make it automatic?

This mode is like the missing piece of latex editing for org mode. It is swify and fluent the latex editing experience on org.

**Comment by shenlebantongying** [comment]
What do you think? I can make a pull request (with doc included) if you consider this is a good addition.

**Comment by samhedin** [comment]
I've used org-fragtog since I saw this post and it's amazing. Can't imagine working without it now, it almost feels like it should be included in org-mode itself.

**Comment by shenlebantongying** [comment]
I have written a lot of raw latex math now. Raw latex math is good enough; I can even deduce equations with them.

Just try properly adding more spaces and indents to make complex ones look good. This also makes your colleagues' lives easier if they use less powerful editors.

Also, try writing all calculations on paper or a digital notebook first and have everything clarified before tying them in latex so that you can type once and never look back. There is no need to look back at those inline raw latex math.
