### ISSUE TITLE
Poor vertical alignment of vertico options

### ISSUE THREAD

**Issue by memeplex** [doomemacs/doomemacs#5566]
### What did you expect to happen?

When shown a list of tabulated options in the minibuffer, each column is properly aligned.

### What actually happened?

Length of any column propagate to the next one. I understand you maybe don't want the worst case to compromise the rest and also don't want to truncate the name of the option, but the current algorithm fails in ways that are avoidable and unaesthetic to the point that no pretension of tabulation at all would have been preferable.

![image](https://user-images.githubusercontent.com/2845433/135738865-c3cf4ae9-0c1a-4ebf-9052-cdf67738282a.png)

![image](https://user-images.githubusercontent.com/2845433/135738800-45e622a0-1678-4915-84d4-ff91aa083056.png)
 
Short of widening the first column to fit the longest entry or truncating the first column, I see two alternatives here:
* avoid tabulation altogether
* avoid propagating displacements more than which is strictly necessary (this will mainly improve the alignment of the documentation column -the last one-).

### Steps to reproduce

1. Open emacs
2. Press C-h v dict

### System Information

https://pastebin.com/udw0q8ck

**Comment by memeplex** [comment]
I think this is all managed by marginalia so maybe there's not much to be done downstream. If that's so please feel free to close the issue.

**Comment by iyefrat** [comment]
This is indeed a known upstream marginalia issue, unfortunately.

**Comment by memeplex** [comment]
I've been tracking this with upstream in https://github.com/minad/marginalia/issues/95 and @minad has submitted a change that fixes the issue for all mine (and probably anyone's) practical purposes. Maybe you want to check it and update.

**Comment by memeplex** [comment]
Well I spoke too soon it seems, apparently it's worse for large screens so the fix was reverted. I'm studying the code to see if I can figure out a sensible trade off.

**Comment by agzam** [comment]
@memeplex Do you have a wide or ultra-wide display? I do sometimes get issues with Marginalia. It helped me a bit increasing `marginalia-margin-threshold` to 350. But I still do get the columns misaligned.

**Comment by memeplex** [comment]
I move back and forth from my MacBook screen to an external 28" 16:9 screen on a daily basis, so adjusting `marginalia-margin-threshold` is out of question. Anyway I'm afraid that won't be enough, there is a long discussion in https://github.com/minad/marginalia/issues/95.

**Comment by minad** [comment]
@iyefrat The Marginalia alignment issue has been properly fixed. Please take a look if it works in the context of Doom.

**Comment by iyefrat** [comment]
Ah, cool. I've been waiting for changes relating to that to settle a bit before taking it out for a spin.

**Comment by minad** [comment]
> Ah, cool. I've been waiting for changes relating to that to settle a bit
> before taking it out for a spin.

Haha, that's wise. There has been quite a bit of fallout due to these
changes and me messing up some things. But it was well worth it -
Marginalia looks much better now.

**Comment by iyefrat** [comment]
This issue was solved a while back with the following vertico module bump, thanks for bringing it to our attention!
