### ISSUE TITLE
After doom upgrade org-capture templates returns "Invalid file location: nil"

### ISSUE THREAD

**Issue by dukebarman** [doomemacs/doomemacs#5583]
### What did you expect to happen?

Added new record to one of org-directory files based on chosen org-capture template

### What actually happened?

Backtrace log: https://pastebin.com/bLgEsXfb

![image](https://user-images.githubusercontent.com/1186777/136039920-9f2db68b-d4f0-4fbe-8870-c221b0cc668a.png)

### Describe your attempts to resolve the issue

Tried to use another folders but same problem on Windows too

Maybe related to https://github.com/hlissner/doom-emacs/issues/4832 

### Steps to reproduce

1. Open Emacs
2. press SPC X
3. Choose one of org-capture templates

Part of my config:
```
(after! org
    (setq org-directory "~/Documents/org/")
    (setq org-capture-templates '(("t" "Todo Today" entry
                                 (file+headline (concat org-directory "todo.org") "Today")
                                 "* TODO %?\n")
                                ("T" "Tickler" entry
                                 (file (concat org-directory "tickler.org"))
                                 "* %i%? \nSCHEDULED: %^t"))
...
```

### System Information

https://pastebin.com/4NpDhEzJ

**Comment by hlissner** [comment]
Sorry for the tremendously late response, but this error occurs because the syntax of your templates are incorrect. Those `(concat ...)` forms must be interpolated, not used verbatim:

```diff
 (after! org
     (setq org-directory "~/Documents/org/")
-    (setq org-capture-templates '(("t" "Todo Today" entry
-                                 (file+headline (concat org-directory "todo.org") "Today")
+    (setq org-capture-templates `(("t" "Todo Today" entry
+                                 (file+headline ,(concat org-directory "todo.org") "Today")
                                  "* TODO %?\n")
                                 ("T" "Tickler" entry
-                                 (file (concat org-directory "tickler.org"))
+                                 (file ,(concat org-directory "tickler.org"))
                                  "* %i%? \nSCHEDULED: %^t"))
...
```

Since this isn't a bug I will close this.
