### ISSUE TITLE
undo-tree has a new home

### ISSUE THREAD

**Issue by memeplex** [doomemacs/doomemacs#5586]
### What did you expect to happen?

The link in the undo module documentation will send me to https://gitlab.com/tsc25/undo-tree.

### What actually happened?

It sent me to emacsmirror instead.

I know the documentation is being reworked but I just wanted to report about the outdated link since as of recent the package has changed home:

* https://www.dr-qubit.org/undo-tree.html
* https://gitlab.com/tsc25/undo-tree

Given that it's a module that [was mistakenly taken for dead in the past](https://github.com/hlissner/doom-emacs/issues/2339) (as Mark Twain -misquotedly- quipped: “The reports of my death are greatly exaggerated”) it's good to know it's still alive and maybe even kicking.

### Steps to reproduce

Follow the link in https://github.com/hlissner/doom-emacs/tree/develop/modules/emacs/undo

### System Information

https://pastebin.com/doesnt_apply

**Comment by hlissner** [comment]
At some point (and it's an ongoing effort), the format of our docs have changed such that links are now automatically provided by straight.el (and in v3, will be provided by elpaca), so we no longer have static links to packages in our module docs. As such I'll consider this resolved and close it. Thanks for bringing it to my attention, in any case!
