### ISSUE TITLE
Remove "View the comparison diff in your browser?' confirmation on `doom upgrade`

### ISSUE THREAD

**Issue by logc** [doomemacs/doomemacs#5590]
### Describe your request

I'd like Doom Emacs to remove the confirmation step "View the comparison diff in your browser? (y or n)" on `doom upgrade` (and possibly other commands of the `doom` tool), because there is another confirmation right after that one "Proceed with upgrade? (y or n)" *and* there is a link to the diff just before the confirmation questions. 

If someone wishes to have a look at the diff before proceeding, they can just copy the link, or click on it from some terminals, and after that they can just confirm on a single question.

This is a very minor request, but I thought it could contribute to the user experience.

### Briefly explain its use-case

1. run `doom upgrade`
2. the upgrade prints the following
```
> Executing 'doom upgrade' with Emacs 28.0.50 at 2021-10-06 16:14:51
  > Preparing to upgrade Doom Emacs and its packages...
  - A new version of Doom Emacs is available!

    Old revision: 4903db036d (2 days ago)
    New revision: 4549b275f2 (2 hours ago)

  Link to diff: https://github.com/hlissner/doom-emacs/compare/4903db036d7342be7efbe0c6bd6978ad4873c1a3...4549b275f2b3abf7622ee7e7e739ccfeae758eaf
Proceed with upgrade? (y or n)
```
3. a user who wishes to review the diff opens the link in a browser, *and then* confirms
4. a user who does not wish to review the diff just confirms
5. a user who wants to stop without upgrading can still exit at this point.

**Comment by hlissner** [comment]
Moved to #4273.
