### ISSUE TITLE
doom-adjust-font-size does not change font size in lsp-ui-doc child frame

### ISSUE THREAD

**Issue by pradeepvrd** [doomemacs/doomemacs#5591]
### What did you expect to happen?

When adjusting font size in doom-emacs via `doom-adjust-font-size` the font changes in all regular buffers. I expected this to uniformly change font across the board.

### What actually happened?

However I noticed that the `lsp-ui-doc` popup still retains the old font size. 

![Screen Shot 2021-10-06 at 2 23 23 PM](https://user-images.githubusercontent.com/23413404/136285226-1707f1fb-c240-43f1-8977-e09e618cf302.png)

However if quit and restart my `emacsclient` instance, the font size is the correct size that was set earlier.

### Steps to reproduce

1. Set font size to 14 in config.el
2. Run Emacs as a daemon
3. Run `emacsclient -c`
4. Open a project which has lsp enabled.
5. Adjust font size using `(doom-adjust-font-size 16 t)`
6. Hover over a symbol and notice that the font size is still 14 in the doc popup.

### System Information

https://pastebin.com/wUi0Wrxv

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
