### ISSUE TITLE
cc +lsp with clangd enables ccls keybinding, which is not necessary

### ISSUE THREAD

**Issue by kaiwk** [doomemacs/doomemacs#5597]
### What did you expect to happen?

cc-mode with lsp + clangd works, and without ccls keybinding.

### What actually happened?

I have `(cc +lsp)` in my config, and set clangd with my lsp server, but doom enables ccls keybinding.

### Describe your attempts to resolve the issue

I found that doom will always requiring ccls when cc +lsp enabled:

https://github.com/hlissner/doom-emacs/blob/68c5336972cdae46cf0c69fb5d39ff5f8db87fb4/modules/lang/cc/config.el#L277

https://github.com/hlissner/doom-emacs/blob/68c5336972cdae46cf0c69fb5d39ff5f8db87fb4/modules/lang/cc/config.el#L240

https://github.com/hlissner/doom-emacs/blob/68c5336972cdae46cf0c69fb5d39ff5f8db87fb4/modules/lang/cc/config.el#L288

In my config, I have:

```emacs lisp
(add-to-list 'lsp-enabled-clients 'pyright)
(add-to-list 'lsp-enabled-clients 'clangd)
(add-to-list 'lsp-disabled-clients 'pyls))
```

to set lsp servers, maybe doom should use it too? like `(memq 'ccls 'lsp-enabled-clients)` or some other ways to tell which lsp server user currently using.

https://github.com/emacs-lsp/lsp-mode/blob/237363939b2630a807261f31614ac98fad29b785/lsp-mode.el#L272

### Steps to reproduce

1. Enable lang `(cc +lsp)`, set clangd as cc-mode lsp server;
2. Open any cpp files, you'll find ccls keybinding exist.

### System Information

https://pastebin.com/fXFaWzB8

**Comment by hlissner** [comment]
As of 374c28c those keybinds will only be bound after ccls loads. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by bixuanzju** [comment]
the keybinds are still present, I left a comment for a proper [fix](https://github.com/doomemacs/doomemacs/commit/374c28cedd5386622e61b6e8779ef0dda9fe2bb7#r150920653).
