### ISSUE TITLE
Back to back emphasis markers are not observed

### ISSUE THREAD

**Issue by jeep** [doomemacs/doomemacs#5605]
### What did you expect to happen?

When in org mode, if I type `_underline_ *bold*` the first word should be underlined, the second bold.

### What actually happened?

When I type multiple emphasis markers in a row, only every other works. When there is normal text interspersed, there is no issue.
![emphasis](https://user-images.githubusercontent.com/89500/136703792-dc88d0a0-a1fd-4e20-91c9-5235b2e0eeb5.gif)

When I do the same without the doom config (by running `emacs -q` there is no issue)
![vanilaemacs](https://user-images.githubusercontent.com/89500/136703989-fd999471-90e4-49d8-a672-769170dd2359.PNG)

### Describe your attempts to resolve the issue

I removed my personal config, so I was using out of the box doom emacs and I see the same issue.
I ran `emacs -q` and there is no issue.

### Steps to reproduce

1. Open emacs
2. Start an org doc
3. Type `_word_ _word_`
4. observe that only the first is underlined.

### System Information

https://pastebin.com/WEn5rKtC

**Comment by hlissner** [comment]
As it turns out, I lost track of when this was fixed, but it was fixed upstream and `org` was  bumped sometime in May to include the fix, so this issue has been resolved. If that isn't the case, let me know and I'll reopen it. Thanks for bringing it to my attention!
