### ISSUE TITLE
`undo-tree` visualizer is no longer displayed in a side window

### ISSUE THREAD

**Issue by Mwakamune** [doomemacs/doomemacs#5617]
### What did you expect to happen?

I updated doom emacs few days ago and i just notice that undo tree didn't have the same behavior. I press C-x u to toggle it and before the update it always appeared on the left side in a specific and thin buffer (like the treemacs one).

Here is a scree of the old behavior:

![Screenshot from 2021-10-11 22-34-33](https://user-images.githubusercontent.com/77499202/136932142-02898e3b-2b6a-41ea-b8d2-fb9f3a9a4f3c.png)

### What actually happened?

After the update undo tree toggle in a classic buffer (an existing one or splitting the current display). Everything works fine, i press q and get the original layout but I prefered the old behavior. Here is a screen of the undo tree buffer after the update:

![Screenshot from 2021-10-12 11-43-58](https://user-images.githubusercontent.com/77499202/136933356-b773f334-d301-48a0-bbe5-052dcd448ad0.png)

### Describe your attempts to resolve the issue

I tried to copy the previous config.el of undo tree into `~/.emacs/module/emacs/undo` but didn't work.

### Steps to reproduce

1- Open emacs
2- Open a file
3- Make some random edits
4- Toggle undo tree

### System Information

https://pastebin.com/N15Uk3nX

**Comment by vqhuy** [comment]
Not sure if I should open a new issue for this, please let me know.
For me when I open the visualizer for the first time it opens in a classic buffer  (same as the screenshot above), and afterwards, it works just fine (it shows in popup).
I tested it with doom sandbox (`C-c C-p`) so I guess it has nothing to do with my config (I don't even have any config for this module).
