### ISSUE TITLE
List of suggestions from which-key is partially covered by status line

### ISSUE THREAD

**Issue by tad-lispy** [doomemacs/doomemacs#5622]
### What did you expect to happen?

When pressing first key of a combo to see all possible following keys at the bottom of a frame, e.g. pressing `g` and waiting should show 

```
# -> evil-ex-search-unbounded-wo..
$ -> evil-end-of-visual-line
```

and so forth.

### What actually happened?

The last line of the list is almost completely "covered" by the status line. I only see few pixels of each character. See the screenshot.

![Screenshot from 2021-10-12 17-12-04](https://user-images.githubusercontent.com/1684495/136985399-5f77cdd0-06ae-48c7-bf08-4c566c9e28c7.png)

It only happens when there are many lines. For example when pressing `SPC f` all options are visible.

### Describe your attempts to resolve the issue

I tried `ctrl-h j` and `ctrl-h k` for paging, but it doesn't do anything.

### Steps to reproduce

1. Open Emacs
2. Visit any buffer
3. Press `g` and wait
4. See the partially covered suggestions.

### System Information

https://pastebin.com/5UFMGWWE

**Comment by notevenaperson** [comment]
Happens to me too
![HuffPolioJowl](https://user-images.githubusercontent.com/66701832/137728881-337a5aae-51d8-46d9-a835-0e1d842bdc2b.png)

**Comment by tad-lispy** [comment]
Thanks @notevenaperson! Setting `which-key-allow-imprecise-window-fit` works for me too.
