### ISSUE TITLE
Font conflict between Noto Color Emoji and Arabic in Doom Emacs

### ISSUE THREAD

**Issue by zakissimo** [doomemacs/doomemacs#5623]
### What did you expect to happen?

In Doom Emacs I have this setting that allows me to set this particular font only to arabic characters.

```
(set-fontset-font t 'arabic "Noto Naskh Arabic")
```

Here's a visual representation (notice the emojis in the Qtile bar):

![2021-10-12-230612_379x114_scrot](https://user-images.githubusercontent.com/64891486/137035189-9e71e60d-ccee-4334-a0e8-daa000863454.png)

### What actually happened?

However, when I install the Noto Color Emoji, it overrides my setting in Emacs:

![2021-10-12-230715_401x73_scrot](https://user-images.githubusercontent.com/64891486/137035256-13a851f1-7767-4fae-babd-9abfde6315e9.png)

### Describe your attempts to resolve the issue

I tried setting the Noto Naskh Arabic font directly with :

```
(setq doom-font (font-spec :family "Noto Naskh Arabic" :size 15 :weight 'semi-light))
```
And it works as intended even with the emoji font installed. (I obviously can't use emacs like this since the arabic font doesn't cover latin characters).

Removing the font reverts me to the prior state. I don't know if the issue can be fixed in the system or in Emacs' settings, which is why I'm posting here.

### Steps to reproduce

1. Install Noto Naskh Arabic font
2. Edit config.el to include
```
(set-fontset-font t 'arabic "Noto Naskh Arabic")
```
3. Copy the following sentence to your emacs and remember what it looks like (maybe take a screenshot)
```
هذه تجربة ، فو بار
```
4. Install Noto Color Emoji font
5. Refesh Emacs and check back your arabic sample text

### System Information

https://pastebin.com/qf3rYw88

**Comment by joobus** [comment]
I solved a similar problem [here](https://github.com/doomemacs/doomemacs/issues/5160#issuecomment-1318133703).  Try in your config.el:

```
(after! all-the-icons
  (set-fontset-font t 'arabic "Noto Naskh Arabic"))
```
