### ISSUE TITLE
set-company-backend! appending instead of prepending

### ISSUE THREAD

**Issue by lastgosumatt** [doomemacs/doomemacs#5672]
### What did you expect to happen?

Write in config.el:
`(set-company-backend! 'rustic-mode  '(company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine))`

Output:
describe-variable company-backends:
`((company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine)(company-campf company-yasnippet))`

### What actually happened?

Write in config.el:
`(set-company-backend! 'rustic-mode  '(company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine))`

Output:
```
describe-variable company-backends:
((:separate company-capf company-yasnippet)
 (company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine)
 company-yasnippet)
```

### Describe your attempts to resolve the issue

Delete from config.el:
`(set-company-backend! 'rustic-mode  '(company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine))`

Output:
`(company-capf company-yasnippet)`

### Steps to reproduce

Write in config.el:
(set-company-backend! 'rustic-mode '(company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine))

### System Information

https://pastebin.com/BcKPSWjn

**Comment by hlissner** [comment]
You need to defer it, to have it prepend to its default value.

```lisp
(after! rustic
  (set-company-backend! 'rustic-mode ...))
```

**Comment by lastgosumatt** [comment]
Sorry, added to config, then restart emacs

Config:
```
(after! rustic
(set-company-backend! 'rustic-mode '(company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine)))
```


Output:
```
((:separate company-capf company-yasnippet)
 (company-capf company-yasnippet company-dabbrev company-dabbrev-code company-tabnine)
 company-yasnippet)

```

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/88a396148922a2cb5d1e1a731f741e02aada691a, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
