### ISSUE TITLE
`eshell` buffer tabs are grouped with buffers from the `Emacs` group

### ISSUE THREAD

**Issue by edgar-vincent** [doomemacs/doomemacs#5675]
### What did you expect to happen?

With the `:ui tabs` module enabled, tabs corresponding to `eshell` buffers should not be grouped with buffers from the `Emacs` group, i.e. ` *Messages* `, ` *scratch* `, ` *doom* `.

### What actually happened?

`eshell` tabs, such as ` *doom:eshell* ` are displayed in the same tab group as ` *Messages* `, ` *scratch* `, ` *doom* ` (see screenshot below).
![image](https://user-images.githubusercontent.com/63352906/138454257-90a26098-4a5a-4c34-8ab6-402232b3630e.png)

### Describe your attempts to resolve the issue

The following definition of `centaur-tabs-buffer-groups` solves the issue:

```elisp
(defun centaur-tabs-buffer-groups ()
  "`centaur-tabs-buffer-groups' control buffers' group rules.

Group centaur-tabs with mode if buffer is derived from `eshell-mode'
`emacs-lisp-mode' `dired-mode' `org-mode' `magit-mode'.
All buffer name start with * will group to \"Emacs\".
Other buffer group by `centaur-tabs-get-group-name' with project name."
  (list
   (cond
    ((or (and (string-equal "*" (substring (buffer-name) 0 1))
              (not (derived-mode-p 'eshell-mode)))
	 (memq major-mode '(magit-process-mode
			    magit-status-mode
			    magit-diff-mode
			    magit-log-mode
			    magit-file-mode
			    magit-blob-mode
			    magit-blame-mode
			    )))
     "Emacs")
    ((derived-mode-p 'eshell-mode)
     "EShell")
    ((derived-mode-p 'emacs-lisp-mode)
     "Elisp")
    ((derived-mode-p 'dired-mode)
     "Dired")
    ((memq major-mode '(org-mode org-agenda-mode diary-mode))
     "OrgMode")
    (t
     (centaur-tabs-get-group-name (current-buffer))))))
```
I can submit a PR if this solution is satisfactory.
### Steps to reproduce

1. Open Emacs with the `:ui tabs` module enabled.
2. Open an `eshell` buffer with `SPC o E`.

### System Information

https://pastebin.com/Rh7bv8jy

**Comment by hlissner** [comment]
I consider this an upstream issue for centaur-tabs. In any case, I'll be replacing centaur-tabs with the built in tab-{bar,line}-mode soon, so I don't intend to support this package going forward. Thanks for bringing it to my attention, in any case!
