### ISSUE TITLE
Error installing on ubuntu 20.04.3 (org-yt -> wrong-type-argument arrayp nil)

### ISSUE THREAD

**Issue by fguarini** [doomemacs/doomemacs#5685]
### What did you expect to happen?

Install to be successful.
    On Ubuntu 20.04.3
    Using the commands for cloning and "doom install"
    

### What actually happened?

> Cloning org-yt...
    x There was an unexpected error
      Message: Wrong type argument
      Error: (wrong-type-argument arrayp nil)
      Backtrace:
        (substring nil 0 0)
        (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
        (shell-quote-argument nil)
        (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
        (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name direct...
        (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file...
        (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (exp...
        (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n...
        (let* ((result result) (exit (car result)) (invoked (numberp exit)) (succe...
        (let ((directory x6) (result x4) (args x2) (program x0)) (let* ((result re...

### Describe your attempts to resolve the issue

At first I was trying to upgrade doom but got an error with a package, so I ended up eliminating the straight repos and doing a doom upgrade but the problem persisted. At the end I deleted .emacs.d and the doom config folder to make a clean install and I'm still getting errors when attempting to install Doom Emacs.

### Steps to reproduce

1. On Ubuntu 20.04.3
2. Run the installation commands given in the instructions:
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install

### System Information

https://pastebin.com/JL6an4NR

**Comment by jazzpi** [comment]
I had the same issue, except it triggered on `org-contrib` instead. However, I don't think this is a duplicate of #5207  -- it's a different error message, and the repository is never actually downloaded, so the fix doesn't work (although the workaround in https://github.com/hlissner/doom-emacs/issues/5207#issuecomment-932053166 allows installation to continue).

But I don't think disabling SSL verification is a reasonable long-term fix.

**Comment by M1ndo** [comment]
> I had the same issue, except it triggered on `org-contrib` instead. However, I don't think this is a duplicate of #5207 -- it's a different error message, and the repository is never actually downloaded, so the fix doesn't work (although the workaround in [#5207 (comment)](https://github.com/hlissner/doom-emacs/issues/5207#issuecomment-932053166) allows installation to continue).
> 
> But I don't think disabling SSL verification is a reasonable long-term fix.

same thing happened to me , using this ```git config --global http.sslVerify false``` fixed it for me .
