### ISSUE TITLE
org-capture-mode doesn't start properly after opening agenda

### ISSUE THREAD

**Issue by dmusican** [doomemacs/doomemacs#5714]
### What did you expect to happen?

When I start org-capture after having first opening an org agenda, I expect the org-capture buffer to open with org-capture-mode enabled. This enables the c-c, c-k, etc keys for completing org-capture.

### What actually happened?

If I start org-capture after having started an agenda, then org-capture-mode doesn't start automatically. I can start org-capture-mode manually at that point, but of course one would prefer not to do so. I deleted my config.el and the problem persists; after posting to Discord, user @Mayobr(öd|ead|ot) confirmed seeing the same behavior.

### Steps to reproduce

0. Make sure that ~/org is not present in your filesystem.
1. Open Emacs
2. Start an agenda with a todo list. (SPC o a t)
3. Start an org-capture (SPC X t).
4. Answer "y" to create ~/org directory if it is not there. (org-capture-mode IS working at this point.)
5. Enter C-k, then quit emacs (SPC q q)
6. Restart emacs.
7. Start an agenda with a todo list. (SPC o a t)
8. Start an org-capture (SPC X t).
9. Observe that org-capture-mode is not on.

### System Information

https://pastebin.com/xBTDeTky

**Comment by dmusican** [comment]
I just discovered bug #4832 , which is exactly the problem I was seeing. [This workaround](https://github.com/hlissner/doom-emacs/issues/4832#issuecomment-822845907), i.e. 

```
(defalias '+org--restart-mode-h #'ignore)
```

works for me, but it's clear that the underlying bug is still present.

**Comment by steven-lang** [comment]
I can confirm the described issue. The proposed workaround does seem to fix it for now.

**Comment by dustinfarris** [comment]
The workaround fixes the capture in agenda problem; however it also seems to interfere with org-roam's buffer — it stops updating as you navigate through different nodes.

**Comment by dustinfarris** [comment]
here's a more complex workaround that mocks `+org--restart-mode-h` just for capturing and then restores it to normal via the capture finalize hook

```elisp
(map! :after org
      "C-c n" #'org-roam-capture
      "C-c c" #'df/org-capture) ; FIXME - use regular org capture after doom-emacs#5714 is resolved


; FIXME - workaround for org capture
; see https://github.com/hlissner/doom-emacs/issues/5714
; copying the implementation into a new namespace so it can be referenced without being circular
(defun df/restart-mode-h nil "Restart `org-mode', but only once."
       (if doom-debug-p
           (progn
             (org-mode-restart))
         (let
             ((inhibit-message t)
              (save-silently t))
           (prog1
               (org-mode-restart)
             (message ""))))
       (setq org-agenda-new-buffers
             (delq
              (current-buffer)
              org-agenda-new-buffers))
       (remove-hook 'doom-switch-buffer-hook #'+org--restart-mode-h 'local)
       (run-hooks 'find-file-hook))

(defvar df/restart-mode-fn 'df/restart-mode-h)

(defalias '+org--restart-mode-h (lambda () (funcall df/restart-mode-fn)))

(defun df/org-capture (&optional goto keys)
  (interactive "P")
  (message "ignoring restart-mode")
  (setq df/restart-mode-fn #'ignore)
  (org-capture goto keys))

(defun df/restore-restart-mode ()
  (message "restoring restart-mode")
 (setq df/restart-mode-fn 'df/restart-mode-h))

(add-hook! 'org-capture-before-finalize-hook #'df/restore-restart-mode)
; END HACK
```

**Comment by danilevy1212** [comment]
I've just encountered this bug, Really hard to debug, glad I found this issue. The culprit of this bug is `+org-defer-mode-in-agenda-buffers-h` that is part of the 'org-agenda-finalize-hook`. Specifically `+org--restart-mode-h`,  like all of you have pointed out.

**Comment by danilevy1212** [comment]
I've came up with this fix that I think is a bit more simple that what is proposed above:

```elisp
(after! org
  (defadvice! dan/org-capture-prevent-restart (fn &rest args)
    :around #'+org--restart-mode-h
    (unless (bound-and-true-p org-capture-mode)
      (apply fn args)))
  (add-hook! 'org-capture-after-finalize-hook
             (let ((buffer (org-capture-get :buffer)))
               (when (buffer-live-p buffer)
                 (with-current-buffer buffer
                   (+org--restart-mode-h))))))
```

Basically, we prevent restarting buffers that are `org-capture` buffers. Then, if we captured into a buffer that is live, we restart it. That way if we visit that buffer, it should have all the bells a whistles that are activated through `org-mode-hook`s

**Comment by danilevy1212** [comment]
I will have another crack at this, but I think that an even simpler solution should be to preserve `org-capture-current-plist` and `org-capure-plist` between restarts, because that really seems to be the source of the issue.

**Comment by danilevy1212** [comment]
> I will have another crack at this, but I think that an even simpler solution should be to preserve `org-capture-current-plist` and `org-capure-plist` between restarts, because that really seems to be the source of the issue.

(after! org
  (defadvice! dan/org-capture-prevent-restart (fn &rest args)
    :around #'+org--restart-mode-h
    (let ((old-org-capture-current-plist (and (bound-and-true-p org-capture-mode)
                                              (bound-and-true-p org-capture-current-plist))))
      (apply fn args)
      (when old-org-capture-current-plist
        (setq-local org-capture-current-plist old-org-capture-current-plist)
        (org-capture-mode +1)))))

**Comment by danilevy1212** [comment]
> > I will have another crack at this, but I think that an even simpler solution should be to preserve `org-capture-current-plist` and `org-capure-plist` between restarts, because that really seems to be the source of the issue.
> 
> ```emacs-lisp
> (after! org
>   (defadvice! dan/+org--restart-mode-h-careful-restart (fn &rest args)
>     :around #'+org--restart-mode-h
>     (let ((old-org-capture-current-plist (and (bound-and-true-p org-capture-mode)
>                                               (bound-and-true-p org-capture-current-plist))))
>       (apply fn args)
>       (when old-org-capture-current-plist
>         (setq-local org-capture-current-plist old-org-capture-current-plist)
>         (org-capture-mode +1)))))
> ```
> 
> This is part of my config now.

If you get logs of error messages having to do with `org-element--cache-sync`, add this to your config:

```elisp
(after! org
  (add-hook! 'org-capture-after-finalize-hook (org-element-cache-reset t)))
```

**Comment by hperrey** [comment]
> I've came up with this fix that I think is a bit more simple that what is proposed above:
> 
> ```emacs-lisp
> (after! org
>   (defadvice! dan/org-capture-prevent-restart (fn &rest args)
>     :around #'+org--restart-mode-h
>     (unless (bound-and-true-p org-capture-mode)
>       (apply fn args)))
>   (add-hook! 'org-capture-after-finalize-hook
>              (let ((buffer (org-capture-get :buffer)))
>                (when (buffer-live-p buffer)
>                  (with-current-buffer buffer
>                    (+org--restart-mode-h))))))
> ```
> 
> Basically, we prevent restarting buffers that are `org-capture` buffers. Then, if we captured into a buffer that is live, we restart it. That way if we visit that buffer, it should have all the bells a whistles that are activated through `org-mode-hook`s
> 
> With this hack, the capture buffer doesn't have the `+fancy` features, but I'm pretty sure one could activate them somehow, maybe adding them to the `org-capture-mode-hook`. I just don't care for it much myself.

Thanks for providing this workaround! This does solve my issue. However, something must be slightly different on my end, as your later suggestion does *not* help for some reason.

I have not yet had the chance to dig any deeper into this.

**Comment by real-or-random** [comment]
> Thanks for providing this workaround! This does solve my issue. However, something must be slightly different on my end, as your later suggestion does _not_ help for some reason.

Same here, the [first workaround](https://github.com/doomemacs/doomemacs/issues/5714#issuecomment-1018039845) works for me, but the [second workaround that just sets `org-capture-current-plist`](https://github.com/doomemacs/doomemacs/issues/5714#issuecomment-1018945771) doesn't do the trick.

**Comment by real-or-random** [comment]
Here's a more general version:
```emacs-lisp
(after! org
  (defadvice! >org-capture-prevent-restart (fn &rest args)
    :around #'+org--restart-mode-h
    (unless (buffer-base-buffer) ; Skip in indirect buffers with the hook cloned
       (apply fn args))))
```

---

> ```emacs-lisp
>   (add-hook! 'org-capture-after-finalize-hook
>              (let ((buffer (org-capture-get :buffer)))
>                (when (buffer-live-p buffer)
>                  (with-current-buffer buffer
>                    (+org--restart-mode-h))))))
> ```
> 
> (...) Then, if we captured into a buffer that is live, we restart it. That way if we visit that buffer, it should have all the bells a whistles that are activated through `org-mode-hook`s

Do we really need this part? What happens if you omit it? I don't encounter with bad consequences when omitting it. Also, conceptually, the original buffer should still `+org--restart-mode-h` normally when we open it in a window, no?

**Comment by real-or-random** [comment]
#7618 has a proper fix that performs the restart of org-mode at the right time, instead of just skipping it (as done by the workarounds above).
