### ISSUE TITLE
`format` module uses `dartfmt` which has been deprecated

### ISSUE THREAD

**Issue by 3nt3** [doomemacs/doomemacs#5777]
### What did you expect to happen?

When you save a file with the `format` module enabled, it shoud format it without opening a new window.

### What actually happened?

When you save a dart file with the `(format +onsave)` module enabled, a new window appears with the following text:

```
Warning: 'dartfmt' is deprecated. Please use 'dart format'.
(See https://github.com/dart-lang/dart_style/wiki/CLI-Changes.)
```

### Steps to reproduce

1. Open emacs (with `(format +onsave)` enabled in `init.el`) 
2. Open any dart file
3. Make changes
4. Save the file

### System Information

https://pastebin.com/YCbQuUSv

**Comment by sei40kr** [comment]
This is an upstream issue and already marked as fixed in upstream → https://github.com/lassik/emacs-format-all-the-code/pull/162

We need to bump `format-all` in the format module.

**Comment by hlissner** [comment]
I'm aware of this, and the format module is pending a rewrite to do away with format-all. Bumping format-all is in [our do-not-PR list](https://discourse.doomemacs.org/do-not-pr) because it has introduced breaking changes. Unpin it at your own risk.

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. Please open a new issue if this (or other) issues present themselves with the new implementation.
