### ISSUE TITLE
EditorConfig and Format integration

### ISSUE THREAD

**Issue by M-Gregoire** [doomemacs/doomemacs#5992]
### What did you expect to happen?

I have both 
```
:editor
(format +onsave)
```

And
```
:tools
editorconfig
```

I am editing some Java files `(java +meghanada)`.
My `.editorconfig` sets some specific indent size which are different from the defaults.

`M-x editorconfig-format-buffer` works as intended.

### What actually happened?

When saving the `.java` file, the entire file is reformated by `clang-format`.

I am not sure whether this is an expected behavior or not.

I could try to use `!set-formatter` with `editorconfig-format-buffer` either:
- For all major modes, but would break formatting on files extension I do not have an `.editorconfig` for
- For specific major modes I have an `.editorconfig` but would need manual modifications for every file extension.

Is there a way for `(format +onsave)` to use `.editorconfig` when it specifies config for the specific filetype, and to fallback to `format-all` otherwise?

I'm sorry if this as already been answered, I couldn't fond any issue about this.

### Steps to reproduce

1. Set Doom emacs config with `EditorConfig` and `Format +onsave`
2. Edit some files
3. `.editorconfig` is ignored by `+onsave`

### System Information

Emacs 27.1 with Doom revision 29536a22f0

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. Please open a new issue if this (or other) issues present themselves with the new implementation.
