### ISSUE TITLE
Opening an org-roam-capture-ref from firefox doesn't work with emacs daemon + emacsclient specifically

### ISSUE THREAD

**Issue by DominikMendel** [doomemacs/doomemacs#5997]
### What did you expect to happen?

When I run the org-roam-capture-ref-template from firefox it does what is originally did with normal "emacs" vs "emacsclient". It should open an org capture template.

### What actually happened?

Nothing happens. When I click on my bookmark it looks like nothing occurs. If I am not running the emacsclient or the emacs daemon it works fine. This only happens when I am on the emacs daemon + emacsclient. 

### Describe your attempts to resolve the issue

Run my ref-template with a normal emacs session and not the emacs daemon + emacsclient. 

### Steps to reproduce

Relevent code: 
My org reg: 
`  (setq org-roam-capture-ref-templates
        '(("e" "example" plain "- tags ::  %?\n* "
           :if-new (file+head "website/%(url-host (url-generic-parse-url \"${ref}\"))-${slug}.org" ":PROPERTIES:
:ROAM_REFS: ${ref}
:END:
,#+TITLE: ${title}\n")
           :unnarrowed t)))`

My Firefox bookmark: 
```javascript:location.href = 'org-protocol://roam-ref?template=e&ref=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title) + '&body=' + encodeURIComponent(window.getSelection())```

Attempt to run this bookmark from the firefox web browser. It should open up an org capture template in Emacs. However this does not work if running emacs daemon + emacsclient. 

### System Information

https://pastebin.com/cG19C2q2

**Comment by DominikMendel** [comment]
If this information helps. This is my org-protocol.desktop file found in ~/.local/share/applications:
`[Desktop Entry]
Name=Org-Protocol
Exec=emacsclient %u
Icon=emacs-icon
Type=Application
Terminal=false
MimeType=x-scheme-handler/org-protocol
`

**Comment by truemped** [comment]
Hey, I have the exact same issue. It used to work, but unfortunately I don't really recall when it stopped working. I also happened to install everything on a fresh Laptop. But even there it did not work. Basically, following the official [docs](https://www.orgroam.com/manual.html#Org_002droam-Protocol) does not work right now.

Anyway I can help? I don't really know elisp though, but am willing to learn...

**Comment by hlissner** [comment]
As of fb1c8eb11d10e15a73d3cdbfe6764d74daac0aaf this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
