### ISSUE TITLE
HTML auto-formatting can corrupt multi-byte UTF-8 characters on macOS

### ISSUE THREAD

**Issue by dlukes** [doomemacs/doomemacs#6149]
### What did you expect to happen?

When I save an HTML file which contains an emoji (or really, any non-ASCII UTF-8 codepoint) with format-on-save enabled, I expect output which looks like this:

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  🙂
</body>
</html>
```

### What actually happened?

Instead, on macOS 12.2.1, I get the following output:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
  <title></title>
</head>

<body>
  &eth;&#376;&#8482;&#8218;
</body>
</html>
```

Note:

- the doctype is obsolete
- the emoji has been garbled -- individual bytes have been converted to entities, some bytes have even been discarded as "invalid" (as per the warnings in a separate message buffer -- e.g. "replacing invalid character code 159")

### Describe your attempts to resolve the issue

This isn't technically a bug in Doom -- the problem is that macOS ships with a very old version of the `tidy` program (from 2006), which behaves differently w.r.t. UTF-8 than the newer versions Doom (or `emacs-format-all-the-code`) expects. But Doom still happily uses it as the auto-formatting provider (if not overridden by a newer version installed e.g. via Homebrew).

If the user had manually installed an old version of `tidy`, then I'd say they deserve what they get. But in this case, the old version comes preinstalled with macOS, so maybe they don't even realize where the problem is.

The particularly insidious way of hitting this issue (which is how I personally encountered it) is by getting garbled Org Mode exports. Org exports via a temporary buffer, which means onsave hooks are run. So with this old version of `tidy`, your export is corrupted at the last moment before being saved, without you being even able to see it happen. It led me on a wild goose chase through Org export functions, looking for encoding-related problems. This affects both HTML and ODT exports (because ODT uses XML, which is also formatted using `tidy`).

(I'm planning to ask on the Org Mode mailing list whether there might be a way for Org to completely circumvent auto-formatting shenanigans during export.)

Here are a few ideas on how the issue could be mitigated, arranged roughly by amount of effort required:

- Warn about the obsolete version of `tidy` shipped with macOS somewhere in the docs. At least in the module's README, but maybe even next to the `(format +onsave)` line in the default `init.el`, so that people have a chance to realize they might be affected when they're enabling it.
- Check for a minimum required version of `tidy`.
- Since this might affect other auto-formatters, have a prompt on first run to confirm the given program is what the user was intending to use as auto-formatter.

### Steps to reproduce

1. Open Emacs on macOS, where `/usr/bin/tidy` is the first `tidy` program on your `PATH` as seen by Emacs. Run `tidy --version` to confirm it's an old version from 2006.
2. Start editing an empty HTML file.
3. Insert a multi-byte UTF-8 character, e.g. an emoji like 🙂.
4. Save the file. The document will be reformatted and the content corrupted (the emoji's bytes will be converted to entities / removed if considered invalid).

### System Information

https://pastebin.com/bmHVuNYz

**Comment by hlissner** [comment]
The `:editor format` module replaced [format-all](https://github.com/lassik/emacs-format-all-the-code) with [Apheleia](https://github.com/radian-software/apheleia/) in 4ecd616cd8f60640d6b0be2ffc3d762e88099bb4, which uses prettier for html-mode/web-mode by default, which doesn't come included on MacOS or any other OS. Additionally, Apheleia includes a definition for tidy, but does not associate it with any major mode by default, effectively make it opt-in, so users won't unintentionally run into this particular issue unless they ask for it.

As such, I will consider this resolved. Thanks for bringing it to my attention, in any case!
