### ISSUE TITLE
+file-templates-inhibit-in-org-capture-a in :editor/file-templates slows down org-capture.

### ISSUE THREAD

**Issue by precompute** [doomemacs/doomemacs#6160]
### What did you expect to happen?

When calling org-capture, I experienced really long delays (~10s) until it showed the options.

I expected it to not have delays.

### What actually happened?

There is no bug here.  The CPU profiler gave me the following:

```
137  50% - command-execute
129  47%  - funcall-interactively
129  47%   - org-capture
129  47%    - apply
129  47%     - +file-templates-inhibit-in-org-capture-a
129  47%      - let
129  47%       - apply
129  47%        - #<subr org-capture>
 82  30%         - org-store-link
 82  30%          + #<lambda 0x9860b7c8557e006>
 47  17%         - org-capture-select-template
 47  17%          - org-mks
 47  17%           - apply
 47  17%            - +org--remove-customize-option-a
 47  17%             - funcall
 47  17%              + #<subr org-mks>
```

My capture templates are pretty simple:
```lisp
(setq org-capture-templates
      '(("p" "PDF" plain (file 46-da-org-dir-path-c)
         "** %(org-capture-pdf-c 1)
[[%(org-capture-pdf-c 2)]]
%U
PAGE: %(org-capture-pdf-c 4)
#+begin_quote
%(org-capture-pdf-c 3)
#+end_quote
%?" :empty-lines 1)
        ("f" "file" plain (file 46-da-org-dir-path-c)
         "** %f
[[%F]]
%U
#+begin_quote
%i
#+end_quote
%?" :empty-lines 1) ))
```

### Describe your attempts to resolve the issue

I unadvised org-capture and the issue disappeared, `org-capture` does not have delays now:

```lisp
(advice-remove '+file-templates-inhibit-in-org-capture-a #'org-capture)
```

### Steps to reproduce

1. Define org capture template
2. Call org-capture

### System Information

https://pastebin.com/9RWdR5TD

**Comment by hlissner** [comment]
I cannot reproduce this, nor does `+file-templates-inhibit-in-org-capture-a` do anything expensive. I'm inclined to suspect a local issue, but can't investigate further without a reproducible test case.

**Comment by hlissner** [comment]
Sorry for the late response. As of 802f015 I've altogether disabled file-templates in org-capture templates, which should've indirectly resolved this. Thanks for bringing it to my attention!
