### ISSUE TITLE
Company not working in `fountain-mode`

### ISSUE THREAD

**Issue by alienbogart** [doomemacs/doomemacs#6180]
### What did you expect to happen?

I'm trying to use [fountain-mode](https://github.com/rnkn/fountain-mode) with `company` and the usual completions. 

### What actually happened?

[Here's a gif of the issue taking place](https://thumbs.gfycat.com/PinkNeatCrossbill-mobile.mp4).

When I first open the file, `company` works fine, but after a while the completions cease to work. I this video was taken with all `company` settings disabled, so this is not an issue with `company` configuration. Here's the error I'm getting:

``` emacs-lisp
Starting "look" process...
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Wrong type argument: characterp, space" on command post-command
```

### Describe your attempts to resolve the issue

Remove all my fountain and company personal settings.

### Steps to reproduce

1. Open a `fountain` file with `fountain-mode` installed.
2. Navigate a few senquences.
3. Type anything that should trigger a company completion

### System Information

https://pastebin.com/HmtazizM

**Comment by tianyaochou** [comment]
Same thing happens to ProofGeneral and company-coq. After debugging, I found out that in `modules/completion/company/config.el`, there is a `after-change-major-mode-hook` that reset `company-backends` with `+company-init-backends-h`.

Comment out that line(67) works for me.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/88a396148922a2cb5d1e1a731f741e02aada691a, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
