### ISSUE TITLE
`format-all` is pinned to a commit older than 2 years

### ISSUE THREAD

**Issue by dschrempf** [doomemacs/doomemacs#6203]
### What package(s) should be bumped?

`format-all`

### Why should Doom bump these packages early?

I saw from older issues/PRs that `format-all` is on a "do not bump list". However, I did not find a reason why, and the pinned commit is missing features. For example, `cabal-fmt` is not available, although it is in the description of Doom Emacs (and also of `format-all`).

What is the reason for `format-all` being on this list? Can we still bump this package?

Thank you for your help!

**Comment by elken** [comment]
IIRC because it's slated to be replaced by https://github.com/raxod502/apheleia due to being difficult to maintain. 

Henrik has been without internet for a few days so might not respond to this for a few days, if you want to keep it open a bit longer to get a proper answer from the horse's mouth :)

**Comment by goetzc** [comment]
See also: [[Discussion] The future of :editor format #4526](https://github.com/hlissner/doom-emacs/issues/4526).

**Comment by dschrempf** [comment]
Thank you. From what I can see, the discussion about file formatting has been pretty stale. I do not yet see why Doom requires it's own file formatting solution. Why not go with the flow and use a ready-made package supporting most file formats in a canonical way? (`format-all` or `apheleia` both seem good to me). Feel free to close this issue, I don't really feel like closing it now, because I still cannot format `cabal` code out of the box.

**Comment by sei40kr** [comment]
@dschrempf 
> Why not go with the flow and use a ready-made package supporting most file formats in a canonical way?

In order to support LSP formatters & add [some improvements](https://github.com/sei40kr/doom-emacs/blob/845700e3a3d4d4bbcf42333ef4b86080ca1e6091/modules/editor/format/autoload/format.el).

> I still cannot format cabal code out of the box.

Did you mean `cabal-fmt`? I haven't tested this yet, but you can port it on your own by using `set-formatter!` macro.

```emacs-lisp
(set-formatter! 'cabal-fmt "cabal-fmt" :modes 'haskell-cabal-mode)
```

**Comment by dschrempf** [comment]
Thanks for your detailed replies! It is great that we have a workaround! Still, it should work out of the box, especially because it is also advertised in the Doom manual.

**Comment by 0liu** [comment]
Please update `format-all` to the latest. Need `yapf` support for Python code. Thank you.

**Comment by elken** [comment]
> Please update `format-all` to the latest. Need `yapf` support for Python code. Thank you.

Unpin it yourself then 😁

**Comment by dschrempf** [comment]
I can not see the post you are quoting. I think `format-all` can not be unpinned, because it has moved on quite a lot and is incompatible with Doom Emacs latest. Please correct me if this is wrong!

**Comment by elken** [comment]
> I can not see the post you are quoting. I think `format-all` can not be unpinned, because it has moved on quite a lot and is incompatible with Doom Emacs latest. Please correct me if this is wrong!

Correct, they've deleted their comment but they asked for it to be unpinned as in my quoted reply.

**Comment by Jdogzz** [comment]
@hlissner Looks like this one can be closed now that format-all is replaced?
