### ISSUE TITLE
Wrong ligature spacing when using the Iosevka font

### ISSUE THREAD

**Issue by UndeadKernel** [doomemacs/doomemacs#6217]
### What did you expect to happen?

When the `+iosevka` flag is set for the `ligature` module (and with the correct patched font is installed), the ligatures are shown with the correct spacing. More specifically, the space occupied by the ligature symbols is the same (or close to the same) as the space used by the symbols that form the ligature.

### What actually happened?

When the `+iosevka` flag is set for the `ligature` module (and with the correct patched font is installed), the ligatures are shown with the wrong spacing. When the cursor moves outside the ligature symbols and the proper ligature is shown, a space is added to the front of the ligature and the spacing gets messed up.

### Describe your attempts to resolve the issue

I'm able to fix this issue with the following patch:

```diff
--- a/modules/ui/ligatures/config.el
+++ b/modules/ui/ligatures/config.el
@@ -117,7 +117,7 @@ correct width of the symbols instead of the width measured by `char-width'."
   (let ((len (length (car ligature-alist)))
         (acc (list   (cdr ligature-alist))))
     (while (> len 1)
-      (setq acc (cons #X00a0 (cons '(Br . Bl) acc))
+      (setq acc (cons #X00a0 (cons '(Br . Br) acc))
             len (1- len)))
     (cons (car ligature-alist) acc)))
```

### Steps to reproduce

1. Set in `init.el` the `ligature` module as `(ligatures +iosevka)`.
2. Install the Iosevka patched font with `+ligatures/install-patched-font`.
3. Open the scratch buffer or a new file and change the major mode to something that supports ligatures, e.g., `rust-mode`.
4. Type in `=` followed by `>`.
5. Move the cursor away from the typed symbols into a new line.
6. Watch how the ligature shifts to the right because a space is (incorrectly) added to the front of the ligature.

### System Information

https://pastebin.com/nqy2raCE

**Comment by non** [comment]
I can confirm that I'm seeing this issue as well, and the proposed work around seems to have worked.

**Comment by jhilker1** [comment]
I can also confirm that I'm seeing this issue as well, and that the proposed work around seems to have worked.

**Comment by timinou** [comment]
Same here, with the Recursive font this time.

**Comment by real-or-random** [comment]
> I'm able to fix this issue with the following patch: [...]

This seems to be a red herring. The change is in the function `+ligatures--correct-symbol-bounds`, which is currently called nowhere (and should probably be removed). The last call has been removed in 46d7404befcdf5a69cc164fe448ac75bd9b9b598.

**Comment by real-or-random** [comment]
cc @gagbo, this is about ligatures

**Comment by gagbo** [comment]
Are you still using Emacs 27? Because everything in this issue is about now-deleted code that was only relevant if you use Emacs 27 or older (which is unsupported now)

**Comment by real-or-random** [comment]
> Are you still using Emacs 27?

Sorry if this was not clear: I can't speak for @UndeadKernel, but I am not affected by this. I simply stumbled upon the issue because I was looking into https://github.com/doomemacs/doomemacs/issues/7440. 

> Because everything in this issue is about now-deleted code that was only relevant if you use Emacs 27 or older (which is unsupported now)

I guess the issue should be closed then.
