### ISSUE TITLE
+format/buffer does not work with "prettier"

### ISSUE THREAD

**Issue by UndeadKernel** [doomemacs/doomemacs#6218]
### What did you expect to happen?

Given this configuration:
```lisp
(setq-hook! 'web-mode-hook +format-with-lsp nil)
(setq-hook! 'web-mode-hook +format-with 'prettier)
```

when manually or automatically calling `+format/buffer` on a buffer with `web-mode` as major mode, the  buffer should be formatted using the "prettier" binary.

### What actually happened?

The function `+format/buffer` exits with an error and the buffer is not formatted.

### Describe your attempts to resolve the issue

These advices in `modules/editor/format/config.el`:
```lisp
(advice-add #'format-all--probe :around #'+format-probe-a)
(advice-add #'format-all-buffer--with :override #'+format-buffer-a)
```
introduce a problem when formatting the buffer. If I remove the advices, I'm able to call `format-all-buffer` (which is called by `+format/buffer` successfully. The problem seems to be in the advice function `+format-probe-a. line 112:
```lisp
(list +format-with t))
```
This line returns a list like `('prettier t)` while `format-all-buffer` expects something similar to `('prettier "vue")`.

### Steps to reproduce

1. Add to your configuration:
```lisp
(setq-hook! 'web-mode-hook +format-with-lsp nil)
(setq-hook! 'web-mode-hook +format-with 'prettier)
```
2. Make sure "prettier" is installed in your system.
3. Open the scratch buffer
4. Switch to the web major mode with `M-x web-mode`.
5. Try to format the buffer with `M-x +format/buffer`.

### System Information

https://pastebin.com/ghj9whTG

**Comment by GRVYDEV** [comment]
+1 also running into this issue

**Comment by cpackard** [comment]
For anyone else who runs into this issue, my current workaround in `config.el`:

```emacs-lisp
(after! rjsx-mode
  ;; Disable LSP formatting to use prettier
  (setq-hook! 'rjsx-mode-hook +format-with-lsp nil)
  ;; format-on-save doesn't work by default with rjsx-mode
  (add-hook 'rjsx-mode-hook (lambda () (add-hook 'before-save-hook #'+format-buffer-h))))
  ```

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. Please open a new issue if this (or other) issues present themselves with the new implementation.
