### ISSUE TITLE
Doom info stopped working

### ISSUE THREAD

**Issue by dschrempf** [doomemacs/doomemacs#6227]
### What did you expect to happen?

`doom/info` works.

### What actually happened?

Error:
```
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) nil "Collects some debug information about your Emacs s..." (interactive "P") (save-current-buffer (set-buffer (pop-to-buffer "*doom info*")) (setq buffer-read-only t) (let* ((modified (buffer-modified-p)) (buffer-undo-list t) (inhibit-read-only t) (inhibit-modification-hooks t)) (unwind-protect (progn (erase-buffer) (save-excursion (let ... ...))) (if modified nil (restore-buffer-modified-p nil)))) (kill-new (buffer-string)) (if (y-or-n-p "Your doom-info was copied to the clipboard.\n\nOpen ...") (progn (browse-url "https://pastebin.com"))))) 1)
```

### Describe your attempts to resolve the issue

The error was introduced by this commit:
https://github.com/hlissner/doom-emacs/commit/dcae7187b4e3d67e10d7955dc6eb4577c3d6e285

### Steps to reproduce

1. Open Emacs.
2. `doom/info`.

### System Information

I cannot do that :).

**Comment by elken** [comment]
> System Information

> I cannot do that :).

10/10

**Comment by hlissner** [comment]
My bad! This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
