### ISSUE TITLE
Freeze org-capture template with properties

### ISSUE THREAD

**Issue by apraga** [doomemacs/doomemacs#6250]
### What did you expect to happen?

When capturing a new task with a properties, save it or cancel it without freezin.

### What actually happened?

Emacs freezes, I have to kill it

### Describe your attempts to resolve the issue

A capture template with properties does not have any issue in vanilla emacs. I can reproduce the issue with an empty destination file and on emacs 27.
It also happens with a minimal config

```(setq org-capture-templates '(("t" "my todo" entry (file+headline "~/org/todo.org" "Inbox") "* TODO %^{test}p")))```

It happens on FreeBSD and Windows 10.
**Commenting out the org module in `init.el` fixes the issue**

### Steps to reproduce

1. Set a custom capture :  
```          
(after! org
  (setq
        org-capture-templates
        '(("t" "Personal todo" entry
           (file+headline "~/org/todo2.org" "Inbox")
           "* TODO %?\n%^{test}p" :prepend t :kill-buffer t)))
  )
```
2. Capture a task by setting the property first
3. Save it or cancel it.

### System Information

https://pastebin.com/VPuc7nhK

**Comment by apraga** [comment]
The culprit is `org-crypt` (the org-module as a before-save hook with org-crypt). As a temporary fix, I've disabled it in `packages.el` :

```(package! org-crypt :disable t)```

**Comment by andreypudov** [comment]
@apraga thank you for this hint! It helps to resolve an issue.

**Comment by hlissner** [comment]
I've revised the bootstrap config for org-crypt, which I hope has indirectly resolved this -- I can no longer reproduce it. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
