### ISSUE TITLE
Add consult-tramp

### ISSUE THREAD

**Issue by edgar-vincent** [doomemacs/doomemacs#6258]
### Describe your request

I think [consult-tramp](https://github.com/Ladicle/consult-tramp) might be a welcome addition to Doom. It lists Tramp targets such as the hosts in the ssh configuration file and Docker containers.

### Briefly explain its use-case

1. Press `SPC f t`.
2. `consult-tramp` is run.
3. The minibuffer lists different Tramp targets, which the user can filter through and open.

**Comment by elken** [comment]
I can see the value for sure, I might have a go at adding it in the next few days but if anyone else sees this feel free to pick it up.

**Comment by hlissner** [comment]
As of 4389e2b consult-dir now has tramp sources registered, which should indirectly fulfill this request. Thanks for bringing it to my attention (and to @elken for the PR)!

**Comment by edgar-vincent** [comment]
Thanks a lot to both of you @hlissner and @elken!
