### ISSUE TITLE
`ruby` module overwrites `company-backends` set in `.doom.d/config.el`

### ISSUE THREAD

**Issue by yugarinn** [doomemacs/doomemacs#6261]
### What did you expect to happen?

When I set the following in my `~/.doom.d/config.el`:
```lisp
(after! company
  (add-to-list 'company-backends #'company-tabnine)

  (set-company-backend! '(c-mode
                          c++-mode
                          ess-mode
                          haskell-mode
                          emacs-lisp-mode
                          conf-mode
                          lisp-mode
                          sh-mode
                          php-mode
                          python-mode
                          go-mode
                          ruby-mode
                          rust-mode
                          js-mode
                          css-mode
                          web-mode
                          nix-mode
                          json-mode
                          )
    '(
      company-tabnine
      :separate
      company-capf
      ))

  (setq +lsp-company-backends '(company-tabnine :separate company-capf))
  (setq company-show-numbers t)
  (setq company-idle-delay 0)
)
```
I expect `company-backends` to be set as `(company-tabnine :separate company-capf)` when in `ruby-mode`.

### What actually happened?

Instead, when inspecting the variable I receive `(company-robe company-dabbrev-code company-capf company-yasnippet company-tabnine)`. The configuration defined in my `config.el` seems to be overwritten by the `ruby` lang module.

### Describe your attempts to resolve the issue

Commenting out this line https://github.com/hlissner/doom-emacs/blob/6bbf837c9f4bc5e50f241b3439f8b76c76f878e2/modules/lang/ruby/config.el#L49 seems to solve the issue.

### Steps to reproduce

1. Set the aforementioned configuration
2. Either open a ruby file or manually set `ruby-mode`
3. Inspect the value of `company-backends` with `SPC h v company-backends RET`

### System Information

https://pastebin.com/SAQUYrJ3

**Comment by hlissner** [comment]
A rewrite of how `:completion company` initializes `company-backends` is in the works.

In the meantime, the workaround:

```lisp
(after! ruby-mode
  (set-company-backend! 'ruby-mode '(company-tabnine :separate company-capf)))
```

**Comment by sergiouve** [comment]
Thanks for the quick response! Unfortunately, the workaround you proposed doesn't seem to do the trick. I'll investigate a bit further and post here a solution if I find one.

**Comment by gmartsenkov** [comment]
I have the same problem, luckily i don't use robe so disabling the package fixes the issue.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/88a396148922a2cb5d1e1a731f741e02aada691a, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
