### ISSUE TITLE
:tabs module (centaur tabs) is broken when upgraded to emacs-devel branch

### ISSUE THREAD

**Issue by kskarthik** [doomemacs/doomemacs#6280]
### What did you expect to happen?

Switched to emacs-devel branch build from stable.

```
$ emacs --version
GNU Emacs 29.0.50
```

### What actually happened?

I have recenly switched to emacs-devel build & after that, centuar-tabs seem to have issues working, I got this error in \*Messages\* buffer 
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp (Git "~/my/work/gkapp/")) [55 times]
```

### Describe your attempts to resolve the issue

tried reinstalling `tabs` module

### Steps to reproduce

Open two file buffers & check the \*Messages\*buffer 

### System Information

http://paste.debian.net/1237569/

**Comment by sorawee** [comment]
This happens to me too, after upgrading to Emacs 28.1.

**Comment by sorawee** [comment]
See also: https://github.com/ema2159/centaur-tabs/issues/181

I confirm that the error is fixed after adding `(centaur-tabs-group-by-projectile-project)`. Perhaps Doom Emacs should add this by default (at least for now)?

**Comment by kskarthik** [comment]
@sorawee thank you very much for this!

`(centaur-tabs-group-by-projectile-project)` worked !

**Comment by kskarthik** [comment]
> See also: [ema2159/centaur-tabs#181](https://github.com/ema2159/centaur-tabs/issues/181)
> 
> I confirm that the error is fixed after adding `(centaur-tabs-group-by-projectile-project)`. Perhaps Doom Emacs should add this by default (at least for now)?

@hlissner any comments on this?

**Comment by hlissner** [comment]
Something has changed in project.el, so perhaps bumping it recently was premature. Try pinning to an older commit, either:

```elisp
;;; in $DOOMDIR/packages.el
(package! project :pin "125a1a8d15f998cd495ef6a6b981b1a0e201bd2f") ; Feb 23
;; or
(package! project :pin "5347dfc5f32b0408bf4ff7bbace7b2356cf59a8f") ; Jan 27
```

Then run `doom sync -u` and restart Emacs.

**Comment by sorawee** [comment]
This commit introduces the issue, FWIW: https://github.com/emacs-mirror/emacs/commit/86969f9658e278ebacb3d625d0309046ff1f2b54. There is a GitHub comment that explains what's going on.

**Comment by lesharris** [comment]
```
Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil) [113 times]

```
FWIW, even with adding `(centaur-tabs-group-by-projectile-project)` I was still getting hundreds of these on every keystroke.  

This (now-closed?) upstream issue ( [em2159/centaur-tabs/issue/3](https://github.com/ema2159/centaur-tabs/issues/3)  ) described it as an interaction between centaur-tabs, doom, and all-the-icons.  

I can confirm that adding:

```emacs-lisp
(after! centaur-tabs
    (setq centaur-tabs-set-icons nil
          centaur-tabs-gray-out-icons nil)
    ...)
```
to my `config.el` seems to stop the problem after an initial spurt of them (presumably before the `after!` config executes?).  Of course now I have no icons in the tabs :smile:

**Comment by JoseConseco** [comment]
I had similar issue - wrong-type-args, when  space-p-p and loading projects.
adding 
```elisp
(after! centaur-tabs
  (centaur-tabs-group-by-projectile-project))
```
to config.el fixed the issue. 
There was no issue (tabs were displayed ok) when instead of opening project, I just used   :e  some_file.xyz    - tabs were displayed ok.

**Comment by hlissner** [comment]
As of 8b93e8b this issue should be locally (and temporarily) resolved on Doom's end, though the issue should definitely be addressed upstream eventually. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kskarthik** [comment]
@hlissner It fixes the issue, Thank you very much for this!

**Comment by AnabasisXu** [comment]
> ```
> Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil) [113 times]
> ```
> 
> FWIW, even with adding `(centaur-tabs-group-by-projectile-project)` I was still getting hundreds of these on every keystroke.
> 
> This (now-closed?) upstream issue ( [em2159/centaur-tabs/issue/3](https://github.com/ema2159/centaur-tabs/issues/3) ) described it as an interaction between centaur-tabs, doom, and all-the-icons.
> 
> I can confirm that adding:
> 
> ```emacs-lisp
> (after! centaur-tabs
>     (setq centaur-tabs-set-icons nil
>           centaur-tabs-gray-out-icons nil)
>     ...)
> ```
> 
> to my `config.el` seems to stop the problem after an initial spurt of them (presumably before the `after!` config executes?). Of course now I have no icons in the tabs 😄

The same issue happens after upgrading to Emacs 29.2.
I ended up commenting out everything that relates to all the icons in my use package centaur config.

**Comment by DZL1943** [comment]
> I had similar issue - wrong-type-args, when  space-p-p and loading projects.
> adding 
> ```elisp
> (after! centaur-tabs
>   (centaur-tabs-group-by-projectile-project))
> ```
> to config.el fixed the issue. 
> There was no issue (tabs were displayed ok) when instead of opening project, I just used   :e  some_file.xyz    - tabs were displayed ok. 
> 

it doesn't work, nothing displaying...
