### ISSUE TITLE
[ Mu4e]: Open more than one email at a time

### ISSUE THREAD

**Issue by fbob** [doomemacs/doomemacs#6303]
### Describe your request

 I'm new to mu4e workflow and was wondering if it's possible to view multiple emails at the same time, like in a new centaur-tab (as in thunderbird) or in a split window. 
But to me for now It's indeed quite cumbersome to have to manually do `clone-buffer` for each mail I want to keep seeing.

Could this be a cool feature request for our beloved  and excellent doom-emacs ?
Thanks !

### Briefly explain its use-case

1. Open one email in mu4e
2. If you want to see another one you have to clone the last buffer
3. Go back to *mu4e-headers*
4. Open another email
5. Select the cloned buffer or split current window and select the cloned buffer

Quite a lot of steps for me.
My workflow may be completely wrong, by the way so feel free to get me in the right path.

**Comment by hlissner** [comment]
Resolved in https://discourse.doomemacs.org/t/mu4e-open-more-than-one-email-at-a-time/2517.
