### ISSUE TITLE
TODO "View in browser" action already exist on mu v1.6.10

### ISSUE THREAD

**Issue by gpkfr** [doomemacs/doomemacs#6328]
### What did you expect to happen?

since "View in browser" action already defined in mu 1.6.10, it should not be duplicated in mu4e-view-actions

### What actually happened?

view in browser action appear twice.

[v]iew in browser [V]iew in browser

### Describe your attempts to resolve the issue

commented the line resolve the duplicate:

https://github.com/hlissner/doom-emacs/blob/0e48c22c3e4d22bdaa4700e9c9f3484d2ce84973/modules/email/mu4e/config.el#L184

### Steps to reproduce

use action in msg view

### System Information

https://pastebin.com/PNAJXeuD

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/424b7af45fa2c96bbee9b06f33c6cd0fc13412ac this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
