### ISSUE TITLE
SVG (nXML) incorrect behavior with closing tags expansion.

### ISSUE THREAD

**Issue by vikigenius** [doomemacs/doomemacs#6331]
### What did you expect to happen?

When editing XML/HTML files doom automatically expands closing tags. For example after `<div>` if you type in `</>` it automatically expands to `</div>`

When editing SVG as XML closing tag expansion should work correctly just like in HTML files.

### What actually happened?

When editing SVG as XML (the modeline shows nXML) using `C-c C-c` the closing tag expansion is incorrect. It expands to `</svg>>` instead of `</svg>` (Notice the extra '>')

### Describe your attempts to resolve the issue

I tried attempting the same in HTML (Web Mode) and the expansion works fine there.

### Steps to reproduce

1. Open Emacs
2. Create an SVG file. 
3. Close it and open it again.
4. `C-c C-c` to edit as XML 
5. Add a svg tag `<svg>` trigger the closing tag expansion by typing `</>`
6. It expands to `</svg>>` instead of `</svg>`

### System Information

https://pastebin.com/CdiEk9wg

**Comment by vikigenius** [comment]
Upon further debugging I see the issue.

`nxml-electric-slash` assumes that you will be expanding closing tags like this `<\` which correctly closes the tag. But since doom automatically inserts a matching `>` for every `<` we get an additional `>`.

Don't know how to actually solve this though.

**Comment by amnore** [comment]
Same issue here. Added the following piece of code in my config to make it work correctly:

```elisp
(defadvice! --nxml-electric-slash-remove-duplicate-right-angle-and-indent (func arg)
  :around 'nxml-electric-slash
  (let ((point-before (point)))
    (funcall func arg)
    (unless (equal (+ 1 point-before) (point))
      (delete-char 1)
      (funcall indent-line-function))))
```
