### ISSUE TITLE
Doom's consult-assisting +vertico/crm-* functions reduce functionality 

### ISSUE THREAD

**Issue by t-e-r-m** [doomemacs/doomemacs#6352]
### What did you expect to happen?

When selecting an option, there should also be an option to edit the current selection, before pressing enter to confirm the selection(s).  In the default non-multiple completion, this occurs as follows:

- `[tab]` select entry
- move up and edit entry
- press `RET` to accept, and exit completion.

For `consult-completing-read-multiple`, the options are as follows (assume the command has just been called):

1. When cursor is on a pre-fetched candidate (aka not the first, editable line):
  1.1. `RET` to add to "selected candidates" list
  1.2. `[tab]` to add it to the editable line, and have the option to edit it.  Press `RET` to add it to the "selected candidates" list.

I expected the same, default behavior.  `[tab]` to add to the "selected candidates" list is much more intuitive, but restricts 1.2.

### What actually happened?

1. When cursor is on a pre-fetched candidate (aka not the first, editable line):
  1.1. `[tab]` to add to "selected candidates" list
  1.2. `RET` to add to "selected candidates" list and immediately exit completion.
  
`[backtab]`, as far as I can tell, does nothing useful.  One can enter something in the editable first line and then select a candidate with `[backtab]`, but then there's no way to see the actual list of candidates.

The functions that are bound below are responsible:

https://github.com/doomemacs/doomemacs/blob/3b789752a30419535b328c605957b6b43a9d47fa/modules/completion/vertico/config.el#L149-L152

### Describe your attempts to resolve the issue

Since the only entries were the ones Doom populated it with:

`(setq consult-crm-map nil)`

### Steps to reproduce

Eval the following:
```lisp
(progn
  (end-of-buffer)
  (let ((choices (completing-read-multiple "Enter a name: " '("Tom" "Jerry" "Spike" "Tyke"))))
    (while (> (length choices) 0 )
      (insert (concat (pop choices) " ")))))
```

Then eval it again after `(setq consult-crm-map nil)` to witness the difference.

### System Information

https://pastebin.com/7PdNdjV2

**Comment by iyefrat** [comment]
Huh, good point. This never really came up in my usage of `crm`. Since the linked PR bumps the `vertico` module and remove Doom's and Consult's `crm` changes, this issue should get "solved" once that's merged.
