### ISSUE TITLE
politza/pdf-tools moved to vedang/pdf-tools

### ISSUE THREAD

**Issue by SichangHe** [doomemacs/doomemacs#6353]
### What package(s) should be bumped?

pdf-tools

### Why should Doom bump these packages early?

no activities from politza/pdf-tools since 2020,
[a recent issue](https://github.com/politza/pdf-tools/issues/697#issuecomment-1007367178) suggests that it is no longer maintained and moved to politza/pdf-tools, which is actively maintained

**Comment by hlissner** [comment]
Doom already uses vedang/pdf-tools, and has since July 6, 2021, beacuse it's [the dominant recipe on MELPA](https://github.com/melpa/melpa/blob/master/recipes/pdf-tools).
