### ISSUE TITLE
keep the window when do project search (space s p)

### ISSUE THREAD

**Issue by luxufan** [doomemacs/doomemacs#6354]
### Describe your request

While doing the project search, if I choose a result and jump to it, the search window would disappear. If the result is not what I want. I have to type the space+s+p and search pattern again.

### Briefly explain its use-case

If the window can keep and can peek look the result of the project search, then I don't need to type the search key and search content again.

**Comment by hlissner** [comment]
Assuming you use vertico:

- After searching: `SPC '` or `M-x vertico-repeat` to "repeat" the last vertico action. Or `SPC u SPC '` to select a previous vertico action to repeat.
- During searching: `C-; E` to pull the results into an occur window, which will stick around for as long as you want it to.

Anyhow, please use [our Discourse](https://discourse.doomemacs.org) or [Discord](https://doomemacs.org/discord) for user support. Our issue tracker is only for bug reports.

**Comment by luxufan** [comment]
Thanks for reminding! @hlissner

**Comment by davidhaley** [comment]
@hlissner, is it possible to do the following:

When either:

1. `+default/search-project`: `SPC / <search_term> RET`

or

2. `+default/search-buffer`: `SPC s s <search_term> RET`

A) Bring up the previous search, and place your cursor over the line that you last pressed `RET` on.
B) And, for `1`, also move the cursor to the found line (match the behaviour of `2` in this regard)

Thank you very much for your time!
