### ISSUE TITLE
Keybinding overlap

### ISSUE THREAD

**Issue by JiaweiChenC** [doomemacs/doomemacs#6355]
### What did you expect to happen?

space i r has two bonded functionality.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/88721906/166627959-e29f8817-685e-4860-a243-ab6a10e6b071.png">

### What actually happened?

When I type space i r, I can only use the register consult, while I want to see the number registers.

### Steps to reproduce

1. open emacs
2. M-x 
3. type register

### System Information

generated    May 04, 2022 01:41:23 system       MacOS 12.3.1 Darwin 21.4.0 arm64 ns emacs        29.0.50 ~/.emacs.d/ -> ~/.emacs.d/ doom         3.0.0-dev HEAD -> master 7a305825 2022-05-03 18:38:21 +0200 ~/.doom.d/ -> ~/.doom.d/ shell        /bin/zsh features     ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB traits       gui server-running envvar-file custom-file custom       package-selected-packages connection-local-criteria-alist connection-local-profile-alist warning-suppress-types vc-annotate-very-old-color vc-annotate-color-map vc-annotate-background rustic-ansi-faces pdf-view-midnight-colors org-roam-capture-templates org-agenda-todo-ignore-scheduled org-agenda-files objed-cursor-color jdee-db-spec-breakpoint-face-colors jdee-db-requested-breakpoint-face-colors jdee-db-active-breakpoint-face-colors highlight-tail-colors fci-rule-color exwm-floating-border-color custom-safe-themes conda-env-home-directory conda-anaconda-home ansi-color-names-vector ansi-color-faces-vector modules      :completion company vertico :ui deft doom doom-dashboard doom-quit hl-todo modeline neotree ophints (popup +defaults) vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold snippets :emacs dired electric undo vc :term term vterm :checkers syntax (spell +flyspell) :tools (eval +overlay) lookup lsp magit pdf :ojs (&nopath macos) :lang cc emacs-lisp latex markdown (org +pretty +roam2) (python +lsp +pyright +conda) sh :config (default +bindings +smartparens) packages     (org-super-agenda) (org-roam-ui) unpin        org-roam company-org-roam elpa         zotxt zmq websocket treemacs tablist spinner simple-httpd s request posframe pkg-info pfuture pdf-tools org-fragtog markdown-mode lv lsp-ui lsp-treemacs lsp-mode latex-math-preview imenu-list hydra ht hover goto-chg flycheck f evil-matchit evil epl deferred dash dart-mode dap-mode company cfrs cdlatex bui avy auctex ace-window

**Comment by volisoft** [comment]
Indeed, `consult-register` and `evil-show-registers` keybindings overlap. Moreover `consult-register` shows only registers "0" and "garbage".

**Comment by hlissner** [comment]
The vertico module intentionally remaps `evil-show-registers` to `consult-register`, however, the latter did not track Evil's registers, which I've fixed in https://github.com/doomemacs/doomemacs/commit/faeab956e5bfc1dfba87f8e788eb5175b083ea47. I've done this so that `evil-show-registers` can benefit from `consult-register`'s superior interface.

Let me know if this gives you any trouble and I'll reopen the issue. Thanks for bringing it to my attention!
