### ISSUE TITLE
Update consult-notmuch (preview is broken currently)

### ISSUE THREAD

**Issue by brabalan** [doomemacs/doomemacs#6360]
### What package(s) should be bumped?

consult-notmuch

### Why should Doom bump these packages early?

Preview has changed in consult. The current version of consult-notmuch can no longer preview messages.

Testing with https://codeberg.org/jao/consult-notmuch/commit/16eb2c100ca144140f07014c32e99487c6a73e18 restores the previewing of messages.

**Comment by hlissner** [comment]
consult-notmuch was bumped in 61a7c54, which fulfills this request, so I will close it. Thanks for bringing it to my attention!
