### ISSUE TITLE
Broken links in your README.md file

### ISSUE THREAD

**Issue by GregDavidson** [doomemacs/doomemacs#6366]
### What did you expect to happen?

Clicking on
` [faq]: https://discourse.doomemacs.org/t/doom-emacs-faq/45`
 should work

Clicking on 
`[Development Roadmap](https://github.com/orgs/doomemacs/projects/6)`

### What actually happened?

Clicking on
` [faq]: https://discourse.doomemacs.org/t/doom-emacs-faq/45`
takes me to
> Doom Emacs Discourse
> Oops! This topic has been deleted and is no longer available.

Clicking on 
`[Development Roadmap](https://github.com/orgs/doomemacs/projects/6)`
takes me to
> 404 This is not the web page you are looking for.

### Describe your attempts to resolve the issue

1. Checking on  the md code -- seems fine
2. Filing this report
3. Whinging about all the silly steps github now requires for such a simple report! ;-)

### Steps to reproduce

1. Click on faq link
2. Click on Development Roadmap link

### System Information

Not relevant!!!

**Comment by hlissner** [comment]
I'm aware. The project is in the middle of migrating to our Github org (@doomemacs) and a rewrite (and restructuring) of all its docs (in-repo and on Discourse), so links are the first line of casualties. They will be fixed over the new few days. Thanks for letting me know!
