### ISSUE TITLE
Hack for Twitter Image display in twittering-mode

### ISSUE THREAD

**Issue by lesharris** [doomemacs/doomemacs#6383]
### Describe your request

twittering-mode's maintainer is on a bit of a hiatus it seems but it would be nice to support some more format codes for tweet display.  A solution to add a new format code, `I`, to display images in a tweet was described in [twittering-mode/issues/136]( https://github.com/hayamiz/twittering-mode/issues/136#issuecomment-375902630) by @fuxialexander.

The original suggestion overrode the entire format table generating function `twittering-generate-format-table` but I've implement his core code using `:around` to be less noisy/intrusive:

```emacs-lisp
;;;  Twittering
(after! twittering-mode
  ;; https://github.com/hayamiz/twittering-mode/issues/136#issuecomment-375902630
  (defun +lh/twittering-add-image-format (format-table-func status-sym prefix-sym)
    "Adds the I format code to display images in the twittering-mode format table."
    (let ((format-table (funcall format-table-func status-sym prefix-sym)))
      (push `("I" .
              (let* ((entities (cdr (assq 'entity ,status-sym)))
                     text)
                (mapc (lambda (url-info)
                        (setq text (or (cdr (assq 'media-url url-info)) "")))
                      (cdr (assq 'media entities)))
                (if (string-equal "" text)
                    text
                  (let ((twittering-convert-fix-size 360))
                    (twittering-make-icon-string nil nil text))))) format-table)))
  (advice-add #'twittering-generate-format-table :around #'+lh/twittering-add-image-format)
  (setq twittering-icon-mode t
        twittering-use-icon-storage t
        twittering-icon-storage-limit 10000
        twittering-convert-fix-size 40
        twittering-status-format "
  %i  %FACE[font-lock-function-name-face]{  @%s}  %FACE[italic]{%@}  %FACE[error]{%FIELD-IF-NONZERO[❤ %d]{favorite_count}}  %FACE[warning]{%FIELD-IF-NONZERO[↺ %d]{retweet_count}}

%FOLD[   ]{%FILL{%t}
%QT{
%FOLD[   ]{%FACE[font-lock-function-name-face]{@%s}\t%FACE[shadow]{%@}
%FOLD[ ]{%FILL{%t}}
}}}

    %I

%FACE[twitter-divider]{                                                                                                                                                                                  }
"))

```

The important parts are the advice adding and the setting of `twittering-status-format` to include the new format spec.

When in place the above hack allows for images to be displayed in twittering-mode:

<img width="640" alt="twittering" src="https://user-images.githubusercontent.com/1480883/167322267-88fd49b3-c343-4242-91da-393995ecb586.png">

### Briefly explain its use-case

I imagine something like the config above could be added into the config.el for the twitter module - perhaps behind a +flag or doom* variable setting?

**Comment by hlissner** [comment]
Since twittering-mode is now defunct (and the Twitter API in general is in ruins), I've deprecated the Twitter module. I'm closing this issue because no additioned work will be done on it for this point on. Thanks for bringing it to my attention, in any case!
