### ISSUE TITLE
coffee-mode and .coffee in Rails applications

### ISSUE THREAD

**Issue by FiloSpaTeam** [doomemacs/doomemacs#6385]
### What did you expect to happen?

Coffeescript syntax hightlight and functions related works

### What actually happened?

Simply the major mode is set to Fundamental, when i save the .coffee file an error pop up:
![Screenshot from 2022-05-10 17-54-24](https://user-images.githubusercontent.com/2974561/167674255-cb9147d8-ed4b-4215-9117-4606c9d1e948.png)

The file itself is saved on disk.

### Describe your attempts to resolve the issue

- reinstall coffee-mode package manually
- load manually major mode with autoload list

### Steps to reproduce

1. Open Emacs
2. Open a coffeescript file
3. No highlights or something else
4. Edit it
5. Save it
6. Error on save, but on disk is correct

### System Information

https://pastebin.com/9bLQcpXh

**Comment by hlissner** [comment]
This is neither a bug nor an issue that I intend to address in Doom (at this time):

- None of Doom's modules install `coffee-mode`, so it must be manually set up.
- I don't consider `coffee-mode` essential enough to Ruby development as a whole to include it in the `:lang ruby` module by default.
- `coffee-mode` only needs one line of elisp to set up, which is too trivial to warrant its own module.

How to set it up yourself:

1. ```elisp
   ;;; add to $DOOMDIR/packages.el
   (package! coffee-mode)
   ```

2. Run `doom sync`.

3. Restart Emacs.

**Comment by hlissner** [comment]
>      elpa         cmake-mode nord-theme coffee-mode

I just noticed you've installed `coffee-mode` with ELPA. Perhaps you aren't aware that Doom has its own package manager? The snippet I suggested above will solve your issue.

If you insist on using package.el, you need to properly initialize it at startup (by calling `(package-initialize)`).

**Comment by FiloSpaTeam** [comment]
Sorry but i want to understand this:
https://github.com/doomemacs/doomemacs/blob/3b789752a30419535b328c605957b6b43a9d47fa/modules/lang/javascript/README.org

Following this, i should include the javascript module to have coffee-mode. 

I never installed coffee-mode with ELPA, always used modules with appropriated flags/ tag following the documentation and using the `.config`.
Instead reading the javascript module source seems there is no real configuration for coffee-mode or i don't understand how should it works (but in the readme doom-emacs tells should works by default).

Thanks for your attention

**Comment by kgreunke** [comment]
@hlissner @FiloSpaTeam is correct.  Doom documentation says that coffee-mode is included in the javascript lang module, but it isn't.  I just went looking for this myself.
