### ISSUE TITLE
Installation in Non-Standard directory: It Just Doesn't Work™

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#6389]
### What did you expect to happen?

Hi,

I'm trying to transition from vanilla Emacs to Doom.

Following an advice on StackOverflow, I
- (i) backuped my vanilla config
- (ii) installed Doom in a non standard directory (so as not to mess with my current vanilla Emacs config).

What I expected: see a DoomEmacs windows/frame appear

### What actually happened?

Result is I get a fresh vanilla Emacs window/frame (without any config)

### Describe your attempts to resolve the issue

- Tried to set EMACS and EMACSDIR env var (found some refs in `doom` script) but nothing changed
- Tried doom doctor . Told me about lacking fg & rg binaries (seems they are mandatory, but installation did not report any error?!?)... Installed them, no more luck

### Steps to reproduce

```
mv .emacs{,.mine}
mv .emacs.d{,.mine}
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.doom.d
~/.emacs.doom.d/bin/doom install
~/.emacs.doom.d/bin/doom run
```

### System Information

https://pastebin.com/fCBfN1Rw

**Comment by hlissner** [comment]
Does [this](https://github.com/doomemacs/doomemacs/blob/develop/docs/faq.org#i-get-the-vanilla-emacs-splash-screen-at-startup) apply to you?

**Comment by hlissner** [comment]
Ah, nevermind. This appears to be an issue with `doom run`. I'm not sure if I'll address this before #4273. I'll see if I can throw together a workaround for the time being.

**Comment by liar666** [comment]
> Does [this](https://github.com/doomemacs/doomemacs/blob/develop/docs/faq.org#i-get-the-vanilla-emacs-splash-screen-at-startup) apply to you? (Or does a `~/.emacs.d` exist?)

No, I've moved all my vanilla Emacs file out of the way for the moment.

**Comment by liar666** [comment]
> Ah, nevermind. This appears to be an issue with `doom run`. I'm not sure if I'll address this before #4273. I'll see if I can throw together a workaround for the time being.

OK I understand. Thanks for the quick reply anyway :)

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
