### ISSUE TITLE
Kotlin lsp install infinite loop

### ISSUE THREAD

**Issue by aadi58002** [doomemacs/doomemacs#6394]
### What did you expect to happen?

After enabling the kotline +lsp flag . Then opening a .kt file triggers the prompt to install the kotlin-ls which after startging the download complete and then  decompresses it and then it again prompts me to install the lsp again. The relevent infomation is below

### What actually happened?

The following message keeps repeating

```
Wrote /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip
LSP :: Finished downloading /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip...
LSP :: Decompressing /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip...
(Shell command succeeded with no output)
LSP :: Decompressed /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server...
LSP :: Server kotlin-ls downloaded, auto-starting in 1 buffers.
LSP :: Download kotlin-ls started.
LSP :: Starting to download https://github.com/fwcd/kotlin-language-server/releases/latest/download/server.zip to /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip...
Contacting host: github.com:443
Wrote /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip
LSP :: Finished downloading /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip...
LSP :: Decompressing /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server.zip...
(Shell command succeeded with no output)
LSP :: Decompressed /home/aditya-yadav/.emacs.d/.local/etc/lsp/kotlin/kotlin-language-server...
LSP :: Server kotlin-ls downloaded, auto-starting in 1 buffers.
```

### Describe your attempts to resolve the issue

I installed emacs 28 with native comp disabled but the issue still persisted. I have not tried it on emacs27.

### Steps to reproduce

1. Enable the (kotlin +lsp) flag in emacs28 (either with nativecomp enables or disabled)
2. Open a .kt file with emacs
3. Click enter on the kotlin-ls prompt emacs gives
4. Wait till the decompression of the lsp start 
5. Then you will be prompted again to install the same lsp
6. This loop will continue indefinetely

### System Information

https://pastebin.com/h5CD9pAB

### Doom doctor and Lsp Log buffer output
![doom-doctor](https://user-images.githubusercontent.com/96418027/168229129-349689cb-9119-4255-93ef-6b6a9323259c.png)
![lsp-log-buffer](https://user-images.githubusercontent.com/96418027/168229143-f7f6ae24-68eb-4df4-96f4-547867a40ad0.png)

**Comment by elken** [comment]
This should be fixed in https://github.com/emacs-lsp/lsp-mode/pull/3462, it looks like `lsp-mode` needs a bump.

For now, if you manually pin to that commit it should work.

**Comment by hlissner** [comment]
Please don't close issues that require an effort on Doom's end to resolve (in this case a bump). I'll leave this open until 4ae9041 (or similar) is merged.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
