### ISSUE TITLE
Can't paste Chinese characters into emacs on windows 10

### ISSUE THREAD

**Issue by Hxppdv** [doomemacs/doomemacs#6398]
### What did you expect to happen?

Chinese characters can be displayed correctly after being pasted into emacs

### What actually happened?

![image](https://user-images.githubusercontent.com/17672838/168418699-7ce972a7-150a-405c-aa98-5370505b64b6.png)
Chinese characters should be displayed as in the first line and not as in the second line 

### Describe your attempts to resolve the issue

after this commit https://github.com/doomemacs/doomemacs/commit/68d8364aeaf96d20493314ad5f77b49b8b81aa3a
```
(unless IS-WINDOWS
  (setq selection-coding-system 'utf-8)) 
```
was changed to
```
(when (boundp 'w32-get-true-file-attributes)
--------------------
  (setq selection-coding-system 'utf-8))
```
This may cause the selection-coding-system on windows to be set to utf-8 by mistake.
This issue #5961 also mentions this problem, but the final result of the discussion is that this is a problem only on windows 11, however, I also reproduced this problem on windows 10, so I think there may be other reasons. 

### Steps to reproduce

1. open emacs
2. copy some Chinese characters such as 中文
3. paste(M-x yank) these chinese characters into emacs

### System Information

https://pastebin.com/660rGGa8

**Comment by himila** [comment]
;;解决粘贴中文出现乱码的问题
(if (eq system-type 'windows-nt)
	(progn
	  ;; (setq selection-coding-system 'utf-16le-dos) ;;修复从网页剪切文本过来时显示 \nnn \nnn 的问题
	  ;; (set-default selection-coding-system 'utf-16le-dos)
	  (set-selection-coding-system 'utf-16le-dos) ;;别名set-clipboard-coding-system
	  )
  (set-selection-coding-system 'utf-8))

**Comment by Hxppdv** [comment]
> ;;解决粘贴中文出现乱码的问题 (if (eq system-type 'windows-nt) (progn ;; (setq selection-coding-system 'utf-16le-dos) ;;修复从网页剪切文本过来时显示 \nnn \nnn 的问题 ;; (set-default selection-coding-system 'utf-16le-dos) (set-selection-coding-system 'utf-16le-dos) ;;别名set-clipboard-coding-system ) (set-selection-coding-system 'utf-8))

I know this will solve the problem, and I also think this is the cause of the problem. 
This method was actually mentioned in issue #1284 and implemented in https://github.com/doomemacs/doomemacs/commit/37525bb1bdfac1c63b8e661d8e6589a27cc74086, but as I mentioned above, the behavior was modified in https://github.com/doomemacs/doomemacs/commit/68d8364aeaf96d20493314ad5f77b49b8b81aa3a.
I want to know if this modification is intentional

**Comment by himila** [comment]
有时间纠结这个问题，不如多写几个代码，不被人卡脖子。在你纠结这个问题的同时，美国人已经离火星更近一步 了。
我的理解这是个windows encoding system问题，不是international 问题。

**Comment by Hxppdv** [comment]
It has been fixed.
