### ISSUE TITLE
Rust analyser wrong error

### ISSUE THREAD

**Issue by aadi58002** [doomemacs/doomemacs#6403]
### What did you expect to happen?

There are no errors in the code and the lsp should also show no errors. As the code compiles and runs as intended.

 The code file : https://pastebin.com/vaBN5scv

### What actually happened?

The rust code compile and runs as inteded but the lsp still shows the following error.

 expected &mut (dyn Iterator<Item = u8>), found &mut dyn Iterator

(The error is wrong as it says that it is missing and found &mut at the same moment) 

Content of lsp-log buffer is given below
```
Command "rls" is present on the path.
Command "/usr/bin/rust-analyzer" is present on the path.
Command "rls" is present on the path.
Command "/usr/bin/rust-analyzer" is present on the path.
Found the following clients for /home/aditya-yadav/Personal/trash/rust/calc/src/main.rs: (server-id rls, priority -1), (server-id rust-analyzer, priority 1)
The following clients were selected based on priority: (server-id rust-analyzer, priority 1)
```

![lsp-errors](https://user-images.githubusercontent.com/96418027/168537343-371469e8-d5db-4def-af6c-02f94412f9cc.png)
![message-buffer](https://user-images.githubusercontent.com/96418027/168537352-4ffcdc24-ec5e-4437-9162-9545d5049128.png)

### Describe your attempts to resolve the issue

I tried to disable my personal config by moving my doom config and creating a new one and then enabling the rust +lsp flag.

### Steps to reproduce

1. Open emacs
2. Create a rust project
3. Try using the read!() function from the text_io crate.

### System Information

https://pastebin.com/zy7gcHPB

**Comment by brotzeit** [comment]
Looks like a rust-analyzer issue ?

**Comment by aadi58002** [comment]
> > Looks like a rust-analyzer issue ?
> 
> No , I opened the same code in vscode and it did not show any errors. I also tried reinstalling rust analyser a few times.

After a few days a update to rust analyser came but still the issue persists.

**Comment by brotzeit** [comment]
It seems you have to update your lsp-mode version https://github.com/emacs-lsp/lsp-mode/commit/d1178661020d0c1710963dcefe02fa5bf2f91bad

**Comment by brotzeit** [comment]
#6395

**Comment by aadi58002** [comment]
> It seems you have to update your lsp-mode version [emacs-lsp/lsp-mode@d117866](https://github.com/emacs-lsp/lsp-mode/commit/d1178661020d0c1710963dcefe02fa5bf2f91bad)

Even after the lsp bump it seem it does not work.
![After-lsp-bump](https://user-images.githubusercontent.com/96418027/169004108-6c7b3845-31f2-436e-ab81-70405083d8cb.png)

Same code in vs code
![vscode](https://user-images.githubusercontent.com/96418027/169005066-30dd38a6-51ee-48e1-97bb-476550834631.jpg)

--  Doom info lsp package bump
      packages     (emojify) (org-bullets) (org-roam-ui) (beacon) (lsp-mode :pin 465bcc5fbeb6293446a3241f5f2c1b872337958c)

**Comment by aadi58002** [comment]
Thanks for the help it seems the lsp bump fixed the issue.

**Comment by brotzeit** [comment]
Probably better to leave the issue open until lsp-mode was bumped.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
