### ISSUE TITLE
Opening c file lspmode fails to start

### ISSUE THREAD

**Issue by maacl** [doomemacs/doomemacs#6408]
### What did you expect to happen?

With (cc +lsp) enabled in init.el. I open a c file and expect lsp-mode to be enabled.

### What actually happened?

 lsp-mode fails to start. I get the following error:

`Error running timer: (void-function lsp--matching-clients\?)`

### Describe your attempts to resolve the issue

I have no idea how to resolve this. I looked at other issues and similar errors have been reported which was a result of (unpin lsp-mode), but I have not done that.

### Steps to reproduce

1. Open c file in doom emacs.

### System Information

https://pastebin.com/0sxrN4J2

**Comment by innerout** [comment]
Hi, did you run doom sync when you enabled lsp-mode? Did you install the c language server (clangd by default)?

**Comment by maacl** [comment]
Yes, and yes.

**Comment by innerout** [comment]
Is there a chance that you are in an old version of doom emacs? Can you try `doom upgrade`?

**Comment by maacl** [comment]
Silly me. I was sure I had upgraded, but apprantly that was my WSL emacs not the native. I have now upgraded and detele the lsp session file, and now all works. Sorry for the inconvenience.
