### ISSUE TITLE
Upgrade dap-mode version to support new dap-dlv-go 

### ISSUE THREAD

**Issue by fakegermano** [doomemacs/doomemacs#6419]
### Describe your request

dap-mode has been updated with a new dap-dlv-go that supports native dlv integration (without the need for the vscode extension).

https://github.com/emacs-lsp/dap-mode

### Briefly explain its use-case

As dap-mode now integrates directly with dlv, there are some use-cases we can better support:

- debugging specific test cases
- better/faster debugging without too much serialization/deserialization

**Comment by hlissner** [comment]
:tools debugger was bumped in https://github.com/doomemacs/doomemacs/commit/1b8f46c7c5893d63e4bcebc203c0d28df9f5981b, which should fulfill this bump request. Thanks for bringing it to my attention!
