### ISSUE TITLE
Have the language server classified as to which language they provide

### ISSUE THREAD

**Issue by aadi58002** [doomemacs/doomemacs#6435]
### What did you expect to happen?
Emacs prompting me to install a vue language server, When opening a *.vue file it opens it with a eslint server which does not have completions for javascript.

### What actually happened?
No promt is there so that i can install a vue language server when opening a *.vue file.

### Suggestion
Please classify the lanauge server list so that it is possible to see which language server provide which language support.

### Steps to reproduce
1. Have the eslint , ts-ls and html-ls lsp servers installed
2. When opening a *.vue file it will by default open in eslint server

**Comment by hlissner** [comment]
1. A rudimentary support list is available [in the `:tools lsp` module docs](https://github.com/doomemacs/doomemacs/blob/master/modules/tools/lsp/README.org#description).
2. A more up-to-date one is available [in lsp-mode's docs](https://emacs-lsp.github.io/lsp-mode/page/languages/).

It's not up to Doom to decide what servers lsp-mode can install for you or not. That is a request better made to [the lsp-mode project](https://github.com/emacs-lsp/lsp-mode).

As this is not a Doom issue I will close it.
