### ISSUE TITLE
:ui indent-guides prevent EIN from displaying inlined images when opened

### ISSUE THREAD

**Issue by daanturo** [doomemacs/doomemacs#6438]
### What did you expect to happen?

With EIN and indent-guides modules enabled, `(setq ein:output-area-inlined-images t)`.

Opened notebooks should be able to display images when first opened.

### What actually happened?

Images saved in the notebook isn't displayed.

A dot "." in shown instead.

### Describe your attempts to resolve the issue

Disable `:ui indent-guides`
or
```lisp
(remove-hook 'prog-mode-hook 'highlight-indent-guides-mode)
```

### Steps to reproduce

1. `M-x ein:run`
2. Open a notebook that holds a plot

### System Information

https://pastebin.com/NBqzyhhp

**Comment by daanturo** [comment]
Proposed workaround in `modules/ui/indent-guides/config.el`:


```elisp

(defvar +indent-guides-disabled-modes '(ein:notebook-mode)
  "List of major and minor modes that
`doom/highlight-indent-guide-mode-maybe' should skip.")

(defun doom/highlight-indent-guide-mode-maybe ()
  "Activate `highlight-indent-guides-mode' unless one of
`+indent-guides-disabled-modes' is active."
  (unless (cl-some (lambda (mode)
                     (or (derived-mode-p mode)
                         (and (boundp mode) mode)))
                   +indent-guides-disabled-modes)
    (highlight-indent-guides-mode)))

(use-package! highlight-indent-guides
  :hook ((prog-mode text-mode conf-mode) . doom/highlight-indent-guide-mode-maybe)
  ;;; the rest
)
```

**Comment by hlissner** [comment]
As of 5f798cf, this is now resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
