### ISSUE TITLE
Obtrusive Lsp window that cant be disabled

### ISSUE THREAD

**Issue by italoaa** [doomemacs/doomemacs#6440]
### What did you expect to happen?

This window cant be clicked on as a click and it disapears. This window takes half of my screen but I can rezise it because it disapears. This window apears when editing rust code and I open a bracket.
![image](https://user-images.githubusercontent.com/72895337/172494614-fc05ed1a-16a3-47dd-aafb-31be74bda3bf.png)
I would expect at least a tittle so that I can find the package.

### What actually happened?

I expected the window to be rezisable, but it never happend and I could never figure a way to change or disable this window.

### Describe your attempts to resolve the issue

I made a question in the discord but nothing worked. I disabled modes one by one: (lsp, lsp-ui, dap, etc) I got to almost no active modes and the window still apeared when opening a bracket. I made a issue in rustic as i infered it would be rustic tough this window does not apear in their documentation. As well as lsp documentation and the documentation of lsp-ui. It apears as no one knows about this window. 

### Steps to reproduce

open a rust project with lsp and rustic and open a bracket for a function like `println!();`

### System Information

https://pastebin.com/13AnMQPQ

**Comment by RBckmnn** [comment]
I had a similar issue a while ago. The following solved the issue in my case:

```
  (after! lsp-mode
    (setq lsp-signature-render-documentation nil))
```

**Comment by RBckmnn** [comment]
Cannot remember precisely. I probably found out about it here:

https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
