### ISSUE TITLE
Every (interactive) action throws an error w/r/t `after-init-hook`: `void-variable f` 

### ISSUE THREAD

**Issue by tomterl** [doomemacs/doomemacs#6441]
### What did you expect to happen?

I updated with `doom update`, `doom sync` - I expected emacs to work as before after that.

### What actually happened?

On start this error is thrown
```
Error (after-init-hook): Error running hook "doom-modeline-mode" because: (void-variable f)
```
After that this happens again and module loading failes with errors like
```
Error (php-mode-local-vars-hook): Error running hook "lsp!" because: (void-variable f) Disable showing Disable logging
Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error php-mode-local-vars-hook lsp! (void-variable f)) Disable showing Disable logging
```

### Describe your attempts to resolve the issue

I removed the `~/.emacs.d/.local/straight` directory and issued `doom sync`and after that failed `doom sync -p` to rebuild the packages. 

### Steps to reproduce

1. Open Emacs - the error is thrown

I pasted the backtrace of the initial error here: https://pastebin.com/1eNaRqLm

### System Information

https://pastebin.com/fU7ye2Mg

**Comment by elken** [comment]
This looks like it's an upstream issue

**Comment by Phundrak** [comment]
Hello, maintainer of `f.el` here, this is indeed an upstream issue. It is tracked in https://github.com/rejeep/f.el/issues/111, for now I removed the shortdoc implementation from master.

**Comment by tomterl** [comment]
Cool - this is quick beyond any expectation thanks :)

can you guide me in how to handle this in the doom setup?  'downpin' f.el to a commit in my package.el or something?

**Comment by Phundrak** [comment]
> Cool - this is quick beyond any expectation; thanks :)
You can simply pull again f.el from master, this should fix itself (or apparently `doom sync -u` as @zeorin just mentioned)
