### ISSUE TITLE
TAB in the middle of text does not indent

### ISSUE THREAD

**Issue by etnt** [doomemacs/doomemacs#6442]
### What did you expect to happen?

When I press TAB in the middle of a line with some code (e.g Erlang or Rust),
I expect the line to be indented according to the mode...

### What actually happened?

...but instead I get a TAB inserted...
However, if I'm standing in front of the text, the line is indented.

### Describe your attempts to resolve the issue

(I've been googling for answers, browsed through old issues, tried to join the Discord (is it dead?)...)

### Steps to reproduce

1. Open Emacs on a Rust or Erlang file (running their respective LSP server)
2. Position the cursor somewhere in the middle of a code line.
3. Press TAB
4. The code is not indented, instead a TAB (?) is inserted...

### System Information

https://pastebin.com/FQ5keViF

**Comment by PhilippeNoel1** [comment]
It depends on the variable `tab-always-indent`. If set to `t`, it allows you to indent the line no matter where you are on the line.

Put this in your `config.el`
```lisp
(setq tab-always-indent t)
```

**Comment by etnt** [comment]
Thanks!
