### ISSUE TITLE
Popup rule for `embark-export` is outdated

### ISSUE THREAD

**Issue by dschrempf** [doomemacs/doomemacs#6465]
### What did you expect to happen?

I think, but please correct me if I am wrong, Embark Export buffers have changed their name from `Embark Export Grep` to `Embark Export: <some-generated-string>`. This means, the popup rule for `Embark Export Grep` is off, and does not trigger.

### What actually happened?

Popup rule does not trigger.

### Describe your attempts to resolve the issue

I identified the cause of the issue.

### Steps to reproduce

Open any Embark Export buffer using grep to display the results. For example, use

`SPC s p`
`phrase`
`C-c C-;`

### System Information

https://pastebin.com/uCaxRCin

**Comment by hlissner** [comment]
As of 4071d27 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
