### ISSUE TITLE
org mode export error

### ISSUE THREAD

**Issue by vanniuner** [doomemacs/doomemacs#6469]
### What did you expect to happen?

When I use SPC e-c in an org mode file, I expect to export it to html or markdown file. The expect is export html or markdown successfully.
 

### What actually happened?

When I use SPC e-c in an org mode file,  there have an error occured ,it said that in the *Message* buffer:
apply: Wrong number of arguments: ((t) nil "Lazy load a babel package when a block is executed during exporting." (+org--babel-lazy-load-library-a (org-babel-get-src-block-info))), 1
 

### Describe your attempts to resolve the issue

I tried to disable all setting about the org babel,but the error come either.
;; set org mode
;; (org-babel-do-load-languages
;;   'org-babel-load-languages
;;   '((emacs-lisp . nil )
;;     (org        . t   )
;;     (plantuml   . t   )))

### Steps to reproduce

My configuartion is https://github.com/vanniuner/neo-emacs
You can reproduce it .

### System Information

https://pastebin.com/QqVGpeQZ

**Comment by tecosaur** [comment]
There was a commit pushed several hours ago that should fix this (e855c2d1324a0dedc4d83c628634c7717c3c0ede), two commits after your current version of Doom.

**Comment by vanniuner** [comment]
> There was a commit pushed several hours ago that should fix this ([e855c2d](https://github.com/doomemacs/doomemacs/commit/e855c2d1324a0dedc4d83c628634c7717c3c0ede)), two commits after your current version of Doom.

thanks~
