### ISSUE TITLE
error in process sentinel: Symbol’s function definition is void: doom-initialize when running `doom/reload` in emacs

### ISSUE THREAD

**Issue by milanglacier** [doomemacs/doomemacs#6470]
### What did you expect to happen?

run `doom/reload` successfully

### What actually happened?

get the following error:
`error in process sentinel: Symbol’s function definition is void: doom-initialize`

### Describe your attempts to resolve the issue

type `C-h f` and type `doom initialize`, don't see such function: `doom-initialize`

### Steps to reproduce

1. open emacs
2. type `M-x doom/reload`
3. get the error

### System Information

https://pastebin.com/0RyuujEP

**Comment by hlissner** [comment]
As of 837f404 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
