### ISSUE TITLE
`doom sync` does not add site lisp directory to `load-path`

### ISSUE THREAD

**Issue by yamanq** [doomemacs/doomemacs#6473]
### What did you expect to happen?

When running `doom sync`, site-lisp files like `/usr/share/emacs/site-lisp/mu4e` should be included in the `load-path` autoloads file (`autoloads.28.1.el`)

### What actually happened?

load-path does not include these files, so I cannot require mu4e without manually adding those paths.

### Describe your attempts to resolve the issue

- I tried running `emacs --no-init-file`. `(require 'mu4e)` works and `load-path` includes the site-lisp folder.
- I ran git bisect and found that the issue started with with 6c0b7e1530a6bbd1fdd19118e26dea690319febf, though I cannot verify this until d5db9076a because doom sync errored on the commits in between. I tested each commit by running `doom sync` and searching the autoloads file.

### Steps to reproduce

1. Install mu4e or another package with site-lisp files
2. Verify that site-lisp is included in load-path when running `emacs --no-init-file`
3. Run `doom sync`
4. Verify that site-lisp is not included in load-path when running doom emacs

### System Information

https://pastebin.com/7Fm7PMV4

**Comment by LemonBreezes** [comment]
I'm having the same issue. A temporary workaround for me is adding `(add-to-list 'load-path "/usr/share/emacs/site-lisp/ebuild-mode")`, since that's the only package I have there.

**Comment by hlissner** [comment]
Can one of you start up Emacs and let me know what the value of `site-run-file` is? The `bin/doom` script intentionally suppresses loading of site files, so [it can load it manually later](https://github.com/doomemacs/doomemacs/blob/master/core/core-cli.el#L52-L69). This works for me on nixos, but perhaps the Emacs package on Arch Linux ships with a different default?

**Comment by yamanq** [comment]
It's "site-start" for me

**Comment by jdn06** [comment]
Same problem on Archlinux and same "site-run-file" with "site-start" value for me.

**Comment by hlissner** [comment]
> same "site-run-file" with "site-start"

If so, then I'm not sure why [the linked snippet](https://github.com/doomemacs/doomemacs/blob/master/core/core-cli.el#L52-L69) doesn't work for you. 

Let's try this: throw this into a file:

```elisp
(require 'cl)
(unless site-run-file
  (let ((site-run-file "site-start")
        (tail load-path)
        (lispdir (expand-file-name "../lisp" data-directory))
        dir)
    (while tail
      (setq dir (car tail))
      (let ((default-directory dir))
        (load (expand-file-name "subdirs.el") t nil t))
      (unless (string-prefix-p lispdir dir)
        (let ((default-directory dir))
          (load (expand-file-name "leim-list.el") t nil t)))
      (setq tail (cdr tail)))
    (load site-run-file t nil)))
```

Then use `emacs -Q --batch -l FILE` to execute it. What does it output?

**Comment by edgar-vincent** [comment]
On Arch Linux, this gives me the following output with Emacs 28:
```
Package cl is deprecated
Loading /usr/share/emacs/28.1.50/lisp/subdirs.el (source)...
```

**Comment by NatHarari** [comment]
> same os, same problem and same `site-run-file` as @jdn06
> 
> > I'm having the same issue. A temporary workaround for me is adding `(add-to-list 'load-path "/usr/share/emacs/site-lisp/ebuild-mode")`, since that's the only package I have there.
> 
> just wanted to add that adding `(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")` before the `mu4e` config in my `~/.config/doom/config.el` solves the issue for now 👍

I'm confirming that this worked for me (with a different path as I'm on a Mac). Thanks very much for posting this! 😀👍

**Comment by Dadams2** [comment]
I have also encountered this problem after removing .local and running `doom sync -up` (I think the key to getting a failure was getting rid of the existing autoloads files as I didn't have any issues before I removed them). Am on Arch and have latest 28.1.50 build.
Can also confirm the `(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")` workaround worked for me as well. I also tried adding the `.local/straight/buildXXXX` and `.local/straight/repos/XXX` paths but they didn't work.

**Comment by timhansinger** [comment]
I can also confirm adding this on my M1 Mac with Emacs installed via homebrew solved the issue:
`(add-to-list 'load-path "/opt/homebrew/share/emacs/site-lisp/mu/mu4e/")`

**Comment by hlissner** [comment]
> I believe that the problem is due to [this](https://www.gnu.org/software/emacs/manual/html_node/emacs/Initial-Options.html#index-_002d_002dquick):

Great catch! I completely missed that. Very happy to have finally put this issue to rest. As of 3b3c008 this should be resolved. Thanks for bringing it to my attention (and for all your help, especially @yamanq, figuring this out)!
