### ISSUE TITLE
doom won't fully upgrade to 49ef0fa8dd

### ISSUE THREAD

**Issue by a2n-s** [doomemacs/doomemacs#6475]
### What did you expect to happen?

i wanted to upgrade my doom Emacs config with `doom upgrade` :yum: 

### What actually happened?

On the first attempt of `doom upgrade`, the script told me 
```bash
> Executing 'doom upgrade' with Emacs 28.1 at 2022-06-19 22:
  > Preparing to upgrade Doom Emacs and its packages...
  - A new version of Doom Emacs is available!
 
    Old revision: 8a27eb99be (6 weeks ago)
    New revision: 49ef0fa8dd (9 hours ago)
 ```
and then the upgrade started until [that error](https://asciinema.org/a/502829) occurs

The backtrace is too big for here and pastebin.com does not want to upload such a big file... :thinking: 
but the file remains on my machine if you want it :+1: 

### Describe your attempts to resolve the issue

I made sure the repo was up to date and did run `doom sync` as suggested by `doom upgrade` but this did nothing :confused: 

### Steps to reproduce

1. open a terminal
2. run `doom upgrade`

### System Information

https://pastebin.com/zhakAc54

**Comment by hlissner** [comment]
Have you tried [upgrading manually](https://github.com/doomemacs/doomemacs/issues/6472#issuecomment-1159707428)? There were some big fixes to our CLI made in the past 48 hours, that older versions of Doom may struggle to upgrade to with `doom upgrade`.

**Comment by a2n-s** [comment]
@hlissner 


> Have you tried [upgrading manually](https://github.com/doomemacs/doomemacs/issues/6472#issuecomment-1159707428)? There were some big fixes to our CLI made in the past 48 hours, that older versions of Doom may struggle to upgrade to with `doom upgrade`.
>
yes i did :confused: 

i did run 
```bash
cd ~/.emacs.d
git pull --rebase
doom sync -u
``` 
once before writing the issue, i.e. trying to upgrade to `49ef0fa8dd`, and right now, i.e. to `b81e4af66a0f` :thinking: 
still getting the same error each time :sob:

**Comment by a2n-s** [comment]
i forgot to close the issue :wink: 
this is clearly not a bug from `doom` but from my side :+1: 

```diff
diff --git a/.config/doom/packages.el b/.config/doom/package
s.el
index 9bac9581..c2c573a9 100644
--- a/.config/doom/packages.el
+++ b/.config/doom/packages.el
@@ -53,10 +53,9 @@
 (package! beacon)
 (package! minimap)
 (package! clippy)
-;; (package! mu4e)
 (package! xresources-theme :recipe
   (:host github
-   :repo "a2n-s/xresources-theme"
+   :repo "martenlienen/xresources-theme"
    :branch "master"))
 (package! rainbow-mode)
 
```
solved the issue for me :ok_hand:

**Comment by hlissner** [comment]
Understood. Thanks for letting me know! I'll see if I can improve that error message, regardless.

**Comment by a2n-s** [comment]
> Understood. Thanks for letting me know! I'll see if I can improve that error message, regardless.
>
it would be really great, 'cause that error on my side was soooo stupid to be honest...

something a tiny bit more precise than a "_`git` error_" would be amazing! :star_struck: 
and maybe leaving the name of the updated package would help as well :thinking: i've seen, during the blink of an eye, the name `xresources-theme`, then i understood what was happening! but, when the error is thrown, the name of the package gets erased :yum:
