### ISSUE TITLE
After upgrading, my literate configuration is not being regenerated.

### ISSUE THREAD

**Issue by offbyone** [doomemacs/doomemacs#6479]
### What did you expect to happen?

When I run `doom sync` or `doom upgrade` I expect my literate configuration in `config.org` to be tangled into `config.el` and other files.

### What actually happened?

No error occurs, but my configuration is not re-tangled.

```
$ doom sync -u
> Synchronizing your config with Doom Emacs...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
```

### Describe your attempts to resolve the issue

Per [workaround on the discord](https://discord.com/channels/406534637242810369/988463711280824320/988475640732856360) I reverted to an older commit, which allowed my configuration to rebuild.

See also #4273, which refers to this.

### Steps to reproduce

1. update doom to the latest version, with `literate` set in `$DOOMDIR/init.el`
2. run `doom sync`

(the system information is in a github gist because my employer blocks _all_ POST to pastebin)

### System Information

https://gist.github.com/offbyone/bc736767e318df2f897ccb7387110f74

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
