### ISSUE TITLE
org-protocol capture doesn't work after doom upgrade

### ISSUE THREAD

**Issue by hwiorn** [doomemacs/doomemacs#6481]
### What did you expect to happen?

When I call `org-protocol://roam-ref?template=....`, it should capture by org.

### What actually happened?

When I call `org-protocol://roam-ref?template=....`, Emacs is trying to open `org-protocol://roam-ref?template=...` itself as a filename.

### Steps to reproduce

1. `doom upgrade`
2. org-protocol capture

### System Information

https://pastebin.com/fD0bmd7Q

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
