### ISSUE TITLE
doom's cli -y toggle no longer accepted, but -! still prompts

### ISSUE THREAD

**Issue by sebasmagri** [doomemacs/doomemacs#6485]
### What did you expect to happen?

I expect not to get prompted on updates

### What actually happened?

I was using `-y` but got an error about this parameter not being accepted. After switching to `-!` as per `--help`, I still got prompted.

### Steps to reproduce

doom -y up

### System Information

https://pastebin.com/VnkYFy4y

**Comment by hlissner** [comment]
Which prompt are you still getting?

**Comment by sebasmagri** [comment]
The prompt to see the diff in the browser and then to continue upgrading.

Il mar 21 giu 2022, 12:09 Henrik Lissner ***@***.***> ha
scritto:

**Comment by mangkoran** [comment]
I can confirm this bug still exists.
```
❯ doom upgrade -!
> Preparing to upgrade Doom Emacs and its packages...
- A new version of Doom Emacs is available!

    Old revision: 9f2d6262e5 (4 hours ago)
    New revision: db3ca52ed6 (7 minutes ago)
```

**Comment by mangkoran** [comment]
As of 1f4b9b7, it seems `doom-cli-context-suppress-propts-p` is not yet implemented. Or am I having misunderstanding?
![image](https://user-images.githubusercontent.com/57625126/174857142-fe1d5c2f-9c0b-4612-94a9-4e46e7c140e9.png)

**Comment by sebasmagri** [comment]
Confirmed the fix! Thanks a lot!
