### ISSUE TITLE
Error running `doom install` with `yes | `: `/home/$USER/.emacs.d/bin/doom: 10: __DOOMPIPE+=0: not found`

### ISSUE THREAD

**Issue by singatullin** [doomemacs/doomemacs#6486]
### What did you expect to happen?

When I make fresh, clean install latest Doom Emacs on top of Emacs 27.1 by running
`git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d`
`yes | ~/.emacs.d/bin/doom install`
it should install without issues.

### What actually happened?

But I get following error:
`/home/username/.emacs.d/bin/doom: 10: __DOOMPIPE+=0: not found`

### Steps to reproduce

1. open Terminal Emulator
2. `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d`
3. `yes | ~/.emacs.d/bin/doom install`
4. get an error

### System Information

issue cames before I can install Doom Emacs

**Comment by singatullin** [comment]
Switched to fish recently and forgot to run it with `bash -c 'commands'` prefix.
Sorry for bothering You.

**Comment by hlissner** [comment]
Is `sh` symlinked to `fish` on your system?

**Comment by singatullin** [comment]
I've changed default login shell with this command:
`chsh -s $(which fish)`

Thank you for quick response, btw.

**Comment by hlissner** [comment]
That shouldn't affect the `bin/doom` script though. It has a `#!/usr/bin/env sh` shebang line, so executing it should use `sh` on your system. Or does fish ignore shebang lines?

**Comment by ckruse** [comment]
I am a Fish user and no, it doesn't, it respects the shebang.

**Comment by singatullin** [comment]
Yes, Fish respects shebang lines. 

I've got a mistake at 3rd step in **Steps to reproduce** section:
3. `yes | ~/.emacs.d/bin/doom install`

So, it doesn't work with `yes | `.
I remember it did, at least couple weeks ago.
And it doesn't matter which shell I run (tried both of them).

**Comment by hlissner** [comment]
I can't reproduce that precise error in bash or zsh (piping `yes` works as expected), so I suspect it's a fish issue, rather than a Doom one.
