### ISSUE TITLE
Make core/core-lib.el loadable in non-Doom environments

### ISSUE THREAD

**Issue by daanturo** [doomemacs/doomemacs#6489]
### Describe your request

Remove the usage of `EMACS28+` and/or move the ";;; Backports" section from `core/core-lib.el` to make it "independent" from other components of Doom.

### Briefly explain its use-case

I want to make use of Doom's lovely API such as `add-hook!`, `cmds!`, `setq!`, `pushnew!`, `add-hook!`, etc. outside of Doom. A way to achieve that is to use `straight` and specify `:files ("core/core-lib.el")`. 

Until recently, even when not using Doom, Emacs can load `core-lib.el` just fine. The usage of `EMACS28+` inside the file broke that.

We can change
`EMACS28+` to `(> emacs-major-version 27)` easily without any loss.

Or `(unless EMACS28+ ...)` to
`(when (< emacs-major-version 28) ...)` (looks more understandable than mentioning 27 only).

**Comment by hlissner** [comment]
It's only one check now, and I think feature checks are more precise, so I don't mind changing it in this case, but this is a terribly brittle arrangement. That backports section _will_ grow and I can't promise it'll always be so portable.

In what context are you using them though? If you're writing elisp scripts, perhaps Doom's new CLI framework can help ([some examples](https://gist.github.com/hlissner/ba8c3b4c6f37c24ff27b72194942b7aa))? Granted, it's not well documented yet (and it's less than a week old), but it'd be much more reliable than loading Doom stuff from afar.
