### ISSUE TITLE
restart-emacs name collision in Emacs 29

### ISSUE THREAD

**Issue by PatrickWulfe** [doomemacs/doomemacs#6492]
### What did you expect to happen?

Using leader q r to call doom/reload-and-restore should restart Emacs and restore the previous session.

### What actually happened?

Due to a name collision with the built in 'restart-emacs' in Emacs 29, this causes a wrong number of arguments error to be displayed.

### Describe your attempts to resolve the issue

This can be fixed by adding this to your config.org

(use-package!
    :config
    (require 'files))
    
 Not sure if this is worth making an issue over since it's specific to Emacs 29, but I use this keybind regularly and thought anyone else running into this issue might appreciate a fix.

### Steps to reproduce

1. Open Emacs 29
2. Call doom/reload-and-restore

### System Information

https://pastebin.com/XtwtYkvX

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
