### ISSUE TITLE
Projectile ignored directories does not work on Mac

### ISSUE THREAD

**Issue by M-Gregoire** [doomemacs/doomemacs#6504]
### What did you expect to happen?

This configuration:
```
(after! projectile
  (add-to-list 'projectile-globally-ignored-directories '"vendor"))
```
is used to globally ignore `vendor` folders in every projects.

### What actually happened?

This works as expected on my machine Linux, but not in Mac OS.

The `projectile-globally-ignored-directories` is correctly set with `"vendor"` appended at the beginning of the list on both OS.

### Describe your attempts to resolve the issue

1. Ran `projectile-invalidate-cache`
2. Reinstall `.emacs.d` to make sure there is no cache whatsoever
3. Made sure to have `rg` and ran `doom env` and `doom sync`

### Steps to reproduce

1. Add `(after! projectile
  (add-to-list 'projectile-globally-ignored-directories '"vendor"))` to your config

2. Create project directory, with a `vendor` directory and a `test` file inside it.
3. Start Emacs, go to the project root
4. `SPC SPC` shows the `vendor/test` file in it's search result 

### System Information

https://pastebin.com/UgWhgSfK

**Comment by elken** [comment]
I can confirm they do work in macos.

https://github.com/elken/doom#ignore-directories

**Comment by M-Gregoire** [comment]
Thanks for your reply, not sure why I quoted the string :roll_eyes:

Unfortunately, this does not seems to be the issue, I've sync my config and removed the cache, but `find-file` still shows results starting with `vendor/` where it doesn't on Linux.

**Comment by M-Gregoire** [comment]
Thank you for your reply @acristoffers .

With `(add-to-list 'projectile-globally-ignored-directories "vendor")`, `projectile-find-file` and `find-file` both show the files in vendor directory.

I've asked for help on [Reddit](https://www.reddit.com/r/emacs/comments/vlt68k/projectile_and_ignore_directories_behavior/): `(add-to-list 'projectile-globally-ignored-directories "*vendor")` followed by `projectile-invalidate-cache` makes the `vendor` directory not appear in `projectile-find-file`, but stills appear in `find-file` as you describe.

However, the need for adding `*` before the vendor is contrary to what I read of the documentation, from what I understood, `*` is used to ignore folder which are not at the root of the project, but my vendor folder is, so I should not need the `*`.

I also struggle to understand how to make `+default/search-project` (`SPC /`) and `find-file` ignore a directory/file. From what I understand, It depends of Vertico (https://github.com/doomemacs/doomemacs/blob/3b789752a30419535b328c605957b6b43a9d47fa/modules/config/default/autoload/search.el#L87) , but after asking in the Vertico project (https://github.com/minad/vertico/issues/246#issuecomment-1168368252), it seems it's dependent of my Doom configuration.

Thank you for any help you might provide.

**Comment by acristoffers** [comment]
The variable `projectile-globally-ignored-directories` only works for projectile itself, so functions from other projects are not going to respect it, which is the case with `find-file` and `+default/search-project`, which in your case is using vertico instead of projectile.

The problem with `projectile-find-file` not working with `*build` is a bug and I reported it: https://github.com/bbatsov/projectile/issues/1783.

`find-file` is a Emacs built-in, so it won't respect projectile anyway.

`+vertico/project-search` is a doom function, so it may be ok to respect the projectile setting there, but I'm not a maintainer, so we need permission to make that, probably.

**Comment by elken** [comment]
Seems like this is getting derailed now. The initial issue was about projectile not respecting directories on Mac, which has been shown to be false.

Please close and file a new issue if there are other requests :)

**Comment by acristoffers** [comment]
It has not been shown to be false, but a bug upstream. The bug exists in the specific case the OP reported. Getting the setting to work somewhere else, on the other hand, may be something worth a new issue.

**Comment by elken** [comment]
> I've asked for help on [Reddit](https://www.reddit.com/r/emacs/comments/vlt68k/projectile_and_ignore_directories_behavior/): (add-to-list 'projectile-globally-ignored-directories "*vendor") followed by projectile-invalidate-cache makes the vendor directory not appear in projectile-find-file

It has, see also my original post. The directory isn't referred to as "vendor", it's "./vendor"; hence the need for correct regex.

**Comment by M-Gregoire** [comment]
Awesome, thank you @acristoffers for confirming, and fixing the issue!

**Comment by bheesham** [comment]
Heads up: I was getting an error with an older version `fd-find` installed (v8.1.1).

When I was searching for files within a project I saw an error related to `--strip-cwd-prefix` in the `*projectile-file-errors*` buffer, showing up where normally the files/projects would show up (forgive me, I'm still new to emacs). Upgrading to fd-find to v8.4.0 fixed this issue for me.

The error I was getting was:

```
error: Found argument '--strip-cwd-prefix' which wasn't expected, or isn't valid in this context

   USAGE:
           fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
^L
error: Found argument '--strip-cwd-prefix' which wasn't expected, or isn't valid in this context

                USAGE:
                    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```
