### ISSUE TITLE
Doom sandbox modes (vanilla or + modules) don't work

### ISSUE THREAD

**Issue by indigoviolet** [doomemacs/doomemacs#6505]
### What did you expect to happen?

When I hit `doom/sandbox` -> `C-c C-d` or `C-c C-p`, it should load a functional emacs.

### What actually happened?

Instead I got

```
Debugger entered--Lisp error: (void-function doom-initialize)
  (doom-initialize)
  (let ((doom-init-modules-p t)) (doom-initialize) (doom-initialize-core-modules))
  load-with-code-conversion("/tmp/doom-sandbox/init.el" "/tmp/doom-sandbox/init.el" nil t)
  command-line-1(("-l" "/tmp/doom-sandbox/init.el"))
  command-line()
  normal-top-level()
```

### Describe your attempts to resolve the issue

I've upgraded doom to a fairly recent version.

### Steps to reproduce

1. Open doom emacs
2. doom/sandbox
3. C-c C-d or C-c C-p

Note that I'm using chemacs2 with 
```
(
 ;; Doom. These are its defaults, and it's better to use them for doom/sandbox etc to work
 ("default" . ((user-emacs-directory . "~/.emacs.d")
               (env . (("DOOMDIR" . "~/.config/doom")))))
 )
```

### System Information

https://pastebin.com/HQr07pC1

**Comment by workcomplete** [comment]
Having the same issue using doom emacs on KDE/arch

**Comment by aikrahguzar** [comment]
It seems that `doom--sandbox-run` needs a rewrite. `doom-initialize` is now gone and I think elisp file in doom-core have been split/reorganized. Removing calls to `doom-initialize` and then adding calls to load `core-packages.el` and `core-modules.el` allows to `C-c C-d` to complete without error but then I do get bindings from my private config so issues with it run deeper.

**Comment by xeruf** [comment]
temporarily move away your doom config folder I guess

**Comment by hlissner** [comment]
I'm aware of the issue. The new sandbox relies on some as-of-yet-released functionality from the 3.0 release, so the fix for this will coincide with its release and the completion of #4273. I'll leave this open until it is done.

**Comment by vancleve** [comment]
> You can launch Doom with a "blank" config by giving it a non-existent $DOOMDIR:
> 
> $ doom run --doomdir /tmp
> or $ DOOMDIR=/tmp/does/not/exist emacs

This workaround helped, thanks!

**Comment by xeruf** [comment]
Any progress here? Doom is getting more and more broken on my machines and I am struggling to keep it usable, despite multiple re-clones ^^

**Comment by hlissner** [comment]
Sorry for the delay. As of https://github.com/doomemacs/doomemacs/commit/60083a2626dc5f5e91c39d85b65259d838e06a69 and https://github.com/doomemacs/doomemacs/commit/a022e55c08a18cfed97c0695da45553f7f73ab82, `doom/sandbox` should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
