### ISSUE TITLE
the proxy config

### ISSUE THREAD

**Issue by exten** [doomemacs/doomemacs#6507]
### What package(s) should be bumped?

! init.el already exists, skipping
  ! config.el already exists, skipping
  ! packages.el already exists, skipping
  - Envvar file already exists, skipping
  Installing plugins
  > Installing packages...
    > Updating recipe repos...
      > In repository "melpa", remote "origin" has URL
        "https://gh.gcdn.mirr.one/melpa/melpa.git"
      but recipe specifies a URL of
        "https://github.com/melpa/melpa.git"

           1) Abort
           2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
           3) Rename remote "origin" manually, re-create it with correct URL, and fetch
           4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
           5) Delete remote "origin", re-create it with manually set URL, and fetch

        How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4) 1

I set my github proxy, show the message.
what can i do this? choose why number can use my proxy config?

**Comment by hlissner** [comment]
If you want to force Straight to use your git config, set `DOOMGITCONFIG` to the path of your git config file. E.g.

```sh
DOOMGITCONFIG=~/.config/git/config doom sync
```

-----

In the future, please do not post support requests on our issue tracker. It is only for bugs and feature requests. Post on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) instead.
