### ISSUE TITLE
Emacs 27.2 `error in process filter: Symbol's function definition is void: ansi-color-compilation-filter`

### ISSUE THREAD

**Issue by kdtsh** [doomemacs/doomemacs#6515]
### What did you expect to happen?

When performing compilation, ANSI colours should be displayed in the compilation buffer.

### What actually happened?

There is an error in the message echo area: `error in process filter: Symbol's function definition is void: ansi-color-compilation-filter`

### Describe your attempts to resolve the issue

The function `ansi-color-compilation-filter` does not appear to exist in ansi-color.el. This is a new function available in Emacs 28.1 but not Emacs 27.2.

The modification to doom-emacs to provide support for `ansi-color-compilation-filter` is https://github.com/doomemacs/doomemacs/commit/2f7171bf8a5f76c1fbb3b9c91921be270b09c0b5

The modification to Emacs to include the new `ansi-color-compilation-filter` is e.g. https://github.com/emacs-mirror/emacs/commit/f7f2024b86bdcf028ce942e59d1cfdba89747d0b

I have not tested this in Emacs 28.1 (not available in my distro's repository yet) but presumably this does not impact Emacs 28.1 or newer versions.

### Steps to reproduce

1. Open Emacs (27.2 or earlier).
2. Open a project (e.g. 'SPC p p')
3. Compile the project (e.g. 'SPC p R')

### System Information

https://pastebin.com/rcicbWAd

**Comment by kdtsh** [comment]
Hi hlissner, the obvious workaround for this is to upgrade to Emacs 28.1 - however as it stands this doesn't work for anything older than Emacs 28.1. I have not tried reverting my doom-emacs repository to see if this fixes the issue.

Thank you very much as always for Doom Emacs.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kdtsh** [comment]
I performed a `doom sync` and it looks good now :-)
