### ISSUE TITLE
Disable flycheck in a file

### ISSUE THREAD

**Issue by JiaweiChenC** [doomemacs/doomemacs#6518]
### What did you expect to happen?
flycheck doesn't work very well on remote, I'd like to disable it.
I know there are several ways to do that, file local variable, directory local variable, or add a configuration. But none of them did what I want, for example: 
I add 
\# Local Variables:
\# eval: (flycheck-mode nil)
\# End:
in my file, and flycheck mode should be closed every time I open that file, but it still worked.

### What actually happened?

I add 
\# Local Variables:
\# eval: (flycheck-mode nil)
\# End:
in my file, but flycheck mode still works in that file

### Describe your attempts to resolve the issue

I tried to replace the flycheck-mode with visual-line mode and it works as expected.

### Steps to reproduce

1. Open emacs
2. create a python file or something else
3. add eval: (flycheck-mode nil) (add file local variable)
4. close the buffer and reopen it 

### System Information

generated  Jun 28, 2022 18:01:49 system     MacOS 12.4 Darwin 21.5.0 arm64 ns emacs      29.0.50 ~/.emacs.d/ -> ~/.emacs.d/ doom       3.0.0-dev HEAD -> master 3a7eab38 2022-06-20 19:09:50 +0200 ~/.doom.d/ ->            ~/.doom.d/ shell      /bin/zsh features   ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES            NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF            TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS ZLIB traits     gui server-running envvar-file custom-file custom     global-flycheck-mode safe-local-variable-values            connection-local-criteria-alist connection-local-profile-alist            package-selected-packages evil-snipe-mode custom-safe-themes modules    :completion (company + childframe) vertico :ui deft doom doom-dashboard            doom-quit hl-todo modeline ophints (popup +defaults) vc-gutter            vi-tilde-fringe workspaces :editor (evil +everywhere) file-templates fold            snippets :emacs (dired +icons) electric undo vc :term term vterm :checkers            syntax (spell +flyspell) :tools (eval +overlay) lookup (lsp +eglot) magit            pdf :ojs (&nopath macos) :lang (cc +lsp) emacs-lisp ess latex markdown (org            +pretty +roam2) (python +lsp +pyright +conda) rust sh :app calendar :config            (default +bindings +smartparens) packages   (org-roam-ui) (pdf-tools) (evil-matchit) (zotxt) (olivetti) (dumb-jump            :disable t) (ox-reveal) (htmlize) (impatient-showdown) (impatient-mode)            (company-box) unpin      org-roam company-org-roam elpa       htmlize frame-local dash company-box company cdlatex cape auctex

**Comment by hlissner** [comment]
You need to declare variables and specific `eval` forms as "safe". See [this post](https://discourse.doomemacs.org/t/file-and-directory-local-settings/161#security-and-local-variables-3).

Otherwise, the `flycheck-disabled-checkers` variable is already safe, so use `M-x flycheck-verify-setup` to determine what checkers are active in that buffer, then set `flycheck-disabled-checkers` with file-local variables. E.g.

```elis
# Local Variables:
# flycheck-disabled-checkers: (checker1 checker2)
# End:
```

----

In the future, please post user support questions like these on [our Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org/). Our issue tracker is only for issues. Thanks.
