### ISSUE TITLE
Elisp flycheck errors out on "No such file or directory core"

### ISSUE THREAD

**Issue by ymarco** [doomemacs/doomemacs#6522]
### What did you expect to happen?

I expected Flycheck to not error out because of its own load-path issues.

Seems to only happen to elisp files in `~/.config/emacs/.local/straight/repos/*/`

### What actually happened?

The flycheck process fails because it failed to `(require 'core)`

Backtrace:
<details><pre>
Suspicious state from syntax checker emacs-lisp: Flycheck checker emacs-lisp returned 255, but its output contained no errors: 
Error: file-missing ("Cannot open load file" "No such file or directory" "core")
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0x5d904200e5179b8>))
  debug-early-backtrace()
  debug-early(error (file-missing "Cannot open load file" "No such file or directory" "core"))
  require(core)
  (progn (setq doom-modules '#<hash-table equal 54/65 0x156389e8913b> doom-disabled-packages '(org-msg mu4e-msg org-fancy-priorities org-appear org-superstar mu4e-alert evil-escape explain-pause-mode)) (require 'core) (require 'core-cli-lib) (ignore-errors (load "/home/ym/.config/emacs/core/core-start.el" t t)) (setq byte-compile-warnings '(obsolete cl-functions interactive-only make-local mapcar suspicious constants)) (defmacro map! (&rest _)))
  (progn (progn (setq doom-modules '#<hash-table equal 54/65 0x156389e8913b> doom-disabled-packages '(org-msg mu4e-msg org-fancy-priorities org-appear org-superstar mu4e-alert evil-escape explain-pause-mode)) (require 'core) (require 'core-cli-lib) (ignore-errors (load "/home/ym/.config/emacs/core/core-start.el" t t)) (setq byte-compile-warnings '(obsolete cl-functions interactive-only make-local mapcar suspicious constants)) (defmacro map! (&rest _))) (progn (defvar jka-compr-inhibit) (unwind-protect (let ((jka-compr-inhibit t)) (when (equal (car command-line-args-left) "--") (setq command-line-args-left (cdr command-line-args-left))) (require 'bytecomp) (defvar flycheck-byte-compiled-files nil) (let ((byte-compile-dest-file-function (lambda (source) (let ((temp-file (make-temp-file (file-name-nondirectory source)))) (push temp-file flycheck-byte-compiled-files) temp-file)))) (unwind-protect (byte-compile-file (car command-line-args-left)) (mapc (lambda (f) (ignore-errors (delete-file f))) flycheck-byte-compiled-files)) (when (bound-and-true-p flycheck-emacs-lisp-check-declare) (check-declare-file (car command-line-args-left))))) (setq command-line-args-left nil))))
  eval((progn (progn (setq doom-modules '#<hash-table equal 54/65 0x156389e8913b> doom-disabled-packages '(org-msg mu4e-msg org-fancy-priorities org-appear org-superstar mu4e-alert evil-escape explain-pause-mode)) (require 'core) (require 'core-cli-lib) (ignore-errors (load "/home/ym/.config/emacs/core/core-start.el" t t)) (setq byte-compile-warnings '(obsolete cl-functions interactive-only make-local mapcar suspicious constants)) (defmacro map! (&rest _))) (progn (defvar jka-compr-inhibit) (unwind-protect (let ((jka-compr-inhibit t)) (when (equal (car command-line-args-left) "--") (setq command-line-args-left (cdr command-line-args-left))) (require 'bytecomp) (defvar flycheck-byte-compiled-files nil) (let ((byte-compile-dest-file-function (lambda (source) (let ((temp-file (make-temp-file (file-name-nondirectory source)))) (push temp-file flycheck-byte-compiled-files) temp-file)))) (unwind-protect (byte-compile-file (car command-line-args-left)) (mapc (lambda (f) (ignore-errors (delete-file f))) flycheck-byte-compiled-files)) (when (bound-and-true-p flycheck-emacs-lisp-check-declare) (check-declare-file (car command-line-args-left))))) (setq command-line-args-left nil)))) t)
  command-line-1(("--directory" "/home/ym/.config/emacs/.local/straight/repos/tree-sitter-langs/" "--eval" "(setq package-user-dir \"/home/ym/.config/emacs/.local/straight/repos/tree-sitter-langs/.cask/29.0/elpa\")" "--eval" "(with-demoted-errors \"Error during package initialization: %S\" (package-initialize))" "--eval" "(progn (require 'bytecomp) (setq byte-compile-root-dir \"/home/ym/.config/emacs/.local/straight/repos/tree-sitter-langs/\"))" "--eval" "(progn (progn (setq doom-modules '#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ((:completion . company) (:flags nil :path \"/home/ym/.config/emacs/modules/completion/company/\") (:completion . vertico) (:flags nil :path \"/home/ym/.config/emacs/modules/completion/vertico/\") (:ui . doom) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/doom/\") (:ui . doom-dashboard) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/doom-dashboard/\") (:ui . hl-todo) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/hl-todo/\") (:ui . modeline) (:flags (+light) :path \"/home/ym/.config/emacs/modules/ui/modeline/\") (:ui . nav-flash) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/nav-flash/\") (:ui . ophints) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/ophints/\") (:ui . popup) (:flags (+defaults) :path \"/home/ym/.config/emacs/modules/ui/popup/\") (:ui . vc-gutter) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/vc-gutter/\") (:ui . window-select) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/window-select/\") (:ui . workspaces) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/workspaces/\") (:ui . zen) (:flags nil :path \"/home/ym/.config/emacs/modules/ui/zen/\") (:editor . evil) (:flags (+everywhere) :path \"/home/ym/.config/emacs/modules/editor/evil/\") (:editor . file-templates) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/file-templates/\") (:editor . fold) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/fold/\") (:editor . format) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/format/\") (:editor . lispy) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/lispy/\") (:editor . multiple-cursors) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/multiple-cursors/\") (:editor . snippets) (:flags nil :path \"/home/ym/.config/emacs/modules/editor/snippets/\") (:emacs . dired) (:flags (+icons) :path \"/home/ym/.config/emacs/modules/emacs/dired/\") (:emacs . ibuffer) (:flags nil :path \"/home/ym/.config/emacs/modules/emacs/ibuffer/\") (:emacs . electric) (:flags nil :path \"/home/ym/.config/emacs/modules/emacs/electric/\") (:emacs . vc) (:flags nil :path \"/home/ym/.config/emacs/modules/emacs/vc/\") (:emacs . undo) (:flags nil :path \"/home/ym/.config/emacs/modules/emacs/undo/\") (:term . vterm) (:flags nil :path \"/home/ym/.config/emacs/modules/term/vterm/\") (:tools . tree-sitter) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/tree-sitter/\") (:tools . editorconfig) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/editorconfig/\") (:tools . eval) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/eval/\") (:tools . lookup) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/lookup/\") (:tools . lsp) (:flags (+peek) :path \"/home/ym/.config/emacs/modules/tools/lsp/\") (:tools . magit) (:flags (+forge) :path \"/home/ym/.config/emacs/modules/tools/magit/\") (:tools . pdf) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/pdf/\") (:tools . rgb) (:flags nil :path \"/home/ym/.config/emacs/modules/tools/rgb/\") (:checkers . syntax) (:flags nil :path \"/home/ym/.config/emacs/modules/checkers/syntax/\") (:lang . json) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/json/\") (:lang . cc) (:flags (+lsp) :path \"/home/ym/.config/emacs/modules/lang/cc/\") (:lang . csharp) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/csharp/\") (:lang . data) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/data/\") (:lang . emacs-lisp) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/emacs-lisp/\") (:lang . java) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/java/\") (:lang . javascript) (:flags (+lsp) :path \"/home/ym/.config/emacs/modules/lang/javascript/\") (:lang . latex) (:flags (+fold +latexmk) :path \"/home/ym/.config/emacs/modules/lang/latex/\") (:lang . lua) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/lua/\") (:lang . markdown) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/markdown/\") (:lang . org) (:flags (+dragndrop +present +roam2) :path \"/home/ym/.config/emacs/modules/lang/org/\") (:lang . python) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/python/\") (:lang . rest) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/rest/\") (:lang . rust) (:flags (+tree-sitter) :path \"/home/ym/.config/emacs/modules/lang/rust/\") (:lang . sh) (:flags (+lsp) :path \"/home/ym/.config/emacs/modules/lang/sh/\") (:lang . web) (:flags nil :path \"/home/ym/.config/emacs/modules/lang/web/\") (:lang . zig) (:flags niCannot open load file: No such file or directory, core
l :path \"/home/ym/.config/emacs/modules/lang/zig/\") (:email . mu4e) (:flags (+gmail) :path \"/home/ym/.config/emacs/modules/email/mu4e/\") (:config . default) (:flags (+bindings +smartparens) :path \"/home/ym/.config/emacs/modules/config/default/\"))) doom-disabled-packages '(org-msg mu4e-msg org-fancy-priorities org-appear org-superstar mu4e-alert evil-escape explain-pause-mode)) (require 'core) (require 'core-cli-lib) (ignore-errors (load \"/home/ym/.config/emacs/core/core-start.el\" t t)) (setq byte-compile-warnings '(obsolete cl-functions interactive-only make-local mapcar suspicious constants)) (defmacro map! (&rest _))) (progn (defvar jka-compr-inhibit) (unwind-protect (let ((jka-compr-inhibit t)) (when (equal (car command-line-args-left) \"--\") (setq command-line-args-left (cdr command-line-args-left))) (require 'bytecomp) (defvar flycheck-byte-compiled-files nil) (let ((byte-compile-dest-file-function (lambda (source) (let ((temp-file (make-temp-file (file-name-nondirectory source)))) (push temp-file flycheck-byte-compiled-files) temp-file)))) (unwind-protect (byte-compile-file (car command-line-args-left)) (mapc (lambda (f) (ignore-errors (delete-file f))) flycheck-byte-compiled-files)) (when (bound-and-true-p flycheck-emacs-lisp-check-declare) (check-declare-file (car command-line-args-left))))) (setq command-line-args-left nil))))" "--" "/home/ym/.config/emacs/.local/straight/repos/tree-sitter-langs/flycheck_tree-sitter-langs.el"))
  command-line()
  normal-top-level()
</pre></details>

### Describe your attempts to resolve the issue

This is the line making the error:
https://github.com/doomemacs/doomemacs/blob/a570ffe16c24aaaf6b4f8f1761bb037c992de877/modules/lang/emacs-lisp/autoload.el#L264

### Steps to reproduce

1. Open Emacs
2. Open an elisp file in `~/.config/emacs/.local/straight/repos/*/`
3. Press something like `ESC` to trigger Flycheck
4. See the error message and backtrace is the echo area

### System Information

https://pastebin.com/7JKiGUXt

**Comment by jadestrong** [comment]
I also encounter this error.

**Comment by hlissner** [comment]
As of afa154db27fc5ff710e8c76061c7579eee2cd918 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
