### ISSUE TITLE
Help flag ignores pager

### ISSUE THREAD

**Issue by xeruf** [doomemacs/doomemacs#6526]
### What did you expect to happen?

--pager option is respected

### What actually happened?

    doom --pager true upgrade --help

does not paginate, while

    doom --pager false install --help

does paginate

### Steps to reproduce

    doom --pager true upgrade --help
    doom --pager false install --help

in an appropriately sized terminal

### System Information

https://pastebin.com/CjgTs1QH

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
