### ISSUE TITLE
typescript-tsx-mode does not work well with tree-sitter (incorrect syntax highlighting, closing tags)

### ISSUE THREAD

**Issue by vikigenius** [doomemacs/doomemacs#6528]
### What did you expect to happen?

tree-sitter should work with typescript-tsx-mode as mentioned in the docs.

### What actually happened?

After enabling tree-sitter for javascript editing .tsx files has poor experience. Syntax highlighting is incorrect and closing tags are incorrect.

### Describe your attempts to resolve the issue

Disabling tee-sitter gives correct syntax highlighting and closing tags again.

### Steps to reproduce

1. Enable tree-sitter and add it for javascript and web-mode
2. Open a TSX file, use the following example snippet

```
import React from 'react';

export type ArrowIndicatorProps = {
  onClick: React.MouseEventHandler<HTMLElement>;
}

function ArrowIndicator(props: ArrowIndicatorProps): React.ReactElement {
  return (
    <div id='arrow-indicator'>
      <span></span>
      <span></span>
      <span></span>
      <div></div>
      <span></div> // This is a result of incorrect closing tags start typing <span></ it automatically closes it to div
    </div>
  )
}

```
![scrot_20220702_190701](https://user-images.githubusercontent.com/12724810/177018448-570808ac-4ab3-4700-9c2a-f7b74b875127.png)

In the image you can see incorrect highlighting of div.

Saving, closing and reopening emacs fixes the old highlighting, but it happens again with new tags. Obviously the incorrect closing tags happen every time.

### System Information

https://pastebin.com/rhyP945Q

**Comment by jeetelongname** [comment]
This should be fixed [using this commit](https://github.com/doomemacs/doomemacs/commit/8e68cd5ffd56d04fc25f2505760899f94a189712) though I forgot to add it to the commit (and its a little late now...)
