### ISSUE TITLE
Replace racer (deprecated) with rust-analyzer

### ISSUE THREAD

**Issue by kquote03** [doomemacs/doomemacs#6529]
### What did you expect to happen?

Having code completion when editing rust source code. 

### What actually happened?

Racer just does not work. It is not currently installed on my system, when I try to install it, I encounter this bug: https://github.com/racer-rust/racer/issues/1181

The proposed solution is to downgrade rust to a 3 month old nightly. The developers even mention that racer is no longer developed in the readme

### Describe your attempts to resolve the issue

Trying to install racer manually

### Steps to reproduce

1. Open Emacs
2. Edit rust file
3. mfw no code completion.rs
4. log https://gist.github.com/kquote03/68c1886fcc0bd89bf8769ef402dcce89

### System Information

https://pastebin.com/qF55iBcX

**Comment by hlissner** [comment]
Rust-analyzer support already exists. [This guide](https://discourse.doomemacs.org/t/set-up-lsp-mode-or-eglot-for-insert-language-here/62) shows you how to enable it (i.e. LSP support in general).

As this request is already fulfilled, I will close this.

**Comment by kquote03** [comment]
thank you
