### ISSUE TITLE
user-emacs-directory

### ISSUE THREAD

**Issue by jkroes** [doomemacs/doomemacs#6530]
### What did you expect to happen?

`user-emacs-directory` is equivalent to `doom-emacs-dir`, but if not nothing about Doom Emacs should break. 

### What actually happened?

commit 46844b55de0eb1df690c50261cfe8997308b5bc2 changed `user-emacs-directory` from `doom-emacs-dir` to `doom-cache-dir`. The log notes that "this introduces an edge case for any legitimate uses of the variable...but I've found no such uses in any of the packages I've audited for Doom or elsewhere." What about `+default/search-emacsd`? Now recursive text searches within `user-emacs-directory` only return results from within cache files. 

### Describe your attempts to resolve the issue

Had to scrub all references to `user-emacs-directory` from my personal config and patch at least one Doom module.

### Steps to reproduce

N/A

### System Information

N/A

**Comment by hlissner** [comment]
As of 442d607 the old uses of `user-emacs-directory` have been removed, which should resolve this issue. Let me know if you run into any other references to it and I'll reopen it. Thanks for bringing it to my attention!
