### ISSUE TITLE
CLI: `doom env --allow` fails

### ISSUE THREAD

**Issue by bpic** [doomemacs/doomemacs#6534]
### What did you expect to happen?

When doing `.emacs.d/bin/doom env -a '^SSH_'`, il expect the file `.emacs.d/.local/env` to be created/overriden and contain my environment variables which names start with "SSH_" (namely `SSH_AUTH_SOCK` and `SSH_AGENT_PID`)

### What actually happened?

```
$ .emacs.d/bin/doom env --allow '^SSH_'
Error: -a/--allow/-d/--deny received invalid value "^SSH_"

Validation errors:
- .

See 'doom h[elp] env' or 'doom env {-?,--help}' for documentation.
```

And the `.emacs.d/.local/env` file is not updated.

### Describe your attempts to resolve the issue

Without the `--allow` option, the command works and the file is updated (but does not contain the environment variables starting with "SSH_"

```
$ .emacs.d/bin/doom env
> Regenerating envvars file
  ✓ Generated ~/.emacs.d/.local/env
```

Adding `--debug` to the command line does not give any extra output.
The same result is obtained with both the fish shell and bash.

### Steps to reproduce

With a fresh install of doom (commit acae9f9acb328c46f71b4cc975abcdb95c09cee6)
1. Open a terminal
2. Type `~/.emacs.d/bin/doom env --allow '^SSH_'` and press return

### System Information

https://pastebin.com/WTsnFvSK

**Comment by hlissner** [comment]
As of cd8fb00, this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by bpic** [comment]
Thanks a lot for the super fast fix !
I confirm that it now works as expected for me.
