### ISSUE TITLE
default value of `bookmark-default-file` has changed from `.local/etc/bookmark` to `.local/cache/bookmark`

### ISSUE THREAD

**Issue by duog** [doomemacs/doomemacs#6540]
### What did you expect to happen?

* Start doom. 
* `SPC RET` show's bookmarks as saved in $DOOMDIR/.local/etc/bookmarks 

### What actually happened?

The presented list of bookmarks is empty.

### Describe your attempts to resolve the issue

I found my existing bookmarks in `.local/etc/bookmarks`.

The value of `bookmark-default-file` is $DOOMDIR/`.local/cache/bookmarks`

I suspect the culprit is: 46844b55de0eb1df690c50261cfe8997308b5bc2

### Steps to reproduce

This is an upgrade problem, I have not tested the instructions below. 

* start fresh install of doom at a commit older than 46844b55de0eb1df690c50261cfe8997308b5bc2
* observe value of `bookmark-default-file` is `.emacs.d/.local/etc/bookmarks`
* create a bookmark
* `SPC RET` observer your created bookmark
* upgrade doom to HEAD
* start doom
* `SPC RET`
* observe empty bookmarks
* observe value of `bookmark-default-file` is `.emacs.d/.local/cache/bookmarks`

### System Information

https://pastebin.com/K5sRKkyW

**Comment by rittelle** [comment]
This seems to have happened to me, too.
My current workaround is adding this to my `config.el`:
```elisp
(after! bookmark
        (setq bookmark-default-file  (concat user-emacs-directory "../etc/bookmarks")))
```

**Comment by hlissner** [comment]
Sorry for the delay. As of 52bda5f `bookmark-default-file` should default to doom-etc-dir, resolving this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
