### ISSUE TITLE
org-meta-return is broken in Doom's org (9.6-??-e9da29b6f)

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#6544]
### What did you expect to happen?

If my org file contains (<marks the cursor>)
** toto <>tata titi
Hitting M-Return (org-meta-return, which calls org-insert-heading) is supposed to result in:
** toto
** <>tata titi

Indeed, `org-meta-return` calls `org-insert-heading` and `C-h a org-insert-heading` says:
"If point is in the middle of a line, split it and create a new
headline with the text in the current line after point (see
org-M-RET-may-split-line on how to modify this behavior).  As
a special case, on a headline, splitting can only happen on the
title itself.  E.g., this excludes breaking stars or tags."

And `org-M-RET-may-split-line` is set to:
((default . t))

### What actually happened?

If my org file contains (<marks the cursor>)
** toto <>tata titi
Hitting M-Return results in:
** toto tata titi
** <>
which does not respect the current settings of `org-meta-return` / `org-insert-heading` / `org-M-RET-may-split-line`

### Describe your attempts to resolve the issue

PRELIMINARY NOTE: I'm a newbie in Emacs/Doom/Lisp, so the "hacks" I tried, listed below, might be totally irrelevant... Sorry if it is the case

I've attempted many things, but the reported `org-version` in DoomEmacs is "9.6-??-e9da29b6f", which does not exist in the `org` repository (latest release is 9.5.4)... So in the end I'm not sure I'm resolving the correct problem with the correct version.
What I tried:

- Disabling Doom's version of `org` in `init.el` and installing MELPA's org with `list-packages`
  => results in errors when using some org commands (probably `org-*` packages are not in sync anymore with `org`) ?

- Cloning actual `org` repo in `/tmp`, checking out commit `e9da29b6f`, running `emacs -Q`, loading `org` with `(add-to-list 'load-path "/tmp/...") (load "org")` , running `M-x org-reload`
  => executing `org-version` still reports 9.3 (Vanilla Emacs builtin) version being used

- Going to /home/user/.emacs.doom.d/.local/straight/repos/org/ and `git pull`ing lastest commit (Doom's `org` version is >24k commits behind?!?)
  => not sure how to compile the new code. I did it manually with `make` in `/repos/`, then moved `*.elc` files to '/built-27.1/' with no success
  => plus : `doom sync/upgrade` reverts these changes

- Editing `/home/gmuller/.emacs.d/modules/lang/org/packages.el` to set org :pin to latest `org` repo  commit (`71359820221ec18d27fab28403d4fd3537ca0491`) and running doom sync/sync -u/upgrade
 => no noticeable change

### Steps to reproduce

- Create an org file which contains
`** toto tata titi`
- Move cursor to middle of line
`** toto <>tata titi`
- Hit M-Return
- Observe the unexpected results:
```
** toto tata titi
** <>
```

### System Information

https://pastebin.com/XcSGmN5Z

**Comment by archiif** [comment]
It seems that because of the way `org-insert-heading` is designed, headline splitting can only occur if you set `org-insert-heading-respect-content` to `nil`, but do note that this will change the behavior of header insertions.

**Comment by liar666** [comment]
Very nice. Works perfectly. Thanks !
