### ISSUE TITLE
evil-terminal-cursor-changer upstream

### ISSUE THREAD

**Issue by basaran** [doomemacs/doomemacs#6551]
### What did you expect to happen?

`Prereq`
Enabled `os: tty` from the init.el

`Expected`
Cursor Change for Evil States

### What actually happened?

Cursor did not change (It did change without tmux)

### Describe your attempts to resolve the issue

Resolution
`kisaragi-hiu` fork has tmux capabilities, but I think they are for older versions of tmux or something. Meanwhile upstream `7696122` updated about two weeks ago.

I have:

- removed evil-terminal-cursor-changer from .local, and build
- manually cloned from `7696122`
- doom sync
- alacritty + tmux + emacs = cursor change

### Steps to reproduce

Enable os tty then,

1. Alacritty, Termite, Xterm etc
2. Tmux-3
3. Emacs -nw

### System Information

https://pastebin.com/niuUGsSF

**Comment by hlissner** [comment]
This should now be resolved (see https://github.com/doomemacs/doomemacs/pull/6565#issuecomment-1193136706 for the follow-up).
