### ISSUE TITLE
Projectile do not remember remote projects

### ISSUE THREAD

**Issue by TransshipmentEnvoy** [doomemacs/doomemacs#6552]
### What did you expect to happen?

When I add a remote project to projectile, the project should be remembered and next time I launch emacs, I should see that remote project.

### What actually happened?

When I add a remote project to projectile, the project is remembered. After I exit emacs and launch again, the remote project disappears.

### Describe your attempts to resolve the issue

1. I watched the `projectile.projects` file. The file contains the remote project after the emacs exits. However, the remote project disappear in the cache as soon as emacs is launched again.
2. There is an upstream issue about this: https://github.com/bbatsov/projectile/issues/1649. It is fixed upstream, but the problem remains in doom emacs.

### Steps to reproduce

1. tramp to a remote, password protected server `C-x C-f /ssh:server:`
2. open remote project `C-x C-f /ssh:server:/path/to/remote/project`
3. `M-x projectile-add-known-project`
4. remote project in `projectile-known-projects`
5. `C-x C-c`
6. launch `emacs` again
7. the remote project doesn't appear in `projectile-known-projects`

### System Information

https://pastebin.com/K0SH3Hyb

**Comment by stites** [comment]
I believe I found the cause of this bug in https://github.com/bbatsov/projectile/issues/1649#issuecomment-1234677133. The fix is to `(require 'tramp)` before you start projectile-mode.

**Comment by hlissner** [comment]
As of 42ac62d this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
