### ISSUE TITLE
dirvish: getting void-variable dired-omit-files errors when activating dirvish

### ISSUE THREAD

**Issue by teehemkay** [doomemacs/doomemacs#6562]
### What did you expect to happen?

when I activate dirvish (`+dirvish`) on `emacs: dired` I expected to not get `void-variable dired-omit-files` errors.

### What actually happened?

I'm constantly getting `void-variable dired-omit-files errors` which prevents opening any file in emacs. 

### Describe your attempts to resolve the issue

The error seems to be triggered [here](https://github.com/doomemacs/doomemacs/blob/33c5f3721a704c72e49efc5960be3785d1a80b81/modules/emacs/dired/config.el#L148) (at least it disappears when I remove that line) and as far as I could tell `dired-omit-files` is defined in `dired-x`...

You may want to consider *not* disabling `dired-x`. Please note that dirvish author [confirmed](https://github.com/alexluigit/dirvish/discussions/76) that to his knowledge there should be not incompatibilities between `dirvish` and `dired-x`.

FWIW I've `(unpin dirvish)` to use the latest version.

### Steps to reproduce

Add the `+dirvish` flag to `dired` in your `init.el` file.
Add `(unpin dirvish)` to your `packages.el` file.
Run `doom sync`

### System Information

https://pastebin.com/EweaG5bu

**Comment by teehemkay** [comment]
Ping @zrquan

**Comment by Patryk27** [comment]
FWIW, I've also had to add an explicit `(require 'dired-x)`:
```patch
diff --git a/modules/emacs/dired/config.el b/modules/emacs/dired/config.el
index 2d6c18272..3b5d49e78 100644
--- a/modules/emacs/dired/config.el
+++ b/modules/emacs/dired/config.el
@@ -142,6 +142,7 @@ we have to clean it up ourselves."
   :init (after! dired (dirvish-override-dired-mode))
   :hook (dired-mode . dired-omit-mode)
   :config
+  (require 'dired-x)
   (setq dirvish-cache-dir (concat doom-cache-dir "dirvish/")
         dirvish-hide-details nil
         dirvish-attributes '(git-msg)
@@ -184,7 +185,6 @@ we have to clean it up ourselves."
 
 
 (use-package! dired-x
-  :unless (featurep! +dirvish)
   :unless (featurep! +ranger)
   :hook (dired-mode . dired-omit-mode)
   :config
```

**Comment by zrquan** [comment]
Sorry for the late reply and my mistake, I don't know why I always get dired-x loaded even though I don't explicitly require it 😵
