### ISSUE TITLE
void-variable doom-debug-p

### ISSUE THREAD

**Issue by neildavidforrest** [doomemacs/doomemacs#6563]
### What did you expect to happen?

Being able to launch emacs, or run doom sync.

### What actually happened?

When running `~/.emacs.d/bin/doom --help`, or sync/upgrade etc.

```
Debugger entered--Lisp error: (doom-private-error "init.el" (void-variable doom-debug-p))
  signal(doom-private-error ("init.el" (void-variable doom-debug-p)))
  (let* ((source (file-name-sans-extension target)) (err (cond ((not (featurep 'core)) (cons 'error (file-name-directory path))) ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((file-in-directory-p source (expand-file-name "cli" doom-core-dir)) (cons 'doom-cli-error (expand-file-name "cli" doom-core-dir))) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))
  doom--handle-load-error((void-variable doom-debug-p) "/home/neil/.doom.d/init" "~/.doom.d/")
  (condition-case e (let (file-name-handler-alist) (load (expand-file-name doom-module-init-file doom-private-dir) t 'nomessage)) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (doom--handle-load-error e (expand-file-name doom-module-init-file doom-private-dir) doom-private-dir)))
  eval-buffer(#<buffer  *load*> nil "/home/neil/.emacs.d/bin/doom" nil t)  ; Reading at buffer position 5685
  load-with-code-conversion("/home/neil/.emacs.d/bin/doom" "/home/neil/.emacs.d/bin/doom" nil t)
  load("/home/neil/.emacs.d/bin/doom" nil t)
  command-line-1(("--no-splash" "--load" "/home/neil/.emacs.d/bin/doom" "--" "--help"))
  command-line()
  normal-top-level()
```

### Describe your attempts to resolve the issue

Using git bisect, the first commit that results in this error is 14b239542414db812b32f9eca4fb58016d93d687 which refers to removing this variable as it is unused.

Perhaps the variable is still cached somewhere, but I'm not really sure how to resolve this.

I also tried to remove all *.elc files from .emacs.d, however this didn't resolve the issue.

`find . -name "*.elc" -type f | xargs rm -f`

### Steps to reproduce

Run doom upgrade to receive a version after 14b239542414db812b32f9eca4fb58016d93d687

I assume that this is not sufficient to reproduce the issue, otherwise I would have found other issues reported here.

I recently switched from emacs 27 to 28. Not sure if this has any impact though as it was working fine before 14b239542414db812b32f9eca4fb58016d93d687.

### System Information

https://pastebin.com/QUPa4hbA

Thanks for your hard work and patience!

**Comment by hlissner** [comment]
The backtrace suggests you have a reference to `doom-debug-p` in `$DOOMDIR/init.el`. All references to the variable were removed from Doom, so this is likely a private config or migration issue while upgrading.

Alternatively, try deleting `~/.emacs.d/.local/autoloads.*` manually, then run `doom sync`.

If that doesn't work, there's always the nuclear option: delete `~/.emacs.d/.local` and run `doom sync`.

**Comment by ncihnegn** [comment]
Exactly my case.
> The backtrace suggests you have a reference to `doom-debug-p` in `$DOOMDIR/init.el`. All references to the variable were removed from Doom, so this is likely a private config or migration issue while upgrading.

**Comment by neildavidforrest** [comment]
Aha! Same here. Thanks for pointing me in the right direction.

I should have remembered. Many months ago I had added these lines to `init.el` following your suggestions here #4498 and never removed them.

```
;; Profiling startup
;; See: https://github.com/hlissner/doom-emacs/issues/4498
(when doom-debug-p
  (require 'benchmark-init)
  (add-hook 'doom-first-input-hook #'benchmark-init/deactivate))
```

**Comment by hlissner** [comment]
Ah, that makes sense. You can replace `doom-debug-p` with `init-file-debug` (I removed the former since it was redundant with the latter). 

Glad I could help!
