### ISSUE TITLE
[Suggestion] Use `doomacs` as project name

### ISSUE THREAD

**Issue by anddam** [doomemacs/doomemacs#6576]
### Describe your request

I propose to either rename the project to `doomacs` or accept that as official nickname.

Reasons:

1. easier to search as single word without possible meaning conflicts
1. low hanging portmanteau fruit right there
1. Spacemacs does it

### Briefly explain its use-case

1. Install Emacs
2. Install Doom
3. Call it `doomacs`

**Comment by hlissner** [comment]
Thanks for the suggestion, but I don't think the benefit is worth the trouble at this point.

> 1. easier to search as single word without possible meaning conflicts
> 2. low hanging portmanteau fruit right there

"Doom Emacs" seems unique enough to search for, even if "Doom" and "Emacs" alone are not. "doomemacs" works too, if the space is so bothersome. What's more, there's already enough inertia behind its current name (e.g. doomemacs.org, various written/youtube guides, etc) that a new one would be more confusing than helpful, and would split search results between users that are and aren't savvy to this sudden and subtle change.

Not to suggest "Doom Emacs" is the perfect name for a project, but I likely won't be changing the name of the project for anything short of a C&D from idsoftware.

**Comment by anddam** [comment]
>but I likely won't be changing the name of the project for anything short of a C&D from idsoftware.

That's it, I'm calling *the Johns*.
