### ISSUE TITLE
`void-function: length=` error emitted on `magit-diff` in Emacs 27.x

### ISSUE THREAD

**Issue by SimonAltrogge** [doomemacs/doomemacs#6583]
### What did you expect to happen?

When I use `magit-diff`, it should show me a working, colorized diff view.

### What actually happened?

When I use `magit-diff`, it shows a broken diff view, see
![magit-diff](https://user-images.githubusercontent.com/8720147/180209103-1de8cc84-15a2-4492-9e5b-48199ff90c9d.png)

### Steps to reproduce

1. Do a clean install of Doom Emacs
2. Open "init.example.el" in the ".emacs.d" directory
3. Do a change and save the file
4. Execute `magit-diff` and select the "Dwim" action by pressing the "d"-key
5. You will be presented with a broken magit-diff view.

### System Information

https://pastebin.com/x2ZqG5qB

**Comment by snuffop** [comment]
I didn't notice in your steps to reproduce, did you stage and or comit you change to a repository?

**Comment by hlissner** [comment]
Please produce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error.

**Comment by hlissner** [comment]
Seems this has been reported [upstream](https://github.com/magit/magit/issues/4730). Does `doom sync -u && doom build` fix the issue?

**Comment by hlissner** [comment]
As mentioned in #6591, there are `void-function: string-search` errors occurring as well, due to this issue. Something is definitely up with `compat`, as it backports `string-search` for 27.1 users.

**Comment by nedhanks** [comment]
I did a ``` doom sync -u && doom build ```. Did not fix the problems. I will check if I can upgrade to Emacs 28, is it ready for MacOS.

**Comment by g5pw** [comment]
Adding `(package! compat :pin "cc1924fd8b3f9b75b26bf93f084ea938c06f9615")` to package.el and running a `doom sync && doom build` fixed the problem for me

**Comment by minad** [comment]
@hlissner Just had a conversation with @phikal about the Doom version pinning. Doesn't Doom pin all the packages (and its dependencies) which should prevent such issues from happening?

It seems that Magit itself is pinned by packages.el, but its dependency `compat` is not. Is there a way to enforce such pinning too or do you have to list all packages manually? In https://github.com/doomemacs/doomemacs/commit/e4184c6bc3340b055cd8e6ddf40f962fe6785056 the Magit version was bumped. Probably it would have been necessary to add `compat` to the package list there manually? Maybe some CI check could help to prevent such issues?

**Comment by hlissner** [comment]
@minad They would all need to be listed, but that's nothing CI couldn't handle. The real problem: shared dependencies across modules. E.g. Module X wants package A 1.0 and module Y wants package A 2.0. Emacs won't let us load two independent versions of the same codebase in one session, so my compromise was to only pin primary dependencies and leave the rest to their own devices. This often works out fine, since 2nd+ order deps tend to be a little more observant of backwards compatibility, but perhaps compat is the exception.

That said, `doom sync -u` (and `doom upgrade`) should update unpinned packages to HEAD unconditionally, so I'm confused why a `doom sync -u && doom build` (update + recompile) didn't work. Or is the problem that magit requires an _older_ commit?

**Comment by hlissner** [comment]
Ah, that clears it up. In that case I'll go ahead pin it soon. Thanks for your help!

**Comment by hlissner** [comment]
And done! As of dd34802 compat is pinned for the two packages (magit and doom-modeline) that depend on it. The repetition isn't ideal, but a better solution will materialize alongside #4273. 

Run `doom upgrade` to absorb the fix. If the issue persists let me know and I'll reopen the issue. Thanks again for all your help!

**Comment by minad** [comment]
On 7/31/22 17:03, Henrik Lissner wrote:
> And done! As of dd34802
> <https://github.com/doomemacs/doomemacs/commit/dd348025233c2302bafc51d8832c5cc691a91b0f>
> compat is pinned for the two packages (magit and doom-modeline) that
> depend on it. The repetition isn't ideal, but a better solution will
> materialize alongside #4273
> <https://github.com/doomemacs/doomemacs/issues/4273>.
> 
> Run |doom upgrade| to absorb the fix. If the issue persists let me know
> and I'll reopen the issue. Thanks again for all your help!

Compat is also used by Consult. It may be better to pin Compat as part
of the core packages?

**Comment by hlissner** [comment]
> It may be better to pin Compat as part of the core packages?

That's what I plan to do, it's just that there's no easy way to just pin a package without installing it for users who don't have any of these packages installed (however rare that may be). Something I'll adress in #4273.

> Compat is also used by Consult

Ah! Good catch. Will do.
