### ISSUE TITLE
New async tangle doesn't work with `IS-{LINUX,WINDOWS,MAC,BSD}` variables

### ISSUE THREAD

**Issue by archiif** [doomemacs/doomemacs#6588]
### What did you expect to happen?

I sometimes use code blocks in my literate config that tangles conditionally based on the current OS:

```org
#+begin_src shell :tangle (if IS-WINDOWS "yes" "no")
t
#+end_src
```

### What actually happened?

But these Doom-specific convenience variables no longer work with the new async tangle, producing this error:

```elisp
Symbol's value as variable is void: IS-WINDOWS
```

### Describe your attempts to resolve the issue

Of course, the old vanilla way still works, but it's less convenience

```org
#+begin_src shell :tangle (if (memq system-type '(cygwin windows-nt ms-dos)) "yes" "no")
t
#+end_src
```

### Steps to reproduce

1. Activate the `literate` module
2. Add a conditional code block that uses any of the `IS-{LINUX,WINDOWS,MAC,BSD}` variables as a condition
3. Save the file and wait for the tangling process to complete

### System Information

https://pastebin.com/SQyNjgJj

**Comment by hlissner** [comment]
Seems this was a regression introduced in 8df91f0b33a2d771f246ed344a83e77d5aa4246b (where tangling is now offloaded to a child process). As of 043d32f, the tangling process should see Doom's stdlib and global constants, which resolves your issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
