### ISSUE TITLE
`file-missing: /tmp/straight-stderr-26076` error on `doom sync` (on Android+Termux)

### ISSUE THREAD

**Issue by tj64** [doomemacs/doomemacs#6590]
### What did you expect to happen?

run doom sync => sync successfully 

### What actually happened?

```
error "Failed to run %S; see buffer "s"
(program . "git")
(args "rev-parse" "HEAD")
(result file-missing "Cannot redirect stderr" "No such file or directory "/tmp/straight-stderr-26076")
```

### Describe your attempts to resolve the issue

Trying many times, since there are many reports about this with always the same suggestion - try again. 
Deleting all caches inside .local of doom git repo

### Steps to reproduce

1. start Termux on phone 
2. call <<doom-repo>>/bin/doom sync
3. see checking out and building many repos , e.g. ob-async
4. at the end, when Updating recipe repos, "There was an unexpected runtime error"

Not sure if this actually inhibits the sync, or only writing the error log for the failed sync, but on termux there is no /tmp directory. 

"root" = /data/data/com.termux/files
in /files, there is /home and /usr, and there you find /usr/tmp

### System Information

no pastebin, since the termux filesystem is just like it is

**Comment by hlissner** [comment]
This is beyond me, sorry to say. I am unable to test in that environment and there isn't enough information to make many guesses, so I'll have to leave this open to another termux user to debug. Since I cannot reproduce the issue on my Linux, macOS, or Windows VMs, I have only the unconventional operating system left to suspect, but that's all I've got.

**Comment by tj64** [comment]
This boils down to the use of `temporary-file-directory` in line 898 of straight.el. 

`echo $TMPDIR`
 -> /tmp 
in Termux too, unfortunately, and I guess thats where Emacs reads the `temporary-file-directory` .

with 
`export TMPDIR=/data/data/com.termux/files/usr/tmp`
this error can be avoided. 

I close this issue, thanks for Doom Emacs!
