### ISSUE TITLE
Add `+lsp` flag to Nix module

### ISSUE THREAD

**Issue by Lord-Valen** [doomemacs/doomemacs#6592]
### Describe your request

#3973 formerly requested this feature, but it was mistakenly closed as it was [misinterpreted as being merely an upstream issue](https://github.com/doomemacs/doomemacs/issues/3973#issuecomment-757113967). While [rnix-lsp](https://github.com/nix-community/rnix-lsp) was added to [lsp-mode](https://github.com/emacs-lsp/lsp-mode), this was not reflected in the Doom Nix module.

### Briefly explain its use-case

1. Enable `:tools lsp`
2. Enable `:lang nix` with `+lsp` flag
3. Edit nix files with lsp support
4. ???
6. Profit!

**Comment by hlissner** [comment]
As of 26b8383 issue should be resolved. Thanks for bringing it to my attention!
