### ISSUE TITLE
Cannot upgrade: Failed to fetch from upstream

### ISSUE THREAD

**Issue by alienbogart** [doomemacs/doomemacs#6598]
### What did you expect to happen?

Upgrade should happen.

### What actually happened?

Upgrade does not occur due to runtime error:

```
[.doom.d]$ doom upgrade 
> Preparing to upgrade Doom Emacs and its packages...
x There was an unexpected runtime error
  Message: Failed to fetch from upstream
  Backtrace:
    (error "Failed to fetch from upstream")
    (or (= 0 (car (setq result (doom-call-process "git" "fetch" "--force" "--tags" doom-upgrade-remote (format "%s:%s" branch target...
    (let (result) (or (= 0 (car (doom-call-process "git" "remote" "add" doom-upgrade-remote doom-upgrade-url))) (error "Failed to ad...
    (unwind-protect (let (result) (or (= 0 (car (doom-call-process "git" "remote" "add" doom-upgrade-remote doom-upgrade-url))) (err...
    (let* ((branch (replace-regexp-in-string "^\\(?:[^/]+/[^/]+/\\)?\\(.+\\)\\(?:~[0-9]+\\)?$" "\\1" (cdr (doom-call-process "git" "...
    (let ((default-directory doom-emacs-dir) process-file-side-effects) (doom-print (doom-print--format (doom-print--class 'start "P...
    (doom-cli-upgrade nil nil)
    (cond (packages\? (call! sync-cmd) (doom-print (doom-print--format (doom-print--class 'success "Finished upgrading Doom Emacs"))...
    (let* ((force\? (progn (or (progn (and (memq (type-of context) cl-struct-doom-cli-context-tags) t)) (signal 'wrong-type-argument...
    (let ((packages\? (cdr (assq 'packages\? alist))) (jobs (cdr (assq 'jobs alist))) (context (cdr (assq 'context alist)))) (let* (...
    ((closure (t) (cli alist) (let ((packages\? (cdr (assq 'packages\? alist))) (jobs (cdr (assq 'jobs alist))) (context (cdr (assq ...
    (funcall (closure (t) (cli alist) (let ((packages\? (cdr (assq 'packages\? alist))) (jobs (cdr (assq 'jobs alist))) (context (cd...
  ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220726132346.227673.error
✓ Finished in 6.24352s
```

`doom doctor` tells me this, even thought that's a fresh install:

[.doom.d]$ doom doctor
The doctor will see you now...

```
> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
! ~/.emacs.d/.local/straight/build-28.1/bind-key/bind-key.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-bind-key.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-core.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-delight.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-diminish.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-ensure.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-jump.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package-lint.elc is out-of-date
! ~/.emacs.d/.local/straight/build-28.1/use-package/use-package.elc is out-of-date
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-dev
  ✓ Detected 26 modules
  ✓ Detected 115 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...

There are 9 warnings!
```

### Describe your attempts to resolve the issue

I removed `~/.doom.d` and `.emacs.d` and reinstalled from scratch twive.

### Steps to reproduce

Run `$ doom upgrade`.

### System Information

https://pastebin.com/Ui9YYPdp

**Comment by hlissner** [comment]
I'm not entirely sure this issue was related to the one I was fixing in 615848e, but that commit introduces a little more future proofing for the `doom upgrade` command. Unfortunately, this won't prevent folks from running into it once they upgrade past 615848e, so they must unavoidably upgrade manually:

```sh
git reset --hard 35a89bdfa6
git pull origin master
doom sync -u
```

I'll pin this issue, since there will likely be a wave of folks running into this.

**Comment by RomeoV** [comment]
In case anyone else is unsure, the mentioned git commands need to be executed in the `~/.emacs.d` directory if you're running a normal setup.

**Comment by zedeus** [comment]
It's still broken for me after trying the steps mentioned here and in the commit message. Resetting, pulling and running `doom sync -u` all work fine, but running `doom upgrade` afterwards results in the same upstream error. Backtrace: http://ix.io/46w7

![image](https://user-images.githubusercontent.com/9434921/182552156-d919e5a2-ee37-4371-9e18-11acd26654c6.png)

**Comment by iris-garcia** [comment]
I have exactly the same problem as @zedeus

**Comment by jasonm23** [comment]
@iris-garcia @zedeus - have you guys cleared out `rm -rf ~/.doom.d/.local` and then tried `doom sync`?

**Comment by jasonm23** [comment]
@iris-garcia @zedeus - please post the error log as text not a screenshot.

**Comment by jasonm23** [comment]
I'd also try just doing a full clone of doom `.emacs.d` from scratch and then doing `doom sync`

**Comment by jasonm23** [comment]
The error log for the extended backtrace is what we need to see, to help you out.

**Comment by iris-garcia** [comment]
Ok, deleting `.emacs.d` and cloning doom again fixed the issue.
Not sure what was the problem and can't debug it anymore.

Thank you @jasonm23

**Comment by zedeus** [comment]
@jasonm23 I included a link to the extended backtrace, did you miss it?

**Comment by jasonm23** [comment]
I did miss it sorry.

Did a full clean start of emacs d solve it for you too @zedeus

**Comment by jasonm23** [comment]
> @jasonm23 I included a link to the extended backtrace, did you miss it?

The link throws a SSL/HTTPS error on Firefox macos

**Comment by Ban3** [comment]
> It's still broken for me after trying the steps mentioned here and in the commit message.

I needed to remove the leftover branch and remote to get `upgrade` running:
```
git remote remove _upgrade
git branch -D _upgrade_master
```

**Comment by yubrshen** [comment]
I ran into the same error. I found out that it was caused by my creating a new branch locally, `backup-working-before-upgrade`
After removing the new branch, then `doom upgrade` worked.
```
git remote remove _upgrade
git branch -D backup-working-before-upgrade
```
I don't fully understand the meaning of `git remote remove _upgrade`, but executing it didn't cause any problem, nor complaint.
