### ISSUE TITLE
The `projectile-find-file` command errors on fd with `error: Found argument '--strip-cwd-prefix' which wasn't expected, or isn't valid in this context`

### ISSUE THREAD

**Issue by jperras** [doomemacs/doomemacs#6600]
### What did you expect to happen?

Invoking `projectile-find-file` should not error, and should allow filtering of project files.

### What actually happened?

When invoking `projectile-find-file`, the following error is produced:

```
error: Found argument '--strip-cwd-prefix' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

### Steps to reproduce

1. Attempted to load different projects; seems to work for some, and not for others? I can't detect a pattern just yet.
2. Attempted to remove and re-add projects to projectile. Same effect; some projects work, others don't.
3. Attempted to clear projectile cache; no effect.

## Steps to Reproduce

1. Open (doom) emacs, with projectile enabled
4. `SPC p p` to open a project
5. The error will be produced when the `find file` transient window pops up, or if you attempt to manually invoke `projectile-find-file`

### System Information

https://pastebin.com/X7uB1Khr

**Comment by hlissner** [comment]
I'm aware of this issue. Explanation and fix in https://github.com/doomemacs/doomemacs/pull/6597. The workaround is to install fd 8.3 or newer. Will look into addressing this soon.

**Comment by jperras** [comment]
@hlissner ah, thank you for the explanation! My apologies for not finding the draft PR before creating an issue; I only searched open/closed issues.

**Comment by gdonald** [comment]
I've upgraded my `fd` to >=8.3

```
> fd --version
fd 8.4.0
```

```
> which fd
/home/gd/.cargo/bin/fd
```

but I'm still getting projectile errors:

```
error: Found argument '--strip-cwd-prefix' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

**Comment by jperras** [comment]
I upgraded to `8.4` and mine seems to work just fine 🤷‍♂️

**Comment by hlissner** [comment]
This issue should now be resolved (and without upping our minimum supported version to 8.3.0). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by jperras** [comment]
@hlissner no, thank _you_ for all the hard work!

**Comment by nfedyashev** [comment]
10.1.0 works fine too
