### ISSUE TITLE
Doom fails to start: "No such file or directory `core-lib'"

### ISSUE THREAD

**Issue by jackmac92** [doomemacs/doomemacs#6602]
### What did you expect to happen?

Emacs should successfully start after `doom upgrade` (doom doctor does not display any errors, just warnings that already existed)

### What actually happened?

Emacs starts but fails to load my config, when I try to startup with `--debug-init`, the command fails before it makes a frame
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "core-lib")
  require(core-lib)
  load-with-code-conversion("/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." "/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." t t)
  load("/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." t t)
  (if (load (expand-file-name "core/core" user-emacs-directory) t t) (setq init-file (expand-file-name "core-start" doom-core-dir)) (setq early-init-file (expand-file-name "early-init" user-emacs-directory)) (load early-init-file t t))
  (let (init-file) (if (load (expand-file-name "core/core" user-emacs-directory) t t) (setq init-file (expand-file-name "core-start" doom-core-dir)) (setq early-init-file (expand-file-name "early-init" user-emacs-directory)) (load early-init-file t t)) (prog1 (defalias 'startup--load-user-init-file@init-doom #'(lambda (args) "Initialize Doom Emacs in an interactive session." (list #'(lambda nil ...) nil (car (cdr ...))))) (advice-add 'startup--load-user-init-file :filter-args #'startup--load-user-init-file@init-doom)))
  load-with-code-conversion("/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." "/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." t t)
  load("/home/jmccown/.local/emacs.profiles/donkey/emacs.d..." t t)
  (let ((early-init-file (expand-file-name "early-init.el" user-emacs-directory))) (load early-init-file t t))
  chemacs-load-user-early-init()
  load-with-code-conversion("/home/jmccown/.emacs.d/early-init.el" "/home/jmccown/.emacs.d/early-init.el" t t)
  load("/home/jmccown/.emacs.d/early-init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1873a65f39101750>))
  command-line()
  normal-top-level()
```

### Describe your attempts to resolve the issue

wiping cache/rebuilding didn't work. Only downgrading my emacs.d to dd83c455bad0c77f6f903242dc7008b2f6bbe06a
could I start emacs again

### Steps to reproduce

I'm not exactly sure, since I couldn't use --debug-init I'm a bit lost, but it seems like it must be related to the recent profiles feature (I currently use chemacs2 for that)

### System Information

https://pastebin.com/jifK5XjN

**Comment by jackmac92** [comment]
fixed!

**Comment by jeetelongname** [comment]
How was it fixed?

**Comment by jackmac92** [comment]
just kidding, I thought I was testing with the latest, but I was not. And the issue is still present with the latest.

Having trouble understanding how to make profiles work with chemacs2, are the incompatible?

**Comment by hlissner** [comment]
Chemacs _should_ be compatible, but `bin/doom` is not Chemacs aware. You'd have to always provide `--doomdir` (and `--emacsdir` if bin/doom doesn't live in the Emacs config you're targeting). Otherwise, you could set the `$EMACSDIR` and `$DOOMDIR` envvars. 

For example:
```bash
$ doom sync --emacsdir ~/.local/emacs.profiles/donkey/emacs.d/ \
            --doomdir ~/.local/emacs.profiles/donkey/doom/
# or
$ export EMACSDIR=~/.local/emacs.profiles/donkey/emacs.d/
$ export DOOMDIR=~/.local/emacs.profiles/donkey/doom/
$ doom sync
```

If `bin/doom` lives in `~/.local/emacs.profiles/donkey/emacs.d/`, you can omit `--emacsdir`/`$EMACSDIR`.

That said, there've been some improvements to Doom's profile system, so see if updating Doom fixes your original issue

-----

As a workaround or alternative while I look for a solution, [Doom can now act as a bootloader](https://gist.github.com/hlissner/46d6423a49f19d30e34336eb5bc1a07e) (replacing Chemacs), if you prefer.

**Comment by jackmac92** [comment]
I actually already do specify the above vars (via a `.env` file in ~/.local/emacs.profiles/$PROFILE_NAME/.env),  as well as set `DOOMLOCALDIR`

wondering if the local dir could be an issue?

I'd like to keep my chemacs setup if possible, willing to wait a while to see if I can figure out my issue.

But happy to test things and report back if that's useful. The error occurred for me on my linux desktop and my macbook (which  share a common set of dotfiles). So if reproducing the issue is helpful, let me know!

**Comment by jackmac92** [comment]
I removed chemacs and am having the same issue, so it must be something about how I'm configuring dirs with the environment variables.

same as #6608 so I'll close this one
