### ISSUE TITLE
doom-reload does not work

### ISSUE THREAD

**Issue by rittelle** [doomemacs/doomemacs#6603]
### What did you expect to happen?

Calling `M-x doom/reload` shoud call `doom sync`, which in term applies changes to the configuration.

### What actually happened?

The output buffer shows the following log.

```
-*- mode: compilation; default-directory: "~/.emacs.d/core/autoload/" -*-
Comint started at Thu Jul 28 02:50:03

"~/.emacs.d/bin/doom" sync -e
zsh:1: no such file or directory: ~/.emacs.d/bin/doom

Comint exited abnormally with code 127 at Thu Jul 28 02:50:03"
```

### Describe your attempts to resolve the issue

I replaced `%S` with `%s` inside the format string here: https://github.com/doomemacs/doomemacs/blob/1ecb5c7b9b792c940b22591a290c6f65b6039674/core/autoload/config.el#L79
This essentially reverts https://github.com/doomemacs/doomemacs/commit/3ecf95ff35d4bfe23e553eae66a7c34b1612150b .
Using `%S` causes the resulting string to be wrapped in quotes. bash and zsh don't seem to expand "~" in paths when the character is quoted.
`$ doom/reload` has worked for me before and I didn't use doom when the change was made. So something else broke. Maybe value of `doom-bin` has changed?

### Steps to reproduce

1. Open (doom) emacs
2. Verify that `doom-bin` contains a tilde: `M-x eval-expression` then enter `doom-bin`
3. Run `M-x doom/reload`

### System Information

https://pastebin.com/dr7VfR8y

**Comment by rittelle** [comment]
One way to not trigger https://github.com/doomemacs/doomemacs/issues/4249 again would be to expand the tilde ourself somewhere. Maybe when `doom-bin` is set?
Maybe with something like `(s-replace-regexp "^~/" (concat (getenv "HOME") "/") doom-bin)` when on a POSIX-platform?

**Comment by TinyStego** [comment]
Just seeing this now after fixing it myself so I haven't tried rittelle's fix. For me I made a work around by creating a symlink to the doom executable in /usr/local/bin and then edited the core/autoload/config.el with:

    (defvar doom-bin-dir (concat "/usr/local/" "bin/"))

I left the concat in there in the event that there is a better fix.

**Comment by aljab012** [comment]
I got the same issue on macOS. Using @rittelle solution by replacing `%S` with `%s` solves the problem

**Comment by htetyan** [comment]
Was having the same issue after: 

1. Upgraded from 27.2 to 28.1 using railwaycat pre-build release
2. Ran `doom build && doom sync`
3. Upgraded `v21.12.0-alpha` to `v3.0.0-dev`
4. After `doom upgrade` and had to `doom sync` (since it was loading vanilla emacs)
5. Had the same issue during `M-x doom/reload`

**Solved** by using @rittelle solution of replacing line 79 in `/core/autoload/config.el` solved the problem. Thanks @rittelle

**Comment by hlissner** [comment]
As of 35a89bd this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by rittelle** [comment]
Thanks for the quick response. https://github.com/doomemacs/doomemacs/commit/35a89bdfa6064e507f8848b1d162433fe92ca829 did indeed fix the issue for me.
