### ISSUE TITLE
switch-buffer and switch-workspace-buffer not working

### ISSUE THREAD

**Issue by ctaque** [doomemacs/doomemacs#6606]
### What did you expect to happen?

When I do "SPC b b" I get :

![image](https://user-images.githubusercontent.com/48220254/181524609-54d909bc-ae0d-4f7f-a64f-5bb4703a213b.png)

When I do "SPC b B" I get :

![image](https://user-images.githubusercontent.com/48220254/181524907-a60a9ed7-42b4-487f-81e4-54a152781899.png)

Interestingly "SPC p b" (projectile switch buffer) works

Happening on a machine with :   
- doom emacs up to date,
- Emacs 28.1
- Emacs installed via snap on Ubuntu 20.04

Sorry for the screenshots, I could'nt copy the minibuffer content.

### What actually happened?

"SPC b b" expects switch buffer

"SPC b B" expects switch workspace buffer

### Describe your attempts to resolve the issue

I tried updating doom and Emacs several times.

### Steps to reproduce

This happens only on my work machine, not on my home computer

### System Information

https://pastebin.com/RGinWkuW

**Comment by elken** [comment]
Looks like you're using helm and vertico. These aren't meant to be used together, I would imagine this is what's failing.

**Comment by ctaque** [comment]
Alright ! You nailed it. Thank you
