### ISSUE TITLE
Bug: fail to start own profile

### ISSUE THREAD

**Issue by jeffkowalski** [doomemacs/doomemacs#6608]
### What did you expect to happen?

When I issue just `emacs` all is well: I get doom emacs.
If I have a profile effectively pointing the same way, and invoke that with `emacs --profile doom`, it too should start.

### What actually happened?

doom emacs fails to start with `emacs --profile doom`
```
Warning (initialization): An error occurred while loading ‘/home/jeff/.config/emacs/early-init.el’:

File is missing: Cannot open load file, No such file or directory, core-lib

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

### Describe your attempts to resolve the issue

I have not tried to resolve the issue, and have simply reverted to using `emacs` rather than specifying a profile.
Note that /other/ profiles (e.g. prelude) work fine.

### Steps to reproduce

doom is installed at `~/.config/emacs`
personal doom files are at `~/.config/doom`
alternate personal files for bbatsov's prelude are at `~/.config/emacs-prelude`
`~/.config/emacs/profiles.el` contains
```
(
 (doom      . ((user-emacs-directory . "~/.config/emacs")
               (env . (("DOOMDIR" . "~/.config/doom")))))

 (prelude   . ((user-emacs-directory . "~/.config/emacs-prelude")))
)
```

### System Information

https://pastebin.com/Ezvab7Di

**Comment by jeffkowalski** [comment]
just for information, there is no longer any chemacs[2] in the way.  It's doom all the way down... ;)

**Comment by jeffkowalski** [comment]
seems to be related more to user-emacs-directory than to the profile's DOOMDIR
I get the same error if I attempt `emacs --profile doom-virgin` with this in `~/.config/emacs/profiles.el`:
```
(
 (doom        . ((user-emacs-directory . "~/.config/emacs")
                 (env . (("DOOMDIR" . "~/.config/doom")))))

 (doom-virgin . ((user-emacs-directory . "~/.config/emacs")
                 (env . (("DOOMDIR" . "~/.config/doom-virgin")))))

 (prelude     . ((user-emacs-directory . "~/.config/emacs-prelude")))
 )
```

**Comment by montchr** [comment]
I'm running into the same error.

I started with an existing doom configuration which I moved into `$EMACSDIR/profiles/doom`, without `profiles.el`. In that case, `doom` would fail with an error complaining about a missing `profiles.el`, regardless of any combination of flags/subcommands I tried.

So I added the following `profiles.el`:

```
((doom    (user-emacs-directory . "~/.config/emacs")
           (env ("DOOMDIR" . "~/.config/emacs/profiles/doom")))
 (xtallos (user-emacs-directory . "~/.config/profiles/xtallos")))
```

Then I exported `DOOMPROFILE=doom`. That's when I got the missing `core-lib` error while running `doom install` or `doom sync`.

I also tried passing the recommended `--emacsdir` and `--doomdir` flags to point to the corresponding directories:

```
doom sync --emacsdir ~/.config/emacs --doomdir ~/.config/emacs/profiles/doom
```

Still got the `core-lib` error.

After unsetting `DOOMPROFILE`, I could run the same `doom sync ...` command successfully.

**Comment by jackmac92** [comment]
I'm having a similar issue, FWIW all `doom` commands seem to run w/o any issue. Launching emacs directly is where I get an error (not using doom as my bootloader*). `doom sync`/`doom doctor` both complete successfully. Even `doom run` works to launch emacs with my config, but I can't figure out what `emacs` command to run that works

*not at the moment, I tried that earlier and still had an error, but that didn't include #6598 615848e3a71ca9ecd4e50cd7abc49eedc2fbea23 so I may have been in a broken state)

**Comment by jeffkowalski** [comment]
More recently I'm getting the same net failure, but different error message:
```
Warning (initialization): An error occurred while loading ‘/home/jeff/.config/emacs/lisp/doom-start.el’:

Error in Doom Emacs core: Doom is in an incomplete state, run 'doom sync' on the command line to repair it

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```
including `--debug-init` I see
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "/home/jeff/.config/emacs/profiles/doom@latest/init")
  load("/home/jeff/.config/emacs/profiles/doom@latest/init" nil nomessage)
  (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) ((debug file-missing) (if (locate-file doom-autoloads-file load-path) (signal 'doom-autoload-error e) (signal 'doom-error (list "Doom is in an incomplete state" "run 'doom sync' on the command line to repair it")))))
  eval-buffer(#<buffer  *load*> nil "/home/jeff/.config/emacs/lisp/doom-start.el" nil t)  ; Reading at buffer position 7082
  load-with-code-conversion("/home/jeff/.config/emacs/lisp/doom-start.el" "/home/jeff/.config/emacs/lisp/doom-start.el" t t)
  load("/home/jeff/.config/emacs/lisp/doom-start" noerror nomessage)
  #f(compiled-function (filename-function &optional alternate-filename-function load-defaults) "Load a user init-file.\nFILENAME-FUNCTION is called with no arguments and should return\nthe name of the init-file to load.  If this file cannot be\nloaded, and ALTERNATE-FILENAME-FUNCTION is non-nil, then it is\ncalled with no arguments and should return the name of an\nalternate init-file to load.  If LOAD-DEFAULTS is non-nil, then\nload default.el after the init-file, unless `inhibit-default-init'\nis non-nil.\n\nThis function sets `user-init-file' to the name of the loaded\ninit-file, or to a default value if loading is not possible." #<bytecode -0xbc197ac42e841d9>)((closure ((args #f(compiled-function () #<bytecode 0x13532cf9c8d6104e>) #f(compiled-function () #<bytecode 0x4d12c0e0e44348b>) t) (init-file . "/home/jeff/.config/emacs/lisp/doom-start") t) nil (or init-file (expand-file-name "init.el" user-emacs-directory))) (closure ((args #f(compiled-function () #<bytecode 0x13532cf9c8d6104e>) #f(compiled-function () #<bytecode 0x4d12c0e0e44348b>) t) (init-file . "/home/jeff/.config/emacs/lisp/doom-start") t) nil (expand-file-name "safe-mode@static/init.el" doom-profiles-dir)) t)
  apply(#f(compiled-function (filename-function &optional alternate-filename-function load-defaults) "Load a user init-file.\nFILENAME-FUNCTION is called with no arguments and should return\nthe name of the init-file to load.  If this file cannot be\nloaded, and ALTERNATE-FILENAME-FUNCTION is non-nil, then it is\ncalled with no arguments and should return the name of an\nalternate init-file to load.  If LOAD-DEFAULTS is non-nil, then\nload default.el after the init-file, unless `inhibit-default-init'\nis non-nil.\n\nThis function sets `user-init-file' to the name of the loaded\ninit-file, or to a default value if loading is not possible." #<bytecode -0xbc197ac42e841d9>) ((closure ((args #f(compiled-function () #<bytecode 0x13532cf9c8d6104e>) #f(compiled-function () #<bytecode 0x4d12c0e0e44348b>) t) (init-file . "/home/jeff/.config/emacs/lisp/doom-start") t) nil (or init-file (expand-file-name "init.el" user-emacs-directory))) (closure ((args #f(compiled-function () #<bytecode 0x13532cf9c8d6104e>) #f(compiled-function () #<bytecode 0x4d12c0e0e44348b>) t) (init-file . "/home/jeff/.config/emacs/lisp/doom-start") t) nil (expand-file-name "safe-mode@static/init.el" doom-profiles-dir)) t))
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x13532cf9c8d6104e>) #f(compiled-function () #<bytecode 0x4d12c0e0e44348b>) t)
  command-line()
  normal-top-level()
```

**Comment by LeoQiao18** [comment]
I ran into the same issue of not being able to find core-lib. I had an environment variable as `EMACSDIR=$HOME/.config/emacs`. I resolved the issue by adding a slash at the end: `EMACSDIR=$HOME/.config/emacs/`.

Without it, the load-path of doom emacs turns out to include `$HOME/.config/emacscore`, which is obviously not right. Maybe this is something that can be detected when doom emacs add load-path?

**Comment by jackmac92** [comment]
@LeoQiao18 thank you! that fixed my issue as well

**Comment by hlissner** [comment]
There have been a number of fixes to Doom's profile system in the past week. Please update and let me know if this is still an issue.

> File is missing: Cannot open load file, No such file or directory, core-lib

Side-note: `core-lib.el` was renamed to `doom-lib.el` in https://github.com/hlissner/doom-emacs/commit/b9933e6637713ecf518e9ab26fccad5569c0d9fd, so I'm not sure why you're setting that error. Please make sure Doom is up-to-date.

**Comment by hlissner** [comment]
With the two following commits, this issue should now be resolved:

- d8d06390d2c6624884c824fbfcbe7c4cddd402fa -- in case a trailing slash was forgotten when setting `user-emacs-directory` in your profiles.el config file.
- 7aa87eb019ed302a1f6f26fe678e139b645aaaab -- fixes an issue where the profile's init.el was being ignored.

Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
