### ISSUE TITLE
Enabling LaTeX in init.el makes doom upgrade crash

### ISSUE THREAD

**Issue by winkelnp** [doomemacs/doomemacs#6617]
### What did you expect to happen?

enabling LaTeX in init.el simply enables language, updates with ```doom upgrade``` 

### What actually happened?

When `doom upgrade` is run, it gets to "upgrading packages", and crashes with this comment:

```
  > Updating packages (this may take a while)...
    x There was an unexpected runtime error
      Message: Failed to run "git"; see buffer *straight-process*
      Backtrace:
        (error "Failed to run %S; see buffer %s" "git" "*straight-process*")
        (if success (let ((output (concat stdout stderr))) (if straight--pro...
        (let* ((result (apply #'straight--process-run program args)) (exit (...
        (straight--process-output "git" "rev-parse" "HEAD")
        (straight-vc-git-get-commit "latex-preview-pane")
        (apply straight-vc-git-get-commit "latex-preview-pane")
        (let ((func (intern (format "straight-vc-%S-%S" type method)))) (if ...
        (straight-vc get-commit git "latex-preview-pane")
        (let ((straight--default-directory (straight--repos-dir local-repo))...
        (straight-vc-get-commit git "latex-preview-pane")
        (let ((ref (straight-vc-get-commit type local-repo)) (target-ref (cd...
        (condition-case e (let ((ref (straight-vc-get-commit type local-repo...
      ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220731222901.170289.error
```

### Describe your attempts to resolve the issue

I went through all of my enabled packages disabling one at a time and isolated the issue to uncommenting the LaTeX line in init.el

### Steps to reproduce

1. Open Emacs
2. enable LaTeX support in init.el
3. run `doom sync`
4. run `doom upgrade`
5. `doom upgrade` should crash

### System Information

https://pastebin.com/wV9Y1gqW

**Comment by hlissner** [comment]
Errors like these are generally connection issues, not bugs, but it's hard to tell.

I just pushed 4ee7f0113e9cc480090bf5e1685d4748277e7290. This is not a fix for your issue, it is a fix for Doom's error handler, so it will display a more helpful error message when you encounter this. 

Please upgrade manually:

```sh
$ cd ~/.emacs.d
$ git pull
$ doom sync -u
```

Then see if you can reproduce the error.

**Comment by winkelnp** [comment]
I have run `doom sync -u` and this is what the error shows:
```
  > Updating packages (this may take a while)...
    x The package manager threw an error
    x Last 16 lines of straight's error log:
      [Return code: 0]
      $ cd /home/winkel/.emacs.d/.local/straight/repos/emacs-buttercup/
      $ git rev-parse HEAD
      ceedad5efa797e860dbb356bc2c3028a4e0321ec
      [Return code: 0]
      $ cd /home/winkel/.emacs.d/.local/straight/repos/auctex/
      $ git rev-parse HEAD
      830e40a0639aedc6c362a3a01e160aaa8246bb99
      [Return code: 0]
      $ cd /home/winkel/.emacs.d/.local/straight/repos/latex-preview-pane/
      $ git rev-parse HEAD
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [Return code: 128]
    ! Wrote extended straight log to ~/.emacs.d/.local/logs/cli.doom.220731232310.175609.error
```

And I re-ran `doom sync -u`  before and after enabling latex in init.el and it works just fine without it, so it can't be an internet issue

**Comment by rbocheux** [comment]
Hi,

Upgrading manually solved the problem for me. I don’t know what caused the problem, but 2 days ago upgrading manually didn’t do anything.
In any case, I think this issue is solved.

**Comment by quangIO** [comment]
You may have a broken git clone. Does `ls ~/.emacs.d/.local/straight/repos/latex-preview-pane/` return an empty folder? Running the upgrade after removing `~/.emacs.d/.local/straight/repos/latex-preview-pane/` may fix the issue for you.

**Comment by winkelnp** [comment]
Just ran it again, and it seems to just work now, I have no idea what was the issue, but it is resolved now, I guess…
