### ISSUE TITLE
New org-journal entries make org-cycle stop working

### ISSUE THREAD

**Issue by danielmt** [doomemacs/doomemacs#6623]
### What did you expect to happen?

For `TAB` `(org-cycle)` to fold/unfold items after calling `SPC n j j` `(org-journal-new-entry)`.

### What actually happened?

Folding `TAB` / `M-x org-cycle` stops working after calling `SPC n j j` `(org-journal-new-entry)`

### Describe your attempts to resolve the issue

1. Tried to reset `~/.emacs.d`, didn't work.
2. Reset again, and ran `doom install` without `~/.doom.d`. Enabled `(org +journal)` and ran `doom sync` to get journal installed, same issue.

### Steps to reproduce

1. open emacs
3. write new entry to journal (`SPC n j j`) and add sub items
4. write another entry to journal (`SPC n j j`)
5. `TAB` / `M-x org-cycle` stops working

### System Information

https://pastebin.com/CzyXFaGz

**Comment by DhruvaKashyap** [comment]
Facing the same issue. I've been using Undo(```u```) after ```SPC n j j``` and then Redo(```C-r```) to unfold items. ```TAB (org-cycle)``` works after the items have been unfolded.

**Comment by rafebelmont** [comment]
I am having the same problem. And the Undo, Redo tip didn't work for me.

**Comment by tournemire** [comment]
This looks like an upstream issue : https://github.com/bastibe/org-journal/issues/392 (workaround mentioned there).

**Comment by danielmt** [comment]
Thanks @tournemire, seems like the work-around fixes it for me: `(setq org-fold-core-style 'overlays)`.
minad/consult#563 gives some context on the issue, which seems to have been caused by the org-fold merge to org-mode.
