### ISSUE TITLE
error `void-variable (doom-user-dir)` in org async export

### ISSUE THREAD

**Issue by VitalyAnkh** [doomemacs/doomemacs#6624]
### What did you expect to happen?

Type `C-c C-e l p`  to make org-mode async export to pdf.

### What actually happened?

org async export error.

Backtrace:
```
Symbol’s value as variable is void: doom-private-dir

Error: void-variable (doom-private-dir)
  debug-early-backtrace()
  debug-early(error (void-variable doom-private-dir))
  (expand-file-name "modules/" doom-private-dir)
  (list (expand-file-name "modules/" doom-private-dir) doom-modules-dir)
  (defvar doom-modules-dirs (list (expand-file-name "modules/" doom-private-dir) doom-modules-dir) "A list of module root directories. Order determines priority.")
  load-with-code-conversion("/home/vitalyr/.config/.emacs.d/lisp/doom-modules.el" "/home/vitalyr/.config/.emacs.d/lisp/doom-modules.el" nil t)
  require(doom-modules)
  load-with-code-conversion("/home/vitalyr/.emacs.d/lisp/doom-start.el" "/home/vitalyr/.emacs.d/lisp/doom-start.el" nil t)
  load("/home/vitalyr/.emacs.d/lisp/doom-start.el" nil t)
  (unwind-protect (load "/home/vitalyr/.emacs.d/lisp/doom-start.el" nil t) (delete-file load-file-name))
  load-with-code-conversion("/tmp/doom-org-async-exportDmlswH" "/tmp/doom-org-async-exportDmlswH" nil t)
  command-line-1(("-l" "/tmp/doom-org-async-exportDmlswH" "-l" "/tmp/org-export-process2yTq4t"))
  command-line()
  normal-top-level()
```

### Describe your attempts to resolve the issue

The `doom-private-dir` is `/home/vitalyr/.config/doom/` in my current emacs process. I guess when emacs does async export, it launches a new emacs process where the `doom-private-dir`'s definition isn't loaded.

### Steps to reproduce

Use org async export.

### System Information

https://pastebin.com/csqdNTdm

**Comment by sleepyeye** [comment]
Exporting to HTML also have same issue.
Exporting works correctly after turning off async mode.

**Comment by VitalyAnkh** [comment]
After [this commit](https://github.com/doomemacs/doomemacs/commit/a5c80fcb4b487b929681f1cb4fd64e5b5a2ae473), all `doom-private-dir` is the error messages become `doom-user-dir`, but the behavior is the same.

**Comment by JPYamamoto** [comment]
I'm getting the same error with `doom-user-dir` when using async export to latex file.

**Comment by pard68** [comment]
Confirmed it's happening for me as well. 

To mitigate this issue, disabling async works as @sleepyeye mentioned. To do this access the dispatch menu (`C-cC-e` or `SPC m e`) and then hit `C-a`.

**Comment by hlissner** [comment]
This occurs because I've recently changed the value of `user-init-file` to point to `doom-start`, which is not the correct entry point for bootstrapping Doom anymore. To help me confirm that theory, try inserting this into your `$DOOMDIR/config.el`:

```elisp
(defadvice! fixed-+org--fix-async-export-a (fn &rest args)
  :override #'+org--fix-async-export-a
  (let ((old-async-init-file org-export-async-init-file)
        (org-export-async-init-file (make-temp-file "doom-org-async-export")))
    (with-temp-file org-export-async-init-file
      (prin1 `(progn (setq org-export-async-debug
                           ,(or org-export-async-debug
                                debug-on-error)
                           load-path ',load-path)
                     (unwind-protect
                         (load ,(or old-async-init-file early-init-file)
                               nil t)
                       (delete-file load-file-name)))
             (current-buffer)))
    (apply fn args)))
```

**Comment by VitalyAnkh** [comment]
@hlissner Hi Henrik! After putting these code in the `config.el`, the error `void-variable (doom-user-dir)` disappears but another error `user-error ("CSL style file not found: \"acm-siggraph.csl\"") ` bumps up. Here is the backtrace: https://gist.github.com/VitalyAnkh/9d6109afb2d34b3ecce0ce8170113efb (maybe only the beginning lines are useful).

I use `org-cite` and `org-cite-csl-styles-dir` is set to `~/Zotero/styles~ where lives an `asm-siggraph.csl` file. After disabling async export this error also disappears and emacs can export org to pdf smoothly.

**Comment by hlissner** [comment]
@VitalyAnkh I've changed the snippet above. See if replacing the advice fixes your issue.

**Comment by Zilong-Li** [comment]
Hi @hlissner the new snippet works for me. Thanks.

**Comment by VitalyAnkh** [comment]
This also works for me, you are so wonderful! :heart:

**Comment by jpyamamoto** [comment]
Thank you @hlissner, the snippet is working perfectly

**Comment by dlukes** [comment]
Thank you looking into this! Unfortunately, the workaround doesn't work in my case. This is the error shown in the `*Org Export Process*` buffer:

```
Doom loaded -1 packages across 53 modules in 0.550s
Invalid read syntax: "#", 115, 12573

Error: invalid-read-syntax ("#" 115 12573)
  debug-early-backtrace()
  debug-early(error (invalid-read-syntax "#" 115 12573))
  read(#<buffer  *load*>)
  load-with-code-conversion("/tmp/org-export-process5aGJM7" "/tmp/org-export-process5aGJM7" nil t)
  command-line-1(("-l" "/tmp/doom-org-async-exportVEbtme" "-l" "/tmp/org-export-process5aGJM7"))
  command-line()
  normal-top-level()
```

`M-x doom/info`:

<details>

```
generated  Sep 09, 2022 15:33:39
system     "Fedora release 36 (Thirty Six)" Linux 5.19.6-200.fc36.x86_64 x86_64 pgtk
emacs      29.0.50 ~/.config/emacs/ -> ~/.config/emacs/
doom       3.0.0-dev HEAD -> master, origin/master, origin/HEAD c44bc81a0 2022-08-19
           11:24:34 +0200 ~/.config/doom/ -> ~/.files/emacs/doom/
shell      /usr/bin/fish
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON
           LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY
           INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF
           TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB
traits     gui server-running envvar-file custom-file
custom     warning-suppress-types safe-local-variable-values
modules    :completion (company +childframe) (vertico +icons) :ui doom doom-dashboard
           hl-todo hydra indent-guides modeline neotree ophints (popup +defaults)
           vc-gutter vi-tilde-fringe workspaces zen :editor (evil +everywhere)
           file-templates fold (format +onsave) snippets :emacs dired electric undo vc
           :term vterm :checkers syntax (spell +flyspell +everywhere) :tools biblio
           editorconfig (eval +overlay) lookup lsp magit pdf tree-sitter :lang (cc
           +lsp) data elm emacs-lisp (haskell +lsp) json javascript latex lua markdown
           (org +dragndrop +jupyter +present +roam2) python rst (rust +lsp) (sh +lsp
           +fish) web yaml :config (default +bindings +smartparens)
packages   (org-roam-ui) (ox-odt :recipe (:host github :repo
           kjambunathan/org-mode-ox-odt :nonrecursive t :files (lisp/ox-odt.el etc
           docs contrib/odt/LibreOffice))) (org-fancy-priorities :disable t)
```

</details>

**Comment by hlissner** [comment]
As of 551f0ca this should be resolved. Let me know if that isn't the case and I'll reopen it.

**Comment by dlukes** [comment]
Thank you very much! Async export works for me now :tada:

(Opening the generated file after export doesn't work in combination with async, but I think that's expected. At least AFAICS, `emacs -q` behaves the same in this respect. I think you're just supposed to open the export stack and open the generated file manually.)

**Comment by ronisbr** [comment]
I am getting this error:

```
Symbol’s value as variable is void: doom-version

Error: void-variable (doom-version)
  debug-early-backtrace()
  debug-early(error (void-variable doom-version))
  (equal doom-version "3.0.0-pre")
  (if (equal doom-version "3.0.0-pre") nil (error "The installed version of Doom (%s) has changed (to %s) since last 'doom sync'. Run 'doom sync' to bring Doom up to speed" "3.0.0-pre" doom-version))
  load-with-code-conversion("/Users/ronan.arraes/.emacs.d/.local/etc/@/init.29.el" "/Users/ronan.arraes/.emacs.d/.local/etc/@/init.29.el" nil t)
  command-line-1(("-l" "/Users/ronan.arraes/.emacs.d/.local/etc/@/init.29.el" "-l" "/var/folders/w1/n224xlws14s3v7n09gmj7m180000gn/T/org-export-processm5cGO7"))
  command-line()
  normal-top-level()
```

when trying to export to a buffer in async mode. Exporting to a file in async mode works fine. Is it possible this problem is related to the current issue?

**Comment by maikol-solis** [comment]
@hlissner I have the same issue, and I'm in the latest commit using 28.2. I reported some debug info  here https://github.com/nobiot/org-transclusion/issues/137
