### ISSUE TITLE
conda-env-activate breaks with conda=4.13 (4.12 works)

### ISSUE THREAD

**Issue by zepedaj** [doomemacs/doomemacs#6626]
### What did you expect to happen?

An Python conda environment should be activated, and its name indicated in the modeline.

### What actually happened?

When running 
    alt+x, conda-env-activate, base
the following error message appears

conda--get-path-prefix: Error: executing command "<home>/anaconda3/bin/conda ..activate "bash" "<home>/anaconda3/"" produced error code 2

Here is the backtrace:

 Debugger entered--Lisp error: (error "Error: executing command \"<home>/anaconda3...")
   signal(error ("Error: executing command \"<home>/anaconda3..."))
   error("Error: executing command \"<home>/anaconda3...")
   conda--get-path-prefix("<home>/anaconda3/")
   conda-env-activate-path("<home>/anaconda3/")
   conda-env-activate()
   funcall-interactively(conda-env-activate)
   call-interactively(conda-env-activate record nil)
   command-execute(conda-env-activate record)
   execute-extended-command(nil "conda-env-activate" #("conda-env-act" 11 13 (ws-butler-chg chg)))
   funcall-interactively(execute-extended-command nil "conda-env-activate" #("conda-env-act" 11 13 (ws-butler-chg chg)))
   call-interactively(execute-extended-command nil nil)
   command-execute(execute-extended-command)

### Describe your attempts to resolve the issue

Changing the conda version to conda=4.12 appears to fix it. The latest conda=4.13, however produces the error.

This installer includes conda=4.12:
    [Anaconda3-2020.11-Linux-x86_64.sh](https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh)
Upgrading from this installer using 
    `conda update -n base -c defaults conda`
breaks things again.

This installer includes conda=4.13 out-of-the-box:
    [Anaconda3-2022.05-Linux-x86_64.sh](https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh)

### Steps to reproduce

1. Install doom and upgrade.
2. Install the latest Anaconda (with conda=4.13) with all the defaults.
3. Open emacs with doom
4. alt+x, conda-env-activate, base

### System Information

https://pastebin.com/GNB1yWDx

**Comment by sleepyeye** [comment]
I guess conda 4.13>= causes the issue.
Luckily the recent conda.el fixed the issue and I shoot the PR but it would takes some time to be merged.
So.... if just want to fix it right now, try this

```emacs-lisp
;; $DOOMDIR/pacakges.el
(unpin! conda)
```

This works for my Ubuntu 20.04 PC and MacOS 13 M1 Macbook.
I couldn't test it with Windows PC.

**Comment by zepedaj** [comment]
Tried it on Windows (and Ubuntu 20.04), seems to work as well. Thanks!

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
