### ISSUE TITLE
Getting started (https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org) 404s

### ISSUE THREAD

**Issue by maxwedwards** [doomemacs/doomemacs#6631]
### What did you expect to happen?

document to be there

### What actually happened?

document wasn't there

### Describe your attempts to resolve the issue

clicked on the link in the readme

### Steps to reproduce

click on getting started in the readme

### System Information

no pastebin

**Comment by hlissner** [comment]
I am aware and am currently in the process of swapping out the docs. For the time being, you'll find them in https://github.com/doomemacs/doomemacs/blob/develop/docs/.
