### ISSUE TITLE
org-persist throwing `file-missing` error when killing an `org-mode` buffer

### ISSUE THREAD

**Issue by Jorghy-Del** [doomemacs/doomemacs#6635]
### What did you expect to happen?

Well I did not expect this warning to show up. But it keeps coming up now and then

There is a warning that shows up in the minibuffer like so -
`(file-missing Creating directory No such file or directory /home/ari/.config/emacs/.local/cache/org/persist/). Deleting bad index entry.`

Well, the correct location should be `/home/ari/.config/emacs/.local/cache/org-persist` i presume. 

### What actually happened?

Explained above

### Steps to reproduce

It comes up by itself when i kill any buffer with `SPC b k`

### System Information

https://pastebin.com/cTqvYdqt

**Comment by hlissner** [comment]
As of a71e575 this should be resolved, though it should be eventually resolved upstream -- I'll do this when I get around to it. 

Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!

**Comment by Jorghy-Del** [comment]
Yes, resolved.
