### ISSUE TITLE
Emacs crashes after repeating "kill buffer command" 

### ISSUE THREAD

**Issue by hvsouza** [doomemacs/doomemacs#6648]
### What did you expect to happen?

After killing buffers using "evil-repeat" for "kill-current-buffer" emacs will crash

### What actually happened?

Emacs will crash after closing the last buffer and transit to dired: 

![image](https://user-images.githubusercontent.com/62480697/183428906-94773fdf-02ac-409c-bc30-b623ea20e924.png)

### Steps to reproduce

This is the way that never fails to reproduce for me: 

1. Open emacs
2. Open init.el and config.el 
3. Open "dired" in any path using `SPC .` 
4. `SPC b b` change to init.el file
5. `SPC b b` change to config.el file
6. `SPC b k` kill config.el file
7. `.` to repeat the command. 

After doing so, init.el will be killed but emacs will freeze. 

### System Information

https://pastebin.com/KekgNm5X

**Comment by Jdogzz** [comment]
@hvsouza Are you still able to reproduce this? I tried following your steps and did not experience any freezing.

https://pastebin.com/Y8xMBwFq

**Comment by hvsouza** [comment]
@Jdogzz, in fact I didn't have the problem in the past months I believe, thanks. I will close the issue
