### ISSUE TITLE
+vterm/toggle creates duplicate buffers if you set vterm-buffer-name-string to "%s"

### ISSUE THREAD

**Issue by indigoviolet** [doomemacs/doomemacs#6651]
### What did you expect to happen?

`+vterm/toggle` should not create new buffers each time, but instead toggle an existing buffer.

https://github.com/akermu/emacs-libvterm#vterm-buffer-name-string

Since `+vterm/toggle` looks for the buffer by name, setting `vterm-buffer-name-string` to `"%s"` will break its ability to toggle the buffer. Instead it creates a new buffer each time.

### What actually happened?

If I set `vterm-buffer-name-string` to contain `%s`, the buffer name is affected by the shell directory. This causes `+vterm/toggle` to incorrectly create a new buffer each time.

### Steps to reproduce

1. Set vterm-buffer-name-string to `"%s"`
2. Use `+vterm/toggle` and notice new buffers each time.

### System Information

https://pastebin.com/jsNfW0uk

**Comment by indigoviolet** [comment]
The appropriate solution is probably to create buffer local variables to guide the search for the cognate buffer

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by schemar** [comment]
The issue persists for me. The name of the vterm buffer changes while I use it. It is updated to reflect the current working directory. The current "workaround" is to not rename the buffer while using vterm.

`config.el`: `setq vterm-buffer-name-string "vterm %s"`
`.zshrc`:
```sh
# Hook to rename the vterm buffer
add-zsh-hook -Uz chpwd (){ print -Pn "\e]2;%m:%2~\a" }
```

Full `.zshrc` relating to Emacs: https://pastebin.com/ixVYAk54
System information: https://pastebin.com/j9SjmPAa

Thank you for all your work, Henrik :pray:

**Comment by schemar** [comment]
How could I configure Emacs in a way where I only change the buffer name if it _isn't_ the pop-up? Would I advise the function that renames the vterm buffer and only rename it if the current name wasn't the name of the vterm pop-up?

**Comment by mogorman** [comment]
I was able to work around this issue by doing this 
```
(defun mog/vterm--set-title (title)
            (message "called")
  "Use TITLE to set the buffer name according to `vterm-buffer-name-string'."
  (if (string-equal (buffer-name) "*doom:vterm-popup:main*")
          (message "not renaming")
    (when vterm-buffer-name-string
    (rename-buffer (format vterm-buffer-name-string title) t))
        )

                             )
(advice-add 'vterm--set-title :override #'mog/vterm--set-title)
```
