### ISSUE TITLE
`Symbol’s function definition is void: diff-hl-magit-post-refresh` error

### ISSUE THREAD

**Issue by gjm** [doomemacs/doomemacs#6654]
### What did you expect to happen?

Expect to use magit without errors.

### What actually happened?

Opening magit status or doing some magit operations I get these errors:
```
error in process sentinel: run-hooks: Symbol’s function definition is void: diff-hl-magit-post-refresh
error in process sentinel: Symbol’s function definition is void: diff-hl-magit-post-refresh
```

### Steps to reproduce

1. Open emacs
2. Open magit-status
3. Fetch from remote

### System Information

https://pastebin.com/cgkfqtda

**Comment by Typas** [comment]
A temporary solution is to modify the `init.el`, from `vc-gutter` to `(vc-gutter +diff-hl)`.
Nothing has been installed or updated after I run `doom sync`, it's weird since there's always some package installed after adding flag on a module.

**Comment by hlissner** [comment]
As of 24623f9959cbb548826602d9b0bccc35cd2ba2d3, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by cxb811201** [comment]
@hlissner Tested and can be started properly with `emacs --daemon`, thanks
