### ISSUE TITLE
Package "ado-mode" does not load when installed from packages.el

### ISSUE THREAD

**Issue by marcklemp** [doomemacs/doomemacs#6655]
### What did you expect to happen?

Adding `(package! ado-mode)` to `~/.doom.d/packages.el` and executing `~/.emacs.d/bin/doom sync` should enable the use of `ado-mode` in Doom Emacs.

### What actually happened?

The `doom sync` terminal command reported that the package was installed. However, after restarting Doom Emacs with `M-x doom/restart` in Emacs, no `ado-mode`-related commands can be found in Emacs using `M-x`.

### Describe your attempts to resolve the issue

I successfully enabled the package by loading it manually (i.e., downloading and `require`'ing the code in Emacs).

### Steps to reproduce

1. Install Doom Emacs.
2. Add `(package! ado-mode)` to `~/.doom.d/packages.el` and execute `~/.emacs.d/bin/doom sync`.
3. Restart Emacs and type `M-x ado-mode`.
4. Observe a lack of matches.

### System Information

https://pastebin.com/qXqWe1nX

**Comment by elken** [comment]
All you did was tell emacs to download the package, not load it.

Try adding `(use-package! ado-mode)` to your `init.el` and `doom sync`

**Comment by hlissner** [comment]
- `package!` dictates how and where packages are installed. Not how they are loaded.
- Most packages autoload their key entry points (common commands, major/minor modes, etc). This means that, when you call those commands, modes, functions, etc. Emacs will automatically load their package. However, assuming https://github.com/louabill/ado-mode is the ado-mode you're talking about, it has no autoloads whatsoever.
- In the absence of proper autoloads, it comes down to you to either define some yourself, or simply load the package immediately. As `(use-package! ado-mode)` or `(require 'ado-mode)` would accomplish. Alternatively, you can be more selective about when it loads. For example: to use `ado-mode` for any file with an *.ado extension:

```elisp
;; tell Emacs the `ado-mode' major mode belongs to the "ado-mode" package.
(autoload 'ado-mode "ado-mode" nil t)
;; then tell Emacs to associate *.ado files with the `ado-mode` major mode
(add-to-list 'auto-mode-alist '("\\.ado\\'" . ado-mode))
```

This can be expressed more succinctly with `use-package!`:

```elisp
(use-package! ado-mode
  :mode "\\.ado\\'")
```

-----

As this is not a Doom issue I will close it, but feel free to follow up here.
