### ISSUE TITLE
Attempt to set a constant symbol: t

### ISSUE THREAD

**Issue by whxcode** [doomemacs/doomemacs#6656]
### What did you expect to happen?

I occasionally have problems during actual use
1. When I execute the shortcut key SPC g g, I expect to open the magit window
2. When I execute the shortcut key SPC p ., switch the project

### What actually happened?

Executing this shortcut command will prompt me: After 'Attempt to set a constant symbol: t', the magit window is not opened or the project is switched successfully.

![image](https://user-images.githubusercontent.com/44012914/183847597-defec5cf-d200-4fc5-940f-37a464c541f1.png)

### Steps to reproduce

I can't stabilize

### System Information

https://pastebin.com/iqSbucHD

**Comment by whxcode** [comment]
Sorry, the first picture copy is wrong, I added another one.
![image](https://user-images.githubusercontent.com/44012914/183850632-328d6b48-23a4-425f-b28e-485d01723086.png)

**Comment by hlissner** [comment]
I can't reproduce this, so I'm inclined to suspect your personal configuration. Somewhere, something is trying to set `t`. E.g. `(setq t ...)`, which is illegal.

Please try to create [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error. Failing that, once you've double checked your private config, [try bisecting your config](https://discourse.doomemacs.org/t/how-to-debug-issues/55) and investigating [\*Messages\* for any adjacent warnings/errors](https://discourse.doomemacs.org/t/how-to-debug-issues/55). Also look for a `$DOOMDIR/custom.el`, if it exists; perhaps `t` is getting set in there.

**Comment by whxcode** [comment]
> I can't reproduce this, so I'm inclined to suspect your personal configuration. Somewhere, something is trying to set `t`. E.g. `(setq t ...)`, which is illegal.
> 
> Please try to create [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error. Failing that, once you've double checked your private config, [try bisecting your config](https://discourse.doomemacs.org/t/how-to-debug-issues/55) and investigating [*Messages* for any adjacent warnings/errors](https://discourse.doomemacs.org/t/how-to-debug-issues/55). Also look for a `$DOOMDIR/custom.el`, if it exists; perhaps `t` is getting set in there.

Then I'll check it out tomorrow, thanks.

**Comment by whxcode** [comment]
> I can't reproduce this, so I'm inclined to suspect your personal configuration. Somewhere, something is trying to set `t`. E.g. `(setq t ...)`, which is illegal.
> 
> Please try to create [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error. Failing that, once you've double checked your private config, [try bisecting your config](https://discourse.doomemacs.org/t/how-to-debug-issues/55) and investigating [*Messages* for any adjacent warnings/errors](https://discourse.doomemacs.org/t/how-to-debug-issues/55). Also look for a `$DOOMDIR/custom.el`, if it exists; perhaps `t` is getting set in there.

I have deleted the custom.el file but still get the error.
Here is some log information.
![image](https://user-images.githubusercontent.com/44012914/184049639-dff87c34-a2ff-4eb5-816b-88619e9df41b.png)

**Comment by whxcode** [comment]
> I can't reproduce this, so I'm inclined to suspect your personal configuration. Somewhere, something is trying to set `t`. E.g. `(setq t ...)`, which is illegal.
> 
> Please try to create [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error. Failing that, once you've double checked your private config, [try bisecting your config](https://discourse.doomemacs.org/t/how-to-debug-issues/55) and investigating [*Messages* for any adjacent warnings/errors](https://discourse.doomemacs.org/t/how-to-debug-issues/55). Also look for a `$DOOMDIR/custom.el`, if it exists; perhaps `t` is getting set in there.

Sorry, there is an extra .dir-locals.el file in my project, which makes it impossible to switch projects. Now I delete it and it can be used normally. Thank you for your reply.
