### ISSUE TITLE
In use-package!, lexical binding only works when evaluated in org-mode code blocks

### ISSUE THREAD

**Issue by ning-y** [doomemacs/doomemacs#6670]
### What did you expect to happen?

In my literate config, I define a higher-order function which returns functions that can be bound to keymaps.

```lisp
#+begin_src emacs-lisp
;;; -*- lexical-binding: t -*-
#+end_src

#+begin_src emacs-lisp
(use-package! org-roam
  :config
  (defun ning/org-roam-file-find-given-filetag (tag)
    (org-roam-node-find nil nil
                        '(lambda (node)
                           (and
                            (eq (org-roam-node-level node) 0)
                            (cl-member tag (org-roam-node-tags node) :test #'string=)))))
  (defun ning/org-roam-review-find ()
    (interactive) (ning/org-roam-file-find-given-filetag "review"))
  (defun ning/org-roam-task-find ()
    (interactive) (ning/org-roam-file-find-given-filetag "task"))
  (defun ning/org-roam-file-find ()
    (interactive) (ning/org-roam-file-find-given-filetag nil))
  (map! :leader
        :prefix "r"
        ; Finder functions
        :desc "org-roam-review-find" "r" #'ning/org-roam-review-find
        :desc "org-roam-task-find" "t" #'ning/org-roam-task-find
        :desc "org-roam-file-find" "f" #'ning/org-roam-file-find))
#+end_src
```

I transpile this to a config.el file via `doom sync`, and then restart emacs. In this new fresh session of emacs, I expect all of the defined `ning/org-roam-*-find` functions to work well, e.g. `ning/org-roam-review-find` opens a completion buffer thing which only completes top-level roam nodes with "review" as a file tag.

### What actually happened?

In the new fresh session of emacs, any of the defined `ning/org-roam-*-find` functions raise an error related to the lexical binding of the `tag` variable:

```
Symbol’s value as variable is void: tag
```

### Describe your attempts to resolve the issue

*What doesn't work*

- Using `load-file` on config.el
- Running `C-x C-e` (`eros-eval-last-sexp`) on the entire `(use-package! org-roam ...)` call in `config.el`
- Running `C-x C-e` on the `(defun ning/org-roam-review-find () ...)` statement in `config.el`

*What works (!)*

- Running `C-c C-c` (`org-ctrl-c-ctrl-c`) to evaluate the code block containing the entire `(use-package! org-roam ...)` call in `config.org` (the code block contains nothing else)
- Running `C-x C-e` (`eros-eval-last-sexp`) on the `(defun ning/org-roam-review-find () ...)` statement in `config.org`

I am sure that the config.org and config.el files are equivalent and updated: I have run `doom sync` many times and I have checked that the contents of config.el correspond to those of config.org.

### Steps to reproduce

1. Set up a literate config.org
2. Enable the module with org-roam
3. Add the quoted use-package set-up above for org-roam
4. Run `doom sync`
5. Restart emacs
6. Try using any of the `ning/org-roam-*-find` functions

### System Information

https://pastebin.com/C5qt2uiD

**Comment by ning-y** [comment]
Avoiding the HOF also fixes this (because it avoids the `tag` variable), but I would like to have the HOF for a cleaner program.

```lisp
(use-package! org-roam
  :config
  (defun ning/org-roam-review-find ()
    (interactive)
    (org-roam-node-find nil nil
                        '(lambda (node)
                           (and
                            (eq (org-roam-node-level node) 0)
                            (cl-member "review" (org-roam-node-tags node) :test #'string=)))))
  (defun ning/org-roam-task-find ()
    (interactive)
    (org-roam-node-find nil nil
                        '(lambda (node)
                           (and
                            (eq (org-roam-node-level node) 0)
                            (cl-member "task" (org-roam-node-tags node) :test #'string=)))))
  (defun ning/org-roam-file-find ()
    (interactive)
    (org-roam-node-find nil nil '(lambda (node) (eq (org-roam-node-level node) 0))))
  (map! :leader
        :prefix "r"
        ; Finder functions
        :desc "org-roam-review-find" "r" #'ning/org-roam-review-find
        :desc "org-roam-task-find" "t" #'ning/org-roam-task-find
        :desc "org-roam-file-find" "f" #'ning/org-roam-file-find))
```

**Comment by gagbo** [comment]
Why are you quoting the `lambda` in your HOF ?
```lisp
(defun ning/org-roam-file-find-given-filetag (tag)
    (org-roam-node-find nil nil
                        '(lambda (node)                                                   ; The quote here
                           (and
                            (eq (org-roam-node-level node) 0)
                            (cl-member tag (org-roam-node-tags node) :test #'string=)))))
 ```
 
 `tag` will never get evaluated in the `lambda` since it's just a list of symbols and nothing else. The fact that it even _can_ work is surprising to me, but maybe `org-roam-node-find` does magic behind your back that I don't get. Maybe it's a macro with specific evaluation rules that you need to look for.

**Comment by hlissner** [comment]
As gagbo said, this is a quoting issue. Unquote the `lambda` and it will capture the lexical environment (and `tag` along with it). Since this isn't a Doom bug I will close this.

**Comment by ning-y** [comment]
@gagbo Thank you for the help, as you said unquoting the lambda fixed the issue. I haven't made the time to really learn (e)lisp, but your explanation makes it clear how quoting the lambda is not a good idea.

@hlissner So sorry for crowding the bug reports with amateur stuff, and thanks for maintaining doom emacs!
