### ISSUE TITLE
forge degrade after running upgrade

### ISSUE THREAD

**Issue by nozomirin** [doomemacs/doomemacs#6679]
### What did you expect to happen?

The forge package should not degrade.

### What actually happened?

After I run doom upgrade, I can't open my project and an error showed in minibuffer.
forge-db: The Forge database was created with a newer Forge version. You need to update the Forge package.
I compared the upgrade output and forge commitment, it actually degraded.
(109/295) forge: 9556d3b -> 36208c4 
up-to-date -> Commits on Jun 17, 2022
https://github.com/magit/forge/commits/master 

### Steps to reproduce

1. install doom emacs
2. modify init.el (magit +forge)
3. run doom sync
4. open any project (and forge database will init)
5. run doom upgrade
6. reload and open the project

### System Information

https://pastebin.com/67243VvB

**Comment by hlissner** [comment]
Run `M-x forge-reset-database`.
