### ISSUE TITLE
lispyville shouldn't require Ivy

### ISSUE THREAD

**Issue by alienbogart** [doomemacs/doomemacs#6681]
### Describe your request

When `ivy`module is not enabled, other packages shouldn't require Ivy.

### Briefly explain its use-case

Enabling the `lispy` module requires the `ivy` package. This is redundant since I already have the `vertico` module enabled. `lispy` shouldn't require `ivy`.

Adding this to `packages.el` doesn't seem to have any effect:

```
(package! ivy :disable t)
(package! swiper :disable t)
```

**Comment by iyefrat** [comment]
This is because `lispy` depends on `swiper` (which depends on `ivy`). Not much we can do about that here.
