### ISSUE TITLE
`+default/search-project` missing dependency when not using ivy, helm, or vertico

### ISSUE THREAD

**Issue by leppert** [doomemacs/doomemacs#6682]
### What did you expect to happen?

Doom should install the Projectile dependencies ([link](https://github.com/bbatsov/projectile/blame/d31860b7d37cf6a3e735062a2618c6b9f514a309/doc/modules/ROOT/pages/usage.adoc#L57)) ripgrep.el or rg.el so that `+default/search-project` is able to return search results using `projectile-ripgrep` when the user has selected a search package other than ivy, helm, or vertico (ex: ido).

### What actually happened?

An error is displayed reading "Packages ‘ripgrep’ and ‘rg’ are not available". This error originates from Projectile ([line](https://github.com/doomemacs/doomemacs/blob/e0385052a8004ec54a402c27357b1352840eb798/modules/config/default/autoload/search.el#L88)) which is called from the `+default/search-project` function ([line](https://github.com/doomemacs/doomemacs/blob/e0385052a8004ec54a402c27357b1352840eb798/modules/config/default/autoload/search.el#L88)) as a fallback when something other than ivy, helm, or vertico are used.

Here is the backtrace:

```
Debugger entered--Lisp error: (error "Packages ‘ripgrep’ and ‘rg’ are not available")
  apply(debug (error (error "Packages ‘ripgrep’ and ‘rg’ are not available")))
  (let ((backtrace (doom-backtrace))) (setq num-nonmacro-input-events (1+ num-nonmacro-input-events)) (apply #'debug args))
  doom-debugger(error (error "Packages ‘ripgrep’ and ‘rg’ are not available"))
  error("Packages `ripgrep' and `rg' are not available")
  projectile-ripgrep("testing" nil)
  #<subr funcall-interactively>(projectile-ripgrep "testing" nil)
  apply(#<subr funcall-interactively> (projectile-ripgrep "testing" nil))
  funcall-interactively(projectile-ripgrep "testing" nil)
  #<subr call-interactively>(projectile-ripgrep)
  apply(#<subr call-interactively> projectile-ripgrep nil)
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> projectile-ripgrep)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> projectile-ripgrep)
  #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command)(projectile-ripgrep)
  apply(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) projectile-ripgrep)
  explain-pause--wrap-call-interactively(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) projectile-ripgrep)
  apply(explain-pause--wrap-call-interactively #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) projectile-ripgrep)
  call-interactively(projectile-ripgrep)
  (let* ((projectile-project-root nil) (disabled-command-function nil) (current-prefix-arg (if (eq arg 'other) nil arg)) (default-directory (if (eq arg 'other) (let* ((projects (and t ...))) (if projects (completing-read "Search project: " projects nil t) (user-error "There are no known projects"))) default-directory))) (call-interactively (cond (nil #'+ivy/project-search) (nil #'+helm/project-search) (nil #'+vertico/project-search) (#'projectile-ripgrep))))
  +default/search-project(nil)
  #<subr funcall-interactively>(+default/search-project nil)
  apply(#<subr funcall-interactively> (+default/search-project nil))
  funcall-interactively(+default/search-project nil)
  #<subr call-interactively>(+default/search-project nil nil)
  apply(#<subr call-interactively> +default/search-project (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> +default/search-project nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (+default/search-project nil nil))
  #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command)(+default/search-project nil nil)
  apply(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) (+default/search-project nil nil))
  explain-pause--wrap-call-interactively(#f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) +default/search-project nil nil)
  apply(explain-pause--wrap-call-interactively #f(advice-wrapper :around #<subr call-interactively> call-interactively@ido-cr+-record-current-command) (+default/search-project nil nil))
  call-interactively(+default/search-project nil nil)
  command-execute(+default/search-project)
```

### Describe your attempts to resolve the issue

I added `(package! ripgrep)` to my .doom.d/packages.el file and the error resolves, but since this is a dependency for built-in module functionality, I imagine it would be better for Doom to install this seamlessly.

### Steps to reproduce

1. Boot up a fresh install of Doom
2. In `.doom.d/init.el`, comment out `vertico` and uncomment `ido`.
3. Run `M-x +default/search-project`

### System Information

https://pastebin.com/rDJFY4bs

**Comment by hlissner** [comment]
I plan to drop projectile in the near future (in favor of project.el), so I don't intend to extend support for its capabilities (much of which is made redundant by the helm, ivy, and vertico modules). That said, our ido module is certainly lagging far behind in functionality compared to the others. As I don't dogfood the module, I'd happily welcome a PR to bring it up to speed.

That, or consider using [deadgrep](https://github.com/Wilfred/deadgrep), which I am considering for Doom, to compliment the live-search features of our other completion modules.

Anyhow, sorry for the trouble, but thanks for bringing it to my attention!
