### ISSUE TITLE
Update `org-mode`

### ISSUE THREAD

**Issue by akoptelov** [doomemacs/doomemacs#6691]
### What package(s) should be bumped?

org-mode

### Why should Doom bump these packages early?

Org-mode has an issue with `org-encode-time` described here:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=56746

In a nutshell, Emacs reports `invalid function 'org-encode-time'` when trying to update dynamic time table.

The issue is fixed in this commit: 
https://github.com/emacs-straight/org-mode/commit/d3a9c424ba32382fff1da4f4ecb447dc99205261

**Comment by Schievel1** [comment]
Just a qick reminder for new (to doom) people: If you need that new version of org-mode now and can't wait for Doom to include it in an upgrade, put `(unpin! org-mode` (if you always want to have the newest version of org-mode that is available on its github) or `(package! org-mode :pin "0432f4f")` (if you want this specific commit) into `packages.el`. Then do `doom upgrade` in the terminal.

**Comment by akoptelov** [comment]
> 



> Just a qick reminder for new (to doom) people: If you need that new version of org-mode now and can't wait for Doom to include it in an upgrade, put `(unpin! org-mode` (if you always want to have the newest version of org-mode that is available on its github) or `(package! org-mode :pin "0432f4f")` (if you want this specific commit) into `packages.el`. Then do `doom upgrade` in the terminal.

BTW, currently this does not work with `org-mode`. The full recipe should be used for non-pinned version: https://github.com/doomemacs/doomemacs/issues/6491#issuecomment-1210721419

**Comment by Schievel1** [comment]
> > 
> 
> > Just a qick reminder for new (to doom) people: If you need that new version of org-mode now and can't wait for Doom to include it in an upgrade, put `(unpin! org-mode` (if you always want to have the newest version of org-mode that is available on its github) or `(package! org-mode :pin "0432f4f")` (if you want this specific commit) into `packages.el`. Then do `doom upgrade` in the terminal.
> 
> BTW, currently this does not work with `org-mode`. The full recipe should be used for non-pinned version: [#6491 (comment)](https://github.com/doomemacs/doomemacs/issues/6491#issuecomment-1210721419)

Thats weird, when I did the `doom upgrade` it downloaded the commit 0432f4f like it should.

**Comment by hlissner** [comment]
I've bumped `:lang org` (and `org`, by extension) in e2ce434, so I'll consider this issue resolved. Thanks for bringing it to my attention!
