### ISSUE TITLE
Python auto-completion issues

### ISSUE THREAD

**Issue by silverbladeg** [doomemacs/doomemacs#6693]
### What did you expect to happen?

Get relevant auto-completion in python files. Have not looked into/tested other languages.

### What actually happened?

Python auto-complete provides inconsistent and often irrelevant auto-completion options / nothing that's related/inherited from the variable.

There are two aspects to this:
1) Inconsistent: As you can see from my reproduced example below, I do get correct auto-completes but then it goes on to fail to provide relevant ones in the immediate next step.

2) Irrelevant: It's usually the same irrelevant options, i think from yas based the company-diag output but i'm very new to emacs so hard for me to tell.

It might help to also note that for some reason I haven't had this issue while importing various classes I have written but quite often when importing a variable or assigning a variable to a new class in a script. 

Below is an example that showcases an instance in which, with the same quite common/popular module, I can get the correct auto-complete and then it fails to provide relevant auto-complete in the immediate next step.

The first image is from doom emacs, the second is from VSCODE (VSC was the only other editor I could quickly check the auto complete against this and VSC does provide the expected auto-complete options).

Doom Emacs python auto-complete(including the output from company-diag):

![doom_emacs_python_codecompletion](https://user-images.githubusercontent.com/1237697/185440105-92ce75fa-d6f7-47a3-a5d8-19a85e67c1a1.png)

VSCODE auto-complete:

![image](https://user-images.githubusercontent.com/1237697/185442709-b05e6958-e71f-49dc-a2fc-a71b6eea6f9e.png)

### Describe your attempts to resolve the issue

I have attempted various combinations of company backends, tried different lsp server instead of pyright, tried anaconda, tried with company-jedi, with elpy, and i'm sure a few others that I can't recall anymore. In all instances I have either received "None" for the autocomplete or irrelevant options for the autocomplete on the exact same script described below.

### Steps to reproduce

1) pip3 install pandas_datareader pyright (in case you don't have them already)

2) open an install of doom emacs (I have tried with clean installs inside various docker containers as well - no difference) and have at least the following enabled in init.el: company, lsp and (python+lsp+pyright)

3) Code:

import pandas_datareader as pdr

test = pdr.get_data_yahoo("SPY") 
##(note the auto-complete in this step works just fine)
test.
##attempt to get auto-complete on "test" variable gives random options not associated with the object that's produced by the prior line of code. 

### System Information

https://pastebin.com/5MxLaEcm

**Comment by samhedin** [comment]
I have had this issue as well, but after trying out https://discourse.doomemacs.org/t/new-completion-corfu-module/2685 the suggestions got a lot better.

**Comment by silverbladeg** [comment]
> I have had this issue as well, but after trying out https://discourse.doomemacs.org/t/new-completion-corfu-module/2685 the suggestions got a lot better.

thanks, trying it out now.

**Comment by silverbladeg** [comment]
@samhedin switching to corfu helped significantly on the completion, thanks for the tip. @hlissner would be great to add corfu module as a completion option in the default configs like company, it has been a significant improvement and it seems ( see link above for more details). I will close the issue.
