### ISSUE TITLE
Error: "Symbol's value as variable is void: use-package-font-lock-keywords" in a fresh install of doom emacs

### ISSUE THREAD

**Issue by ronisbr** [doomemacs/doomemacs#6699]
### What did you expect to happen?

I installed doom emacs in a Mac using emacs-plus.

### What actually happened?

When I open emacs after `doom instal`, I get the message:

```
Warning (initialization): An error occurred while loading ‘/Users/ronisbr/.emacs.d/lisp/doom-start.el’:

Symbol's value as variable is void: use-package-font-lock-keywords

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

### Describe your attempts to resolve the issue

I deleted `~/.doom.d` and `~/.emacs.d` and tried a fresh install.

### Steps to reproduce

1. Install doom emacs as indicated in the documentation.
2. Open emacs.

### System Information

https://pastebin.com/41XDtBqh

**Comment by ronisbr** [comment]
Maybe it is related to this commit:

https://github.com/jwiegley/use-package/commit/8a3d29e433d97cfa5612e7bc686ce7c0d24b8f47

**Comment by jwiegley** [comment]
Ok, until we're sure I've reverted the PR change.

**Comment by belak** [comment]
It's looking like doom directly references `use-package-font-lock-keywords` to remove the face, so when it was dropped from use-package, doom broke.

**Comment by aikrahguzar** [comment]
> Maybe it is related to this commit:
> 
> [jwiegley/use-package@8a3d29e](https://github.com/jwiegley/use-package/commit/8a3d29e433d97cfa5612e7bc686ce7c0d24b8f47)

Seems strange, `use-package` is pinned to a commit from June. Did you unpin it in your private config?

**Comment by hlissner** [comment]
I'm aware of the upstream change and will adapt Doom when I next bump Doom's core packages.

That said, I cannot reproduce this behavior on a fresh install of Doom, and the latest commit of Doom has use-package pinned to https://github.com/jwiegley/use-package/commit/0ad5d9d5d8a61517a207ab04bf69e71c081149eb, which predates the change by roughly two months. I also don't see any extra config in your `M-x doom/info` suggesting that you're unpinning the package. Are you, perhaps, installing `use-package` through external means? Maybe by adding a local clone to your `load-path`, or through your system package manager (so it lives in your site-files)?

**Comment by ronisbr** [comment]
Thanks @hlissner for the fast answer!

Something is strange, it seems the pin is not respected for use-package. A `git log` inside `~/.emacs.d/.local/straight/repos/use-package` show:

```
commit 8a3d29e433d97cfa5612e7bc686ce7c0d24b8f47 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: John Wiegley <johnw@newartisans.com>
Date:   Thu Aug 18 17:27:55 2022 -0700

    Merge pull request #859 from belak/remove-extra-font-lock-keywords
(END)
```

Removing and syncing doom again leads to the same scenario.

Do you have any ideia why this is happening?

**Comment by ronisbr** [comment]
New information! If I do `doom upgrade`, then `use-package` is pinned to the right version:

```
commit 0ad5d9d5d8a61517a207ab04bf69e71c081149eb (HEAD -> master)
Author: John Wiegley <johnw@newartisans.com>
Date:   Sat Jun 25 12:37:19 2022 -0700

    Add further notes to the README

commit a7422fb8ab1baee19adb2717b5b47b9c3812a84c
Merge: e6b4bf8 560ea32
Author: John Wiegley <johnw@newartisans.com>
Date:   Wed Feb 10 08:09:23 2021 -0800

    Merge pull request #910 from minad/improved-unbind

commit 560ea32eaf1e16ac5d673496e5d52d63dfeec23a
Author: Daniel Mendler <mail@daniel-mendler.de>
Date:   Wed Feb 10 14:13:36 2021 +0100

    unbind-key: Ensure that keys are removed from the keymap

    * The removal from the keymap is performed by bind-key--remove
    * Use the same argument normalization as bind-key
...
```

However, that directory is now a full clone.

**Comment by hlissner** [comment]
@ronisbr That is odd. I think it may be a bug in our bootstrapper (straight.el and use-package get special treatment). I'll look into that separately.

In the meantime, I've removed the problematic block in 995b403 and bumped use-package in 2b07fd1dd834c88a679dbbe9ff56062782140422, so the original issue should now be resolved. Let me know if that isn't the case and I'll reopen it.
