### ISSUE TITLE
docs/getting_started.org is not in master branch

### ISSUE THREAD

**Issue by JohnAtl** [doomemacs/doomemacs#6702]
### What did you expect to happen?

When I click any of the links under Getting Started in index.org, expected Getting Started to open.

### What actually happened?

Getting Started did not open.

### Describe your attempts to resolve the issue

Copied docs/getting_started.org from the develop branch.

### Steps to reproduce

1. Open emacs
2. SPC h d h to open docs
3. Click on Getting Started, or one of it's subheadings.
4. 

### System Information

https://pastebin.com/sEAPtLWz

**Comment by elken** [comment]
This is known. The docs are currently in flux and will be resolved soon.

For now they exist on `develop`.

**Comment by iyefrat** [comment]
Duplicate of #6671
