### ISSUE TITLE
`doom upgrade`: `-f` is an outdated option

### ISSUE THREAD

**Issue by hydrobeam** [doomemacs/doomemacs#6712]
### What did you expect to happen?

I modified a file under `.emacs.d/modules/lang/go/config.el` (added a newline near the top of the file) then tried to run `doom upgrade`, which gave me this warning suggesting `doom upgrade -f`:

```rs
Error: Refusing to upgrade because "~/.emacs.d/" has been modified.

Either stash/undo your changes or run 'doom upgrade -f' to discard local changes.

 M modules/lang/go/config.el
```

However running `doom upgrade -f` yields this error:
```rs
$ doom upgrade -f

Error: unknown option -f

Usage: doom upgrade [-p|--packages] [-j|--jobs NUM]

See 'doom h[elp] upgrade' or 'doom upgrade {-?,--help}' for documentation.
```

### What actually happened?

Faced with an error when using `doom upgrade -f`

### Describe your attempts to resolve the issue

Looked at the docs via `doom upgrade --help`
```rs
  Global options:
    -!, --force
      Suppress prompts by auto-accepting their consequences.
```
It seems like `-f` is not an option at least anymore, so I just used `--force` instead and it worked

### Steps to reproduce

1. Modify any file under `.emacs.d/modules/`
2. run `doom upgrade` and get instructed to run `doom upgrade -f`
3. run `doom upgrade -f`
4. receive warning that `-f` is not a recognized flag

### System Information

https://pastebin.com/

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
