### ISSUE TITLE
:lang scheme Switch from '+guile' to '+chez' won't start

### ISSUE THREAD

**Issue by kilesduli** [doomemacs/doomemacs#6752]
### What did you expect to happen?

It work fine.

### What actually happened?

```
Message: Symbol's function definition is void
    Details: (geiser-impl--add-to-alist)
    Backtrace:
      (geiser-impl--add-to-alist regexp "\\.def\\'" chez t)
      (byte-code "\300\301\302\"\210\303\304\305\306\307\310\"\311$\266\303\312\313\"\207" [register-definition-prefixes "/home/duli/dotfiles/...
      (load "/home/duli/dotfiles/doomemacs/.emacs.d/.local/autoloads.29.0.50" nil nomessage)
      (condition-case e (load (string-remove-suffix ".el" doom-autoloads-file) nil 'nomessage) ((debug file-missing) (if (locate-file doom-autoloads-f...
      (load-with-code-conversion "/home/duli/dotfiles/doomemacs/.emacs.d/lisp/doom-start.el" "/home/duli/dotfiles/doomemacs/.emacs.d/lisp/doom-start.e...
      (require doom-start)
      (let ((noninteractive nil) kill-emacs-query-functions kill-emacs-hook) (defvar doom-reloading-p nil) (if (file-exists-p doom-autoloads-file) nil...
      (let ((doom-print-indent (+ (if t doom-print-indent-increment 0) doom-print-indent))) (let ((noninteractive nil) kill-emacs-query-functions kill...
      (condition-case ex (let ((doom-print-indent (+ (if t doom-print-indent-increment 0) doom-print-indent))) (let ((noninteractive nil) kill-emacs-q...
      (let nil (doom-print (doom-print--format "The doctor will see you now...\n") :format nil) (doom-print (doom-print--format (doom-print--class 'st...
      ((closure (t) (cli alist) (let nil (doom-print (doom-print--format "The doctor will see you now...\n") :format nil) (doom-print (doom-print--for...
      (funcall (closure (t) (cli alist) (let nil (doom-print (doom-print--format "The doctor will see you now...\n") :format nil) (doom-print (doom-pr...
```

### Describe your attempts to resolve the issue

It seems like bytecode file do not deleted when doom sync. And caused it.
I found #4869 and this line https://github.com/doomemacs/doomemacs/blob/4efdf51ca56820696bf8b237c3725d5fb1eeb229/modules/lang/scheme/autoload.el#L17.
So I deleted `.local/cache/eln` folder and all files about geiser in `.local/straight/repo/`. And have no error appear.

### Steps to reproduce

1. Set `:lang (scheme +guile)` and doom sync
2. Change `:lang (scheme +guile)` to `:lang (scheme +chez)`
3. doom sync
4. Get error

### System Information

https://pastebin.com/1i2gia1x

**Comment by kilesduli** [comment]
Or delete `.emacs.d/.local/straight/build-29.0.50/geise*` , `rm -rf ~/.emacs.d/.local/cache/eln` and doom sync

**Comment by jakelinnzy** [comment]
I got the same problem and reinstalling doom seems to fix it.

**Comment by hlissner** [comment]
This was likely fixed in the many commits of the past 48 hours, which has rewritten how autoloads are generated. I'll close this for now, but let me know if the issue resurfaces.
