### ISSUE TITLE
can't switch between buffer using C-x b

### ISSUE THREAD

**Issue by osfe** [doomemacs/doomemacs#6753]
### What did you expect to happen?

When using C-x b I expect the usual behavior, a minibuffer in which I can choose the one I want to display.

### What actually happened?

Here is what I see instead in the mini-buffer : 

In ‘+vertico/switch-workspace-buffer History’ source: ‘#[0 \304\302\300\305\303$\211\205\0\306\307\310\301""\207 [#[128 \302\300\303\301""\207 [consult--multi-predicate ([(:name main :hidden nil :narrow 49 :category buffer :state +vertico--workspace-buffer-state :items (closure ((name . main) (i . 1) (last-i . 1) (key-range 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90) (workspaces main) (active-workspace . main) t) nil (consult--buffer-query :sort 'visibility :as #'buffer-name :predicate #'(lambda (buf) (let* ((workspace (and t (+workspace-get name t)))) (if workspace (+workspace-contains-buffer-p buf workspace) nil))))))]) apply append] 6 

(fn &rest ARGS2)]  consult--buffer-history nil helm-comp-read-get-candidates nil delete  helm-cr-default] 6]’ 
 (args-out-of-range [(:name "main" :hidden nil :narrow 49 :category buffer :state +vertico--workspace-buffer-state :items (closure ((name . "main") (i . 1) (last-i . 1) (key-range 49 50 51 52 53 54 55 56 57 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90) (workspaces "main") (active-workspace . "main") t) nil (consult--buffer-query :sort 'visibility :as #'buffer-name :predicate #'(lambda (buf) (let* ((workspace (and t (+workspace-get name t)))) (if workspace (+workspace-contains-buffer-p buf workspace) nil))))))] -2097042)

### Steps to reproduce

1. open emacs
2. open multiple files
3. attempt to switch between them using C-x b

### System Information

https://pastebin.com/kaKvU4UU

**Comment by elken** [comment]
> :completion helm vertico

Pick one of those modules to use; ivy, helm and vertico don't co-exist.

**Comment by osfe** [comment]
Hi Elken,
this solved the issue, thank you so much :)
regards, 
Olivier
