### ISSUE TITLE
mu4e evil mode error: Search failed: "quit"

### ISSUE THREAD

**Issue by neildavidforrest** [doomemacs/doomemacs#6762]
### What did you expect to happen?

When opening mu4e (e.g. `SPC o m`) the main mu4e menu should be displayed.

### What actually happened?

An error is displayed:

```
error in process filter: let: Search failed: "quit"
error in process filter: Search failed: "quit"
```

The main mu4e menu is eventually displayed after a short delay, although items in the "Misc" section are duplicated, and it does not automatically fetch new mail.

Example of duplicated menu items:
```
  Misc

	* [;]Switch focus
	* [u]pdate email & database (Alternatively: gr)

	* [N]ews
	* [A]bout mu4e
	* [H]elp
	* [q]uit


	* [;]Switch context
	* [U]pdate email & database

	* [N]ews
	* [A]bout mu4e
	* [H]elp
	* [q]uit

```

### Describe your attempts to resolve the issue

I traced this back to these lines in `~/.emacs.d/modules/email/mu4e/config.el`:

```
  (when (modulep! :editor evil)
    ;; As +mu4e~main-action-str-prettier replaces [k]ey with key q]uit should become quit
    (setq evil-collection-mu4e-end-region-misc "quit"))
```

Commenting out this section apparently resolves the issue.

After this the menu looks like:
```
  Misc

	* [;]Switch focus
	* [u]pdate email & database (Alternatively: gr)

	* [N]ews
	* [A]bout mu4e
	* [H]elp
	* [q]uit
```

The error is not displayed, and mail is fetched.

I'm not sure exactly what the original intent is, so i'm not confident if this is a suitable resolution or not.

I do notice that the comment:
```
; As +mu4e~main-action-str-prettier replaces [k]ey with key q]uit should become quit
```
...does not appear to be true (any more?), i.e. it's still displayed as [q]uit, maybe that is a clue?

I would appreciate any advice. Thanks in advance.

### Steps to reproduce

Open mu4e (`SPC o m`)

### System Information

https://pastebin.com/MwJJujZ0

**Comment by milanglacier** [comment]
are you using older version of mu? I am using mu 1.8.9 and there’s no such problem. And if I use an older mu (1.6), I have the same message but the mu4e dashboard can be succesfully opened.

**Comment by neildavidforrest** [comment]
@milanglacier thanks for testing. this was indeed the problem. i was using mu 1.6 and had been putting off the upgrade as a pre-build package was not available for my distribution. i've built mu 1.8 from source and it works great. thanks again.

**Comment by NovaViper** [comment]
How do you install the latest version of mu? There seems to be no way to install it on Linux Mint/Ubuntu LTS without possibly breaking the system 😔

**Comment by neildavidforrest** [comment]
I checked out the release branch `release/1.8` of mu and followed the build/install instructions. I'm on Ubuntu 20.04 LTS.

I do remember having some issues with emacs not finding the new mu4e package, but after I ensured the old package was fully removed and refreshed it worked fine.

**Comment by NovaViper** [comment]
> I checked out the release branch `release/1.8` of mu and followed the build/install instructions. I'm on Ubuntu 20.04 LTS.
> 
> I do remember having some issues with emacs not finding the new mu4e package, but after I ensured the old package was fully removed and refreshed it worked fine.

Thanks for the info! But I've been trying to build the branch but it's not working at all.. i keep getting this `ninja: error: loading 'build.ninja': No such file or directory` error when I try to run the make command and also I get this `Directory does not contain a valid build tree:` when I run the .autogen.sh file

**Comment by avlec** [comment]
Yeah I had the same problem on Ubuntu 22.04 server. 1.6 is the default version and that doesn't seem to play nice. So manually building/installing mu from source works. Needed the following dependencies though, possibly more...
- meson (might be able to build without it?)
- libxapian-dev
- libgmime-3.0-dev
