### ISSUE TITLE
Doom dashboard does not open on startup

### ISSUE THREAD

**Issue by manueldeljesus** [doomemacs/doomemacs#6780]
### What did you expect to happen?

When I open Emacs, I expect that the Doom dashboard appears once Emacs ends up loading.

### What actually happened?

When I open Emacs, it starts directly into the scratch buffer. If I don't do anything, it stays there. If I open any other buffer, or run any command, the Doom dashboard opens in the background.

That is, after opening Emacs if I list all buffers, the dashboard does not appear. However, after opening any file, or running a command, the dashboard appears among the opened buffers.

Moreover, if I open the Messages buffer after Emacs has loaded, the Messages buffer and the Doom Dashboard open simultaneously in a vertical split.

### Describe your attempts to resolve the issue

I have deleted all the configuration files in my .doom.d directory, so I can assure that the issue is not related to my specific config.

### Steps to reproduce

1. Open Emacs
2. Observe that the doom dashboard does not load
3. Run `SPC b B` to list all buffers and verify that *doom* is not in there
4. Open *any* file
5. Run `SPC b B` and verify that *doom* is there

### System Information

https://pastebin.com/GvBueSwc

**Comment by azzamsa** [comment]
In my case;

- https://github.com/doomemacs/doomemacs/commit/c44bc81a05f3758ceaa28921dd9c830b9c571e61: works
- Old revision: 29e30e8af4 (4 days ago): doesn't work
- New revision: 811c18ca68 (4 hours ago): works

Try the latest version.

**Comment by 0xp0nder** [comment]
Same problem here. When I open Emacs, it appears empty window named `dashboard-refresh-buffer`. I only able to see the dashboard if I create a new tab.

My config files are in a different folder from the default `~/.doom.d`. What  I have done recently is:

-  Fresh installation of Emacs by removing `.emacs.d`
-  Install with empty config
-  Upgrade Doom Emacs
-  Open Emacs
-  Have the same problem (empty window named `dashboard-refresh-buffer`)

**Comment by p7u** [comment]
+1

**Comment by manueldeljesus** [comment]
> * New revision: [811c18c](https://github.com/doomemacs/doomemacs/commit/811c18ca680d31b411ce395e0d28ab97816f177a) (4 hours ago): works

I can confirm that it also works for me.

When I do pull the new commit and run `doom sync -u` afterwards, the first startup throws an error: a timeout due to emacsql. However, if I run `org-roam-db-sync` after the error, the error never reproduces again.

**Comment by 0xp0nder** [comment]
I'm in master and still have the same problem

**Comment by manueldeljesus** [comment]
Have you pulled the last commit from GitHub and then run `doom sync -u`?

If you did that, I am afraid I cannot be of any help. Sorry.

**Comment by 0xp0nder** [comment]
I still have the same problem after doing that. I will try on discord

**Comment by 0xp0nder** [comment]
I fix it by updating Doom Emacs, also I found that if I wait a few seconds after starting up my machine, the `dashboard-refresh-buffer` does not appear anymore. Maybe Doom Emacs needs time on startup

**Comment by Jdogzz** [comment]
@hlissner Looks like this can be closed as OP had the issue resolved?
