### ISSUE TITLE
`Symbol's function definition is void  Details: (doom-initialize-modules)` when running `~/.emacs.d/bin/doom install --force` in a brand new host

### ISSUE THREAD

**Issue by milanglacier** [doomemacs/doomemacs#6784]
### What did you expect to happen?

run `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d     && ~/.emacs.d/bin/doom install --force` on a brand new host and install doom successfully 

### What actually happened?

run `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d     && ~/.emacs.d/bin/doom install --force`
in a brand new host, get the following error:

```
Message: Symbol's function definition is void
   Details: (doom-initialize-modules)
   Backtrace:
     (doom-initialize-modules 'force 'no-config)
     (let ((default-directory doom-emacs-dir) (yes\? (progn (or (progn (and (...
     (let ((config\? (cdr (assq 'config\? alist))) (envfile\? (cdr (assq 'env...
     ((closure (t) (cli alist) (let ((config\? (cdr (assq 'config\? alist))) ...
     (funcall (closure (t) (cli alist) (let ((config\? (cdr (assq 'config\? a...
     (doom-cli-execute #s(doom-cli ("doom" "install") nil (("SUMMARY" . "Inst...
     (let ((cli x9) (bindings x10)) (doom-cli-execute cli bindings))
     (let* ((x9 (car-safe x8)) (x10 (cdr-safe x8))) (let ((cli x9) (bindings ...
     (progn (ignore (consp x8)) (let* ((x9 (car-safe x8)) (x10 (cdr-safe x8))...
     (let ((x8 (car --dolist-tail--))) (progn (ignore (consp x8)) (let* ((x9 ...
     (while --dolist-tail-- (let ((x8 (car --dolist-tail--))) (progn (ignore ...
     (let ((--dolist-tail-- (nreverse runners))) (while --dolist-tail-- (let ...
   ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220916034529.1.error

```

### Steps to reproduce

run `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d     && ~/.emacs.d/bin/doom install --force` on a brand new host

### System Information

https://pastebin.com/clone/hUhTHaj7

**Comment by Anskrevy** [comment]
Was coming here to post this as well.

**Comment by Anskrevy** [comment]
Looks like commit [b914830](https://github.com/doomemacs/doomemacs/commit/b914830403631b3d027cd6c9b9d2dd70546af84e) was the one that did it (shocker). Checkout  [3d6e031](https://github.com/doomemacs/doomemacs/commit/3d6e0311b9fb868f953becb90937b81814b6e65a) and run `doom install` and it should work.

**Comment by jasonjckn** [comment]
Same error here

**Comment by milanglacier** [comment]
> Looks like commit [b914830](https://github.com/doomemacs/doomemacs/commit/b914830403631b3d027cd6c9b9d2dd70546af84e) was the one that did it (shocker). Checkout [3d6e031](https://github.com/doomemacs/doomemacs/commit/3d6e0311b9fb868f953becb90937b81814b6e65a) and run `doom install` and it should work.

via 3d6e031 can succesfully install the doom. `3d6e031` also has other problems: for example `menu-bar-mode` is enabled in terminall mode. I believe doom always disables `menu-bar-mode` and there's no breaking change. Hence `menu-bar-mode` enabled should be considered as a bug. And in my Alpine linux docker machine, even with `evil + everywhere` flag, the `evil-mode` is not enabled on start, I have to manually call `M-x evil-mode` to turn on it.

**Comment by tamasgal** [comment]
Yes I can confirm, the install procedure is not working anymore. Just decided to move from Emacs 27 to 28 and now stranded without Doom 🙈 

For me, https://github.com/doomemacs/doomemacs/commit/3d6e0311b9fb868f953becb90937b81814b6e65a is not working either, as @milanglacier pointed out: the menu bar is there and evil is not on by default. Not sure what else is broken... I will now go back in history and try to find a commit which works.

**Comment by 0x1eef** [comment]
I also ran into this error while trying doom for the first time. Checking out https://github.com/doomemacs/doomemacs/commit/3d6e0311b9fb868f953becb90937b81814b6e65a got me to the point that the install process was successful.

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
