### ISSUE TITLE
`menu-bar-mode` is not disabled for a new fresh install in terminal mode

### ISSUE THREAD

**Issue by milanglacier** [doomemacs/doomemacs#6790]
### What did you expect to happen?

There's no menu bar in terminal for a new fresh install

### What actually happened?

Install doom for a brand new host, the starting up interface is like:

<img width="1430" alt="Screen Shot 2022-09-16 at 12 07 17" src="https://user-images.githubusercontent.com/45728125/190683016-a4e718d2-6517-46ca-aee5-a277bc1d79ce.png">

menubar is not disabled by default

### Describe your attempts to resolve the issue

a directly `setq` to disable it should be fine, but it should be disabled by default for doom.

### Steps to reproduce

1. install doom from new
2. launch doom and see the annoying result

### System Information

https://pastebin.com/SsVJa74y

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
