### ISSUE TITLE
Warning: reference to free variable ‘id’

### ISSUE THREAD

**Issue by Gusted** [doomemacs/doomemacs#6791]
### What did you expect to happen?

No errors were printed while executing `doom upgrade`. 

### What actually happened?

While executing `doom upgrade` an error was printed:

```
! No profile manifest found. Generating one...
  > Regenerating it...
  > Synchronizing 1 known profile...
    - Added safe-mode
    ✓ Regenerated profile manifest: ~/.emacs.d/.local/cache/known-profiles.el

    
    In toplevel form:
    init.28.el:21:50: Warning: reference to free variable ‘id’
```

### Describe your attempts to resolve the issue

It seems to be trival to resolve this issue as a user, by just removing that line to avoid any runtime errors. But obviously this has to be solved in the generation code. 

### Steps to reproduce

1. Execute `doom upgrade` and upgrade after safe-mode profile commit(not sure which, before upgrading the latest commit was 29e30e8af4b937cd0d4c9b5eb900205f22bddf7b and I upgraded to 9121100bb4a619b3e95e0f427ab1fc484216c35d)
2. See generation error.

### System Information

https://pastebin.com/azzffMBn

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by Gusted** [comment]
Thanks @hlissner for the fix (and for Doom Emacs 😉)!

Just to make sure, `doom sync` or `doom profiles sync` should re-write the init code for the profiles right? After upgrading doom it seems it is still the incorrect code:

```lisp
-> % cat ~/.emacs.d/profiles/init.28.el 
;; -*- lexical-binding: t; tab-width: 8; -*-
;; Updated: 2022-09-16 18:48:57
;; Generated by 'doom profiles sync' or 'doom sync'.
;; DO NOT EDIT THIS BY HAND!
"3.0.0-pre"
(funcall
 (alist-get
  (intern
   (getenv-internal "DOOMPROFILE"))
  (list
   (cons 'safe-mode
         (lambda nil
           (let nil
             (set 'user-emacs-directory
                  (file-truename user-emacs-directory))))))
  (lambda nil
    (if
        (or noninteractive
            (file-equal-p user-emacs-directory "~/.config/emacs")
            (file-equal-p user-emacs-directory "~/.emacs.d"))
        (user-error "Failed to find profile: %s" id)
      (user-error "To be a bootloader, Doom must be installed in ~/.config/emacs or ~/.emacs.d")))))
```
