### ISSUE TITLE
org: minibuffer shows `link: nil` in minibuffer when point is on a normal heading

### ISSUE THREAD

**Issue by milanglacier** [doomemacs/doomemacs#6795]
### What did you expect to happen?

put cursor at any heading in org mode, then the minibuffer should display its outline path

### What actually happened?

1. put cursor at any normal heading
2.  the minibuffer displays `link: nil`
<img width="571" alt="Screen Shot 2022-09-16 at 22 40 37" src="https://user-images.githubusercontent.com/45728125/190837620-11e9713e-dbe8-4348-9619-a49467a0f477.png">

PS: if put the cursor at an org link, then the minibuffer displays the link correctly though.
<img width="566" alt="Screen Shot 2022-09-16 at 22 46 03" src="https://user-images.githubusercontent.com/45728125/190837626-42626216-9251-4f01-86ab-432700c76731.png">

### Describe your attempts to resolve the issue

```lisp
(advice-remove #'org-eldoc-documentation-function #'+org-display-link-in-eldoc-a)
```

will be a regression, but not a fix

### Steps to reproduce

put cursor at any heading in org mode, then watch what minibuffer displays

### System Information

https://pastebin.com/pkRESMDR

**Comment by milanglacier** [comment]
it seems that this is because `org-eldoc-documentation-function` is adviced by `+org-display-link-in-eldoc-a`

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
