### ISSUE TITLE
Emacs server failing to start with (server-start) command.

### ISSUE THREAD

**Issue by aadi58002** [doomemacs/doomemacs#6796]
### What did you expect to happen?

Emacs server not starting with `emacsclient -c -a "" -e "(server-start)"`.

![Screenshot_20220917_085036](https://user-images.githubusercontent.com/96418027/190838644-4f7d1428-038a-4268-9a6f-9ec6c5f8b5d7.png)

It works with emacs --daemon . But then the emms player music does not work. It opens vlc but there is no sound.

Also emacsclient can't connect to the emacs --daemon by default i have to maually specify the server file with `-s /tmp/emacs1000/server` but now in this case the emms player does not work.

### What actually happened?

The command `emacsclient -c -a ''  (server-start) is showing the error below
![Screenshot_20220917_084246](https://user-images.githubusercontent.com/96418027/190838463-0703a7c6-c397-47c1-a244-772d7a980602.png)

### Describe your attempts to resolve the issue

I tried to reinstall doom emacs.
I tried disableing the personal config.
I tried to see if the main emacs application works fine. And it does it work with `emacsclient -c -a '' -e "(server-start)"

### Steps to reproduce

1. Try to start the emacs server with `emacsclient -a "" -e "(server-start)"`
2. Connect to it with emacsclient -c -a ""

### System Information

https://pastebin.com/EvniEP03

**Comment by Occhioverde** [comment]
> Also emacsclient can't connect to the emacs --daemon by default i have to maually specify the server file with `-s /tmp/emacs1000/server` but now in this case the emms player does not work.

Direnv too seems to be affected by strange issues when running in client-server mode after the latest update.

If I directly run Emacs without connecting to it through `emacsclient -cs /tmp/emacs1000/server`, in fact, Direnv works as expected, while opening the same folder with a client frame yields the `direnv: error couldn't find a configuration directory for direnv` error along with a message that says `File mode specification error: (wrong-type-argument stringp nil)`:

![Direnv error](https://user-images.githubusercontent.com/18429412/190876957-45bcc8cf-1301-42dd-9eae-8c30202c1247.png)

**Comment by hlissner** [comment]
I cannot reproduce the original issue on the latest commit of Doom. Please update and make sure it hasn't already been fixed.

@Occhioverde Please produce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85#how-to-produce-a-backtrace-3) from the error.

**Comment by MithicSpirit** [comment]
Had the same issue earlier today, but at some point it must've gotten fixed as it works fine again.

**Comment by tecosaur** [comment]
For the record, I had the same issue briefly, if anybody else does try upgrading to the latest Doom.

**Comment by MithicSpirit** [comment]
Sounds like there was a faulty commit somewhere in there that eventually got fixed. Maybe someone should bisect it? Too lazy to do it now but maybe I'll try if/when I have more time.

**Comment by Occhioverde** [comment]
> Please update and make sure it hasn't already been fixed.

Upgrading from 811c18ca68 to 195359cf99 solved both the daemon and the Direnv issue. Thank you very much.
