### ISSUE TITLE
bin/doom sync: Lisp error

### ISSUE THREAD

**Issue by nicdob** [doomemacs/doomemacs#6801]
### What did you expect to happen?

Successfully running bin/doom sync on 0c918f3b2d4e91af56a198b2ac0bdf95ebe55fcb, because of #6800 

### What actually happened?

When running bin/doom sync, doom throws a Lisp error:
https://pastebin.com/CeirQn49

### Describe your attempts to resolve the issue

I tried went a bit through the commit history of bin/doom. It works in b7bd27d22b453d6d7a1411d00ca40faae8261716 and breaks in 775ee2f04aadad02e3e2e8094c8fb4610683c8b6.

### Steps to reproduce

1. Install Doom as per:
```
git clone https://github.com/hlissner/doom-emacs ~/doom-emacs
~/doom-emacs/bin/doom install
```
 2. Run bin/doom install from commit 0c918f3b2d4e91af56a198b2ac0bdf95ebe55fcb because of #6800
 3. Run bin/doom sync 

### System Information

https://pastebin.com/Si4L96mr

**Comment by hlissner** [comment]
Already fixed in https://github.com/doomemacs/doomemacs/commit/7161f27bb3283761c7a7e653de187e2eb8e3d191.
