### ISSUE TITLE
`doom env` is only respected after `doom/reload-env` is called

### ISSUE THREAD

**Issue by powersurge360** [doomemacs/doomemacs#6802]
### What did you expect to happen?

When I open emacs, I expect my `exec-path` to be equivalent to my `$PATH` variable in the shell after I run `doom env` and start emacs from the dock on macOS.

### What actually happened?

My path is minimal, as if the env file generated in `.emacs.d/.local/env` is not being read. If I run `doom/reload-env` after opening emacs, it populates correctly.

### Describe your attempts to resolve the issue

I started with just running an update on doom, then moved on to a fresh install of doom, and then removed my changes to `.doom.d` but nothing seemed to work. I didn't dive into elisp to further debug why it might not be respecting my env on initial start.

### Steps to reproduce

1. Install `doom` per the instructions
2. Run `doom env`
3. Inspect `exec-path` with `SPC :` and searching for `exec-path`
4. See that it is very minimal
5. Run `doom/reload-env` with `SPC h r e`
6. Inspect `exec-path` with `SPC :` and searching for `exec-path`

### System Information

https://pastebin.com/yhJ8cDD8

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by azzamsa** [comment]
Thanks for the report. I have the same issue after the upgrade yesterday. I don't have time to report and I believe it will be released in subsequent days.

Before:

```
("/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "/usr/libexec/emacs/28.1/x86_64-redhat-linux-gnu")
```
I need to invoke `doom/reload-env` manually.

After upgrade:

```
    Old revision: 811c18ca68 (31 hours ago)
    New revision: 9d52ba2747 (73 minutes ago)
```

```
("/run/user/1000/fnm_multishells/81536_1663414964445/bin" "/home/user/bin/private" "/home/user/bin/public" "/home/user/.emacs.d/bin" "/home/user/.cargo/bin" "/home/user/.local/bin" "/home/user/.nodebin/node_modules/.bin" "/usr/local/bin" "/usr/local/sbin" "/usr/bin" "/usr/sbin" "/usr/libexec/emacs/28.1/x86_64-redhat-linux-gnu/")
```

Worked like a charm! :tada: 

Thanks for your hard work for Doom :heart:
