### ISSUE TITLE
Autoload issue for `doom-docs-make-symbol-link`

### ISSUE THREAD

**Issue by bhankas** [doomemacs/doomemacs#6810]
### What did you expect to happen?

After `doom upgrade`, Emacs should start normally.

### What actually happened?

Emacs throws error:

`
error: nil, (error Autoloading file /home/user/.emacs.d/lisp/lib/docs.el failed to define function doom-docs-make-symbol-link
`

### Describe your attempts to resolve the issue

Roll back to `0172b180a9`

### Steps to reproduce

1. `doom upgrade`
2. `$ emacs`

### System Information

https://pastebin.com/4AfiRBKs

**Comment by hlissner** [comment]
Update manually.

```sh
cd ~/.emacs.d
git pull
doom sync -u
```

This is an Emacs 29 issue that is resolved by upgrading manually once, then it shouldn't appear again.
