### ISSUE TITLE
Doom no longer native-compiles ahead of time

### ISSUE THREAD

**Issue by basaran** [doomemacs/doomemacs#6811]
### What did you expect to happen?

Doom sync / Doom install no longer native compiles packages ahead of time. I see *native compile async*, and *native-compile* buffers after launching emacs. 

### What actually happened?

It does on demand compiling instead.

### Describe your attempts to resolve the issue
I have an older doom emacs on the laptop c44bc81a05f3758ceaa28921dd9c830b9c571e61 and it does native compile ahead of time.

### Steps to reproduce

1. Fresh clone doom as of September 18th.
2. Doom install

### System Information

https://pastebin.com/TjYkNFhw

**Comment by hlissner** [comment]
Yes, this was intentionally changed in 3853dff5e11655e858d0bfae64b70cb12ef685ac. I plan to add an `--aot` switch (or similar) to `doom sync`/`doom install` in the near future, but it is currently low priority. For the time being, it might be enough to throw this into `$DOOMDIR/init.el`:

```elisp
(setq native-comp-deferred-compilation nil)
(after! (doom-packages straight)
  (setq straight--native-comp-available t))
```

 I'll leave this open until the switch has been implemented.

**Comment by basaran** [comment]
Thank you for the commit number :) This was driving me a bit south the last 48 hours. I was actually trying to find it out. Much appreciated.

**Comment by ronisbr** [comment]
In macOS after this commit, if I open and close emacs before the compilation finished, I receive dialog saying the Emacs had a problem:

<img width="1112" alt="Captura de Tela 2022-09-21 às 15 25 10" src="https://user-images.githubusercontent.com/1068295/191581951-a5de30a3-cfd5-4a69-975a-3b301729a0ec.png">

**Comment by port19x** [comment]
> Yes, this was intentionally changed in [3853dff](https://github.com/doomemacs/doomemacs/commit/3853dff5e11655e858d0bfae64b70cb12ef685ac). I plan to add an `--aot` switch (or similar) to `doom {sync,install,build}` in the near future, but it is currently low priority. For the time being, it might be enough to throw this into `$DOOMDIR/init.el`:
> 
> ```emacs-lisp
> (setq native-comp-deferred-compilation nil)
> (after! (doom-packages straight)
>   (setq straight--native-comp-available t))
> ```
> 
> I'll leave this open until the switch has been implemented.

Good to know this is intended behaviour 
Looking forward to `--aot`
For anyone else who ends up here, add the mentioned codesnippet after the (doom! ...) and then `doom build`
I assume `doom sync` works for new modules only. At least it didn't start compiling for me.

**Comment by hlissner** [comment]
As of e3fdfee, `doom sync`, `doom upgrade`, and `doom install` all now have an `--aot` option for native-compiling packages ahead-of-time. Note that this will not work to retroactively compile already installed packages, but will do so for newly installed/updated ones. 

You'll need `doom sync --aot --rebuild` if you want to natively compile all your existing packages.

In the future, I'll be adding an option you can set from your config to make ahead-of-time compilation the default, but this will do for now. Thanks for bringing this to my attention, in any case!
