### ISSUE TITLE
Doom emacs ignores EMACSLOADPATH set by wrapper nix wrapper script (nix-darwin)

### ISSUE THREAD

**Issue by motevets** [doomemacs/doomemacs#6839]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I install emacs through darwin-nix & home-manager, install doom emacs through git clone and running the installer, open emacs, and run `C-h v load-path`, I expect to see a long list that includes:
 
```
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp" 
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp/mu4e"
```

### Current behavior

When I install emacs through darwin-nix & home-manager, install doom emacs through git clone and running the installer, open emacs, and run `C-h v load-path`, I see a long list that does not include either
 
```
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp"
```
or
```
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp/mu4e"
```

### Steps to reproduce

1. install emacs through darwin-nix & home-manager with
```
  programs.emacs = {
    enable = true;
    extraPackages = epkgs: [
      pkgs.mu
    ];
  };
```
2. install doom emacs with
```
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
~/.emacs.d/bin/doom install
```
3. open emacs and run `C-h v load-path` 
4. notice that the following are missing:
```
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp" 
"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp/mu4e"
```
5. close emacs
6. `mv ~/.emacs.d ~/.emacs.d.old`
7. open emacs and run `C-h v load-path`
8. notice that `"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp"` and `"/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp/mu4e"` are present

### System Information

https://pastebin.com/w9MBqWXd

**Comment by hlissner** [comment]
Consult `C-h v load-path` and scroll down to "Symbol Properties". What is the value of `initial-value`?

**Comment by hlissner** [comment]
I am unable to reproduce this issue. 

`EMACSLOADPATH="~/testA:~/testB:" doom sync` successfully incorporates the two extra directories into the `load-path` Doom bakes into its cache (and makes its way into `load-path`'s value post-startup.

This suggests that perhaps `EMACSLOADPATH` isn't being set in the context of the `bin/doom` script. Have you done so? Are you sure you're using the correct executable? If not, try:

```sh
EMACS=/path/to/wrapped/emacs doom sync
```

In fact, are you sure `EMACSLOADPATH` is used at all? I searched `home-manager`'s repo for it and found nothing.

**Comment by motevets** [comment]
Thank you for such a quick reply!
> Consult C-h v load-path and scroll down to "Symbol Properties". What is the value of initial-value?
```
Symbol Properties
initial-value
  ("/Users/kindrobot/.emacs.d/lisp/" "/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp" "/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp/mu4e" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/site-lisp" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/site-lisp" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/vc" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/url" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/textmodes" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/progmodes" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/play" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/org" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/nxml" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/net" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/mh-e" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/mail" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/leim" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/language" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/international" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/image" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/gnus" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/eshell" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/erc" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/emulation" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/emacs-lisp" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/cedet" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/calendar" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/calc" "/nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/share/emacs/28.2/lisp/obsolete")
```

> In fact, are you sure EMACSLOADPATH is used at all? I searched home-manager's repo for it and found nothing.

I'm not 100% sure what generates the wrapper script (home-manager, nix-darwin, elf-magic?) But here it is,

```
kindrobot@wapple ~/wrk> which emacs
/etc/profiles/per-user/kindrobot/bin/emacs
kindrobot@wapple ~/wrk> cat /etc/profiles/per-user/kindrobot/bin/emacs
#!/nix/store/6w31h3gy9a6f2nikjh4qjgwrs8aivxsn-bash-5.1-p16/bin/bash

set -x

IFS=:

newLoadPath=()
newNativeLoadPath=()
added=

if [[ -n $EMACSLOADPATH ]]
then
    while read -rd: entry
    do
        if [[ -z $entry && -z $added ]]
        then
            newLoadPath+=(/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp)
            added=1
        fi
        newLoadPath+=("$entry")
    done <<< "$EMACSLOADPATH:"
else
    newLoadPath+=(/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp)
    newLoadPath+=("")
fi

if [[ -n $EMACSNATIVELOADPATH ]]
then
    while read -rd: entry
    do
        if [[ -z $entry && -z $added ]]
        then
            newNativeLoadPath+=(/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/native-lisp:)
            added=1
        fi
        newNativeLoadPath+=("$entry")
    done <<< "$EMACSNATIVELOADPATH:"
else
    newNativeLoadPath+=(/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/native-lisp:)
    newNativeLoadPath+=("")
fi

export EMACSLOADPATH="${newLoadPath[*]}"
export emacsWithPackages_siteLisp=/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/site-lisp

export EMACSNATIVELOADPATH="${newNativeLoadPath[*]}"
export emacsWithPackages_siteLispNative=/nix/store/a2s4v9gr3ksv7kj1x5nd6w7klqb8lxcv-emacs-packages-deps/share/emacs/native-lisp:

exec /nix/store/8s6nbk75kml0nbzfgk5hjzbn0bix667y-emacs-28.2/bin/emacs "$@"
```

> This suggests that perhaps EMACSLOADPATH isn't being set in the context of the bin/doom script. Have you done so? Are you sure you're using the correct executable? If not, try:
>
> ```
> EMACS=/path/to/wrapped/emacs doom sync
> ```

Running `EMACS=/etc/profiles/per-user/kindrobot/bin/emacs ~/.emacs.d/bin/doom sync` fixed the problem!

I had tried running `doom sync` on its own without the `EMACS` env var before which didn't help.

**Comment by motevets** [comment]
Hmm, I wonder if it's because I first ran emacs using the alias that nix-darwin puts in ~/Applications, and I may have even run that before I had `mu` installed, so it might've gotten cached without mu4e in the load-path.

Given that uncertainty, maybe it's just best to close this issue for now. Now that I have a better idea what's going on, I'll pay more attention on a freshly provisioned machine and see if it reproduces and open another issue if it resurfaces.

Thank you for you help!
