### ISSUE TITLE
Error message in `doom doctor` after latest update

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#6840]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I run `doom doctor` it should give out normal result.

### Current behavior

Run `doom doctor`, it gives out `There was an unexpected runtime error` message. The full text dump as below:

```
❯ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 69 modules
  ✓ Detected 218 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
  x There was an unexpected runtime error
    Message: Symbol's value as variable is void
    Details: (key)
    Backtrace:
      (doom-module-context key)
      (let ((doom-module-context (doom-module-context key))) (if doom-inhibi...
      (condition-case ex (let ((doom-module-context (doom-module-context key...
      (let (doom-doctor--errors doom-doctor--warnings) (condition-case ex (l...
      (let (doom-local-errors doom-local-warnings) (let (doom-doctor--errors...
      (let ((group x54) (name x55)) (let (doom-local-errors doom-local-warni...
      (let* ((x54 (car-safe x53)) (x55 (cdr-safe x53))) (let ((group x54) (n...
      (progn (ignore (consp x53)) (let* ((x54 (car-safe x53)) (x55 (cdr-safe...
      (let ((x53 (car --dolist-tail--))) (progn (ignore (consp x53)) (let* (...
      (while --dolist-tail-- (let ((x53 (car --dolist-tail--))) (progn (igno...
      (let ((--dolist-tail-- (doom-module-list))) (while --dolist-tail-- (le...
      (progn (doom-print (doom-print--format (doom-print--class 'start "Chec...
    ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.220925112455.53484.error
```

[cli.doom.220925112455.53484.error](https://github.com/doomemacs/doomemacs/files/9639954/cli.doom.220925112455.53484.error.txt)

### Steps to reproduce

Run `doom doctor`.

### System Information

https://pastebin.com/hwUW8MVv

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
