### ISSUE TITLE
doom-emacs-dir doesn't end in trailing slash

### ISSUE THREAD

**Issue by meedstrom** [doomemacs/doomemacs#6842]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expect helpful-callable (`C-h f`) to show me documentation.

### Current behavior

Using `C-h f` on some functions, I get the error: `No such file or directory: "/home/me/doom-emacsdocs/examples.org"`.

It's clear what's going on: `doom-emacs-dir` should end in a trailing slash but does not.

Since I use chemacs2, I fixed this by going into its config file `~/.emacs-profiles.el` and making sure it sets `EMACSDIR` to `"/home/me/doom-emacs/"`, i.e. ensure a trailing slash:

```
(("doom" . ((user-emacs-directory . "~/doom-emacs/")
            (env . (("DOOMDIR" . "/home/kept/Emacs/conf-doom/")
                    ("EMACSDIR" . "~/doom-emacs/")))))
```

However, Chemacs is not the root cause; something in Doom is stripping the trailing slash unless I set EMACSDIR.  If I start a different Chemacs profile, the variable `user-emacs-directory` retains a trailing slash.

### Steps to reproduce

1. Open Emacs
2. Call `M-x helpful-callable` on some function, such as `org-roam-capture`.
3. The described error appears.

### System Information

https://pastebin.com/vR9uyffn

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
