### ISSUE TITLE
doom-run-hook errors when removing advice: '(void-variable sym)'

### ISSUE THREAD

**Issue by oolonc** [doomemacs/doomemacs#6865]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Emacs should start without entering a backtrace.

### Current behavior

Hello!

I'm getting an error after updating to a6f0bf3123102f54fdb9852a38ee2a3b47d5f80a. I'm not sure exactly what is causing the problem, but think it's possible related to [this](https://github.com/doomemacs/doomemacs/commit/a4b58311daced01a5d5ab32212e5f5b1a259512d#diff-347022e99c0e1168eb93f6296af8ce138a8f4a2d4897627288f841dd3fb82312L733-R732) change. I switched back to `doom-lib.el` in d33478dc79296ac35c75950525073e66ce1a34ce and no longer have the issue.

Thanks for the distro and maintaining it!

<details>
<summary>Full backtrace</summary>

```lisp
Debugger entered--Lisp error: (void-variable sym)
  (functionp sym)
  (cond ((functionp sym) (advice-remove sym #'doom-transient-hook114)) ((symbolp sym) (remove-hook sym #'doom-transient-hook114)))
  doom-transient-hook114()
  funcall(doom-transient-hook114)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(doom-transient-hook114)
  run-hook-wrapped(doom-run-hook doom-transient-hook114)
  (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook))
  (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(doom-init-ui-hook)
  doom-init-ui-h()
  run-hooks(window-setup-hook)
  #f(compiled-function () #<bytecode -0xebf4cc839f435cc>)()
  normal-top-level()
```

</details>

### Steps to reproduce

Update to a6f0bf3123102f54fdb9852a38ee2a3b47d5f80a

### System Information

https://pastebin.com/4NLxcu9C

**Comment by hlissner** [comment]
I was unable to reproduce this error and am unable to explain it, but I reverted the change in ff9602e, which should resolve this. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
