### ISSUE TITLE
Unable to edit files via Tramp

### ISSUE THREAD

**Issue by posiczko** [doomemacs/doomemacs#6871]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Editing files via `/ssh:user@host:file.txt` using Tramp fails to open the files on a remote. The resulting entry in the messages buffer is:

```
tramp-file-name-handler: Wrong number of arguments: (1 . 1), 2
```

### Current behavior

Emacs is at the latest release with the default doom configuration. Editing files via Tramps results in:

```
tramp-file-name-handler: Wrong number of arguments: (1 . 1), 2
```

Debug file is available as a [gist](https://gist.github.com/posiczko/24fa9a3d5d63602df4eeb8e80198f976).

### Steps to reproduce

1. Edit a remote file via `ssh://user@host/file.txt`.

### System Information

https://pastebin.com/Eb2qjws1

**Comment by Jdogzz** [comment]
@posiczko Are you still able to reproduce this error? I am unable to reproduce it.

https://pastebin.com/D25qE5Ya
