### ISSUE TITLE
Forge update package to latest that allows for editing PR Draft status

### ISSUE THREAD

**Issue by TK-WF** [doomemacs/doomemacs#6875]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

On an existing PR I should be able to press `C-c C-e` while on the "Draft" row to edit the Draft status.

--OR--

I should be able to invoke `forge-edit-topic-draft` interactively.

REF: https://magit.vc/manual/forge.html#Editing-Topics-and-Posts

### Current behavior

When trying to edit the Draft status of an existing PR with `C-c C-e` the message "There is no thing at point that could be edited" in the mini-buffer.

### Steps to reproduce

Referenced above.

### System Information

https://pastebin.com/dk7J4ae4

**Comment by hlissner** [comment]
As of c9cc3f8, `forge` is now up-to-date, which should fix this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by TK-WF** [comment]
Missing functionality is working now - I can edit the Draft status of PRs as expected.

There may be a sort-of related bug that has cropped up though. I will open a separate issue if/when I pin it down.
