### ISSUE TITLE
mu4e-alert not working with mu1.8

### ISSUE THREAD

**Issue by k11m1** [doomemacs/doomemacs#6896]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Get working notifications with mu4e-alert as before mu 1.8.

### Current behavior

No notifications using mu 1.8, only getting the notification sound played.

I am not getting any errors nor warnings.

I have my own workaround for this in config.el that takes the function from https://github.com/xzz53/mu4e-alert/blob/master/mu4e-alert.el and sets it as `mu4e-alert-grouped-mail-notification-formatter`.

I have tried to rewrite it for mu 1.8 by myself but i wasn't able to fix it due to my lack of knowledge. I think it related with the mu 1.8 change of contact cells to plist.

I think the problem is related to https://github.com/doomemacs/doomemacs/pull/6832 as well since it deals with this 1.8 conversion.

### Steps to reproduce

1. Open Emacs and mu4e
2. hear "pop" for new mail but no notifications are shown

### System Information

https://pastebin.com/2QmLMkAF

**Comment by tomterl** [comment]
The cause is somewhere in `+mu4e-alert-grouped-mail-notification-formatter-with-bell` in `modules/email/mu4e/config.el`, to get notifications back, you can for the time being either
```
(setq mu4e-alert-email-notification-types '(count))
```
or
```
(setq mu4e-alert-grouped-mail-notification-formatter 'mu4e-alert-default-grouped-mail-notification-formatter)
```
in your config; Note that I tested this with an `unpin!`ed mu4e-alert package, I don't know if this is relevant
