### ISSUE TITLE
Pinning packages seems broken

### ISSUE THREAD

**Issue by dlukes** [doomemacs/doomemacs#6901]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I pinned Treemacs in `packages.el` with:

```elisp
(package! treemacs :pin "938c2678dc29817f57871445bc25699da0df076d")
```

I would expect Doom/Straight to checkout this commit and use it. For instance, I would expect the following output upon running these shell commands:

```shell
$ cd ~/.config/emacs/.local/straight/repos/treemacs/
$ git rev-parse HEAD
938c2678dc29817f57871445bc25699da0df076d
```

### Current behavior

Instead, I see the following output:

```shell-session
$ cd ~/.config/emacs/.local/straight/repos/treemacs/
$ git rev-parse HEAD
e4bb236bd5cd7c077c2207b33d2699485c405536
```

The hash corresponds to [the commit currently pinned by Doom itself](https://github.com/doomemacs/doomemacs/blob/9f22a0a2a5191cf57184846281164f478df4b7ac/modules/ui/treemacs/packages.el#L4).

### Steps to reproduce

1. Enable `treemacs` in your `init.el`.
2. Add `(package! treemacs :pin "938c2678dc29817f57871445bc25699da0df076d")` to your `packages.el`.
3. Run `doom sync` at the command line.
4. Run the commands listed in the sections describing expected/current behavior and check the hash shown by Git. It should be the one from the pin, but it isn't.

### System Information

https://pastebin.com/2680mtV5

**Comment by elken** [comment]
Need to `doom sync -u` when updating recipes

**Comment by dlukes** [comment]
Thanks for the reply! It did occur to me I should try `doom sync -u` too (although the `packages.el` template [only mentions `doom sync`](https://github.com/doomemacs/doomemacs/blob/9f22a0a2a5191cf57184846281164f478df4b7ac/templates/packages.example.el#L4)), but unfortunately, it doesn't help.

**Comment by dlukes** [comment]
I also thought it might be related to the fact that Doom performs a shallow clone which doesn't actually fetch the commit referenced by the pin. So I tried running `git fetch --unshallow` in `~/.config/emacs/.local/straight/repos/treemacs/` and then re-running `doom sync -u`, but still no luck.

**Comment by dlukes** [comment]
I've tried that, and re-tried now, but that just shallowly re-fetches that single commit from Doom's pin (not mine).

**Comment by erik-overdahl** [comment]
I also ran into this problem when trying to change the pin for `org-contrib` after running into https://github.com/doomemacs/doomemacs/issues/6881. Pinning in `$DOOMDIR/packages.el` did not override the commit pinned in `modules/lang/org/packages.el`

**Comment by hlissner** [comment]
This turned out to be a regression introduced in https://github.com/doomemacs/doomemacs/commit/5a5195b84d2fade4de1d55ec5441277a0e2cc591. As of a1f8063 it should be fixed.

Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
