### ISSUE TITLE
mu(4e) 1.6 compatibility

### ISSUE THREAD

**Issue by Grauwolf** [doomemacs/doomemacs#6906]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

mu4e starting without error. bookmarks working.

### Current behavior

When launching mu4e `Space-o-m` the error `error in process filter: Search failed: "quit"` is printed but the mu4e-main buffer is still loaded seemingly correct.

Wanting to go to a bookmark one gets the error `Wrong type argument: commandp, mu4e-search-bookmark`.

### Steps to reproduce

1. starting mu4e via `Space o m`
2. trying to filter via one of the default bookmarks `b n`

### System Information

https://pastebin.com/6KJ6tM27

**Comment by Grauwolf** [comment]
Had the time to `git bisect`. The problem seems to have been introduced in commit 2662d68ae89cf782351fa7801ef8a77087e07bad by @tecosaur 

Reverting that commit makes mu4e work again with mu/mu4e 1.6.

**Comment by tecosaur** [comment]
Thanks for bisecting. I assume the issue is due to `mu4e-headers-buffer-name` not existing in 1.6? If you could confirm and ideally offer an equivalent that would be nice.

**Comment by Grauwolf** [comment]
Yes, setting it in my config.el via

```elisp
(defconst mu4e-headers-buffer-name "*mu4e-headers*"
  "Name of the buffer for message headers.")
```
(taken from https://github.com/djcb/mu/blob/bf0af7465f8a19671ca1441591eefcb2c2a0b701/mu4e/mu4e-helpers.el#L114-L115) makes in work again when disabling evil-shortcuts via `C-z`.

Next up making it work with evil-collection/evil. This still prints the initial reported errors.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/60e94479a7952a9939b349dc478378ea47289fa9 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
