### ISSUE TITLE
Magit updated magit

### ISSUE THREAD

**Issue by Gusted** [doomemacs/doomemacs#6908]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Don't produce an update message for a package that indirectly updated itself.

### Current behavior

Doing `doom upgrade`(from 9f22a0a2a5 to ceb985673c), resulted in magit being indirectly updated by magit:
```
    ✓ (103/229) magit was updated indirectly (with magit)
```

### Steps to reproduce

1. Run `doom upgrade` from version 9f22a0a2a5
2. Observe *incorrect* weird message. 

### System Information

https://pastebin.com/MhSFzNBy

**Comment by hlissner** [comment]
I'm aware of the issue, but it will be fixed as part of #4273, so I'll close this as a duplicate thereof. Thanks for letting me know!
