### ISSUE TITLE
evil-inner-double-quote fails in go-mode

### ISSUE THREAD

**Issue by yathxyz** [doomemacs/doomemacs#6910]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I call `evil-inner-double-quote`, the characters enclosed in double quotes should be selected. In `go-mode` this results in an error.

### Current behavior

When I call `evil-inner-double-quote` in `go-mode` in text enclosed by double quotes I get the following error `evil-forward-quote: End position is smaller than start position`. The error is the same with `evil-a-double-quote`. In a small test I've used the same *scratch* buffer for go-mode and python-mode (as control) for backtrace comparison. The buffer only contained "aa" with the cursor at the first instance of 'a' (see attached image).

![doomemacstest](https://user-images.githubusercontent.com/61882912/197460620-a674af61-8e21-4635-91b0-7e6e0c3a06d4.png)

Here is the backtrace when using go-mode
```
Debugger entered--Lisp error: (error "End position is smaller than start position")
  parse-partial-sexp(5 2 nil nil (0 nil 1 nil nil nil 0 nil nil nil nil))
  evil-forward-quote(34 1)
  forward-evil-quote(1)
  forward-thing(evil-quote 1)
  evil-select-quote-thing(evil-quote 2 3 inclusive 1 nil)
  evil-select-quote(34 2 3 inclusive 1)
  evil-inner-double-quote(nil 2 3 inclusive)
  funcall-interactively(evil-inner-double-quote nil 2 3 inclusive)
  call-interactively(evil-inner-double-quote nil nil)
  command-execute(evil-inner-double-quote)
```

And here's the backtrace when using python-mode for comparison
```
Debugger entered--entering a function:
  evil-forward-quote(34 1)
  forward-evil-quote(1)
  forward-thing(evil-quote 1)
  #f(compiled-function () #<bytecode 0xb441398397837>)()
  bounds-of-thing-at-point(evil-quote)
  evil-select-quote-thing(evil-quote 2 3 inclusive 1 nil)
  evil-select-quote(34 2 3 inclusive 1)
  evil-inner-double-quote(nil 2 3 inclusive)
  funcall-interactively(evil-inner-double-quote nil 2 3 inclusive)
  command-execute(evil-inner-double-quote)
```

### Steps to reproduce

1. Install doom emacs with no prior configuration files in ~/.doom.d.
2. Uncomment `(go +lsp)`. Make sure all dependencies for the golang package are satisfied.
3. Open the *scratch* buffer.
4. Activate `go-mode`, input any text enclosed in double quotes.
5. Call `evil-inner-double-quote` (v i ").

### System Information

https://pastebin.com/3g1unrR9

**Comment by vadimi** [comment]
it looks like this is fixed in go-mode directly - https://github.com/dominikh/go-mode.el/commit/f03998154bbed359f1912284a49b598fef074406. I've tried unpinning the package and it worked for me.
