### ISSUE TITLE
Symbol is void (straight-recipes-nongnu-elpa-retrieve)

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#6914]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

doom sync / doom upgrade work flawlessly

### Current behavior

doom sync/upgrade crashes with error "Symbol's function definition is void" "(straight-recipes-nongnu-elpa-retrieve)"

Seems I'm not the only one:
https://discourse.doomemacs.org/t/cant-upgrade-nor-sync-straight-recipes-nongnu-elpa-retrieve/3294

### Steps to reproduce

1. run doom sync (today: 2022/10/26)
2. observe error

### System Information

https://pastebin.com/Z42z1f9P

**Comment by liar666** [comment]
Quoting:
[geoma](https://discourse.doomemacs.org/u/geoma)
[7d](https://discourse.doomemacs.org/t/cant-upgrade-nor-sync-straight-recipes-nongnu-elpa-retrieve/3294/3)
thanks! I solved it by just installing emacs and doom again from scratch (of course keeping my config files)

In the end I did the same thing (even if it took hours on my very old & slow machine to reinstall all the packages & LSP servers :{ )

**Comment by Balooga** [comment]
I experienced this issue today. Removing `~/.emacs.d/.local/straight/repos/straight.el/` and executing `sync` seemed to fix it.
