### ISSUE TITLE
Native compile error after the latest updates

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#6925]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Updated packs should be byte-compiled and native compiled without error.

### Current behavior

After the latest updates native compile errors appears on many packs, the content are almost the same, as quoted below:

```
Compiling /Users/neo/.emacs.d/.local/straight/build-28.2/doom-modeline/doom-modeline-core.el...
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
libgccjit.so: error: error invoking gcc driver
/Users/neo/.emacs.d/.local/straight/build-28.2/doom-modeline/doom-modeline-env.el: Error: Internal native compiler error failed to compile
```

I cannot determine whether it has something to do with the new macOS 13 Ventura. I'll dig further later.

### Steps to reproduce

Update some packs and launch Emacs.

### System Information

https://gist.github.com/neolee/d9743798ab05e6165448aefb141c8dc2

**Comment by neolee** [comment]
After re-install Xcode command line tools the issue is solved. Closed.

**Comment by mtwomey** [comment]
+1 Had the same issue and reinstalling xcode CLI tools resolved it for me also.
