### ISSUE TITLE
Error running timer ‘which-key--update’: (void-function +vc-gutter/previous-hunk)

### ISSUE THREAD

**Issue by lesliesrussell** [doomemacs/doomemacs#6957]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I press "[" which-key should popup.

### Current behavior

When I press "[" throws an error: "Error running timer ‘which-key--update’: (void-function +vc-gutter/previous-hunk)" and which-key is not displayed.

disable Git-gutter-mode corrects the issue for only current buffer.

backtrace:
```
Debugger entered--Lisp error: (void-function +vc-gutter/previous-hunk)
  which-key--propertize-description("+vc-gutter/previous-hunk" nil nil nil "+vc-gutter/previous-hunk")
  which-key--format-and-replace((("[ SPC" . "+evil/insert-newline-above") ("[ #" . "+evil/previous-preproc-directive") ("[ '" . "evil-previous-mark-line") ("[ (" . "evil-previous-open-paren") ("[ [" . "evil-backward-section-begin") ("[ ]" . "evil-backward-section-end") ("[ `" . "evil-previous-mark") ("[ a" . "evil-backward-arg") ("[ b" . "previous-buffer") ("[ c" . "+evil/previous-comment") ("[ d" . "+vc-gutter/previous-hunk") ("[ e" . "previous-error") ("[ f" . "+evil/previous-file") ("[ F" . "+evil/previous-frame") ("[ h" . "outline-previous-visible-heading") ("[ m" . "+evil/previous-beginning-of-method") ("[ M" . "+evil/previous-end-of-method") ("[ o" . "+evil/insert-newline-above") ("[ s" . "evil-prev-flyspell-error") ("[ t" . "hl-todo-previous") ("[ u" . "+evil:url-decode") ("[ w" . "+workspace/switch-left") ("[ y" . "+evil:c-string-decode") ("[ {" . "evil-previous-open-brace")) nil)
  which-key--get-bindings([91] nil nil)
  which-key--create-buffer-and-show([91])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 100000 t which-key--update nil idle 0 nil])

```

### Steps to reproduce

1. Open emacs
2. Press [ in normal mode

### System Information

https://pastebin.com/3tzLjjZe

**Comment by ronisbr** [comment]
I am also seeing this behavior in a fresh Doom installation without any config.
