### ISSUE TITLE
lsp! does not work when I don't also have treemacs

### ISSUE THREAD

**Issue by krux02** [doomemacs/doomemacs#6961]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`M-x lsp!` should run the lsp project initialization.

### Current behavior

`M-x lsp!` will fail. 

```
Error running timer: (void-function treemacs-define-leaf-node)
```

### Steps to reproduce

just start `lsp!` in a scala project with `(scala +lsp)`

### System Information

https://pastebin.com/9Vh6AiMc

**Comment by mekpavit** [comment]
You can follow this issue [here](https://github.com/emacs-lsp/lsp-metals/issues/84)
