### ISSUE TITLE
Error when attempting to install Doom

### ISSUE THREAD

**Issue by Aspectsides** [doomemacs/doomemacs#6966]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I run 
`git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
  ~/.emacs.d/bin/doom install`

Doom should install normally

### Current behavior

When I run the installation command, this happens 
```
`Installing plugins
> Installing straight...
x There was an unexpected runtime error
  Message: Wrong type argument
  Details: (stringp afternoon-theme)
  Backtrace:
    (intern afternoon-theme)
    ((closure ((package . gnu-elpa-mirror) use-package-pre-ensure-function use-package-keywords use-package-ensure-function use-package-defaults package-selected-packages packa...
    (cl--position gnu-elpa-mirror ((afternoon-theme :url "https://github.com/osener/emacs-afternoon-theme" :ignored-files ("*.png")) (alect-themes :url "https://github.com/alez...
    (cl-position gnu-elpa-mirror ((afternoon-theme :url "https://github.com/osener/emacs-afternoon-theme" :ignored-files ("*.png")) (alect-themes :url "https://github.com/alezo...
    (cl-find gnu-elpa-mirror ((afternoon-theme :url "https://github.com/osener/emacs-afternoon-theme" :ignored-files ("*.png")) (alect-themes :url "https://github.com/alezost/a...
    (straight-recipes-nongnu-elpa--translate (cl-find package (straight-recipes-nongnu-elpa--recipes) :key #'(lambda (it) (intern (car it)))))
    (straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (apply straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (let ((default-directory (if local-repo (straight--repos-dir local-repo) default-directory)) (func (intern (format "straight-recipes-%S-%S" name method)))) (apply func args))
    (let* ((--cl-rest-- recipe) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo))))) (let ((default-directory (if local-repo (straight--repos-dir local-repo) defau...
    (let ((recipe (straight--convert-recipe name cause))) (let* ((--cl-rest-- recipe) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo))))) (let ((default-directory...
    (let ((straight--recipe-repository-stack (cons name straight--recipe-repository-stack))) (straight-use-package name nil nil cause) (let ((recipe (straight--convert-recipe n...
  ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.221126205047.148044.error
```
![error](https://user-images.githubusercontent.com/64868985/204119826-7fc43f29-1f1d-44a4-9036-a35153863c82.jpg)

### Steps to reproduce

1. Install emacs with `sudo pacman -S emacs-nativecomp`
2. Install ripgrep and find with `sudo pacman -S ripgrep fd`
3. Run `git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
  ~/.emacs.d/bin/doom install`

### System Information

https://gist.github.com/Aspectsides/e22c893a68ca6da5ae0166c6dfb4bf25

**Comment by bipinmdr07** [comment]
This issue is similar to #6960.

You can try the workaround as in [this comment](https://github.com/doomemacs/doomemacs/issues/6960#issuecomment-1327122489) suggested by `@goofansu` until this gets resolved.

**Comment by Aspectsides** [comment]
> This issue is similar to #6960.
> 
> You can try the workaround as in [this comment](https://github.com/doomemacs/doomemacs/issues/6960#issuecomment-1327122489) suggested by `@goofansu` until this gets resolved.

Ok, thank you, that works perfectly! Closing.

**Comment by vishnudas-bluefox** [comment]
> This issue is similar to #6960.
> 
> You can try the workaround as in [this comment](https://github.com/doomemacs/doomemacs/issues/6960#issuecomment-1327122489) suggested by `@goofansu` until this gets resolved.

Perfectly working solution thanks for the help
