### ISSUE TITLE
org +present

### ISSUE THREAD

**Issue by brucejuz** [doomemacs/doomemacs#6981]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I have change (org +present) in the init.el.
But when I open doom emacs:
In message buffer, it shows:
progn: Cannot open load file: No such file or directory, org-re-reveal

### Current behavior

I have change (org +present) in the init.el.
But when I open doom emacs:
In message buffer, it shows:
progn: Cannot open load file: No such file or directory, org-re-reveal
or
File mode specification error: (file-missing Cannot open load file No such file or directory org-re-reveal)

### Steps to reproduce

1. open emacs
2. :e text.org
3. it will not into the org-mode
4. You must use M-x, org-mode to go into the org mode.
5. the org-re-reveal doesn't work

Thanks!

### System Information

https://pastebin.com/GdCaXTjb

**Comment by peterhoeg** [comment]
`doom sync` ?

I'm a heavy `(org +present)` user and it works perfectly fine here.

**Comment by brucejuz** [comment]
Thank you!
I try the many times,  and find out that the strange problem is that the connection to github is so poor. 
So I  have to use "Doom sync" or "install" many times to finished git cloning process. 
Some how, it seem to have finished git clone. And your can actually finished the "Doom sync" and "Doom doctor", but it still have this issue.

So I doing these steps to solve the problem:
I turned the "+present" off in my init.el. 
Then "Doom sync"
Then "Doom purge"
Then  turn on "+present" again.
Then "doom sync"
With some lucky, the connection to github is stable for a while, the git cloning was not interrupt, then i fix the problem. Thanks a lot.

Doom emacs is great!
But it depends so heavily on the github. There are someplace where the connection to the github is so poor, which keep the users from using it. 
Hope doom emacs can give an option to chose download the packages from GNU or server.

**Comment by peterhoeg** [comment]
It's not that doom uses github heavily (sure, it itself is hosted there), but it's that most of the emacs packages happen to be hosted on github.

**Comment by Jdogzz** [comment]
@hlissner Since it looks like this one was resolved, and was an issue with stable internet connection rather than the doom emacs side of things, this may be able to be closed?
