### ISSUE TITLE
`(wrong-type-argument sequencep #<subr code-review-section--magit-diff-insert-file-section>)` when starting code-review

### ISSUE THREAD

**Issue by ahmetrehaseker** [doomemacs/doomemacs#6987]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I should start the code-review if I enable the `magit` with `+forge`

### Current behavior

packages.el in magit module pins the  `0ef98ef51811807952a4c3c677cbf3dfb269de2e` hash of magit repository and `95b36ec8e7935f96b2f3c6c9086d49cf4a72cbff` hash of code-review repository. 

In that version of magit  one function `magit-diff-insert-file-section` accepts 8 arguments `(file orig status modes rename header binary long-status)` but the function `code-review-section--magit-diff-insert-file-section` which overwrites the magits function in code-review repo accepts 7 arguments `(file orig status modes rename header &optional long-status)`  they fixed this method in commit `975465487aa2388b8a2544a2b64dce4c0279c572`. Because of this we get `deferred error : (wrong-type-argument sequencep #<subr code-review-section--magit-diff-insert-file-section>)
` error when try to  open code-review

### Steps to reproduce

1. Open emacs
2. `M-x +magit/start-code-review RET`
3. Enter a PR url
4. Observe the `*Messages*` buffer

### System Information

https://gist.github.com/ahmetrehaseker/082ec39953bc0b3012350c10f636b27b

**Comment by nipuna-perera** [comment]
Did you figure out a workaround? I am running into the same and I'm unable to do code reviews.

**Comment by ahmetrehaseker** [comment]
You can unpin the code-review package that will work

**Comment by nipuna-perera** [comment]
Unpinning code review didn't work. i am still getting the same error. Did you unpin any of the other packages? Like forge?

**Comment by ahmetrehaseker** [comment]
adding this line `(unpin! code-review)` into `.doom.d/packages.el` and `doom sync` worked for me

**Comment by shroomist** [comment]
`doom sync` wasn't enough for me, I had to `doom upgrade` after `(unpin! code-review)`

**Comment by mcamou** [comment]
`doom sync -u` worked for me

**Comment by hlissner** [comment]
As of 5018f93 this should be resolved. Thanks for letting me know and to @shroomist for the PR!

-----

BTW: Don't forget the `-u` option in `doom sync -u` when updating packages. `doom sync` alone does not update them, it only installs missing packages.
