### ISSUE TITLE
Error running ts-ls server after successfully installing

### ISSUE THREAD

**Issue by acanimal** [doomemacs/doomemacs#6989]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I want to have `ts-ls` active when opening a `.ts.` file

### Current behavior

First time I open a `.ts` file I've asked to install a lsp server. `ts-ls` is installed successfully but fails on running.

Next I attach all the outputs:

ls-install (npx) buffer
```
-*- mode: compilation; default-directory: "~/.emacs.d/.local/etc/lsp/npm/typescript/lib/node_modules/typescript/" -*-
Comint started at Sun Dec 11 14:08:01

/Users/antonio/.nvm/versions/node/v18.12.1/bin/npx npm-install-peers
This package doesn't seem to have any peerDependencies

Comint finished at Sun Dec 11 14:08:03
```

lsp-install (npm) buffer
```
-*- mode: compilation; default-directory: "~/Projects/sideprojects/miims/packages/graphql/src/" -*-
Comint started at Sun Dec 11 14:07:58

/Users/antonio/.nvm/versions/node/v18.12.1/bin/npm -g --prefix /Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript install typescript

added 1 package, and audited 2 packages in 947ms

found 0 vulnerabilities

Comint finished at Sun Dec 11 14:08:00
```

lsp og
```
Command "deno lsp" is not present on the path.
Command "/Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript-language-server/bin/typescript-language-server --tsserver-path /Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript/bin/tsserver --stdio" is present on the path.
Command "deno lsp" is not present on the path.
Command "/Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript-language-server/bin/typescript-language-server --tsserver-path /Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript/bin/tsserver --stdio" is present on the path.
Command "deno lsp" is not present on the path.
Found the following clients for /Users/antonio/Projects/sideprojects/miims/packages/graphql/src/index.ts: (server-id ts-ls, priority -2)
The following clients were selected based on priority: (server-id ts-ls, priority -2)
```

ts-ls::stderr
```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /Users/antonio/.emacs.d/.local/etc/lsp/npm/typescript-language-server/lib/node_modules/typescript-language-server/lib/ts-protocol.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.12.1

Process ts-ls stderr finished
```

### Steps to reproduce

- First time I open a .ts file I'have asked to install a lsp server. You can also test uninstalling and installing server again with `lsp-uninstall-server/lsp-install-server`
- I chose to install de recommended `ts-ls`.
- Process finishes successfully and all seems installed but when run de ts-ls server an error arise.

### System Information

https://pastebin.com/j4qXXLQ2

**Comment by mustaqimM** [comment]
I had the same problem and had to manually install it like so:

`pnpm -g --prefix /home/mustaqim/.emacs.d/.local/etc/lsp/npm/typescript install typescript`

`pnpm -g --prefix /home/mustaqim/.emacs.d/.local/etc/lsp/npm/typescript install typescript-language-server`

Personally, I use `pnpm`, but it should be the same.

**Comment by acanimal** [comment]
The error was reported in `lsp-mode` project: https://github.com/emacs-lsp/lsp-mode/issues/3576 and https://github.com/emacs-lsp/lsp-mode/issues/3851

I will close the issue because it is not related with doomemacs
