### ISSUE TITLE
Calls to doom script fails after fresh clone in wsl 

### ISSUE THREAD

**Issue by innerout** [doomemacs/doomemacs#6990]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I clone the doom emacs repository, I expect to be able to call the doom binary and install the doom distribution.

### Current behavior

When I clone the doom emacs repository and run the doom sync command, the shell reports:
`/usr/bin/env: ‘sh\r’: No such file or directory`

To fix this issue, I ran the following commands: 
```
cd ~/.emacs.d/bin
sed $'s/\r$//' ./doom > doom_backup
mv doom_backup doom
```
Then every command runs as expected.

### Steps to reproduce

1. Clone the doom repo based on the repo's instructions in a wsl installation.
2. Run `doom sync`

### System Information

https://pastebin.com/e1ZkujhU

**Comment by sephiron99** [comment]
This works for me.
`$ git config --global core.autocrlf false`

from [this](https://stackoverflow.com/a/13154031).

**Comment by innerout** [comment]
This works for me too. Thanks for the suggestion! Closing this issue.
