### ISSUE TITLE
File missing when installing

### ISSUE THREAD

**Issue by god464** [doomemacs/doomemacs#6991]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Can not install Doom Emacs follow the [manual](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#doom-emacs)

### Current behavior

When I run ``.\.emacs.d\bin\doom install``, I receive the error log like follow this:
```
Installing Doom Emacs!

- Skipping ~/.doom.d/ (already exists)
  - Skipping init.el (already exists)
  - Skipping config.el (already exists)
  - Skipping packages.el (already exists)
- Envvar file already exists, skipping
Installing plugins
x There was an unexpected runtime error
  Message: File is missing
  Details: ("Cannot open load file" "No such file or directory" "c:/Users/ddh/.emacs.d/.local/straight/repos/straight.el/straight.el")
  Backtrace:
    (require straight "c:/Users/ddh/.emacs.d/.local/straight/repos/straight....
    (let ((repo-dir (doom-path straight-base-dir "straight/repos/straight.el...
    (let ((process-environment (copy-sequence process-environment))) (setenv...
    (doom--ensure-straight (:host github :repo "radian-software/straight.el"...
    (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (p...
    (let ((packages (doom-package-list '((:core))))) (let* ((--cl-rest-- (al...
    (progn (if doom-inhibit-log nil (doom--log "Initializing straight")) (le...
    (if (or force-p (null (and (boundp 'straight-recipe-repositories) straig...
    (doom-initialize-core-packages nil)
    (doom-initialize-packages)
    (doom-packages-install)
    (if (eq install\? :no) (doom-print (doom-print--format (doom-print--clas...
  ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.221214172109.6704.error
```

### Steps to reproduce

Per above, I just ran ``doom install`` and received this error. I try to search "straight.el" in this repositories but no result.

I did not encounter this problem when installing on Arch Linux, maybe the Windows installation script needs to be updated?

### System Information

https://gist.github.com/god464/ecac2c970a6b39af0f4d0e7b2e2ba85c

**Comment by 4wardx** [comment]
Do you have some network issues, e.g. too slow download speed?

This issue can be solved by entering the `~/.emacs.d/.local/straight/repo/`, and if I am right,
you can easily find that the `straight` folder is empty, what you need to do is deleting the
*empty* package folders, in your case, it is `straight`. After that, try to reinstall it.

BTW, this is a common issuewhen *github,com* is blocked.

**Comment by 4wardx** [comment]
Do you have some network issues, e.g. too slow download speed?

This issue can be solved by entering the `~/.emacs.d/.local/straight/repo/`, and if I am right,
you can easily find that the `straight` folder is empty, what you need to do is deleting the
*empty* package folders, in your case, it is `straight`. After that, try to reinstall it.

BTW, this is a common issue where *github.com* is blocked.

**Comment by stephenwithav** [comment]
I can reproduce this.
