### ISSUE TITLE
issue with TLS handshake obtaining packges from Codeberge "Visual-fill-column"

### ISSUE THREAD

**Issue by alarawms** [doomemacs/doomemacs#7013]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When installing, pulling visual-fill-column, should be okay. 
During the git the TLS handshake fails. The installer fails to proceed. 

### Current behavior

 > Updating packages (this may take a while)...
    x The package manager threw an errorumn...
    x Last 16 lines of straight's error log:
      [Return code: 0]
      $ cd /home/xxx/.emacs.d/.local/straight/repos/fringe-helper.el/
      $ git log --oneline --no-merges ef4a9c023bae18ec1ddd7265f1f2d6d2e775efdd \^ef4a9c023bae18ec1ddd7265f1f2d6d2e775efdd
      [Return code: 0]
      $ cd /home/xxx/.emacs.d/.local/straight/repos/visual-fill-column/
      $ git rev-parse HEAD
      453d698d7fc243a547665f8ba43c55eee574e0db
      [Return code: 0]
      $ cd /home/xxxx/.emacs.d/.local/straight/repos/visual-fill-column/
      $ git config --get remote.origin.url
      https://codeberg.org/joostkremers/visual-fill-column.git
      [Return code: 0]
      $ cd /home/xxx/.emacs.d/.local/straight/repos/visual-fill-column/
      $ git fetch origin
      fatal: unable to access 'https://codeberg.org/joostkremers/visual-fill-column.git/': gnutls_handshake() failed: Error in the pull function.
      [Return code: 128]
    ! Wrote extended straight log to ~/.emacs.d/.local/logs/cli.doom.221225070705.9119.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.

### Steps to reproduce

from shell 

.emacs.d/bin/doom sync 
.emacd.d/bin/doom upgrade 

### System Information

https://pastebin.com/1VCRxG1b

**Comment by vikigenius** [comment]
I am facing the same issue as well. Doom upgrade no longer works

**Comment by flaggerkatt** [comment]
Worked fine for me until today; now facing a 502-error from the same repo (can file a separate bug if preferred, but have a hunch these might be related?

$ git fetch origin
      fatal: unable to access 'https://codeberg.org/joostkremers/visual-fill-column.git/': The requested URL returned error: 502

**Comment by AlexLJordan** [comment]
Currently (19-06-23) Codeberg.org is experiencing an outage. According to their mastodon an SSD failed and is impacting performance: https://social.anoxinon.de/@Codeberg/110570203087630341

Is there any way to avoid `doom upgrade` completely failing because of this?

**Comment by dsbahr** [comment]
Facing the same issue, it also prevents me from reinstalling doom from scratch. I get the same error when trying to install a new doom instance and/or when upgrading doom.

**Comment by roiholtzman** [comment]
I am also having a similar issue. Has anyone found a workaround?

**Comment by AlexLJordan** [comment]
> I am also having a similar issue. Has anyone found a workaround?

It works again when Codeberg comes back online.
So just waiting a day for the upgrade would probably suffice. Not a nice solution but it works!

(Disclaimer: I have moved away from emacs some months ago.)

**Comment by hlissner** [comment]
There is a more reliable [Github mirror](https://github.com/emacsmirror/visual-fill-column) for the package. Use the following to install it from there instead of Codeberg:

```elisp
;;; add to $DOOMDIR/packages.el
(package! visual-fill-column
  :recipe (:host github :repo "emacsmirror/visual-fill-column"))
```

Then run `doom sync -u` and restart Emacs. 

I may also add a mirror to @doomelpa in the future, since emacsmirror lacks fully complete recipes for its packages, but until then, the above is your best bet.

**Comment by roiholtzman** [comment]
> > I am also having a similar issue. Has anyone found a workaround?
> 
> It works again when Codeberg comes back online. So just waiting a day for the upgrade would probably suffice. Not a nice solution but it works!
> 
> (Disclaimer: I have moved away from emacs some months ago.)

But it seems that it is online. I can see it in my browser. 




> There is a more reliable [Github mirror](https://github.com/emacsmirror/visual-fill-column) for the package. Use the following to install it from there instead of Codeberg:
> 
> ```emacs-lisp
> ;;; add to $DOOMDIR/packages.el
> (package! visual-fill-column
>   :recipe (:host github :repo "emacsmirror/visual-fill-column"))
> ```

For me it happens for spell-fu (I think). This is the output I get for `doom upgrade`
```
  x The package manager threw an error
    x Last 16 lines of straight's error log:
      [Return code: 0]
      $ cd /Users/roiho/.emacs.d/.local/straight/repos/emacs-spell-fu/
      $ git rev-parse HEAD
      aed6e87aa31013534b7a6cbedb26e4f29ccea735
      [Return code: 0]
      $ cd /Users/roiho/.emacs.d/.local/straight/repos/emacs-spell-fu/
      $ git rev-parse -q --verify e4031935803c66eca2f076dce72b0a6a770d026c\^\{commit\}
      [Return code: 1]
      $ cd /Users/roiho/.emacs.d/.local/straight/repos/emacs-spell-fu/
      $ git config --get remote.origin.url
      https://codeberg.org/ideasman42/emacs-spell-fu.git
      [Return code: 0]
      $ cd /Users/roiho/.emacs.d/.local/straight/repos/emacs-spell-fu/
      $ git fetch origin
      fatal: unable to access 'https://codeberg.org/ideasman42/emacs-spell-fu.git/': SSL: no alternative certificate subject name matches target host name 'codeberg.org'
      [Return code: 128]
```

**Comment by hlissner** [comment]
As of 179e300, the `:editor word-wrap` module has been reconfigured to use the Github mirror, which should resolve this issue as far as Doom is concerned, but users installing the package themselves will have to use [the advice I set out above](https://github.com/doomemacs/doomemacs/issues/7013#issuecomment-1975987029).

@roiholtzman Thanks for letting me know. As of 183ab38, our module now uses the emacsmirror mirror.

**Comment by roiholtzman** [comment]
> As of [179e300](https://github.com/doomemacs/doomemacs/commit/179e300bfdd55d6dc8b002a63481990a1e86b574), the `:editor word-wrap` module has been reconfigured to use the Github mirror, which should resolve this issue as far as Doom is concerned, but users installing the package themselves will have to use [the advice I set out above](https://github.com/doomemacs/doomemacs/issues/7013#issuecomment-1975987029).
> 
> > For me it happens for spell-fu
> 
> @roiholtzman Thanks for letting me know. As of 183ab38, our module now uses the emacsmirror mirror.


Thanks @hlissner 
Excuse my ignorance. Does this mean that if I will now do `doom upgrade` I will not see this issue?

**Comment by hlissner** [comment]
> Does this mean that if I will now do doom upgrade I will not see this issue?

Yes, it should.

**Comment by whompyjaw** [comment]
I hope it's okay if I add this comment. Please feel free to delete it since it's not related to doom, but I found this issue when searching that error. 

My work doesn't trust self-signed certs, so this solution should work for non-doom but using straight users:
(this also assumes you have straight setup)
```
(use-package visual-fill-column
  :straight (visual-fill-column :type git :host github :repo "emacsmirror/visual-fill-column"))
```
I am a huge huge fan of Doom emacs and used it for many years, and would recommend *everyone* use it at least once in their Emacs journey. But, once I became Emacs savvy I went back to vanilla and rebuilt my own config. (Mostly because my work did not play nicely with it at times)
