### ISSUE TITLE
vertico childframe no longer working

### ISSUE THREAD

**Issue by Schweber** [doomemacs/doomemacs#7025]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

In my `init.el` i have (vertico +childframe +icons). Vertico should open in a childframe in the center of screen when pressing `SPC f p` with the standard keybindings and did so until the most recent update a few days ago.

### Current behavior

Vertico doesn't open in a childframe but only at the bottom (is it called minibuffer?).

![image](https://user-images.githubusercontent.com/64630479/210485318-b638a6f0-783e-4919-94c2-889fc782df6c.png)

### Steps to reproduce

1. add (vertico +childframe +icons) to `init.el`
2. run `doom upgrade`
3. restart emacs
4. press e.g. `SPC f p` on standard keybindings

### System Information

https://pastebin.com/myMMKnZ9

**Comment by innerout** [comment]
Hi, are you using emacs from a terminal?

**Comment by Schweber** [comment]
Hi,

no, i use it as a GUI window. Except running doom upgrade i changed nothing at all and it worked fine before.

**Comment by M1ndo** [comment]
@Schweber There might be a possibility on why vertico childframe is not working i see that you also have company-mode childframe enabled too. so there's a high chance there might be confliction where vertico childframe is disabled.

**Comment by Schweber** [comment]
@M1ndo Thank you for the suggestion, it didn't help though.

I noticed that `vertico-posframe` is enabled by default as it should be and if i disable and re-enable it, then the childframe works. I also noticed that it received an update 3 weeks ago if i remember correctly so i think they introduced a mistake.

**Comment by KaiAragaki** [comment]
Breaking commit appears to be https://github.com/tumashu/vertico-posframe/commit/0834bbbfd4def85677afd8a50dc2fe94d5756f47. Pinning to https://github.com/tumashu/vertico-posframe/commit/c40ec61fd54dddb3a0e72a909099c20167804134 appears to fix this.
