### ISSUE TITLE
Wrong company backends set to eshell-mode

### ISSUE THREAD

**Issue by BeBel42** [doomemacs/doomemacs#7040]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Please note that the issue was already published on:
Discourse: https://discourse.doomemacs.org/t/completing-path-to-executable-in-eshell-removes-the-preceding-path/2527 (linking to github link)
Discord (by me): https://discord.com/channels/406534637242810369/1058490454997467146
Github: https://github.com/company-mode/company-mode/issues/1322
The fix in github did not work, the only way I had to fix it was to upgrade to emacs 29, but I want to stay on 28.2

I expect that, in an eshell buffer, when pressing **TAB** on a prompt containing:
`./executa`
That the prompt should be changed to:
`./executable.sh`
(if executable.sh is an executable file in the current directory)

### Current behavior

Eshell will replace
`./executa`
by
`executable.sh`
(without the "./")
When pressing **TAB**.
Pressing enter afterwards will not execute the file but show this instead:
`Wrong type argument: sequencep, 771` Which is normal (because the "./" is missing)

### Steps to reproduce

1. Open emacs
2. Open an eshell bugger (SPC o e)
3. Go to directory where an executable file is located (e.g.: .out files o .sh file) Those files need to have +x privileges for the autocompletion to detect them.
4. Start typing `./executable-name` but not entirely, then press **TAB** to trigger autocompletion.
5. The autocompletion remove the "./"

### System Information

https://pastebin.com/9mWGDgbV

**Comment by BeBel42** [comment]
I could find a way to fix it by disabling company mode and using the deprecated pcomplete:

```lisp
(add-hook 'eshell-mode-hook
	(lambda ()
		(company-mode -1)
		(setq eshell-cmpl-cycle-completions nil)
		(define-key eshell-mode-map (kbd "<tab>")
			#'(lambda ()
				  (interactive)
				  (pcomplete t)))))
```

But I get this warning when doing `doom/reload` after opening an eshell buffer:
```
Warning (initialization): An error occurred while loading ‘/home/martin/.config/emacs/.local/etc/@/init.28.elc’:

Error in a Doom module: /home/martin/.config/emacs/modules/term/eshell/config.el, (wrong-type-argument sequencep 771)
```

**Comment by BeBel42** [comment]
The issue was company not having the right backends set to it.

Here is the code that fixes it by setting the correct backends:
```lisp
(set-company-backend! 'eshell-mode
	'(company-files)
	'(company-shell :with company-yasnippet))```

**Comment by claytharrison** [comment]
> The issue was company not having the right backend set to it.
> 
> Here is the code that fixes it by setting the correct backends:
> 
> ```lisp
> (set-company-backend! 'eshell-mode
> 	'(company-files))
> ```

Did this fix all your issues with eshell? i.e. `Wrong-type-argument` instead of working `eshell-did-you-mean` mode, and the error message when running `doom/reload` after opening an eshell? I tried this fix but neither of those issues have changed for me.

**Comment by victorawareways** [comment]
Any update on this one? I upgraded Doom Emacs and now I don't have the completion list for files, it works for folders only

**Comment by MAVDOGz** [comment]
Also have this issue. Using 29.4 build with following error:

⛔ Warning (initialization): An error occurred while booting Doom Emacs:

Error in a Doom module: /home/usr/.config/emacs/modules/term/eshell/config.el, (wrong-type-argument sequencep 771)

**Comment by hlissner** [comment]
This was fixed in https://github.com/doomemacs/doomemacs/commit/dbcd30820bccc79680ad83f8a09cdc1614027c5a.
