### ISSUE TITLE
Recentf mode broken

### ISSUE THREAD

**Issue by xeruf** [doomemacs/doomemacs#7048]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I get this error at startup and when trying to open a file for the first time:
 
    Error (doom-first-file-hook): Error running hook "recentf-mode" because: (wrong-type-argument symbolp (:method :user :domain :host :port :localname :hop))

### Current behavior

The selected file does not open until I do it thrice.

And I cannot use recentf:
```
Loading /home/janek/.local/state/emacs/cache/recentf...
eval-buffer: Wrong type argument: symbolp, (:method :user :domain :host :port :localname :hop)
```

### Steps to reproduce

Try to use recentf in Doom

### System Information

https://pastebin.com/7zSy9GjV

**Comment by xeruf** [comment]
Note: removing /home/janek/.local/state/emacs/cache/recentf fixes it, idk how this ended up in there:
```sh
❯ cat recentf
;;; Automatically generated by ‘recentf’ on Mon Jan 16 15:41:01 2023.

(setq (:method :user :domain :host :port :localname :hop)recentf-list
      '(
        "/home/janek/data/5-incubator/downloads/"
        ))

(setq recentf-filter-changer-current 'nil)



;; Local Variables:
;; coding: utf-8-emacs
;; End:
```
either way, this should not break that much

**Comment by xeruf** [comment]
and why is this file constantly resetting now :thinking:

**Comment by hlissner** [comment]
Not sure how that got into your recentf cache. Since you've seemingly fixed it, and it doesn't seem like a Doom issue, I will close this.
