### ISSUE TITLE
Default emacs theme

### ISSUE THREAD

**Issue by bo-tato** [doomemacs/doomemacs#7050]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`(setq doom-theme 'default)` will leave the emacs default color scheme, as I found searching here: https://github.com/doomemacs/doomemacs/issues/4214

### Current behavior

Initially it somewhat worked, but with lot's of text not showing up, I assume same color as the background. I tried to set it to 'default again now to take screenshots and now I just see a black screen but it's just the colors, emacs is still working if I type out the keystrokes to open and edit a file.

Everything is working fine with emacs default theme if rather than 'default I use nil, in config.el:
`(setq doom-theme nil)` 

### Steps to reproduce

Just a clean default doom installation with `(setq doom-theme 'default)` in `config.el`

### System Information

https://gist.github.com/bo-tato/5c721d7b472a987784d661719e3a980b

**Comment by tendernine** [comment]
If you add "doom" to init.el, the default color theme is doom-one.
You can comment out "doom" from init.el. 
Also, I can't find any documentation that says the default can be set.

**Comment by bo-tato** [comment]
oh neat, but disabling that will get rid of some other font and ui improvements?
Really all I want in a color scheme is:
1. light
2. not have code comments be some faint light color on white
of all the light color schemes in doom default theme pack, the emacs default is the only light one with readable comments

**Comment by tendernine** [comment]
"doom" provides only themes.
The Doom theme is a special theme that supports solaire-mode.
The default Emacs theme does not support solaire-mode visual effects.
I don't know of any Emacs-like theme that supports solaire-mode.
You might want to report this to doomemacs/themes rather than doomemacs/doomemacs.
It's a new feature.

**Comment by bo-tato** [comment]
hm including a light scheme that doesn't have faint comment color would be feature request in doomemacs/themes?
but this issue is bug in doom behaviour based on https://github.com/doomemacs/doomemacs/issues/4214 saying you should be able to set doom-theme to 'default?

**Comment by tendernine** [comment]
In my opinion, "the color theme as you request should be compatible with solaire-mode" is a feature requirement for doomemacs/themes.

You are correct. I know that as of #4214, doom-theme could be set to 'default'.

I checked the source code for these comments. I noticed that all the code regarding ui has been rewritten.

Rather than Emacs failing to load 'default', the code for 'default' does not exist.

**Comment by ki827** [comment]
I set the value to nil and it work.

**Comment by hlissner** [comment]
The advice given in #4214 is obsolete. I've updated it to reflect that.

Since https://github.com/doomemacs/doomemacs/commit/f989bf60f00a0da4fdb56e1768c464b52b4dddda, `doom-theme` must be set to `nil` to use the default Emacs theme.

To quote its docstring as of March 11, 2023:

> A symbol representing the Emacs theme to load at startup.
>
> Set to nil to load no theme at all. This variable is changed by
> load-theme.

**Comment by bo-tato** [comment]
great, thanks!
