### ISSUE TITLE
"doom doctor" does not detect missing user-selected fonts

### ISSUE THREAD

**Issue by jaybosamiya** [doomemacs/doomemacs#7055]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

It would be good if `doom doctor` reported that user-selected `doom-font` may not actually be on the system, if it doesn't exist.

### Current behavior

Currently, `doom doctor` prints this output:

```sh
$ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 44 modules
  ✓ Detected 149 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...

Everything seems fine, happy Emacs'ing!
```

Even if the font selected in `config.el` doesn't exist on the system. This means that the user is then greeted with an entirely blank screen on startup.

Running `emacs --debug-init` makes it immediately obvious that it is a font issue, but if a user doesn't know to run `--debug-init` they won't know why they get a blank screen. Worse, with the blank screen, trying to run Doom's sandbox mode and such becomes quite challenging to try to debug things. Maybe the FAQ should mention `--debug-init`? It currently doesn't.

### Steps to reproduce

1. Start from a blank clean Doom Emacs install.
2. Set `doom-font` to a font that doesn't exist on the system (i.e., add `(setq doom-font "THISFONTDOESNOTEXIST")` to `config.el`).
3. Run `emacs`. This gives a blank screen (tested on Linux).
4. Run `doom doctor`. This will show no errors.

### System Information

https://pastebin.com/Zs3NN9Pa

**Comment by hlissner** [comment]
Our doctor doesn't check `doom-font`, and cannot because font libraries are not (and cannot be) loaded in noninteractive Emacs. We can do checks for nerd-icons, because they're in predictable locations and there are shell tools for looking them up.

The *real* problem here, is that when you've set `doom-font` to a font it cannot found, an unrelated bug causes Emacs to show a blank frame. This, I've fixed in 98d753e.

The error that is presented at startup when your font is missing is enough to alert the user to the problem. 98d753e also improves the readability of said error, so I'll consider this resolved. Thanks for bringing it to my attention!
