### ISSUE TITLE
Emacs not working on M1 with `emoji +unicode`

### ISSUE THREAD

**Issue by sangwoo-joh** [doomemacs/doomemacs#7057]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Emacs does not operate with `:ui (emoji +unicode)` on M1 macos Ventura.

### Current behavior

The GUI is not even showing.

### Steps to reproduce

 1. Set `(emoji +unicode)` in `:ui` on M1 macos Ventura.
 2. Open Emacs
 3. Emacs does not operate. The GUI is not even showing so I couldn't capture any `*Message*` buffer or so.
So I had no choice but using `(emoji +unicode)` only for linux: `(:if IS-LINUX (emoji +unicode))`.

 - Doomemacs  commit: e96624926d724aff98e862221422cd7124a99c19
 - Emacs version: GNU Emacs 28.2 (installed via `emacs-plus@28`, not native compilation)
 - The [system information](https://pastebin.com/0GBHfefm) does not contain `:ui (emoji +unicode)` because it was the only way to acquire `M-x doom/info`.

### System Information

https://pastebin.com/0GBHfefm

**Comment by acristoffers** [comment]
I'm on a M1 with macOS 13.2 but I cannot reproduce the issue. What is `emacs-plus@28`? Homebrew (which tap?)?

**Comment by tchadelicard** [comment]
I'm on a M1 Pro running macOS 13.2 and I have the same issue with `emacs-plus@28` installed using Homebrew with the following tap: `d12frosted/emacs-plus`. Changing `(emoji +unicode)` to `(:if IS-LINUX (emoji +unicode)) ` in `~/.doom.d/init.el` also solved the problem on my Doom Emacs installation. I can provide extra logs if needed.

**Comment by acristoffers** [comment]
Yeah, I really cannot reproduce. Just installed it and everything is ok. So maybe the logs of when it fails may help. You can also try to run as `emacs --debug-init` to see if you get anything out.

**Comment by tchadelicard** [comment]
I don't really understand. I've reverted to `(emoji +unicode)` launched Doom Emacs with `emacs --debug-init` and now it works. The fonts were automatically downloaded by Doom Emacs.
