### ISSUE TITLE
org-ditaa-jar-path being overwritten at ditaa code block execution

### ISSUE THREAD

**Issue by newsig** [doomemacs/doomemacs#7062]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

having this in my config.el.

```
  (setq org-ditaa-jar-path "/usr/share/java/ditaa/ditaa-0.11.jar")
```
Nothing should overwrite it i guess ?!

### Current behavior

When executing a ditaa code block in org-mode. the variable **org-ditaa-jar-path** (and **org-ditaa-eps-jar-path**  probably) are overwritten by another value. **_("$HOME/.emacs.d/.local/straight/build-28.2/org-contrib/scripts/ditaa.jar")_**
and obviously an error message shows that the ditaa.jar file isn't found at the late location. and the execution fails.

### Steps to reproduce

1. open doom
2. open org mode buffer
3. execute a ditaa code block

### System Information

https://pastebin.com/9U4Sra0v

**Comment by thefenriswolf** [comment]
Wrap your `(setq org-ditaa-jar-path "/usr/share/java/ditaa/ditaa-0.11.jar")` inside a `(after! org)` block like this:
```
(after! org
  (setq org-ditaa-jar-path "/usr share/java/ditaa/ditaa-0.11.jar")
)
```

This worked for me and I also wrapped my babel config like this!

**Comment by hlissner** [comment]
It must be after org and ob-ditaa loads:

```elisp
(after! (org ob-ditaa)
  (setq org-ditaa-jar-path ...))
```

I'll put some work into simplifying the load order of the Org module's defaults after v3.0, so that only `(after! ob-ditaa ...)` is necessary, but for now, reconfiguring any package X's org-related defaults necessitates `(after! (org X) ...)`.

Thanks for bringing it to my attention, in any case!

**Comment by newsig** [comment]
> It must be after org and ob-ditaa loads:
> 
> ```emacs-lisp
> (after! (org ob-ditaa)
>   (setq org-ditaa-jar-path ...))
> ```
> 
> I'll put some work into simplifying the load order of the Org module's defaults after v3.0, so that only `(after! ob-ditaa ...)` is necessary, but for now, reconfiguring any package X's org-related defaults necessitates `(after! (org X) ...)`.
> 
> Thanks for bringing it to my attention, in any case!

Yep it works !!
Thanks
