### ISSUE TITLE
invalid preview key on the latest consult

### ISSUE THREAD

**Issue by LemonBreezes** [doomemacs/doomemacs#7064]
![image](https://user-images.githubusercontent.com/29102529/216071609-9e3e6930-ef36-4957-a807-4a49f5f5d64e.png)
This block is causing an `Invalid preview key: [67108896]` error because `(key-valid-p (kbd "C-SPC"))` returns nil.

### System Information

https://pastebin.com/L1fVW6d8

**Comment by b40yd** [comment]
this problem need rewrite `:preview-key (kbd "C-SPC")` to `:preview "<C-SPC>"`.

**Comment by akaihola** [comment]
I also see this when typing `C-c f r` in `nix-doom-emacs`:
![kuva](https://user-images.githubusercontent.com/13725/216603657-7e023a21-1b2b-4653-a710-54c92f6444a9.png)

**Comment by garyo** [comment]
I'm seeing it with plain emacs built from trunk with consult and other stuff, so unlikely to be Doom-related.

**Comment by akaihola** [comment]
Is there any work-around I can use in my Emacs configuration file?

**Comment by ghosty141** [comment]
@minad I'm wondering is C-SPC actually invalid or did something change, I also had C-SPC bound in my config (not related to doom emacs though) and currently I too get this error/warning.

**Comment by minad** [comment]
@ghosty141 I updated the key configuration to use the new key format. See also the changelog. I clarified the message in https://github.com/minad/consult/commit/982ec0b0c15c5b01bb7bef7c45f142fcc32ab550.

**Comment by ghosty141** [comment]
I see, so basically it was always invalid and kbd was just very permissive. That clarifies it, thank you.

**Comment by minad** [comment]
No, the difference is that instead of `:preview-key (kbd "C-SPC")` you should just write `:preview-key "C-SPC"`. The value of `(kbd "C-SPC")` is `[67108896]`, which is what you see in the error message.

**Comment by ghosty141** [comment]
Funnily enough I just found that out myself, thanks for clarifying though!
