### ISSUE TITLE
PlantUML does not work with OS installed version

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7071]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I have the following `.org` file:
```
#+STARTUP: showall indent

* Plant UML test

#+BEGIN_SRC plantuml :file ./test_plantuml_seq.png
  title Authentication Sequence

  Alice->Bob: Authentication Request
  note right of Bob: Bob thinks about it
  Bob->Alice: Authentication Response
#+END_SRC

#+RESULTS:
```
When I hit C-c C-c in the SRC block I should get the link to the resulting `./test_plantuml_seq.png` file in the RESULTS block.

### Current behavior

What I actually get is:
`cond: Could not find plantuml.jar at /usr/share/plantuml/plantuml.jar`
even if the file exits and has the correct access rights:
```
ls /usr/share/plantuml/plantuml.jar
.rw-r--r--  8.6M root 10 Mar  2020   /usr/share/plantuml/plantuml.jar
```
and perfectly works:
```
java -jar /usr/share/plantuml/plantuml.jar -version
PlantUML version 1.2020.02 (Sun Mar 01 11:22:07 CET 2020)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 11.0.17+8-post-Ubuntu-1ubuntu222.04
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US
Machine: FAYOL-MULLER-G
PLANTUML_LIMIT_SIZE: 4096
Processors: 16
Max Memory: 16,651,386,880
Total Memory: 1,052,770,304
Free Memory: 1,042,639,488
Used Memory: 10,130,816
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/bin/dot
Dot version: dot - graphviz version 2.43.0 (0)
Installation seems OK. File generation OK
```

NOTE: If I run `M-x plantuml-download-jar`, then everything works fine (apart that filename is `plantuml.1.2022.4.jar` whereas `-version` reports `PlantUML version 1.2023.1`), but I have no idea why/how plantuml mode is getting the path where this commands installs the `.jar` file since it gets it correctly even if I have forced the path in my `config.org` file
```
(after! plantuml-mode
  (setq org-plantuml-jar-path (expand-file-name "/usr/share/plantuml/plantuml.jar"))
  (setq plantuml-default-exec-mode 'jar)
  )
```
NOTE2: I even replaced the `/usr/...` version of the jar with the `M-x ...` installed one and it does not work.
NOTE3: Everything was working fine a few months ago when I last used PlantUML

### Steps to reproduce

0. Install plantuml through your OS (`apt install plantuml`)
1. Open a DoomEmacs configured to use plantuml package (in `init.el`)
2. Copy-paste above `.org` example
3. Hit C-c C-c in SRC block
4. Observe the error

### System Information

https://gist.github.com/liar666/eb865740fc12f389a1253cca901514b5

**Comment by liar666** [comment]
My bad: I had 2 configurations for plantuml: one for plantuml itself and one for org-babel :{

**Comment by newsig** [comment]
`after! plantuml-mode` -> isn't what you need.. because you are using an org buffer not plantuml.. try `after! org`
