### ISSUE TITLE
Emacs-everywhere does not run

### ISSUE THREAD

**Issue by vantu5z** [doomemacs/doomemacs#7072]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Add keybinding from Gnome with command:
`emacsclient --eval "(emacs-everywhere)"`
or
`doom +everywhere`
Run emacs daemon by systemd (autostart).
Hit this keybinding and emacs window should open to enter some text.

### Current behavior

Add keybinding from Gnome with command:
`emacsclient --eval "(emacs-everywhere)"`
or
`doom +everywhere`

Run emacs daemon by systemd (autostart).
Hit this keybinding and nothing happens.

If run command from terminal, it show error:
```
$ doom +everywhere
*ERROR*: Wrong type argument: stringp, nil
```

But if we open emacsclient and evaluate there (emacs-everywhere), or restart emacs systemd service, then all start work as expected.

### Steps to reproduce

Enable emacs systemd service `systemctl --user enable emacs.service` and reboot system.

In terminal run:
`emacsclient --eval "(emacs-everywhere)"`
or
`doom +everywhere`

### System Information

https://pastebin.com/bnXLe78w

**Comment by rbobrowicz** [comment]
I think I'm running into the same issue. Essentially after a recent doom upgrade emacs no longer creates a server socket when running in daemon mode.

With vanilla emacs and a blank `.emacs.d` when running `emacs --fg-daemon` I get:

```
Warning: due to a long standing Gtk+ bug
https://gitlab.gnome.org/GNOME/gtk/issues/221
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Starting Emacs daemon.
```

And a socket is created at `/run/user/1000/emacs/server`.

I did a clean checkout and install of doom master branch and now when I run `emacs --fg-daemon` I get:

```
Warning: due to a long standing Gtk+ bug
https://gitlab.gnome.org/GNOME/gtk/issues/221
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
```

Notice no "Starting Emacs daemon" line at the end, and there is no socket file in the `/run/user/1000/emacs` directory.

I'm on emacs 28.2, master branch, commit e96624926d724aff98e862221422cd7124a99c19

**Comment by rbobrowicz** [comment]
I think I solved my issue it appears it was the same thing as https://github.com/doomemacs/doomemacs/issues/7078

Pinning `transient` and `with-editor` fixes the daemon startup issues for me.

```
(package! transient :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440")
(package! with-editor :pin "391e76a256aeec6b9e4cbd733088f30c677d965b")
```

**Comment by iyefrat** [comment]
Hey, compat was bumped in https://github.com/doomemacs/doomemacs/pull/7075, which should resolve this issue. Feel free to reopen it if the problem persists!
