### ISSUE TITLE
Unable to open any files on fresh doomemacs install on windows11

### ISSUE THREAD

**Issue by ticviking** [doomemacs/doomemacs#7078]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I open any file on a fresh install on windows the file should open without error.

### Current behavior

 I receive a lisp error saying (void-variable transient-base-map)
 
 This is the case when trying to open `.doom.d\init.el` with a completely fresh install.
 
 ``` emacs-lisp
 Debugger entered--Lisp error: (void-variable transient-base-map)
  byte-code("\304\10\305\306\307\310\311\312\313\310\314\315\316\317\320\321\322\317\323\321&\23\210\304\11\305\324\325\10\326\327\330\331\332\333\334\335\336\335\337\340\341\342&\23\210\304\n\305\343..." [transient-base-map transient-map transient-edit-map transient-sticky-map defvar-keymap :doc "Parent of other keymaps used by Transient.\n\nThis i..." "ESC ESC ESC" transient-quit-all "C-g" transient-quit-one "C-q" "C-z" transient-suspend "C-v" transient-scroll-up "C-M-v" transient-scroll-down "<next>" "<prior>" "Top-level keymap used by all transients.\n\nIf you a..." :parent "C-u" universal-argument "C--" negative-argument "C-t" transient-show "?" transient-help "C-h" "C-M-p" transient-history-prev "C-M-n" transient-history-next "Keymap that is active while a transient in is in \"..." "C-x l" transient-set-level "Keymap that is active while an incomplete key sequ..." transient-quit-seq] 20)
  require(transient)
  load-with-code-conversion("c:/Users/awh/.emacs.d/.local/straight/build-28.1/g..." "c:/Users/awh/.emacs.d/.local/straight/build-28.1/g..." nil t)
  global-git-commit-mode()
  funcall(global-git-commit-mode)
  (condition-case e (funcall hook) ((debug error) (signal 'doom-hook-error (list hook e))))
  doom-run-hook(global-git-commit-mode)
  run-hook-wrapped(doom-run-hook global-git-commit-mode)
  (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook))
  (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car (cdr e))) (symbol-name (car (cdr e))) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e)))))
  (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp (car ...)) (symbol-name (car ...)) (car (cdr e))) (car (cdr (cdr e))))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if (symbolp ...) (symbol-name ...) (car ...)) (car (cdr ...)))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- hooks)) (while --dolist-tail-- (let ((hook (car --dolist-tail--))) (condition-case e (let ((doom--hook hook)) (run-hook-wrapped hook #'doom-run-hook)) ((debug doom-hook-error) (if debug-on-error nil (lwarn hook :error "Error running hook %S because: %s" (if ... ... ...) (car ...))) (signal 'doom-hook-error (cons hook (cdr e))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  doom-run-hooks(doom-first-file-hook)
  (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil))
  (if (and after-init-time (not running\?) (or (daemonp) (and (boundp hook) (symbol-value hook)))) (progn (setq running\? t) (doom-run-hooks hook-var) (set hook-var nil)))
  chain-doom-first-file-hook-to-find-file-hook-h(nil t)
  apply(chain-doom-first-file-hook-to-find-file-hook-h (nil t))
  after-find-file(nil t)
  find-file-noselect-1(#<buffer init.el> "~/.doom.d/init.el" nil nil "~/.doom.d/init.el" (0 3462313289))
  find-file-noselect("~/.doom.d/init.el" nil nil t)
  find-file("~/.doom.d/init.el" t)
  funcall-interactively(find-file "~/.doom.d/init.el" t)
  command-execute(find-file)
 ```
 
I was unable to reproduce this behavior on mac.
Interestingly the second time I attempt to `(find-file)` it appears to work. I have a slight hunch that somehow we are trying to use a mode map before it is loaded, but no idea why it would not load in windows but does in mac.

### Steps to reproduce

1. Follow doomemacs windows install instructions
2. Open Emacs
3. Use the open private configuration shortcut on the initial screen `SPC f P`

### System Information

https://pastebin.com/k5qcYRiJ

**Comment by belmarca** [comment]
I also have this error with the latest upgrade:

```
Error (doom-first-file-hook): Error running hook "global-git-commit-mode" because: (void-variable transient-base-map)
```

**Comment by GambolingPangolin** [comment]
For me, `defvar-keymap` is not defined (emacs 28.2 (snap)/Ubuntu 22.04).  I was able to repair my system by downgrading `magit` and `transient`:

```console
cd .emacs.d/.local/straight/repos/with-editor
git fetch origin bbc60f68ac190f02da8a100b6fb67cf1c27c53ab && git checkout bbc60f68ac190f02da8a100b6fb67cf1c27c53ab
cd .emacs.d/.local/straight/repos/transient
git fetch origin c2bdf7e12c530eb85476d3aef317eb2941ab9440 && git switch c2bdf7e12c530eb85476d3aef317eb2941ab9440
rm -r .emacs.d/.local/straight/build-28.2/{with-editor,transient}
doom sync
```

Depending on your setup you may need to track down additional uses of `defvar-keymap`.

**Comment by kubni** [comment]
Confirmed that this happens with Arch Linux, Emacs 28.2, both normal and natively compiled versions. Doing what @GambolingPangolin said, with the addition of --detach parameter to the transient's git switch command (wihout it it wouldn't switch to older commit), fixed it.

**Comment by alwyn** [comment]
Weirdly enough, @GambolingPangolin post, solved my issue with descriptive links showing up in org-roam buffer.

**Comment by twillis** [comment]
a kind person on discord pointed out ...

You can do the same in your packages.el as a short term fix:

(package! transient :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440")
(package! with-editor :pin "391e76a256aeec6b9e4cbd733088f30c677d965b")

I did this before running doom install and it worked, i'm not sure if other order of operations would be the same.

**Comment by easbarba** [comment]
Yep, can confirm, and it's a rather usual issue that occurs almost monthly :/

**Comment by alwyn** [comment]
Does it make sense to use the Emacs 29 git based packages until 29.1 is actually released or will that come with its own set of issues?

**Comment by Nick1296** [comment]
https://github.com/doomemacs/doomemacs/issues/7078#issuecomment-1428775097

This solved the issue for me (Arch, emacs 28.2)

**Comment by temefleet** [comment]
@dan-robertson I think you meant
```emacs-lisp
(package! compat :pin "6f73eac")
```
correct?

**Comment by dschrempf** [comment]
For me it was

```
(package! transient :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440")
(package! with-editor :pin "391e76a256aeec6b9e4cbd733088f30c677d965b")
```

**Comment by dan-robertson** [comment]
@temefleet yeah I did, thanks. I edited my comment above.

**Comment by arun-mani-j** [comment]
```
(package! transient :pin "c2bdf7e12c530eb85476d3aef317eb2941ab9440")
(package! with-editor :pin "391e76a256aeec6b9e4cbd733088f30c677d965b")
```
Added this to packages.el and ran `doom sync -u` fixed it! Thanks!

**Comment by ceolinrenato** [comment]
Looks like they pushed a fix on magit for this already https://github.com/magit/magit/commit/30b0debaaadadec6103a8d7eab92322fd9d30a15

Maybe we could bump magit on https://github.com/doomemacs/doomemacs/blob/master/modules/tools/magit/packages.el ?

**Comment by port19x** [comment]
Also experiencing this issue

**Comment by maikol-solis** [comment]
I have the same issue in termux. Thanks for the solution.

**Comment by brabalan** [comment]
As I needed a more recent version of `compat` for `denote`, I simply did a `(unpin! compat)` in `packages.el`. It’s clearly less elegant than specifying the version, but it worked for me.

**Comment by daraul** [comment]
Where can I see progress on emacs 29+ support? Currently, the readme says it is *not supported*.

**Comment by mopsfelder** [comment]
I did some digging, and after reverting https://github.com/magit/transient/commit/5a966aa857d08894961bae65d579fa79109ff2b3, it solved the problem for me.

Here is what I did on my Doomemacs setup (macOS M1) to solve it temporarily:

```
cd $HOME/.emacs.d/.local/straight/repos/transient
git fetch --unshallow
git revert 5a966aa857d08894961bae65d579fa79109ff2b3
cd $HOME/.emacs.d
./bin/doom purge
./bin/doom sync
./bin/doom build
```

I've reported this to the author of the commit: https://github.com/magit/transient/issues/233

**Comment by tarsius** [comment]
For released versions of Emacs the third-party package `compat` provides `keymap-set` and many other functions from later releases. My packages, including the ones mentioned here, depend on `compat`.

`keymap-set` and related functions were added fairly recently. I have updated my packages to depend on a recent enough version of `compat`.

So it seems the version of `compat` in Doom Emacs has to be updated.

**Comment by tarsius** [comment]
I see this was already discovered above but others continue to suggest pinning `transient` and `with-editor` instead. As a temporary local kludge the latter of course works too (but now you would also have to pin `magit` and probably a few of my other packages.

The proper fix is to unpin `compat`, or to pin it to at least `29.1.1.1`.  There have been important bug fixes and other useful additions since that release, so you might as well update to the latest version `29.1.3.4`.

`compat` release notes can be found at https://lists.sr.ht/~pkal/compat-devel.

**Comment by iyefrat** [comment]
Hey, compat was bumped in https://github.com/doomemacs/doomemacs/pull/7075, which should resolve this issue. Feel free to reopen it if the problem persists!

**Comment by jdelStrother** [comment]
I think I'm continuing to hit this despite running doom at 818efb263fdb5f564e9e37f79bce17d50b559888.

https://pastebin.com/nCSyTAeh

```
Error in post-command-hook (consult--preview-post-command): (doom-hook-error doom-first-file-hook global-git-commit-mode (void-variable transient-base-map))
```

It's working for others, I take it?

**Comment by dschrempf** [comment]
Yes, I do not have any problem since the mentioned commit.

**Comment by hlissner** [comment]
The recent bump should've fixed this, _but_ you may need to rebuild compat and magit (and in that specific order -- with 52d413f44873517a70e1bda050f9011d9c5a839c, I'm hoping these compilation-order issues like that won't bite us again). You can do this selectively with:

```sh
cd ~/.config/emacs/.local/straight
# I've added transient and with-editor for good measure
rm -rf {build-*,repos}/{compat,magit,transient,with-editor}
doom sync
```

Or simply rebuild all packages by running `$ doom build`.

**Comment by jdelStrother** [comment]
Ahh, thanks - think that must have been my missing step. `doom sync` on its own wasn't doing the trick.

**Comment by mopsfelder** [comment]
Now, everything is working again with Doomemacs.
Thank you, @hlissner and @tarsius!

**Comment by alanmaciel** [comment]
Confirmed this happens in Pop! OS 22.04 LTS, Doom Emacs 28.2, @GambolingPangolin procedure fixed it. :+1:
