### ISSUE TITLE
`emacs-cython-mode` commit SHA is incorrect

### ISSUE THREAD

**Issue by danieldk** [doomemacs/doomemacs#7081]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I run `doom upgrade` it should finish successfully.

### Current behavior

When I run `doom upgrade` with Cython mode enabled, it fails with the following error:

```
      > Cloning emacs-cython-mode...
    ✓ (146/194) emacs-cython-mode: 3e47905 -> b201559 [1 commit(s)]
        ERROR: Couldn't collect commit list because: fatal: bad object b2015596b38df4b7b2978d87385da20d69e4e822

    x The package manager threw an error
    x Last 16 lines of straight's error log:
      [Return code: 0]
```

GitHub also doesn't seem to think that this is an existing commit: https://github.com/cython/emacs-cython-mode/commit/b2015596b38df4b7b2978d87385da20d69e4e822

### Steps to reproduce

Enable Cython mode:

```
       (python +cython +pyenv +lsp +pyright) ; beautiful is better than ugly
```

and run `doom upgrade`.

### System Information

https://gist.github.com/danieldk/9aebf71549d6ff6231f7caa48afb22ed

**Comment by hlissner** [comment]
I've bumped the package in dbf8f74 to https://github.com/cython/emacs-cython-mode/commit/3e4790559d31, which should resolve this issue. Thanks for letting me know!
