### ISSUE TITLE
missing function zmq-send-encoded and zmq-recive-decoded cause org export failed

### ISSUE THREAD

**Issue by zhyzky** [doomemacs/doomemacs#7086]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Try to export org file, which contains a python code block. the ox package seems to refer to undefined function zmq-send-encoded and zmq-recieve-decoded.
Maybe these two functions are defined in old emacs-zmq repos. But clearly their missing breaks the export process.

### Current behavior

export to file with no errors

### Steps to reproduce

open a org file contains a python code block
run ox-export to anything else
there would be error msg about the missing function

### System Information

https://pastebin.com/EYWvr9a8

**Comment by mnick** [comment]
The fix that works for me is to pin jupyter to the correct version

```
(package! jupyter :pin "bc3b78be4333bb7a51e262018f7e6dcded621c41")
```

**Comment by hlissner** [comment]
The source of this issue: https://github.com/nnicandro/emacs-jupyter/issues/433

A fix will be up shortly. The workaround is to un or re-pin `emacs-jupyter`, as @mnick suggested.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/7c1c1f52bb12761b1a51482a6db563367a5b7eeb, this should be resolved. Let me know if that isn't the case and I'll reopen this.
