### ISSUE TITLE
Can't install or sync, Could not resolve host: github.com

### ISSUE THREAD

**Issue by ElnuDev** [doomemacs/doomemacs#7089]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Doom should sync/install correctly with no errors.

### Current behavior

When I try to sync or install, Doom fails and says that it "Could not resolve host: github.com" almost as if I don't have internet access, but if I try to run the Git commands manually there is no issue and I have no problems accessing GitHub.

When I run `doom sync` on my install, pulled with the latest commit of Doom:

```
> Synchronizing "default" profile...
  x The package manager threw an error
  x Last 16 lines of straight's error log:
    $ cd /home/elnu/.emacs.d.old/.local/straight/repos/el-get/
    $ git submodule update --init --recursive
    [Return code: 0]
    $ cd /home/elnu/.emacs.d.old/.local/straight/repos/
    $ git clone --origin origin --no-checkout https\://github.com/emacs-straight/emacsmirror-mirror.git /home/elnu/.emacs.d.old/.local/straight/repos/emacsmirror-mirror/ --depth 1 --single-branch --no-tags
    Cloning into '/home/elnu/.emacs.d.old/.local/straight/repos/emacsmirror-mirror'...
    fatal: unable to access 'https://github.com/emacs-straight/emacsmirror-mirror.git/': Could not resolve host: github.com
    [Return code: 128]
    $ cd /home/elnu/.emacs.d.old/.local/straight/repos/
    $ git clone --origin origin --no-checkout https\://github.com/emacs-straight/emacsmirror-mirror.git /home/elnu/.emacs.d.old/.local/straight/repos/emacsmirror-mirror/ --no-single-bran
ch
    Cloning into '/home/elnu/.emacs.d.old/.local/straight/repos/emacsmirror-mirror'...
    fatal: unable to access 'https://github.com/emacs-straight/emacsmirror-mirror.git/': Could not resolve host: github.com
    [Return code: 128]
    $ cd /home/elnu/.emacs.d.old/.local/straight/repos/emacsmirror-mirror/
    $ git branch -r
    [File error while Setting current directory]
  ! Wrote extended straight log to ~/.emacs.d.old/.local/logs/cli.doom.230219102340.6062.error
  ! Script was abruptly aborted, leaving Doom in an incomplete state!
  - Run 'doom sync' to repair it.
  ✓ Finished in 6.31642s
```

When I run `doom install` on a new clone:

```
Installing Doom Emacs!

- Skipping ~/.doom.d/ (already exists)
  - Skipping init.el (already exists)
  - Skipping config.el (already exists)
  - Skipping packages.el (already exists)
Generate an envvar file? (see `doom help env` for details) (y or n) y
> Generating envvars file
  ✓ Generated ~/.emacs.d/.local/env
Installing plugins
> Installing straight...
x The package manager threw an error
x Last 16 lines of straight's error log:
  $ cd /home/elnu/.emacs.d/.local/straight/repos/
  $ git clone --origin origin --no-checkout https\://github.com/melpa/melpa.git /home/elnu/.emacs.d/.local/straight/repos/melpa/ --depth 1 --single-branch --no-tags
  Cloning into '/home/elnu/.emacs.d/.local/straight/repos/melpa'...
  fatal: unable to access 'https://github.com/melpa/melpa.git/': Could not resolve host: github.com
  [Return code: 128]
  $ cd /home/elnu/.emacs.d/.local/straight/repos/
  $ git clone --origin origin --no-checkout https\://github.com/melpa/melpa.git /home/elnu/.emacs.d/.local/straight/repos/melpa/ --no-single-branch
  Cloning into '/home/elnu/.emacs.d/.local/straight/repos/melpa'...
  fatal: unable to access 'https://github.com/melpa/melpa.git/': Could not resolve host: github.com
  [Return code: 128]
  $ cd /home/elnu/.emacs.d/.local/straight/repos/melpa/
  $ git branch -r
  [File error while Setting current directory]
Opening output file: No such file or directory, /home/elnu/.emacs.d/.local/logs/cli.doom.230219101752.5323.error
```

I've also made [a Reddit post](https://www.reddit.com/r/DoomEmacs/comments/11547su/cant_sync_config_could_not_resolve_host_githubcom/) regarding the issue. I hope this isn't a duplicate; I looked around but I couldn't find any other cases of this "Could not resolve host: github.com" error.

### Steps to reproduce

Sync/install Doom Emacs.

### System Information

https://gist.github.com/ElnuDev/8e2301dd1885f58bdc98782d06e77337

**Comment by god464** [comment]
This does not seem to be a Doom Emacs problem. Perhaps you should check if your network can access Github.

**Comment by ElnuDev** [comment]
As I said, I have no problems accessing GitHub, and if I manually run the Git commands which it is failing on there are no problems. That's what makes this issue so weird.

**Comment by god464** [comment]
> As I said, I have no problems accessing GitHub, and if I manually run the Git commands which it is failing on there are no problems. That's what makes this issue so weird.

I also had this problem when I installed it in PowerShell. I can run the git command but can not run `doom install` . Considering my country's network problem, I set up shell proxy and successfully resolved.

**Comment by ElnuDev** [comment]
Switched my DNS to 1.1.1.1 and it fixed the issue. Would also explain why I've had pages not load intermittently... thanks for the help!
