### ISSUE TITLE
(wrong-type-argument stringp nil) error when browsing project with SPC-p-.

### ISSUE THREAD

**Issue by tekpriest** [doomemacs/doomemacs#7093]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I use `SPC-p-.`, it should allow me browse current project.

### Current behavior

instead it shows error `wrong-type-argument stringp, nil`
checking the `*Messages*` window shows `file-truename: Wrong type argument: stringp, nil`

### Steps to reproduce

1. Open Emacs
2.  Open the private configuration with `SPC-f-p`
3. Add the `~/.doom.d/` folder to projects with `SPC-p-a`
4. Browse files with `SPC-p-.`

### System Information

https://pastebin.com/AWHPYGAZ

**Comment by hlissner** [comment]
Please provide [a backtrace](https://discourse.doomemacs.org/how2backtrace) of the error.

**Comment by hlissner** [comment]
Nevermind, I found the issue. As of 45d25af this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
