### ISSUE TITLE
Case sensitive completion at org-tags-view start

### ISSUE THREAD

**Issue by vantu5z** [doomemacs/doomemacs#7101]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I run **M-x org-tags-view** it should ask me for tag and provide case insensitive completion.

### Current behavior

When I run **M-x org-tags-view** it ask me for tag and provide case sensitive completion.

### Steps to reproduce

1. Run **M-x org-tags-view**
2. Try to type tag and look for completion

### System Information

https://pastebin.com/YvE6EXnS

**Comment by hlissner** [comment]
This doesn't appear to be a bug. Org [hard-codes tag case-sensitivity into `org-tags-completion-function` [here](https://github.com/emacs-straight/org-mode/blob/main/lisp/org.el#L11810). This doesn't offer us any way to customize it, besides rewriting the function:

```lisp
;; add to $DOOMDIR/config.el
(defadvice! org-tags-completion-function (string _predicate &optional flag)
  :override #'org-tags-completion-function
  (let ((completion-ignore-case t)
	(confirm (lambda (x) (stringp (car x))))
	(prefix ""))
    (when (string-match "^\\(.*[-+:&,|]\\)\\([^-+:&,|]*\\)$" string)
      (setq prefix (match-string 1 string))
      (setq string (match-string 2 string)))
    (pcase flag
      (`t (all-completions string org-last-tags-completion-table confirm))
      (`lambda (assoc string org-last-tags-completion-table)) ;exact match?
      (`nil
       (pcase (try-completion string org-last-tags-completion-table confirm)
	 ((and completion (pred stringp))
	  (concat prefix
		  completion
		  (if (and org-add-colon-after-tag-completion
			   (assoc completion org-last-tags-completion-table))
		      ":"
		    "")))
	 (completion completion)))
      (_ nil))))
```

Since this is not a Doom issue I will close this, but I suggest bringing this up upstream, to the Org project instead.
