### ISSUE TITLE
Symbol’s function definition is void: magit-menu-item

### ISSUE THREAD

**Issue by kostajh** [doomemacs/doomemacs#7111]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

<code>spc g g</code> or `magit-status` opens magit status.

### Current behavior

```
Source file ‘/Users/kostajh/.emacs.d/.local/straight/build-28.2/magit/magit-diff.el’ newer than byte-compiled file; using older file
byte-code: Symbol’s function definition is void: magit-menu-item
```

### Steps to reproduce

Seeing this today after running `doom upgrade` and restarting Emacs. I've removed magit from ~/.emacs.d/.local/straight/repos/magit and re-run `doom sync`; I also see that magit-menu-item is still defined in magit's code[0], so I don't really know what's going on.
[0] https://github.com/magit/magit/blob/deb10e984e16201182b0569f7df7d30ec3b8afa9/lisp/magit-section.el#L602 

### System Information

https://pastebin.com/yBirkzgP

**Comment by lairez** [comment]
`doom build` solved the issue for me

**Comment by kostajh** [comment]
Aha, for me as well. I guess this could be closed, unless there is some adjustment to make with `doom upgrade` or `doom sync`.
