### ISSUE TITLE
`doom-first-input-hook`, `doom-first-file-hook`, `doom-first-buffer-hook` "permenant-local" misspelled

### ISSUE THREAD

**Issue by Jacobfaib** [doomemacs/doomemacs#7123]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

defcustoms [`doom-first-input-hook`](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-start.el#L8), [`doom-first-file-hook`](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-start.el#L14), and [`doom-first-buffer-hook`](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-start.el#L20) all have the `local:` field set to `permenant-local`. "permenant" is misspelled and should be "permanent". Indeed looking through `C-h f defcustom RET` I find:
```
defcustom is a Lisp macro in ‘custom.el’.

(defcustom SYMBOL STANDARD DOC &rest ARGS)

...
:local  If VALUE is t, mark SYMBOL as automatically buffer-local.
        If VALUE is ‘permanent’, also set SYMBOL’s ‘permanent-local’
        property to t.
...
```
Note I don't know that this actually breaks anything.

### Current behavior

N/A

### Steps to reproduce

N/A

### System Information

N/A

**Comment by hlissner** [comment]
Good catch! This is now fixed in 8d578ca. Thanks for letting me know!
