### ISSUE TITLE
treemacs showing in mini buffer below instead of sidebar

### ISSUE THREAD

**Issue by osfe** [doomemacs/doomemacs#7126]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Usually treemacs is showing on the left side of the window. 

### Current behavior

Since I upgraded to 2 days ago, treemacs is showing below like a mini buffer 
https://imgur.com/a/oxG5PL1

### Steps to reproduce

1. open emacs
2. open c++ file
3. M-x treemacs

### System Information

https://pastebin.com/kT36Zwt1

**Comment by bittopaz** [comment]
I'm having the same issue.

**Comment by JonathanReeve** [comment]
I have no idea what I'm doing, but I guessed that this might have something to do with 1eb3fd3 ("bump: :ui") and so I rolled back and reinstalled from that point, but it didn't fix it. If anyone else has any ideas, let me know.

**Comment by ashton** [comment]
@JonathanReeve Yes, this bump brough a lot of updates of treemacs, one of them, is a change in how treemacs opens a popup window: https://github.com/Alexander-Miller/treemacs/commit/79927691bb2aba5b50161deb30b1a892489f31fa

**Comment by Dadams2** [comment]
Also having this issue

**Comment by Dadams2** [comment]
I have a proper fix now. 

adding
```
  (set-popup-rule! "^ ?\\*Treemacs" :ignore t)
```
to the `:config` section of `modules/ui/treemacs/config.el` fixes things. It would appear that seeing treemacs switched to using `display-buffer` it is now subject to the popup autoload settings which by default sets it to be a small buffer at the bottom. Neotree works because it has a similar ignore rule in its config. 

I haven't submitted a PR to doom before but would be happy to do so

**Comment by myrgy** [comment]
seems to be related to https://github.com/doomemacs/doomemacs/issues/7119

**Comment by myrgy** [comment]
Thank you @Dadams2 ! I put `(set-popup-rule! "^ ?\\*Treemacs" :ignore t)` in my `.doom.d/config.el`

**Comment by mattsawyer77** [comment]
AFAICT, this is the breaking change in treemacs: https://github.com/Alexander-Miller/treemacs/pull/971 It seems to have caused vars like `treemacs-position` to become ignored. 

FWIW this is my current workaround, working with the latest treemacs:

```elisp
(after! treemacs
  ;; (irrelevant preferences elided)
  (setq treemacs-position 'left)
  (setq treemacs-width 40)
  ;; workaround here:
  (set-popup-rule! "^ \\*Treemacs"
    :side treemacs-position
    :window-width treemacs-width)
  )
```

**Comment by osfe** [comment]
Thank you to all of you !! treemacs is now showing up on the left side on my window :)
I used @mattsawyer77 fix...
By the way, do you this is gonna be fixed or we'll just have to configure it by hand now ?
