### ISSUE TITLE
Could not find package jet. on `doom upgrade`

### ISSUE THREAD

**Issue by mewfree** [doomemacs/doomemacs#7128]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I run `doom upgrade`, I expect the upgrade process to run

### Current behavior

When I run `doom upgrade`,  I get an error message instead:

```
Message: Could not find package jet. Updating recipe repositories: (org-elpa melpa nongnu-elpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this
    Backtrace:
      (error "Could not find package %S. Updating recipe repositories: %S wi...
      (if (straight--package-built-in-p melpa-style-recipe) (throw '--cl-blo...
      (or (straight-recipes-retrieve melpa-style-recipe nil cause) (if (stra...
      (if recipe-specified-p melpa-style-recipe (or (straight-recipes-retrie...
      (let* ((recipe-specified-p (listp melpa-style-recipe)) (full-melpa-sty...
      (or (and (symbolp melpa-style-recipe) (gethash (symbol-name melpa-styl...
      (catch '--cl-block-straight--convert-recipe-- (if (memq melpa-style-re...
      (straight--convert-recipe jet nil)
      (let ((recipe (straight--convert-recipe (or (straight--get-overridden-...
      (catch '--cl-block-straight-use-package-- (let ((recipe (straight--con...
      (straight-use-package jet no-clone)
      (straight-register-package jet)
```

### Steps to reproduce

run `doom upgrade`

### System Information

https://pastebin.com/b92Wf43W

**Comment by elken** [comment]
@ericdallo ?

**Comment by ericdallo** [comment]
That's odd, the package is on both melpa and melpa-stable, maybe the sync with melpa didn't work or something?

**Comment by elken** [comment]
I remember someone else having this issue before, that's the only thing I can think of but pretty sure the first thing doom does is update.

Maybe needs a straight folder clear-out @hlissner ?

**Comment by deheras** [comment]
@elken I just had this issue but with `flycheck-eglot` and a straight folder clear-out worked for me.

**Comment by mewfree** [comment]
Thanks, clearing out my `straight` folder worked.

Not sure what to do with the issue?

**Comment by shrik450** [comment]
Happened to me too, and clearing the straight folder worked. Any idea why it failed, though?

**Comment by nickmurison** [comment]
Just had this happen on two separate installs as well. Running `rm -rf ~/.emacs.d/.local/straight/*` followed by `doom sync` fixed it in both cases.

**Comment by ruslanasa** [comment]
Running rm -rf ~/.emacs.d/.local/straight/* followed by doom sync fixed my issue
