### ISSUE TITLE
Replying to a message in mu4e causes emacs to freeze / hang

### ISSUE THREAD

**Issue by JonathanReeve** [doomemacs/doomemacs#7133]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expect Emacs not to hang when I try to compose an email reply. 

### Current behavior

From any message in mu4e, triggering a reply causes emacs to hang entirely, becoming totally unresponsive. It doesn't respond to Ctrl+G, or anything else. I can stop the process with `kill -SIGUSR2 <pid>` and the pid for emacs, which returns traces like this (they're different every time I kill the process): 

```
Debugger entered--entering a function:
* put-text-property(480 1980 fontified nil)
  jit-lock-fontify-now(480 1980)
  jit-lock-function(480)
  redisplay_internal\ \(C\ function\)()
  recursive-edit()
  debug(lambda)
* put-text-property(207 1707 fontified nil)
  jit-lock-fontify-now(207 1707)
  jit-lock-function(207)
  redisplay_internal\ \(C\ function\)()
```

```
Debugger entered--entering a function:
* #f(compiled-function () #<bytecode 0x224abfe4452e83>)()
  file-name-sans-extension("1677909917.c0b552d026d119d4.jon-laptop:2,DS")
  org-element-org-data-parser()
  org-element--parse-to(1)
  org-element--cache-verify-element((paragraph (:begin 1 :end 436 :contents-begin 1 :contents-end 436 :post-blank 0 :post-affiliated 1 :mode top-comment :granularity element :cached t :parent (section (:begin 1 :end 2268 :contents-begin 1 :contents-end 2267 :robust-begin 1 :robust-end 2265 :post-blank 1 :post-affiliated 1 :mode first-section :granularity element :cached t :parent (org-data (:begin 1 :contents-begin 1 :contents-end 2267 :end 2268 :robust-begin 3 :robust-end 2265 :post-blank 1 :post-affiliated 1 :path "/home/jon/Mail/columbia/[Gmail]/Drafts/cur/1677909..." :mode org-data :CATEGORY "1677909917.c0b552d026d119d4" :cached t)))))))
  org-element-at-point()
  org-adaptive-fill-function()
  fill-match-adaptive-prefix()
  fill-context-prefix(96 140)
  #<subr adaptive-wrap-fill-context-prefix>(96 140)
  funcall(#<subr adaptive-wrap-fill-context-prefix> 96 140)
  (let ((adaptive-wrap-extra-indent (+word-wrap--calc-extra-indent beg))) (funcall fn beg end))
  +word-wrap--adjust-extra-indent-a(#<subr adaptive-wrap-fill-context-prefix> 96 140)
  apply(+word-wrap--adjust-extra-indent-a #<subr adaptive-wrap-fill-context-prefix> (96 140))
  adaptive-wrap-fill-context-prefix(96 140)
  adaptive-wrap-prefix-function(96 1596)
  #f(compiled-function (fun) #<bytecode 0x19a2f352921943fd>)(adaptive-wrap-prefix-function)
  jit-lock--run-functions(96 1596)
  jit-lock-fontify-now(96 1596)
  jit-lock-function(96)
  redisplay_internal\ \(C\ function\)()
```

Something's apparently in some kind of infinite loop or recursive something, related to fontification.

### Steps to reproduce

1. Open a message in mu4e
2. Press `R` to trigger a reply
3. Note that emacs has frozen / hung, and has become totally unresponsive

### System Information

https://pastebin.com/Qn50DmAA

**Comment by JonathanReeve** [comment]
This is probably related to global-word-wrap-mode, since running `M-x global-word-wrap-mode` also causes Emacs to freeze.

**Comment by peterhoeg** [comment]
Ref the upstream bug report, I'm seeing this on doom too, but word-wrap-mode isn't related. The only way to be sure not to hit this is to disable font locking.

**Comment by peterhoeg** [comment]
I have not had this issue since I started using this:
```
(add-hook 'org-msg-edit-mode-hook
          (lambda ()
            (setq org-font-lock-keywords (delq 'gnus-message-citation-keywords org-font-lock-keywords))))
```

**Comment by JonathanReeve** [comment]
I'm not seeing this issue any more either, but for me I had to remove and recreate my maildir, regenerate the mu index, downgrade to mu 1.8, upgrade doom and all its packages, and switch to using nix-doom-emacs, which has certain packages pinned for compatibility. One of those things fixed it for me. Not such which. I'll close this issue.
