### ISSUE TITLE
first tab-new after fresh launch does not work

### ISSUE THREAD

**Issue by pennae** [doomemacs/doomemacs#7139]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`tab-new`, `find-file-other-tab` etc should always work and not fail if they're the first tab action run after a fresh launch of emacs.

### Current behavior

when launching a fresh emacs, with or without a file to edit, the first `tab-new` or `find-file-other-tab` do not work. neither creates a new tab on the first run, `find-file-other-tab` will replace the current buffer. after this initial failure things start working as expected.

this seems to be caused by d12b0ebc80dc2e14b5bcfad7f00f0cc07d3f2841. specifically removing the `+workspaces-load-tab-bar-data-from-file-h` call from `tab-bar-mode-hook` fixes the problem, but haven't checked whether it causes new problems. it probably does.

### Steps to reproduce

1. open emacs
2. open some file
3. `find-file-other-tab` some other file
4. observe the current buffer being replaced, but no new tab being created

### System Information

https://pastebin.com/EgJzi9C7

**Comment by roife** [comment]
I have fixed it by adding a check before loading configs in #7476

If you use `tab-bar-mode`, I recommend enabling `tab-bar-mode` in your configs.
