### ISSUE TITLE
doom-guess-mode-h doesn't preserve evil state

### ISSUE THREAD

**Issue by daanturo** [doomemacs/doomemacs#7141]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

In a `fundamental-mode` buffer, `M-x save-buffer` doesn't have to change `evil-state`.

### Current behavior

While in `evil-insert-state`, `save-buffer` makes Emacs goes to `evil-normal-state` because of `doom-guess-mode-h`.

### Steps to reproduce

1. Open an empty file without extension, such as `/tmp/test`
2. Enter insert state
3. Type anything there so that saving hooks are triggered
4. `M-x save-buffer`

### System Information

https://pastebin.com/AMNHd4SK

**Comment by hlissner** [comment]
I can reproduce this; I'll look into a fix. In the meantime, does this fix the issue for you?

```elisp
;; add to $DOOMDIR/config.el
(defadvice! +evil--restore-state-after-guess-mode-a (fn &rest args)
  :around #'doom-guess-mode-h
  (evil-save-state (apply fn args)))
```

**Comment by daanturo** [comment]
> I can reproduce this; I'll look into a fix. In the meantime, does this fix the issue for you?
> 
> ```emacs-lisp
> ;; add to $DOOMDIR/config.el
> (defadvice! +evil--restore-state-after-guess-mode-a (fn &rest args)
>   :around #'doom-guess-mode-h
>   (evil-save-state (apply fn args)))
> ```

Thank you, that works.

**Comment by hlissner** [comment]
As of adb125f this should be fixed. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
