### ISSUE TITLE
`C-<delete>` does not run `kill-word`.

### ISSUE THREAD

**Issue by gdonald** [doomemacs/doomemacs#7150]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I hit `C-<delete>` I expect `kill-word` to run.

### Current behavior

When I hit `C-<delete>` `evil-delete-char` runs instead of `kill-word`. 

### Steps to reproduce

1. open emacs and open a file.
2. inside the buffer move the cursor to a word.
3. hit `C-<delete>` and notice how only a single character to the right of the cursor is deleted, not the whole word.
4. hit `M-x kill-word` and notice how the whole word is deleted as expected.

`SPC h k C-<delete>` says `evil-delete-char` is bound to `C-<delete>`.

`SPC h f kill-word` shows one entry: `kill-word (C-<delete>)`.  Inside that one entry it says `C-<delete>` belongs to `global-map`, and there's no mention of `evil-delete-char`.

Adding `(unbind-key "C-<delete>" global-map)` to my `config.el` does not prevent `evil-delete-char` from running when I hit `C-<delete>`.

### System Information

https://pastebin.com/fXWf9NFq

**Comment by kmarker1101** [comment]
I looked at this a little bit today. If you want to delete the word, M-d seems to do the trick.

**Comment by gdonald** [comment]
`M-d` is bound to `evil-multiedit-match-and-next` and does not do the trick for me.

**Comment by gdonald** [comment]
I gave up on Doom and went back to managing my own config.  Closing.
