### ISSUE TITLE
doom doesn't honor vim 's' command

### ISSUE THREAD

**Issue by hazayan** [doomemacs/doomemacs#7155]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When you invoke the `s` command in normal mode, it should delete the character at the cursor's position and switch to insert mode.

### Current behavior

Instead, invoking the `s` command prints `2>` in the inferior mode, no character is deleted and it doesn't switch to insert mode.

### Steps to reproduce

1. open a text file with doom-emacs
2. position the cursor inside a line
3. switch to normal mode
4. press `s`

### System Information

https://pastebin.com/hNgAFkWG

**Comment by hlissner** [comment]
This is intention, as mentioned [in our FAQ](https://github.com/doomemacs/doomemacs/blob/develop/docs/faq.org#the-s-and-s-keys-dont-behave-like-they-do-in-vimevil-1307) and [the evil module's README](https://github.com/doomemacs/doomemacs/tree/develop/modules/editor/evil#restoring-old-substitution-behavior-on-ss).
