### ISSUE TITLE
Cyrillic character "Я" is rendered with a wrong font

### ISSUE THREAD

**Issue by koiuo** [doomemacs/doomemacs#7167]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`config.el`
```
(setq doom-font (font-spec :family "IBM Plex Mono" :size 10.0 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 10.0))
```

`init.el` does not enable `unicode` module
```
       :ui
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       modeline          ; snazzy, Atom-inspired modeline, plus API vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       workspaces        ; tab emulation, persistence & separate workspaces
```

### Current behavior

All the characters from cyrillic script rendered with the configured font _IBM Plex Mono_ except a single character Я (only the capital Я).

```
             position: 32 of 70 (44%), column: 31
            character: я (displayed as я) (codepoint 1103, #o2117, #x44f)
              charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0x044F
               script: cyrillic
               syntax: w 	which means: word
             category: .:Base, L:Strong L2R, Y:2-byte Cyrillic, c:Chinese, h:Korean, j:Japanese, y:Cyrillic
             to input: type "z" with ukrainian-computer input method
          buffer code: #xD1 #x8F
            file code: #xD1 #x8F (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    ftcrhb:-IBM -IBM Plex Mono-normal-normal-normal-*-18-*-*-*-m-0-iso10646-1 (#x237)

Character code properties: customize what to show
  name: CYRILLIC SMALL LETTER YA
  old-name: CYRILLIC SMALL LETTER IA
  general-category: Ll (Letter, Lowercase)
  decomposition: (1103) ('я')

There are text properties here:
  ws-butler-chg        chg
```

```
             position: 69 of 70 (97%), column: 0
            character: Я (displayed as Я) (codepoint 1071, #o2057, #x42f)
              charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0x042F
               script: cyrillic
               syntax: w 	which means: word
             category: .:Base, L:Strong L2R, Y:2-byte Cyrillic, c:Chinese, h:Korean, j:Japanese, y:Cyrillic
             to input: type "Z" with ukrainian-computer input method
          buffer code: #xD0 #xAF
            file code: #xD0 #xAF (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    ftcrhb:-unknown-file-icons-normal-normal-normal-*-18-*-*-*-*-0-iso10646-1 (#x26)

Character code properties: customize what to show
  name: CYRILLIC CAPITAL LETTER YA
  old-name: CYRILLIC CAPITAL LETTER IA
  general-category: Lu (Letter, Uppercase)
  decomposition: (1071) ('Я')

There are text properties here:
  ws-butler-chg        chg
```

The font is _absolutely_ not the issue, I verified and it has the corresponding glyph. Also I can reproduce this with any other font on my system.

### Steps to reproduce

1. Open emacs scratch buffer
2. paste in the following
```
абвгдеєжзиіїйклмнопрстуфхцчшщьюя
АБВГДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯ
```
3. Notice how the last char of the second line has different font than the others
4. `M-x` `describe-char` to confirm the font is indeed different

### System Information

https://pastebin.com/ApTENkNp

**Comment by koiuo** [comment]
Currently worked around by adding this to my `config.el` AND _reevaluating config_ (`SPC h r r`) while emacs window is running. For some reason it doesn't work on startup.

```
(set-fontset-font "fontset-default" #x042F       ;; UTF-8 Я
                  "IBM Plex Mono" nil 'prepend)
```

**Comment by vlnn** [comment]
I can confirm the problem with Я character across the wide range of fonts (Iosevka, Fira Mono etc)

**Comment by degiz** [comment]
I can confirm the same issue.

**Comment by degiz** [comment]
@koiuo @vlnn 

As I've learned [here](https://github.com/doomemacs/doomemacs/issues/3298), the workaround that works on startup looks like that:
```elisp
(add-hook! 'after-setting-font-hook
  (set-fontset-font "fontset-default" #x042F       ;; UTF-8 Я
                    "Avenir Next Cyr" nil 'prepend))
```

**Comment by shroomist** [comment]
this is painful, but workaround helped, thanks.
