### ISSUE TITLE
Projectile search via vertico and ripgrep was broken in a recent commit

### ISSUE THREAD

**Issue by or** [doomemacs/doomemacs#7172]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I use vertico and projectile, I can use `+default/search-project` to search for matching lines in the files of the project.

### Current behavior

When I use vertico and projectile and then invoke `+default/search-project` in a project, I don't see any matches, no matter what pattern I provide, and I couldn't find any errors.

I've bisected recent changes and found that this seems to be broken in https://github.com/doomemacs/doomemacs/commit/e5dbd4e8b1c14a608cad36b3cbff88db3228f42c, and indeed if I revert just that commit, then it works as expected again.

### Steps to reproduce

1. In `init.el` uncomment `vertico`, comment out `helm`, `ido`, `ivy`.
2. Open Emacs
3. Open some project (in my case indicated by a `.projectile` file in the directory)
4. Invoke `+default/search-project`

### System Information

https://pastebin.com/SMy4TWTX

**Comment by sdvcrx** [comment]
Have you tried running the command `doom sync -u` (to update consult package) ?

**Comment by or** [comment]
Ok, embarrassingly the problem here was that I used a wrapper around ripgrep in my path. I didn't connect that while debugging the issue.

The reason it stopped working is that now paths are added to the end of the `rg` call, which ends up being a `.`, which confused my wrapper.

Everything works as expected, so this can be closed.
