### ISSUE TITLE
cannot open load file: no such file or directory, neotree

### ISSUE THREAD

**Issue by MATIASARAUJ0** [doomemacs/doomemacs#7182]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When i type neotree on M-x neotree, there should be a "neotree" file.

### Current behavior

When i type neotree on M-x, there is only "neotree-..." files.
if i use these files, this is the answer.
-cannot open load file: no such file or directory, neotree

### Steps to reproduce

1.Open Emacs
2.Activate neotree on init.el.
3.M-x doom/reload
4.doom sync

### System Information

https://pastebin.com/uJN7e6dm

**Comment by l3all** [comment]
I have the same exact issue

**Comment by tuananh131001** [comment]
same with me
