### ISSUE TITLE
Unicode font does not change

### ISSUE THREAD

**Issue by M0hanad0** [doomemacs/doomemacs#7186]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I change `doom-unicode-font` to `"Amiri"` in my config, evaluate it, and then reload the font, then change it back to `"Symbola"` applying it use the same previous steps, arabic text is will be rendered using `"Symbola"`.

### Current behavior

Arabic text is rendered using the `"Amiri"` font.

Tried to change the `doom-unicode-font` to fonts other than `"Symbola"`. Didn't work.
Tried going back to a previous commit using git. Didn't work. 

![2023-04-08_01-34](https://user-images.githubusercontent.com/41490275/230687080-6c9772b1-12ef-48ae-bea2-405e8999fcfd.png)

### Steps to reproduce

1. Change `doom-unicode-font` to `"Amiri"`
2. Evaluate config
3. reload font using `doom-reload-font`
4. Change it back to any other font
5. Evaluate config
6. reload font using `doom-reload-font`

### System Information

https://pastebin.com/hMrq6vnV

**Comment by vancleve** [comment]
So this seems to be a problem with `doom-reload-font`? Do you get the right behavior by restarting emacs after the config change?

**Comment by vancleve** [comment]
I think its because Symbola doesn't have many Arabic characters:

fileformat.info/info/unicode/font/symbola/list.htm

https://everythingfonts.com/unicode/arabic

**Comment by vancleve** [comment]
It seems have these:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/1442334/230973665-b1061592-c265-4c49-814f-4fca8af8739e.png">
So you can see if those show up correctly as Symbola.

**Comment by M0hanad0** [comment]
Actually the font used to work before, but I don't know what happened that broke it.
Here is a screenshot from a previous date:
![An Example of it working](https://user-images.githubusercontent.com/41490275/230998981-7b20cb77-58b1-4eda-9d91-a7215248f461.png)

After further investigation I found that org-mode buffers display headings in _Symbola_ but the rest of the text gets displayed in _Amiri_.
![Headings vs Normal text](https://user-images.githubusercontent.com/41490275/230999443-5c67f3d9-2043-426b-941a-263e9e0f923d.png)

**Comment by M0hanad0** [comment]
Furthermore, the default fallback unicode fonts that are specified by the `unicode-fonts` package are _Symbola_ and _Quivira_, so _Symbola_ must support most Arabic characters by default?

In the `unicode-fonts-block-font-mapping` : 
```elisp
 ("Arabic"
  ("Symbola" "Courier New" "Simplified Arabic Fixed" "Simplified Arabic" "Amiri" "Aldhabi" "Adobe Arabic" "Urdu Typesetting" "Geeza Pro" "Baghdad" "Damascus" "Al Bayan" "Andalus" "Arabic Typesetting" "Traditional Arabic" "Scheherazade" "DejaVu Sans Mono" "DejaVu Sans:width=condensed" "Arial Unicode MS" "Nadeem" "Microsoft Uighur" "Tahoma" "Microsoft Sans Serif" "MPH 2B Damase" "KufiStandardGK" "DecoType Naskh" "Koodak" "FreeMono" "Code2000"))
 ("Arabic Extended-A"
  ("Symbola" "Scheherazade" "Amiri"))
 ("Arabic Mathematical Alphabetic Symbols"
  ("Symbola" "Amiri"))
 ("Arabic Presentation Forms-A"
  ("Symbola" "Geeza Pro" "Amiri" "Arial Unicode MS" "Microsoft Sans Serif" "Tahoma" "KufiStandardGK" "Andalus" "Arabic Typesetting" "Urdu Typesetting" "Adobe Arabic" "DecoType Naskh" "Al Bayan" "DejaVu Sans Mono" "DejaVu Sans:width=condensed" "MPH 2B Damase" "Code2000"))
 ("Arabic Presentation Forms-B"
  ("Symbola" "DejaVu Sans Mono" "Geeza Pro" "Amiri" "Adobe Arabic" "Traditional Arabic" "Urdu Typesetting" "Arial Unicode MS" "Microsoft Sans Serif" "KufiStandardGK" "DejaVu Sans:width=condensed" "FreeMono" "DecoType Naskh" "Code2000"))
 ("Arabic Supplement"
  ("Symbola" "Courier New" "Simplified Arabic Fixed" "Amiri" "Simplified Arabic" "Geeza Pro" "Damascus" "Andalus" "Arabic Typesetting" "Traditional Arabic" "Scheherazade" "Adobe Arabic" "Microsoft Uighur" "Tahoma" "Microsoft Sans Serif" "MPH 2B Damase"))
```

_Symbola_ is the first font specified.

**Comment by vancleve** [comment]
Hmm. For that second foo.org screenshot, can you run `describe-char` on a character in the heading where Symbola is being used just to confirm its Symbola?

**Comment by vancleve** [comment]
Yes, I've noticed the same, that emacs is falling back on system fonts that haven't been specified in the config.el. 

I think for that multiple character selection, its actually just showing you the font used for the space (SPC) character at position 32, which is why its using your normal `doom-font`. 

In any case, I think if you do find another Arabic font that you want to use, you shouldn't have any issue getting emacs to use it with with `doom-unicode-font`, so you can probably close the issue.

**Comment by M0hanad0** [comment]
Oh, I think I misunderstood the `unicode-fonts` package use of _Symbola_. :disappointed:
It seems like the _Symbola_ font doesn't support Arabic! Sorry for the inconvenience. I will switch to another font. 
Thanks for the help :+1:
