### ISSUE TITLE
Error when upgrading eglot package: `fatal: bad object e501275e06952889056268dabe08ccd0dbaf23e5`

### ISSUE THREAD

**Issue by asymmetric** [doomemacs/doomemacs#7195]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`doom sync -u` should update the eglot package.

### Current behavior

```
❯ ~/.emacs.d/bin/doom sync -up
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    > (105/265) Re-cloning eglot...
      > Cloning eglot...
    ✓ (105/265) eglot: ee13c9e -> e501275 [1 commit(s)] (w/ 2 dependents)
        ERROR: Couldn't collect commit list because: fatal: bad object e501275e06952889056268dabe08ccd0dbaf23e5
      
    ✓ Updated 3 package(s)
    > (Re)building packages...
      > Building eglot...
      > Building consult-eglot...
      > Building flycheck-eglot...
      > Building citar...
      > Building citar-embark...
      ✓ Rebuilt 5 package(s)
  > Purging orphaned packages (for the emperor)...
    - No builds to purge
    - No ELPA packages to purge
    - No repos to purge
    > Regrafting 247 repos...
      ✓ Regrafted repos/eglot (from 893.1KB to 892.9KB)
      ✓ Finished regrafting. Size before: 584112.9KB and after: 584151.4KB (38.5KB)
    - No ELN directories to purge
  > (Re)building profile in /home/asymmetric/.emacs.d/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.emacs.d/.local/etc/@init.28.el...
    ✓ Built init.28.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 1m 2s
```

### Steps to reproduce

1. Have `(lsp +eglot)` in `init.el`
1. Run `doom sync -u`
2. See error

### System Information

https://pastebin.com/feyc7JBK

**Comment by peterhoeg** [comment]
Workaround:
```elisp
(unpin! eglot)
```

**Comment by razzmatazz** [comment]
I also saw there is a related PR from @elken that updates object hash and should fix this issue:
- https://github.com/doomemacs/doomemacs/pull/7219
