### ISSUE TITLE
update powerthesaurus to prevent 403 errors

### ISSUE THREAD

**Issue by wo** [doomemacs/doomemacs#7201]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

On some platforms (e.g. Linux Mint, for me), powerthesaurus lookups consistently throw a 403 error. 
See [https://github.com/SavchenkoValeriy/emacs-powerthesaurus/issues/23](upstream issue 23).
This is fixed in version 0.3 of emacs-powerthesaurus. 

### Current behavior

There should not be a 403 error.

### Steps to reproduce

M-x powerthesaurus-lookup-dwim

### System Information

https://pastebin.com/BiC7DR3t

**Comment by aserranoni** [comment]
Hey, I was getting the same error as you at some point! Just created a PR (cited above) with the fix. Hope that also works out for you.
