### ISSUE TITLE
Enabling bidi module breaks doom if DejaVu Sans font is not installed

### ISSUE THREAD

**Issue by typoman** [doomemacs/doomemacs#7202]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Nothing

### Current behavior

When I restart emacs I get this error and doom completely breaks.
```
Warning (initialization): An error occurred while loading ‘/Users/bman/.config/emacs/.local/etc/@/init.28.elc’:

Error in a Doom module: ~/.config/emacs/modules/input/bidi/config.el, (error Font not available #<font-spec nil nil DejaVu Sans nil nil nil nil nil nil nil nil nil nil>)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

### Steps to reproduce

1. Enable the `bidi` module 
2. Perform `doom sync`
3. Restart emacs

### System Information

https://pastebin.com/gA3aSsxi

**Comment by mschilli87** [comment]
I have been hit by this as well. Let me know if there is anything I can contribute towards resolving this.

**Comment by hlissner** [comment]
As of db48f76, a missing font will no longer leave Doom in a broken state (though it will still emit a warning). Thanks for bringing it to my attention!
