### ISSUE TITLE
Not able to manually upgrade.

### ISSUE THREAD

**Issue by wnear** [doomemacs/doomemacs#7207]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Due to the poor network, it's impossible for me  to upgrade all the packages without one error.
So even with a in-shell while loop, it's impossible to manually upgrade all the package.

Is there anyway, that tell Doom-Emacs I've have done all the `git fetch origin` stuff, just merge the newest or the pinned commitID of the package.  Or a few line code to loop `git fetch` inside the lisp code.

### Current behavior

`doom sync -u` always exit with some git fetch error.

### Steps to reproduce

`doom sync -u` 

### System Information

https://pastebin.com/rXKXpSzD

**Comment by wnear** [comment]
If I, instead of in the last step run `doom sync -u` ; firstly fetch and merge  for all packages in the  `.local/straight/repos/`  folder, then run `doom sync`. Will this be a valid solution to upgrade all packages and keep the dependancy all happy.

It seems like `doom sync` will check out the commit-id for a selection of packages, which I guess may be a key step to keep the dependancy.

**Comment by BuddhiLW** [comment]
Yeah, seems there is no "timeout" options you can pass or similar. I guess `hlissner` never had this problem (?).

The problem would be that git itself doesn't seem to have a `timeout` flag itself. So, seems more like a git and bandwidth problem to me.

If you find a way to tweak git to take longer to timeout, or if you can keep doing the upgrades with a flag such[^1]:
```
 -k, --keep
     Keep downloaded pack.
```

Then, you could use this strategy to extend the elisp-script that does the upgrading (by calling git) etc.

#### Resources
[^1]: [https://www.git-scm.com/docs/git-pull]( https://www.git-scm.com/docs/git-pull)

**Comment by wnear** [comment]
I'll give it a try.
