### ISSUE TITLE
Equivalent of `eval-after-load` for packages brought with `package!`

### ISSUE THREAD

**Issue by BuddhiLW** [doomemacs/doomemacs#7225]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Putting this snippet at doom configs and have clojure-mode-extra-fonts hooked up to clojure-mode start.
```org
 #+begin_src emacs-lisp :tangle packages.el
(package! clojure-mode-extra-font-locking)
#+end_src

#+begin_src emacs-lisp
(eval-after-load 'clojure-mode '(require 'clojure-mode-extra-font-locking))
#+end_src
 ```
 
 I have tried out `add-hook!`, and `use-package!` with `:hook` and `:config` with no success too.  

### Current behavior

When I start a .clj/.cljs file I get,

run-hooks: Autoloading file /home/buddhilw/.emacs.d/.local/straight/build-27.1/clojure-mode-extra-font-locking/clojure-mode-extra-font-locking.elc failed to define function clojure-mode-extra-font-locking-mode

### Steps to reproduce

Add snippet, sync doom, reload it, and start a clojure-mode.

### System Information

https://pastebin.com/8a7TMan2

**Comment by elken** [comment]
1) Unless you have a specific need for it, you don't need `clojure-mode-extra-font-locking`
2) I recommend you read through [the docs](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#package-management) to understand how to load packages
