### ISSUE TITLE
how to set  default shell with tramp

### ISSUE THREAD

**Issue by ipyffor** [doomemacs/doomemacs#7233]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

set default remote shell automatically

### Current behavior

![image](https://github.com/doomemacs/doomemacs/assets/47955238/7322e8e2-7433-4560-946f-dbaf9fce7402)
The default shell of the remote host is uncertain. It is unreasonable to write the default shell to the configuration. Of course, it is also possible to modify the specified shell. It is better to automatically connect to the remote default shell. Thank you!

### Steps to reproduce

-

### System Information

https://gist.github.com/ipyffor/1686ec2c5d264ac6234a16a4d826cec5

**Comment by elken** [comment]
The issue tracker is for issues specifically related to doom, not your private config.

That said, you shouldn't set this globally for everything; it's defined as a constant for a reason. If you want to set this, use `explicit-shell-file-name` instead.

**Comment by ipyffor** [comment]
It is useless, remote connection is still using sh by default
