### ISSUE TITLE
LSP with Rust not working

### ISSUE THREAD

**Issue by CatRyBouReal** [doomemacs/doomemacs#7245]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I open a file with the extension .rs, enabling the "Rustic" major mode, rust-analyzer should be started by LSP.

### Current behavior

When I open a file with the extension .rs, enabling the "Rustic" major mode, I get a message saying "Unable to find installed server supporting this file. The following servers could be installed automatically:" above a menu which just contains "rust-analyzer". The contents of the `lsp-log` buffer are:
```
Command "rls" is not present on the path
Command "rust-analyzer is not present on the path
```
This is odd because `rust-analyzer` is on the path, having been installed using `rustup`. My `config.el` file is as follows:
```
(after! rustic
  (setq rustic-lsp-server 'rust-analyzer)
  (setq lsp-rust-server 'rust-analyzer))
```

### Steps to reproduce

1. Install `rustup` using the method described on [https://www.rust-lang.org/learn/get-started](https://www.rust-lang.org/learn/get-started). Select the "complete" profile.
2. Open Emacs with LSP and Rust enabled in `init.el`.
3. Open any rust file.

### System Information

https://termbin.com/dfsn

**Comment by eckertliam** [comment]
I had a similar issue and I believe I resolved it by switching to the nightly toolchain as describe [here](https://rust-lang.github.io/rustup/concepts/channels.html)

**Comment by CatRyBouReal** [comment]
I just tried this and it works fine now. Thanks!
