### ISSUE TITLE
Minor mode key binding do not work

### ISSUE THREAD

**Issue by sincebyte** [doomemacs/doomemacs#7248]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

**This is not a bug report,but more like a consultation for you.**

This is the essential config about what I want to do.
```
(map! :after lsp-java
      :map lsp-mode-map
      :n "; s"  #'lsp-signature-activate)
```
With this config I could show the method's signature.
When there have more than one candicate ,I hope the `C-j` and `C-k` is bound to `lsp-signature-previous` and `lsp-signature-next`.
But they are bound to `evil-scroll-down` and `evil-scroll-up` now.
It's seems to be the same scene when I was in evil mode and select the company candicates up and down by `C-j` and `C-k`.

**What I have tried**
I have read your documentation https://discourse.doomemacs.org/t/how-to-re-bind-keys/56#how-to-bind.

```
(map! :after lsp-mode
      :map lsp-signature-mode-map
      :n "c-k"  nil
      :n "c-n"  nil
      :n "c-j"  nil)

(map! :after lsp-mode
      :map lsp-signature-mode-map
      :n "c-k"  #'lsp-signature-previous
      :n "c-n"  #'lsp-signature-previous
      :n "c-j"  #'lsp-signature-next)

(evil-define-key* 'normal lsp-signature-mode-map "C-n" nil)
(evil-define-key* 'normal lsp-signature-mode-map "C-n" #'lsp-signature-next)
```
Unfortunately in the end ,I still failed.

This isuue has bothered me for a longtime, and I'm looking forward to your reply and assistance.
BEST WISHES,

### Current behavior

`C-j` and `C-k` are bound to `evil-scroll-down` and `evil-scroll-up` now in the condition aboved mentioned.

### Steps to reproduce

1. config doom emacs by        (java +lsp +tree-sitter)        
2. goto a java project file
3. cusor located at a valid method
4. use `M-x` and `lsp-signature-activate`
5. use `C-j` or `C-k` for `lsp-signature-previous` and `lsp-signature-next`

### System Information

https://pastebin.com/CNPrPLCW

**Comment by hlissner** [comment]
Rather than putting it in the evil state maps, just put it plainly in `lsp-signature-mode-map`. Also, remember to capitalize the `C-` prefix. `c-` != `C-`. E.g.

```elisp
(map! :after lsp-mode
      :map lsp-signature-mode-map
      "C-k"  #'lsp-signature-previous
      "C-n"  #'lsp-signature-previous
      "C-j"  #'lsp-signature-next)
```

In any case, please do not post support questions on our issue tracker. Use our [Discourse](https://discourse.doomemacs.org) or [Discord](https://doomemacs.org/discord) servers instead.
