### ISSUE TITLE
Enabling tree-sitter breaks ClojureC hooks

### ISSUE THREAD

**Issue by zilti** [doomemacs/doomemacs#7250]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I have `tree-sitter` enabled for Clojure, and I open a `.cljc` file, it behaves normally and works just like `.clj` files.

### Current behavior

When I open a `.cljc` file, I get `Error (clojurec-mode-local-vars-hook): Error running hook "tree-sitter!" because: (error No language registered for major mode 'clojurec-mode')`.

### Steps to reproduce

1. Enable `tree-sitter` for Clojure
2. Open Emacs
3. Open a `.cljc` file

### System Information

https://termbin.com/mkeb

**Comment by cpackard** [comment]
I added this as a workaround to my `config.el` file: `(add-to-list 'auto-mode-alist '("\\.cljc\\'" . clojure-mode))`

**Comment by zilti** [comment]
My workaround now is:

```emacs-lisp
(use-package tree-sitter
  :config
  (add-to-list 'tree-sitter-major-mode-language-alist '(clojurec-mode . clojure))
  (add-to-list 'tree-sitter-major-mode-language-alist '(clojurescript-mode . clojure)))
```

**Comment by cpackard** [comment]
> My workaround now is:
> 
> ```emacs-lisp
> (use-package tree-sitter
>   :config
>   (add-to-list 'tree-sitter-major-mode-language-alist '(clojurec-mode . clojure))
>   (add-to-list 'tree-sitter-major-mode-language-alist '(clojurescript-mode . clojure)))
> ```

Much more cohesive, thanks for the tip!

**Comment by hlissner** [comment]
I've incorporated those lines into the `:lang clojure` module, which should resolve this issue. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
