### ISSUE TITLE
org-roam-graph not showing graph

### ISSUE THREAD

**Issue by bobf32** [doomemacs/doomemacs#7251]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I execute org-roam-graph, I should be presented with a graphical representation of my org-roam notes.

### Current behavior

When I execute org-roam-graph, I see a message saying (org-roam) building graph and nothing else happens. No graph is displayed.

### Steps to reproduce

1. Open emacs
2. C-x C-f to open an org-roam note
3. Spc-Spc org-roam-graph

### System Information

https://pastebin.com/0bryfHFT

**Comment by bobf32** [comment]
If I try and open a SVG file directly I get an xml buffer opened as well as a message "Cannot display image: (Invalid image type 'svg')".

Am guessing this is a config issue as org-roam-graph and opening SVGs works on another machine.

**Comment by iamkarlson** [comment]
for me it opens graph in default browser, perhaps some your settings of default applications is not correct. do you expect it to open in emacs or in the browser?

**Comment by bobf32** [comment]
@iamkarlson In other configs, the SVG opened within emacs. I have tried again and cannot recreate. Think I may have done some reinstalling since reporting originally.

**Comment by hlissner** [comment]
According to your `M-x doom/info`, your Emacs wasn't built with SVG support, so it won't be able to display SVGs. You'll need to install a variant with SVG support or compile it yourself.

As this is not a Doom bug, I'll close this, but feel free to follow up here.
