### ISSUE TITLE
Silent Byte-Compile failures 

### ISSUE THREAD

**Issue by jgrey4296** [doomemacs/doomemacs#7253]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When running `doom sync` it should either succeed and byte-compile `.local/etc/@/init.{version}.elc`, or fail and explain why.

### Current behavior

When syncing doom if byte compilation of the  `.local/etc/@/init.{version}.el` fails,
in [doom-profiles.el](https://github.com/doomemacs/doomemacs/blob/042fe0c43831c8575abfdec4196ebd7305fa16ac/lisp/doom-profiles.el#L361),
this is ignored despite the `condition-case-unless-debug` because `byte-compile-file` doesn't raise errors unless `byte-compile-debug` is true, it just returns nil on failures,
and writes errors to `byte-compile-log-buffer`.

So after failing to compile, the next line `print!`'s a success message without checking the compiled file exists. 
Trying to start emacs after that brings up an error message suggesting you sync doom, even though you did and it said everything worked fine.

### Steps to reproduce

Add a bad autoload into your setup:
```
;;;###autoload
(defmacro simple-test ()
  (eval (format "%s" (fake-function)))
  )

;;;###autoload
(progn 
  ;; (the real problem was a defhydra using an autoloaded function of mine prematurely
  ;; but i found this is equivalent)
  (simple-test)
  )
```

To Fix:
```
(let ((byte-compile-warnings (if init-file-debug '(suspicious make-local callargs)))
        (byte-compile-debug t)) ;; <-- add this and all's good
    (byte-compile-file init-file)))

```

### System Information

https://gist.github.com/jgrey4296/4916396b8d0b8bd50f341ee32f24655b

**Comment by hlissner** [comment]
Sorry for the insanely late follow up, but I've incorporated this into fbcab58. Thanks for bringing it to my attention, in any case!
