### ISSUE TITLE
treeemacs popups hangs with no action

### ISSUE THREAD

**Issue by iamkarlson** [doomemacs/doomemacs#7255]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Treemacs popups are either actionable (you can type inside), or it can be at least closed.

### Current behavior

whenever I open a project sidebar, it has it's own hotkeys to make different actions. for example, renaming a project. However, with evil mode on - this small tooltip window isn't really actionable: I can't type stuff, I can't close it, and it's not closing itself. Only possible way to close this damn popup is via reopening emacs instance

### Steps to reproduce

1. Open emacs
2. Open project via SPC p p 
3. Open project sidebar via SPC o p
4. Call rename project: C-c C-p r
5. a small popup window opens and never goes away:
![image](https://github.com/doomemacs/doomemacs/assets/4534374/26cbc50e-1fd4-4407-9fca-fdee10dfb5fb)

### System Information

https://pastebin.com/wqcAdkpT

**Comment by juboba** [comment]
Hi @iamkarlson I just reproduced this and noticed the problem is that the popup doesn't have a focus. If you click on it it works as expected.

`C-c C-p r` is bound to `(treemacs-rename-project)` so it seems like a treemacs issue.

**Comment by juboba** [comment]
@iamkarlson there is an open issue there https://github.com/Alexander-Miller/treemacs/issues/848

**Comment by iamkarlson** [comment]
@juboba thanks for checking it! it doesn't work for me just clicking on it.  from the issue I figured it's a wayland problem. So perhaps it's going to be fixed upstream. I mentioned a workaround there with holding your mouse clicked.

**Comment by juboba** [comment]
@iamkarlson I see. For now, you can set `treemacs-read-string-input` to `'from-minibuffer` so that it uses that instead of the posframe 🙂 .

**Comment by iamkarlson** [comment]
Oh thank you so much! I didn't know this flag exists! this works much better than a separate window!
