### ISSUE TITLE
Undefined Custom theme

### ISSUE THREAD

**Issue by iamkarlson** [doomemacs/doomemacs#7263]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

custom theme is loaded

### Current behavior

Undefined Custom theme iamkarlson-fallout

### Steps to reproduce

Following https://discourse.doomemacs.org/t/how-to-switch-customize-or-write-themes/37 I have troubles adding my theme. I picked a theme from doomemacs/themes to clone from, downloaded it into `$DOOMDIR/themes`, replaced all the titles with my new name and getting the following error:

```
helm-M-x-execute-command: Undefined Custom theme iamkarlson-fallout
```

and here's shell:
```
❯ pwd && la
/home/iamkarlson/.doom.d/themes
total 12K
-rw-r--r-- 1 iamkarlson iamkarlson 9.1K Jun  5 19:29 iamkarlson-fallout-theme.el
```

This is content of the file https://pastebin.com/6fa8KTKN

### System Information

https://pastebin.com/wvunFrD5

**Comment by iamkarlson** [comment]
Themes from doomemacs-themes repo has to be modified.

**Comment by gagbo** [comment]
Note: This is not the solution.

As I told you on Discord, there's an error in your use of `def-doom-theme`

The line should be

```lisp
(def-doom-theme iamkarlson-fallout
;;...
``` And not
```lisp
(def-doom-theme iamkarlson-fallout-theme
;;...
``` 

Adding an extra `-theme` suffix is wrong, and the `def-doom-theme` macro will expand incorrectly with the extra suffix.

This is why, in the guide you linked at https://discourse.doomemacs.org/t/how-to-switch-customize-or-write-themes/37/6, there is no `-theme` suffix either in the `def-doom-theme` call.

This is why, in doomemacs/themes repo, no theme has the `-theme` suffix in their `def-doom-theme` call e.g.

https://github.com/doomemacs/themes/blob/e4f0b006a516a35f53df2dce2ec116876c5cd7f9/themes/doom-one-theme.el#L44
