### ISSUE TITLE
Freebsd13.2，doom emacs install “error”

### ISSUE THREAD

**Issue by purepig** [doomemacs/doomemacs#7281]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

doom build 

x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (arrayp nil)
    Backtrace:
      (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      (shell-quote-argument nil)
      (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
      (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name di...
      (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-...
      (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument ...
      (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd ...
      (let* ((result result) (exit (car result)) (invoked (numberp exit)) (s...
      (let ((program x53) (args x55) (result x57) (directory x59)) (let* ((r...
      (progn (ignore (null x60)) (let ((program x53) (args x55) (result x57)...
      (let* ((x59 (car-safe x58)) (x60 (cdr-safe x58))) (progn (ignore (null...
      (progn (ignore (consp x58)) (let* ((x59 (car-safe x58)) (x60 (cdr-safe...
    ! Wrote extended backtrace to /usr/home/purepig/.config/emacs/.local/state/logs/cli.doom.230624051942.11487.error

### Current behavior

doom sync

> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated /usr/home/purepig/.config/emacs/.local/env
  > Installing packages...
    - Checked out evil-anzu: d1e98ee6976437164627542909a25c6946497899
    > Building evil-anzu...
    - Checked out evil: 2ce03d412c4e93b0b89eb43d796c991806415b8a
    > Building evil-anzu > Building evil...
    > Building evil-anzu > Building evil > Cloning goto-chg...
    x The package manager threw an error
    x Last 16 lines of straight's error log:
      $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/
      $ git clone --origin origin --no-checkout https\://github.com/emacs-evil/goto-chg.git /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/ --depth 1 --single-branch --no-tags
      f-#eie0 '/usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg'...
      ih//o<RPC e$1h4%ccurl 56 Recv failure: e/9f9e$d=d:h?f%
      h4e=ih//o<e(e<g(eh!(d9ee:h/%fd8d8* flush e 
      [Return code: 128]
      $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/
      $ git clone --origin origin --no-checkout https\://github.com/emacs-evil/goto-chg.git /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/ --no-single-branch
      f-#eie0 '/usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg'...
      h4e=ih//o<f f3h.?i. 'https://github.com/emacs-evil/goto-chg.git/'o<Failed to connect to github.com port 443 after 21118 ms: Couldn't connect to server
      [Return code: 128]
      $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/
      $ git branch -r
      [File error while Setting current directory]
    ! Wrote extended straight log to /usr/home/purepig/.config/emacs/.local/state/logs/cli.doom.230624053754.12730.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 1m 16s

### Steps to reproduce

doom install

x The package manager threw an error
  x Last 16 lines of straight's error log:
    $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/evil/
    $ git submodule update --init --recursive
    [Return code: 0]
    $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/
    $ git clone --origin origin --no-checkout https\://github.com/emacs-evil/goto-chg.git /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/ --depth 1 --single-branch --no-tags
    f-#eie0 '/usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg'...
    h4e=ih//o<f f3h.?i. 'https://github.com/emacs-evil/goto-chg.git/'o<Failure when receiving data from the peer
    [Return code: 128]
    $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/
    $ git clone --origin origin --no-checkout https\://github.com/emacs-evil/goto-chg.git /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/ --no-single-branch
    f-#eie0 '/usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg'...
    h4e=ih//o<f f3h.?i. 'https://github.com/emacs-evil/goto-chg.git/'o<Recv failure: e/9f9e$d=d:h?f%
    [Return code: 128]
    $ cd /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/
    $ git branch -r
    [File error while Setting current directory]
  ! Wrote extended straight log to /usr/home/purepig/.config/emacs/.local/state/logs/cli.doom.230624052831.11705.error
  ✓ Finished in 3m 38s

### System Information

doomemacs.org/discord

**Comment by Patryk27** [comment]
This kinda suggests a flaky network connection on your side:

```
$ git clone --origin origin --no-checkout https://github.com/emacs-evil/goto-chg.git /usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg/ --depth 1 --single-branch --no-tags
f-#eie0 '/usr/home/purepig/.config/emacs/.local/straight/repos/goto-chg'...
ih//o<RPC e$1h4%ccurl 56 Recv failure: e/9f9e$d=d:h?f%
h4e=ih//o<e(e<g(eh!(d9ee:h/%fd8d8* flush e
[Return code: 128]
```

Are you perhaps behind a firewall or a VPN?

**Comment by purepig** [comment]
IT's done.  thanks.

sorry, I am from CHINA.
