### ISSUE TITLE
evil-yank-line not doing as advertised

### ISSUE THREAD

**Issue by bobf32** [doomemacs/doomemacs#7284]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

evil-yank-line should copy the entire line, including any newline.

### Current behavior

evil-yank-line seems to yank from the current position to the end of the line, excluding newline.

### Steps to reproduce

I'm writing an elisp function that, among other things, copies the current line and pastes it just before.

I have this function:

```
(defun foo ()
    (interactive)
    (call-interactively 'evil-yank-line)
    (call-interactively 'evil-paste-before)
)
```

It is acting as though evil-yank-line is not, as the help suggests, saving the whole line, but rather saving that chunk of the line from the cursor to to the end of the line, excluding any newline. If I call this function with the cursor on the second character of a line consisting of 

```
Foobar
```

I get 

```
Foobaroobar
```

rather than the desired

```
Foobar
Foobar
```

### System Information

https://pastebin.com/gfYJHxJ2

**Comment by bobf32** [comment]
Possibly related to #2446

**Comment by hlissner** [comment]
`evil-yank-line` is what's bound to `Y`, whose behavior was never to include the newline at EOL, here or in vim. I think what you want is `evil-yank-lines`, which is designed for direct use in elisp:

```elisp
(defun foo ()
  (interactive)
  (evil-yank-lines (bol) (eol))
  (call-interactively 'evil-paste-before))
```

As this isn't a bug, I'll close this, but feel free to follow up here.
