### ISSUE TITLE
Fresh install in MacOS Ventura freezes when any file is opened

### ISSUE THREAD

**Issue by rogs-ua** [doomemacs/doomemacs#7289]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I open a file in Doom Emacs, I expect for it to be opened and not freeze

### Current behavior

When I open any file in a brand new install of Doom Emacs in MacOS Ventura, it freezes (no hard crash, only freeze).

I have confirmed the install works on my Linux machine. 

I tried my custom Doom config first (which works fine in Linux). When that didn't work, I deleted doom and tried to install fresh (without the `.config/doom` folder), and it didn't work either

### Steps to reproduce

1. Install Doom Emacs on a fresh Emacs installation in MacOS Ventura.
2. Open Emacsm see the welcome screen and try opening a file.
3. Watch it freeze.

### System Information

https://pastebin.com/LBgzPVeD

**Comment by rogs-ua** [comment]
I was able to pinpoint the issue to the `vc` package, in `init.el`. If I comment it out, Emacs works as expected. I will continue investigating, but this is good news 👍

**Comment by rogs-ua** [comment]
It loooks like this is a known issue for Emacs +26.

https://emacs.stackexchange.com/questions/77715/emacs-28-2-vc-git-crashes-on-mac-studio-ventura

**Comment by rogs-ua** [comment]
I was able to fix this by updating Emacs to version 29. This may be closed now

**Comment by Game-Warrior** [comment]
I am having the same error on Emacs 29. I have tried different compilation flags and it has persisted.  Below I have added the output of doom info.

generated  Nov 03, 2023 18:50:34
system     MacOS 14.1 Darwin 23.1.0 arm64
emacs      29.1 ~/.emacs.d/
doom       3.0.0-pre PROFILE=_@0 HEAD -> master 98639850 2023-10-07 02:33:45
	   +0200 ~/.config/doom/
shell      /bin/zsh
features   ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3
	   THREADS TOOLKIT_SCROLL_BARS TREE_SITTER XIM ZLIB
traits     batch server-running envvar-file custom-file
modules    :config use-package :completion company vertico :ui doom
	   doom-dashboard hl-todo modeline ophints (popup +defaults) treemacs
	   (vc-gutter +pretty) vi-tilde-fringe workspaces zen :editor (evil
	   +everywhere) file-templates fold snippets word-wrap :emacs (dired
	   +icons) electric (ibuffer +icons) undo vc :term term vterm :checkers
	   syntax grammar :tools biblio editorconfig (eval +overlay) lookup lsp
	   magit pdf tree-sitter :os macos :lang (cc +lsp) emacs-lisp (go +lsp)
	   javascript (kotlin +lsp) (lua +lsp) markdown nix (org +gnuplot
	   +pretty +pandoc +noter +dragndrop +journal +present +publish) (python
	   +lsp) sh web yaml :email (mu4e +org +gmail +evil) :app calendar
	   everywhere rss :config literate (default +bindings +smartparens)
packages   (evil-tutor) (tldr) (org-tree-slide) (org-auto-tangle)
	   (org-re-reveal) (ox-twbs) (dired-open) (dired-subtree) (peep-dired)
	   (emojify) (beacon) (rainbow-mode) (resize-window) (fountain-mode)
	   (wc-mode) (ivy-posframe) (yasnippet) (palimpsest) (emmet-mode)
	   (elfeed-goodies) (mw-thesaurus) (writeroom-mode) (olivetti) (org-ref)
	   (mastodon) (ox-pandoc) (pandoc) (request) (2048-game) (poetry)
	   (pretty-symbols) (magit-todos) (org-anki) (anki-connect) (ox-gfm)
	   (ivy-bibtex) (anki-mode) (go-translate) (transient :pin
	   c2bdf7e12c530eb85476d3aef317eb2941ab9440 :recipe (:host github :repo
	   magit/transient)) (with-editor :pin
	   bbc60f68ac190f02da8a100b6fb67cf1c27c53ab :recipe (:host github :repo
	   magit/with-editor)) (blamer) (org-noter) (nov.el) (ox-epub) (esxml)
	   (burly) (eshell-prompt-extras) (chatgpt-shell) (dall-e-shell)
	   (ob-chatgpt-shell) (synosaurus) (academic-phrases) (pacmacs)
	   (fireplace) (jinx) (org-bullets) (fedi) (lem) (org-cliplink) (ellama)
	   (org-timeblock) (llm)

**Comment by nujabse** [comment]
@Game-Warrior Did you solve the problem yet?

**Comment by Game-Warrior** [comment]
I solved it by moving to Emacs-plus. It doesn't have these problems.

**Comment by shkodm** [comment]
Interesting bug, after experiencing random freezes opening files and new buffers on multiple emacs ports (emacs-plus, emac-port) on M2 Macbook Air, commenting our `vc` package was the only thing that fixed this for me.

**Comment by FrederickGeek8** [comment]
Hi there. Yeah, I'm suffering from this issue too it seems. My Macbook died for some reason the two nights ago while plugged in and now Emacs will crash whenever a file or directory is selected with `find-file`  (both through `M-x find-file` and `Spc .`).

Commenting out `vc` in `init.el` fixes the issue. I also tried commenting out `(vc-gutter +pretty)` but not `vc` and I still see the issue. Commenting out only `vc` fixes the problem.

I'm on macOS 14.2.1 on an Intel Macbook Pro (2018). I'm running `emacs-plus` where `emacs --version` reports `GNU Emacs 29.1`. I installed Emacs through Homebrew.

Unlike @leonlan, after commenting out `vc` I am still able to open (basic) `.org` files.

`killall Emacs` exits Emacs without issue. Spamming `C-g` does nothing. 

With `kill -SIGUSR2 <pid>` I am able to drop Emacs into it's debugger. I copy-pasted the message in the debugger into the `emacs.crash.log` which I've attached to this post. Running with just `emacs --with-profile=default --debug-init &` hangs with `editor:evil: loading evil-collection-epa` in the modeline. Strange...

Things I've tried
- doom doctor (seems fine)
- doom clean
- doom build
- doom update
- brew upgrade
- brew doctor (seems mostly fine)

I'm going to hop on the Discord. I'll report back if I find a solution.

[emacs.crash.log](https://github.com/doomemacs/doomemacs/files/13941750/emacs.crash.log)

**Comment by FrederickGeek8** [comment]
I'm cross-posting this from the issue #7589. I was able to solve this issue, which for me appeared to be because of `gpg` which was locking up the `find-file`.

I posted my macOS-specific solution to a StackExchange question whose `gpg` started locking up a few days ago. It might be worth checking out and see if it helps with your issues.

https://unix.stackexchange.com/questions/766275/gpg-hangs-on-macos/766998#766998

From #7589:

> This could be completely unrelated., but I was having a problem with `find-file` on macOS. As near as I can tell, it was related to `gnupg@2.4.3`. 
> 
> I posted about my problem on #7289, which dealt with an issue where people couldn't open files. They didn't post much debug information, so it's hard to tell if it was the same issue I was having.
> 
> The issue was apparently that the command `/usr/local/bin/gpg --with-colons --no-greeting --batch --with-fingerprint --with-fingerprint --fixed-list-mode --list-keys "Frederick"` was hanging indefinitely. **Downgrading to `gnupg@2.2` solved the issue immediately**. 
> 
> In my quest to fix this issue I noticed something before my downgrade:
> - When I tried to run the above command the first time, `gpg` would get stuck waiting for a lock. I also noticed that I had at least a dozen `gpg` command that were stuck in the background. A quick `killall gpg` killed them. I then deleted the `~/.gnupg/gnupg_spawn_keyboxd_sentinel.lock` lock file, and the `gpg` command would hang without a message.
> 
> From there I downgraded to `gpupg@2.2`. Around that time, I noticed there was a `~/.gnupg/public-keys.d/pubring.db.lock` file. I didn't delete it before downgrading, but when I downgraded to `gnupg@2.2` everything worked great.
> 
> So I thought: what if I upgraded back to 2.4.3 and deleted that lockfile? So I did. And it worked! 
> 
> I'm wondering if there was a change that made `gnupg` respect that lockfile, since `gnupg@2.2` didn't seem to care, but 2.4.3 did. 
> 
> I posted my solution to this StackExchange post for someone macOS whose `gnupg` 2.4.3 started hanging a few days ago. I'm curious whether an unexpected poweroff may have locked up your `gnupg` 2.4.3.
> 
> https://unix.stackexchange.com/questions/766275/gpg-hangs-on-macos/766998#766998
> 
> Cheers!
> 
> Perhaps it's all unrelated. Maybe I'm drawing connections between two maybe issues that seem related. Nonetheless, I thought I would share my findings.

**Comment by shkodm** [comment]
@FrederickGeek8 thanks for your comment, I solved my issue already previously, and it was indeed related to new `gnupg`, version, but I had not realised it was realised it was related to the lock file. And good thing to have it all documented, I spent too much time debugging it.

**Comment by AaronDovTurkel** [comment]
Hey all 👋🏻,
Im still having this issue.
I've tried:
- downgrading gig
- commenting out vc
- plus normal clean, upgrades, etc

I'm using `modules v24.02` but to no avail.

Any suggestions or more info I can provide please let me know. (Emacs/Doom noob here)

**Comment by jabirali** [comment]
I'm also having the same issue:

Doom Emacs + Emacs Mac port (v29.1) freezes when I open any file, and pressing `C-g`, `ESC`, etc. doesn't help. Waiting for 10+ min also didn't help. The issue persists until I `killall gpg`, then Emacs is responsive again.

This issue does not occur using my vanilla Emacs config or when using `emacs -Q`. It appears to only happen in Doom Emacs (even a fresh clone).

For me, deleting that lock file didn't resolve it. But `brew install gnupg@2.2`, followed by adding `/opt/homebrew/opt/grep/libexec/gnubin` early in `$PATH` to prevent Emacs from using the new `gnupg` version, did fix it.
