### ISSUE TITLE
Symbol’s function definition is void: dired-read-dir-and-switches

### ISSUE THREAD

**Issue by Roger-Roger-debug** [doomemacs/doomemacs#7299]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Dired opens when I press `SPC f d` (`+default/dired`) right after opening emacs. Doesn't happen if I open other stuff first (for example `SPC f p`.

### Current behavior

Error shows and dired doesn't open.

### Steps to reproduce

1. Open Emacs
2. `SPC f d`
3. error

### System Information

https://pastebin.com/2JqjivgU

**Comment by jacekjarosz55** [comment]
I just installed the latest version of doom emacs on Windows and the issue is still present
