### ISSUE TITLE
In OpenBSD, lsp-install-server > metals installs Linux binary (with solution)

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7305]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Context: I run OpenBSD.

When I install lsp::metals in DoomEmacs, it should work. i.e. install the OpenBSD compatible binaries.

### Current behavior

The installation log (comint) for lsp::metals shows a message saying more or less "coursier : invalid format"

PROBLEM: When I go to `.emacs.d/.local/etc/lsp/metals/` the installed `coursier` file is a Linux ELF binary.

SOLUTION: When you go to [coursier's installation instructions page](https://get-coursier.io/docs/cli-installation#launcher-urls)  there is an entry "Any (needs JVM)" which work perfectly under OpenBSD. Installing this version (for everyone or for *BSDs only) would solve the problem

### Steps to reproduce

1. Run OpenBSD 
2. Start DoomEmacs
3. M-x lsp-install-server
4. Select metals
5.  check binary type
```
$ file "~/.emacs.d/.local/etc/lsp/metals/coursier"
~/.emacs.d/.local/etc/lsp/metals/coursier: ELF 64-bit LSB pie executable, x86-64 ...
``` 

### System Information

https://pastebin.com/Q7nWhJNC

**Comment by elken** [comment]
One for [upstream](https://github.com/emacs-lsp/lsp-metals)

**Comment by liar666** [comment]
Ooops sorry... DONE !
https://github.com/emacs-lsp/lsp-metals/issues/98
