### ISSUE TITLE
Building the compat package fails

### ISSUE THREAD

**Issue by olynch** [doomemacs/doomemacs#7310]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Doom emacs installs without error.

### Current behavior

When I run `.emacs.d/bin/doom install` I get:

```
- Skipping ~/.doom.d/ (already exists)
  - Skipping init.el (already exists)
  - Creating ~/.doom.d/config.el
  ✓ Done!
  - Skipping packages.el (already exists)
Generate an envvar file? (see `doom help env` for details) (y or n) n
Installing plugins
> Installing packages...
  - Checked out project: e086bdc7c515f8bfc22598d473ba888ba7683f0c
  > Building project...
  x There was an unexpected runtime error
    Message: :pre-build command error in "project" recipe in command "(\"./autogen.sh\")"
    Backtrace:
      (error ":pre-build command error in %S recipe in command %S" "project" "(\"./autogen.sh\")")
      (condition-case err (if (cl-every #'stringp command) (if (apply #'straight--process-run-p command) ...
      (let ((command (car --dolist-tail--))) (condition-case err (if (cl-every #'stringp command) (if (ap...
      (while --dolist-tail-- (let ((command (car --dolist-tail--))) (condition-case err (if (cl-every #'s...
      (let ((--dolist-tail-- (if (cl-every #'listp commands) commands (list commands)))) (while --dolist-...
      (let ((default-directory repo) (commanderror nil)) (let ((--dolist-tail-- (if (cl-every #'listp com...
      (if repo (let ((default-directory repo) (commanderror nil)) (let ((--dolist-tail-- (if (cl-every #'...
      (let* ((commands (and t (if post post-build pre-build))) (repo (and commands (straight--repos-dir (...
      (let* ((--cl-rest-- recipe) (pre-build (car (cdr (plist-member --cl-rest-- ':pre-build)))) (post-bu...
      (straight--run-build-commands (:type git :host github :repo "emacs-straight/project" :files ("*.el"...
      (progn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--compute-...
      (prog1 (progn (straight--run-build-commands recipe) (straight--symlink-package recipe) (straight--c...
    ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230726112838.167357.error
```

### Steps to reproduce

1. Run emacs on nixos
2. Clone doom emacs into `.emacs.d`
3. Install with `.emacs/bin/doom install`

### System Information

https://pastebin.com/MdUHf5Uq

**Comment by hlissner** [comment]
`project.el` does not have a `:pre-build` property in its recipe. I'm not sure if it was removed at some point, upstream, but this error should no longer be possible, so I'll close this. Thanks for bringing it to my attention, in any case!
