### ISSUE TITLE
Loading of org-mode broken - org-yt `org-display-user-inline-images` produces error

### ISSUE THREAD

**Issue by danielkrajnik** [doomemacs/doomemacs#7317]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Org mode loads correctly

### Current behavior

Loading org-mode breaks in bad state.

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  get-char-property-and-overlay(nil org-image-overlay)
  org-display-user-inline-images(nil nil nil nil)
  apply(org-display-user-inline-images (nil nil nil nil))
```

I've traced the issue to this function (part of org-yt package). I assume this must have been cause by recent update:

![image](https://github.com/doomemacs/doomemacs/assets/15096799/4a314321-7dd8-4e45-a99e-ac14c4c5b5b5)

Workaround is to remove this advice from `org-display-inline-images` function: `(after! org (advice-remove 'org-display-inline-images 'org-display-user-inline-images) ... )` , but I don't know what side effects will be in the long term.

Any advice (no pun intended) would be really appreciated (I've spent 20 hours trying to solve it already).

### Steps to reproduce

1. Open Emacs
2. create an .org file with a link to some webpage
3. toggle-inline-images

### System Information

https://pastebin.com/rSMWXqHi

**Comment by 8dcc** [comment]
This is exactly my issue.

**Comment by 8dcc** [comment]
After running that, it just says "No images to display inline".

There is a link like this in the file:
`[[https://user-images.githubusercontent.com/29655971/258917459-fd279e8f-61c8-4dfa-96b4-8edaa8a6378d.png]]`

**Comment by danielkrajnik** [comment]
This link doesn't work for me neither, I've never tried displaying web-based images directly, I usually first snip them to a file (using org-download):
![image](https://github.com/doomemacs/doomemacs/assets/15096799/5423ec7f-a6ec-4129-87c7-979de353169d)

It's a cool idea though, I can see how this would come in handy. Seems like a job for org-yt package is made for that (the same package of the issue I've linked above).

**Comment by danielkrajnik** [comment]
> I might try pinning org-mode to version 28 to see if that works. How can I do that?

Sorry, my bad. I didn't mean org-mode, but emacs. If you are on arch-based distro you can pin it to version 28.

**Comment by danielkrajnik** [comment]
That's annoying, you probably have already seen this thread? I've tried to change `org-display-remote-inline-images variable to `t` or `cache`, but both to no avail. It's set to download by default. Inline images still don't pop up.

I am going through some issues on my own system and couldn't sign up to github for the past hour.

**Comment by 8dcc** [comment]
> That would be a really cool feature though, so I will send an update if it eventually works.

It has worked for me in the past, in case I wasn't clear.

**Comment by ispringle** [comment]
```elisp
(advice-remove 'org-display-inline-images 'org-display-user-inline-images)
```
This worked for me on Emacs 29

**Comment by 8dcc** [comment]
> ```emacs-lisp
> (advice-remove 'org-display-inline-images 'org-display-user-inline-images)
> ```
> 
> This worked for me on Emacs 29.
> 
> edit:
> 
> Nevermind, it seems to be that the error is sporadic, not that this solved the issue.

After doing that, it just says "No images to display inline". Using the same URL and format I posted before.

**Comment by ispringle** [comment]
I switched to emacs-plus@28 and this is still an issue. I get it when I clock into a task, however it's not on every clock. Not sure what's going on.

**Comment by hlissner** [comment]
As of 321f2d2, I've removed the org-yt package, which should indirectly fix this issue. Let me know if that gives you any trouble and I'll reopen this. Thanks for bringing it to my attention!
