### ISSUE TITLE
`doom sync` on fresh install broken

### ISSUE THREAD

**Issue by liar666** [doomemacs/doomemacs#7322]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Following https://github.com/doomemacs/doomemacs/issues/7321 I had to reinstall DoomEmacs from scratch.

When I run doom sync I expect it to work flowlessly

### Current behavior

Now, when I run `doom sync`, I get:
```
$ doom sync
> Tangling your literate config...
  ✓ Done tangling 1 file(s)!
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    - Checked out rainbow-mode: 8e96388fb4d616a9dde23e712bad0d9cd048fbf0
    > Building rainbow-mode...
    x There was an unexpected runtime error
      Message: Error with packages
      Details: ("rainbow-mode" (error "rainbow-mode.el:0:0: error: cl-assertion-failed: ((> (point) output-start))"))
      Backtrace:
        (signal doom-package-error ("rainbow-mode" (error "rainbow-mode.el:0:0: error: cl-assertion-failed: ((> (point) output-start))")))
        (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (let* ((commit (and t (cdr (assoc pkg pinned))))) (if commit (doom-print (doom-print--format (doom-prin...
        (progn (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (condition-case e (let ((straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _)...
        (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (package (car (cdr (plist-member --cl-rest-- ':package)))) (type (car (cdr (plist-m...
        (cl-destructuring-bind (&key recipe package type local-repo &allow-other-keys) (append (list :recipe recipe) recipe) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-re...
        (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-packages--cli-recipes-update)) (conditio...
        (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir local-repo)) nil (doom-pa...
        (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-directory-p (straight--repos-dir lo...
        (let ((--dolist-tail-- recipes)) (while --dolist-tail-- (let ((recipe (car --dolist-tail--))) (straight--with-plist (append (list :recipe recipe) recipe) (recipe package type local-repo) (if (file-di...
        (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) straight-u...
        (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg built)))) str...
        (let* ((built (and t (let* ((recipes (doom-package-recipe-list)) (built nil) (straight-use-package-pre-build-functions (cons #'(lambda (pkg &rest _) (setq built (if (member pkg built) built (cons pkg...
      ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.230731154256.906997.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
```

### Steps to reproduce

- Fresh install Doom
- Add a working config.org with some external packages
-  Run an upgrade.
- Run `doom sync`

### System Information

https://pastebin.com/EmuU5sr4

**Comment by codingCoffee** [comment]
Happened when I upgraded `emacs` to version `29.1`.

**Comment by Timothy-W-Hilton** [comment]
> Happened when I upgraded `emacs` to version `29.1`.

@codingCoffee, could be because [29.1 is not officially supported](https://github.com/doomemacs/doomemacs#prerequisites)

**Comment by codingCoffee** [comment]
Thanks @Timothy-W-Hilton, downgrading to `28.2.2` solved it for me.

**Comment by liar666** [comment]
I'm on a fresh install on Emacs 28.1

**Comment by liar666** [comment]
DoomEmacs is totally broken here. 
- `doom sync` crashes as shown above
- `doom clean` and `doom build` work but do not solve the problem
- `doom purge` does not work, asks for solving problems with `sync` first
- `doom compile` works but does not solve the problem...

Any ideas? I just recovered my `config.org`, `init.el` and `packages.el` from a working config onto a fresh install  of latest DoomEmacs, and now I cannot do anything with my Doom installation :'(

**Comment by liar666** [comment]
OK.... After fighting hours with my 1000s line config, executing it line-by-line, I discovered there was a non-closed paren somewhere, and (Doom)Emacs never complained about it!
Paren is now closed and `doom sync` works as expected
