### ISSUE TITLE
org-roam-node-insert error: `wrong-type-argument integer-or-marker-p nil`

### ISSUE THREAD

**Issue by cyphersnake** [doomemacs/doomemacs#7326]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the latest available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I to `org-roam-node-insert` inside org-roam file and select a file from the list, I expect a link, to be added

### Current behavior

When I to `org-roam-node-insert` and and select a file from the list, I receive error:
```lisp
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  org-roam-db-insert-link((link (:standard-properties [650 706 693 704 0 nil nil nil nil nil nil nil nil nil (paragraph (:standard-properties [650 707 650 707 0 650 nil t nil nil nil nil element nil (section ...) nil nil #<buffer 20230801104609-name.org>])) nil nil #<buffer 20230801104609-name.org>] :type "id" :path "b0e0128c-b8e8-49e6-a333-fb193c70ec78" :format bracket :raw-link "id:b0e0128c-b8e8-49e6-a333-fb193c70ec78" :application nil :search-option nil)))
  org-roam-db-map-links((org-roam-db-insert-link))
  org-roam-db-update-file()
  org-roam-db-autosync--try-update-on-save-h()
  run-hooks(after-save-hook)
  basic-save-buffer(nil)
  save-buffer()
  evil-write(nil nil nil nil nil)
  funcall-interactively(evil-write nil nil nil nil nil)
  call-interactively(evil-write)
  evil-ex-call-command(nil #("w" 0 1 (ex-index 1)) nil)
  eval((evil-ex-call-command nil #("w" 0 1 (ex-index 1)) nil))
  evil-ex-execute(#("w" 0 1 (ex-index 1)))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
```
file exists, ID is correct.

Occurs randomly, also due to this error, some files are lost after `org-roam-db-sync`. At the same time, the transition by links works correctly.

### Steps to reproduce

1. Open Emacs
2. `org-roam-node-insert`
3. Select node from list
4. Receive error

### System Information

https://pastebin.com/r32RYHkc

**Comment by Delapouite** [comment]
Related issue on org-roam tracker https://github.com/org-roam/org-roam/issues/2361

**Comment by yantar92** [comment]
See https://github.com/radian-software/straight.el/issues/1107
