### ISSUE TITLE
org-element invoke error when preview-latex in org file

### ISSUE THREAD

**Issue by zhyzky** [doomemacs/doomemacs#7334]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Press Enter on a latex formula, latex will converted to img without error.

### Current behavior

Now after press Enter, the error shows
Warning (org-element-cache): org-element--cache: Org parser error in someorgfile.org::18. Resetting.
 The error was: (error "Invalid search bound (wrong side of point)")
And I did some investigation to find the issue has something todo with org-element--current-element.

### Steps to reproduce

Press Enter on a latex formula would simply got this issue
And eval (org-element--current-element (point)) would cause the same error

### System Information

https://pastebin.com/EYWvr9a8

**Comment by kilesduli** [comment]
Maybe related to this issue radian-software/straight.el#1107.

Could downgrade org version to avoid this problem.

Just copy package declaration from the module/lang/org into `$DOOMDIR/packages.el ` and pin a 9.6 version.
Delete `.emacs.d/.local/repos/org` and `.emacs.d/.local/build-xxxxxx/org` (maybe need `doom build` or delete `.local/cache/eln`), and doom sync.
In emacs, `M-x org-version` see 9.67 will be work.
Org mode version 9.6.7 (9.6.7-??-ca873f7 @ /home/xxxx/.emacs.d/.local/straight/build-30.0.50/org/)

``` emacs-lisp
(package! org
  :recipe (:host github
           ;; REVIEW: I intentionally avoid git.savannah.gnu.org because of SSL
           ;;   issues (see #5655), uptime issues, download time, and lack of
           ;;   shallow clone support.
           :repo "emacs-straight/org-mode"
           :files (:defaults "etc")
           :depth 1
           ;; HACK: Org has a post-install step that generates org-version.el
           ;;   and org-loaddefs.el, but Straight doesn't invoke this step, and
           ;;   the former doesn't work if the Org repo is a shallow clone.
           ;;   Rather than impose the network burden of a full clone (and other
           ;;   redundant work in Org's makefile), I'd rather fake these files
           ;;   instead. Besides, Straight already produces a org-autoloads.el,
           ;;   so org-loaddefs.el isn't needed.
           :build t
           :pre-build
           (progn
             (with-temp-file "org-loaddefs.el")
             (with-temp-file "org-version.el"
               (let ((version
                      (with-temp-buffer
                        (insert-file-contents (doom-path "lisp/org.el") nil 0 1024)
                        (if (re-search-forward "^;; Version: \\([^\n-]+\\)" nil t)
                            (match-string-no-properties 1)
                          "Unknown"))))
                 (insert (format "(defun org-release () %S)\n" version)
                         (format "(defun org-git-version (&rest _) \"%s-??-%s\")\n"
                                 version (cdr (doom-call-process "git" "rev-parse" "--short" "HEAD")))
                         "(provide 'org-version)\n")))))
  :pin "ca873f7fe47546bca19821f1578a6ab95bf5351c")
```

**Comment by zhyzky** [comment]
Seems not related to this issue https://github.com/radian-software/straight.el/issues/1107.
With the recently upgrade, some issue about org-element seems go away, except this one.

**Comment by nujabse** [comment]
Encountered the same issue, down grading does not help, still get warnings.

**Comment by zhyzky** [comment]
The issue seems related to org-element-at-point
But it's strange (Cursor is at 1234 for example) when I execute 
(org-with-point-at 1 (org-with-point-at 1234 (org-element-at-point)))
there is no org-cache error print.

**Comment by chumutt** [comment]
Is there, at the very least, a way to disable or ignore the warning until this gets fixed? I can't seem to find a way to do it gracefully.

**Comment by Loberrino** [comment]
The behaviour I get is that the error pops up and then the LaTeX preview loads but it loads at a much larger scale than it's supposed to. Downgrading Org as mentioned above does stop the error from appearing (at least on my end) but LaTeX previews are still abnormally large

**Comment by zhyzky** [comment]
> Is there, at the very least, a way to disable or ignore the warning until this gets fixed? I can't seem to find a way to do it gracefully.

Maybe you're looking for this
``` lisp
(setq warning-suppress-types (append warning-suppress-types '((org-element-cache))))
```

**Comment by chumutt** [comment]
> > Is there, at the very least, a way to disable or ignore the warning until this gets fixed? I can't seem to find a way to do it gracefully.
> 
> Maybe you're looking for this
> 
> ```lisp
> (setq warning-suppress-types (append warning-suppress-types '((org-element-cache))))
> ```

Yes, that worked. Thank you.

**Comment by MDevVal** [comment]
Having the same issue. Was not fixed with a downgrade.

**Comment by colawithsauce** [comment]
I met this issue today, but it've gone away by downgrading. Thanks!

**Comment by zeorin** [comment]
I had a different issue (no LaTeX involved, just opening a new daily org-roam note `org-roam-dailies-goto-today`), but the with the same error. I had to nuke the entire `$DOOMLOCALDIR` and `doom install`, then `doom sync -u` to fix. I tried being less aggressive by only removing the `org*` packages from the local straight repos, and then all the local straight repos, but that didn't work.

**Comment by zhyzky** [comment]
After a recently update, seems fixed.
