### ISSUE TITLE
Can't install doom emacs

### ISSUE THREAD

**Issue by TheRealOne78** [doomemacs/doomemacs#7360]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

To initialize doom emacs instead of vanilla emacs.

### Current behavior

I've just installed doom emacs on emacs28 (AUR, because Arch Linux ships unsuported emacs29) and I can't get doom emacs to work.

I have followed the instructions from https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org 

Running `emacs` or `doom run` opens up Vanilla Emacs instead of Doom Emacs. (The fonts are like this because of Xresources)

![Screenshot_20230820_141345](https://github.com/doomemacs/doomemacs/assets/53640879/ef742093-8a0d-4c55-9b48-7154552d89a0)

I have installed doom emacs about half year ago and I wanted to try Doom Emacs again in order to learn Emacs. As such, I had to paste a screenshot instead of copying-pasting text, because I don't know any Emacs bindings.

`doom doctor` also shows the following message:
```
❯ doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for great Emacs features...
! Emacs was not built with native compilation support
  Users will see a substantial performance gain by building Emacs with
  native compilation support, availible in emacs 28+.You must install a
  prebuilt Emacs binary with this included, or compile Emacs with the
  --with-native-compilation option.
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 50 modules
  ✓ Detected 176 packages
  > Checking Doom core for irregularities...
    Found font material-design-icons.ttf
    Found font weathericons.ttf
    Found font octicons.ttf
    Found font fontawesome.ttf
    Found font file-icons.ttf
    Found font all-the-icons.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :input japanese
      ! Cannot find "cmigemo", migemo won't work
    > :lang cc
      x This module requires (:tools lsp)
    > :lang python
      ! Couldn't find isort. Import sorting will not work.
      ! Couldn't find pipenv. pipenv support will not work.
      ! Couldn't find nosetests. Running tests through nose will not work.
      ! Couldn't find pytest. Running tests through pytest will not work.
    > :lang sh
      ! Couldn't find shellcheck. Shell script linting will not work

There are 7 warnings!
There is 1 error!
```

### Steps to reproduce

1. Install [emacs28](https://aur.archlinux.org/packages/emacs28) from AUR (I used the `yay` package manager);
2. Follow https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org to install doom emacs;
3. Run `emacs` or `doom run`.

### System Information

https://therealone78.ddns.net/uploads/doom-emacs-report-issue.txt

**Comment by hlissner** [comment]
The error is that your chosen font cannot be found (in this case, "DejaVu Sans"). You'll need to open `$DOOMDIR/config.el` and find the `(setq doom-font ...)` line and set it to a font that actually exists on your system (or installing Dejavu Sans on your system).

**Comment by elken** [comment]
Noticed "The fonts are like this because of Xresources", so the issue lies there; but same outcome. The font is missing or in a strange place.

**Comment by TheRealOne78** [comment]
> Noticed "The fonts are like this because of Xresources", so the issue lies there; but same outcome. The font is missing or in a strange place.

Meant to say that the font _colors_ is like this because of Xresources. The only font I am using in my Xresources file is MesloLGS NF.

```
!! Colorscheme

! special
URxvt.depth      : 32
!*.foreground    :   #f2f7c8
*.foreground     : #e7f096
URxvt.background : rgba:0000/0000/0000/eeee
xterm*background : #000000
URxvt.cursorColor:  #c5c8c6

! black
*.color0:  #1d1f21
*.color8:  #969896

! red
*.color1:  #cc342b
*.color9:  #cc342b

! green
*.color2:  #198844
*.color10: #198844

! yellow
*.color3:  #fba922
*.color11: #fba922

! blue
*.color4:  #3971ed
*.color12: #3971ed

! magenta
*.color5:  #a36ac7
*.color13: #a36ac7

! cyan
*.color6:  #3971ed
*.color14: #3971ed

! white
*.color7:  #c5c8c6
*.color15: #ffffff

!! URxvt Appearance
!URxvt.font          : xft:Inconsolata     :size=8
!URxvt.font          : xft:Mono            :pixelsize=14:antialias=true
URxvt.font           : xft:MesloLGS NF     :pixelsize=14
!URxvt*.font         : xft:MesloLGS NF     :pixelsize=14:antialias=true
!URxvt.boldFont      : xft:
!URxvt.italicFont    : xft:DejaVu Sans Mono:pixelsize=15,style=Book
!URxvt.boldItalicfont: xft:DejaVu Sans Mono:pixelsize=15,style=Book
URxvt.letterSpace    : 0
URxvt.lineSpace      : 0
URxvt.geometry       : 92x24
!URxvt.internalBorder: 24
URxvt.internalBorder : 8
URxvt.cursorBlink    : true
URxvt.cursorUnderline: false
URxvt.saveline       : 2048
URxvt.scrollBar      : false
URxvt.scrollBar_right: false
URxvt.urgentOnBell   : true
URxvt.iso14755       : false

!! URxvt Functions
URxvt.keysym.Shift-Control-V: eval:paste_clipboard
URxvt.keysym.Shift-Control-C: eval:selection_to_clipboard

URxvt.keysym.Control-Up   : \033[1;5A
URxvt.keysym.Control-Down : \033[1;5B
URxvt.keysym.Control-Left : \033[1;5D
URxvt.keysym.Control-Right: \033[1;5C

URxvt.perl-ext-common      : default,tabbed,matcher,resize-font,-tabbed
URxvt.keysym.C-KP_Subtract : resize-font:smaller
URxvt.keysym.C-KP_Add      : resize-font:bigger
URxvt.keysym.C-equal       : resize-font:reset
URxvt.keysym.C-question    : resize-font:show
```

**Comment by TheRealOne78** [comment]
> The error is that your chosen font cannot be found (in this case, "DejaVu Sans"). You'll need to open `$DOOMDIR/config.el` and find (or add) the `(setq doom-font ...)` line ([example](https://github.com/doomemacs/doomemacs/blob/master/templates/config.example.el#L24-L25)) and set it to a font that actually exists on your system (otherwise, install Dejavu Sans on your system).

Instaling ttf-dejavu solved the problem... However shouldn't have the doom installer checked for this font? I kinda expected it since it cloned tremendous ammounts of git repos and had to compile elisp stuff for about 10 minutes or so.

Anyway, thank you for the fast reply, especially in sunday!

**Comment by hlissner** [comment]
> However shouldn't have the doom installer checked for this font?

Making any guesses about the user's config is *much* more challenging than it sounds, especially when GUIs/fonts (and the myriad OSes users run Emacs on, plus the sheer breadth of user freedom that elisp allows) are involved. I leave it to Emacs' runtime errors to report these issues instead, even if they aren't very beginner friendly to parse. Still, I'm working on ways to document them better and catch+regurgitate them into something more beginner friendly.

In any case, glad you figured out the issue!
