### ISSUE TITLE
C.UTF-8 not defined on macOS, affecting `doom` CLI wrapper script

### ISSUE THREAD

**Issue by chrisbarrett** [doomemacs/doomemacs#7361]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

The `doom` wrapper script runs without warnings, setting locale variables appropriately to ensure locale-dependent behaviour is predictable.

### Current behavior

Running `doom`, e.g. to perform `doom sync`, will issue warnings on macOS and may have unpredicted behaviour, since `C.UTF-8` is not defined on that platform.

The issue was introduced here: https://github.com/doomemacs/doomemacs/pull/7331

[Related SO thread](https://unix.stackexchange.com/questions/597962/how-widespread-is-the-c-utf-8-locale?rq=1) notes the presence of this locale is spotty across OSes and Linux distros.

The locale is hardcoded in `bin/doom`; to work around the problem on my machine I can modify the script to set a different locale. I'm in NZ, but `en_US` might be reasonable for most users.

```diff
diff --git a/bin/doom b/bin/doom
index deafdf66..c8849a02 100755
--- a/bin/doom
+++ b/bin/doom
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 :; # -*- mode: emacs-lisp; lexical-binding: t -*-
-:; export LC_ALL=C.UTF-8
+:; export LC_ALL=en_NZ.UTF-8
 :; case "$EMACS" in *term*) EMACS=emacs ;; *) EMACS="${EMACS:-emacs}" ;; esac
 :; emacs="$EMACS ${DEBUG:+--debug-init} -q --no-site-file --batch"
 :; tmpdir=`$emacs --eval '(princ (temporary-file-directory))' 2>/dev/null`
```

### Steps to reproduce

1. Get your grubby mits on a Mac running Ventura
2. Run `locale -a | grep -i utf | sort` to list locales
3. Feel sad because C.UTF-8 is not there.

This is also visible in the output of `doom`, e.g.:
```sh
$ doom s
<snip>/.config/emacs/bin/doom: line 3: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
/nix/store/<snip>-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
/nix/store/<snip>-bash-5.2-p15/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
> Synchronizing "default" profile...
  > Installing packages...
    <snip>
```

### System Information

https://pastebin.com/YEaLq7Rw

**Comment by hlissner** [comment]
As of 7a75030 this should be fixed. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
