### ISSUE TITLE
After upgrading I have an error: Error (clojure-mode-local-vars-hook): Error running hook "cider-mode" because: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by khmelevskii** [doomemacs/doomemacs#7365]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

I expect to run project with cider without exception

### Current behavior

When starts project with cider and this `.dir-local.el`
```
((nil . ((cider-ns-refresh-before-fn . "integrant.repl/suspend")
         (cider-ns-refresh-after-fn . "integrant.repl/resume"))))
```
I have an error
```
Error (clojure-mode-local-vars-hook): Error running hook "cider-mode" because: (wrong-type-argument stringp nil)
```

### Steps to reproduce

1. Open Emacs
2. Open clojure project with cider

### System Information

https://pastebin.com/djnJ7HVy

**Comment by hlissner** [comment]
Please produce [a backtrace](https://discourse.doomemacs.org/how2backtrace) from the error.

**Comment by khmelevskii** [comment]
It works after latest updates. Thank you!
