### ISSUE TITLE
Error during redisplay wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by HouzuoGuo** [doomemacs/doomemacs#7367]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

This is an unexpected error.

### Current behavior

```
[2023-08-22 10:27:38] * 150.203572:*:debug: enabled!
[2023-08-22 10:27:38] * 150.203908:*:debug:vars: magit-refresh-verbose = nil
[2023-08-22 10:27:38] * 150.204254:*:debug:vars: lsp-log-io = nil
Debug mode disabled!
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil) [1774 times]
QuitError during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil) [2 times]
QuitError during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil) [5 times]
evil-line-move: End of bufferError during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil) [15 times]
funcall-interactively: Beginning of bufferError during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil)
Error during redisplay: (eval (doom-modeline-segment--modals)) signaled (wrong-type-argument stringp nil)
...
...
```

### Steps to reproduce

Just open a freshly installed emacs, the same error keeps showing up from multiple doom internal functions.

### System Information

https://pastebin.com/6rUJSTCQ

**Comment by HouzuoGuo** [comment]
Forgot to mention - this has started to happen since yesterday.

**Comment by HouzuoGuo** [comment]
This appears to have already been reported to doom-modeline maintainers: https://github.com/seagle0128/doom-modeline/issues/658
Should be resolved by: https://github.com/seagle0128/doom-modeline/commit/92d95ac9737371d8efcacd517ce9bb0049f9c47c

I'll update to that version and give it a try.

**Comment by blithefeng** [comment]
The problem is caused by a advise in modules/ui/modeline/config.el. The latest version of doom-modeline heavily rely on the result of the function.

```emacs-lisp
(defadvice! +modeline-disable-icon-in-daemon-a (fn &rest args)
    :around #'doom-modeline-propertize-icon
    (when (display-graphic-p)
      (apply fn args)))
```

I try to modify it to:

```emacs-lisp
(defadvice! +modeline-disable-icon-in-daemon-a (fn &rest args)
     :around #'doom-modeline-propertize-icon
     (if (display-graphic-p)
         (apply fn args)
       ""))
```

It works

**Comment by tcx4c70** [comment]
It can be mitigated by removing the advice too.

``` emacs-lisp
(after! doom-modeline
  (undefadvice! +modeline-disable-icon-in-daemon-a (fn &rest args)
    :around #'doom-modeline-propertize-icon))
```

And after that, the icons can be showed in terminal too. It needs a nerd font in terminal tho...
<img width="1053" alt="image" src="https://github.com/doomemacs/doomemacs/assets/16728230/c5ea1988-94e0-458d-b49e-3c0eb4613f38">
