### ISSUE TITLE
Can't set wildcard on M-x rgrep

### ISSUE THREAD

**Issue by hendi** [doomemacs/doomemacs#7370]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I'm in (e.g.) a Python file, I want to `M-x rgrep` within (e.g.) HTML files. It's not possible to enter a custom wildcard in Doom, but it works fine in vanilla Emacs.

### Current behavior

![image](https://github.com/doomemacs/doomemacs/assets/550218/97777dc2-099c-41b0-9b37-83437b7d0b2c)

Not possible to enter a custom value (selection stays at `*.py` and custom value isn't accepted):

![image](https://github.com/doomemacs/doomemacs/assets/550218/2bbb110d-2427-4344-be16-297865332f5f)

### Steps to reproduce

1. Open Emacs
2. Open a `.py` file
3. Run `M-x rgrep`
4. Emacs asks what to "Search for:", enter e.g. `foo`
5. Emacs asks for which files to search in, and defaults to `.py` (since you're in a .py file). Try to enter `*.html`

### System Information

https://pastebin.com/vqmbWAnH

(This issue also occurs on Emacs 28 with a stock Doom install, only change to my config is disabling of evil mode)

**Comment by hlissner** [comment]
You have to press `C-k` / `C-p` to "select" the prompt to enter the custom input.
