### ISSUE TITLE
Quickload Safeguards

### ISSUE THREAD

**Issue by vqhuy** [doomemacs/doomemacs#7376]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Adding `(add-hook 'window-setup-hook #'doom/quickload-session)` to `config.el` should allow us to restore the last session automatically whenever emacs starts.

### Current behavior

The new safeguards introduced in  #7351 caused several issues.
- For people (a quick search on discord says it seems there are a lot) who want to automatically load the last session when starting up emacs, this causes an error on `Wrong number of argument ...`. This is caused due to the new confirmation introduced in #7351.
- Also in #7351, there is a solution proposed to by the author, however there are two problems:

    - If we use `(defadvice! restore-no-confirm-session-quickload-a ()` this makes `(add-hook 'window-setup-hook #'doom/quickload-session)` works again, however a manual `SPC q l` does not work.

    - If we use `(defadvice! restore-no-confirm-session-quickload-a (_)` (suggested in https://github.com/doomemacs/doomemacs/pull/7351#issuecomment-1693406647), `(add-hook 'window-setup-hook #'doom/quickload-session)` does not work.

### Steps to reproduce

Add `(add-hook 'window-setup-hook #'doom/quickload-session)` to `config.el`.

### System Information

https://pastebin.com/Y4XgRsYp

**Comment by hlissner** [comment]
`doom/quickload-session` is intended solely for interactive use, so this is outside its purview. A better option would be to set `persp-auto-resume-time` instead. E.g. 

```lisp
(after! persp-mode
  (setq persp-auto-resume-time 0.5))
```

As this isn't a bug I will close it, but feel free to follow up here.

**Comment by vqhuy** [comment]
Thanks @hlissner , it worked!
