### ISSUE TITLE
Request to bump org-mode version 

### ISSUE THREAD

**Issue by stekern** [doomemacs/doomemacs#7392]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

The `org-set-tags-command` should offer tag completion when being used in an indirect buffer.

### Current behavior

The `org-set-tags-command` hangs indefinitely when being used in an indirect buffer. It works as expected in regular buffers.

The same issue was reported in the org-mode issue tracker at https://list.orgmode.org/orgmode/E1qVc9n-0006Ti-92@rmmprod06.runbox. Based on that bug report, the issue seems to have been introduced in [org-mode@2f7b35ac](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=2f7b35ac89470f17937f5c20524c38db103aaa4c), and fixed in [org-mode@561c1d0d](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?id=561c1d0db0d79c550ca018610072d45d40d6e453).

### Steps to reproduce

Emacs hangs indefinitely when using `org-set-tags-command` in an indirect buffer (e.g., when using a capture template).

### System Information

https://pastebin.com/42LdKcsA

**Comment by maikol-solis** [comment]
It is important to be aware that org-mode 9.7 can break `org-ql` (https://github.com/alphapapa/org-ql/issues/364). There is a fix on the way, though.
