### ISSUE TITLE
MS Python LSP server and Palantir Python LSP server now deprecated

### ISSUE THREAD

**Issue by beojan** [doomemacs/doomemacs#7395]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Both the Microsoft Python LSP server and the Palantir one (two of the three supported by Doom) are now deprecated. Can we have some of the supported ones, like the Spyder fork of the Palantir one here: https://github.com/python-lsp/python-lsp-server?

### Current behavior

N/A

### Steps to reproduce

N/A

### System Information

N/A

**Comment by beojan** [comment]
I found that I needed to patch the Python module for this, otherwise it loads lsp-python-ms if pyright isn't configured.

**Comment by hlissner** [comment]
It's been some time since we dropped lsp-python-ms support, and both lsp-mode and eglot support ruff, pyright, jedi-language-server, etc. so I think this can be safely closed by now. Thanks for bringing it to my attention, in any case!
