### ISSUE TITLE
Creating project using dired not working

### ISSUE THREAD

**Issue by syha6821** [doomemacs/doomemacs#7413]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I'm a new to emacs. So I just try to learn by using it.
And What I'm trying to do is just making simple project.
I make a directory in dired using + command.
And inside that directory I create .projectile file.
If I know correctly, when I revisit that directory, that directory should be registered in project by projectile.
But It wasn't registered. Also not manually registered by SPC-p-a command ( In this case, seems to registered because I can see when I do SPC-SPC, But It does not do project things like SPC-p-p to show inside files etc ... )

### Current behavior

And I made exactly same directory ( and .projectile file ) outside emacs and opened in emacs. and It works like I expected ( visit and registered as project ).
What makes them work differently? 

### Steps to reproduce

1. Open emacs.
2. make directory using dired
3. and make empty .projectile file in that directory
4. and goto that directory
5. do test in that directory , 
6. SPC-SPC to open file list. -> not working (just show project list)
7. SPC-p-a to register that directory as project. -> seems working ( registered in project list) but can't do project things like SPC-SPC in that directory to list files

But works fine when I create directory and .projectile outside emacs and do test in emacs.
( But It can be solved by invalidate cache of that directory ) 

### System Information

https://pastebin.com/XLVHGgm3

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/5a4aa916bc0470ce63e57855eb1483e87414a21a this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
