### ISSUE TITLE
`doom  doctor` reports 'couldn't find "NFM.ttf" font' warning

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#7431]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom doctor` should report 0 warning 0 error.

### Current behavior

After `doom upgrade` to the newest revision `doom doctor` report warning:
```
> Checking Doom core for irregularities...
    ! Warning: couldn't find "NFM.ttf" font
```

### Steps to reproduce

Run `doom doctor` command.

### System Information

https://pastebin.com/bFqjGWBW

**Comment by neolee** [comment]
And I can confirm that there is an `NFM.ttf` file at `.local/straight/repos/nerd-icons.el/fonts/NFM.ttf`.

**Comment by hlissner** [comment]
The issue is that the font isn't installed on your system. You need to run `M-x nerd-icons-install-fonts` or manually install NFM.tff from nerd-icons' repo. I've improved `doom doctor`'s explanation for this issue to reduce confusion. Thanks for bringing it to my attention in any case!

**Comment by neolee** [comment]
@hlissner Thanks! Issue fixed after running `M-x nerd-icons-install-fonts`. Still don't know why the font suddenly missing in the system but anyway :)

**Comment by hlissner** [comment]
Yeah, our switch from all-the-icons to nerd-icons only happened a few days ago (#7411), and there is no automated "install fonts" step in the `doom upgrade` process (and it's hard to add one, because of font system inconsistencies across OSes). So, unfortunately, folks will likely upgrade to suddenly find their icons broken until they run that command.

**Comment by goofansu** [comment]
Tip: You may need to set the `nerd-icons-font-names` if the icon font name is not `NFM.ttf`.

For example, I installed the font with Nix, and the installed font file is "SymbolsNerdFontMono-Regular.ttf":

```nix
(nerdfonts.override { fonts = [ "NerdFontsSymbolsOnly" ]; })
```
 
To make `doom doctor` happy, the code needs to be added to my config:

```emacs-lisp
(setq nerd-icons-font-names '("SymbolsNerdFontMono-Regular.ttf"))
```

**Comment by YellowOnion** [comment]
@hlissner would you consider making doom doctor compatible with the official file names? as per what @goofansu quotes above, this isn't unique to Nix, That's the exact name provided by Nerd fonts.

**Comment by shroomist** [comment]
I'm using the workaround provided by **goofansu**.
it's not only about the doom doctor - the icons/fonts wouldn't be picked up by doom. 
I guess the `nerd-icons-install-fonts` is the preferred way to installing the fonts.

**Comment by hlissner** [comment]
> @hlissner would you consider making doom doctor compatible with the official file names?

I will do so soon.
