### ISSUE TITLE
The overridden `org-tag` slows down `org-roam` file search window

### ISSUE THREAD

**Issue by zedkaido** [doomemacs/doomemacs#7432]
### Theme(s)

doom-homage-black

### What were you expecting?

![Screenshot 2023-05-07 at 14 48 48](https://user-images.githubusercontent.com/96333349/236681461-5d7f5686-2e84-4a77-95fc-ea998d7b4e60.jpg)

### What actually happened?

![Screenshot 2023-05-07 at 14 44 43](https://user-images.githubusercontent.com/96333349/236681492-6927d0ed-544d-41bd-8e00-1c97e0e0d959.jpg)

The following code lines are causing this issue:
```
 ;; make tags and dates to have pretty box around them
((org-tag &override)   :foreground fg :background base1
  :box `(:line-width -1 :color ,base5 :style 'released-button))
```

Not only does it look bad, the `:box` is significantly slowing down navigation

### Steps to reproduce

1. (M-x) org-roam-node-find

### Operating system

OSX

### Emacs version

28.2

### Installed commit of doom-themes

e4f0b006a516a35f53df2dce2ec116876c5cd7f9

**Comment by hlissner** [comment]
This was an issue with doomemacs/doomemacs, so I've transferred it here from doomemacs/themes. In any case, it has been fixed in ae8c5cf. Thanks for bringing it to my attention!
