### ISSUE TITLE
setting +ligatures-prog-mode-list doesn't work

### ISSUE THREAD

**Issue by andresilva** [doomemacs/doomemacs#7433]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

1. set `+ligatures-prog-mode-list` with a set of ligatures
2. only those ligatures should be used

### Current behavior

After setting `+ligatures-prog-mode-list` the original set of ligatures is still used.

### Steps to reproduce

1. `(setq +ligatures-prog-mode-list '("==" "==="))`
2. observe that other ligatures are still used

### System Information

https://pastebin.com/a3NYqcu3

**Comment by andresilva** [comment]
I have been able to workaround the issue like this:

```emacs-lisp
(after! ligature
  (setq +ligatures-prog-mode-list '("==" "===")
        (setq ligature-composition-table nil) ;; this was necessary
        (ligature-set-ligatures 'prog-mode +ligatures-prog-mode-list)))
```

**Comment by hlissner** [comment]
`+ligatures-prog-mode-list` and `+ligatures-all-modes-list` are only written once, which makes them deceptively useless. I'd recommend using `set-font-ligatures!` instead, as it will be the canonical way to modify that list going forward (I will be removing the above variables, since they serve no purpose):

```elisp
(set-font-ligatures! 'prog-mode "==" "===")
```

**Comment by andresilva** [comment]
That also doesn't seem to work. After adding that call to my config I get an error on startup `(void-variable font-ligatures)`.

**Comment by andresilva** [comment]
https://github.com/doomemacs/doomemacs/blob/master/modules/ui/ligatures/autoload/ligatures.el#L76

I guess there's a typo here: s/font-ligatures/ligatures

**Comment by gagbo** [comment]
> I guess there's a typo [here](https://github.com/doomemacs/doomemacs/blob/master/modules/ui/ligatures/autoload/ligatures.el#L76): s/font-ligatures/ligatures. I still think this doesn't work after the typo is fixed, it just appends to `ligature-composition-table` and doesn't remove what's already there for `prog-mode` (although that might be a bug in `ligatures.el`).

Sorry about the typo, forgot to triple check after the refactoring. `set-font-ligatures` is an additive command by default, so this behaviour of not replacing everything is expected. If you want to replace everything you should first have a `(set-font-ligatures! 'prog-mode nil)` call in your config, then add all your customizations

**Comment by andresilva** [comment]
#7436 Doesn't seem to fix the problem. `(set-font-ligatures! 'prog-mode nil)` doesn't reset the ligatures and `ligatures-composition-table` is unchanged.
