### ISSUE TITLE
Can not update cmake-mode

### ISSUE THREAD

**Issue by god464** [doomemacs/doomemacs#7434]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

It will finish the upgrade when run `I doom upgrade`

### Current behavior

When I run `doom upgrade`, I will receive a error:
```bash
  ✓ (180/332) cmake-mode: f9c7a21 -> 6ce5633 [1 commit(s)]
        ERROR: Couldn't collect commit list because: fatal: bad object 6ce56331445ad7ef79a11d5a3163364a883067c2
```

### Steps to reproduce

`doom upgrade`

### System Information

https://fars.ee/ptNo

**Comment by hlissner** [comment]
Looks like https://github.com/emacsmirror/cmake-mode/commits/6ce56331445ad7ef79a11d5a3163364a883067c2 was deleted/force pushed at some point. I've bumped it in 5f3a667 which should resolve your issue. Thanks for bringing it to my attention!
