### ISSUE TITLE
Error opening org-mode file with org-babel source blocks

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#7437]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Org-mode document with org-babel source block should be open and rendered without error.

### Current behavior

Opening org-mode document with org-babel source block brings error info in Message buffer:
```
Error during redisplay: (jit-lock-function 1) signaled (error "Selecting deleted buffer")
```
And the doc display is buggy:
![screens](https://github.com/doomemacs/doomemacs/assets/24796/6addf1ef-372b-423d-bbf4-394f23c76052)

And the backtrace as below:
[debug.log](https://github.com/doomemacs/doomemacs/files/12642449/debug.log)

I don't know but maybe related to ligature and the recent font switch?

### Steps to reproduce

Open any org-mode document with org-babel source block.

### System Information

https://pastebin.com/bFqjGWBW

**Comment by honza** [comment]
I have the same problem.  This also happens with dynamic blocks.

**Comment by neolee** [comment]
@honza seems related to org-mode 9.7 master branch, pinning to the latest 9.6.x release works for me:
```
(package! org :pin "806abc5a2bbcb5f884467a0145547221ba09eb59")
```

Also recommend Doom to re-consider the version strategy which follows org-mode master branch. @hlissner

**Comment by honza** [comment]
Pinning org mode to the latest tag solves this for me

**Comment by tjstankus** [comment]
This still seems to be an issue. I rolled all the way back to org `9.6.30` to get `org-insert-structure-template` to work:

`(package! org :pin "071c6e986c424d2e496be7d0815d6e9cd83ae4e6")`

**Comment by hlissner** [comment]
Org was bumped to v9.7.11 in 0dc1084e8a915d778af7cc5774477ffb3daa0b0a (and will only be bumped to tagged releases from this point on). Since I can no longer reproduce this, I'll consider this resolved.  Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by tjstankus** [comment]
Yes, this is resolved for me now. Thank you!
