### ISSUE TITLE
ligatures: Extra symbols enabled unconditionally without +extra flag

### ISSUE THREAD

**Issue by smsegal** [doomemacs/doomemacs#7440]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I enable the updated `ligatures` module without the `+extra` flag, I expect only font ligatures to be enabled. 

### Current behavior

When I enable the `ligatures` module without the `+extra` flag, I still have extra symbols replaced. In particular, `lambda` in python code is getting replaced with the lambda symbol.

I've tried the following to resolve this with no effect: 

1. `(setq +ligatures-extra-symbols nil)`
2. `(setq +ligatures-extras-in-modes nil)`
3. `(global-prettify-symbols-mode nil)`
4. wrapping all of the above in an `(after! ligatures)` sexp. 

### Steps to reproduce

1. Enable ligatures without `+extra` in `init.el`
2. Observe extra symbols being prettified in buffers.

### System Information

https://pastebin.com/FZsNKwxz

**Comment by gagbo** [comment]
@hlissner I _think_ this [line](https://github.com/doomemacs/doomemacs/blame/2be3cf4b38251eae13cba5daf6ae5bb6964de4a4/modules/ui/ligatures/config.el#L137-L137) should be

```diff
-(when (and (or in-mode-p in-mode-extras-p)
+(when (and in-mode-extras-p
``` 

And it might fix this.

**Comment by smsegal** [comment]
@gagbo just tried it, can confirm it works. Thanks!

**Comment by real-or-random** [comment]
> @hlissner I _think_ this [line](https://github.com/doomemacs/doomemacs/blame/2be3cf4b38251eae13cba5daf6ae5bb6964de4a4/modules/ui/ligatures/config.el#L137-L137) should be
> 
> ```diff
> -(when (and (or in-mode-p in-mode-extras-p)
> +(when (and in-mode-extras-p
> ```

Yes, after 46d7404befcdf5a69cc164fe448ac75bd9b9b598, we need to enable `prettify-symbols-mode` only when with `+extra`. But the code in the module is still correct in essence because it doesn't add the extra symbols to the alist. *But* there's another thing going on, namely this default `lisp-mode`, which just sets the lambda:
```
(defconst lisp-prettify-symbols-alist '(("lambda"  . ?λ))
  "Alist of symbol/\"pretty\" characters to be displayed.")
```
(see https://github.com/emacs-mirror/emacs/blame/a61cc138edeee269e8cf62c13058d5258310d7bc/lisp/emacs-lisp/lisp-mode.el#L188-L189 )

And yes, I have this in my config, and it's another workaround:
```
  (setq-default lisp-prettify-symbols-alist nil))
```

So the right way to resolve this is:
 - Set `lisp-prettify-symbols-alist` to `nil`, probably in the `emacs-lisp` module, because that definition conflicts with this module  (the rust module does the same)
 - Enable `prettify-symbols-mode` only when `+extra` is set (just for performance)

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/5ad99220b86ae1bf421861dfad24492d768ac4d9, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by smsegal** [comment]
Just tested it out, the ligatures module is now working as advertised. Thanks for the fix!

**Comment by real-or-random** [comment]
@hlissner 

> Set `lisp-prettify-symbols-alist` to `nil`, probably in the `emacs-lisp` module, because that definition conflicts with this module (the rust module does the same)

 This part still needs to be done for the special case of the lambda symbol in lisp (see my comment above for explanation)

To reproduce:
 - Enable `+extra`
 - Have this in your config, which should disable all extra symbols. `(setq +ligatures-extra-symbols nil)` 
 - Observe that the lambda symbol is still used to replace `lambda` in the lisp mode.

**Comment by hlissner** [comment]
From [bd1409](https://github.com/doomemacs/doomemacs/commit/bd140955164ca854450c52f4b5c4ca9e0f5c878b), `lisp-prettify-symbols-alist` will be nil. I figure it's better to set from the ligatures module, since what I'm addressing is the interaction between `lisp-prettify-symbols-alist` and a null `+ligatures-extra-symbols`. Thanks for letting me know!

**Comment by real-or-random** [comment]
> I figure it's better to set from the ligatures module, since what I'm addressing is the interaction between `lisp-prettify-symbols-alist` and a null `+ligatures-extra-symbols`. Thanks for letting me know!

That's also reasonable. Just to let you know, it's different in the rust module:
https://github.com/doomemacs/doomemacs/blob/73460f42fd9a7bca76b7b5be47c4d3b6f8aa1040/modules/lang/rust/config.el#L45-L46

**Comment by hlissner** [comment]
With [c07f359](https://github.com/doomemacs/doomemacs/commit/c07f359d648a447ebeaaa3a89a69a3a25c3d0366) I've adopted a new strategy: 

1. Just don't activate `prettify-symbols-mode` in buffers whose mode has no (or an empty) `+ligatures-extras-alist` entry. 
2. In modes with a non-empty entry, `prettify-symbols-alist` will overwrite its buffer-local value (ignoring any defaults left behind by the likes of `lisp-prettify-symbols-alist` or `rust-prettify-symbols-alist`), while still respecting the global, default value of `prettify-symbols-alist`. 

This should make `+extra` behave more predictably without having to play whack-a-mole with all these mode variables. Plus, the user gets the option to enjoy those mode defaults if they enable `prettify-symbols-mode` themselves (with or without `+extra`).

**Comment by real-or-random** [comment]
Nice, I think that's indeed simple and predictable!

**Comment by real-or-random** [comment]
I don't have time to look into this right now, but c07f359d648a447ebeaa breaks org-mode for me when `+extra` is enabled:

```
Debugger entered--Lisp error: (wrong-type-argument listp org-mode)
  car(org-mode)
  prettify-symbols--make-keywords()
  prettify-symbols-mode(1)
  (progn (setq prettify-symbols-alist (append symbols (default-value 'prettify-symbols-alist))) (if (and (boundp 'prettify-symbols-mode) prettify-symbols-mode) (progn (prettify-symbols-mode -1))) (prettify-symbols-mode 1))
  (if symbols (progn (setq prettify-symbols-alist (append symbols (default-value 'prettify-symbols-alist))) (if (and (boundp 'prettify-symbols-mode) prettify-symbols-mode) (progn (prettify-symbols-mode -1))) (prettify-symbols-mode 1)))
  (let* ((s (and t (+ligatures--enable-p +ligatures-extras-in-modes))) (symbols (and s (let* ((symbols (and t ...))) (if symbols symbols (let* (... ... ... ... --cl-var--) (while ... ...) --cl-var--)))))) (if symbols (progn (setq prettify-symbols-alist (append symbols (default-value 'prettify-symbols-alist))) (if (and (boundp 'prettify-symbols-mode) prettify-symbols-mode) (progn (prettify-symbols-mode -1))) (prettify-symbols-mode 1))))
  (progn (let* ((s (and t (+ligatures--enable-p +ligatures-extras-in-modes))) (symbols (and s (let* ((symbols ...)) (if symbols symbols (let* ... ... --cl-var--)))))) (if symbols (progn (setq prettify-symbols-alist (append symbols (default-value 'prettify-symbols-alist))) (if (and (boundp 'prettify-symbols-mode) prettify-symbols-mode) (progn (prettify-symbols-mode -1))) (prettify-symbols-mode 1)))))
  (if after-init-time (progn (let* ((s (and t (+ligatures--enable-p +ligatures-extras-in-modes))) (symbols (and s (let* (...) (if symbols symbols ...))))) (if symbols (progn (setq prettify-symbols-alist (append symbols (default-value ...))) (if (and (boundp ...) prettify-symbols-mode) (progn (prettify-symbols-mode -1))) (prettify-symbols-mode 1))))))
  +ligatures-init-extra-symbols-h()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(org-mode-hook)
  org-mode()
  funcall-interactively(org-mode)
  command-execute(org-mode record)
  execute-extended-command(nil "org-mode" #("org mode" 0 7 (wrap-prefix "    " ws-butler-chg chg fontified t) 7 8 (wrap-prefix "    " ws-butler-chg chg fontified nil)))
  funcall-interactively(execute-extended-command nil "org-mode" #("org mode" 0 7 (wrap-prefix "    " ws-butler-chg chg fontified t) 7 8 (wrap-prefix "    " ws-butler-chg chg fontified nil)))
  command-execute(execute-extended-command)
```

(Sorry, it seems that whenever I comment on commit, this starts a cascade of issues and fixups... :D)

**Comment by hlissner** [comment]
I think that's fixed by https://github.com/doomemacs/doomemacs/pull/8071, which I just merged.
