### ISSUE TITLE
Can not download deno-ls via lsp-install-server

### ISSUE THREAD

**Issue by god464** [doomemacs/doomemacs#7446]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

It should have an option to install deno-ls when I run `M-x lsp-install-server'.

### Current behavior

I cannot find this option, but according to the document and the `M-x describe-variable' it should support it.

### Steps to reproduce

1. `M-x lsp-install-server` or open a new javascript file without any settings.
2. Type deno-ls like this: https://fars.ee/RtnD.png

### System Information

https://fars.ee/kSDw

**Comment by elken** [comment]
There's no installer setup for deno-ls, and this should be reported [upstream](https://github.com/emacs-lsp/lsp-mode/issues/new/choose)
