### ISSUE TITLE
`doom sync --profile` broken due to `noninteractive`

### ISSUE THREAD

**Issue by hpfr** [doomemacs/doomemacs#7457]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom sync --profile FOO` should work per: https://github.com/doomemacs/doomemacs/blob/3983fba5b5d9ed0b707cfa49dcab2038d5b2aed2/profiles/README.org#L38

### Current behavior

```
0 2023-09-23 11:47:01 $ doom profiles sync
Loading /nix/store/qkasnjq86si8vspaxpz0rm9s96i21hdz-emacs-pgtk-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
  > Synchronizing 2 known profiles...
    - Added sandbox
    ✓ Regenerated profile loader: ~/.config/emacs/profiles/load.el
✓ Finished in 0.10372s


0 2023-09-23 11:47:06 $ doom sync --profile sandbox
Loading /nix/store/qkasnjq86si8vspaxpz0rm9s96i21hdz-emacs-pgtk-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
Loading /nix/store/qkasnjq86si8vspaxpz0rm9s96i21hdz-emacs-pgtk-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
> Synchronizing "sandboxEMACSDIR=/home/lh/.config/emacs/" profile...
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Purging orphaned packages (for the emperor)...
    - Skipping builds
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
    - Skipping native bytecode
  > (Re)building profile in /home/lh/.local/share/doom/sandboxEMACSDIR=/home/lh/.config/emacs/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.local/share/doom/sandboxEMACSDIR=/home/lh/.config/emacs/@/0init.29.el...
    ✓ Built init.29.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 2.46945s
0 2023-09-23 11:47:19 $ ls ~/.local/share/doom/
'sandboxEMACSDIR='
```

I think this is because `command-line-args` is unset here, so `profile` is `nil`: https://github.com/doomemacs/doomemacs/blob/3983fba5b5d9ed0b707cfa49dcab2038d5b2aed2/early-init.el#L54-L61

When I added `(message "profile is %s" profile)` after the `let` and `(message "set DOOMPROFILE to %s" profile)` after the subsequent `(setenv "DOOMPROFILE" profile)`, I got some strange output:
```
0 2023-09-23 13:03:22 $ doom sync --profile sandbox
profile is nil
Loading /nix/store/qkasnjq86si8vspaxpz0rm9s96i21hdz-emacs-pgtk-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
profile is sandboxEMACSDIR=/home/lh/.config/emacs/
set DOOMPROFILE to sandboxEMACSDIR=/home/lh/.config/emacs/
Loading /nix/store/qkasnjq86si8vspaxpz0rm9s96i21hdz-emacs-pgtk-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
> Synchronizing "sandboxEMACSDIR=/home/lh/.config/emacs/" profile...
```

It’s like this file is loaded twice with different contexts? I don’t know. I considered attempting to fix this, but the code is pretty hairy, and I don’t have an ergonomic way to test Emacs 28 currently. The `DOOMPROFILE` environment variable works fine as a workaround. In fact, I’m guessing you didn’t catch `--profile` was broken because you use the environment variable. Maybe you could just drop one of the two interfaces?

Then again, I’m surprised no one else ran into this, so maybe something weirder is happening…

### Steps to reproduce

see previous

### System Information

https://pastebin.com/mmJ3391G

**Comment by hlissner** [comment]
Good catch. This should be fixed in fe18640. Let me know if that isn't the case!
