### ISSUE TITLE
centaur-tabs-line error when starting emacs as server

### ISSUE THREAD

**Issue by fishman** [doomemacs/doomemacs#7477]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Tabs should show up when using emacsclient. centaur-tabs is currently broken when using it in server mode through emacsclient. Upstream documents this in the following link https://github.com/ema2159/centaur-tabs/issues/173

None of the fixes from https://github.com/doomemacs/doomemacs/issues/6280 work.

### Current behavior

When using emacs daemon doom will throw the following error messages

Error during redisplay: (eval (centaur-tabs-line)) signaled (wrong-type-argument stringp nil)

### Steps to reproduce

1. Open emacs server
2. open emacsclient
3. open a file

### System Information

https://pastebin.com/rqZKCyki

**Comment by hlissner** [comment]
I'd consider this an upstream issue, but fddc912 should hopefully fix it. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
