### ISSUE TITLE
[Windows] `selection-coding-system` set to `utf-8` instead of default `utf-16le-dos` (again)

### ISSUE THREAD

**Issue by PRESFIL** [doomemacs/doomemacs#7479]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

The encoding on Windows must be UTF-16 for the clipboard to work.

### Current behavior

Non-ASCII characters are not decoded correctly, resulting in escape sequences as in

- #1284
- #5961
- #6398, in which everything was fixed, but immediately after 2 weeks during an unsuccessful refactoring
- https://github.com/doomemacs/doomemacs/commit/6a83079d2e1fa947adf29b816e95861a6b96e9f2 introduced regression, inverting condition from `unless` to `when`

### Steps to reproduce

1. Open Emacs
2. Try to paste text, which contains non-latin characters, from Windows clipboart to Emacs buffer

### System Information

Unable to access to work computer

**Comment by PRESFIL** [comment]
Any updates on this?

**Comment by hlissner** [comment]
Sorry for the wait. As of 659f7bf this should be resolved. Let me know if that isn't the case and I'll reopen this. Thanks for bringing it to my attention!
