### ISSUE TITLE
+lookup/reference does not open/switch to file

### ISSUE THREAD

**Issue by npajkovsky** [doomemacs/doomemacs#7483]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [ ] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

C-c cD should pen file and set cursor on the reference. 

### Current behavior

But it does not do that. Instead, it stays in the same buffer. If I open the file manually, the cursor is there.

Note xref-find-references (C-c c D) does the right thing(tm). What I don't understand why both functions are bound to the same C-c c D.

+lookup/references (C-c c D)                                 Show a list of usages of IDENTIFIER (defaults to the symbol at point)
xref-find-references (C-c c D)                               Find references to the identifier at point.

### Steps to reproduce

``` shell
cargo new lookup
cd lookup
-> % cat src/xref.rs
pub(crate) fn find_me() {}

> % cat src/main.rs
mod xref;

fn main() {
    xref::find_me();
}
```
close xref buffer, go to the main.rs and run `M-x +lookup/references`.  It won't open the file.

### System Information

https://pastebin.com/RUtSZcYM

**Comment by zhyzky** [comment]
The same with c-mode/cpp-mode with
lookup-definition function set to rtags (the default setting)
And this may be related to the lookup function
``` lisp
(defun +lookup--run-handlers (handler identifier origin)
  (doom-log "Looking up '%s' with '%s'" identifier handler)
  (condition-case-unless-debug e
      (let ((wconf (current-window-configuration))
            (result (condition-case-unless-debug e
                        (+lookup--run-handler handler identifier)
                      (error
                       (doom-log "Lookup handler %S threw an error: %s" handler e)
                       'fail))))
        (cond ((eq result 'fail)
               (set-window-configuration wconf)
               nil)
              ((or (get handler '+lookup-async)
                   (eq result 'deferred)))
              ((or result
                   (null origin)
                   (/= (point-marker) origin))
               (prog1 (point-marker)
                 (set-window-configuration wconf)))))                                  <---here
    ((error user-error)
     (message "Lookup handler %S: %s" handler e)
     nil)))
```
When the result return is t, the above line will set the window buffer back to origin.
Maybe in cc-module the rtags-find-symbol-at-point should add a :async t property.

**Comment by npajkovsky** [comment]
I have switched to vertico. Problem go away.

**Comment by dekkers** [comment]
For anyone running into the same problem: If you enable the lookup module it will take over (C-c c D)  and M-?, so if you want to have to keys do xref-find-references you need to disable the lookup module or override the keymap.
