### ISSUE TITLE
Icons are broken on Emacs 29.1, macOS 14

### ISSUE THREAD

**Issue by andreypudov** [doomemacs/doomemacs#7484]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Icons should displayed with correct glyphs.

### Current behavior

Icons are broken in multiple places of the Doom Emacs, including the dashboard:

<img width="958" alt="image" src="https://github.com/doomemacs/doomemacs/assets/9801177/c35d580f-3643-435c-95e9-f8ec02882390">

### Steps to reproduce

1. Install Emacs
brew tap d12frosted/emacs-plus
brew install emacs-plus --with-native-comp
2. Install Doom configuration
3. Run Emacs

### System Information

https://pastebin.com/dXUy1NKM

**Comment by g0rr0g** [comment]
Just fixed an issue with my setup by running `nerd-icons-install-fonts`. Apologies if this is totally off-topic :grimacing:

**Comment by andreypudov** [comment]
> Just fixed an issue with my setup by running `nerd-icons-install-fonts`. Apologies if this is totally off-topic 😬

Thank you a lot! This solved the problem!

**Comment by dsbahr** [comment]
Just had the same issue on Windows 11, with Emacs 29.1. Fresh install and ran `M-x all-the-icons-install-fonts' reloaded, but my icons didn't show. 

Then I tried running `M-x nerd-icons-install-fonts` restarted emacs again, and then my icons worked.
