### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by jgfox** [doomemacs/doomemacs#7485]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect the font icons to display correctly.

### Current behavior

![emacs_font_error](https://github.com/doomemacs/doomemacs/assets/3915034/8b584814-8e1b-45d8-963a-82e8d2f33045)

I'm getting the above for Linux.  MacOS is similar with the wrong icons but slightly different icons for "reload last session" and "jump to bookmark".  I have done the following in ensuring the fonts are installed:

1. Installed all-the-icons via M-x command
2. Installed all-the-icons via distro file repository: AUR for EndeavourOS using yay, Brew for MacOS
3. Did a git pull of all-the-icons.el, copied the appropriate icon files in ~/.local/share/fonts and verified that all files are the right size. Library/Fonts for Mac was verified.
4. I have reinstalled Doom Emacs several times.

Each of these steps I have run fc-cache -f to clear the font cache.  I have fun fc-list and verified that .local/share/fonts contents is listed (Library/Fonts for Mac) .

I apologize if I'm cluttering the report, this has been an issue for a month now despite my updating of Doom Emacs on a regular basis hoping for a fix.

### Steps to reproduce

1. Open Emacs
2. Notice the failure

### System Information

https://pastebin.com/QgdVkhhM

**Comment by g0rr0g** [comment]
Just fixed an issue with my setup by running `nerd-icons-install-fonts`. Apologies if this is totally off-topic :grimacing:

**Comment by supersven** [comment]
I had the same issue on NixOS / Emacs 29.1: Running `nerd-icons-install-fonts` fixed it on my machine, too.

**Comment by jgfox** [comment]
nerd-icon-install-fonts worked.

Thanks everyone.
