### ISSUE TITLE
`doom/sandbox` calls `doom-initialize`, which was removed

### ISSUE THREAD

**Issue by lyterk** [doomemacs/doomemacs#7486]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`(doom/sandbox)`. `C-c C-d` to execute Vanilla Doom. A frame should open with Vanilla Doom, only core modules loaded.

### Current behavior

The new frame opens with the error:

```Debugger entered--Lisp error: (void-function doom-initialize)
  (doom-initialize)
  (let ((doom-init-modules-p t)) (doom-initialize) (doom-initialize-core-modules))
  load-with-code-conversion("/tmp/doom-sandbox/init.el" "/tmp/doom-sandbox/init.el" nil t)
  command-line-1(("-l" "/tmp/doom-sandbox/init.el"))
  command-line()
  normal-top-level()
```

**I believe that `(doom-initialize)` is a vestigial call, removed in the commit `1402db512 * @ refactor: how Doom starts up`.**

There was a lot of consolidation going on to refactor how doom starts up at the time. 

[Discord issue here](https://discord.com/channels/406534637242810369/1158930907118452746/1158930907118452746)

### Steps to reproduce

1. Open Emacs, call `(doom/sandbox)` or SPC h E.
2. Press `C-c C-d` to open a Vanilla Doom sandbox.

Reproduced in fresh install of doom and emacs, generated config.

### System Information

https://pastebin.com/Z7jQK0KU

**Comment by jhacksworth** [comment]
Same result here.

### System Information

https://pastebin.com/1z8dbD5a

**Comment by hlissner** [comment]
Sorry for the delay. As of https://github.com/doomemacs/doomemacs/commit/60083a2626dc5f5e91c39d85b65259d838e06a69 and https://github.com/doomemacs/doomemacs/commit/a022e55c08a18cfed97c0695da45553f7f73ab82, `doom/sandbox` should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
