### ISSUE TITLE
Switch to workspace (non-evil mode):  C-c w-w produces error: Switch to workspace: [Error in post-command-hook (ivy-queue-exhibit): (wrong-type-argument listp leaf)]

### ISSUE THREAD

**Issue by cletus-snapit** [doomemacs/doomemacs#7499]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

**relevant init.el settings
(ivy +fuzzy)

**Doom/Emacs  version:
GNU Emacs     v28.2                       nil
Doom core     v3.0.0-pre               HEAD -> master 986398504 2023-10-07 02:33:45 +0200
Doom modules  v23.09.0-pre     HEAD -> master 986398504 2023-10-07 02:33:45 +0200

**OS: Debian bookworm 

**Expected behavior:
the command  C-c w-l  allows one to load the saved session of choice. Good
issuing the command C-c w-w is expected display the list of work spaces 

### Current behavior

After loading the saved session of choice using, C-c w-l,
When I issue the command : C-c w-w, I get this debug error:
"Switch to workspace: [Error in post-command-hook (ivy-queue-exhibit): (wrong-type-argument listp leaf)]"

Interestingly, at startup of doom, just before loading the saved session,
C-c w-w works fine. It displays :  main      *No buffers*

![doomSwitchTocmdFail](https://github.com/doomemacs/doomemacs/assets/94402716/128f089a-e7af-4ce3-b321-02602c451146)

### Steps to reproduce

1. Open emacs
2. run: C-c w-c to open a new work space
3. run: C-c w-c to open another workspace
4. run: C-c w-s to save the session
5. close emac (C-x C-c)
6. Launch emacs again and run C-c w-l  and load the previously saved session
7. Now run C-c w-w to select the list of workspace that you want to choose from: Above error is displayed
8. Interestingly, C-c w-d displays the list of workspace in the mode line fine. C-c w-w is however very convenient if it works

Thank youu

### System Information

https://pastebin.com/dV6UpPuX

**Comment by cletus-snapit** [comment]
Thanks for you comments in advance

**Comment by cletus-snapit** [comment]
It seems this is the same issue as this: https://github.com/Yevgnen/ivy-rich/issues/119

**Comment by cletus-snapit** [comment]
Fixed now. Now sure how it all works but putting:

(require 'ivy) 

in my config.el file made the error message go away. I can now type "C-c w-w" and the list of work spaces pops up nicely

**Comment by drayah** [comment]
```
(require 'ivy)
```
 in `config.el` worked for me too, thanks for the tip

**Comment by ThunderHeavyIndustries** [comment]
I had the same issue on OSX in evil mode, `(require 'ivy)` fixed this for me as well

**Comment by YellowOnion** [comment]
Can someone turn this in to proper fix? @hlissner

**Comment by hlissner** [comment]
As of 90070c6 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
