### ISSUE TITLE
"There was an unexpected runtime error" during a fresh install

### ISSUE THREAD

**Issue by adamroyjones** [doomemacs/doomemacs#7501]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect to be able to install Doom Emacs following the instructions given.

### Current behavior

Installation fails.

There are similar issues when attempting to upgrade an existing installation. (Failures to upgrade existing installations on multiple machines on multiple networks led to attempting a fresh installation.)

The steps in the reproduction lead to errors like the below. The failures do not happen at a consistent place; the package that causes the problem is indeterminate. Perhaps the issue is GitHub. I don't know. I'd just like to edit text.

I'd add the associated log file to Pastebin but the file is too large.

```
Cloning into '/root/.config/emacs'...
remote: Enumerating objects: 1166, done.
remote: Counting objects: 100% (1166/1166), done.
remote: Compressing objects: 100% (1044/1044), done.
remote: Total 1166 (delta 88), reused 574 (delta 79), pack-reused 0
Receiving objects: 100% (1166/1166), 1.14 MiB | 3.05 MiB/s, done.
Resolving deltas: 100% (88/88), done.
Installing Doom Emacs!

✓ Created ~/.config/doom/
  - Creating ~/.config/doom/init.el
  ✓ Done!
  - Creating ~/.config/doom/config.el
  ✓ Done!
  - Creating ~/.config/doom/packages.el
  ✓ Done!
Generate an envvar file? (see `doom help env` for details) (y or n) y
> Generating envvars file
  ✓ Generated ~/.config/emacs/.local/env
Installing plugins
> Installing straight...
> Installing packages...
  > Updating recipe repos...
  > Cloning use-package... emacsmirror-mirror...
  - Checked out use-package: a6e856418d2ebd053b34e0ab2fda328abeba731c
  > Building use-package...
  > Building use-package > Building bind-key...
  > Building use-package...
  > Cloning auto-minor-mode...
  - Checked out auto-minor-mode: 17cfa1b54800fdef2975c0c0531dad34846a5065
  > Building auto-minor-mode...
  > Cloning gcmh...
  - Checked out gcmh: 0089f9c3a6d4e9a310d0791cf6fa8f35642ecfd9
  > Building gcmh...
  > Cloning explain-pause-mode...
  - Checked out explain-pause-mode: 2356c8c3639cbeeb9751744dbe737267849b4b51
  > Building explain-pause-mode...
  > Building straight...
  > Cloning all-the-icons.el...
  > Building all-the-icons...
  > Cloning nerd-icons.el...
  > Building nerd-icons...
  > Cloning emacs-hide-mode-line...
  > Building hide-mode-line...
  > Cloning highlight-numbers...
  - Checked out highlight-numbers: 8b4744c7f46c72b1d3d599d4fb75ef8183dee307
  > Building highlight-numbers...
  > Building highlight-numbers > Cloning parent-mode...
  > Building highlight-numbers > Building parent-mode...
  > Building highlight-numbers...
  > Cloning rainbow-delimiters...
  - Checked out rainbow-delimiters: f40ece58df8b2f0fb6c8576b527755a552a5e763
  > Building rainbow-delimiters...
  > Cloning restart-emacs...
  x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (arrayp nil)
    Backtrace:
      (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      (shell-quote-argument nil)
      (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
      (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)...
      (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-nam...
      (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-...
      (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n$ %s...
      (let* ((result result) (exit (car result)) (invoked (numberp exit)) (success (...
      (let ((program x55) (args x57) (result x59) (directory x61)) (let* ((result re...
      (progn (ignore (null x62)) (let ((program x55) (args x57) (result x59) (direct...
      (let* ((x61 (car-safe x60)) (x62 (cdr-safe x60))) (progn (ignore (null x62)) (...
      (progn (ignore (consp x60)) (let* ((x61 (car-safe x60)) (x62 (cdr-safe x60))) ...
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.231013195458.6364.error
  ✓ Finished in 34.58737s
```

### Steps to reproduce

Again: this was preceded by failures to upgrade Doom Emacs on multiple computers on multiple networks.

```sh
docker container run -it debian:bookworm bash
```

and then

```sh
apt update && apt install --yes emacs git ripgrep
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
```

### System Information

https://pastebin.com/Pf5QauUr

**Comment by j4wshua** [comment]
I can confirm this on Void Linux as well. Looks like the install script does not like that i.e. https://github.com/melpa/melpa.git/ is 301 moved permanently to https://github.com/melpa/melpa/

**Comment by adamroyjones** [comment]
> You could gzip and upload the log file to GitHub as an attachment.

Thanks (I didn't know I could upload gzips to GitHub!)—I've attached a log [here](https://github.com/doomemacs/doomemacs/files/12902753/err.log.gz) from a new run. The error on this run was essentially the same as [mentioned above](https://github.com/doomemacs/doomemacs/issues/7501#issuecomment-1762360317). That category of error was the common problem I faced when I was trying to grade existing installations.

I've similarly shaped problems with the smaller reproduction you've suggested.

It's a little odd. I'm at a loss. It's difficult to even correlate anything—the overwhelming majority of packages are on GitHub, so it's difficult to know if the forge is the problem.

**Comment by andresilva** [comment]
I'm having the same issue, trying to update also fails (`doom sync -u`). It seems that requests to github are timing out for some reason.

**Comment by henrythebuilder** [comment]
Same here, 
For a couple of days I have been mistaken in the download/access to Github Repo from Doomemacs during upgrade/install operations.
Today trying to install Doomemacs from scratch I had the same problems.
The strange thing that the errors did not always take place at the same point, so the only solution was to try again (and again) the installation until all downloads were successfully completed.
I attach some info [by pastebin](https://pastebin.com/tGShn0LQ) about 'doom info' (after successfull installation) and some errors during installation.
hope this help

**Comment by j4wshua** [comment]
> Same here, For a couple of days I have been mistaken in the download/access to Github Repo from Doomemacs during upgrade/install operations. Today trying to install Doomemacs from scratch I had the same problems. The strange thing that the errors did not always take place at the same point, so the only solution was to try again (and again) the installation until all downloads were successfully completed. I attach some info [by pastebin](https://pastebin.com/tGShn0LQ) about 'doom info' (after successfull installation) and some errors during installation. hope this help

I can confirm re-iterating the installation over and over again works. What also "solves" the problem for me is to use a VPN connection to the United States. Maybe this helps in any way.

**Comment by adamroyjones** [comment]
It's now resolved itself for me. I can only guess it was an issue on GitHub's side, maybe related to my being in the UK and not the US. There's nothing on [their status page's history](https://www.githubstatus.com/history), but that's not dispositive.

😮‍💨 I'm sorry for any time that was wasted.

**Comment by henrythebuilder** [comment]
> It's now resolved itself for me. I can only guess it was an issue on GitHub's side, maybe related to my being in the UK and not the US. There's nothing on [their status page's history](https://www.githubstatus.com/history), but that's not dispositive.
> 
> 😮‍💨 I'm sorry for any time that was wasted.

Same here **now** (from Italy), tried installing/upgrading doomemacs several times.
I apologize too to the doomemacs maintainers!

_... however, the problem remains strange._

**Comment by rafaelcgs10** [comment]
I am having this issue at the moment.
Same error message.

**Comment by Boxit379** [comment]
I'm also getting the same error on MacOS Sonoma with emacs-mac from homebrew. (I'm in Canada)

**Comment by Boxit379** [comment]
Update: It seems to be an issue with undo-fu - I first got the error cloning `emacs-undo-fu-session`, ran the install script again, got the error again cloning `emacs-undo-fu...macsmirror-mirror...`, and then installed the rest without errors the third time. However, I'm getting the error `Error running hook "undo-fu-mode" because: (file-missing Cannot open load file No such file or directory undo-fu` inside emacs now.

**Comment by Qfl3x** [comment]
Can confirm that  a few packages are failing with either this error or #7501 during a fresh install.

**Comment by Suhail-Af** [comment]
Had the same problem today whenever it reached this step `Cloning emacs-undo-fu....`. 
fixed it by running a vpn and installing doom emacs again. No clue where it's trying to get that package from, but that site is  probably blocked by my ISP/Country for whatever reason. The one i know for sure is blocked by my ISP is Codeberg.

**Comment by yytsui** [comment]
same problem here:
` 
  > Building browse-at-remote...
  > Cloning vundo...
  > Checked out vundo: 24271862a2f746be038306eafe20f5eff55c4566
  > Building vundo...
  > Cloning emacs-undo-fu-session...
  x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (arrayp nil)
    Backtrace:
      (replace-regexp-in-string "[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
      (shell-quote-argument nil)
      (mapconcat shell-quote-argument ("git" "branch" "-m" nil) " ")
      (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argument (cons prog...
      (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote-argumen...
      (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name directory)) (mapconcat #'shell-quote...
      (let* ((inhibit-read-only t) (entry (concat (propertize (format "$ cd %s\n$ %s\n\n" (shell-quote-argument (expand-file-name ...
      (let* ((result result) (exit (car result)) (invoked (numberp exit)) (success (and invoked (= 0 exit))) (failure (not success...
      (let ((program x55) (args x57) (result x59) (directory x61)) (let* ((result result) (exit (car result)) (invoked (numberp ex...
      (progn (ignore (null x62)) (let ((program x55) (args x57) (result x59) (directory x61)) (let* ((result result) (exit (car re...
      (let* ((x61 (car-safe x60)) (x62 (cdr-safe x60))) (progn (ignore (null x62)) (let ((program x55) (args x57) (result x59) (di...
      (progn (ignore (consp x60)) (let* ((x61 (car-safe x60)) (x62 (cdr-safe x60))) (progn (ignore (null x62)) (let ((program x55)... 
`
Althought the second run works!

**Comment by yytsui** [comment]
It looks like the second run just skipping the error, because I got the error messge after 'doom run' : Error ruuning hook "undo-fu-mode"
![emacs_error](https://github.com/doomemacs/doomemacs/assets/6809335/008b8da5-16e4-4aa2-a36b-a2532331dd96)

**Comment by lukebarton** [comment]
I cd'd into `~/.emacs.d/.local/straight/repos/emacs-undo-fu-session/` and ran `git pull` and got 
```fatal: unable to access 'https://codeberg.org/ideasman42/emacs-undo-fu-session.git/': OpenSSL/3.0.13: error:16000069
:STORE routines::unregistered scheme```

**Comment by retonlage** [comment]
for anyone else currently having this bug: is it occuring because emacs-undo-fu-sesion is pulled from codeberg. because of this `doom install` will fail with this error whenever codeberg is down. codeberg is currently undergoing maintenance
