### ISSUE TITLE
doom-big-font-mode throws error "No fonts match"

### ISSUE THREAD

**Issue by Dieken** [doomemacs/doomemacs#7510]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

~/.doom.d/config.el

```
(setq doom-font (font-spec :family "Menlo" :size 12))
```

`M-x doom-big-font-mode` should increase font size.

### Current behavior

Execute `M-x doom-big-font-mode`, it worked ago, but now Emacs throws error "No fonts match ‘-*-Menlo-normal-normal-normal-*-12-*-*-*-*-*-*-*’".

### Steps to reproduce

1. Open Emacs
2. Run `M-x doom-big-font-mode`

Extra information:

`M-x describe-font`:

<img width="467" alt="image" src="https://github.com/doomemacs/doomemacs/assets/2365/bfa3dbc3-e6d8-4cb5-a50b-1d57d880eb04">

This issue can be fixed in ~/.doom.d/config.el

```
(setq doom-font (font-spec :family "Menlo" :size 12 :weight 'medium))
```

macOS 14.0,  Emacs 29.1, latest Doom Emacs.

### System Information

https://pastebin.com/f0dZeBan

**Comment by hlissner** [comment]
Did you find a solution to this?
