### ISSUE TITLE
Rustic format regression again

### ISSUE THREAD

**Issue by marcbowes** [doomemacs/doomemacs#7514]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a rust project using `async` syntax using lsp and save the buffer, I expect no errors and for the buffer to be formatted using the lsp server.

### Current behavior

I get an error about formatting failing. This is documented in the rust module too, but is not the desired behavior (see https://github.com/doomemacs/doomemacs/issues/5030). This is because rustfmt is being used to format the buffer.

### Steps to reproduce

1. Create a new cargo project, ala `cargo new test`.
2. Create any function that requires more modern syntax, e.g. `async fn foo() {}`
3. Save the buffer

### System Information

https://gist.github.com/marcbowes/777427ab2367aaa098eab986657a6d1c

**Comment by marcbowes** [comment]
This seems to fix it for me

```
(defun apheleia-inhibit-me ()
  (setq apheleia-inhibit t))

(after! rustic
  (add-hook 'rustic-mode-hook 'apheleia-inhibit-me)
  )
```

**Comment by marcbowes** [comment]
I think I see what happened here.. https://github.com/doomemacs/doomemacs/commit/4ecd616cd8f60640d6b0be2ffc3d762e88099bb4 completely ripped out support for `+format-with-lsp` with `+onsave`.

**Comment by marcbowes** [comment]
```
  (setq rustic-format-trigger 'on-save
        rustic-format-on-save-method #'lsp-format-buffer)
```
this seems to be the smallest extra change to get back to the previous behavior after disabling apheleia. I'm not sure if apheleia supports lsp directly, seems not based on a quick search.

**Comment by henrythebuilder** [comment]
some time ago I too had to change something in the configuration due to rust-formatting, but without disabled anything.
This is my current configuration for rust development (`(rust +lsp +tree-sitter)`):

```
(require 'toml-mode)
;;(require 'flycheck-inline)

(use-package! rustic
              :defer t
              :config
              (my-message "rustic configuration")
              (setq! rustic-format-trigger 'on-save
                     rustic-format-on-save t
                     rustic-format-on-save-method 'rustic-format-buffer
                     rustic-compile-backtrace "1"
                     rustic-compile-directory-method 'rustic-buffer-crate ;;'rustic-project-root
                     ;;rustic-format-display-method #'switch-to-buffer
                     ;;rustic-kill-buffer-and-window nil
                     ;;rustic-compile-display-method #'ace-display-buffer
                     rustic-lsp-server 'rust-analyzer)
              (custom-set-faces!
               '(rustic-message :inherit default)
               '(rustic-compilation-error :inherit compilation-error )
               '(rustic-compilation-warning :inherit compilation-warning)
               '(rustic-compilation-info :inherit compilation-info)
               '(rustic-compilation-line :inherit compilation-line-number)
               '(rustic-compilation-column :inherit compilation-column-number))
              (setq! rustic-ansi-faces ansi-color-names-vector))

(use-package! flycheck
              :defer t
              :config
              (require 'flycheck-rust)
              (push 'rustic-clippy flycheck-checkers))

(add-hook 'rust-mode-hook 'flycheck-mode)

;; https://github.com/flycheck/flycheck-rust
(with-eval-after-load 'rust-mode
  (add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
```

([my doom/info](https://pastebin.com/n8SZ2x2R))

**Comment by marcbowes** [comment]
I landed up reverting my patch locally because I was finding that lsp-mode would get into a weird state after <unknown conditions>. The weird state would have the following symptoms:

1. goto definition would stop working for some types
2. lsp-code-action would do inappropriate things (like do a completely different action)

The only fix I could find to get out of this state was to restart emacs. Toggling lsp-mode, revert-buffer - nothing else worked.

My current state is to use out-of-the-box formatting with doom (via apheleia). I made a rustfmt.toml in my home directory to avoid polluting it per project, which fixes the one error. However, I still don't like this solution. The main regression is that invalid syntax state is handled much better by lsp than rustfmt.

**Comment by hlissner** [comment]
LSP/eglot integration was added to the format module in the past few weeks (beginning with https://github.com/doomemacs/doomemacs/commit/fd1941b95f22ce3649ef7c5b28b9b5c982586bb4 and most recently https://github.com/doomemacs/doomemacs/commit/a0c901cca7607965e771f4d8fe50604d80a34bb6), which should resolve this issue. Remember to enable `:editor format` with the `+lsp` flag to enable this integration. Let me know if that's not the case and I'll reopen this. Thanks for bringing it to my attention!
