### ISSUE TITLE
Treemacs icons are inconsistent, depending on their names

### ISSUE THREAD

**Issue by JonathanReeve** [doomemacs/doomemacs#7519]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect Treemacs to display icons consistently, whether using LSP mode or not. 

### Current behavior

When you start LSP mode before starting Treemacs, the icons display weirdly. Directories, rather than looking small and gray as usual, are large, pixelated, and colored strangely. Files with names like `.project` are green and twice as big, for no reason. 

### Steps to reproduce

To reproduce: 

1. Create a new directory and change into it: `mkdir treemacs-test; cd treemacs-test`
2. Create several directories, some with special names (`bin`, `src`, `test`, etc.), and some without: `mkdir src bin test something else` 
3. Create several files, some with special names (e.g. `.project`): `touch .project something.txt else.txt README.md`
4. Create a file in a language for which you have the `+lsp` flag installed, e.g., add `python +lsp` in your init.el and `touch test.py`
5. Shut down Emacs
6. Open Emacs, and open the file, e.g. `M-x find-file test.py`. This should trigger LSP mode. 
7. Open Treemacs. Notice how the icons for `src`, `bin`, `test` `.project`, and so on look very inconsistent: they're twice as big, full-color, and pixelated. See screenshot:   

<img width="267" alt="Screenshot 2023-10-23 at 1 22 32 PM" src="https://github.com/doomemacs/doomemacs/assets/1843676/c39fd243-ad5e-4dde-aab9-aacfe637a97f">

Note that this doesn't happen if you've already opened Treemacs before starting lsp mode, so you must open the file with LSP before loading Treemacs for the first time. 

### System Information

https://pastebin.com/WaRTfLeD

**Comment by jhacksworth** [comment]
Same result here. Additionally, it looks like the files and directories are not aligned properly, both in the before and after screenshots. 

Before launching lsp:

<img width="191" alt="before" src="https://github.com/doomemacs/doomemacs/assets/286057/4600137e-e461-47c0-a2a8-f9d657cc6aea">

After lsp:

<img width="193" alt="after" src="https://github.com/doomemacs/doomemacs/assets/286057/71ed134e-89a0-4953-911e-5c14a4f76547">

Some system info:

```
system     MacOS 14.0 Darwin 23.0.0 x86_64 ns

GNU Emacs     v29.1            nil
Doom core     v3.0.0-pre       HEAD -> master, origin/master, origin/HEAD 986398504 2023-10-07 02:33:45 +0200
Doom modules  v23.09.0-pre     HEAD -> master, origin/master, origin/HEAD 986398504 2023-10-07 02:33:45 +0200
```

Using the doom-moonlight theme in the screenshots.

**Comment by jhacksworth** [comment]
From https://github.com/Alexander-Miller/treemacs/issues/1016

> It looks that when support for directory-specific icons was added in https://github.com/Alexander-Miller/treemacs/commit/f68a846f3ed593fa9ed081c45f0af9b1c67753a1 , the all-the-icons theme slightly broke:

I pinned treemacs in my `packages.el` to the commit previous to that, https://github.com/Alexander-Miller/treemacs/commit/7c6628a241845cd8f626d2603f747f777de4eefb 

    (package! treemacs :pin "7c6628a241845cd8f626d2603f747f777de4eefb")

And then ran `bin/doom sync -u`.

The file and directory icons are still misaligned, but at least the icons don't change when lsp is active. Works as a stopgap until the underlying cause is resolved.

**Comment by JonathanReeve** [comment]
See also https://github.com/doomemacs/doomemacs/issues/7519 for possible workarounds.

**Comment by JonathanReeve** [comment]
Additionally, I just noticed that these same directories (`bin`, `src`, `test`) and files (`.project`, etc.) will have no icons at all if treemacs is launched before `lsp`. See screenshot: 

<img width="210" alt="Screenshot 2023-11-13 at 11 18 17 AM" src="https://github.com/doomemacs/doomemacs/assets/1843676/a424eb03-aca6-43bd-9304-9586f76fc644">

**Comment by hlissner** [comment]
dec058f should hopefully correct the load order of the involved packages. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
