### ISSUE TITLE
"doom sync" fails with unexpected runtime error

### ISSUE THREAD

**Issue by wilhelmy** [doomemacs/doomemacs#7539]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom sync` should byte-compile `~/.emacs.d` as usual

### Current behavior

doom sync fails with the following runtime error

```
$ ./.emacs.d/bin/doom sync 
x There was an unexpected runtime error
  Message: Wrong type argument
  Details: (stringp adoc-mode)
  Backtrace:
    (intern adoc-mode)
    ((closure ((package . gnu-elpa-mirror) use-package-pre-ensure-function use-package-keywords use-package-ensure-function use-pa...
    (cl--position gnu-elpa-mirror ((adoc-mode :url "https://github.com/bbatsov/adoc-mode") (afternoon-theme :url "https://github.c...
    (cl-position gnu-elpa-mirror ((adoc-mode :url "https://github.com/bbatsov/adoc-mode") (afternoon-theme :url "https://github.co...
    (apply cl-position gnu-elpa-mirror ((adoc-mode :url "https://github.com/bbatsov/adoc-mode") (afternoon-theme :url "https://git...
    (cl-find gnu-elpa-mirror ((adoc-mode :url "https://github.com/bbatsov/adoc-mode") (afternoon-theme :url "https://github.com/os...
    (straight-recipes-nongnu-elpa--translate (cl-find package (straight-recipes-nongnu-elpa--recipes) :key #'(lambda (it) (intern ...
    (straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (apply straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (let ((default-directory (if local-repo (straight--repos-dir local-repo) default-directory)) (func (intern (format "straight-r...
    (let* ((--cl-rest-- recipe) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo))))) (let ((default-directory (if loc...
    (let ((recipe (straight--convert-recipe name cause))) (let* ((--cl-rest-- recipe) (local-repo (car (cdr (plist-member --cl-res...
  ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.231110124247.348981.error
✓ Finished in 0.75764s

```

Furthermore, the string "adoc" does not occur in `~/.doom.d` and I don't remember enabling it myself.

### Steps to reproduce

Run "doom sync", watch it fail.

### System Information

https://paste.xinu.at/LOWQB0/

**Comment by wilhelmy** [comment]
See https://paste.xinu.at/ZCPj/ for the `~/.emacs.d/.local/state/logs/cli.doom.231110124247.348981.error` file containing the extended backtrace

**Comment by wilhelmy** [comment]
I get the same backtrace running every other `~/.emacs.d/bin doom <foo>` I try. purge/build/clean/compile/install, doesn't matter. `adoc-mode` isn't enabled and doesn't really occur in `~/.emacs.d/`
This is really weird, it would be nice if someone with a better understanding of doom could look at it.

**Comment by mathcass** [comment]
I was coming across the same issue as this one. 

However, I happened upon this discussion thread (https://discourse.doomemacs.org/t/error-on-syncing-wrong-type-argument-string-p-afternoon-theme/3432) and decided to just try removing my entire ~/.emacs.d/.local directory. 

That actually resolved the issue so I wonder if there's a missing step for updating these (potentially) out-of-date repos.

**Comment by hlissner** [comment]
Straight (our package manager) downloads the recipe archives from all the usual suspects (MELPA, GNU ELPA, NonGNU ELPA, etc), and I suspect there was a syntax error in the nongnu archive. Since I don't see any such errors now, I'm guessing it was fixed upstream at some point. 

This has happened once before, iirc, and is difficult to handle without suppressing legitimate errors. In any case, the only solution is to delete the local recipe repo and resync, e.g.

```sh
$ rm -rf ~/.config/emacs/.local/straight/repos/nongnu-elpa/
$ doom sync
```

Deleting all of `~/.config/emacs/.local` works too, but will take longer.

In any case, since I'm swapping out Straight for Elpaca soon, I'll close this, since I'm no longer working on improving Straight integration and the switch will tackle *many* issues like these. Thanks for bringing it to my attention, in any case!
