### ISSUE TITLE
lsp-mode pinned to version that breaks on newer typescript lsp

### ISSUE THREAD

**Issue by johnche** [doomemacs/doomemacs#7540]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When opening a `.ts` file, lsp should run without trying to restart.

### Current behavior

When opening a `.ts` file, lsp crashes. Error looks like this

```
error: unknown option '--tsserver-path'

Process ts-ls stderr finished
```

The problem lies in `typescript-language-server` removing the flag from [v4.0.0 to v4.1.0](https://github.com/typescript-language-server/typescript-language-server/commit/cadf3748a8e0de7655260ddeb1ffb30888723aaf) (after having being deprecated for a while), and the fix came to `lsp-mode` [2 weeks ago](https://github.com/emacs-lsp/lsp-mode/pull/4202).

Currently, `lsp-mode` is pinned to a [9 week old commit (266945b)](https://github.com/doomemacs/doomemacs/blob/261f94c768aa986284c6c9b55be101e418ab9b10/modules/tools/lsp/packages.el#L12) which is breaking for anyone that installs a fresh doom emacs, or updates `ts-ls`.

### Steps to reproduce

1. Install emacs/doom
2. Uncomment `lsp` and `(web +lsp)` (i think?) in `init.el`
3. Open `*.ts` file
4. Install `ts-ls` through lsp-mode prompt
5. Should get error now, or open new .ts file

### System Information

https://pastebin.com/ifP169gs

**Comment by krakn-dev** [comment]
i regret pacman -Syu...

**Comment by johnche** [comment]
@krakn-dev a temporary measure i did was to [unpin lsp-mode](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#pinning-packages-to-specific-commits)

```
(unpin! lsp-mode)
```

**Comment by CodEsteban** [comment]
@johnche too late, already switched to neovim

**Comment by krakn-dev** [comment]
@johnche too late, already switched to vscode

**Comment by arnfaldur** [comment]
The `(unpin! lsp-mode)` command can be put into `packages.el` in your doom config folder.
I had to run `doom upgrade` to get the updated `lsp-mode` package and have it built and working with the rest of the system.

**Comment by SleeplessOne1917** [comment]
I also ran into this issue.

**Comment by mickp34** [comment]
Same issue here, on GNU Emacs 27.1 - not doom. Is there a way to solve this issue on this version ? (I'm not fluent in emacs config and not sure how to unpin a package, sorry).
Thx.

**Comment by RolandMarchand** [comment]
Bumping because I need to use a JS LSP in Emacs.

**Comment by Pinjontall94** [comment]
Also bumping bc I'm learning js on emacs and I'd really rather not switch to vsc for one thing!

**Comment by hlissner** [comment]
I've bumped lsp-mode in cb3d019 which should resolve this. Let me know if that isn't the case and I'll reopen it. Thanks for letting me know!
