### ISSUE TITLE
LSP is not automatically started on .cs files if tree-sitter is enabled

### ISSUE THREAD

**Issue by SkyLeite** [doomemacs/doomemacs#7541]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When a C# (`.cs`) file is opened with `tree-sitter` enabled, `lsp!` should run automatically.

### Current behavior

When a C# (`.cs`) file is opened with `tree-sitter` enabled, it uses the major mode `csharp-tree-sitter-mode` instead of `csharp-mode`, so `lsp!` is never run.

### Steps to reproduce

1. Enable `(csharp +lsp +tree-sitter)` in `init.el`
2. Open a `.cs` file
3. Observe that LSP doesn't work until you manually run `M-x lsp!`

Removing the `+tree-sitter` flag makes it work again. `(add-hook 'csharp-tree-sitter-mode-hook #'lsp-deferred)` did not seem to work.

### System Information

https://gist.github.com/SkyLeite/2bba068c47bf61765ab6b1ede205c3d1

**Comment by freddez** [comment]
I have same problem with python-mode and ts-mode

**Comment by hlissner** [comment]
> Removing the +tree-sitter flag makes it work again. (add-hook 'csharp-tree-sitter-mode-hook #'lsp-deferred) did not seem to work.

@SkyLeite Have you tried adding `lsp!` instead of `lsp-deferred` to that hook?
