### ISSUE TITLE
Eager Macro Expansion error breaks LSP when coding in Go

### ISSUE THREAD

**Issue by TheKamboy** [doomemacs/doomemacs#7542]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a Go file, it should show errors in the file and have auto completion.

### Current behavior

When I open a Go file, error handling somewhat works, but no auto completion.

And this pops up:
![image](https://github.com/doomemacs/doomemacs/assets/89111294/991d1b0a-9c51-49e2-a726-41f7e8c0dc41)

### Steps to reproduce

1. Open Emacs
2. Open Go Project
3. Open a Go File

### System Information

https://gist.github.com/TheKamboy/a01f7ddb7bd2b45e6461840be25ad9a1

**Comment by daedric** [comment]
It seems more of an lsp-mode issue... I do have the same issue and I use this patch which "solve" the issue for me: https://github.com/daedric/lsp-mode/commit/317df419b24e16dbd39110818a9d78206f68c9f6

A couple of people also have the issue: https://github.com/emacs-lsp/lsp-mode/pull/4172

**Comment by TheKamboy** [comment]
Thanks! I'll try that when I can.

**Comment by TheKamboy** [comment]
Sorry for late response but it did work! Thanks!
