### ISSUE TITLE
Possible incompatibility between org-journal and org mode versions

### ISSUE THREAD

**Issue by nmoseman** [doomemacs/doomemacs#7545]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

when running 'org-journal-new-entry'  via "SPC n j j" command I expect that:

1.  A new weekly org-journal file is created, if necessary
2. opens the file in a buffer, if necessary
3. Creates a org entry with todays date in the org-journal file, if necessary
4. Creates a time (like ** 12:04) entry under the date entry.

### Current behavior

It is able to do steps 1-3 correctly, but fails to create a date entry.

It throws a message like: 

"org-element-at-point: ‘org-element-at-point’ cannot be used in non-Org buffer"

I can make it work by pinning org-mode to a older version.

When I put the following entry into packages.el:

```
(package! org
  :pin "806abc5a2bbcb5f884467a0145547221ba09eb59")
```

And then exit emacs and run "doom sync -u"

I am then able to open emacs and successfully create the org-journal entry.  Everything seems to be working after that.

The 806abc5a2bbc git reference is tagged "release_9.6.9" in https://git.savannah.gnu.org/git/emacs/org-mode.git

I believe it is related to incompatible changes in org-mode main.  This seems to have impacted quite a few org-related packages.   Like https://github.com/org-roam/org-roam/issues/2361#issuecomment-1632943836

Looks like a lot of packages have been updated to fix it, but I am not sure.  I looked, but didn't spot a bug in org-journal, but I could of easily missed one. Unfortunately I don't have a lot of time to investigate further right now.  I'll try to follow up. 

### Steps to reproduce

1. Open Emacs
2. Execute "SPC n j j"

See it create the new file, new date entry, but not new time entry.

(package! org
  :pin "806abc5a2bbcb5f884467a0145547221ba09eb59")  in package.el and 'doom sync -u' seems to work around the issue.

### System Information

https://gist.github.com/nmoseman/a8713806f625dd8eb435398d4cc87b60

**Comment by SeanMaclochlainn** [comment]
Fyi, I had this same error and created https://github.com/doomemacs/doomemacs/pull/7506 to fix it

**Comment by nmoseman** [comment]
That is fantastic.  Thank you. Pinning org-journal to use the version in your PR fixed it perfectly. 

Closing this as your PR is the fix for it.
