### ISSUE TITLE
eww opens in a window at the bottom instead of a new buffer

### ISSUE THREAD

**Issue by ascob** [doomemacs/doomemacs#7551]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

eww opens a webpage in a new buffer (tested with vanilla emacs)

### Current behavior

eww opens a webpage in a window at the bottom (tested with vanilla doom config)

### Steps to reproduce

1. `M-x eww`
2. `example.com`
3. example.com opens in a narrow window at the bottom

### System Information

https://notebin.de/?946838dc2750838b#GkxpAvvkqYPMi1EoBPamsSwNEYZguWsaEPCvZokZDefK

**Comment by EsAu79p** [comment]
This is what the [popup module does](https://github.com/doomemacs/doomemacs/tree/master/modules/ui/popup).
To disable this behavior you need to comment out the line `(popup +defaults)` from `init.el` in your config. This restores the vanilla behavior of opening in a new buffer. 

If you would like to continue playing with the popup module but dislike the popup opening in the in a narrow window at the bottom, you can consider tweaking the popup rules. For example `eww` launch in a side window that grabs focus and does not exit on `escape` adding the following line to your `config.el` will do the trick:
`(set-popup-rules! '(("^\\*eww" :side right :size 0.50 :select t :quit nil)))`
 For more information on popup rules see the [popup module documentation](https://github.com/doomemacs/doomemacs/tree/master/modules/ui/popup).

**Comment by ascob** [comment]
Thanks a lot, that worked!

**Comment by RyanGibb** [comment]
According to the eww module this shouldn't be the case when eww is invoked directly https://github.com/doomemacs/doomemacs/blob/2bc052425ca45a41532be0648ebd976d1bd2e6c1/modules/emacs/eww/config.el#L30-L32
```
  ;; HACK: There are packages that use eww to pop up html documentation; we want
  ;;   those to open in a popup, but if the user calls `eww' directly, it should
  ;;   open in the current window.
```

**Comment by hlissner** [comment]
Their `M-x doom/info` pastebin expired, so I can't confirm, but OP likely didn't have the eww module active.

**Comment by ascob** [comment]
Thanks a lot! I enabled the eww module and the popup module. It works perfectly!
