### ISSUE TITLE
emacsclient opens only on terminal 

### ISSUE THREAD

**Issue by MahalParida** [doomemacs/doomemacs#7552]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

emacs --daemon ( to start the emacs server)

emacsclient -ca emacs( this command should open emacs in a new window )

### Current behavior

emacsclient -ca emacs( Opens emacs in terminal )

### Steps to reproduce

1. Install emacs-plus in mac
2. install and configure doomemacs
3. start emacs server i.e run emacs --daemon
4. start emacs client i.e emacsclient -ca emacs

### System Information

https://pastebin.com/P7QtG790

**Comment by hlissner** [comment]
```
features   ACL DBUS GMP GNUTLS JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY
	   KQUEUE PDUMPER SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER WEBP
	   XIM XWIDGETS ZLIB
```

It seems your build of Emacs lacks GTK, PGTK, and/or X11 support, so it is incapable of producing GUI frames. You must install a build of Emacs with these features (avoid any emacs packages with `nox` in the name, like [`emacs-nox` on Arch](https://archlinux.org/packages/extra/x86_64/emacs-nox/)).

As this is not a Doom issue, I'll close this, but feel free to follow up here.
