### ISSUE TITLE
+popup--evil-command-window-a has been broken by upstream changes

### ISSUE THREAD

**Issue by rmmanseau** [doomemacs/doomemacs#7556]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`M-x evil-command-window-ex` should not throw errors

### Current behavior

`M-x evil-command-window-ex` throws the error `Wrong type argument: stringp, nil` and then renders incorrectly.

the root cause is that the advice `+popup--evil-command-window-a` which overrides `evil-command-window` has been broken by upstream changes. specifically [this line](https://github.com/doomemacs/doomemacs/blob/master/modules/ui/popup/%2Bhacks.el#L121): `(setq-local evil-command-window-cmd-key cmd-key)`. the equivalent line in the advised function is now `(setq-local evil--command-window-prompt prompt)` 

`evil-command-window-cmd-key` must have been renamed to `evil--command-window-prompt`

### Steps to reproduce

`M-x evil-command-window-ex`

### System Information

https://pastebin.com/RqNxdfiL

**Comment by tim-goto** [comment]
maybe @howsiwei can take a look?

**Comment by tim-goto** [comment]
maybe @howsiwei can take a look?

**Comment by howsiwei** [comment]
Hmm seems like `(set-popup-rule! "^\\*Command Line\\*$" ...)` still works after removing the advice.
```elisp
(advice-remove 'evil-command-window #'+popup--evil-command-window-a)
```
I wonder if the advice is obsolete now that `evil-command-window` no longer calls `switch-to-buffer`.

**Comment by rmmanseau** [comment]
seems like it is to me, i've had `(advice-remove 'evil-command-window #'+popup--evil-command-window-a)` in my config for a while now & its been behaving as expected.
