### ISSUE TITLE
Get error message every format-buffer: if: Symbol’s value as variable is void: apheleia-inhibit-functions 

### ISSUE THREAD

**Issue by colawithsauce** [doomemacs/doomemacs#7568]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Don't display this error message

### Current behavior

Get this error on each format-buffer:
```
if: Symbol’s value as variable is void: apheleia-inhibit-functions 
```

### Steps to reproduce

1. enable the following flags `(format +onsave)`, `(lsp +eglot -peek)` and `(cc +lsp)` (maybe relavant)
2. open a `*.c` file, type some code.
3. save, and the problem reproduce

### System Information

https://pastebin.com/RSKNUcgR

**Comment by gpanago** [comment]
The commit [fbd00b6a08300b453c15410e693823078c9015af ](https://github.com/doomemacs/doomemacs/commit/fbd00b6a08300b453c15410e693823078c9015af) needs to be reverted. That fixes the issue.

**Comment by colawithsauce** [comment]
@gpanago nope, I updated to head of doom, and this problem still here. I run `M-x unload-feature` and type `aphe`, I only get this
![image](https://github.com/doomemacs/doomemacs/assets/51731521/c8fcfa20-6c46-4cc2-9308-c45cd2f079eb)

I also tried `doom sync`, and `doom build`, the issue doesn't gone.

Is that because my configuration? I'm going to keep debuging on it.

**Comment by peterhoeg** [comment]
Alternatively as a workaround, put this in `~/.config/doom/packages.el`:

```lisp
(unpin! apheleia)
```

**Comment by colawithsauce** [comment]
@peterhoeg That works! Thanks

**Comment by peterhoeg** [comment]
Please note @colawithsauce, that the mentioned PR is required in order for `format-buffer` to actually *do* something.
