### ISSUE TITLE
clangd not starting in cuda-mode

### ISSUE THREAD

**Issue by beojan** [doomemacs/doomemacs#7576]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a CUDA buffer, I expect clangd to start (as in a c++-mode buffer)

### Current behavior

clangd does not start.

### Steps to reproduce

1. Open a CUDA file.

### System Information

https://gist.github.com/beojan/0a3a409a23b388d588184a8f4b6e844f

**Comment by hlissner** [comment]
Would this be enough to fix the issue?

```elisp
;; add to $DOOMDIR/config.el
(add-hook 'cuda-mode-local-vars-hook #'lsp!)
```

If so, I'll add it to the `:lang cc` module.

**Comment by beojan** [comment]
That doesn't seem to have worked.

**Comment by hlissner** [comment]
Turns out `cuda-mode` isn't defined as a proper major mode so none of the standard major mode hooks (besides cuda-mode-hook) run for it. As of 36d18d6 this should be fixed. Let me know if that isn't the case.

**Comment by ethercflow** [comment]
Hi @hlissner  I met this issue with 511c8af36537992fd60ff970e19e5638207546ed , whould you please take a look?

When open a `.cu` or `.cuh` file, no line number, no clangd.
