### ISSUE TITLE
https://repo.or.cz/ob-clojure-literate.el.git is down

### ISSUE THREAD

**Issue by Ramblurr** [doomemacs/doomemacs#7586]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`sync -u succeeds`

### Current behavior

```
Loading /nix/store/gb4gjmnr4gw3xpc2xlmxgw8m5d3q3634-emacs-29.1/share/emacs/site-lisp/site-start (native compiled elisp)...
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.emacs.d/.local/env
  > Installing packages...
    - No packages need to be installed
  > (Re)building packages...
    - No packages need rebuilding
  > Updating recipe repos...
  > Updating packages (this may take a while)...
    x The package manager threw an error-date...
    x Last 16 lines of straight's error log:
      [Return code: 0]
      $ cd /home/ramblurr/.emacs.d/.local/straight/repos/lsp-pyright/
      $ git rev-parse HEAD
      54a2acddfdd7c3d31cb804a042305a3c6e60cf81
      [Return code: 0]
      $ cd /home/ramblurr/.emacs.d/.local/straight/repos/pip-requirements.el/
      $ git rev-parse HEAD
      216cd1690f80cc965d4ae47b8753fc185f778ff6
      [Return code: 0]
      $ cd /home/ramblurr/.emacs.d/.local/straight/repos/ob-clojure-literate.el/
      $ git rev-parse HEAD
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [Return code: 128]
    ! Wrote extended straight log to ~/.emacs.d/.local/state/logs/cli.doom.231211090311.38181.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
    ✓ Finished in 41.01890s
```

### Steps to reproduce

1. enable org
2. enable clojure
3. `doom sync -u`

Source line: https://github.com/doomemacs/doomemacs/blob/master/modules/lang/org/packages.el#L120-L127

`repo.or.cz` seems down. Noting this here in the issue, maybe it comes back soon, maybe its gone forever?

### System Information

https://0x0.st/H3tQ.info

**Comment by barakdiker123** [comment]
follow , I have the exact same thing

**Comment by EsAu79p** [comment]
I have just checked and the website seems to be up. 
`doom sync` with org and clojure enabled completes with no issues.

**Comment by FrederickGeek8** [comment]
I faced this issue when upgrading doom via `doom upgrade` and `doom sync -u`. I had only recently started using clojure in Emacs at the time.

I was able to solve this by
```bash
cd ~/.config/doom-emacs/.local/straight/repos/ob-clojure-literate.el/; # cd into the local git repository
git pull origin master; # pull down changes (master branch is empty before)
```

When I tried to pull up `git log` in that local repo initially, there were no commits on the `master` branch. Pulling down those changes manually was necessary to allow `doom upgrade` to proceed.

Looking at `git log` in that directory now I see:
```
commit 18c3ea15b872a43e67c899a9914182c35b00b7ee (grafted, HEAD -> master, origin/master)
Author: stardiviner <numbchild@gmail.com>
Date:   Thu May 27 22:03:35 2021 +0800

    Move ob-clojure-literate out from org-mode contrib/
```

Hope that helps.

**Comment by hlissner** [comment]
As of 1e358ca, the `:lang org` module now installs ob-clojure-literate from https://github.com/emacsattic/ob-clojure-literate, which should resolve this issue going forward. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
