### ISSUE TITLE
Tree-sitter language grammar for python is unavailable

### ISSUE THREAD

**Issue by honuonhval** [doomemacs/doomemacs#7601]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open py file, tree-sitter is activated

### Current behavior

eglot in general wasn't working when I try to enable python-ts-mode manually I see
```
⛔ Warning (treesit): Cannot activate tree-sitter, because language grammar for python is unavailable (not-found): (libtree-sitter-python libtree-sitter-python.0 libtree-sitter-python.0.0 libtree-sitter-python.so libtree-sitter-python.so.0 libtree-sitter-python.so.0.0) No such file or directory
```

### Steps to reproduce

1. enable (lsp +eglot)
2. enable tree-sitter
3. enable (python +lsp +pyright +pyenv +tree-sitter)
4. open py file

### System Information

https://pastebin.com/gCSKBzeh

**Comment by darrenkenny** [comment]
Did you run `treesit-install-language-grammar` to download the ts grammer binaries?

**Comment by honuonhval** [comment]
I didn't run it before but even after running it and renaming all the files (I don't remember having to rename grammar files previously) it still complains about not being able to find libtree-sitter-python.so.  I've also verified that tree-sitter-load-path contains the /bin folder where libtree-sitter-* are located

**Comment by honuonhval** [comment]
![image](https://github.com/doomemacs/doomemacs/assets/43633615/8cd5ac48-037b-4280-9bed-e941c70f8159)

this is what I see when I M-x python-ts-mode

**Comment by honuonhval** [comment]
Made bit of progress, trying to figure out how to get it to work.
```emacs-lisp
(unpin! eglot)
(unpin! lsp-pyright)
(unpin! tree-sitter-langs)
```

set treesit-extra-load-path since the article above mentioned it (even though tree-sitter-load-path is already set to same)
rename all the .so files with libtree-sitter-<lang>.  Eglot--Managed, tree-sitter-hl, and tree-sitter seems to load ok (no more anaconda mode getting loaded).  I still see some error messages in *Messages*

```
Loading project (native compiled elisp)...done
Loading eldoc...done
Loading seq...done
Loading flymake...done
Loading xref...done
Loading jsonrpc...done
Loading external-completion...done
tsc-dyn-get: Using source :github (:loaded nil :recorded emacs-tree-sitter@0.18.0 :requested 0.18.0)
Could not get ‘tsc-dyn’: (error Invalid version syntax: ‘emacs-tree-sitter@0.18.0’ (must start with a number))
tsc-dyn-get: Using source :compilation (:loaded nil :recorded emacs-tree-sitter@0.18.0 :requested 0.18.0)
Could not get ‘tsc-dyn’: (error Invalid version syntax: ‘emacs-tree-sitter@0.18.0’ (must start with a number))
[tree-sitter-langs] Running (git rev-parse --show-toplevel) in <emacsdir>/.local/straight/build-29.1/tree-sitter-langs/
The directory <emacsdir>/.local/straight/build-29.1/tree-sitter-langs/ doesn’t seem to be a git working dir. Grammar-building functions will not work.
tree-sitter-langs: Grammar bundle v0.12.90 was already installed; skipped
Running direnv in <home>/projects/pythonproject/ ... (C-g to abort)
Direnv succeeded in <home>/projects/pythonproject/
File local-variables error: (doom-hook-error python-mode-local-vars-hook tree-sitter! (error Cannot find shared library for language: python))
 [1] main   [2] pythonproject  | Switched to 'pythonproject' in new workspace
Error running timer: (void-function jsonrpc--request-continuations)
```

**Comment by dvzubarev** [comment]
`tree-sitter-langs`, `tree-sitter-load-path`  and `tree-sitter-hl` (and errors in Messages) have nothing to do with `python-ts-mode`. `python-ts-mode` is the new major mode based on treesit library added in Emacs-29. You have to setup `treesit-language-source-alist` variable and call `treesit-install-language-grammar`. That's it, you don't have to rename anything. All of this is described in https://www.masteringemacs.org/article/how-to-get-started-tree-sitter. 
After you did this you can activate `M-x python-ts-mode` in your python buffer. You will get basic syntax highlighting that is worse by default than highlighting from `tree-sitter-hl`.
Since the support for `python-ts-mode` is  not existent in the doom, you have to manually activate lsp or eglot, linters, yasnippet and all other minor modes that you are accustomed to. Moreover you have to manually setup keybindings for that mode (e.g. `,t` prefix), that were available in `python-mode`.
So after all of this hustle, consider whether you really want to use `python-ts-mode`.

**Comment by honuonhval** [comment]
Thank you so much.  I was mistaken.  My python environment, setup just by (python +pyenv +lsp +tree-sitter +pyright), felt broken (somehow much different than about a month ago) so I thought it was because python-ts-mode was broken.  I'll have to figure out why it is broken on my machine.  I'll close this issue.
