### ISSUE TITLE
Update Anaconda Mode Pinned SHA to one that supports Python 3.11+

### ISSUE THREAD

**Issue by kschwab** [doomemacs/doomemacs#7602]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Anaconda mode should work with Python 3.11+.

### Current behavior

See pythonic-emacs/anaconda-mode#436. The issue is also present on spacemacs, etc.

The currently pinned anaconda mode package does not have fix pythonic-emacs/anaconda-mode#437, which added support for python 3.11+.

I have verified that adding the below to my `.doom.d/packages.el` resolves the issue:
```lisp
(unpin! anaconda-mode)
(package! anaconda-mode :pin "92a6295622df7fae563d6b599e2dc8640e940ddf")
```

### Steps to reproduce

Run emacs anaconda mode with python 3.11+.

### System Information

https://gist.github.com/kschwab/a019798033225581265d05b7744d7006

**Comment by EsAu79p** [comment]
I just made a PR that closes this issue. 
I don't think the code you attached does what you expect it to however. 
From your system information it lists anaconda-mode as unpinned and will therefore not stay on the specified commit.

I think what you want is the following snippet
```
(package! anaconda-mode :pin "92a6295622df7fae563d6b599e2dc8640e940ddf")
```
Specifically just remove the `(unpin! anaconda-mode)`.

This just changes the pin to the wanted commit without unpinning it.
