### ISSUE TITLE
Second window with the same buffer moves its point upon view

### ISSUE THREAD

**Issue by ishovkun** [doomemacs/doomemacs#7626]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I often use multiple windows within the same frame to work on a single buffer. These views usually focus on various parts of the buffer, e.g. different functions. I do not expect the unfocused window to move it's view while I save the buffer in the main window. 

### Current behavior

When I save buffer in the first window, the second window changes its view to the point of the most recent change.

### Steps to reproduce

1. Open emacs
2. Open a file in two windows that form a vertical split. The file should be sufficiently large so that it does not fit into the window vertically.
3. work for a while on a file and save periodically. Sometimes, the view in the second window will not move, but sometimes it will.

### System Information

https://pastebin.com/N66mPkyi

**Comment by 45mm** [comment]
This is normal behavior AFAIK - you have two windows looking at the same buffer, and point only has one value per buffer. The scroll position moving doesn't happen for me so I've got nothing for that.

If you want different values of point (cursor position) per buffer, what you can do is create an [indirect buffer](https://www.gnu.org/software/emacs/manual/html_node/emacs/Indirect-Buffers.html). `M-x clone-indirect-buffer` (`SPC b c`) will open one in a new window.  `(clone-indirect-buffer (buffer-name) nil)` will open one in the current window (doesn't call `pop-to-buffer`).

**Comment by ishovkun** [comment]
Thanks for the suggestion: I'll consider using indirect buffers as a workaround.

The scroll issue happens not at every save but rather randomly. This behavior appeared a while ago but it is certainly not the default emacs behavior. I assume that some minor mode is the culprit. I tried turning off modes one by one but I could not finish the process to identify the root cause :-(

**Comment by ishovkun** [comment]
I figured it out! yascroll-bar-mode was the culprit! Closing this!
