### ISSUE TITLE
Doom freezes every time i open a file

### ISSUE THREAD

**Issue by led0nk** [doomemacs/doomemacs#7628]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I run emacs or open a simple testfile with emacs, it should just open it and not freeze / crash.

### Current behavior

I've got an issue with doom emacs freezing everytime i open any files..
There are different ways of reproducing this error.
I'm launching Emacs through terminal "emacs" (1) or via rofi (2)

(1) If i'm launching sth like: `"emacs test.txt"`
 i'm just getting a white Window and nothing happens. Therefore i have to ctrl + C the emacs command.

(2) If i launch Emacs via Rofi the standard doom emacs dashboard is displayed.
Then i'm going to open a file or trying to do anything in emacs, the exact moment I push a button / open a file emacs freezes. Next I have to pkill my emacs to shut it down, because nothing more happens.

I tried doom emacs on my notebook with the exact same Fedora Image, no configs or anything personal and everything works fine. I also reinstalled Emacs and then doom emacs on top several times with multiple restarts, but i'm not able to get rid of this.

### Steps to reproduce

1. Open Emacs
2. Open any file

### System Information

https://pastebin.com/Z6zQ4Mid

**Comment by Patryk27** [comment]
Does the terminal variant work stable, i.e. `emacs -nw`?

**Comment by led0nk** [comment]
> Does the terminal variant work stable, i.e. `emacs -nw`?

No, if i launch via terminal i.e. 'emacs -nw' it just opens a white window and nothing happens..
I also have to pkill that emacs process.

**Comment by Patryk27** [comment]
Hmm, could you show a screenshot?

**Comment by led0nk** [comment]
![swappy-20240125_084713](https://github.com/doomemacs/doomemacs/assets/10290002/e0e372c8-ea31-4f7a-80a1-26ae54499fa0)

(1) This is via terminal 'emacs -nw'. If i now open any file or do any commands via M+x or open a file via C + x C +f it freezes like you can see. I can only exit via pkill cmd / htop.

![swappy-20240125_084932](https://github.com/doomemacs/doomemacs/assets/10290002/9a8725ca-24df-4171-a88f-ae473080bd7f)

(2) This is via 'emacs test.txt'. At the right you can clearly see only a white window which is emacs. I can only exit via C + c in terminal.

**Comment by Michael-Leibbrandt** [comment]
I have the exact same issue on a M1 Macbook Pro (Sonoma 14.2.1) using `emacs-plus@30`

**Comment by jm77git** [comment]
Same here,
Working fine until I updated Endevouros this morning. Doom scratch freezes. Didn't happened before. Version 29.2

**Comment by manikantateja973** [comment]
Same issue on Fedora 39 as well

**Comment by wugouzi** [comment]
I solved the issue by https://github.com/doomemacs/doomemacs/issues/7289#issuecomment-1892826635

**Comment by led0nk** [comment]
> I solved the issue by [#7289 (comment)](https://github.com/doomemacs/doomemacs/issues/7289#issuecomment-1892826635)

This perfectly worked for me. Emacs doesn't freeze anymore,
Thank you very much!

**Comment by H3r0F1r3** [comment]
> I solved the issue by [#7289 (comment)](https://github.com/doomemacs/doomemacs/issues/7289#issuecomment-1892826635)

I was also able to fix it on Fedora 39, thank you!
