### ISSUE TITLE
BEGIN_EXAMPLE blocks are not being syntax highlighted [org-mode]

### ISSUE THREAD

**Issue by molok** [doomemacs/doomemacs#7629]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

in a org-mode buffer BEGIN_EXAMPLE blocks should have a working  syntax highlight

### Current behavior

BEGIN_SRC blocks are syntax highlighted but BEGIN_EXAMPLE blocks are not

### Steps to reproduce

1. create a file with this content
```
#+BEGIN_SRC javascript
console.log("hi")
#+END_SRC

#+BEGIN_EXAMPLE javascript
console.log("hi")
#+END_EXAMPLE
```

2. open it with doom emacs, notice how the BEGIN_EXAMPLE block is NOT highlighted
3. open it with `emacs -Q`, notice how the BEGIN_EXAMPLE block IS highlighted

### System Information

https://pastebin.com/N0VFuhQa

**Comment by peterhoeg** [comment]
That's how it's supposed to be: https://orgmode.org/manual/Literal-Examples.html

**Comment by molok** [comment]
@peterhoeg then why EXAMPLE blocks are highlighted starting emacs with `emacs -Q`?

**Comment by peterhoeg** [comment]
That’s a good point. Going by the documentation, that shouldn’t be the case, but I don’t know what doom does differently.



That being said, is there a problem using SRC blocks if you need highlighting? I know it sounds like a cop out…

**Comment by molok** [comment]
@peterhoeg the EXAMPLE blocks are never executed, SRC block might be executed when exporting the document or by `org-ctrl-c-ctrl-c`. I might argue that unless you intend to execute the code, EXAMPLE blocks are more suited to contain source code than SRC blocks

Having

#+BEGIN_SRC sh
rm -fr ~/*
#+END_SRC

in a org file isn't really something desiderable

**Comment by hlissner** [comment]
> he EXAMPLE blocks are never executed

Use `:eval no` to inhibit any possible execution of a src block (e.g. by export or C-c C-c).

> BEGIN_SRC blocks are syntax highlighted but BEGIN_EXAMPLE blocks are not

I'm not sure what causes the discrepancy, but I suspect it's because Doom installs a newer version of Org than what comes bundled with stable versions of Emacs. I'll test that sometime this week.

In any case, since a lack of syntax highlighting is what's expected (going by the docs), I'll consider this a non-issue (or at the very least a bug in Org rather than Doom) and I'll close this, but feel free to follow up here. I will once I get around to testing it some more.

**Comment by NightMachinery** [comment]
This was solved upstream.
