### ISSUE TITLE
Void function definition: org-eldoc-get-src-lang

### ISSUE THREAD

**Issue by ArtemSmaznov** [doomemacs/doomemacs#7633]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Given I use literal config for doom emacs (setq +literate-config-file (concat doom-user-dir "README.org"))
When I put my cursor on any variable in a src block
And I press Shift+K (+lookup/documentation)
Then I should see the help/doc page for this variable popup

Given I use literal config for doom emacs (setq +literate-config-file (concat doom-user-dir "README.org"))
When I invoke +eval/buffer-or-region on a src block
Then I should see the code evaluated and applied

### Current behavior

When I lookup documentation on a variable
I see a popup for selecting a search engine to use

When I evaluate an src block
I get the following error in the messages buffer "or: Symbol’s function definition is void: org-eldoc-get-src-lang"

Invoking (org-eldoc-load) fixes both issues. Both used to work by default without having to invoke this in my config.

### Steps to reproduce

1. Open Emacs
2. Open an org file
3. Add a simple src block like so:
```
#+begin_src emacs-lisp
(use-package! org-roam
  :after org
  :config
  (setq org-roam-directory org-directory))
#+end_src
```
4.1. Put cursor on org-roam-directory
4.2. Press Shift+K (+lookup/documentation)
5.1. Put the cursor on the last `)` in the src block
5.2. Press Space+c+e (+eval/buffer-or-region)

### System Information

https://pastebin.com/R53gAMfd

**Comment by yaaama** [comment]
```
;; Prevents getting an annoying error
(autoload 'org-eldoc-get-src-lang "org-eldoc")
```

Add this snippet to your config file, it fixed the problem for me

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ArtemSmaznov** [comment]
thanks - can confirm this is fixed now
