### ISSUE TITLE
texlab

### ISSUE THREAD

**Issue by aloispichler** [doomemacs/doomemacs#7635]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I am on Arch and have `texlab` installed. M-: `(executable-find "texlab")` reports the correct path.
However, `doom doctor` reports:
```
 x There was an unexpected runtime error
    Message: Could not find package texlab. …
```

### Current behavior

doom doctor report is wrong

### Steps to reproduce

run M-: `(executable-find "texlab")`
run `doom doctor`

### System Information

https://gist.github.com/aloispichler/2e3b7fba0701825385bca7077f7a1daf

**Comment by hlissner** [comment]
> doom doctor reports:

Can you provide more context, so I know which module the report is coming from? I don't see any texlab checks in `:lang latex`, or across Doom, for that matter.
