### ISSUE TITLE
helpful-callable: Defining as dynamic an already lexical var: org-mode-hook

### ISSUE THREAD

**Issue by l2dy** [doomemacs/doomemacs#7653]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`SPC h f` `let*` shows help for `let*` in minibuffer.

### Current behavior

When I do so, it throws an error: `Defining as dynamic an already lexical var: org-mode-hook`.

### Steps to reproduce

1. Open Emacs
2. `SPC h f` `let*` (first time use only)

### System Information

https://pastebin.com/nApLVAtM

**Comment by hlissner** [comment]
As of a5ff292 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
