### ISSUE TITLE
can't open file on a fresh install:  Error running hook "global-flycheck-mode" because: (error compat package not installed)

### ISSUE THREAD

**Issue by llj098** [doomemacs/doomemacs#7656]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open any file on a fresh install on linux the file should open without error.

### Current behavior

 ■  Error (doom-first-buffer-hook): Error running hook "global-flycheck-mode" because: (error compat package not installed)

### Steps to reproduce

1. Open Emacs
2. C-x f, open a file

### System Information

https://pastebin.com/raw/XwfdyDaD

**Comment by yaaama** [comment]
Run doom sync again. I've had the same problem before.

Sometimes the packages aren't built during the first doom sync.

I usually rerun doom sync multiple times after an upgrade now

**Comment by llj098** [comment]
> Run doom sync again. I've had the same problem before.
> 
> Sometimes the packages aren't built during the first doom sync.
> 
> I usually rerun doom sync multiple times after an upgrade now

I have already tried many times, no work.

Thanks

**Comment by llj098** [comment]
after remove all the files and reinstall, problem solved.
