### ISSUE TITLE
Help menu does not work after latest upstep

### ISSUE THREAD

**Issue by kavasaziz** [doomemacs/doomemacs#7666]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I press `SPC h v`, I am able to see and search the variables. Besides, when I select the any variable, I would expect is to see it in help menu.

(Note: pls ask if I am missing anything in the explanations)

### Current behavior

However, after `SPC h v`, when I select any one of the variable from search buffer, I get following error message and traceback output. Besides, this is true regardless of the help menu function that I use.

Error Message
> if: Symbol’s value as variable is void: elisp-demos-user-files

Traceback:
> Debugger entered--Lisp error: (void-variable elisp-demos-user-files)
  (member file elisp-demos-user-files)
  (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files)))
  (let ((file (car --dolist-tail--))) (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((file (car --dolist-tail--))) (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((--dolist-tail-- (doom-module-locate-paths (doom-module-list) "demos.org"))) (while --dolist-tail-- (let ((file (car --dolist-tail--))) (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (progn (let ((--dolist-tail-- (doom-module-locate-paths (doom-module-list) "demos.org"))) (while --dolist-tail-- (let ((file (car --dolist-tail--))) (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (defvar org-inhibit-startup) (defvar org-mode-hook) (progn (defalias '+emacs-lisp--optimize-org-init-a #'(lambda (fn &rest args) "Disable unrelated functionality to optimize calls ..." (let ((org-inhibit-startup t) enable-dir-local-variables org-mode-hook) (apply fn args)))) (let ((--dolist-tail-- (list (cons :around (ensure-list ...)) (cons :around (ensure-list ...)) (cons :around (ensure-list ...))))) (while --dolist-tail-- (let ((targets (car --dolist-tail--))) (let ((--dolist-tail-- ...)) (while --dolist-tail-- (let ... ... ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) t)
  (closure (t) nil (progn (let ((--dolist-tail-- (doom-module-locate-paths (doom-module-list) "demos.org"))) (while --dolist-tail-- (let ((file (car --dolist-tail--))) (if (member file elisp-demos-user-files) elisp-demos-user-files (setq elisp-demos-user-files (cons file elisp-demos-user-files))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (defvar org-inhibit-startup) (defvar org-mode-hook) (progn (defalias '+emacs-lisp--optimize-org-init-a #'(lambda (fn &rest args) "Disable unrelated functionality to optimize calls ..." (let (... enable-dir-local-variables org-mode-hook) (apply fn args)))) (let ((--dolist-tail-- (list (cons :around ...) (cons :around ...) (cons :around ...)))) (while --dolist-tail-- (let ((targets ...)) (let (...) (while --dolist-tail-- ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) t))()
  eval-after-load-helper("/home/aziz.kavas@corp.airties.com/.config/emacs/.l...")
  run-hook-with-args(eval-after-load-helper "/home/aziz.kavas@corp.airties.com/.config/emacs/.l...")
  do-after-load-evaluation("/home/aziz.kavas@corp.airties.com/.config/emacs/.l...")
  elisp-demos-advice-helpful-update()
  apply(elisp-demos-advice-helpful-update nil)
  helpful-update()
  helpful--update-and-switch-buffer(tab-width nil)
  helpful-variable(tab-width)
  #<subr funcall-interactively>(helpful-variable tab-width)
  apply(#<subr funcall-interactively> (helpful-variable tab-width))
  funcall-interactively(helpful-variable tab-width)
  #<subr call-interactively>(helpful-variable nil nil)
  apply(#<subr call-interactively> (helpful-variable nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> helpful-variable nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (helpful-variable nil nil))
  call-interactively(helpful-variable nil nil)
  command-execute(helpful-variable)

### Further Observations
When I traced back this variable inside doom repo I found following snippet:
```elisp
(use-package! elisp-demos
  :defer t
  :init
  (advice-add #'describe-function-1 :after #'elisp-demos-advice-describe-function-1)
  (advice-add #'helpful-update :after #'elisp-demos-advice-helpful-update)
  :config
  ;; Add Doom's core and module demo files, so additional demos can be specified
  ;; by end-users (in $DOOMDIR/demos.org), by modules (modules/X/Y/demos.org),
  ;; or Doom's core (lisp/demos.org).
  (dolist (file (doom-module-locate-paths (doom-module-list) "demos.org"))
    (add-to-list 'elisp-demos-user-files file))
```
Therefore, I have tried to recompile it, but I didn't observe any change. Further, when I try to evaluate following statement solely, I observed the same issue:
```elisp
  (dolist (file (doom-module-locate-paths (doom-module-list) "demos.org"))
    (add-to-list 'elisp-demos-user-files file))
```

As a work around, with my limited knowledge, what I can think of is just to create a variable as below:
```elisp
(defvar elisp-demos-user-files '()
  "List of user demo files for elisp demos.")
```
With this it works without a problem, but I guess this is not the appropriate one. Therefore, I wanted to ask.

### Steps to reproduce

Note that this problem is true for all help functions that I tried
1. Open Emacs
2. Press `SPC h v`
3. Select any of the variables
4. See error messages

### System Information

https://gist.github.com/kavasaziz/d950f8f11ec204bebab69b75a5f1a307

**Comment by hlissner** [comment]
How are you updating Doom? It sounds like the elisp-demos wasn't updated, which suggests you're not using `doom upgrade`, but instead, updating Doom with `git pull` without running `doom sync -u` afterwards (the `-u` ensures that packages are updated, if their pins have changed). That, or there was an error during the last `doom upgrade` you might've missed that stopped it from completing the update process.

In any case, try `doom sync -u`, to ensure your packages are up-to-date. elisp-demos-user-files is certainly [present in the elisp-demos package](https://github.com/xuchunyang/elisp-demos/blob/1a108d1c5011f9ced58be2ca98bea1fbd4130a2f/elisp-demos.el#L40).

**Comment by kavasaziz** [comment]
I used `doom upgrade` actually, but I didn't know the `-u` option. Let me try real quick.

**Comment by kavasaziz** [comment]
Yes, I used `doom upgrade && doom sync`, but it seem I should keep in mind to use `-u` option. Thanks for your time, and sorry for wrong error.

**Comment by hlissner** [comment]
Only `doom upgrade` is necessary (it runs `doom sync -u` for you), but there was likely an error the first time it tried (maybe one of the package repos was down). The process doesn't 'roll back' on failures (yet).

Anyhow, glad you figured it out!
