### ISSUE TITLE
Asterisk in org mode instead of Symbols

### ISSUE THREAD

**Issue by Amrit-codes** [doomemacs/doomemacs#7667]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

![image](https://github.com/doomemacs/doomemacs/assets/128936479/5a7fb55b-aded-40b8-8c6b-12b778fccdf0)
Instead of symbols, asterisk are appearing in org mode

### Current behavior

![image](https://github.com/doomemacs/doomemacs/assets/128936479/5a7fb55b-aded-40b8-8c6b-12b778fccdf0)
Instead of symbols, asterisk are appearing in org mode

### Steps to reproduce

Try typing headings in org mode

### System Information

https://pastebin.com/UryAXUSA

**Comment by hlissner** [comment]
You haven't enabled `+pretty` on the `:lang org` module. Please do so.

I'll close this since this isn't a bug, but feel free to follow up here.

**Comment by Amrit-codes** [comment]
My bad, I shouldn't have asked here
Also thanks a lot for helping me despite that
