### ISSUE TITLE
+format/region always prefers apheleia over eglot 

### ISSUE THREAD

**Issue by lunik1** [doomemacs/doomemacs#7673]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I call `+format/region` on a buffer using `eglot` and `+format-with-lsp` set to `t` I expect `eglot` to be used to format the buffer.

### Current behavior

When I call `+format/region` on a buffer using `eglot` and `+format-with-lsp` set to `t`, `apheleia` is used to format the buffer.

### Steps to reproduce

1. Enable `(lsp +eglot)`
2. Enable `format`
3. Format a buffer using an LSP server supporting formatting

### System Information

https://pastebin.com/J8M9QjRb

**Comment by lunik1** [comment]
It's because `+format/buffer` checks `(bound-and-true-p lsp-mode)`

(I'm not sure `lsp-feature?` in the following like will work either?)

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
