### ISSUE TITLE
Doom Keybindings not working

### ISSUE THREAD

**Issue by huNt-FMJ** [doomemacs/doomemacs#7675]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I press `SPC RET`, my list of book marks should be shown

### Current behavior

When I press `SPC RET`, the echo area states: `[2024-02-14 17:44:15] SPC RET is undefined`

There is no error, no stacktrace, and no hint in the `*Messages*` buffer.

Pressing `SPC` gives me only two options:
![image](https://github.com/doomemacs/doomemacs/assets/2405937/38e76461-20d6-4103-9f60-f4fb98e0277d)
 
- I also just updated my doom emacs on another machine and while the doom key mappings worked before, after the update they were also gone.
- I reverted to several older commits in hope of being able to *rollback*, but apart from `doom sync` after `git checkout <old-commit>`, I wasn't sure what to do. The missing key mapping persisted.
- I also deleted `~/.config/emacs` and reinstalled doom, but again, the issue is not fixed.

`doom doctor` gives:
``` 
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  ✓ Initialized Doom Emacs 3.0.0-pre
  ✓ Detected 53 modules
  ✓ Detected 219 packages
  > Checking Doom core for irregularities...
    Found font NFM.ttf
  > Checking for stale elc files in your DOOMDIR...
  > Checking your enabled modules...
    > :lang clojure
      ! Couldn't find clj-kondo. flycheck-clj-kondo will not work.
    > :lang go
      ! Couldn't find gopls.
      ! Couldn't find gomodifytags. Manipulating struct tags will not work
      ! Couldn't find gotests. Generating tests will not work
      ! Couldn't find gore. REPL will not work
      ! Couldn't find guru. Refactoring commands (go-guru-*) won't work
    > :lang kotlin
      ! ktlint not found. flycheck-kotlin won't work.
    > :lang markdown
      ! Couldn't find a markdown compiler, `markdown-preview' won't work
    > :lang python
      ! Couldn't find isort. Import sorting will not work.
      ! Couldn't find pipenv. pipenv support will not work.
      ! Couldn't find nosetests. Running tests through nose will not work.
      ! Couldn't find pytest. Running tests through pytest will not work.
      ! setuptools wasn't detected, which anaconda-mode requires
    > :lang rust
      ! Couldn't find rust analyzer (rust-analyzer)
      ! Couldn't find rustc binary
    > :lang web
      ! Couldn't find tidy. Code formatting in HTML modes will not work.
      ! Couldn't find stylelint. Linting for CSS modes will not work.
      ! Couldn't find js-beautify. Code formatting in JS/CSS/HTML modes will not work.
    > :email mu4e
      ! Couldn't find mu command. Mu4e requires this to work.

There are 19 warnings!
```

`doom run --debug-init` gives:
```
doom run --debug-init
Loading /home/x/.config/emacs/lisp/doom.el (source)...
Loading /home/x/.config/emacs/lisp/doom.el (source)...done
* 0.010649:*:load: doom-start nil
* 0.013100:*:hook:doom-before-init-hook: run doom--begin-init-h
* 0.013125::context: +init (t)
* 0.013460:*:init:load: /home/x/.config/doom/init t
```

### Steps to reproduce

1. Open doom emacs
2. press `SPC <doom key>`
3. See `SPC <doom key>` is undefined

### System Information

https://gist.github.com/huNt-FMJ/ecd3676b8f6fa74001ef7fdbf28945a8

**Comment by hlissner** [comment]
When keybinds go missing, it's because there is an unaddressed (and often unrelated) error while Emacs is starting up. Please use the tools mentioned [in the debugging guide](https://discourse.doomemacs.org/t/how-to-debug-issues/55) to find them. The first thing to try being: `C-h e` (`M-x view-echo-area-messages`) to see the `*Messages*` buffer. Search for error messages, and if you find one, try to produce a backtrace for it (see "Dealing with errors" at the Discourse link above).

**Comment by huNt-FMJ** [comment]
Will check, thank you.

**Comment by huNt-FMJ** [comment]
Dead on. Thanks a ton.
