### ISSUE TITLE
`void-function geiser-implementation-extension` error from any geiser-* package

### ISSUE THREAD

**Issue by ynty** [doomemacs/doomemacs#7693]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I run `doom doctor`,  I expect to see no runtime errors.

### Current behavior

When I run `doom doctor`,  there's an unexpected runtime error.
```
  x There was an unexpected runtime error
    Message: Symbol's function definition is void
    Details: (geiser-implementation-extension)
    Backtrace:
      (geiser-implementation-extension 'chez "def")
      (eval-buffer #<buffer  *load*-558722> nil "/Users/macuser/.config/emac...
      (load-with-code-conversion "/Users/macuser/.config/emacs/.local/etc/@/...
      (load "/Users/macuser/.config/emacs/.local/etc/@/init.29.el" noerror n...
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (...
      (doom-load "/Users/macuser/.config/emacs/.local/etc/@/init.29.el" noer...
      (let (kill-emacs-query-functions kill-emacs-hook) (doom-load init-file...
      (let ((init-file (doom-profile-init-file))) (if (file-exists-p init-fi...
      (progn (doom-require 'doom-profiles) (let ((init-file (doom-profile-in...
      (if noninteractive (progn (doom-require 'doom-profiles) (let ((init-fi...
      (eval-buffer #<buffer  *load*-115783> nil "/Users/macuser/.config/emac...
      (load-with-code-conversion "/Users/macuser/.config/emacs/lisp/doom-sta...
```
[cli.doom.240224205641.13945.error.txt](https://github.com/doomemacs/doomemacs/files/14392878/cli.doom.240224205641.13945.error.txt)

### Steps to reproduce

1. In Doom's init.el, enable `(scheme +chez)`
2. `doom sync`
3. `doom doctor`

### System Information

https://gist.github.com/tn-072/8631432d33bcbb99344706c5b270469d

**Comment by DeesonGao** [comment]
I have the same problem.

I guess, this is because the functions autoloaded by `geiser-chez` depend on the functions autoloaded by `geiser`.
But the autoloads files were collected in the order they build (straight--build-cache), which make functions autoloaded by `geiser-chez` has higher priority, so it can't find the function definition.

**Comment by tn-072** [comment]
> I have the same problem.
> 
> I guess, this is because the functions autoloaded by `geiser-chez` depend on the functions autoloaded by `geiser`. But the autoloads files were collected in the order they build (straight--build-cache), which make functions autoloaded by `geiser-chez` has higher priority, so it can't find the function definition.
> 
> This is a temporary solution:
> 
> 1. remove `+chez` of `(scheme +chez)` in .doom.d/init.el. （So it should be `(scheme)` ）
> 2. `doom sync`
> 3. restore to `(scheme +chez)`
> 4. `doom sync`
> 
> It should work now.

It raelly works.
Thanks a lot.

**Comment by hevt** [comment]
This really helped me solve an issue for geiser autoloading in racket too, thank you! (similarly, sync'ing with just ~scheme~ first, then ~(scheme +racket)~ solves the "couldn't find extension" issue)

**Comment by welcome-linja** [comment]
Hang on now, this shouldn't be closed, it's a bug! The existence of a workaround doesn't negate that.
