### ISSUE TITLE
mu4e-clear-caches is obsoleted but still used by doom emacs

### ISSUE THREAD

**Issue by epichub** [doomemacs/doomemacs#7703]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When i reply to a email in mu4e it should switch context to the email account connected to the email I am replying to without getting an error.

### Current behavior

I am getting the following error:

```
Debugger entered--Lisp error: (void-function mu4e-clear-caches)
  (mu4e-clear-caches)
  (progn (setq +mu4e-personal-addresses nil) (mu4e-clear-caches))
  (closure (t) nil (progn (setq +mu4e-personal-addresses nil) (mu4e-clear-caches)))()
  #<subr mu4e-context-switch>(nil "ntnu")
  apply(#<subr mu4e-context-switch> (nil "ntnu"))
  (let ((context mu4e-alert--mu4e-context-current)) (apply orig args) (if (equal context mu4e-alert--mu4e-context-current) nil (mu4e-alert-update-mail-count-modeline)))
  mu4e-alert--context-switch(#<subr mu4e-context-switch> nil "ntnu")
  apply(mu4e-alert--context-switch #<subr mu4e-context-switch> (nil "ntnu"))
  mu4e-context-switch(nil "ntnu")
  mu4e--context-autoswitch((:size 25644 :date (26060 10440 0) :from ((:email "l.folkman@griffith.edu.au" :name "Lukas Folkman")) :message-id "SYBPR01MB4012EF1E5EA36DAD91A381F3BD4E2@SYBPR01MB40..." :priority normal :references ("SYBPR01MB401205C2C36D5F4A450F4DD4BD0AA@SYBPR01MB40..." "2EEDB3F3-9F23-445A-AE06-0ABF660858D0@ntnu.no") :subject "Re: Salmon image dataset" :to ((:email "bjornmm@ntnu.no" :name "Bjørn Magnus Mathisen")) :path "/home/bmat/.mail/ntnu/INBOX/cur/1707878690.2626763..." :changed (26060 29264 0) :flags (seen) :maildir "/ntnu/INBOX" :docid 166933 :meta (:path "065:ffe:fff:z" :level 2 :date "n65cc28c8" :data-tstamp (0 0 0) :first-child t :last-child t)) ask-if-none)
  mu4e--compose-setup(reply #f(compiled-function (parent) #<bytecode -0xa920f478ed02898>))
  #<subr mu4e-compose-reply>()
  apply(#<subr mu4e-compose-reply> nil)
  #f(advice +mu4e-ensure-compose-writeable-a :before #<subr mu4e-compose-reply>)()
  funcall(#f(advice +mu4e-ensure-compose-writeable-a :before #<subr mu4e-compose-reply>))
  +mu4e-maybe-toggle-org-msg-a(#f(advice +mu4e-ensure-compose-writeable-a :before #<subr mu4e-compose-reply>) 1)
  apply(+mu4e-maybe-toggle-org-msg-a #f(advice +mu4e-ensure-compose-writeable-a :before #<subr mu4e-compose-reply>) 1)
  mu4e-compose-reply(1)
  funcall-interactively(mu4e-compose-reply 1)
  command-execute(mu4e-compose-reply)
```
I think the cause is that mu4e has obsoleted mu4e-clear-caches (https://github.com/djcb/mu/blob/1e5a807b6994640d676d9ecb7a129d908bbb9622/mu4e/mu4e-obsolete.el#L276) per version 1.11.15. and this function is used by doom in the mu4e email module: https://github.com/doomemacs/doomemacs/blob/183ab38926aa1506203ea9ea64f631d598f90b4a/modules/email/mu4e/autoload/email.el#L37 

### Steps to reproduce

There may be other ways of triggering the bug, but mine was like this:
1. have two different email contexts in mu4e.
2. reply to an email not in the currently active context

### System Information

https://pastebin.com/EVP4U5fz

**Comment by Kakupakat** [comment]
I can confirm this. Simply trying to change the context will trigger the error.

**Comment by 45mg** [comment]
This appears to be an issue only for mu>1.10.0. The commit that obsoletes this function is f73aad2b.

**Comment by dltacube** [comment]
How are you guys dealing with this? Did you just pin mu4e to an earlier version?

**Comment by hlissner** [comment]
> pin mu4e to an earlier version

We can't, unfortunately. mu4e is tied to the `mu` program available through OS package distros (which Doom doesn't/can't manage). `mu4e` will refuse to run if its version doesn't match `mu`'s.

Since backwards-incompatible changes are quite common with mu4e (and mu's availability and version varies wildly depending on distro, distro version, and package manager), our mu4e module will need a more sophisticated compatibility layer to shim/alias things across breaking releases and stay ahead of these breakages in the future.

Until then, there's really no workaround besides installing an older version of mu, if that is an option with your package manager.

**Comment by dltacube** [comment]
Since it _sounds_ like clearing the cache is unnecessary (https://github.com/djcb/mu/issues/2537#issuecomment-1686555873) I just added a function definition as a simple fix:

`(defun mu4e-clear-caches (&rest args) "No-op before advice.")`

Someone stop me if this is a bad idea!

**Comment by hlissner** [comment]
> Since it sounds like clearing the cache is unnecessary

Huh. Good to know. In that case I'll look into removing the call. Thanks for looking into it!

**Comment by dltacube** [comment]
Maybe hold off on that. I deleted emails from another client and they're showing as "marked for deletion" in mu4e. Gray, italics and crossed out. Is that what `mu4e-clear-caches` was handling? If not it might be unrelated.

**Comment by hlissner** [comment]
For the time being, I've guarded the call with a `fboundp` check, so it'll be called if it's present, ignored otherwise. This should at least tide over OPs issue until more work can be done on the module. Thanks for bringing it to my attention, in any case!
