### ISSUE TITLE
Ctrl + +/Ctrl + - stopped zooming in/out

### ISSUE THREAD

**Issue by hrqmonteiro** [doomemacs/doomemacs#7704]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When i pressed Control + + or Control + -, it zoomed in and out, and it stopped working?

### Current behavior

Not doing it.

### Steps to reproduce

Just press it.

### System Information

https://pastebin.com/frRaMTdG

**Comment by CestDiego** [comment]
I came here to post about the same thing.

**Comment by hlissner** [comment]
I cannot reproduce this. Can either of you provide any more information? Error messages? Logs in `*Messages*`?

**Comment by hrqmonteiro** [comment]
> I cannot reproduce this. Can either of you provide any more information? Error messages? Logs in `*Messages*`?

So in your config it still works? Cause i am trying on a vanilla doom config install, even.

And there are no logs in messages.

**Comment by hlissner** [comment]
Please update doom. I'm hoping that https://github.com/doomemacs/doomemacs/commit/c20c2aa36ed0be93beca3fc63eea2724f57af6a7 may have indirectly fixed this issue.

----

> So in your config it still works? Cause i am trying on a vanilla doom config install, even.

Yes.

**Comment by hrqmonteiro** [comment]
> Please update doom. I'm hoping that [c20c2aa](https://github.com/doomemacs/doomemacs/commit/c20c2aa36ed0be93beca3fc63eea2724f57af6a7) may have indirectly fixed this issue.
> 
> > So in your config it still works? Cause i am trying on a vanilla doom config install, even.
> 
> Yes.

Now it works! Thanks
