### ISSUE TITLE
Company mode autocomplete error when using ledger mode after upgrading Doom emacs

### ISSUE THREAD

**Issue by tjroth** [doomemacs/doomemacs#7717]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When editing a ledger entry account field emacs should provide a list of available accounts as one begins typing an account prefix. For example, typing "Assets:Banking:"  should list all account with that prefix... "Assets:Banking:Bofa, Assets:Banking:FirstUnion, etc".  This allows one to easily tab to the correct account.

### Current behavior

Instead of seeing the list of available matching accounts, I'm getting the following error as I start typing in the account filed "Company: backend company-capf error 'Invalid search bound (wrong side of point)'"

### Steps to reproduce

1. Open a ledger-cli file in Emacs
2. Move cursor under a transaction and begin typing the account name to create a new entry for the transaction

### System Information
https://gist.github.com/tjroth/76b70529dafa5e4cd5e15c439fa08d11

**Comment by hlissner** [comment]
I cannot reproduce this. From your `M-x doom/info`, it seems you've installed company using ELPA (e.g. `M-x package-install` or similar). It's possible you've installed an unsupported version, and you've done with an unsupported package manager, which could conflict with the `:completion company` module, which would've installed company for you anyway.

Run `doom sync -p` to purge packages installed with ELPA, and clear out any uses of `package-install` or `:ensure t` (in your `use-package` blocks) from your config, then restart Emacs.

**Comment by tjroth** [comment]
Thanks, I followed those steps but still getting same behavior/error.  My updated doom info...

generated  Mar 09, 2024 06:49:00
system     MacOS 14.3.1 Darwin 23.3.0 x86_64
emacs      29.1 29.1-mac-10.0 e173249a1 EMACSDIR=~/.config/emacs/
	   EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs
doom       3.0.0-pre PROFILE=_@0 grafted, HEAD -> master, origin/master,
	   origin/HEAD bea81278 2024-03-05 01:21:09 -0500 ~/.doom.d/
shell      /bin/zsh
features   ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3
	   THREADS TOOLKIT_SCROLL_BARS TREE_SITTER XWIDGETS ZLIB
traits     batch envvar-file
modules    :config use-package :completion company ivy :ui doom doom-dashboard
	   doom-quit hl-todo modeline ophints (popup +defaults) treemacs
	   vc-gutter vi-tilde-fringe workspaces :editor (evil +everywhere)
	   file-templates fold (format +onsave) snippets :emacs dired electric
	   undo vc :term eshell vterm :checkers syntax :tools (eval +overlay)
	   lookup lsp magit :lang (clojure +lsp) emacs-lisp ledger markdown org
	   (rust +lsp) sh :config (default +bindings +smartparens)

**Comment by hlissner** [comment]
Please produce [a backtrace](https://discourse.doomemacs.org/how2backtrace) from the error.

**Comment by tjroth** [comment]
This turned out to not be an issue with company-mode or doom-emacs.   There were formatting errors in my ledger file that were being detected and causing the error/warning.  Everything works as expected after correcting the formatting errors.  Thanks for your guidance.

backtrace...

Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-forward("\\(?:^[ \11]+\\(?:[!*][ \11]*\\)?[[(]?\\(?1:[^][(); \11\15\n]+\\..." 1782483 t)
  #f(compiled-function (pos date state payee) #<bytecode 0x1efc8d1f8879c9e>)(1782450 (24554 47056) nil #("C" 0 1 (fontified nil)))
  ledger-xact-iterate-transactions(#f(compiled-function (pos date state payee) #<bytecode 0x1efc8d1f8879c9e>))
  ledger-accounts-in-buffer()
  ledger-accounts-list-in-buffer()
  ledger-accounts-list()
  #f(compiled-function (_) #<bytecode 0xa156a1412f7de45>)("As")
  #f(compiled-function (arg) #<bytecode -0x1e7c23c228144d1f>)("As")
  #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>)("As" nil t)
  all-completions("As" #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>) nil)
  completion-pcm--all-completions("" ("As" point) #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>) nil)
  completion-basic-all-completions("As" #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>) nil 2)
  #f(compiled-function (style) #<bytecode -0x18c9661b4f7089bf>)(basic)
  completion--some(#f(compiled-function (style) #<bytecode -0x18c9661b4f7089bf>) (basic partial-completion emacs22))
  completion--nth-completion(2 "As" #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>) nil 2 (metadata))
  completion-all-completions("As" #f(compiled-function (string pred action) #<bytecode -0x12c5c3e031816f2c>) nil 2 (metadata))
  company-capf--candidates("As")
  company-capf(candidates "As")
  apply(company-capf (candidates "As"))
  company-call-backend-raw(candidates "As")
  company--fetch-candidates("As")
  company-calculate-candidates("As" nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer ledger.ledger> #<window 3 on ledger.ledger> 72 2888470)
  apply(company-idle-begin (#<buffer ledger.ledger> #<window 3 on ledger.ledger> 72 2888470))
  explain-pause--wrap-callback(#s(explain-pause-command-record :command timer :native t :parent #s(explain-pause-command-record :command company-post-command :native nil :parent #s(explain-pause-command-record :command post-command-hook :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 3837 :entry-snap (26093 39508 592355 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap (26093 39508 484367 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) company-idle-begin #<buffer ledger.ledger> #<window 3 on ledger.ledger> 72 2888470)
  apply(explain-pause--wrap-callback (#s(explain-pause-command-record :command timer :native t :parent #s(explain-pause-command-record :command company-post-command :native nil :parent #s(explain-pause-command-record :command post-command-hook :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 3837 :entry-snap (26093 39508 592355 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap (26093 39508 484367 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) company-idle-begin #<buffer ledger.ledger> #<window 3 on ledger.ledger> 72 2888470))
  timer-event-handler([t 26093 39508 684379 nil explain-pause--wrap-callback (#s(explain-pause-command-record :command timer :native t :parent #s(explain-pause-command-record :command company-post-command :native nil :parent #s(explain-pause-command-record :command post-command-hook :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 3837 :entry-snap (26093 39508 592355 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap (26093 39508 484367 0) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 3) company-idle-begin #<buffer ledger.ledger> #<window 3 on ledger.ledger> 72 2888470) nil 0 nil])
