### ISSUE TITLE
unable to set formatter

### ISSUE THREAD

**Issue by mtxn2147** [doomemacs/doomemacs#7718]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

after adding \<code below\> to `doom/config.el`, formatter for `c++-mode` and `c-mode` should change  to `astyle`.
```elisp
(set-formatter! 'astyle '("astyle" (mapconcat 'identity (apheleia-formatters-locate-file "--options=" ".astylerc"))) :modes '(c++-mode c-mode))
```

### Current behavior

formatter for selected modes doesn't change however the parameters does.

### Steps to reproduce

add \<code below\> to `doom/config.el` file.
```eslip
(set-formatter! 'astyle '("astyle" (mapconcat 'identity (apheleia-formatters-locate-file "--options=" ".astylerc"))) :modes '(c++-mode c-mode))
```

### System Information

https://pastebin.com/xWYw9Ajc

**Comment by hlissner** [comment]
Config like this usually needs to be wrapped in a `(after! cc-mode ...)`. See if that fixes your issue.

**Comment by elken** [comment]
Correct, as per the [module docs](https://github.com/doomemacs/doomemacs/tree/master/modules/editor/format#configuration) :smile:

**Comment by hlissner** [comment]
> I tested it with `(after! apheleia-mode ...)` but it didn't work

That's because the package you want is `apheleia`. There is no `apheleia-mode` package.
