### ISSUE TITLE
M-x doom/set-frame-opacity stopped working after upgrading to the latest version of doom

### ISSUE THREAD

**Issue by sla7** [doomemacs/doomemacs#7721]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

M-x doom/set-frame-opacity should change the opacity of the frame. It has worked before I updated doomemacs to the latest version.

```> doom version
GNU Emacs     v29.2            nil
Doom core     v3.0.0-pre       HEAD -> master aad8ec18 2024-03-10 00:54:34 -0500
Doom modules  v24.02.0-pre     HEAD -> master aad8ec18 2024-03-10 00:54:34 -0500

Copyright (c) 2014-2024 Henrik Lissner.

Doom Emacs uses the MIT license and is provided without warranty of
any kind. You may redistribute and modify copies if given proper
attribution. See the LICENSE file for details.
```
### Current behavior

`M-x doom/set-frame-opacity` does nothing after updating doomemacs to the latest version on macos. Opacity can be set to 0 and there is no change to the frames opascity.

![Screenshot 2024-03-10 at 1 16 22 AM](https://github.com/doomemacs/doomemacs/assets/33646780/3a3af903-8818-4bd5-af87-532deeb47723)

### Steps to reproduce

1. Open emacs
2. M-x doom/set-frame-opacity
3. Set to any number and no changes happen.

### System Information

https://pastebin.com/5SMR2Z6S

**Comment by hlissner** [comment]
@hpfr Would you happen to know if `alpha-background` is expected to work on macOS (with NS, in particular)? Seems https://github.com/doomemacs/doomemacs/commit/088bd387f6c901273ad166b67a14bf1745026c4f is the cause of this.

**Comment by elken** [comment]
90% sure it's a PGTK thing so I'd wager no
