### ISSUE TITLE
Yasnippet TAB not working in Org Mode

### ISSUE THREAD

**Issue by postcert** [doomemacs/doomemacs#7733]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After inserting a snippet, pressing the tab key should move me to the next field in the snippet when in org-mode.

```
# -*- mode: snippet -*-
# name: #+begin_src
# uuid: src
# key: src
# --
#+begin_src $1
`%`$0
#+end_src
```

The expectation is for the cursor to move to $0 on tab press but I end up at the field $1 and inserting a literal tab.

### Current behavior

After inserting the snippet pressing tab calls `org-cyle` and inserts a literal tab space.

### Steps to reproduce

1. Open an org file
2. Type `<s` to be presented the source block snippet prompt
3. Press tab/enter to activate the snippet
4. Type in a valid language for babel, name of your favorite cat, etc
5. Press tab and see that a literal tab space is inserted after your text instead of moving your into the source block

### System Information

https://gist.github.com/postcert/747232ca960f990d33c20fb0b4da7b8f

**Comment by postcert** [comment]
I've been able to work around this issue by rebinding `<tab>` in the `evil-org-mode-map` to a conditional function that calls the expected `yasnippet` function conditionally.

```
(defun my/org-tab-conditional ()
  (interactive)
  (if (yas-active-snippets)
      (yas-next-field-or-maybe-expand)
    (org-cycle)))

(map! :after evil-org
      :map evil-org-mode-map
      :i "<tab>" #'my/org-tab-conditional)
```

**Comment by postcert** [comment]
Discord doom-help posting: https://discord.com/channels/406534637242810369/1217814396437401742
Previous >30d in age posting that was deleted by the author: https://discord.com/channels/406534637242810369/1204440395426041897

I'm new to Doom and Emacs so I didn't know the snippets have multiple fields (though it didn't seem correct).
Only really noticed/addressed today after following a YT videos on creating a using yasnippets.

**Comment by Wumianzhe** [comment]
I have the same issue and it's been around for under 5 months (doom on second machine is that old), but more than a month.

**Comment by Herschenglime** [comment]
I didn't experience the issue on a build of doom from 2 weeks ago, but after updating today it appeared, so I think it may be a more recent breaking change.

**Comment by tdehaeze** [comment]
Same, just appeared recently.

**Comment by neuhalje** [comment]
# Summary
- When testing snippets, the buffer stars in `normal` mode, expected: `insert` mode
- 

# Steps to reproduce

Create a new snippet with `yas-new-snippet` and set it to
```text
a$1b$0c
```

## Expected bevavior
Test snippet with `C-c C-t`

`^` denoting point. Buffer in `insert` mode.
```
a^bc
```

Press `TAB`
```
ab^c
```

Press `S-TAB`
```
a^bc
```
## Actual Behavior (when staying in `normal` mode)

Test snippet with `C-c C-t`

`^` denoting point. Buffer in`normal` mode.
```
a^bc
```

Press `TAB`:  User error `No matching item found on the current line`
```
a^bc
```

Press `S-TAB`
```
ab^c
```

Press `S-TAB` again: User error `<backtab> is undefined`

## Actual Behavior (when switching to `insert` mode)

Test snippet with `C-c C-t`

`^` denoting point. Buffer in`normal` mode.
```
a^bc
```

Press `i` to switch to `insert` mode.

Press `TAB`:  Correctly jumps to the next
```
ab^c
```

Press `TAB`:  Correctly (?) inserts TAB

```
ab    ^c
```

Press `S-TAB`: User error `<backtab> is undefined`
```
ab    ^c
```

**Comment by nerffan1** [comment]
Hello, apologies for bothering you with this, but when I press TAB with the following snippet, I only get the subheader to get demoted :(

``` org
# -*- mode: snippet -*-
# name: job-application
# key: job
# --
* APPLY ${1:Company}: ${2:Experience} - ${3:Position}
** Description
** Experience Table
** About the Company
** LINKS
** COVER LETTER
```

**Comment by goderich** [comment]
@nerffan1 how do you bind the keys? Yasnippet's expansion bindings are a bit tricky, especially if you want to have other functionality on TAB as well. See [my config](https://github.com/goderich/dotfiles/blob/master/doom-emacs/.config/doom/keybindings.el#L206) for an example of such a binding with an explanation. Refer to Emacs' help system for the relevant functions as well.

**Comment by laurentHYZ** [comment]
> [@nerffan1](https://github.com/nerffan1) how do you bind the keys? Yasnippet's expansion bindings are a bit tricky, especially if you want to have other functionality on TAB as well. See [my config](https://github.com/goderich/dotfiles/blob/master/doom-emacs/.config/doom/keybindings.el#L206) for an example of such a binding with an explanation. Refer to Emacs' help system for the relevant functions as well.

Hi Goderich, 
I checked your configuration and I don't understand it:) I am only using 3 files: packages.el, init.el and config.el
where am I supposed to put the keybindings.el?

I really want to use yasnippet but it has been years that I am unable to do the most basic tab navigation, thank you for your help :)

**Comment by goderich** [comment]
Hi @laurentHYZ !

I no longer use Doom, but I'll try to help.

> where am I supposed to put the keybindings.el?

You can just put the relevant code in `config.el`! All the extra files I have there aren't necessary, they are just my way of organizing the code. If you look at my `config.el`, all it does is load other files.

My point was [this](https://github.com/goderich/dotfiles/blob/master/doom-emacs/.config/doom/keybindings.el#L208-L216), i.e. that you mustn't quote `yas-maybe-expand` when binding it, and if you want to have other functionality on Tab, it must go **before** `yas-maybe-expand`.

Hope this helps!

**Comment by laurentHYZ** [comment]
Will try to implement your advice, thank you, right now on my phone but I am curious: did you switch to vanilla emacs?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by goderich** [comment]
@laurentHYZ let's not go off-topic in this issue any more :)
But to answer your question: I have my own (literate) config. Feel free to have a look [here](https://github.com/goderich/.emacs.d/blob/master/config.org).

**Comment by laurentHYZ** [comment]
Gotcha,
Thank you for the link
br,
laurent

________________________________

**Comment by laurentHYZ** [comment]
> [@nerffan1](https://github.com/nerffan1) how do you bind the keys? Yasnippet's expansion bindings are a bit tricky, especially if you want to have other functionality on TAB as well. See [my config](https://github.com/goderich/dotfiles/blob/master/doom-emacs/.config/doom/keybindings.el#L206) for an example of such a binding with an explanation. Refer to Emacs' help system for the relevant functions as well.

Hi again Goderich, so in your doom emacs config I see the mapping below. 
I mainly use org-mode, so does that mean i should replace markdown with org-mode, 
and then put within my config.el file?  Also curious: why don't you have the same for org-mode, were you not using it with doom? Thank you!
`
(map! :map markdown-mode-map
      :after yasnippet
      :nvi [tab] #'markdown-cycle
      ;; The above TAB binding shadows yas-expand.
      ;; In order to make yasnippets work, I need to
      ;; manually pass the binding to `yas-maybe-expand'
      ;; BELOW the new binding (since it expands only
      ;; when there is a snippet).
      ;; Note that `yas-maybe-expand' is NOT a function,
      ;; so it must not be sharp-quoted.
      :nvi [tab]        yas-maybe-expand
      :nvi "M-<left>"   #'markdown-promote
      :nvi "M-h"        #'markdown-promote
      :nvi "M-<right>"  #'markdown-demote
      :nvi "M-l"        #'markdown-demote
      :nvi "M-<up>"     #'markdown-move-up
      :nvi "M-k"        #'markdown-move-up
      :nvi "M-<down>"   #'markdown-move-down
      :nvi "M-j"        #'markdown-move-down
      :nvi "C-<return>" #'markdown-insert-list-item
      (:prefix "g"
       :nv "h" #'markdown-up-heading
       :nv "j" #'markdown-next-visible-heading
       :nv "k" #'markdown-previous-visible-heading)
      (:localleader
       :desc "Insert citation"    "c" #'ebib-insert-citation
       :desc "Toggle valign mode" "v" #'valign-mode))`

**Comment by laurentHYZ** [comment]
I have used your config and modified it to work with org-mode. 
The code below works:
`
(map! :map org-mode-map
      :after yasnippet
      ;; Retain org-mode's native TAB functionality but allow yas-expand when a snippet is available
      :nvi [tab]        yas-maybe-expand
      ;; Optionally, bind other keys for snippet navigation
      :nvi "C-c n"      #'yas-next-field
      :nvi "C-c p"      #'yas-prev-field)`

I want to thank you for coming in this forum and helping people out. you are not even using doom right now and you still take the time to share you experience. over the last 4 years that I have seriously tried to integrate emacs into my life, the yasnippet within orgmode is one where I can see a big potential, but not being able to jump along whatever document I had in mind was bothering me. Now finally I get to use snippets properly. It is going to be a big plus, I have been meaning to write very elaborate prompts I can then send to LLM and having proper snippets will help immensely. From the bottom of my  heart thank you, you made my year, pathetic maybe but I am not even joking :)
best regards, laurent


> [@laurentHYZ](https://github.com/laurentHYZ) let's not go off-topic in this issue any more :) But to answer your question: I have my own (literate) config. Feel free to have a look [here](https://github.com/goderich/.emacs.d/blob/master/config.org).

**Comment by laurentHYZ** [comment]
@nerffan1 @goderich 

Dear Goderich, 
I have used your config and modified it to work with org-mode.
The code below works:
` (map! :map org-mode-map :after yasnippet ;; Retain org-mode's native TAB functionality but allow yas-expand when a snippet is available :nvi [tab]        yas-maybe-expand ;; Optionally, bind other keys for snippet navigation :nvi "C-c n"      #'yas-next-field :nvi "C-c p"      #'yas-prev-field)`

I want to thank you for coming in this forum and helping people out.
 you are not even using doom right now and you still take the time to share you experience. 

Over the last 4 years that I have seriously tried to integrate emacs into my life, the yasnippet within orgmode is one where I can see a big potential, but not being able to jump along whatever document I had in mind was bothering me. 

Now finally I get to use snippets properly.
It is going to be a big plus, I have been meaning to write very elaborate prompts I can then send to LLM and having proper snippets will help immensely. From the bottom of my heart thank you, you made my year, pathetic maybe but I am not even joking :)

best regards, laurent

[@laurentHYZ](https://github.com/laurentHYZ) let's not go off-topic in this issue any more :) But to answer your question: I have my own (literate) config. Feel free to have a look [here](https://github.com/goderich/.emacs.d/blob/master/config.org).

> I have used your config and modified it to work with org-mode. The code below works: ` (map! :map org-mode-map :after yasnippet ;; Retain org-mode's native TAB functionality but allow yas-expand when a snippet is available :nvi [tab] yas-maybe-expand ;; Optionally, bind other keys for snippet navigation :nvi "C-c n" #'yas-next-field :nvi "C-c p" #'yas-prev-field)`
> 
> I want to thank you for coming in this forum and helping people out. you are not even using doom right now and you still take the time to share you experience. over the last 4 years that I have seriously tried to integrate emacs into my life, the yasnippet within orgmode is one where I can see a big potential, but not being able to jump along whatever document I had in mind was bothering me. Now finally I get to use snippets properly. It is going to be a big plus, I have been meaning to write very elaborate prompts I can then send to LLM and having proper snippets will help immensely. From the bottom of my heart thank you, you made my year, pathetic maybe but I am not even joking :) best regards, laurent
> 
> > [@laurentHYZ](https://github.com/laurentHYZ) let's not go off-topic in this issue any more :) But to answer your question: I have my own (literate) config. Feel free to have a look [here](https://github.com/goderich/.emacs.d/blob/master/config.org).
