### ISSUE TITLE
Opening an existing`.org` file uses Doom Docs mode and it is Read Only

### ISSUE THREAD

**Issue by walter-manger** [doomemacs/doomemacs#7751]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open an `.org` file, it should open in Org Mode, and it should not be Read Only.

### Current behavior

When I open an `.org` file in Emacs, it opens in Doom Docs mode and it is Read Only. Emacs should open the file in Org Mode, and it shouldn't be Read Only.

### Steps to reproduce

1. Open Emacs
2. Open an existing `.org` file
3. See that it opens in Doom Docs mode and it is Read Only

### System Information

https://pastebin.com/cwwdyg2w

**Comment by hlissner** [comment]
I cannot reproduce this. Unless you're opening org files inside Doom's source code (in `~/.config/emacs/`), this should not happen.
