### ISSUE TITLE
[bug?] kb shortcuts no longer working

### ISSUE THREAD

**Issue by philiparvidsson** [doomemacs/doomemacs#7756]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

pressing SPC h should show help (.e.g, SPC h v, or k or whatever l

### Current behavior

pressing SPC h just gives "SPC h is undefined" now. also SPC : which used to bring up commands stopped working.

this is a clean install of doom emacs (cloned an hour ago) on emacs-nativecomp 29.3

### Steps to reproduce

install doom emacs, start it, press SPC h

### System Information

https://pastebin.com/XqQdjUYX

**Comment by philiparvidsson** [comment]
not sure what's going on, SPC p f is no longer available either, tons of shortcuts just seem to be gone

**Comment by philiparvidsson** [comment]
so I'm running an older doom emacs commit but the shortcuts are still not working, so I suspect this has to do with emacs 29.3. i was on 29.2 before and it was working fine. trying to figure out what's going on

**Comment by philiparvidsson** [comment]
reverting to 29.2 fixed it for me

**Comment by hlissner** [comment]
Keep in mind that broken keybinds indicates an error occurred during startup, which prevents Doom from finishing the startup process. Keybinds are usually the most visible casualty when this happens. Consult [the debugging guide](https://discourse.doomemacs.org/t/how-to-debug-issues/55) for hints on how to debug these errors.

**Comment by RAOEUS** [comment]
I have this same issue with 29.3. There's nothing of note in the `*Messages*` and I have straight out of the box configurations for emacs and doom. I'm using Arch with the `emacs-nativecomp` package.
