### ISSUE TITLE
Doom sync happens two time when using docker because of the hostname change

### ISSUE THREAD

**Issue by amiorin** [doomemacs/doomemacs#7760]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Now doom rebuilds all package a second time because of this change.
https://github.com/doomemacs/doomemacs/blob/286be1b2496a3ffa2280a16a41f56babebea93f0/lisp/cli/sync.el#L75-L77

The previous behavior was that it was possible to sync during the build of the docker image and during the run of the docker container no new build of all packages was triggered by `doom sync`.

### Current behavior

No need.

### Steps to reproduce

No need

### System Information

https://no-need

**Comment by hlissner** [comment]
As of 12a765c, `doom sync` now has the `-B` option, which will suppress rebuilding on hostname/Emacs version changes. Using that will get around your issue.

**Comment by amiorin** [comment]
Thx.
