### ISSUE TITLE
TAB does not cycle through completion candidates in GUI emacs when using corfu

### ISSUE THREAD

**Issue by lunik1** [doomemacs/doomemacs#7763]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I hit tab when there are completion candidates available, I expect `TAB` to move to the next candidate and update the preview.

### Current behavior

When I press `TAB` in gui emacs, nothing happens.

The behaviour in a tty session is as expected.

### Steps to reproduce

1. Enable `:completion corfu`
2. Open emacs
3. Trigger completion
4. Press tab

### System Information

https://pastebin.com/bPEWaGNP

**Comment by KaiAragaki** [comment]
did #7739 resolve this?

**Comment by lunik1** [comment]
Sorry for the delayed response, can confirm this is fixed.
