### ISSUE TITLE
Corfu: When in prog-mode indenting with tab does not work

### ISSUE THREAD

**Issue by Schievel1** [doomemacs/doomemacs#7767]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

In company-mode pressing TAB when e.g. c-mode is active and in insert-state will indent the line, unless it is already indented to the right position, the it will start company-complete.
This seems to depend on the setting of `tab-always-indent`. 

### Current behavior

When I activate the corfu module instead (and deactivate the company module) TAB always tries to start completion-at-point (it seems, it says `No match` in the minibuffer) regardless of the indentation of the line. 

Being in normal-state indents the line like it should be. 
Also `(setq c-tab-always-indent nil)` does not seem to have an effect at all. Normally this would insert actual tabs if the point is at the end of the line. 

### Steps to reproduce

1. install corfu module
2. open a .c file
3. go to a line which isn't indented correctly
4. press tab

I also changed config.el from the company module and set `tab-always-indent` in there to nil, but that doesn't do the trick. 
Also setting that in c-mode hook or corfu-mode-hook does not work. 

### System Information

https://pastebin.com/xHcHEWhW
Yes I know this is Emacs 29.50, but I can reproduce on a plain Emacs 29 as well.

**Comment by tricera-josua-palmstedt** [comment]
This is already adressed in #7739 (and just the fix would be this #7746).
Until this is merged I'm using `C-i` instead.

**Comment by Schievel1** [comment]
Ok, thanks. I checked the issues if someone elses reported that but I haven't checked the PRs if someone fixed it already.

**Comment by davidbudzynski** [comment]
I'm experiencing the same issue, so merging the PR would be helpful!

**Comment by KaiAragaki** [comment]
@Schievel1 This PR has been merged! Can this issue be closed?

**Comment by Schievel1** [comment]
Yup, thanks
