### ISSUE TITLE
mu4e: 1.12 breaks `org-msg`

### ISSUE THREAD

**Issue by 45mg** [doomemacs/doomemacs#7770]
See https://github.com/jeremy-compostella/org-msg/issues/182 - there is no clear fix in sight yet. Users with a version of `mu` > 1.10 will need to downgrade somehow - I was able to do this by building mu from source, and then adding the lisp directory to `load-path` as described in the docs. This affects users of the AUR package, which is on 1.12.

**Comment by purgat0ri** [comment]
Seems like a fix has finally come through on the Master branch: https://github.com/jeremy-compostella/org-msg/issues/182

**Comment by hlissner** [comment]
I've bumped org-msg in https://github.com/doomemacs/doomemacs/commit/200c9083152184e26b6a1c9f8a14581729ba5f02, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
