### ISSUE TITLE
doom install doesn't create default doom config file on first install

### ISSUE THREAD

**Issue by seasea128** [doomemacs/doomemacs#7772]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When doom install is executed for the first time (basically when new user installs Doom Emacs), it would create all of the necessary doom configuration file.

### Current behavior

When executing doom install for the first time, it doesn't create the necessary doom configuration file.
Reverting back to 201051c368cfdabf3f68c372939297380999e28d fixes this issue.

### Steps to reproduce

1. Clone the repo
2. Run `doom install`
3. After the install process finished, no file exist in ~/.config/doom.

### System Information

https://pastebin.com/wM7t54fq

**Comment by hlissner** [comment]
This was fixed in https://github.com/doomemacs/doomemacs/commit/b6b755dea4546a7ae6d7dfb3fbfdbd71036a01fc. Please update Doom before running `doom install` again.
