### ISSUE TITLE
reloading doom keeps asking to rebuild packages

### ISSUE THREAD

**Issue by Padswynn** [doomemacs/doomemacs#7775]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I would like to run `doom sync` or `M-x doom/reload` without rebuilding packages every time.

### Current behavior

I want to reload my config. with `M-x doom/reload`. Whenever I run `doom/reload` or `$doom sync`, i get the following:
```
- Using Emacs 29.3 @ /usr/bin/emacs
> Synchronizing "default" profile...
  ! Emacs version has changed since last sync (from 29.2 to 29.3)
    Installed packages must be rebuilt. Do so now? (y or n) 
```
I have already run `doom upgrade` since updating emacs. I have run `doom sync` a least 5 times. It just keeps saying the emacs version has changed.

I can confirm I am using emacs 29.3:
```
$ emacs --version
GNU Emacs 29.3
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ eselect emacs list
Available Emacs symlink targets:
  [1]   emacs-29 *
```
Its the only version I still have downloaded.

### Steps to reproduce

1. `doom sync`

### System Information

https://pastebin.com/Gfq8gtjd

**Comment by hlissner** [comment]
As of b01e496 you should no longer be trapped in a build loop. You may still be prompted one last time, but you can avoid this by deleting `~/.config/emacs/.local/etc/sync` first.

**Comment by Padswynn** [comment]
Thanks a bunch! <3
