### ISSUE TITLE
projectile: project-find-file should not follow symlinks

### ISSUE THREAD

**Issue by Atemu** [doomemacs/doomemacs#7781]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I run `project-find-file`, it should show available symlinks inside the project but not follow them and list content under the followed path.

### Current behavior

Symlinks are followed. Hard-coded here:

https://github.com/doomemacs/doomemacs/blob/5f5a163c49207a7083ab1ecc9e78d268fd6600b8/lisp/doom-projects.el#L196

Removing `--follow` here fixes the issue but that's not trivially possible from user config.

### Steps to reproduce

1. Have a project with symlinks inside (commonly the case with `result` symlinks with Nix)
2.  `project-find-file`
3. Observe contents under the symlink present

### System Information

https://pastebin.com/z6czCYHp

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/4fc11b696e109db27321850203ce897be438b512, following symlinks is no longer the default. Thanks for bringing it to my attention!

**Comment by Atemu** [comment]
Thanks a bunch for fixing this! :)
