### ISSUE TITLE
doom sync deletes local packages

### ISSUE THREAD

**Issue by agzam** [doomemacs/doomemacs#7785]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [ ] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Shouldn't delete things in config dir

### Current behavior

I have multiple packages declared in custom modules with 

`:recipe (:local-repo ...)`

`doom sync` and `doom up` are trying this:

    > Building bla-bla ...
    Failed to clone "bla-bla", trying again (attempt #1)...
    Failed to clone "bla-bla", trying again (attempt #2)...
    Failed to clone "bla-bla", trying again (attempt #3)...
    x There was an unexpected runtime error
        Message: Failed to clone package
        
And then proceeds to deleting the entire package directory. That's weird.

<details>
  <summary>Here's one example log</summary>

        > Building evilify-edebug...
        Failed to clone "evilify-edebug", trying again (attempt #1)...
        Failed to clone "evilify-edebug", trying again (attempt #2)...
        Failed to clone "evilify-edebug", trying again (attempt #3)...
        x There was an unexpected runtime error
        Message: Failed to clone package
        Backtrace:
            (error "Failed to clone package")
            (progn (error "Failed to clone package"))
            (if (= try 3) (progn (error "Failed to clone package")))
            (while (not (file-directory-p (doom-path repo-dir ".git"))) (if (= try 3) (progn (error "Failed ...
            (let ((try 0)) (while (not (file-directory-p (doom-path repo-dir ".git"))) (if (= try 3) (progn ...
            (let ((straight-vc-git-post-clone-hook (cons #'(lambda (&rest --cl-rest--) "\n\n(fn &key REPO-DI...
            (condition-case e (let ((straight-vc-git-post-clone-hook (cons #'(lambda (&rest --cl-rest--) "\n...
            (let ((repo-dir (straight--repos-dir (or local-repo package))) (build-dir (straight--build-dir p...
            (let* ((--cl-rest-- (append (list :recipe recipe) recipe)) (package (car (cdr (plist-member --cl...
            (cl-destructuring-bind (&key package local-repo recipe &allow-other-keys) (append (list :recipe ...
            (straight--with-plist (append (list :recipe recipe) recipe) (package local-repo recipe) (let ((r...
            (let ((recipe (car tail))) (straight--with-plist (append (list :recipe recipe) recipe) (package ...
        ! Wrote extended backtrace to ~/.emacs.d/.local/state/logs/cli.doom.240401143453.127217.error
        ! Script was abruptly aborted, leaving Doom in an incomplete state!
        - Run 'doom sync' to repair it.
        ✓ Finished in 5.93698s

</details>

### Steps to reproduce

Declare a local package, run doom sync

### System Information

https://pastebin.com/h0B8mKXb

**Comment by hlissner** [comment]
Good catch! As of c6fc0e5 this should be fixed. Thanks for bringing it to my attention!

**Comment by agzam** [comment]
Of wow. That was quick. Thank you, Henrik! It freaked me out for a second when it started deleting things.
