### ISSUE TITLE
Corfu is broken in eshell

### ISSUE THREAD

**Issue by maikol-solis** [doomemacs/doomemacs#7789]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Autocompleting strings in eshell with corfu, should give a nice popup with the possible candidates. 

### Current behavior

After installing the new corfu module, I'm getting these errors when using eshell. 

Basically, the autocompletion is broken and I cannot get any candidates to complete

**Using pandoc**
 
```emacs-lisp 
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  split-string(nil "\n" t)
  fish-completion--list-completions("pandoc pap")
  #f(compiled-function () #<bytecode 0xbaa546954b4dd98>)()
  pcomplete--here(#f(compiled-function () #<bytecode 0xbaa546954b4dd98>) nil nil nil)
  fish-completion-complete("pandoc pap")
  fish-completion-shell-complete()
  pcomplete-completions()
  #<subr pcomplete-completions-at-point>()
  cape-wrap-properties(#<subr pcomplete-completions-at-point> :exclusive no)
  cape-wrap-nonexclusive(#<subr pcomplete-completions-at-point>)
  apply(cape-wrap-nonexclusive #<subr pcomplete-completions-at-point> nil)
  pcomplete-completions-at-point()
  corfu--capf-wrapper(pcomplete-completions-at-point t)
  corfu--capf-wrapper-advice(#<subr completion--capf-wrapper> pcomplete-completions-at-point all)
  apply(corfu--capf-wrapper-advice #<subr completion--capf-wrapper> (pcomplete-completions-at-point all))
  completion--capf-wrapper(pcomplete-completions-at-point all)
  completion-at-point()
  funcall-interactively(completion-at-point)
  command-execute(completion-at-point)
```

**Using texliveonfly**
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  split-string(nil "\n" t)
  fish-completion--list-completions("texliveonfly paper_")
  #f(compiled-function () #<bytecode -0x6d843028d2f6983>)()
  pcomplete--here(#f(compiled-function () #<bytecode -0x6d843028d2f6983>) nil nil nil)
  fish-completion-complete("texliveonfly paper_")
  fish-completion-shell-complete()
  pcomplete-completions()
  #<subr pcomplete-completions-at-point>()
  cape-wrap-properties(#<subr pcomplete-completions-at-point> :exclusive no)
  cape-wrap-nonexclusive(#<subr pcomplete-completions-at-point>)
  apply(cape-wrap-nonexclusive #<subr pcomplete-completions-at-point> nil)
  pcomplete-completions-at-point()
  corfu--capf-wrapper(pcomplete-completions-at-point t)
  corfu--capf-wrapper-advice(#<subr completion--capf-wrapper> pcomplete-completions-at-point all)
  apply(corfu--capf-wrapper-advice #<subr completion--capf-wrapper> (pcomplete-completions-at-point all))
  completion--capf-wrapper(pcomplete-completions-at-point all)
  completion-at-point()
  funcall-interactively(completion-at-point)
  command-execute(completion-at-point)

```

### Steps to reproduce

1. Open eshell 
2. Try to autocomplete a path after a command. I usually use pandoc to convert files, but it's also happened with other commands like texliveonfly. 

### System Information

https://pastebin.com/eJfxPz2p

**Comment by hlissner** [comment]
Seems this was an upstream issue that was [fixed some time ago](https://github.com/LemonBreezes/emacs-fish-completion/commit/9a741c20044f196ae3bf434db74be17f1f479acf). I've bumped fish-completion in 2a2565f, which should fix this issue. Thanks for bringing it to my attention!
