### ISSUE TITLE
doom upgrade {--jobs | -j } causes `symbol val void`

### ISSUE THREAD

**Issue by yaaama** [doomemacs/doomemacs#7791]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I write the command "doom upgrade --jobs 4" it should upgrade and use 4  j threads

### Current behavior

Instead it causes the following error:

<details><summary>Details</summary>
<p>

x There was an unexpected runtime error
  Message: Symbol's value as variable is void
  Details: (num)
  Backtrace:
    (list "-j" num)
    (if jobs (list "-j" num))
    (append '("sync" "-u") (if nobuild? '("-B")) (if jobs (list "-j" num)))
    (let* ((force? (progn (or (progn (and (memq (type-of context) cl-struct-doom-cli-context-tags) t)) (signal 'wrong-type-argument (list 'doom-cli-context context))) (aref context 6)))...
    (let ((packages? (cdr (assq 'packages? alist))) (jobs (cdr (assq 'jobs alist))) (nobuild? (cdr (assq 'nobuild? alist))) (context (cdr (assq 'context alist)))) (let* ((force? (progn ...
    ((closure (t) (cli alist) (let ((packages? (cdr (assq 'packages? alist))) (jobs (cdr (assq 'jobs alist))) (nobuild? (cdr (assq 'nobuild? alist))) (context (cdr (assq 'context alist)...
    (funcall (closure (t) (cli alist) (let ((packages? (cdr (assq 'packages? alist))) (jobs (cdr (assq 'jobs alist))) (nobuild? (cdr (assq 'nobuild? alist))) (context (cdr (assq 'contex...
    (doom-cli-execute #s(doom-cli ("doom" "upgrade") nil (("SUMMARY" . "Updates Doom and packages.") ("MAIN" . "This requires that ~/.emacs.d is a git repo, and is the equivalent of the...
    (let ((cli x16) (bindings x17)) (doom-cli-execute cli bindings))
    (let* ((x16 (car-safe x15)) (x17 (cdr-safe x15))) (let ((cli x16) (bindings x17)) (doom-cli-execute cli bindings)))
    (progn (ignore (consp x15)) (let* ((x16 (car-safe x15)) (x17 (cdr-safe x15))) (let ((cli x16) (bindings x17)) (doom-cli-execute cli bindings))))
    (let ((x15 (car tail))) (progn (ignore (consp x15)) (let* ((x16 (car-safe x15)) (x17 (cdr-safe x15))) (let ((cli x16) (bindings x17)) (doom-cli-execute cli bindings)))) (setq tail (...
  ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240404000602.121461.error
</p>
</details> 

### Steps to reproduce

Type in `doom upgrade --jobs 4` and it failed

### System Information

https://pastebin.com/rXV9F2TF

### Note

Doom upgrade seems to work fine though.

**Comment by hlissner** [comment]
Good catch! As of 2debe85 this should be fixed. Thanks for bringing it to my attention!
