### ISSUE TITLE
corfu: latest bump to evil breaks minibuffer completion

### ISSUE THREAD

**Issue by 45mg** [doomemacs/doomemacs#7798]
(EDIT: waiting for fix to be merged upstream, see last comment)

### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I press TAB (invoke `completion-at-point`) in the minibuffer, I should see the Corfu popup with a list of candidates. I should then be able to select candidates with `C-n` and `C-p`.

### Current behavior

None of the usual Corfu commands work. To elaborate - when a few characters are typed as input, the popup does show up if auto-completion is on. However, no candidates can be selected or inserted (there's no error message of any kind). Instead, keybindings that should interact with Corfu in some way (I tested `TAB`, `C-n`, `C-p`) now make the popup disappear and do nothing else.

 For example, when I press TAB, `view-lossage` shows that `completion-at-point` is being run, and the value of `completion-at-point-functions` looks appropriate (eg. `(comint-completion-at-point t cape-dabbrev)` for `shell-command`). However, all the happens is that the Corfu popup goes away.

I used `git bisect` to determine that the bug was introduced by https://github.com/doomemacs/doomemacs/commit/13b60b9702ea7868ecf5716d352a7e053ec6dd3f, which bumps :editor evil. Here is the `git bisect log`:
```
git bisect start
# status: waiting for both good and bad commits
# good: [c6fc0e5bc018efc7ee8174dbbec8cff28644ad54] fix(cli): don't delete repos beyond $DOOMLOCALDIR
git bisect good c6fc0e5bc018efc7ee8174dbbec8cff28644ad54
# status: waiting for bad commit, 1 good commit known
# bad: [82e0641bf758c782ebf9ed0a9ba9561f4c379b5a] refactor: remove redundant auto-mode-alist entries
git bisect bad 82e0641bf758c782ebf9ed0a9ba9561f4c379b5a
# bad: [869ad10f34fdbb9132994e85b0dbe7cf0ce2274c] refactor: startup optimizations
git bisect bad 869ad10f34fdbb9132994e85b0dbe7cf0ce2274c
# bad: [beb6e8763696658b4aada08c71bc749889ea90d8] bump: :tools magit :emacs vc
git bisect bad beb6e8763696658b4aada08c71bc749889ea90d8
# bad: [34a9c3d0b3a5e3645fb7fe564eb02c0ebc51ee68] bump: :editor snippets
git bisect bad 34a9c3d0b3a5e3645fb7fe564eb02c0ebc51ee68
# bad: [13b60b9702ea7868ecf5716d352a7e053ec6dd3f] bump: :editor evil
git bisect bad 13b60b9702ea7868ecf5716d352a7e053ec6dd3f
# first bad commit: [13b60b9702ea7868ecf5716d352a7e053ec6dd3f] bump: :editor evil
```

### Steps to reproduce

1. Ensure you have `+corfu-want-minibuffer-completion` and `corfu-auto` set to `t`; if not, do so and restart Emacs.
2. Run any command that uses minibuffer input and would normally have completion. For example, `shell-command` or `evil-ex`.
3. Type a few letters to get the auto-completion popup.
4. Press any keybinding that would normally invoke completion (eg. TAB if it's bound to `completion-at-point`).
5. Observe that the popup disappears and the binding's action is not performed.

### System Information

https://0x0.st/XiaI.txt

**Comment by 45mg** [comment]
Found the offending commit! https://github.com/emacs-evil/evil-collection/commit/198578a2558c7b7c3999d9c8af526c030e716e6a.

**Comment by 45mg** [comment]
Opened a PR to fix it: https://github.com/emacs-evil/evil-collection/pull/803. When it gets merged, Doom should bump evil-collection again.

**Comment by 45mg** [comment]
Oh wait, looks like @LemonBreezes found the issue and fixed it several hours ago. Doom should bump evil-collection when his PR https://github.com/emacs-evil/evil-collection/issues/801 is merged.

**Comment by LemonBreezes** [comment]
> Oh wait, looks like @LemonBreezes found the issue and fixed it several hours ago. Doom should bump evil-collection when his PR https://github.com/emacs-evil/evil-collection/issues/801 is merged.

It's just been merged.

**Comment by hlissner** [comment]
As of a3de6ad issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
