### ISSUE TITLE
which-key-mode issues after upgrade

### ISSUE THREAD

**Issue by bechampion** [doomemacs/doomemacs#7804]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I get this message when doom starts ```Error in pre-command-hook (chain-doom-first-input-hook-to-pre-command-hook-h): (doom-hook-error doom-first-input-hook which-key-mode (error "‘which-key-mode’ can’t be used with ‘helm-descbinds-mode’"))
```

### Current behavior

I get this when doom starts ```Error in pre-command-hook (chain-doom-first-input-hook-to-pre-command-hook-h): (doom-hook-error doom-first-input-hook which-key-mode (error "‘which-key-mode’ can’t be used with ‘helm-descbinds-mode’"))
```

### Steps to reproduce

upgrade

### System Information

a

**Comment by hlissner** [comment]
Update Doom. This was already fixed in https://github.com/doomemacs/doomemacs/commit/a4b7aa1c56f47bdf33796099e3006cbafe194b71.
