### ISSUE TITLE
problem with savehist-mode causing `doom-first-input-hook` to throw an error

### ISSUE THREAD

**Issue by Padswynn** [doomemacs/doomemacs#7817]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I start doom emacs, the `doom-first-input-hook` should succeed, enabling things such as `which-key-mode` and `savehist-mode`

### Current behavior

Instead, I get an error caused by the `savehist-mode` hook:
```
⛔ Error (doom-first-input-hook): Error running hook "savehist-mode" because: (user-error Local variables entry is missing the prefix)
```
Possibly related to  #3535 which went stale?

### Steps to reproduce

1. Open emacs
2. press any prefix key
3. Error pops up

### System Information

https://pastebin.com/7V8SrDKm

**Comment by hlissner** [comment]
I can't reproduce this. I suspect savehist took in a faulty value in `~/.config/emacs/.local/cache/savehist`. See if the error persists if you move the file to another location. If it goes away, it'd be a good idea to look through the file to find the culprit. I'm hesitant to ask you to post it, because it may contain sensitive information.

**Comment by Padswynn** [comment]
> I can't reproduce this. I suspect savehist took in a faulty value in `~/.config/emacs/.local/cache/savehist`. See if the error persists if you move the file to another location. If it goes away, it'd be a good idea to look through the file to find the culprit. I'm hesitant to ask you to post it, because it may contain sensitive information (mainly history from your clipboard and various minibuffer commands, like `M-x`).

Yea that fixed it....
Looking through the file, not sure what I should look for to find the culprit?
In any case, my problem is solved — appreciate the help!
