### ISSUE TITLE
doom-module-from-path couldn't handle symbolic links correctly.

### ISSUE THREAD

**Issue by kilesduli** [doomemacs/doomemacs#7821]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom-autoloads--scan` correctly handles symbolic links located under `doom-core-dir`.

### Current behavior

When doom sync calls `doom-autoloads--scan` to generate autoload, it will call `file-truename` to get the true location of the file. When a file is a symbolic link in `doom-core-dir`, since the actual file location is not under the doom-core-dir directory, it will not be judged as a core module, resulting in the generated `init.el` file not containing Contents of this file.

https://github.com/doomemacs/doomemacs/blob/5b7d6763f8f899e556c7c5d89556bf39a1c81f64/lisp/doom-modules.el#L348-L357

### Steps to reproduce

1. make files in doom-core-dir is symbolic links. such as :)
![image](https://github.com/doomemacs/doomemacs/assets/43215593/fa6f616e-fa67-4b6e-bce2-a712d76867c4)

2. The init.el generated by doom sync does not contain them.

### System Information

https://pastebin.com/cA7VhH4x

**Comment by kilesduli** [comment]
Actually, I think doom-user-dir also needs special handling...

**Comment by hlissner** [comment]
There *must* be another way. I'm not keen on supporting this degree of symlinkery madness. Calling `file-truename` all over the place is relatively expensive. I opt-out of it *inside* `doom-core-dir` to avoid that overhead. Why not symlink `doom-core-dir` itself? Or `doom-emacs-dir`? Every single file is madness, frankly.

In any case, I'll see if I can address this particular issue, but *please* reconsider that setup. Even if I manage to fix it, I don't intend to officially support *that* degree of symlinkery in `doom-core-dir`.

**Comment by kilesduli** [comment]
> Calling file-truename all over the place is relatively expensive. I opt-out of it inside doom-core-dir to avoid that overhead. 

In fact, file-truename is called in two places:
- The first time is when `doom-sync` calls `doom-autoloads--scan` through `doom-profile--generate-doom-autoloads`, and `file-truename` is called once in [autoloads.el#172](https://github.com/doomemacs/doomemacs/blob/5b7d6763f8f899e556c7c5d89556bf39a1c81f64/lisp/lib/autoloads.el#L172), turning the symbolic link into a real link.
- Then, the [file-in-directory-p](https://github.com/emacs-mirror/emacs/blob/930c578c1042e6372e5433e31b2ea801315c01c9/lisp/files.el#L6591) function used in `doom-module-path-from` will internally call file-truename once for file and dir.

Although it seems crazy that every file is a symlink, I think a simpler solution is to replace `file-in-directory-p` and remove the `file-truename` call in `doom-autoloads--scan`. which can Avoiding the calling overhead also makes it work.
