### ISSUE TITLE
anaconda-mode activates despite using (lsp +eglot)

### ISSUE THREAD

**Issue by egr95** [doomemacs/doomemacs#7823]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a python buffer, anaconda-mode should not be enabled since I am already using eglot. I think the issue is because the following condition fails to detect that I am running eglot, perhaps because `eglot--managed-mode` is only activated after the condition is checked? See `doom/modules/lang/python/config.el`
```
  (add-hook! 'python-mode-local-vars-hook :append
    (defun +python-init-anaconda-mode-maybe-h ()
      "Enable `anaconda-mode' if `lsp-mode' is absent and
`python-shell-interpreter' is present."
      (unless (or (bound-and-true-p lsp-mode)
                  (bound-and-true-p eglot--managed-mode)
                  (bound-and-true-p lsp--buffer-deferred)
                  (not (executable-find python-shell-interpreter t)))
        (anaconda-mode +1))))
```

### Current behavior

When I open a python buffer, anaconda-mode is enabled. Bindings like `M-.` should not be taken over by anaconda-mode.

### Steps to reproduce

Enable `(lsp +eglot)` and `(python +lsp)` in `init.el`. Then open emacs and open a python buffer. Then use `C-h m` to check the active modes, and you will see anaconda-mode show up.

### System Information

https://pastebin.com/LnNZuLUD

**Comment by gchape** [comment]
@egr95 
Do you have any updates?

**Comment by egr95** [comment]
It seems to me like this is a bug in doom itself, but I might be wrong. If doom ends up migrating its defaults from lsp-mode to eglot then this will presumably affect more poeple and get fixed. For now, I don't really have a solution, but my temporary workaround is to go into `doom/modules/lang/python/config.el` and comment out the relevant chunk:
```
(use-package! anaconda-mode
...
```

**Comment by egr95** [comment]
Thank you @hlissner!
