### ISSUE TITLE
Wrong mode and missing syntax-highlighting when opening ConTeXt-file

### ISSUE THREAD

**Issue by pepperblue** [doomemacs/doomemacs#7853]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a ConTeXt-file ConTeXt-mode gets enabled and syntax-highlighting is present.

### Current behavior

When I open a file with extension ".tex" and the following content:
```
\setuppapersize[A6]
\starttext
\startsection[title={Testing ConTeXt}]
This is my first ConTeXt document
\stopsection
\stoptext
```
LaTeX/PS-mode gets enabled and no syntax-highlighting is present

### Steps to reproduce

1. activate module "latex"
2. open emacs
3. load ConTeXt-file

### System Information

https://pastebin.com/XvjvF7PS

**Comment by hlissner** [comment]
Are you still seeing this issue? If so, could you [check the \*Messages\* buffer for errors/warnings](https://discourse.doomemacs.org/t/how-to-debug-issues/55) after loading a ConTeXt-file? And if you spot an error, please [produce a backtrace from it](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85).

**Comment by pepperblue** [comment]
Sorry for the delay. Opening a ConTeXt-file now the mode is "ConTeXt-en/PS". Syntax-highlighting is very minimal - I'm not shure if there should be more of it (see attached screenshot).
![context-highlighting](https://github.com/user-attachments/assets/2107dc60-7905-4277-be53-2697363c7835)
No errors/warnings appear in the *Messages* buffer.

**Comment by hlissner** [comment]
This is a bug in [doomemacs/themes](https://github.com/doomemacs/themes) and [I've fixed it there](https://github.com/doomemacs/themes/commit/1cac71a4b2434036496a49b4440fdba3d0b5b387). You'll need to (un|re)pin the `doom-themes` package until I've bumped the `:ui doom` module. I.e.

```lisp
;;; add to $DOOMDIR/packages.el
(package! doom-themes :pin "1cac71a4b2434036496a49b4440fdba3d0b5b387")

;; Then `doom sync` and restart Emacs
```

I'll leave this issue open until I've bumped the module.

**Comment by hlissner** [comment]
`doom-themes` was bumped in [03fbb00](https://github.com/doomemacs/doomemacs/commit/03fbb00e3c1f71070386de6bab101d452189b5b3), which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by tluu11** [comment]
unsubscribe
