### ISSUE TITLE
doom doctor fails

### ISSUE THREAD

**Issue by seokbeomKim** [doomemacs/doomemacs#7857]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

doom doctor must be done without any errors.

### Current behavior

When I do `doom doctor`, it fails from `(straight--modifications find-at-startup)`.

$ doom doctor
The doctor will see you now...

```
> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Wrong type argument
    Details: (listp t)
    Backtrace:
      (memq find-at-startup t)
      (straight--modifications find-at-startup)
      (or (straight--modifications 'find-at-startup) (and (straight--modifications 'find-when-checking) straight--allow-find))
      (if (or (straight--modifications 'find-at-startup) (and (straight--modifications 'find-when-checking) straight--allow-find)) nil (throw '--cl-block-straight--package-might-...
      (progn (if local-repo nil (throw '--cl-block-straight--package-might-be-modified-p-- nil)) (if (or (straight--modifications 'find-at-startup) (and (straight--modifications ...
      (or (null build-info) (catch '--cl-block-nil-- (let ((tail straight--build-keywords)) (while tail (let ((keyword (car tail))) (if (equal (plist-get recipe keyword) (plist-g...
      (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ':package)))) (local-repo (car (cdr (plist-member --cl-rest-- ':local-repo)))) (build-info (gethash...
      (catch '--cl-block-straight--package-might-be-modified-p-- (let* ((--cl-rest-- recipe) (package (car (cdr (plist-member --cl-rest-- ':package)))) (local-repo (car (cdr (pli...
      (straight--package-might-be-modified-p (:type git :host github :repo "melpa/melpa" :build nil :package "melpa" :local-repo "melpa") t)
      (or (and straight--packages-to-rebuild (or (eq straight--packages-to-rebuild :all) (gethash package straight--packages-to-rebuild)) (not (gethash package straight--packages...
      (let* ((no-build (or (null local-repo) (straight--build-disabled-p recipe) (if (let ((object no-build)) (and (not (memq object '(no-build t))) (functionp object))) (funcall...
      (let ((already-registered (gethash package straight--success-cache)) (available (or (null local-repo) (straight--repository-is-available-p recipe)))) (if (if (let ((object ...
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240505114203.18982.error
```

And, here's the backtrace:
- https://gist.github.com/seokbeomKim/2eeb003ac1481f81aa478d2e71950943

### Steps to reproduce

1. `doom doctor`
2. Error from `(memq find-at-startup)`

### System Information

https://gist.github.com/seokbeomKim/78c699efb0ffef03547eb66c1c37e24e

**Comment by hlissner** [comment]
I can't reproduce this. Are you sure you're not setting `straight-check-for-modifications` to `t` somewhere in your config? Doom doesn't. If it's not a local issue, it may have been a transient upstream issue in Straight, which has been bumped a couple times since you opened this issue. For the time being I'll assume it's been resolved, but let me know if you're still seeing the issue. If I can establish a better, causal link to Doom, I'll reopen this.
