### ISSUE TITLE
Build doom for two different emacs installations on the same machine

### ISSUE THREAD

**Issue by jack836** [doomemacs/doomemacs#7859]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Sorry for a newbie question. I am posting it here because I didn't find help elsewhere....

I have two different emacs-29.1 binaries on my PC ( x86_64 and arm64 builds).  Doom is already built with the Emacs-x86_64 version and I have recently added the Emacs-arm64. How do I build doom for the newly added emacs? Is there a way to instruct `doom install' to pick a particular emacs installation? Any help is highly appreciated.

### Current behavior

NA

### Steps to reproduce

NA

### System Information

Emacs-29.1 on Mac OS X

**Comment by woochica** [comment]
Hi!

Looking at the source code of the `doom` script, it contains the following comment:

> ENVIRONMENT VARIABLES:
>
>  `$EMACS'
>
>    The Emacs executable or command to use for any Emacs operations in this or
>    other Doom CLI shell scripts (default: first emacs found in `$PATH').

I assume your x86_64 build is the default one, meaning typing `emacs` will start that.

You have two options:
- Directly set the value of `$EMACS` to point to the arm64 binary when invoking `doom`, i.e. `EMACS=/path/to/arm64/build/emacs doom install`
- Change the content of `$PATH` in your shell's config to make sure that the arm64 binary comes first. This will make you launch the arm64 version whenever calling `emacs`.

**Comment by hlissner** [comment]
What woochica said.

You may also want to set `DOOMLOCALDIR`, because there's a chance build artifacts produced on one build may be incompatible with the other (such as byte-code). E.g.

```sh
EMACS=/path/to/arm64/emacs DOOMLOCALDIR=~/.config/emacs/.local.arm64 doom install
EMACS=/path/to/x64_86/emacs DOOMLOCALDIR=~/.config/emacs/.local.x64_86 doom install
```

Then launch them with:

- `DOOMLOCALDIR=~/.config/emacs/.local.arm64 emacs`
- `DOOMLOCALDIR=~/.config/emacs/.local.x64_86 emacs`

In any case, user support posts don't belong on our issue tracker. Please post on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) in the future.
