### ISSUE TITLE
org-msg-edit-mode-mu4e: Symbol’s function definition is void: mu4e~compose-remap-faces

### ISSUE THREAD

**Issue by kuba-orlik** [doomemacs/doomemacs#7860]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Running `+mu4e/compose` should open the message compose buffer

### Current behavior

An error shows up saying:

```
org-msg-edit-mode-mu4e: Symbol’s function definition is void: mu4e~compose-remap-faces
```

### Steps to reproduce

1. Open emacs
2. Press `C-M M`
3. `M-x +mu4e/compose`

### System Information

https://pastebin.com/nwQeky5W

**Comment by david-alvarez-rosa** [comment]
Same error here, after update

**Comment by robby4769** [comment]
same error here too

**Comment by hlissner** [comment]
(Please use the `:+1:` reaction on the original post rather than replying with 'same error', unless you have more to add to the issue).

I believe the root of this issue is that mu4e has made some backwards incompatible changes (again). As I don't use mu4e, it'll take some time for me to get around to updating the mu4e module, but I'll accept a PR to do so.

**Comment by ashwinp15** [comment]
@kuba-orlik Did you try it with any older versions of `mu4e` to make it work?

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/60e94479a7952a9939b349dc478378ea47289fa9 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
