### ISSUE TITLE
Failed to locate module

### ISSUE THREAD

**Issue by amrit3128** [doomemacs/doomemacs#7861]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

doom sync not working

### Current behavior

```
! Failed to locate a ':term eshell' module
- Using Emacs 29.3 @ /usr/bin/emacs
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    ✓ All 271 packages are up-to-date
  > Purging orphaned packages (for the emperor)...
    - Skipping builds
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
    - Skipping native bytecode
  > (Re)building profile in /home/amrit/.config/emacs/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling ~/.config/emacs/.local/etc/@init.29.el...
    ✓ Built init.29.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
```

### Steps to reproduce

run doom/sync

### System Information

https://pastebin.com/fJYKW3C9

**Comment by goodvibrations32** [comment]
@Amrit-codes running `doom build` and then `doom sync` will first build each package and then sync with your config...
Hope this helps...if not `doom sync -u` will attempt to upgrade and then sync with the pers. config..
