### ISSUE TITLE
Elixir LSP not formatting

### ISSUE THREAD

**Issue by ankhers** [doomemacs/doomemacs#7864]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I save an Elixir file, I expect elixir ls to format the file

### Current behavior

When I save the Elixir file, `apheleia-mode` ends up being used to format the buffer instead.

If I remove `elixir-mode` from `apheleia-mode-alist` and try to save a file, no formatting happens. 

When I manually run `+format/buffer`, it does use the configured LSP in order to format the buffer. `+format-with-lsp` is also set to `t`. 

### Steps to reproduce

1. With `(elixir +lsp)` and lsp enabled in general
2. Open an Elixir file (.ex)
3. make some modifications
4. save the file

### System Information

https://paste.sr.ht/~ankhers/53edc4aa233207d9ca989bc76617b32f739f18f0

**Comment by gchape** [comment]
Can you enable `(format +onsave)` at `$DOOM_DIR/init.el`?

![Screenshot from 2024-06-30 13-09-17](https://github.com/doomemacs/doomemacs/assets/118893979/4c89313e-004e-4520-afdd-ad7ba3a75b9f)

**Comment by ankhers** [comment]
Sorry, I should have added that to the original post. `(format +onsave)` is already enabled.

**Comment by gchape** [comment]
> Sorry, I should have added that to the original post. `(format +onsave)` is already enabled.

Can you check it with this snippet:
```(add-hook 'elixir-mode-hook
          (lambda () (add-hook 'before-save-hook 'elixir-format nil t)))```

**Comment by hlissner** [comment]
That `before-save-hook` will make the package use `mix` or `elixir` directly, not `elixir-ls`. Eglot integration into the `:editor format` needs some work, which I'm already working on.

While we wait for that, try `M-x eglot-format-buffer` and tell me if it successfully formats the buffer. If it does, it will rule out any issue on Eglot's end, at least.

**Comment by ankhers** [comment]
> try `M-x eglot-format-buffer` and tell me if it successfully formats the buffer. If it does, it will rule out any issue on Eglot's end, at least.
> 

My setup is using lsp-mode instead of eglot. I can switch to eglot to test things, but is there an equivalent lsp-mode command to try?

**Comment by hlissner** [comment]
Oops, my bad. Got my wires crossed. I meant that the LSP integration into `:editor format` needs the same work the Eglot integration does, and that you should try `M-x lsp-format-buffer`, instead.

**Comment by ankhers** [comment]
Yes, `M-x lsp-format-buffer` does format the buffer. Just for fun, I also switched to `eglot` and `M-x eglot-format-buffer` also seems to work.
