### ISSUE TITLE
evil-org-mode location changed

### ISSUE THREAD

**Issue by honggw** [doomemacs/doomemacs#7875]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I got a git rev-parse HEAD error about evil-org-mode package while installing the doom emacs ,I checked the repository location of evil-org-mode and found that the package no longer located in hlissner/evil-org-mode but doomelpa/evil-org-mode 

### Current behavior

edit the file modules/lang/org/packages.el line 69 ，substitue the 'hlissner/evil-org-mode' with 'doomelpa/evil-org-mode' 

### Steps to reproduce

1. just run command: "doom install"

### System Information

https://pastebin.com/ek2bpBfk

**Comment by peterhoeg** [comment]
I suggest trying to blow away the checkout for that package and trying again. While it *has* moved as you point out, github should simply redirect to the new location transparently and let you install as expected.

**Comment by hlissner** [comment]
What peterhoeg said, but I've updated the ref in 4788dd6. Thanks for bringing it to my attention!
