### ISSUE TITLE
`indent-guides` breaking line spacing on small zoom levels.

### ISSUE THREAD

**Issue by vikdotdev** [doomemacs/doomemacs#7881]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I reduce the zoom level significantly, I expect the line height not to increase relative to the font size. 

### Current behavior

When zoom level is reduced significantly, indent guides seem to remain big and induce large vertical spacing between lines.

https://github.com/doomemacs/doomemacs/assets/33513522/823bc70b-e9c5-400e-89b8-015ac1f85dcd

This becomes annoying on hi-dpi screens where lower zoom levels might be preferable in some situations.

### Steps to reproduce

- On a fresh Fedora 40 install (live-cd to be precise):
```bash
sudo dnf install emacs -y

git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
```
- Edit `doom/init.el` to include `indent-guides` package and reload with `SPC-h-r-r`.
- Reduce zoom level to -3 (I can see it bottom right, not sure what it's called exactly)
- Start toggling indent lines with `SPC-t-i` and observe extra spacing.

### System Information

https://pastebin.com/Y5QnHZgg

**Comment by vikdotdev** [comment]
The only similar issue I've found is this one https://github.com/doomemacs/doomemacs/issues/5882

**Comment by juliusdelta** [comment]
I am experiencing the exact same issue on MacOS 14.3 (Sonoma):
```
GNU Emacs     v29.2            nil
Doom core     v3.0.0-pre       HEAD -> master 9620bb45a 2024-04-18 14:20:48 -0400
Doom modules  v24.04.0-pre     HEAD -> master 9620bb45a 2024-04-18 14:20:48 -0400
```

I'm upgrading now, but I don't see any adjustments to relevant code in the diff. Am more than happy to report back more info if desired.

**Comment by hlissner** [comment]
This should be fixed (or at least made obsolete) by https://github.com/doomemacs/doomemacs/commit/0d9e188b26ca1d01a57598e37171e5333272cad7, so I'll consider this resolved. Thanks for bringing it to my attention, in any case!
