### ISSUE TITLE
Git push via magit suddenly asking for a password on an ssh key loaded into ssh-agent

### ISSUE THREAD

**Issue by ahuston-0** [doomemacs/doomemacs#7883]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I do a git push from magit, and my ssh keys are loaded into ssh-agent, I should not get a password prompt (for the password on my ssh key). If I do get a password prompt, I can abort the push, run `ssh-add -t 24h <path>`, rerun the git push from magit, and not get a password prompt.

### Current behavior

When i do a git push from magit, I am getting a password prompt for my ssh-key, even though I can run `git push` from the vterm and it does not prompt for a password. Even after running my `ssh-add`, the password prompt is still occuring

### Steps to reproduce

1. enable ssh-agent via `programs.ssh-agent.enable = true` in my nix config
2. add ssh-keys to agent with `ssh-add -t 24h <path>`
3. commit and push a change via magit
4. get a password prompt
5. get push command from doom echo area (SPC h e)
6. [try to run the same command and don't get asked for a password](https://gist.github.com/ahuston-0/b649312f102baa8ae174881f46674085)

### System Information

https://gist.github.com/ahuston-0/b649312f102baa8ae174881f46674085

**Comment by oreodave** [comment]
I had an issue where ssh-agent's socket wasn't set in the environment when booting Emacs but was fine in my terminal.
What's the output for `(getenv "SSH_AUTH_SOCK")`? If it's empty then you have the same issue as mine.

**Comment by hlissner** [comment]
This is an environmental issue, and the two common reasons you may run into this are:

1. You launch Emacs in an environment where `SSH_AUTH_SOCK` isn't set. Executing `(getenv "SSH_AUTH_SOCK")` within Emacs (as oreodave suggested) will tell you its value. If it's `nil`, then the environment is to blame (i.e. if you launch Emacs with an app launcher, like rofi, or a key shortcut daemon like sxhkd, they may launch it in a different shell than the one you normally use, and therefore won't have any envvars you've set in your shell dotfiles).
2. Your envvar file has a `SSH_AUTH_SOCK` entry (which it shouldn't). Your `doom/info` indicates that you have an envvar file (it lives in `$EMACSDIR/.local/env`). Check it for a `SSH_AUTH_SOCK` entry. `SSH_AUTH_SOCK` *is* [in the blacklist](https://github.com/doomemacs/doomemacs/blob/cc7a509e10785dba94f899a0d428d01e6b8bb078/lisp/cli/env.el#L33), but it's possible to overwrite this.

As this is not a Doom issue, I will close this, but feel free to follow up here.
