### ISSUE TITLE
Can't open mu4e

### ISSUE THREAD

**Issue by raingloom** [doomemacs/doomemacs#7885]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`mu4e` should at least open.

### Current behavior

Trying to use `SPC-o-m` or `M-x mu4e` results in this message:

```
execute-extended-command: Cannot open load file: No such file or directory, mu4e
```

Trying `(require 'mu4e)`:

```elisp
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "mu4e")
  require(mu4e)
  eval-expression((require 'mu4e) nil nil 127)
  funcall-interactively(eval-expression (require 'mu4e) nil nil 127)
  command-execute(eval-expression)
```

### Steps to reproduce

`apt install mu4e`, enable `:email mu4e`, sync, try to open it.

### System Information

https://pastebin.com/s7HtjEx9

**Comment by raingloom** [comment]
Also reproduced it on NixOS stable.

**Comment by Jdogzz** [comment]
I run NixOS unstable, I did a flake update after I saw this issue posted, and mu4e is still opening as expected. In home-manager I have installed emacs, mu, and mu4e from nixpkgs unstable.

Can you run `doom sync --rebuild` on both systems and then share the output of `doom doctor` for both systems here?

**Comment by raingloom** [comment]
It works on NixOS unstable.

**Comment by 45mg** [comment]
Since mu4e itself is not installed by Straight (it's usually part of a package called 'mu'), you can sometimes have issues with it not being in your `load-path`. Try finding out where your package manager installs the lisp files of the 'mu' package, and adding that to `load-path` if it isn't there.

**Comment by EsAu79p** [comment]
The troubleshooting from the module documentation might work. Running
```zsh
find / -type d -iname '*mu4e*' 2> /dev/null
```
To find to find the install directory of mu4e and then adding 
```emacs-lisp
(add-to-list 'load-path "your/path/to/mu4e")
```
to `.config/doom/config.el`.

- [module documentation](https://github.com/doomemacs/doomemacs/tree/master/modules/email/mu4e)

**Comment by hlissner** [comment]
Adding mu4e to your `load-path` should no longer be necessary after 2bc6dd2a96fca93202404726a2c24c67418fcf8b, so long as you remember to run `doom sync` after installing [mu](https://github.com/hlissner/dotfiles/blob/55194e703d1fe82e7e0ffd06e460f1897b6fc404/modules/editors/emacs.nix#L59) and [mu4e](https://github.com/hlissner/dotfiles/blob/55194e703d1fe82e7e0ffd06e460f1897b6fc404/modules/editors/emacs.nix#L16) via nixpkgs:

```nix
environment.systemPackages = with pkgs; [
    mu
    # For nixpkgs versions after 23.05: this installs Emacs with mu4e already
    # included (you still need mu above; it just doesn't ship with mu4e anymore)
    ((emacsPackagesFor emacs).emacsWithPackages (epkgs: [ epkgs.mu4e ]))
    # And one of the following
    isync
    offlineimap
];
```

I'll close this since this is mostly a `load-path` issue, but feel free to follow up here. Thanks for bringing it to my attention, in any case.

**Comment by raingloom** [comment]
That NixOS config no longer works.  It did a few weeks ago, no idea what happened.
