### ISSUE TITLE
Five hours to install doom, then black sreen in emacs

### ISSUE THREAD

**Issue by bobf32** [doomemacs/doomemacs#7891]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Doom install should proceed in a timely fashion, taking making several minutes to complete. Never timed it before but sounds about right. Running emacs then starts with the doom config

### Current behavior

Doom install taking over five hours.

```✓ Finished in 5h 18m 50s```

When app starts, I just get a black screen.

I have not used doom for a while, and attempted a clean install today. I have noticed too that certain git operations are performing poorly, not sure if related. Core network downlaod speed is a respectable 250Mbits/s

### Steps to reproduce

Per the install steps:
1. git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
2. ~/.config/emacs/bin/doom install
3. emacs --with-profile doom

### System Information

https://pastebin.com/0ywg2Pxu

**Comment by bobf32** [comment]
Fair enough @hlissner. I too suspect the issue is not with doom. Was just hoping for someone to say "oh yes, I had that".

**Comment by bobf32** [comment]
OK got a bit further, now getting this:

```
$ ~/.config/emacs/bin/doom sync
- Using Emacs 28.2 @ /usr/local/bin/emacs
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    x The package manager threw an error..
    x Last 16 lines of straight's error log:
      $ cd /home/xxxxxxxx/.config/emacs/.local/straight/repos/straight.el/
      $ git rev-parse HEAD
      88e574ae75344e39b436f863ef0344135c7b6517
      [Return code: 0]
      $ cd /home/xxxxxxxx/.config/emacs/.local/straight/repos/use-package/
      $ git rev-parse HEAD
      a6e856418d2ebd053b34e0ab2fda328abeba731c
      [Return code: 0]
      $ cd /home/xxxxxxxx/.config/emacs/.local/straight/repos/auto-minor-mode/
      $ git rev-parse HEAD
      HEAD
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      [Return code: 128]
    ! Wrote extended straight log to ~/.config/emacs/.local/state/logs/cli.doom.240624152729.86589.error
    ! Script was abruptly aborted, leaving Doom in an incomplete state!
    - Run 'doom sync' to repair it.
```

**Comment by hlissner** [comment]
It seems to have failed while cloning the `auto-minor-mode` package. The simple fix: delete `~/.emacs.d/.local/straight/repos/auto-minor-mode/` and re-run `doom sync`. That said, this (along with the original problem) might suggest network connection issues (that is, unless you ran `doom sync` while Github was down).

**Comment by bobf32** [comment]
@hlissner Tried that, it made no difference. I think I will close this as I have successfully run the install in two other environments, there's just something a bit rubbish about the one env I'm trying to run it in.
