### ISSUE TITLE
`No language registered for major mode 'fundamental-mode'` error at startup

### ISSUE THREAD

**Issue by mayersj1** [doomemacs/doomemacs#7895]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

No error as this would be handled by doom emacs.

### Current behavior

I have tree-sitter enabled in my init.el as well as (global-tree-sitter-mode) being called in my config.el.  This all worked properly until this morning when I did a 'doom upgrade'.  Now the error/warning in the subject line occurs.  Is there something new that needs to be set? An exclusion perhaps?

### Steps to reproduce

1. Enable tree-sitter in init.el
2. add (global-tree-sitter-mode) into your config.el
3. doom sync
4. Start emacs
5. Error appears in the *Warnings* buffer

### System Information

https://gist.github.com/mayersj1/820df8a9327b2d447fea09787c62eb67

**Comment by hlissner** [comment]
`global-tree-sitter-mode` activates `tree-sitter-mode` in all buffers, indiscriminately, even fundamental-mode, which tree-sitter doesn't have an associated module for, hence the warning. That's one reason why Doom activates them manually (examples: [1](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/ess/config.el#L28), [2](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/zig/config.el#L20), [3](https://github.com/doomemacs/doomemacs/blob/master/modules/lang/go/config.el#L19)). You can get around by simply avoiding `global-tree-sitter-mode` and add them selectively to the hooks you want instead.

It's certainly not ideal/intuitive behavior though, but it's something that can't be addressed in Doom, and should be reported [upstream](https://github.com/emacs-tree-sitter/elisp-tree-sitter). Thanks for bringing it to my attention, in any case.

**Comment by mayersj1** [comment]
Any clue as to why this warning just started happening?  My usage of globa-tree-sitter-mode predates today's doom update

**Comment by offbyone** [comment]
Same thing, here; this is new to me. ts-fold-mode seems to trigger it.

**Comment by offbyone** [comment]
For anyone who finds their way here, you can get around this and keep tree-sitter by disabling `fold` in `init.el` or vice versa.

I can't find any way to keep both of them in place, though.

**Comment by hlissner** [comment]
In that case, this has to do with how the `:editor fold` module activates ts-fold. See if making this change to the module fixes it for either of you (at the bottom of modules/editor/fold/config.el):

```diff
                                                 :weight light))
   (setq ts-fold-replacement "  [...]  ")
-  (ts-fold-mode +1))
+  (global-ts-fold-mode +1))
```

**Comment by offbyone** [comment]
Yuuuup, that's a viable fix alright!

**Comment by hlissner** [comment]
As of 7ce9a99 this should be resolved. Thanks for your help!
