### ISSUE TITLE
How do I make doom sync always choose the default option when there is a conflict in some package’s git repo?

### ISSUE THREAD

**Issue by NightMachinery** [doomemacs/doomemacs#7906]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

How do I make doom sync always choose the default option when there is a conflict in some package’s git repo?

E.g.,

In repository "dart-mode", remote "origin" has URL
      "https://github.com/bradyt/dart-mode.git"
    but recipe specifies a URL of
      "https://github.com/emacsorphanage/dart-mode.git"

         1) Abort
         2) Rename remote "origin" to "origin-1", re-create "origin" with correct URL, and fetch
         3) Rename remote "origin" manually, re-create it with correct URL, and fetch
         4) Delete remote "origin", re-create it with correct URL, and fetch (Choose this if unsure)
         5) Delete remote "origin", re-create it with manually set URL, and fetch

      How to proceed? (1, 2, 3, 4, 5; don't know? Pick 4) 4
      Really delete remote "origin"? (y or n) y

Using --force will get rid of the first prompt (though it's not clear if it is actually choosing the default option or doing sth else), but not the "really delete" prompt.

I have asked about this on Discourse and Discord, with no answers. It is making doom very difficult to use for me, as I need it installed on multiple remote servers, and I can't just sit behind the screen for an hour answering these prompts every time I run `doom sync`.

### Current behavior

_

### Steps to reproduce

_

### System Information

_

**Comment by hlissner** [comment]
See if throwing this into your config makes `-!`/`--force` suppress the second prompt as well:

```elisp
;;; add to $DOOMDIR/init.el
(defadvice! doom-cli--straight-suppress-confirm-a (&rest _)
  :before-until #'straight-are-you-sure
  (and (bound-and-true-p doom-cli--context)
       (doom-cli-context-suppress-prompts-p context)))
```

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by NightMachinery** [comment]
@hlissner `doom sync --force` hanged for me. When I ran it without `--force`, I got this prompt:
```
  > Updating pinned packages...                                                      
    > In repository "elisp-tree-sitter", HEAD on "release" is behind default branch "
master"                                                                              
                                                                                     
         1) Abort                                                                    
         2) Checkout "master"                                                        
         3) Magit log "release..master" and open recursive edit                      
                                                                                     
      How to proceed? (1, 2, 3)
```
I think this prompt has no default answer which makes `--force` hang.

**Comment by hlissner** [comment]
As of b163c21, `Checkout "master"` should be treated as the recommended/default answer for `--force` to use. Let me know if that isn't the case and I'll reopen this.
