### ISSUE TITLE
issues with badges in README.md

### ISSUE THREAD

**Issue by edgimar** [doomemacs/doomemacs#7910]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Current behavior

The repository's README.md file appears to be using some deprecated way of specifying badges.  For example, they currently show that the last commit was in May, and there is a URL in place of the 'build' badge value (which points to the issue [here](https://github.com/badges/shields/issues/8671)).

**Comment by hlissner** [comment]
I saw that the `last commit` badge was stuck, but the URL was correct. I tweaked it to omit the branch and it corrected itself. Might be browser or github-level caching? Not sure.

In any case, this should be fixed as of c4ee986. I've also commented out the build badge until the new CI/CD is up. Thanks for bringing it to my attention!
