### ISSUE TITLE
Bug: 'Wrong number of arguments' error after being asked what to do about a repo ( 'doom sync' )

### ISSUE THREAD

**Issue by yaaama** [doomemacs/doomemacs#7917]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I modified `dirvish.el` located in 
`~/.config/emacs/.local/straight/build-30.0.50/dirvish/`

I ran `doom sync` and when it asked me what I should do about the `dirvish` repo I selected option 1 which was `abort`.

I expected it to then ignore it and gracefully quit.

Maybe useful info:
`doom sync -U` works to ignore the packages

I understand that I am running an unstable Emacs version but I wanted to report this anyways, it might just be an Emacs problem or something.

### Current behavior

After running `doom sync` it asked for what it should do with the repo since it was modified, using option 1 (abort) will cause a stack trace and a crash with the CLI.

Dir where the file edited was: `~/.config/emacs/.local/straight/build-30.0.50/dirvish/`

Stack trace:

```
      How to proceed? (1, 2, 3, 4; don't know? Pick 2) 1

      ! Aborted
      x There was an unexpected runtime error
        Message: Wrong number of arguments
        Details: (#[(args context) ((let ... ...)) (cl-struct-doom-cli-context-tags cl-struct-doom-cli-option-tags cl-struct-doom-cli-tags t) nil "Accepts one of the
ng:\n\n  (CONTEXT [ARGS...])\n    TODO\n  (STRING [ARGS...])\n    TODO\n  (:restart [ARGS...])\n    TODO\n  (:pager [FILE...])\n    TODO\n  (:pager? [FILE...])\n
(INT)\n    TODO"] 1)
        Backtrace:
          (doom-cli--exit 1)
          (#[nil ((let ((doom-output-indent 0)) (terpri) (doom-print (doom-print--format (doom-print--class 'warn "Aborted")))) (doom-cli--exit 1)) (t)])
          (funcall #[nil ((let ((doom-output-indent 0)) (terpri) (doom-print (doom-print--format (doom-print--class 'warn "Aborted")))) (doom-cli--exit 1)) (t)])
          (let* ((options (cons #'(lambda nil (let ((doom-output-indent 0)) (terpri) (doom-print (doom-print--format (doom-print--class 'warn "Aborted")))) (doom-cli
          (let (recommended options) (progn (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-indent-increment) 0) do
          (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-indent-increment) 0) doom-print-indent))) (terpri) (let (
          (progn (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-indent-increment) 0) doom-print-indent))) (terpri)
          (if (let* ((cl-x doom-cli--context)) (progn (or (let* ((cl-x cl-x)) (progn (and (memq (type-of cl-x) cl-struct-doom-cli-context-tags) t))) (signal 'wrong-t
          (let ((doom-cli--straight-auto-options doom-cli--straight-auto-options)) (setq actions (delq (funcall 'assoc "C-g" actions) actions)) (setq actions (delq (
          (if (and (boundp 'async-in-child-emacs) async-in-child-emacs) (error "Straight prompt: %s" prompt) (let ((doom-cli--straight-auto-options doom-cli--straigh
          (doom-cli--straight-fallback-to-tty-prompt-a #[(prompt actions) ((if noninteractive (progn (error (format "Cannot display prompt in batch mode: %s" prompt)
          (apply doom-cli--straight-fallback-to-tty-prompt-a #[(prompt actions) ((if noninteractive (progn (error (format "Cannot display prompt in batch mode: %s" p
GNU Emacs     v30.0.50         94be2b2682bc16b15755dca63ef8406018c9f3e9
Doom core     v3.0.0-pre       HEAD -> master 7bb5df4c 2024-07-05 20:10:58 -0400
Doom modules  v24.08.0-pre     HEAD -> master 7bb5df4c 2024-07-05 20:10:58 -0400
        ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240706231702.876834.error
      ! Script was abruptly aborted, leaving Doom in an incomplete state!
      - Run 'doom sync' to repair it.
      ✓ Finished in 12.18084s
❯ doom sync
```

### Steps to reproduce

1. Edit dirvish.el 
2. Run doom sync
3. Answer 1 when asked what to do by the CLI
4. 

### System Information

https://pastebin.com/U6Fk4mP6

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
