### ISSUE TITLE
[Question] How to completely clean up doom package cache?

### ISSUE THREAD

**Issue by jman-schief** [doomemacs/doomemacs#7918]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

In commit 63c470bff32875098fa5a7f205e0b5eb08247686

> BREAKING CHANGE: This removes the 'doom compile' and 'doom clean'
> commands, and offers no immediate replacement for them (and no plan to
> include one). In the future, byte-compilation of Doom's internals will
> be baked into 'doom sync', but until then, Doom is not optimized to take
> advantage of byte-compilation, and forcing it provides no benefit.

So what's now the suggested strategy to remove all package and personal config *.elc files?
Maybe running `find $EMACSDIR/.local/straight/build-xx.yy.zz/ -name '*.elc' -delete`?

Note: Also asked a similar question a while ago in the community forum ([link](https://discourse.doomemacs.org/t/explain-or-document-a-panic-button-if-something-breaks-badly/4363)) but it's hard to get answers from the community there.

### Current behavior

Apparently Doom does not allow compiling nor cleaning cache anymore.

### Steps to reproduce

N/A

### System Information

https://paste.sr.ht/~jman/a50ff018cb6217373b300fc1a0975b862f8ad04f

**Comment by stefco** [comment]
Is there a non-expired link to the discord? I can't use the one that's been posted here and elsewhere
