### ISSUE TITLE
UI Performance Regression with vc-gutter with +pretty 

### ISSUE THREAD

**Issue by rymndhng** [doomemacs/doomemacs#7923]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect scrolling to be snappy when I'm scrolling and typing with (vc-gutter +pretty).

Something changed in the last two weeks that have impacted performance on my Emacs. I *think* this might have been introduced in https://github.com/doomemacs/doomemacs/commit/b405225b90949852eae8fb9b35b7377b3a38a44d. 

### Current behavior

In init.el, with (vc-gutter +pretty) and there are a lot of changes in the gutter, the buffer starts to jank and run slowly.

Without +pretty and a lot of changes in the gutter, the UI is smooth and responsive.

### Steps to reproduce

1. Open Emacs
2. Set `(vc-gutter +pretty)`
3. Open up a file with a lot of changes.
4. Try scrolling up/down with `next-line` and `prev-line`

### System Information

https://pastebin.com/ryxqwjnN

**Comment by hlissner** [comment]
Does disabling `diff-hl-flydiff-mode` help?

```elisp
;;; add to $DOOMDIR/config.el
(remove-hook 'diff-hl-mode-hook #'diff-hl-flydiff-mode)
```

This mode is responsible for updating the gutter when you're idle for ~0.5s, which seems to be much slower in Emacs <= 29 (I can't reproduce any slowness in 30.0.50 or 31.0.50).

**Comment by hlissner** [comment]
If turning off `diff-hl-flydiff-mode` *does* help, could you turn it back on and experiment with the `diff-hl-flydiff-delay` variable? Doom defaults it to `0.5` (`diff-hl` defaults it to `0.3`), both of which are evidently too low for <=29. I'd appreciate if you could try `1.0` or `2.0` and see if that helps at all, e.g.

```elisp
;;; add to $DOOMDIR/config.el
(after! diff-hl
  (setq diff-hl-flydiff-delay 2.0))
```

**Comment by hlissner** [comment]
Another thing to try:

```elisp
(after! diff-hl
  (setq diff-hl-update-async t))
```

**Comment by rymndhng** [comment]
@hlissner I've tried all of the above, and neither improve performance. For what it's worth, it doesn't appear to be related to updates because I'm experiencing this slowness when I'm scrolling the buffer (rather than making edits to the file). 

I noticed that if I comment out this line, then the perf issues goes away: https://github.com/doomemacs/doomemacs/blob/21a252d994d3c349fc884dc8f34d66cb14697942/modules/ui/vc-gutter/config.el#L18-L21

From a bit of googling, I suspect I'm experiencing the issue described in this post: https://www.reddit.com/r/emacs/comments/1do1wgj/fringes_incredibly_slow_on_emacs_ns_with_macos/

**Comment by hlissner** [comment]
@rymndhng Thanks for looking into this; that's an interesting find. If the default bitmaps don't trigger the slowness, there must be something to Doom's new bitmaps that the NS build of Emacs doesn't agree with. See if this fixes your issue (make sure you're not commenting anything out in the :ui vc-gutter module while testing this):

```elisp
;;; add to $DOOMDIR/config.el

;; Remove then redefine the existing advice:
(advice-remove #'diff-hl-define-bitmaps #'+vc-gutter-define-thin-bitmaps-a)
(defadvice! +vc-gutter-define-thin-bitmaps-a (&rest _)
  :after #'diff-hl-define-bitmaps
  (let* ((scale (if (and (boundp 'text-scale-mode-amount)
                         (numberp text-scale-mode-amount))
                    (expt text-scale-mode-step text-scale-mode-amount)
                  1))
         (spacing (or (and (display-graphic-p) (default-value 'line-spacing)) 0))
         (h (+ (ceiling (* (frame-char-height) scale))
               (if (floatp spacing)
                   (truncate (* (frame-char-height) spacing))
                 spacing)))
         (w (min (frame-parameter nil (intern (format "%s-fringe" diff-hl-side)))
                 16))
         (_ (if (zerop w) (setq w 16))))
    (define-fringe-bitmap 'diff-hl-bmp-middle
      (make-vector
       h (string-to-number (concat (make-string (/ w 2) ?1)
                                   (make-string (- w (/ w 2)) ?0))
                           2))
      nil nil 'center)))
```

If this doesn't fix it, then I suspect NS is struggling to draw the transparent pixels, in which case, make this change to the advice above and see if it helps:

```diff
     (define-fringe-bitmap 'diff-hl-bmp-middle
       (make-vector
-       h (string-to-number (concat (make-string (/ w 2) ?1)
-                                   (make-string (- w (/ w 2)) ?0))
-                           2))
+       h w
        nil nil 'center)))
```

If even that doesn't help, try removing the background removal hook:

```elisp
;;; anywhere in $DOOMDIR/config.el
(remove-hook 'diff-hl-mode-hook #'+vc-gutter-fix-diff-hl-faces-h)
```

**Comment by rymndhng** [comment]
The first patch significantly significantly improves rendering perf, thanks!
