### ISSUE TITLE
Please consider opening to the public the discussions section on GitHub 

### ISSUE THREAD

**Issue by maikol-solis** [doomemacs/doomemacs#7927]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Hi Henrik,

I apologize for posting here (this is not a real bug), but I think this is the best place to share this.

I've been participating on Discord and have reported issues there, but I find it difficult to search for things. The main problem is when a user has some issue in #doom-help, it is resolved and then is buried to be forgotten. Other users, external to discord, could face the same issue and never be aware of the solution. 

Given that all the Doom development is on GitHub, would it be possible to encourage people to post their questions in the GitHub Discussions (https://github.com/orgs/doomemacs/discussions)? 

The ideal situation is to eventually replace #development, #doom-help and #emacs-help with the bug tracker + GH discussion. 

Discord could still be used as a social room for non-issue-related topics.

Using this, you could move a discussion to an issue (or vice versa), which might make your workflow easier while working through your backlog. Additionally, it would allow every part of the doom development could be indexed by Google, making it easier to search and collaborate on.

I know you prefer using discord, but I wanted to raise an issue that is important to me and possibly to others as well. 

Best. 

### Current behavior

None

### Steps to reproduce

None

### System Information

None

**Comment by hlissner** [comment]
I'm not sure if you're on Discord to have heard me say it, but I've been planning exactly this for the past month or so, I've just been too busy to announce it on Discourse, begin transferring some of the resources/FAQ here, and finalize the categories on our GH discussions board.

That said, it is coming, which is why https://github.com/orgs/doomemacs/discussions even exists at all. I'll post an announcement on Discourse (and then on our GH Discussions) once it happens.
