### ISSUE TITLE
`org-modern` package requires `compat-30` on Emacs 29.x

### ISSUE THREAD

**Issue by mayersj1** [doomemacs/doomemacs#7939]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I am pulling in the org-modern package.  The latest version requires compat-30 to pull in the static-if that has been introduced in Emacs 30.*.  Without it, there are errors when attempting to bring up the Org Agenda.

Running doom sync after manually updating to the latest compat package is resetting the repo back to an earlier version that doesn't contain compat-30.

### Current behavior

org-modern--update-label-face: Invalid function: static-if
Quit
Press key for agenda command:
redisplay--pre-redisplay-functions: (invalid-function static-if) [4 times]
File mode specification error: (invalid-function static-if) [101 times]
redisplay--pre-redisplay-functions: (invalid-function static-if) [15 times]
org-agenda-change-time-span: Viewing span is already "10"
redisplay--pre-redisplay-functions: (invalid-function static-if) [7 times]
Buffer is read-only: #<buffer *Org Agenda*>
redisplay--pre-redisplay-functions: (invalid-function static-if) [8 times]

### Steps to reproduce

1. use org-modern
2. doom sync
3. invoke org agenda
4. error will occur

### System Information

https://pastebin.com/zxanVfJV

**Comment by mayersj1** [comment]
Well, not sure how I got this to work, but I basically removed the cache and straight directories under ~/.emacs.d/.local and performed a 'doom sync && doom build' (just found out that 'doom build' is deprecated, but this is how I ran it).  Following this with another 'doom sync' and now the error is gone. Verified steps on two different machines that were experiencing the same error.

Will leave this open if it's something you want to look into.

**Comment by hlissner** [comment]
> after manually updating to the latest compat package

Can you explain how you did this? `doom sync` shouldn't be resetting a package if you've unpinned (or repinned) it.

**Comment by mayersj1** [comment]
I went into ~/.emacs.d/.local/straight/repos/compat and executed 'git pull'.  It wanted me to select an origin so I changed the command to 'git pull origin main'.  This properly pulled the latest main commit for compat.  Upon executing 'doom sync', I could see that compat was being 'rolled back' to a specific commit (verified by doing 'git status' and 'git log' after running 'doom sync'.  Not sure what else I can offer there.  I don't believe I've forgotten anything...

**Comment by hlissner** [comment]
Alright, then `doom sync` is behaving as intended. In the future, I recommend re or unpinning packages if you want to update them, like so:

```elisp
;;; in $DOOMDIR/packages.el

;; Repins the package to a new commit. Run `doom sync` to update 
;; pinned packages.
(package! compat :pin "09dce8a193c5a70277512263782b82fa1cba84c0")

;; or

;; This updates compat to the latest compatible, BUT you have to run `doom sync -u` to update unpinned packages.
(unpin! compat)
```

Anyhow, I will bump `compat`'s pin soon.

**Comment by mayersj1** [comment]
Thanks for the info! I actually wasn't sure how all that worked under the covers.
