### ISSUE TITLE
Incorrect highlighting in cc-mode when use both tree-sitter-hl-mode and modern-cpp-font-lock

### ISSUE THREAD

**Issue by kaiwk** [doomemacs/doomemacs#7941]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Correct highlighting

### Current behavior

When i enable both  tree-sitter-hl-mode and modern-cpp-font-lock, i'll get highlighting below:

![image](https://github.com/user-attachments/assets/0e5e1314-148d-4088-b88b-c41f2e790c81)

And turn off any one of them, it will highlight correctly.

### Steps to reproduce

1. Open Emacs
2. Open any C++ file, enable tree-sitter-hl-mode and modern-cpp-font-lock
3. define a function, and write `new_abc` or any `<keyword>_<any-characters>`
4. you will get incorrect highlighting

### System Information

https://pastebin.com/9rSQEwgt

**Comment by kaiwk** [comment]
I can fix this by:
``` elisp
(use-package modern-cpp-font-lock
  :config
  ;; Avoid conflict with tree-sitter highlighting
  (setq modern-c++-keywords nil))
```
or just completely disable modern-cpp-font-lock

**Comment by hlissner** [comment]
As of b0e1e68, `modern-cpp-font-lock` will be disabled if `+tree-sitter` is enabled for the `:lang cc` module. Let me know if that gives you any trouble. Thanks for bringing it to my attention!
