### ISSUE TITLE
vc-gutter not working on Windows.

### ISSUE THREAD

**Issue by JordanAnthonyKing** [doomemacs/doomemacs#7950]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When the vc-gutter module is enabled, in a version controlled folder/project, after making and saving changes the margin should show indicators reflecting the kind of change made.

### Current behavior

The vc-gutter module, with or without the +prettier flag does not show anything in the left margin after making and saving changes.

Git is installed on my system. Although no dependencies are listed in the documentation I have tried enabling and disabling the vc and magit modules also to no effect. I've also tested in 29.4 and 30.0.50

### Steps to reproduce

Open emacs on windows.
Open a version controller project.
Make a change to a file.
Save.
Wait a brief moment.
Verify nothing is shown in the margin.

### System Information

https://pastebin.com/5pZQbeyE

**Comment by JordanAnthonyKing** [comment]
1. git version 2.45.2.windows.1
2. No difference
3. Nope
4. Yes, c:/Program Files/Git/cmd/git.exe
5. Yep

**Comment by hlissner** [comment]
Try executing `M-x eval-expression RET (diff-hl-changes)` in a version-controlled file buffer with unstaged changes. Does it return anything?

**Comment by JordanAnthonyKing** [comment]
Yes, this does return nil

**Comment by upbqdn** [comment]
Mine didn't work either a week ago on Linux. I reinstalled Doom from scratch, and it started working smoothly.

**Comment by JordanAnthonyKing** [comment]
1. (SVN Git Hg)
2. Okay:
- Git
- edited
- nil
- nil

**Comment by JordanAnthonyKing** [comment]
Okay, it turned out at first that diff wasn't actually on the path. I'm using the version included with git.

Now in the diff-hl buffer I see this:
```
diff -U 0 --strip-trailing-cr "--label" "c:/Users/jking/AppData/Local/Temp/#3f0118b88bb0e27324deabfae60ee7b2e77d44ea#.~:7301fab6f1526d59cccf45f8767e39b0def4f925~" "--label" "#<buffer data-provider-popup.component.html>" "c:/Users/jking/AppData/Local/Temp/#3f0118b88bb0e27324deabfae60ee7b2e77d44ea#.~:7301fab6f1526d59cccf45f8767e39b0def4f925~" "c:/Users/jking/AppData/Local/Temp/buffer-content-1dbPYX"
diff: c:/Users/jking/AppData/Local/Temp/#3f0118b88bb0e27324deabfae60ee7b2e77d44ea#.~:7301fab6f1526d59cccf45f8767e39b0def4f925~: No such file or directory
```

**Comment by hlissner** [comment]
My first thought is it's struggling with the odd characters in those paths, but I'm curious why I can't reproduce it. Are you able to rpoduce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85) from the error? A stack trace would help narrow down whether this is a Windows thing, a bug in `diff.el`, `vc.el`, or `diff-hl`.

**Comment by JordanAnthonyKing** [comment]
Opening emacs, enabling debug, toggling debug on error, and then navigating to or making changes in a version controlled file doesn't generate a backtrace, even though the error is still printed to the buffer.
