### ISSUE TITLE
After executing +format/region, Emacs remains in the selected state

### ISSUE THREAD

**Issue by sails** [doomemacs/doomemacs#7951]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior
should not remain in the selected state.

### Current behavior

when executing +format/region in a cpp file and then moving the cursor up or down, Emacs remains in the selected state

### Steps to reproduce
#include <stdio.h>
 
int main(int argc, char *argv[]) {
  int x = 0;
    int y = 0;
  return 0;
}

selecting the content from line 4 to line 6, then executing +format/region

### System Information
https://pastebin.com/eRfBMsY5

**Comment by hlissner** [comment]
I can't reproduce this. Check \*Messages\* for errors after formatting a region. `C-h e` will open the \*Messages\* buffer.

**Comment by hlissner** [comment]
As of 13ed89f, the selection will be disengaged after partial reformatting. Thanks for bringing it to my attention!

**Comment by sincebyte** [comment]
It's hard to describe the issue, but there must have someting wrong.In lsp-java use lsp-format-region ,there will have some error from lsp-java in minibuffer,And when exit emacs minibuffer will show me the alert below, but I can't find the buffer which named *apheleia-formatted*.And If I press y There only remain the code which I regioned to formatting fragment. 
```
Save file /utils/redis/RedisKeySerializer.java (buffer  *apheleia-formatted*)? (y, n, !, ., q, C-r, C-f, d or C-h)
```
