### ISSUE TITLE
eglot-jl does not work out of the box

### ISSUE THREAD

**Issue by gdkrmr** [doomemacs/doomemacs#7953]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

eglot-jl should install the julia language server automatically

### Current behavior

eglot-jl language server dies because it fails to install LanguageServer.jl

### Steps to reproduce

Start with a fresh doom install and activate `(julia +lsp)` and use `(lsp +eglot)`

this can be resolved by setting

```
(after! eglot-jl
  (setq eglot-jl-language-server-project "/home/gkraemer/.config/emacs/.local/straight/build-29.4/eglot-jl/"))
```

in `config.el`, manually to the original value provided by `eglot-jl`. So I guess we just have to remove setting the variable to fix the issue. 

https://github.com/doomemacs/doomemacs/blob/13ed89f2354026b9c176f5c6861704aeda07723b/modules/lang/julia/config.el#L95-L98

There is a comment in the code and the original PR suggests that the current state was a deliberate choice, so I am not sure if a "fix" is wanted. https://github.com/doomemacs/doomemacs/commit/ba0f791b05f284ad308e2ba898a54eb1fc8f0149

 I am new to `doom` and haven't figured out yet how to contribute yet. If fix is wanted, I'll be happy to provide a PR once I figure out how to contribute.

### System Information

https://pastebin.com/qjY1r6Jd

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
