### ISSUE TITLE
`describe-function` reports `init.29.el` as the source location for many interactive functions

### ISSUE THREAD

**Issue by offbyone** [doomemacs/doomemacs#7958]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [x] The issue can be reproduced on the **latest** available commit of Doom.
- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I use `describe-function` or `describe-key`, the help buffer that pops up should report to me the location of the defined function.

### Current behavior

When I do it now, however, the help buffer shows `init.29.el` as the location instead. I'll use an example of `projectile-find-file` here; I've just invoked `describe-function` and given it `projectile-find-file`:

```
projectile-find-file is an autoloaded, interactive and natively
compiled function defined in init.29.el.
```

### Steps to reproduce

1. Open emacs
2. C-h f
3. projectile-find-file
4. observe the issue

### System Information

https://gist.github.com/offbyone/122c074c73c393cf39e8d18d81f9012f

**Comment by hlissner** [comment]
Reposting what I said on Discord for posterity:

> I'm aware of this, but it's a little difficult to reproduce across Emacs versions (as the autoloads generator library has changed quite drastically between 29-30), or find a robust solution for. `helpful` does do some autoload checks (autoloading the symbol to pull in the docs), but it doesn't seem to work reliably in this case.
>
> I'll look into advising `helpful` to treat symbols originating from Doom's autoloads file as undefined (or maybe try and autoload it, if possible).

**Comment by hlissner** [comment]
As of 7197ee6 this should finally be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by offbyone** [comment]
This has solved it for all the cases I've tried so far. Thanks for it!
