### ISSUE TITLE
When executing +format/region, the selected distinction content is cleared.

### ISSUE THREAD

**Issue by sails** [doomemacs/doomemacs#7962]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

the formatted content replaces the content in the selected area.

### Current behavior

When executing +format/region, the selected distinction content is cleared.

### Steps to reproduce

1：Select and execute +format/region:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/e62775f6-ae0a-4975-ad40-f036af3aa705">

2: After execute +format/region, the selected distinction content is cleared.:
<img width="378" alt="image" src="https://github.com/user-attachments/assets/b6c48d32-00f3-40dd-8f04-191dfc422e8c">

3: When restoring the content and saving, an error occurs upon executing the +format/region command again.
<img width="579" alt="image" src="https://github.com/user-attachments/assets/d3238199-7fd3-4c70-93ca-efd2768240b0">

4: When closing emacs, a prompt appears to save the temporary buffer to a file.
<img width="389" alt="image" src="https://github.com/user-attachments/assets/e8c45d57-bb35-4777-8e15-1fb8bc922431">

### System Information

https://pastebin.com/iduHYPxT

**Comment by hlissner** [comment]
Are there any errors/warnings in `*Messages*` after `+format/region` clears the selection?

**Comment by sails** [comment]
> Are there any errors/warnings in `*Messages*` after `+format/region` clears the selection?

There are no error messages displayed in *Messages*.
but when add some code in  like 
```
               (condition-case err
                   (progn
                     (delete-region start end)
                     )
                 (error
                  (message "An error occurred: %s" (error-message-string err))
                  nil))
```
will get "An error occurred: Assertion failed: (or track-changes--before-no (<= track-changes--before-beg (track-changes--state-beg track-changes--state) beg end (track-changes--state-end track-changes--state) track-changes--before-end))"

**Comment by hlissner** [comment]
What is the value of `apheleia-formatter` in that c++ buffer? (`C-h v apheleia-formatter` will tell you)

**Comment by sails** [comment]
> apheleia-formatter

<img width="616" alt="image" src="https://github.com/user-attachments/assets/7c963a30-7b35-437e-a995-8787cc8fb4eb">

**Comment by hlissner** [comment]
Hmm, then it's using clang-format. It may be possible that it simply doesn't support partial reformatting, and so spits out no results without an error message (which apheleia can do nothing but interpret as a successful reformatting). `+format/region` is, unfortunately, a hack that won't work with every formatter. 

To get to the bottom of this, enable debug mode with `M-x doom-debug-mode`, then try the `+format/region` again. Then switch to the `*apheleia-debug-log*` buffer and see what it has to say for itself.

Side-note: does `+format/buffer` work without issue, at least?

**Comment by sails** [comment]
> Hmm, then it's using clang-format. It may be possible that it simply doesn't support partial reformatting, and so spits out no results without an error message (which apheleia can do nothing but interpret as a successful reformatting). `+format/region` is, unfortunately, a hack that won't work with every formatter.
> 
> To get to the bottom of this, enable debug mode with `M-x doom-debug-mode`, then try the `+format/region` again. Then switch to the `*apheleia-debug-log*` buffer and see what it has to say for itself.
> 
> Side-note: does `+format/buffer` work without issue, at least?

Backtrace buffer show:
```Debugger entered--Lisp error: (cl-assertion-failed ((or track-changes--before-no (<= track-changes--before-beg (track-changes--state-beg track-changes--state) beg end (track-changes--state-end track-changes--state) track-changes--before-end)) nil))
  cl--assertion-failed((or track-changes--before-no (<= track-changes--before-beg (track-changes--state-beg track-changes--state) beg end (track-changes--state-end track-changes--state) track-changes--before-end)))
  track-changes--after(38 38 37)
  #<subr delete-region>(38 75)
  apply((#<subr delete-region> 38 75))
  goggles--advice(#<subr delete-region> 38 75)
  apply(goggles--advice #<subr delete-region> (38 75))
  delete-region(38 75)
  (save-current-buffer (set-buffer cur-buffer) (delete-region start end) (goto-char start) (save-excursion (insert-buffer-substring-no-properties formatted-buffer) (if callback (progn (funcall callback)))) (kill-buffer formatted-buffer))
  (closure ((indent . 0) (formatted-buffer . #<buffer  *apheleia-formatted*>) (cur-buffer . #<buffer test.cpp>) (callback) (end . 75) (start . 38)) nil (save-current-buffer (set-buffer formatted-buffer) (if (> indent 0) (progn (indent-rigidly (point-min) (point-max) (max 0 (- indent (+format--current-indentation)))))) (set-buffer-modified-p nil)) (save-current-buffer (set-buffer cur-buffer) (delete-region start end) (goto-char start) (save-excursion (insert-buffer-substring-no-properties formatted-buffer) (if callback (progn (funcall callback)))) (kill-buffer formatted-buffer)))()
  #f(compiled-function (err) #<bytecode 0x15ac420b83c46b00>)(nil)
  #f(compiled-function (err patch-buffer) #<bytecode 0x1d02f1f9435a0fb7>)(nil #<buffer  *apheleia-diff-stdout*>)
  #f(compiled-function (proc-exit-status proc-interrupted) #<bytecode 0x231deea8cec4aed>)(1 nil)
  #f(compiled-function (proc event) #<bytecode -0x1ef371abf44675ee>)(#<process apheleia-diff> "exited abnormally with code 1\n")
```

but not find apheleia-debug-log buffer
<img width="411" alt="image" src="https://github.com/user-attachments/assets/7fb9038f-57bd-4ec4-a895-c01276a4060d">


And executing +format/buffer behaves normally

**Comment by hlissner** [comment]
Ah, this actually seems like a bug with `goggles.el`, not the formatter. See if disabling goggles-mode fixes the issue. 

Type `M-x goggles-mode` in that C++ buffer to disable it in that buffer.

**Comment by sails** [comment]
After type M-x goggles-mode in that C++ buffer to disable it in that buffer
```
Debugger entered--Lisp error: (cl-assertion-failed ((or track-changes--before-no (<= track-changes--before-beg (track-changes--state-beg track-changes--state) beg end (track-changes--state-end track-changes--state) track-changes--before-end)) nil))
  cl--assertion-failed((or track-changes--before-no (<= track-changes--before-beg (track-changes--state-beg track-changes--state) beg end (track-changes--state-end track-changes--state) track-changes--before-end)))
  track-changes--after(38 38 39)
  #<subr delete-region>(38 77)
  apply((#<subr delete-region> 38 77))
  goggles--advice(#<subr delete-region> 38 77)
  apply(goggles--advice #<subr delete-region> (38 77))
  delete-region(38 77)
  (save-current-buffer (set-buffer cur-buffer) (delete-region start end) (goto-char start) (save-excursion (insert-buffer-substring-no-properties formatted-buffer) (if callback (progn (funcall callback)))) (kill-buffer formatted-buffer))
  (closure ((indent . 0) (formatted-buffer . #<buffer  *apheleia-formatted*>) (cur-buffer . #<buffer test.cpp>) (callback) (end . 77) (start . 38)) nil (save-current-buffer (set-buffer formatted-buffer) (if (> indent 0) (progn (indent-rigidly (point-min) (point-max) (max 0 (- indent (+format--current-indentation)))))) (set-buffer-modified-p nil)) (save-current-buffer (set-buffer cur-buffer) (delete-region start end) (goto-char start) (save-excursion (insert-buffer-substring-no-properties formatted-buffer) (if callback (progn (funcall callback)))) (kill-buffer formatted-buffer)))()
  #f(compiled-function (err) #<bytecode 0x15ac420b83c46b00>)(nil)
  #f(compiled-function (err patch-buffer) #<bytecode 0x17d88696f90027fd>)(nil #<buffer  *apheleia-diff-stdout*>)
  #f(compiled-function (proc-exit-status proc-interrupted) #<bytecode 0xdd880d405cc4aed>)(1 nil)
  #f(compiled-function (proc event) #<bytecode -0x1ef37d855e8585ee>)(#<process apheleia-diff> "exited abnormally with code 1\n")
```

**Comment by hlissner** [comment]
Ok, it's not goggles, specifically, but it has to do with something else's hook in one of the {after,before}-change-functions variables. Could you see if this fixes it?

```elisp
;;; add to $DOOMDIR/config.el

(defadvice! fixed-+format-region (start end &optional callback)
  :override #'+format-region
  (when-let* ((command (apheleia--get-formatters
                        (if current-prefix-arg
                            'prompt
                          'interactive)))
              (cur-buffer (current-buffer))
              (formatted-buffer (get-buffer-create " *apheleia-formatted*"))
              (indent 0))
    (unwind-protect
        (with-current-buffer formatted-buffer
          (erase-buffer)
          (unless (featurep :system 'windows)
            (setq-local coding-system-for-read 'utf-8)
            (setq-local coding-system-for-write 'utf-8))
          (cl-loop for (var . val)
                   in (cl-remove-if-not #'listp (buffer-local-variables cur-buffer))
                   unless (eq var 'enable-multibyte-characters)
                   do (set (make-local-variable var) val))
          (insert-buffer-substring-no-properties cur-buffer start end)
          (setq indent (+format--current-indentation))
          (when (> indent 0)
            (indent-rigidly (point-min) (point-max) (- indent)))
          (let ((+format--region-p (cons start end)))
            (apheleia-format-buffer
             command
             (lambda ()
               (with-current-buffer formatted-buffer
                 (when (> indent 0)
                   (indent-rigidly (point-min) (point-max)
                                   (max 0 (- indent (+format--current-indentation)))))
                 (set-buffer-modified-p nil))
               (with-current-buffer cur-buffer
                 (replace-region-contents start end (lambda () formatted-buffer) 5)
                 (when callback (funcall callback))
                 (kill-buffer formatted-buffer))))))
      (when (doom-region-active-p)
        (setq deactivate-mark t)))))
```

**Comment by sails** [comment]
Before:
<img width="334" alt="image" src="https://github.com/user-attachments/assets/5a1c0a4f-4584-4aec-a89f-ccd8d8258a0a">

And After execute +format/region:
<img width="286" alt="image" src="https://github.com/user-attachments/assets/36e0d9f6-3c02-4615-912e-1e4fffa3c024">

Then ctrl+x ctrl+s to save file, there are some error:
<img width="749" alt="image" src="https://github.com/user-attachments/assets/b8b35f79-6f09-46c0-85fd-83db5f15d796">

**Comment by hlissner** [comment]
As of a0c901c this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
