### ISSUE TITLE
Doom Install Failure

### ISSUE THREAD

**Issue by Demlar** [doomemacs/doomemacs#7963]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Doom to work properly

### Current behavior

[doomInstall.txt](https://github.com/user-attachments/files/16382827/doomInstall.txt)
https://gist.github.com/Demlar/500953d7c48501971374ef5e031018b9

### Steps to reproduce

./doom install

### System Information

https://gist.github.com/Demlar/2cb22ef4df8af721df5dc3e974125626

**Comment by hlissner** [comment]
You're missing the `as` utility, which Emacs' native-comp feature requires. It's usually bundled with C compilers, but I'm not sure how to get it on Windows. Either install that or install a version of Emacs without native-comp.

In any case, I'll close this because it's not a Doom issue.
