### ISSUE TITLE
The latest commit to persp-mode causes "none" workspace to show up on tabline.

### ISSUE THREAD

**Issue by LemonBreezes** [doomemacs/doomemacs#7968]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I start up Doom Emacs, I expect the only workspace created to be "main".

### Current behavior

When I start up Doom Emacs, instead I have the "none" workspace and "main" workspace. The "none" worskspace is problematic because it cannot be deleted and therefore causes errors when trying to quit Doom Emacs.

### Steps to reproduce

Add `(unpin! persp-mode)` to your `packages.el` and run `doom upgrade`.

### System Information

https://pastebin.com/hY4A2RRT

**Comment by hlissner** [comment]
Looks like there were some breaking refactors upstream. This might be a sign to fast-track [persp-mode's replacement](https://github.com/orgs/doomemacs/projects/5/views/1?filterQuery=-status%3ARejected%2CDone+persp&pane=issue&itemId=52164049).

**Comment by LemonBreezes** [comment]
This has just been fixed upstream. Now I don't have this issue anymore.
