### ISSUE TITLE
mu has been updated to 1.12.6. mu4e package needs to be updated to match mu version.

### ISSUE THREAD

**Issue by mayersj1** [doomemacs/doomemacs#7971]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When launching mu4e with <Spc> o M, expect that mu4e launches. Instead I get an error:

mu4e-error: [mu4e] Found mu version 1.12.6, but mu4e needs version 1.12.5; please set `mu4e-mu-binary' accordingly

### Current behavior

When launching mu4e with <Spc> o M, expect that mu4e launches. Instead I get an error:

mu4e-error: [mu4e] Found mu version 1.12.6, but mu4e needs version 1.12.5; please set `mu4e-mu-binary' accordingly

### Steps to reproduce

1. Open Emacs
2. Launch mu4e
3. Error appears

### System Information

https://gist.github.com/mayersj1/c094148779d3edca91df7ae59471e67d

**Comment by mayersj1** [comment]
This is working now. Not sure if a restart of emacs solved this or not.

**Comment by wchmb** [comment]
It's happening again, how did you fix it?
`mu4e-error: [mu4e] Found mu version 1.12.13, but mu4e needs version 1.12.12; please set 'mu4e-mu-binary' accordingly`

**Comment by wchmb** [comment]
In my case the issue was that I updated [mu](https://github.com/Homebrew/homebrew-core/commits/7bcec77ca1c815571a355b3041d3a22b082e3e0f/Formula/m/mu.rb) (1.12.12 --> 1.12.13) while emacs was running and mu4e didn't notice the change. As @mayersj1 pointed out, a restart of emacs clears the error as the new mu binary is recognized
