### ISSUE TITLE
corfu autocompletion become slow in run-python mode

### ISSUE THREAD

**Issue by yonghuier** [doomemacs/doomemacs#7978]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I am editing a Python script and have `run-python` running in the background for interactive debugging, corfu can completion quickly.

### Current behavior

When I am editing a Python script and have `run-python` running in the background for interactive debugging, I encounter performance issues with autocompletion. Initially, the REPL produces “0__dummy_completion__ 1__dummy_completion__” problems. 

Following the advice from [corfu issue #330](https://github.com/minad/corfu/issues/330), I applied the following configuration:
```
(advice-add 'python-shell-completion-at-point :around
            (lambda (fun &optional arg)
              (cape-wrap-noninterruptible (lambda () (funcall fun arg)))))
```
After this change, the “dummy_completion” characters no longer appear. However, Doom Emacs becomes slow and sometimes very laggy in this scenario.

### Steps to reproduce

1. Open any Python scripts
2. M-x run-python
3. write any code

### System Information

https://pastebin.com/WgCunxj5

**Comment by hlissner** [comment]
Considering `python-shell-completion-at-point` has to talk to the python process every time Corfu tries to present completion candidates, this slowness is unavoidable (and not really a Doom issue). I suggest turning off `corfu-auto` or turning up `corfu-auto-delay`. E.g.

```elisp
;;; Add to $DOOMDIR/config.el

(setq-hook! 'inferior-python-mode-hook 
  corfu-auto nil
  ;; or
  corfu-auto-delay 2.0)
```

Is there any reason to suspect this is exclusively a Doom issue?

**Comment by yonghuier** [comment]
Thank you, I think not using auto-completion might be a good solution. I will do my best to get used to working without it in the future.
