### ISSUE TITLE
`yes-or-n-p` suddenly doesn't accept `spc` as yes 

### ISSUE THREAD

**Issue by saevarb** [doomemacs/doomemacs#7981]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect to be able to use space as `yes` when prompted for `y or n`

### Current behavior

I've been using space to accept `y or n` (`y-or-n-p` prompts) since I started using emacs. After updating to the latest commit, it does not accept space.

### Steps to reproduce

1. Open emacs
2. Evaluate something like `(y-or-n-p "prompt")`
3. Try to accept prompt using the space key
4. Observe that it doesn't work.

### System Information

...

**Comment by saevarb** [comment]
Ah, found the culprit. https://github.com/doomemacs/doomemacs/commit/fe0548e820ff0fb9f3096a7f49847aa3c4e174cc

What is the best way for me to revive this behavior in my own configuration? For now, I've just deleted the line from `doom-ui.el`, but that won't survive future updates.

**Comment by hlissner** [comment]
```elisp
;;; add to $DOOMDIR/config.el
(define-key y-or-n-p-map " " #'y-or-n-p-insert-y)
```

Alternatively, `,` and `.` also work.
