### ISSUE TITLE
doom-docs-mode doesn't quit on q

### ISSUE THREAD

**Issue by krux02** [doomemacs/doomemacs#7985]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I press `q` in doom-docs-mode (activated with e.g. `f1 d m`) pressing `q` should quit the documentation, like it does in helpful-mode for elisp functions (`f1 f`). 

### Current behavior

it shows the following error in `*Messages*` buffer: 

    apply: Buffer is read-only: #<buffer README.org>

### Steps to reproduce

1. Open Emacs (without evil mode)
2. hit `f1 d m RET` in that order to open the documentation for some module
3. try quitting it with `q`

### System Information

https://pastebin.com/q44cQ2Jm

**Comment by hlissner** [comment]
As of a6df88a, `q` is bound in `doom-docs-org-mode`, but only when the buffer is in read-only mode (which it should be, if you're accessing docs via `SPC h d m`). Let me know if it gives you any trouble and I'll reopen it. Thanks for bringing it to my attention!

**Comment by krux02** [comment]
Thanks it works now. There is a second key that I regularly use within emacs that doesn't work in doom-docs yet, it is `g` for refresh. `g` in occur reruns the search for matches, `g` in `compile` reruns the exact same compilation, `g` in `helpful-mode` runs `helpful-update`. `g` in magit runs `magit-refresh`, etc. `g` in doom docs doesn't do anything yet. Personally I can live without that key working as I don't need to refresh the docs that often, but I think it should be bound for consistentcy. Thanks for taking care of this so quickly.
