### ISSUE TITLE
A "none" workspace is created when open project

### ISSUE THREAD

**Issue by nqminhuit** [doomemacs/doomemacs#7986]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

There shouldn't be "none" workspace

### Current behavior

when i start a new emacs instance then open any project, a "none" workspace added by default at index [1]
![image](https://github.com/user-attachments/assets/ffa9e601-84b0-4a38-952a-48a5fe9a5da4)

### Steps to reproduce

1. upgrade doom emacs, here is the change list i received: https://github.com/doomemacs/doomemacs/compare/2c17f719657c46ea37e4846289e951c83409a514...7f3412e3174d3f5bb721a140f67be3a5a055e31d
2. start new emacs
3. open any project
4. press `<SPC><TAB><TAB>`

### System Information

https://gist.github.com/nqminhuit/138e2114f581325363f130a27aec1c78

**Comment by amrit3128** [comment]
I'm also facing this same issue

**Comment by hlissner** [comment]
As of b3bea23 the issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
