### ISSUE TITLE
prog-mode does not allow typing the letter q (using lsp-mode)

### ISSUE THREAD

**Issue by yukiteruamano** [doomemacs/doomemacs#7988]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Hi!

I am currently having a bug with prog-mode using Doom Emacs. The problem is that I can open any code file (I've tried Python, Bash, C/C++) and edit it, but the letter "q" (lowercase) is impossible to type.

The problem (not typing the letter "q") only appears when lsp-mode is active. If I activate (lsp +eglot) the problem disappears.

### Current behavior

I started emacs --debug-init, but I don't see any errors in the console that could give me an idea of ​​what is wrong. If it matters I am using OpenBSD, and the default Doom Emacs configuration works perfectly.

### Steps to reproduce

1.- Open Emacs
2.- Open file (Python, Bash o C/C++ tested) with lsp-mode active
3.- Try write "q" in the file
4.- Fail write "q" other keys work fine. 
5.- "q" work fine in lsp +eglot and standard config. 

### System Information

https://pastebin.com/h9NsqNkS

**Comment by hlissner** [comment]
I can't reproduce this. Please use `C-h k q` to determine what is bound to `q`.

**Comment by yukiteruamano** [comment]
`C-h k q`  show me `evil-record-macro REGISTER`, but this is for `Normal State`, not for `Insert State`. In `Normal State`, q work fine.

**Comment by hlissner** [comment]
Then use `C-h k q` in insert state to see what it's bound to there, or wherever it is that `q` is not behaving as you expect.

**Comment by yukiteruamano** [comment]
Thanks for the suggest! In Insert State `C-h k q` show me `lsp-ui-doc-frame-mode-map q` related with `lsp-ui-doc.el`


![emacs](https://github.com/user-attachments/assets/9d941d1b-3c08-4ed5-88a3-361dd71d2325)

**Comment by hlissner** [comment]
I don't understand why `lsp-ui-doc-frame-mode` is enabled outside of a lsp-ui-doc childframe. Do you have your `$DOOMDIR/config.el` up somewhere I can see it? Maybe you have `(lsp-ui-doc-frame-mode +1)` in your config or similar?

**Comment by yukiteruamano** [comment]
Solved!

The problem is my personal configuration which uses `lsp-ui-doc-frame-mode t`, disabling it makes the problem go away. A change upstream `lsp-ui` causes `q` to be remapped to the described behavior.

Thanks!
