### ISSUE TITLE
Apheleia doesn't respect indent size in prettier config

### ISSUE THREAD

**Issue by johnche** [doomemacs/doomemacs#7998]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

with `(format +onsave)` enabled, i expect the formatter to respect project set indenting for typescript projects. 

The project indent is expected to be 2, set by prettier config.

### Current behavior

When the file gets formatted, formatter sets indent to 4, ignoring both files. The formatter however, respects the other configurations set by prettier config other than indent.

### Steps to reproduce

1. Open emacs
2. Open node project with following prettier config:
```json
{
	"trailingComma": "es5",
	"useTabs": false,
	"semi": true,
	"singleQuote": true,
	"tabWidth": 2
}
```

4. Run formatter on some `.ts` project file (i ran through `+onsave`)

Extra notes:
I have seen (when the formatter fails) that it runs the following command:
`apheleia-npx prettier --stdin-filepath <path-to-project-ts-file> --parser\=typescript --tab-width 4`

Is the last `--tab-width` flag necessary? I believe that it overrides project set configurations. I am not sure whether it comes from doom configurations or apheleia directly

### System Information

https://pastebin.com/jS6eEWNY

**Comment by hlissner** [comment]
Another (Doom-specific) workaround:

```elisp
;;; add to $DOOMDIR/config.el
(after! apheleia-formatters
  (set-formatter! 'prettier
    '("apheleia-npx" "prettier" "--stdin-filepath" filepath
      ;; Ugh, *seriously* prettier?!
      (unless (or (cl-loop for file in '(".prettierrc"
                                         ".prettierrc.json"
                                         ".prettierrc.yml"
                                         ".prettierrc.yaml"
                                         ".prettierrc.json5"
                                         ".prettierrc.js"
                                         "prettier.config.js"
                                         ".prettierrc.mjs"
                                         "prettier.config.mjs"
                                         ".prettierrc.cjs"
                                         "prettier.config.cjs"
                                         ".prettierrc.toml")
                           if (locate-dominating-file default-directory file)
                           return t)
                  (assq 'prettier (+javascript-npm-conf)))
        (apheleia-formatters-js-indent "--use-tabs" "--tab-width")))))
```

**Comment by hlissner** [comment]
Actually, I'll leave this open until a decision is reached upstream. If upstream won't adapt, I'll adapt our `:editor format` module to do the above.

**Comment by johnche** [comment]
I raised an issue upstream: https://github.com/radian-software/apheleia/issues/315

Did some quick copy and paste, but hopefully described the problem well. 

Hopefully they would do something about it. Otherwise, Ill use your suggested fixes until then. I personally think the below example I quoted from you should be sufficient, as I think there is no reason to superimpose extra config flags on a third party abstraction (thats what we have config files for)

```elisp
(after! apheleia-formatters
  (set-formatter! 'prettier
    '("apheleia-npx" "prettier" "--stdin-filepath" filepath)))
```

**Comment by hlissner** [comment]
For the time being, I've incorporated a variant of my first snippet in c0a1b9e, as a stop-gap until either upstream or I come up with a better solution. Thanks for bringing it to my attention, in any case!
