### ISSUE TITLE
Modeline in dired mode is not controled by the modeline config

### ISSUE THREAD

**Issue by JiaweiChenC** [doomemacs/doomemacs#8000]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a dired buffer, I expect the modeline is the same as the modeline I used in other modes. 

### Current behavior

After the latest update, the modeline in dired mode (dirvish mode actually) has a different height compared to other modes and was not controlled by the hide-mode-line-mode (now if I set hide-mode-lime-mode, the mode line will still showup with no words displayed)
<img width="866" alt="image" src="https://github.com/user-attachments/assets/bc087e94-fa55-4655-a1ec-363dfe5a042e">

### Steps to reproduce

1. Open emacs dired mode
2. Active hide-mode-line-mode

### System Information

https://pastebin.com/jc53xuya

**Comment by hlissner** [comment]
I'm aware of this. Dirvish is quite opinionated about the mode-line (something I'll address soon). In the meantime, here is a workaround:

```elisp
;;; add to $DOOMDIR/config.el
(after! dirvish
  (advice-add #'dirvish--setup-mode-line :override #'ignore)
  (setq dirvish-use-mode-line nil))
```

**Comment by hlissner** [comment]
As of d4ad14b and 967586f the two issues should be resolved:

- The mode-line height should match `doom-modeline`'s
- And, if `dirvish-use-mode-line` is `nil` (which is the case if the `:emacs dired` module is enabled without the `+dirvish` flag), Dirvish will use your default mode-line rather than a blank one.

Let me know if it gives you any issues. Thanks for bringing it to my attention!
