### ISSUE TITLE
`wdired-exit` is not bound

### ISSUE THREAD

**Issue by anuvyklack** [doomemacs/doomemacs#8004]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`wdired-exit` should be bound to `Esc` in evil normal state in `wdired-mode`.

### Current behavior

`Esc` is bound to `evil-force-normal-state`, while it should be bound to `wdired-exit` according to `evil-collection-wdired`.

Manually binding
```emacs-lisp
(map! :map wdired-mode-map
  :n "ESC" #'wdired-exit)
```
has no effect either.

### Steps to reproduce

1. `dired-jump`
2. Press `i` to enter `wdired` mode
3. Press `Esc`

### System Information

https://pastebin.com/vxki6AKx

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/34cc0c9d8658ba0906f77bb1b87bce13ed6f9bf4 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
