### ISSUE TITLE
citar-org-roam no longer installed when roam2 is enabled

### ISSUE THREAD

**Issue by pierreaoquadrado** [doomemacs/doomemacs#8008]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When opening an org file, `citar-org-roam` should be loaded.

### Current behavior

Instead of loading `citar-org-roam`, an error is issued:

`progn: Cannot open load file: No such file or directory, citar-org-roam`

It seems that commit 109aa2c changed `modules/tools/biblio/packages.el` to install `citar-org-roam` when the flag `roam`, as opposed to `roam2` on the previous commit.

### Steps to reproduce

1. Open Emacs
2. Try to visit an Org file
3. Org is not loaded because `citar-org-roam` is not loaded.

### System Information

https://gist.github.com/pierreaoquadrado/b4839c753e8ae37c5f7e86acb6725fe5

**Comment by pierreaoquadrado** [comment]
Replacing `roam` for `roam2` on line 13 from `modules/tools/biblio/packages.el` and running a `doom sync` fixed it.

Is `roam2` deprecated?

**Comment by hlissner** [comment]
My bad. I do eventually plan to deprecate `+roam2` (i.e. drop org-roam v1 entirely and move org-roam v2 to `+roam`), but not yet. That particular change snuck into a recent bump commit. As of 41dab49 this should be fixed. Thanks for letting me know!
