### ISSUE TITLE
`Failed to check out: e21e01d4c2` error on `doom upgrade`

### ISSUE THREAD

**Issue by jessy836** [doomemacs/doomemacs#8021]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq),  [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [ ] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I execute `doom upgrade` in terminal or `doom/upgrade` in emacs it should update to the last commit available

### Current behavior

I get following message:

``` emacs-lisp
    Backtrace:
      (error "Failed to check out %s" "e21e01d4c2")
      (or (and (= 0 (car (sh! "git" "reset" "--hard" target-remote))) (equal (cdr (sh! "git" "rev-parse" "HEAD")) ...
      (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-indent-inc...
      (progn (let ((doom-print-level (or nil doom-print-level)) (doom-print-indent (+ (if t (or nil doom-print-ind...
      (if (not (or auto-accept-p (y-or-n-p "Proceed with upgrade?"))) (ignore (doom-print (doom-print--format (doo...
      (cond ((and (null this-rev) (null new-rev)) (error "Failed to get revisions for %s" target-remote)) ((equal ...
      (let ((this-rev (cdr (sh! "git" "rev-parse" "HEAD"))) (new-rev (cdr (sh! "git" "rev-parse" target-remote))))...
      (let (result) (or (= 0 (car (sh! "git" "remote" "add" doom-upgrade-remote doom-upgrade-url))) (error "Failed...
      (unwind-protect (let (result) (or (= 0 (car (sh! "git" "remote" "add" doom-upgrade-remote doom-upgrade-url))...
      (let* ((branch (replace-regexp-in-string "^\\(?:[^/]+/[^/]+/\\)?\\(.+\\)\\(?:~[0-9]+\\)?$" "\\1" (cdr (sh! "...
      (let ((default-directory doom-emacs-dir) process-file-side-effects) (doom-print (doom-print--format (doom-pr...
      (doom-cli-upgrade #s(doom-cli-context (26312 29646 5854 124000) 585967 0 (118 . 12) nil t "doom" nil nil ("d...
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master d4357c173 2024-08-22 16:08:45 -0400
Doom modules  v24.09.0-pre     HEAD -> master d4357c173 2024-08-22 16:08:45 -0400
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240823133438.585967.error
```

Here is the mentioned file with complet backtrace

https://pastebin.com/WmTRR6PA

### Steps to reproduce

`doom upgrade` in cli or `M-x doom/upgrade` in emacs

P.S.

I don't know how mutch this bug is reproductible. I tryed to upgrade doom on an other vm and it worked. I think, I'll just  reinstall doom but I post this issue in case it contain any usefull informations.

### System Information

https://pastebin.com/em7fx48E

**Comment by erkiesken** [comment]
I had the exact same error, but going to the doom folder and doing manual `git pull` fixed it.

**Comment by hlissner** [comment]
I will close this because both of these issues are networking issues, so there's little Doom can do about them, besides improve the error messages (which is already being working on). Thanks for bringing it to my attention in any case!
