### ISSUE TITLE
`doom sync` overeagerly rebuilds on hostname change

### ISSUE THREAD

**Issue by FrederickGeek8** [doomemacs/doomemacs#8024]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When changing networks that inflict a change to `hostname` (bash) AKA `system-name` (elisp), `doom/reload`/`doom sync` should not force a rebuild to installed packages.

### Current behavior

When changing networks, `system-name` can be modified in a minor way. Currently `doom/reload` will require re-building packages. This was introduced in [cff091982e4197db48cd5749a9a0700d47aa9944](https://github.com/doomemacs/doomemacs/blame/0c1c37ad875a15ce8dae628856770af15701a0cf/lisp/cli/sync.el#L81) in the [`lisp/cli/sync.el`](https://github.com/doomemacs/doomemacs/blob/0c1c37ad875a15ce8dae628856770af15701a0cf/lisp/cli/sync.el#L81) file in order to handle configuration migrations between machines or updates to the Emacs version. The commit description indicates that this is a stop-gap solution, but it can be require cumbersome when migrating between different networks.

This interferes with my setup because at my home I have two different routers such that one prescribes a `.lan` hostname and one prescribes `.local` hostname. Although I _might_ be able to change this on the router side, I imagine that this extends to other networks that may be encountered on-the-go.

**Existing workaround**
I saw that this issue was encountered in the past in #7760, where the user was building in a docker environment. As a result, the doom CLI was changed to add the `-B` parameter to `doom sync` to skip the rebuild step for _both_ Emacs version changes and hostname changes.

While this works, it is not canonically accessible (to my knowledge) through `M-x` and even still is disconnected from the common `doom/reload` command. 

**My workaround**
Because hostname changes are common on my machine when using it on my local network, I created the `$DOOMDIR/cli.el` file with the contents:
```elisp
(add-hook! 'doom-before-sync-hook
   (advice-add 'system-name :override
               (lambda ()
                 "fredericks-mbp")))
```
I am not great at elisp, but the purpose of this is snippet to patch `system-name` that is used in the original [`cli.el`](https://github.com/doomemacs/doomemacs/blob/0c1c37ad875a15ce8dae628856770af15701a0cf/lisp/cli/sync.el#L81) to a fixed value. Doing this allows me to transfer networks without issue and do `doom/reload`'s.

**Discussion point**
I know the change to `cli.el` was a stop-gap solution, and detecting changes to the hostname can be important, but is `system-name` the best way to go about this? Is this even a viable solution right now versus not having the `system-name` check be required?

### Steps to reproduce

1. Open Emacs
2. Run `doom/reload` to ensure that your configuration/packages have been built for your current `hostname`.
3. Change your network to one that gives you a different `hostname` (for me, this was `.lan` versus `.local`)
4. Run `doom/reload`
5. You will encounter the "Your system has changed since last sync" warning that requires you to rebuild your packages to precede with your reload.

**Small notes**
I'm not sure exactly when this issue was introduced on my machine, or what the cause was. Around that time I had to get my Macbook repaired (which required a total replacement), and so my machine was migrated via a Time Machine backup. My OS was updated, Emacs was updated, and my Doom Emacs was updated. I believe the Doom Emacs version was not _5 months old_, like the git blame suggests for the introduction of the `system-name` check. It is possible that somehow my network changed a bit, or is struggling to reconsile a new MAC address for my computer. Regardless, I suspect that this issue would not be isolated to my machine specifically, due to the handling in the Doom Emacs code.

### System Information

https://pastebin.com/5bkdZcnJ

**Comment by hlissner** [comment]
I've modified `doom/reload` (and `doom/upgrade`) to supply `-B` to both commands, which should half-resolve your issue.

**Comment by hlissner** [comment]
I've tweaked the heuristic a bit in 80e9263. Unfortunately, `operating-system-release` is too volatile (the user updating their kernel or OS shouldn't affect Elisp bytecode). `system-configuration` is a step in the right direction, so I've settled on a hash of `system-type` (if OS changes), `system-configuration-features` (if the compiled Emacs features have changed), and `doom-local-dir` (in case of username or config location changes) for now, which I hope solves your issue. If that isn't the case, let me know and I'll reopen this. Thanks for bringing it to my attention, in any case!

**Comment by fdeitylink** [comment]
This change has led to Doom prompting to rebuild my packages on every `doom sync` because the hash value returned by `sxhash` does not seem to persist across sessions (as the `sxhash` documentation notes is possible). Would it be fine to not use a hash and just record and compare the "system configuration tuple" directly, or to use MD5 as suggested in #8030?

**Comment by hlissner** [comment]
As of 7f175ab it uses md5. 

> Would it be fine to not use a hash and just record and compare the "system configuration tuple"

I opted not to because I didn't want the heuristic to trigger for folks upgrading from recent versions of Doom (just because the format changed). This is a stopgap solution, in any case; there will be a robust check embedded into our new package manager ([Elpaca](https://github.com/progfolio/elpaca)) when I release v3.0 of Doom's core.
