### ISSUE TITLE
doom/reload exits with command not found: doom

### ISSUE THREAD

**Issue by harry-xm** [doomemacs/doomemacs#8027]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`SPC h r r` runs successfully as it used to be.

### Current behavior

When I type `SPC h r r`, the Comint command exits abnormally.

```
-*- mode: compilation; default-directory: "~/.config/emacs/" -*-
Comint started at Tue Aug 27 11:18:34

doom sync -B -e
zsh:1: command not found: doom

Comint exited abnormally with code 127 at Tue Aug 27 11:18:35
```

### Steps to reproduce

1. Open Emacs
2. Press `SPC h r r`

### System Information

https://pastebin.com/BDHvJa7C

**Comment by hlissner** [comment]
As of a5039c4 this issue should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
