### ISSUE TITLE
rustic-babel failing when rust is installed with nix

### ISSUE THREAD

**Issue by rodfersou** [doomemacs/doomemacs#8029]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I can't use `rustic-babel` when rust is installed with nix

The fix is applied in the master branch: https://github.com/emacs-rustic/rustic/pull/3/files

Can we upgrade rustic or at least apply this change?

### Current behavior

<img width="513" alt="image" src="https://github.com/user-attachments/assets/d6509955-72e7-40a4-becd-bc6c58dcd554">

### Steps to reproduce

To test you can install rust with nix and set this configuration:

```elisp
(setq rustic-babel-default-toolchain nil)
```

### System Information

https://pastebin.com/hg9bFzEH

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/35dd2bb33ced07983e30c03cc7f4b3061089a563 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
