### ISSUE TITLE
TeX-fold-mode doesn't work as expected

### ISSUE THREAD

**Issue by maikol-solis** [doomemacs/doomemacs#8031]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Using LaTeX, I noticed that TeX-fold-mode doesn't work as expected. I attached a dummy example when I pass my cursor above a macro. The only way to unfolded is with `C-c C-o b`

According to the documentation, it should work 

> If you want to make the original text visible again in order to view or edit it, move point sideways onto the placeholder (also called display string) or left-click with the mouse pointer on it. 
> https://www.gnu.org/software/auctex/manual/auctex/Folding.html

https://github.com/user-attachments/assets/c27199c0-b3af-40b0-a99f-d110b9cc3321

However, in doom when you move left or right, you are using the `left-char` and `right-char` commands. 

Therefore, the solution to this is this instruction 

```elisp
(setq! TeX-fold-auto-reveal-commands '(right-char
                                         left-char
                                         (key-binding [left])
                                         (key-binding [right])
                                         backward-char
                                         forward-char
                                         mouse-set-point
                                         pop-to-mark-command
                                         undo))
```

### Current behavior

NA

### Steps to reproduce

1. Open a latex file with TeX-Fold-mode activated. 
2. Pass the cursor over a macro. 

### System Information

https://pastebin.com/iZPzADqx

**Comment by maikol-solis** [comment]
I noticed that for a complete solution, I should add evil movements like `evil-forward-word-begin`, `evil-forward-word-end`, etc. I'm not sure if this is worth it.

**Comment by hlissner** [comment]
Another approach would be `(setq TeX-fold-auto-reveal t)`, but I'm not familiar enough with the mode (or writing latex in Emacs) to know why this isn't the default already.

**Comment by maikol-solis** [comment]
`(setq TeX-fold-auto-reveal t)` does the trick for me. Even I can use the evil motions without any issue. 
 
 And yes, it should be the default. 
 
 Thanks.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/78f8026620a7045014f6d42e5851b8370b6d92b2 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by maikol-solis** [comment]
Thanks Henrik. Awesome as always!
