### ISSUE TITLE
Dired doesn't work as intended without using +dirvish

### ISSUE THREAD

**Issue by vherrmann** [doomemacs/doomemacs#8038]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I open a dired buffer of some directory, open a file A and kill the buffer of file A, I should get back to the dired buffer of the directory.

### Current behavior

Currently the dired buffer of the directory just „vanishes“. If I disable `dirvish-override-dired-mode` it works again as intended.

### Steps to reproduce

1. Open Emacs
2. Open a non-empty directory (with SPC .).
3. Open a file in the dired buffer (with ENTER)
4. Close the buffer of the file (SPC b d)

### System Information

https://pastebin.com/u7B0kKPi

**Comment by hlissner** [comment]
To help me investigate the cause, could you see if this fixes the issue for you?

```elisp
;;; add to $DOOMDIR/config.el
(defadvice! +dired--dirvish-find-entry-a (fn &rest args)
  :around #'dirvish-find-entry-a
  (let ((dirvish-reuse-session t))
    (apply fn args)))
```

**Comment by wgalen** [comment]
I encountered the same difference in behavior, and can confirm that the `defadvice!` suggestion here solves it for me

**Comment by vherrmann** [comment]
I've fixed it for me by disabling dirvish in packages.el. Since my emacs hangs when I try to start it, I'm currently unable to try your fix ^^'.

**Comment by hlissner** [comment]
> I've fixed it for me by disabling dirvish in packages.el. Since my emacs hangs when I try to start it, I'm currently unable to try your fix ^^'.

Whenever you get a chance, see if this helps with hanging with Dirvish:

```elisp
;;; add to $DOOMDIR/config.el
(after! dirvish
  (setq dirvish-attributes (delq 'vc-state dirvish-attributes)))
```

**Comment by vherrmann** [comment]
I should have phrased my previous comment differently. My emacs hangs regardless of enabling dirvish or not.

**Comment by hlissner** [comment]
In that case, see if disabling `:ui vc-gutter` helps with that.

**Comment by vherrmann** [comment]
Yes, that helped. Also the advice works. Thank you!

PS: I will pay you some money

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/1ff37f9fa42b751342552ef42ef403dc41f50896, this should be resolved (at least until I put together a better solution [upstream](https://github.com/hlissner/dirvish)). Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
