### ISSUE TITLE
fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': The requested URL returned error: 502  [Return code: 128]

### ISSUE THREAD

**Issue by davidhaley** [doomemacs/doomemacs#8040]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`doom sync` should work

### Current behavior

fatal: unable to access 'https://git.savannah.gnu.org/git/emacs/nongnu.git/': The requested URL returned error: 502  [Return code: 128]

### Steps to reproduce

`doom sync`

I also tried following the steps here (https://github.com/doomemacs/doomemacs/issues/8003#issuecomment-2322727364):
```
rm -rf $EMACSDIR/.local/straight/repos/melpa/
rm -rf $EMACSDIR/.local/straight/repos/with-editor/
rm -rf $EMACSDIR/.local/straight/repos/transient
rm $EMACSDIR/.local/straight/build-*-cache.el
doom sync -u
```

### System Information

https://gist.github.com/davidhaley/73986250c8fa1802087f4cafea876524

**Comment by muej** [comment]
Looks like there were temporary issues on https://git.savannah.gnu.org/git/emacs/nongnu.git/. I actually had it several times in the past days.
Currently it works again for me.

**Comment by davidhaley** [comment]
Tried again, and it's working. Thank you!

**Comment by hlissner** [comment]
Duplicate of https://github.com/doomemacs/doomemacs/issues/7171
