### ISSUE TITLE
Org-Roam: attempting to create file results in Symbol’s function definition is void: drag-stuff-mode error

### ISSUE THREAD

**Issue by mayersj1** [doomemacs/doomemacs#8041]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I would expect when creating a new org-roam node, that the node gets created

### Current behavior

When I attempt to create a new org-roam node, I'm getting an error "Symbol’s function definition is void: drag-stuff-mode".  From the Messages buffer, I see this info:

Initializing org-roam database...
Clearing removed files...done
Processing modified files... 
File mode specification error: (void-function drag-stuff-mode)
Processing modified files...done
Quit
Symbol’s function definition is void: drag-stuff-mode

This was working before (as of last Friday, 8/30) I ran doom upgrade today.

### Steps to reproduce

1. Open Emacs
2. `'<Spc> <n> <r> <d> <n>'`
3. error message occurs
4. Same error occurs if I try `<Spc> <n> <r> <n>` to create a new node manually

### System Information

https://gist.github.com/mayersj1/779172957e7accb5e2bd6a867f1c9d17

**Comment by hlissner** [comment]
I can't reproduce this. Please [produce a backtrace from the error](https://discourse.doomemacs.org/t/what-is-a-backtrace-how-to-produce-them/85).

**Comment by hlissner** [comment]
In fact, Doom doesn't activate `drag-stuff-mode` anywhere, so this is most likely a private config issue. As of https://github.com/doomemacs/doomemacs/commit/816db4a62addf7ac5e658123ba081069d224d310, `drag-stuff` is no longer installed for Evil users, so you'll need to either:

- Add a `(package! drag-stuff)` to your `$DOOMDIR/packages.el` if you want to continue using it,
- OR remove the code in your `$DOOMDIR/config.el` that activates `drag-stuff-mode`.

**Comment by mayersj1** [comment]
Thanks @hlissner. I'd already seen the commit message where you'd disabled drag-stuff. That made me look at my config.  I found an instance where I'd added an org-mode-hook that included (drag-stuff-mode -1).  I removed that and the issue went away.  Sorry for the inconvenience.
