### ISSUE TITLE
+org-capture-journal-file doesn't use org-directory as its path, instead uses project path

### ISSUE THREAD

**Issue by embeddedpenguin** [doomemacs/doomemacs#8042]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

```
(after! org
  (setq
   org-archive-subtree-default-command 'org-archive-subtree-hierarchical
   org-log-done 'note
   org-time-stamp-custom-formats '("%m/%d/%y %a" . "%m/%d/%y %a %I:%M %p")
   org-display-custom-times t
   org-attach-dir-relative t
   org-link-file-path-type 'relative
   org-directory "~/Documents/notes/org/"
   org-roam-directory "~/Documents/notes/org/"
   org-attach-id-dir ".attach/"
   org-journal-dir "~/Documents/notes/org/"
   +org-capture-journal-file "journal.org"
   org-agenda-files (directory-files-recursively "~/Documents/notes/org/" "\\.org$")
   org-link-file-path-type 'relative
   org-agenda-start-with-follow-mode t
   org-todo-keywords
   '((sequence
      "TODO(t)"
      "BLOCKED(b)"
      "WIP(w)"
      "REVIEW(r)"
      "FLAGGED(f)"
      "INCOMPLETE(i)"
      "|"
      "CLOSED(c)"
      "RESOLVED(R)"
      "DONE(d)"))
   org-todo-keyword-faces
   '(("FLAGGED" . org-warning)
     ("INCOMPLETE" . org-dispatcher-highlight)))
  (org-link-set-parameters "rel" :follow #'browse-url :export #'wvxvw/export-rel-url)
  (set-company-backend!
    'org-mode
    'company-capf 'company-files)
  )
```
In the above snippet, I set my `org-directory` as `~/Documents/notes/org` and set my `+org-capture-journal-file` as `journal.org`. From this, I believe my expected path to the journal should be `~/Documents/notes/org/journal.org`.

```
(setq! org-capture-templates
       '(
         ("g" "Global Templates")
         ("gt" "Todos" entry
          (file+headline +org-capture-todo-file "Inbox")
          "* TODO %?\n%i\n%a" :prepend t)
         ("gn" "Notes" entry
          (file+headline +org-capture-notes-file "Inbox")
          "* %u %?\n%i\n%a" :prepend t)
         ("gj" "Journal" entry
          (file+olp+datetree +org-capture-journal-file)
          "* %U %?\n%i\n%a" :prepend t)))
```
In the above snippet, I set my `org-capture-templates` entry for my journal at `(file+olp+datetree +org-capture-journal-file)`. This makes me think the expected behavior would be to capture journal logs into `~/Documents/notes/org/journal.org`.

### Current behavior

When I started writing this report, I thought it was just hard using a path `~/Documents/notes/journal.org`. I now realize it's using the current project's path somehow...

![image](https://github.com/user-attachments/assets/b4de5d06-1fab-4da8-8ca1-2ce192f37350)

I was in my dotfiles repo (where my doom config is) to write up this report, hit `SPC X g j` (my keybinds are different than the default as seen above) and it used my project's root as the `+org-capture-journal-file` org directory instead of the proper `org-directory` var.

Proof org-directory is still what I set it to: 
![image](https://github.com/user-attachments/assets/17b0aa74-c76c-4070-9341-ef235fffb12b)

### Steps to reproduce

1. open emacs
2. `SPC X g j`
    My default workspace's project root is `~/Documents/notes/`, so when I opened this capture template, it created a journal at `~/Documents/notes/journal.org`
![image](https://github.com/user-attachments/assets/d5ea2b85-09f6-46b2-935f-432a86649c07)

(Ignore the `/storage/Documents...` path. It's symlinked from ~/Documents)

### System Information

https://bpa.st/YDY6I

**Comment by embeddedpenguin** [comment]
I would like to get a stack trace for the capture template loading up, but I'm not sure how to do that with no errors or warnings (because technically nothing is broken :P )

**Comment by hlissner** [comment]
You need to set directory/file variables (like `org-directory`) *before* org loads, so putting them in `(after! org ...)` is setting them too late for `+org-capture-journal-file` to construct a full path from `org-directory`.

**Comment by embeddedpenguin** [comment]
That makes sense. Didn't know that. This didn't solve my issue with +org-capture-journal-file being project base, but hard setting it to its proper place did. I'm guessing it wanting to be project based is something to do with my org agenda or org roam settings. That's ok though. Working now, thanks!

**Comment by hlissner** [comment]
> You need to set directory/file variables (like org-directory) before org loads

To clarify, this applies to `+org-capture-journal-file` as well, e.g.

```elisp
(setq org-directory "~/Documents/notes/org/"
      org-roam-directory "~/Documents/notes/org/"
      org-attach-id-dir ".attach/"
      org-journal-dir "~/Documents/notes/org/"
      +org-capture-journal-file "journal.org")
(after! org
  ...)
```

Then Doom sets `+org-capture-journal-file` to `(expand-file-name +org-capture-journal-file org-directory)` once org loads.

If, somehow, `+org-capture-journal-file` remains as a relative path after org loads, then Org will resolve any capture template you use it with from the current directory of the focused buffer.

**Comment by embeddedpenguin** [comment]
> > You need to set directory/file variables (like org-directory) before org loads
> 
> To clarify, this applies to `+org-capture-journal-file` as well, e.g.
> 
> ```emacs-lisp
> (setq org-directory "~/Documents/notes/org/"
>       org-roam-directory "~/Documents/notes/org/"
>       org-attach-id-dir ".attach/"
>       org-journal-dir "~/Documents/notes/org/"
>       +org-capture-journal-file "journal.org")
> (after! org
>   ...)
> ```
> 
> Then Doom sets `+org-capture-journal-file` to `(expand-file-name +org-capture-journal-file org-directory)` once org loads.
> 
> If, somehow, `+org-capture-journal-file` remains as a relative path after org loads, then Org will resolve any capture template you use it with from the current directory of the focused buffer.

Thanks for this clarification. I was actually losing my mind hunting org-agenda and org-roam variables. I can reproduce this behavior now!
