### ISSUE TITLE
[evil] evil-indent turns off my hl-line-mode

### ISSUE THREAD

**Issue by nqminhuit** [doomemacs/doomemacs#8047]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`hl-line-mode` should still be enabled

![image](https://github.com/user-attachments/assets/43f0aebb-cdce-4352-afa1-350ff1937242)

### Current behavior

`hl-line-mode` was accidentally disabled

![Screenshot_20240905_204319](https://github.com/user-attachments/assets/bf1906b9-6d18-473f-a9f3-1f6348583e0f)

### Steps to reproduce

1. put pointer inside any function
2. press: `= C-M-h` to execute `evil-indent` in the region of that function

### System Information

https://gist.github.com/nqminhuit/fb8d6f46e9add81117bb8e3e77379226

**Comment by hlissner** [comment]
As of 6d9a7e9 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
