### ISSUE TITLE
mu4e update mail command throws error "Cannot open config file '~/.mbsyncrc': No such file or directory"

### ISSUE THREAD

**Issue by Jdogzz** [doomemacs/doomemacs#8048]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

mu4e should be able to update email.

### Current behavior

When I have mu4e update email it throws the error "Cannot open config file '~/.mbsyncrc': No such file or directory". I believe this is connected to the recent change here which now requires a config file:

https://github.com/doomemacs/doomemacs/commit/c6479574e6d324d788e3bc2f6240440010373956

I do have that file as a symlink:

```
> ls -alh ~/
...
lrwxrwxrwx 1 flakeuser users   72 Sep  3 14:18 .mbsyncrc -> /nix/store/xxjwfs0ndwn3n06gmk02pd0qqi3kj8yy-home-manager-files/.mbsyncrc
...
```

This is the way home-manager sets up the mbsyncrc file for my email accounts.

### Steps to reproduce

1. Use home-manager to generate an mbsyncrc file.
2. Open mu4e.
3. Hit `u`

### System Information

https://pastebin.com/2HEHH1NK

**Comment by emenel** [comment]
I had this same issue after updating.

For now I added this to my config based on a reply on Discord:

```
;; add to $DOOMDIR/config.el
(after! mu4e
  (setq mu4e-get-mail-command "mbsync -a"))
```

for reference, i'm on MacOS and XDG_CONFIG_HOME is not set in my env in emacs or in my shell.

**Comment by hlissner** [comment]
With https://github.com/doomemacs/doomemacs/commit/45310f1c3ecbd8a652312bf950e6f43149afcee1, this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
