### ISSUE TITLE
`M-x install-irony server` cannot find

### ISSUE THREAD

**Issue by adam-neeley** [doomemacs/doomemacs#8049]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Irony server should install via `M-x install-irony-server`.

### Current behavior

I'm following to the package instructions for doom's `cc` package and `doom doctor`, but I get the following warning and error (NixOS):
```
-*- mode: compilation; default-directory: "/tmp/build-irony-server-1.6.1/" -*-
Compilation started at Thu Sep  5 11:11:52

cmake -DCMAKE_INSTALL_PREFIX\=/home/adam/.config/emacs/.local/etc/irony-server/  /home/adam/.config/emacs/.local/straight/build-29.4/irony/server && cmake --build . --use-stderr --config Release --target install
CMake Warning at src/CMakeLists.txt:4 (find_package):
  By not providing "FindClang.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Clang", but
  CMake did not find one.

  Could not find a package configuration file provided by "Clang" with any of
  the following names:

    ClangConfig.cmake
    clang-config.cmake

  Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
  "Clang_DIR" to a directory containing one of the above files.  If "Clang"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Error at /nix/store/28s979fhz8d6h1rny3n5zh1ybmby6kjz-cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find LibClang (missing: LIBCLANG_LIBRARY LIBCLANG_INCLUDE_DIR)
Call Stack (most recent call first):
  /nix/store/28s979fhz8d6h1rny3n5zh1ybmby6kjz-cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibClang.cmake:94 (find_package_handle_standard_args)
  src/CMakeLists.txt:28 (find_package)


-- Configuring incomplete, errors occurred!

Compilation exited abnormally with code 1 at Thu Sep  5 11:11:52

```

I installed `libclang`, but this error persists.

Note: In the process of writing this, it seems that installing `irony-server` through nix *and restarting emacs* seems to have done the trick? Yet `doom doctor` still reports:

```
      ! Irony server isn't installed. Run M-x irony-install-server
```

I am willing to submit a PR to update doom`s `cc` package's readme for NixOS users, but I want to make sure I'm not missing something.

### Steps to reproduce

1. Run `M-x install-irony-server`
2. Press enter at the prompt that says something like:
```Install command: cmake -DCMAKE_INSTALL_PREFIX\=/home/adam/.config/emacs/.local/etc/irony-server/  /home/adam/.config/emacs/.local/straight/build-29.4/irony/server && cmake --build . --use-stderr --config Release --target install```

### System Information

https://gist.github.com/adam-neeley/68c44fc35a7571c93587523d72530e7a

**Comment by hlissner** [comment]
I suggest switching to an LSP client. Irony is slated for removal in the coming weeks. 

In any case, the doctor only checks for the irony server installed with `irony-install-server`, not once installed externally, so you can ignore the warning.

**Comment by hlissner** [comment]
I've expedited my plans for irony (and rtags), so as of 1a33838, the two packages have been removed from the cc module. Thanks for bringing this issue to my attention in any case!

**Comment by adam-neeley** [comment]
You are very welcome. I'm a big fan of your software.

-------- Original Message --------
