### ISSUE TITLE
Compiling with LaTeXMk in auctex mode does not revert the PDF buffer automatically.

### ISSUE THREAD

**Issue by dschaehi** [doomemacs/doomemacs#8051]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Compiling with LaTeXMk in auctex mode should revert the PDF buffer automatically.

### Current behavior

After commit 21a252d and even after fix fe54aa4, compiling with LaTeXMk does not automatically revert the PDF buffer, as the `TeX-after-compilation-finished-functions` hook is not activated any more.
I had to add the following to my Doom config file to make the hook work again.
``` elisp
(defun advice-after-TeX-TeX-sentinel (&rest args)
    (unless (TeX-error-report-has-errors-p)
      (run-hook-with-args 'TeX-after-compilation-finished-functions
                          (with-current-buffer TeX-command-buffer
                            (expand-file-name
                             (TeX-active-master (TeX-output-extension)))))))
  (advice-add 'TeX-TeX-sentinel :after #'advice-after-TeX-TeX-sentinel)
```

### Steps to reproduce

Add `(setq-hook! LaTeX-mode TeX-command-default "LaTeXMk")` to `config.el` and compile with `C-c C-a`.

### System Information

https://pastebin.com/mxbTGLqT

**Comment by dschaehi** [comment]
I think the reason is how auctex specifies the formatter for LaTeXMk (https://github.com/emacsmirror/auctex/blob/ef1961483cbdd7ee6d1ccc1e1933f3fd22d50a99/tex.el#L255-L257)
```elisp
    ("LaTeXMk" "latexmk %(latexmk-out) %(file-line-error) %(output-dir) \
%`%(extraopts) %S%(mode)%' %t"
     TeX-run-format nil (LaTeX-mode docTeX-mode) :help "Run LaTeXMk")
```
The chosen formatter `TeX-run-format` does not seem to lead to triggering `TeX-after-compilation-finished-functions`.

**Comment by dschaehi** [comment]
OK, Just replacing `TeX-run-format` with `TeX-run-TeX` seems to be enough to fix the problem, i.e., just add the following to `config.el`:
```elisp 
(add-to-list 'TeX-command-list '("LaTeXMk" "latexmk %(latexmk-out) %(file-line-error) %(output-dir) \
%`%(extraopts) %S%(mode)%' %t"
                                   TeX-run-TeX nil (LaTeX-mode docTeX-mode) :help "Run LaTeXMk"))
```

**Comment by dschaehi** [comment]
They are `LaTeX-mode` and `TeX-LaTeX-sentinel`.

**Comment by hlissner** [comment]
> I highly suspect the main cause is TeX-run-format.

Ah, you're right, [it is](https://github.com/emacs-straight/auctex/blob/08881d08ce4161383b2e5666e5b388e13312188f/tex.el#L8114). I'm curious why this is the default behavior.

Does this work for you?

```elisp
;;; add to $DOOMDIR/config.el
(after! tex
  (setf (nth 2 (assoc "LaTeXMk" TeX-command-list)) #'TeX-run-TeX))
```

**Comment by dschaehi** [comment]
The solution, which is similar to my second fix suggestion (https://github.com/doomemacs/doomemacs/issues/8051#issuecomment-2333388695), does the job of compilation but also throws an error, when you compile your latex file from scratch.
```
Stopping after running "LaTeXMk" 4 times in a row.
LaTeXMk: problems after [0] pages
```
However, once it is compiled and all the auxiliary files are generated, updating and compiling the latex file does not lead to further errors.

I guess there must be a reason why the autex authors use `TeX-run-format` instead of `TeX-run-TeX`. They only forgot to make the former trigger the mentioned hook on successful compilation.
I think for now providing an [advice](https://github.com/doomemacs/doomemacs/issues/8051#issue-2509631173) could be a reasonable (but hacky) solution until there is a change in the upstream.

**Comment by hlissner** [comment]
I've implemented the advice in 79684ad, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by dschaehi** [comment]
Nice. It works well with the newest commit. Thanks for the quick response and for the great work!

**Comment by dschaehi** [comment]
Nice. It works well with the newest commit. Thanks for the quick response and for the great work!

**Comment by mpardalos** [comment]
This issue has re-appeared for me. On `C-c C-a` latexmk runs a few times and then I get `problems after [0] pages` and no update on the pdf preview
