### ISSUE TITLE
Create file fail

### ISSUE THREAD

**Issue by jeasoncc** [doomemacs/doomemacs#8053]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

1. First Step: There had a similar File-Name exist,
2. Second Step:  At this time use  `Space f f ` it will show you that file, but you can't create a file.

Let me show you the case.
1. I create the first file *test1.org*
2. I want to create a  new file *test.org* but it not support
![图片](https://github.com/user-attachments/assets/c6543fb2-5e98-48dd-8d0b-1649ad979da0)

I have to using terminal to create that  FIle **test.org**
![图片](https://github.com/user-attachments/assets/eff075ed-406d-4c15-a70f-a24518c2f759)

### System Information

https://pastebin.com/fCCQ6ZLg

**Comment by hlissner** [comment]
Press `C-p` or `C-k` to "select" the prompt, then press enter to create a file with your current input.

[screencast.webm](https://github.com/user-attachments/assets/ecb355b5-3171-47aa-8ece-931aef091653)

**Comment by jeasoncc** [comment]
It's worked! thanks
