### ISSUE TITLE
Some evil keybinds stopped working. For example, Alt + j, Alt + k, 

### ISSUE THREAD

**Issue by Skullamortis** [doomemacs/doomemacs#8057]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Full "vim" compatible, evil keybinds working.

### Current behavior

Some evil keybinds stopped working recently. For example, the Alt+j (move line down), Alt+k (move line up), on normal mode.

### Steps to reproduce

Just updated and it stopped working. 

### System Information

https://pastebin.com/7MagchXX

**Comment by hlissner** [comment]
This is not a bug and the alt-{j,k} keys you're describing are not Vim keys, they were provided by the drag-stuff package, which was removed in https://github.com/doomemacs/doomemacs/commit/816db4a62addf7ac5e658123ba081069d224d310.

You will need to add the package to your config to restore them.
