### ISSUE TITLE
doom doctor throws error Wrong number of arguments for color-rgb-to-hex

### ISSUE THREAD

**Issue by Jdogzz** [doomemacs/doomemacs#8058]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Running doom doctor should report no errors

### Current behavior

Running doom doctor throws error Wrong number of arguments for color-rgb-to-hex.

Here is the output of doom doctor:
```
❯ ~/.config/emacs/bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Doom's prerequisites...
> Checking for Emacs config conflicts...
> Checking for missing Emacs features...
> Checking for private config conflicts...
> Checking for common environmental issues...
> Checking for stale elc files...
> Checking for problematic git global settings...
> Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: Wrong number of arguments
    Details: (#<subr color-rgb-to-hex> 0)
    Backtrace:
      (color-rgb-to-hex)
      (apply color-rgb-to-hex nil)
      (indent-bars--blend-colors "unspecified-fg" "black" 0.425)
      (indent-bars--main-color #s(indent-bars-style nil nil nil nil indent-bars-face nil nil nil nil))
      (indent-bars--initialize-style #s(indent-bars-style nil nil nil nil indent-bars-face nil nil nil nil))
      (indent-bars-setup)
      (indent-bars-mode 1)
      (if (run-hook-with-args-until-success '+indent-guides-inhibit-functions) nil (indent-bars-mode 1))
      (+indent-guides-init-maybe-h)
      (run-hooks change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
      (apply run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
      (run-mode-hooks org-mode-hook)
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master 9d172f8c2 2024-09-09 18:53:57 -0400
Doom modules  v24.10.0-pre     HEAD -> master 9d172f8c2 2024-09-09 18:53:57 -0400
    ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240909170021.64184.error
```

Here is the extended backtrace: 
[cli.doom.240909170021.64184.error.txt](https://github.com/user-attachments/files/16937732/cli.doom.240909170021.64184.error.txt)

I just updated to the latest doom emacs version and was trying to debug another error like #7041, and when running doom doctor I got the above.

### Steps to reproduce

1. Upgrade to the latest doom emacs
2. Run doom doctor

### System Information

https://pastebin.com/Qs1ZLLG7

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/98e28d801e8acf0047cd9859dc2448a5cee66c21, indent-bars shouldn't activate in CLI sessions, which should resolve this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
