### ISSUE TITLE
Capture abort when capturing a task

### ISSUE THREAD

**Issue by tiagommmelo** [doomemacs/doomemacs#8061]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I use "Space X" to bring the custom templates options, then using one of the pre-defined templates

### Current behavior

The Custom Template options load in the minibuffer just fine. After that, though, if I select any of the options, then it throws the error message below:
`Capture abort: Searching for program: No such file or directory, ispell`

### Steps to reproduce

1. Open emacs
2. Press "Space", then 'X'
3. Press 'T' to select the TODO template
4. Then the error occurs

### System Information

https://pastebin.com/8KVTWxZu

**Comment by hlissner** [comment]
This means you have the `:checker spell` module enabled but none of spelling backends installed (aspell, ispell, hunspell, or enchant), so it falls back to ispell, which is clearly not present on your system. You need to install it via your OS package manager, or one of the other backends as laid out [in the `:checker spell` documentation](https://github.com/doomemacs/doomemacs/blob/master/modules/checkers/spell/README.org#installation).

**Comment by tiagommmelo** [comment]
That solved the issue real quick, thanks!
