### ISSUE TITLE
Setting XDG_CACHE_HOME breaks doom

### ISSUE THREAD

**Issue by rcoacci** [doomemacs/doomemacs#8062]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

- Set the environment variable XDG_CACHE_HOME to an existing directory (e.g. ~/.cache/)
- Run `doom run`
- Doom works as expected.

### Current behavior

```
x There was an unexpected runtime error
  Message: File already exists
  Details: ("File already exists" "/tmp/doom.run/.cache")
  Backtrace:
    (make-symbolic-link "/home/rcoacci/.cache/" "/tmp/doom.run/.cache/")
    (if (file-symlink-p target) nil (make-directory (file-name-directory target) t) (make-symbolic-link xdg-dir target))
    (progn (if (file-symlink-p target) nil (make-directory (file-name-directory target) t) (make-symbolic-link xdg-dir target)))
    (if (file-directory-p xdg-dir) (progn (if (file-symlink-p target) nil (make-directory (file-name-directory target) t) (make-symbolic-link xdg-dir target))))
    (let* ((xdg-dir (doom-path dir)) (target (doom-path tempdir (file-relative-name xdg-dir "~")))) (if (file-directory-p xdg-dir) (progn (if (file-symlink-p target) nil (make-directory (file-name-directory target) t) (make-symbolic...
    (let ((dir (car tail))) (let* ((xdg-dir (doom-path dir)) (target (doom-path tempdir (file-relative-name xdg-dir "~")))) (if (file-directory-p xdg-dir) (progn (if (file-symlink-p target) nil (make-directory (file-name-directory t...
    (while tail (let ((dir (car tail))) (let* ((xdg-dir (doom-path dir)) (target (doom-path tempdir (file-relative-name xdg-dir "~")))) (if (file-directory-p xdg-dir) (progn (if (file-symlink-p target) nil (make-directory (file-name...
    (let ((tail (list (or (getenv "XDG_DATA_HOME") "~/.local/share") (or (getenv "XDG_BIN_HOME") "~/.local/bin") (or (getenv "XDG_CONFIG_HOME") "~/.config") (or (getenv "XDG_CACHE_HOME") "~/.cache")))) (while tail (let ((dir (car ta...
    (let* ((tempdir (doom-path (temporary-file-directory) "doom.run")) (tempemacsdir (doom-path tempdir ".emacs.d"))) (delete-directory tempdir t) (make-directory tempemacsdir t) (let ((tail (list (or (getenv "XDG_DATA_HOME") "~/.lo...
    (if repl? (if input (eval (read input) t) (doom-run-repl context)) (let* ((tempdir (doom-path (temporary-file-directory) "doom.run")) (tempemacsdir (doom-path tempdir ".emacs.d"))) (delete-directory tempdir t) (make-directory te...
    (let ((repl? (cdr (assq 'repl? alist))) (context (cdr (assq 'context alist))) (input (cdr (assq 'input alist))) (args (cdr (assq 'args alist)))) (if repl? (if input (eval (read input) t) (doom-run-repl context)) (let* ((tempdir ...
    ((closure (t) (cli alist) (let ((repl? (cdr (assq 'repl? alist))) (context (cdr (assq 'context alist))) (input (cdr (assq 'input alist))) (args (cdr (assq 'args alist)))) (if repl? (if input (eval (read input) t) (doom-run-repl ...
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master, origin/master, origin/HEAD 4790db644 2024-09-10 15:27:18 -0700
Doom modules  v24.10.0-pre     HEAD -> master, origin/master, origin/HEAD 4790db644 2024-09-10 15:27:18 -0700
  ! Wrote extended backtrace to ~/.config/emacs/.local/state/logs/cli.doom.240910232313.113683.error
```
[doom-error.txt](https://github.com/user-attachments/files/16957106/doom-error.txt)

### Steps to reproduce

1. `$ export XDG_CACHE_HOME=~/.cache`
2. `$ doom run`

### System Information

https://pastebin.com/WwYzcBiL

**Comment by rcoacci** [comment]
Other Doom commands work fine (`doom info`, `doom sync`, etc) only `run` seems to be broken.

**Comment by hlissner** [comment]
I can't reproduce this, and this error doesn't make sense to me. It's complaining that `/tmp/doom.run/.cache` already exists (and isn't a symlink), but `doom run` [deletes `/tmp/doom.run` before recreating it](https://github.com/doomemacs/doomemacs/blob/master/lisp/cli/run.el#L48) every time it runs, but *that* isn't throwing any errors.

Plus, setting `XDG_CONFIG_HOME` to `~/.config` is the same as the default behavior of running `doom run` without having set it, so unless you're quoting it (e.g. `export XDG_CONFIG_HOME="~/.config"`), which would not expand the `~`, this doesn't make sense. Have you omitted any other shell config? Maybe settings for other `XDG_*_HOME` variables?

**Comment by rcoacci** [comment]
I have this consistently on at least two different machines (both Arch if that's relevant). I'll run some more testing and come back. I don't know if you noticed but I added the extended stack trace as "doom-error.txt" right before "Steps to reproduce". One thing I noticed is that if you change XDG_CACHE_HOME to something else (e.g. "/tmp/") the error becomes `(make-symbolic-link "/tmp" "/tmp")` which is even weirder.

**Comment by rcoacci** [comment]
Ok, I think I may have an idea on what's going on.
Doom is installed on `~/.config/emacs` (EMACSDIR) and `~/.config/doom` (DOOMDIR). I've added `~/.config/emacs/bin` to my PATH, and when I start Doom by running `doom run` with XDG_CACHE_HOME set (or any one of XDG_CONFIG_HOME, XDG_DATA_HOME, XDG_BIN_HOME, as I found out later), I get the error. However, running `emacs` directly works. 

So I rg'ed doom for XDG_CACHE_HOME, and got to [this code in cli/run.el](https://github.com/doomemacs/doomemacs/blob/master/lisp/cli/run.el#L54), which seems to try to symlink stuff into some kind of sandbox directory for when doom is not installed on default emacs directories. 

Since my doom install is already inside XDG dirs, maybe it's getting lost and trying to symlink things into themselves? What I fail to understand is why it's triggered only when I set one of the variables.

Perhaps `doom run` should detect if it's actually running from outside XDG dirs before trying to symlink things?

Moving doom outside ~/.config/emacs doesn't change anything.
This are the contents of /tmp/doom.run on a successful run:
```
drwxr-xr-x  4 rcoacci rcoacci 120 set 11 19:33 ./
drwxrwxrwt 34 root    root    760 set 11 19:33 ../
lrwxrwxrwx  1 rcoacci rcoacci  20 set 11 19:33 .cache -> /home/rcoacci/.cache/
lrwxrwxrwx  1 rcoacci rcoacci  21 set 11 19:33 .config -> /home/rcoacci/.config/
drwxr-xr-x  2 rcoacci rcoacci  60 set 11 19:33 .emacs.d/
drwxr-xr-x  2 rcoacci rcoacci  60 set 11 19:33 .local/
```

This are the contents of /tmp/doom.run on a failed run.
```
drwxr-xr-x  4 rcoacci rcoacci 100 set 11 19:34 ./
drwxrwxrwt 34 root    root    760 set 11 19:34 ../
lrwxrwxrwx  1 rcoacci rcoacci  21 set 11 19:34 .config -> /home/rcoacci/.config/
drwxr-xr-x  2 rcoacci rcoacci  40 set 11 19:34 .emacs.d/
drwxr-xr-x  2 rcoacci rcoacci  60 set 11 19:34 .local/
```
Notice the missing cache link.

**Comment by rcoacci** [comment]
Oh, the problem appears to be the use of absolute directories in XDG_* variables.
Setting it to a path inside `~` works.

```
[19:42:57 kuat-linux:~]$ XDG_CACHE_HOME=~/tmp ~/doom/bin/doom run
[19:43:12 kuat-linux:~]$ lla /tmp/doom.run/
total 0
drwxr-xr-x  4 rcoacci rcoacci 120 set 11 19:43 ./
drwxrwxrwt 37 root    root    820 set 11 19:43 ../
lrwxrwxrwx  1 rcoacci rcoacci  21 set 11 19:43 .config -> /home/rcoacci/.config/
drwxr-xr-x  2 rcoacci rcoacci  60 set 11 19:43 .emacs.d/
drwxr-xr-x  2 rcoacci rcoacci  60 set 11 19:43 .local/
lrwxrwxrwx  1 rcoacci rcoacci  17 set 11 19:43 tmp -> /home/rcoacci/tmp/
```

My bet is on `(file-relative-name xdg-dir "~")`, this probably returns the absolute path back if it's absolute or not relative to home, thus trying to symlink /tmp to itself.

**Comment by hlissner** [comment]
> My bet is on (file-relative-name xdg-dir "~"), this probably returns the absolute path back if it's absolute or not relative to home, thus trying to symlink /tmp to itself.

You're right. That's the ticket! I'll have a fix up soon.

**Comment by hlissner** [comment]
With 288b6dc this should finally be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
