### ISSUE TITLE
`cl-subseq: Args out of range: [], 0, -1` error if `C-i` or `C-m` are in `exwm-input-simulation-keys`

### ISSUE THREAD

**Issue by sarg** [doomemacs/doomemacs#8064]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Pressing `C-m` in an X app managed by EXWM throws an error.

### Current behavior

https://github.com/doomemacs/doomemacs/commit/96d7e50f3e1a6b95889f34ae07601af9c8b14fd9 breaks EXWM when C-m is in `exwm-input-simulation-keys`. When pressed in an X app an error is thrown: `error in process filter: cl-subseq: Args out of range: [], 0, -1`. The cause seem to be that `this-single-command-raw-keys` returns empty vector instead of `nil`.

### Steps to reproduce

-

### System Information

-

**Comment by hlissner** [comment]
This should resolved as of https://github.com/doomemacs/doomemacs/commit/14189be77c18bb079f2f37da4147fba192f3efe1. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
