### ISSUE TITLE
Emacs 30.0.91: Could not run doom/set-indent-width

### ISSUE THREAD

**Issue by nqminhuit** [doomemacs/doomemacs#8072]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

the function `doom/set-indent-width` is not useable on anywhere

This is a bug in Emacs 30.0.91 which is not stable, but it might happen when 30.1 releases

### Current behavior

stacktrace of the error:

```elisp
Debugger entered--Lisp error: (void-function editorconfig-set-indentation)
  (editorconfig-set-indentation nil width)
  (let (editorconfig-lisp-use-default-indent) (editorconfig-set-indentation nil width))
  (cond ((require 'editorconfig nil t) (let (editorconfig-lisp-use-default-indent) (editorconfig-set-indentation nil width))) ((require 'dtrt-indent nil t) (let* ((vars (and t (nth 2 (assq major-mode dtrt-indent-hook-mapping-list))))) (if vars (let ((tail (ensure-list vars))) (while tail (let (...) (if ... ...) (set var width) (setq tail ...)))) nil))))
  doom/set-indent-width(4)
  funcall-interactively(doom/set-indent-width 4)
  command-execute(doom/set-indent-width record)
  execute-extended-command(nil "doom/set-indent-width" nil)
  funcall-interactively(execute-extended-command nil "doom/set-indent-width" nil)
  command-execute(execute-extended-command)
```

From the NEWS of Emacs 30, the EditorConfig is now built-in:
https://raw.githubusercontent.com/emacs-mirror/emacs/emacs-30/etc/NEWS

### Steps to reproduce

1. install emacs 30.0.91
2. open any file. E.g., java, sh, yaml, json,...
3. run `doom/set-indent-width` with input = 4 => the error happens

### System Information

https://gist.github.com/nqminhuit/3e7f30c6108fc15afe2ca5c94b8b1d2f

**Comment by real-or-random** [comment]
The builtin editorconfig is apparently different from the packaged variant, and the builtin one lacks the `editorconfig-set-indentation` function, see also  https://github.com/editorconfig/editorconfig-emacs/issues/341.

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/66a2972ebf5fd18cd8adb6eb71a48ec08ce418b8 this should be fixed. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
