### ISSUE TITLE
Mu4e `org-msg` prefix, breaks message compose `(wrong-type-argument number-or-marker-p (4))`

### ISSUE THREAD

**Issue by shroomist** [doomemacs/doomemacs#8073]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

when using mu4e.
When I do `<spc> u` `<C>` it should open a new buffer `*mu4e-draft*`
When I do `<C>` is should open a new buffer with `OrgMsg` draft.

### Current behavior

From `mu4e-main` buffer.
When I do `<spc> u` `<C>` an error occurs.
When I do `<C>` a plain text draft is open. `*mu4e-draft*`

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p (4))
  /=(1 (4))
  (+mu4e-compose-org-msg-handle-toggle (/= 1 (or current-prefix-arg 0)))
  +mu4e-maybe-toggle-org-msg-a()
  apply(+mu4e-maybe-toggle-org-msg-a nil)
  mu4e-compose-new()
  funcall-interactively(mu4e-compose-new)
  command-execute(mu4e-compose-new)
```

### Steps to reproduce

Seems to be related to this change.
https://github.com/doomemacs/doomemacs/commit/f3ad08c4cd2c6d57cf0a49618324f5d06690a35c

Temporary fixing this locally, by redefining defadvice to a previous version:
```elisp
(after! mu4e
  (defadvice! +mu4e-maybe-toggle-org-msg-a (fn &optional toggle-p)
     :around #'mu4e-compose-new
     :around #'mu4e-compose-reply
     :around #'mu4e-compose-forward
     :around #'mu4e-compose-resend
     (interactive "p")
     (+mu4e-compose-org-msg-handle-toggle (/= 1 (or toggle-p 0)))
     (funcall fn)))
```

### System Information

https://pastebin.com/raw/Am04nNEq

**Comment by hlissner** [comment]
As of https://github.com/doomemacs/doomemacs/commit/a78237cc01adeabe0fd4a83ff8b8aca7cb269482 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
