### ISSUE TITLE
edebug doesn't work (emacs on debian on wsl2)

### ISSUE THREAD

**Issue by pjhfggij** [doomemacs/doomemacs#8108]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

running edebug-set-breakpoint with cursor on a defun should cause execution of emacs to stop and let me inspect function when it's run

### Current behavior

nothing happens, function runs as if it wasn't in debug mode

### Steps to reproduce

1. add function like this one to config.el

```elisp
(defun wsl-paste-from-clipboard ()
  "Paste text from Windows clipboard into Emacs."
  (interactive)
  (let ((clipboard-text (string-trim
                         (shell-command-to-string
                          "powershell.exe -NoProfile -Command \"[Console]::OutputEncoding=[Text.UTF8Encoding]::UTF8; Get-Clipboard -Raw\""))))
    (insert clipboard-text)))
```
2. run `edebug-defun` with cursor on defun wsl-paste-from-clipboard
3. run `edebug-set-breakpoint` with cursor on defun wsl-paste-from-clipboard
4. open org-mode buffer and run wsl-paste-from-clipboard
5. see nothing happens

### System Information

https://pastebin.com/kjtcBfTJ

**Comment by hlissner** [comment]
I can't reproduce this on 28.2, 29.4, and 31.0.50. Double check \*Messages\* for errors/warnings, failing that, see if you can reproduce this in vanilla Doom.

**Comment by pjhfggij** [comment]
Sorry, I'm not sure what happened. I've tried to reproduce it now and it worked fine (edebug broke on the function upon invocation). Closed it...
