### ISSUE TITLE
pwsh error on running space-h-r-r on init.el file. Thank you

### ISSUE THREAD

**Issue by yashcgosavi** [doomemacs/doomemacs#8117]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When I do space-h-r-r on init.el I am getting the error of `Powershell 3.0+ is required, but pwsh.exe was not found in your $PATH` however I have added both pwsh.exe (version 7) and powershell.exe in my path.
![Image](https://github.com/user-attachments/assets/0ec7cef0-ce9d-4ee7-8fbf-dd5118ed30a9)
![Image](https://github.com/user-attachments/assets/405c1f65-8a45-4a8d-9ccf-ee66b0423dad)

### Current behavior

I am new to emacs so I dont know how to get the backtrace of the error also I have added the images above then too I am adding them here.
![Image](https://github.com/user-attachments/assets/0ec7cef0-ce9d-4ee7-8fbf-dd5118ed30a9)
![Image](https://github.com/user-attachments/assets/405c1f65-8a45-4a8d-9ccf-ee66b0423dad)

### Steps to reproduce

1. Open Emacs
2. Navigate to init.el in doom.d folder
3. save it using :w 
4. run space-h-r-r command

### System Information

https://pastebin.com/Mq78jtEE

**Comment by hlissner** [comment]
Have you tried running `doom env` then restarting Emacs? It's likely you have an old envvar file with an old value for `PATH`, which doesn't include pwsh.exe's parent directory.

**Comment by yashcgosavi** [comment]
I had to do doom sync from the powershell and then do doom/reload from emacs but dont know why in the tutorial the dude just did doom/reload.

**Comment by yashcgosavi** [comment]
> Have you tried running `doom env` then restarting Emacs? It's likely you have an old envvar file with an old value for `PATH`, which doesn't include pwsh.exe's parent directory.

I didnt tried it saw your message now after doing doom sync. If this issue is reproduced I will try and tag you the results, thank you for trying for helping :)
