### ISSUE TITLE
Meow

### ISSUE THREAD

**Issue by jgarte** [doomemacs/doomemacs#8118]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

[🐈](https://github.com/meow-edit/meow) 

### Current behavior

[🐈](https://github.com/meow-edit/meow) 

### Steps to reproduce

[🐈](https://github.com/meow-edit/meow) 

### System Information

[🐈](https://github.com/meow-edit/meow)

**Comment by hlissner** [comment]
https://github.com/doomemacs/doomemacs/pull/5868#issuecomment-986087379
