### ISSUE TITLE
[Bug] +format/region-or-buffer

### ISSUE THREAD

**Issue by adrianbrink** [doomemacs/doomemacs#8135]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

`SPC c f` should format my current buffer like my `config.el` file.

### Current behavior

I receive the following error in the `*Messages*` buffer.

```
command-execute: Wrong type argument: commandp, +format/region-or-buffer
```

### Steps to reproduce

Start from scratch and it happens.

it seems that this was fixed already in #2349 and #2777 but the same problems appears here.

### System Information

https://pastebin.com/KHbh6Qz8

**Comment by hlissner** [comment]
Judging from your `M-x doom/info`. You do not have the `:editor format` module enabled.

**Comment by adrianbrink** [comment]
amazing. that fixed it
