### ISSUE TITLE
Startup error delayed-warnings-hooks void-variable warning-minimum-log-level because of common-lisp module

### ISSUE THREAD

**Issue by emiltoacs** [doomemacs/doomemacs#8144]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Until Nov 2, 2024 commit 97c0dcc2c328fcc791333e149418c26096043758 doom emacs started properly with `common-lisp` module enable.

### Current behavior

Since commit 8cafbe4408e7d6c68947a2066e5837379d0983c1 starting doom emacs with the `common-lisp` module throws the error

```
display-delayed-warnings: Symbol’s value as variable is void: warning-minimum-log-level
Error in delayed-warnings-hook (display-delayed-warnings): (void-variable warning-minimum-log-level)
```

raw emacs is working without any of the doom customization.

Or you can workaround the problem by commenting out `common-lisp` in your init.el

### Steps to reproduce

 Start a version of Doom Emacs with at least `common-lisp` module since commit 8cafbe4408e7d6c68947a2066e5837379d0983c1

### System Information

https://gist.github.com/emiltoacs/e056ee8759c753e836c3083178c19cb6

**Comment by emiltoacs** [comment]
> I also saw this. I had module common-lisp enabled in init.el. Commenting out that one, and commenting out the configuration for that in my config.el, solved my problem.

Thanks you, commenting out `common-lisp` also solved the issue for me.

**Comment by liaowang11** [comment]
Seems to be related to this typo https://github.com/doomemacs/doomemacs/blob/7531c4298e5decb891d6b48921b320aad18effc2/lisp/lib/autoloads.el#L185
change `pfile` to `file` fix the problem.

**Comment by emiltoacs** [comment]
> Seems to be related to this typo
> 
> [doomemacs/lisp/lib/autoloads.el](https://github.com/doomemacs/doomemacs/blob/7531c4298e5decb891d6b48921b320aad18effc2/lisp/lib/autoloads.el#L185)
> 
> Line 185 in [7531c42](/doomemacs/doomemacs/commit/7531c4298e5decb891d6b48921b320aad18effc2)
>  (replace-match (if (match-end 1) "" pfile) t t)))) 
> 
> change `pfile` to `file` fix the problem.

thanks that's the right fix for common-lisp thanks a lot
