### ISSUE TITLE
(void-variable doom-module-packages-file)

### ISSUE THREAD

**Issue by yaaama** [doomemacs/doomemacs#8149]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I get the error when I run `doom/reload-packages`. I am on the latest version of Doom.

### Current behavior

Raises error:

<details><summary>Backtrace</summary>
<p>

Debugger entered--Lisp error: (void-variable doom-module-packages-file)
  (let ((module-list (cond ((null module-list) (doom-module-list)) ((symbolp module-list) (doom-module-list 'all)) (module-list))) (packages-file doom-module-packages-file) doom-disabled-packages doom-packages) (let ((read-packages (symbol-function #'read-packages))) (ignore read-packages) (let* ((vnew #'(lambda (key) (let ... ... ...))) (old (symbol-function #'read-packages))) (unwind-protect (progn (fset #'read-packages vnew) (let ((doom-context doom-context)) (doom-context-push 'package) (let (...) (if user? ...) (mapc ... module-list) (if user? ...) (nreverse doom-packages)))) (fset #'read-packages old)))))
  (doom-package-list ((:doom)))
  (let ((packages (doom-package-list '((:doom))))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (plist-member --cl-rest-- ':recipe)))) (pin (car (cdr (plist-member --cl-rest-- ':pin))))) (doom--ensure-straight recipe pin)) (doom--ensure-core-packages (seq-filter #'(lambda (%) (eq (plist-get (cdr %) :type) 'core)) packages)))
  (progn (if (and (not doom-inhibit-log) (or (not noninteractive) (<= 2 doom-log-level))) (progn (doom--log 2 "Initializing straight"))) (let ((packages (doom-package-list '((:doom))))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr (plist-member --cl-rest-- ...)))) (pin (car (cdr (plist-member --cl-rest-- ...))))) (doom--ensure-straight recipe pin)) (doom--ensure-core-packages (seq-filter #'(lambda (%) (eq (plist-get ... :type) 'core)) packages))))
  (if (or force-p (null (and (boundp 'straight-recipe-repositories) straight-recipe-repositories))) (progn (if (and (not doom-inhibit-log) (or (not noninteractive) (<= 2 doom-log-level))) (progn (doom--log 2 "Initializing straight"))) (let ((packages (doom-package-list '(...)))) (let* ((--cl-rest-- (alist-get 'straight packages)) (recipe (car (cdr ...))) (pin (car (cdr ...)))) (doom--ensure-straight recipe pin)) (doom--ensure-core-packages (seq-filter #'(lambda (%) (eq ... ...)) packages)))))
  (doom-initialize-core-packages t)
  (doom-initialize-packages t)
  (doom/reload-packages)
  (funcall-interactively doom/reload-packages)
  (command-execute doom/reload-packages)

</p>
</details> 

### Steps to reproduce

Run `doom/reload-packages`.

### System Information

NA

**Comment by hlissner** [comment]
As of 48d0433 this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by ameuret** [comment]
How do I force doom to get this fix when `upgrade` doesn't see it ?

**Comment by hlissner** [comment]
@ameuret The manual way (the snippet below might become outdated someday. Run `doom help upgrade` to find an always-up-to-date version):

```sh
cd ~/.emacs.d
git pull --rebase
doom sync -u
```
