### ISSUE TITLE
Error after upgrade: prin1-to-string: Symbol’s value as variable is void: doom-module-config-file Quit

### ISSUE THREAD

**Issue by alienbogart** [doomemacs/doomemacs#8153]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I expect my init to be tangled correctly with the module +literate

### Current behavior

When I change anything in config.org I get the following message and the init is not tangled:

```
prin1-to-string: Symbol’s value as variable is void: doom-module-config-file
Quit

```

### Steps to reproduce

With the `literate` module, make a change to `config.org`.

### System Information

https://pastebin.com/pkEQJbyg

**Comment by kenranunderscore** [comment]
I'm running into the same thing with no time to debug right now.
The workaround is executing `doom sync`, which tangles the config as well.

**Comment by hlissner** [comment]
As of [bcd399d](https://github.com/doomemacs/doomemacs/commit/bcd399d1c35941990f5da8e593a3464409bc2425) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by kenranunderscore** [comment]
It works for me, thanks a lot Henrik!
