### ISSUE TITLE
Woman manpath is broken if MANPATH env var is set

### ISSUE THREAD

**Issue by rcoacci** [doomemacs/doomemacs#8168]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Asking for some Unix Man page works.

### Current behavior

On some systems, when MANPATH is set, calling `manpath` as is done in https://github.com/doomemacs/doomemacs/blob/7bc39f2c1402794e76ea10b781dfe586fed7253b/modules/config/default/config.el#L65 causes `manpath` to output an extra warning message that breaks `split-string` resulting in a bogus `woman-manpath`.

### Steps to reproduce

1. set MANPATH to something: `export MANPATH=/usr/local/share/man` 
2. Try to read any unix man page using woman in Doom Emacs.
3. Notice that `woman-manpath` variable contains a bogus value like `manpath: warning: $MANPATH set, prepending /etc/man_db.conf`

Adding "-q" (from "quiet") to the call to manpath solves the issue. Here's my current workaround:

```elisp
(after! woman
  ;; The woman-manpath default value does not necessarily match man. If we have
  ;; man available but aren't using it for performance reasons, we can extract
  ;; its manpath.
  (let ((manpath (cond
                  ((executable-find "manpath")
                   (split-string (cdr (doom-call-process "manpath" "-q"))
                                 path-separator t))
                  ((executable-find "man")
                   (split-string (cdr (doom-call-process "man" "--path"))
                                 path-separator t)))))
    (when manpath
      (setq woman-manpath manpath))))
```

### System Information

https://gist.github.com/rcoacci/7b8eb4392bdc10ff365a83a11fe6dcad

**Comment by hlissner** [comment]
As of [9423f6b](https://github.com/doomemacs/doomemacs/commit/9423f6bf95e0bb5e797a94b53a0b50a84680b440) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
