### ISSUE TITLE
use-package: fc8449b -> a6e8564 ERROR: Couldn't collect commit list because: fatal: bad object 16e856418d2ebd053b34e0ab2fda328abeba731c

### ISSUE THREAD

**Issue by kjharcombe** [doomemacs/doomemacs#8175]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Running doom sync in command line runs without any errors

### Current behavior

When running doom sync, I get the following error message and output.

```
- Using Emacs 29.4 @ /usr/local/bin/emacs
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    > (148/154) Re-cloning use-package...
      > Cloning use-package...
    ✓ (148/154) use-package: fc8449b -> a6e8564 [1 commit(s)]
        ERROR: Couldn't collect commit list because: fatal: bad object a6e856418d2ebd053b34e0ab2fda328abeba731c
      
    > Updating recipe repos...-to-date...
    ✓ Updated 1 package(s)
    > Ensuring packages are installed and built...
      > Building use-package...
      ✓ Built 1 package(s)
  > Purging orphaned packages (for the emperor)...
    - Skipping builds
    - Skipping elpa packages
    - Skipping repos
    - Skipping regrafting
    - Skipping native bytecode
  > (Re)building profile in ~/.config/emacs/.local/etc/@/...
    > Deleting old init files...
    > Generating 4 init files...
    > Byte-compiling init.29.4.el...
    ✓ Built /home/kjharcombe/.config/emacs/.local/etc/@/init.29.4.elc
  - Restart Emacs or use 'M-x doom/reload' for changes to take effect
✓ Finished in 10.77834s

```

### Steps to reproduce

1. Install Doom Emacs 
2. Open a new terminal on the system
3. Enter 'doom sync'
4. Error presents itself

### System Information

https://pastebin.com/9UnsEmPg

**Comment by hlissner** [comment]
Already fixed in ef33cb3b63b0c8a1cf669110706175b07c33af0c. Your `M-x doom/info` says you're on https://github.com/doomemacs/doomemacs/commit/7bc39f2c1402794e76ea10b781dfe586fed7253b (which predates the fix). Run `doom upgrade` to fix this.
