### ISSUE TITLE
Module `:lang/sh` overwrites the names of derived modes

### ISSUE THREAD

**Issue by dradetsky** [doomemacs/doomemacs#8178]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Emacs should correctly report that I'm using pkgbuild-mode, not sh-mode (see below).

### Current behavior

I've added `pkgbuild-mode` to my personal config because I use arch. Recently, I noticed that it was showing `sh` as the mode in the modeline instead of `PKGBUILD` (no idea when this started). However, checking `describe-mode` confirmed that it was in fact using pkgbuild-mode, despite referring to it as `sh` in both the modeline and the `describe-mode` help text. Eventually, I traced it to https://github.com/doomemacs/doomemacs/blob/master/modules/lang/sh/config.el#L46. I was able to prevent it from happening and cause `PKGBUILD` to again be displayed as the mode name by adding `(unsetq-hook! 'sh-mode-hook mode-name)`. Presumably this is because pkgbuild-mode is a derived mode of sh-mode, and thus it runs the sh-mode hooks.

On the one hand, this caused me to mistakenly believe that pkgbuild-mode was not being loaded/activated properly, and to waste time trying to debug it, which is suboptimal.

On the other hand, per the module's comment, I recognize the importance of pedantry to the effective operation of doom as a whole, so I'm reluctant to identify this unequivocally as a bug and request it be fixed. But no alternative solution immediately occurs to me. So I figured I'd just write this up for the benefit of the doom developers and let them decide what, if anything, to do.

For the moment, I've added `(setq-hook! 'pkgbuild-mode-hook mode-name "PKGBUILD")` to my config, which addresses the problem for me.

### Steps to reproduce

- add the mode with e.g. `(package! pkgbuild-mode :pin "8c31b24e5979fddf2411456c8957f41f06ae5714")`.
- edit a file named `PKGBUILD`.
- note the name of the mode.
- add `(unsetq-hook! 'sh-mode-hook mode-name)` to config and repeat above steps.

### System Information

no, I've spent enough time on this already

**Comment by dradetsky** [comment]
For reference:

- https://github.com/juergenhoetzel/pkgbuild-mode
- https://github.com/juergenhoetzel/pkgbuild-mode/blob/master/pkgbuild-mode.el#L474

**Comment by dradetsky** [comment]
@hlissner it does in fact fix the issue. And with no loss of pedantry!

**Comment by hlissner** [comment]
As of 94d967490f708bf1333cd54fc6918c9dc39c936d this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
