### ISSUE TITLE
No java completion with +meghanada

### ISSUE THREAD

**Issue by qleguennec** [doomemacs/doomemacs#993]
- OS: gnu/linux (x86_64-pc-linux-gnu)
- Emacs: 26.1.50 (oct. 20, 2018)
- Doom: 2.0.9 (develop 599c95e4a4f1ec0c341c3ce2473a2c312df3de77)
- Graphic display: t (daemon: nil)
- System features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS
- Details:
  ```elisp
  elc count: 0
  uname -a:  Linux hal 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
  modules:   (:feature eval (evil +everywhere) file-templates (lookup +devdocs +docsets) snippets spellcheck (syntax-checker +childframe) workspaces :completion company ivy :ui doom doom-dashboard doom-modeline doom-quit evil-goggles hl-todo nav-flash treemacs (popup +all +defaults) pretty-code vc-gutter vi-tilde-fringe window-select :editor format multiple-cursors parinfer rotate-text :emacs dired ediff electric hideshow imenu term vc :tools editorconfig gist magit :lang cc clojure data emacs-lisp (haskell +intero) (java +meghanada) javascript markdown (org +attach +babel +capture +export +present) php racket rest (sh +fish) web :config literate (default +bindings +snippets +evil-commands))
  packages:  n/a
  exec-path: (~/.local/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin /usr/local/games /usr/games /usr/local/libexec/emacs/26.1.50/x86_64-pc-linux-gnu)
  ```

To reproduce:
- Open a java file
- Try typing `System.out.` => no completion there
- `M-x meghanada-mode`
- `M-x meghanada-mode` => completion works

06cf518af85dec750885309b2a1fc1b25af24ca3 doesn't fix the issue.

**Comment by hlissner** [comment]
Sorry for the late response. Are you still experiencing this issue? Judging from the reproduction steps it sounds like meghanada-mode isn't being activated when you enter java-mode. There is likely an error occurring before it activates. Please check your `*Messages*` buffer for errors or warnings when opening the java file.

**Comment by nwforrer** [comment]
I'm experiencing this same issue. When I open a Java file, I see the "Meghanada indexing" message, and I can see that "meghanada-mode" is active.  However, I see no completion results until I execute "meghanada-mode" twice (to deactivate then reactivate).

I don't see any errors in my *Messages* buffer:
```[yas] Prepared just-in-time loading of snippets successfully.
launch server cmd:java -Djava.net.preferIPv4Stack=true -Dmeghanada.class.completion.matcher=prefix -Dmeghanada.completion.matcher=prefix -Dmeghanada.format=sexp -Dmeghanada.cache.in.project=true -Dmeghanada.skip.build.subprojects=true -Dmeghanada.search.static.method.classes=java.util.Objects,org.junit.Assert -Dmeghanada.javac.arg=-Xlint:all,-processing -Dmeghanada.maven.path=mvn -Xms128m -XX:ReservedCodeCacheSize=240m -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Dfile.encoding=UTF-8 -jar /home/nforrer/.emacs.d/.local/etc/meghanada-server/meghanada-1.0.13.jar -p 0 
Meghanada-Server Starting ...
zstd uncompressing .!home!nforrer!src!rover!ldap-connector!src!main!java!com!redhat!rover!ldap!controller!UsersController.java.~undo-tree~.zst...done
Server waiting client connection ...
meghanada-client process start ...
Please wait. Meghanada indexing ... 
Type "q" to delete help window, M-x scroll-up to scroll help.
Quit
```

**Comment by nwforrer** [comment]
I should note that other features, like importing classes, work fine without needing to disable/enable meghanada-mode. As far as I can tell, only the completions have this problem.

**Comment by hlissner** [comment]
@nwforrer Does invoking code completion manually not work for you? e.g. `C-SPC` (for evil users), `C-;` (for non-evil users), or `M-x company-complete`.

If it doesn't work, that's a bug.

If it does, this is as intended. As-you-type completion is disabled by default. You can enable it by adding the `+auto` flag to the `:completion company` module in `~/.doom.d/init.el`. e.g. `:completion (company +auto)`.

**Comment by nwforrer** [comment]
@hlissner `C-SPC` does not work until I deactivate/reactivate meghanada-mode (that's how I was testing it originally). It does work in other languages, like JavaScript.

**Comment by thegeorgeous** [comment]
@hlissner, the autocomplete seems to work only partially. Spring Boot and Lombok annotations don't come up in the autocomplete.

**Comment by hlissner** [comment]
Hi! Sorry for the late response. Is this still an issue after 5999fee?

**Comment by nkhthe2nd** [comment]
If I type printl, it will autocomplete the entire System.out.println(); It will not if I start typing System...
odd that. It gives me an error in the mini buffer saying 'Please check *meghanada-server-log*'. I'm a little new to doom emacs, so i'm completely lost.

**Comment by nkhthe2nd** [comment]
I can look at the logs through the full buffer list in doom emacs. That's space b B. There was an error related to directory names with spaces in them. It's fixed, but I am still getting errors with completion in .java files. I would like to know if there is supposed to be some extra config for the meghanada, and how to I look up the current config with what comes with doom in the init.el file?

**Comment by Jdogzz** [comment]
@qleguennec Are you still able to reproduce this? Following Henrik's comments in https://github.com/doomemacs/doomemacs/issues/993#issuecomment-472993149 and trying your steps to reproduce, I am not able to reproduce the issue.

https://pastebin.com/rxJXxrAt

**Comment by Jdogzz** [comment]
@hlissner Quick ping that this one might be worth looking into as handled.
